### ISSUE TITLE
RAILIRFinder: Not all MouseMoves are Idle.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1183]
MouseMoves can be scripted to be animations.
http://www.onextrapixel.com/examples/interactive-background/index.html

**Comment by philippebeaudoin** [comment]
Here's a trace that seems to exhibit the problem:
https://drive.google.com/open?id=0B2ZkL2i4sQUnUkJKVlllbEgwemc

From https://xkcd.com/1110/  (I clicked and dragged the mouse around.)

**Comment by benshayden** [comment]
Since I probably won't be around when this needs to be fixed, here's how I think it should be solved.

When handleMouseDragEvents() is deciding whether to ignore a MOUSE_MOVE event, it should first look in event.associatedEvents for a Frame event (tr.e.audits.IMPL_FRAMETIME_TYPE). If the mouse move event directly caused a frame, then create a new Animation ProtoIR instead of an ignored ProtoIR.
The first step, of course, would be to manually look and see if these mouse move events actually have an associated frame event. I assume they would, but you know what they say.

**Comment by benshayden** [comment]
Huh, looks like I fixed this a while ago and forgot to close it.
