### ISSUE TITLE
Refactor PRESUBMIT checks

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1187]
Most of the current PRESUBMIT checks were written for trace-viewer, and they could be better:
 * I think they should use a top-level version of tracing_project
 * I think we should use canned checks where possible (long lines, licenses)
 * We should add in python checks
 * JavaScript style checks should be top-level

I had a ton of interrelated questions on this so I wrote up a doc: https://docs.google.com/a/chromium.org/document/d/1fzdfsbzDDBu_XVnsaSSgPStrj3uwRa90BVzGw4EicAg/edit?usp=sharing

**Comment by anniesullie** [comment]
@petrcermak, any feedback?

**Comment by anniesullie** [comment]
WIP is https://codereview.chromium.org/1277893003

My current list of things to test:
* Long lines
* Licenses required on all files not in excluded paths
* Incorrect files in trace_viewer.gypi
* BUG= on changelists

Anything else I should test?

**Comment by petrcermak** [comment]
Both the document and the patch look good to me. Thanks for all the work!

Petr
