### ISSUE TITLE
have map_traces do gunzip itself

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1193]
js gunzip is crazy slow. on supported os', do the unzip before calling vinn.
this should speed up mapping time.

**Comment by natduca** [comment]
Might be good to do this sooner so we can get a back of the envelope estimate on mappnig speed

**Comment by dstockwell** [comment]
Should we just use python's zlib library to do this on all platforms?

**Comment by natduca** [comment]
sounds awesome. anything is better than gunzip in js!

**Comment by dstockwell** [comment]
It's about a 30% difference.

**Comment by dstockwell** [comment]
Or not... A bunch of my traces were doubly gzipped and the change was causing them to get skipped. With those repaired:

Before:

    real    1m59.346s
    user    57m16.347s
    sys     3m15.536s

After https://codereview.chromium.org/1287193002:

    real    1m57.230s
    user    52m3.563s
    sys     3m22.726s

**Comment by natduca** [comment]
Out of curiosity, hows this perform compared to os.system(gunzip blahblah)?

**Comment by dstockwell** [comment]
Seems about the same:

```
real    1m55.886s
user    52m32.104s
sys     3m17.331s
```

**Comment by natduca** [comment]
python gzip it is!

**Comment by fmeawad** [comment]
Old traces where double gzipped, all new traces are single gizpped
