### ISSUE TITLE
html-side tracing/ paths are 1 level too shallow

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1194]
right now, we map tracing/tracing to / on the devserver. this means that import of /base/foo.html maps to /tracing/tracing/base/foo.html.

I'm thinking we may want to instead have tracing/tracing mapped to /tracing in the global namespace. thus, the example above would be /tracing/base/foo.html.

My thinking here is that this allow tracing to appear as a module to other subsystems like perf_insights or dashboard. Wheras, right now, it appears very ... rootish.

@dj2 @anniesullie @nedn thoughts?

**Comment by anniesullie** [comment]
sgtm

**Comment by dj2** [comment]
https://codereview.chromium.org/1277903004/

**Comment by nedn** [comment]
Oh, I commented the same thin

**Comment by natduca** [comment]
Open till dan lands it :)

**Comment by dj2** [comment]
@nedn not sure what you mean by commented the same thing?

**Comment by nedn** [comment]
Err, I meant my comment in the other doc was basically the same as this proposal. :P
