### ISSUE TITLE
run_d8_tests->run_vinn_tests

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1196]
since we're calling it vinn nao.

probably want to also move the isD8->isVinn in the base.html code

**Comment by natduca** [comment]
@nedn thoughts?

**Comment by nedn** [comment]
LGTM

**Comment by anniesullie** [comment]
You can change the waterfall test name/path here: https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/recipes/catapult.py

**Comment by natduca** [comment]
tracing/run_d8_tests is now fixed, as of f48d444554cb729c34f5a7d92a0685d54ad4e697
