### ISSUE TITLE
Trace Vieweer: some instant events disappear when zooming in

### ISSUE THREAD

**Issue by caseq** [catapult-project/catapult#1200]
Some instant events disappear from trace viewer's flame chart when zoomed in and will reappear again when zoomed out. See video for details:

https://drive.google.com/file/d/0B_yi9xtujhXSMU1iZTdlWnFkRkk/view?usp=sharing

Trace (look for CaptureFrame instant events in the browser):

https://drive.google.com/a/chromium.org/file/d/0B_yi9xtujhXScDZlTjJiWDRVU2M/view?usp=sharing

**Comment by yuhao** [comment]
I guess this is a JS precision issue?

**Comment by benshayden** [comment]
Duplicate of #366 ?
