### ISSUE TITLE
perf_insights/bin/map_traces_locally script is not working

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1201]
It's due to 2 bugs:
1) Naming conflict: the build module in perf_insights/ conflicts with toplevel/build module.
2) Duplicate source_path which lead to failure in loading examples/map_process_count.html failure.

**Comment by natduca** [comment]
Fix coming shortly.

**Comment by anniesullie** [comment]
B..

**Comment by natduca** [comment]
Fixed, a6e18a918e0e9dff2aaa8b037757173d1e387140
