### ISSUE TITLE
Associated Events View aka Critical Path View

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1202]
The TimelineTrackView renders ThreadSlices in threads in horizontal tracks. This makes it difficult to follow FlowEvents and the flow of execution and causation -- the user must scroll up and down between processes and threads, which taxes their working memory and makes it difficult to understand the data displayed, let alone see patterns and gain insight into how Chrome works.

The Associated Events View would make it easier to follow the flow of execution by disregarding threads and processes, and instead packing all of the events that are associated with an IR together vertically in a way that made it unnecessary to scroll vertically. This will unburden the user's working memory and facilitate understanding and eventually insight.

When speculative and other non-critical FlowEvents are filtered out of the associated events, then it reduces to a Critical Path View. Since there should be only 1 critical path, this view should be 1-dimensional since there should not be critical work being done on more than 1 thread at once. When the CPV is 1-dimensional, then it can be stacked with other CPVs for other IRs, and visually compared at a single glance. This would leverage the human brain's excellent visual pattern matching systems to find patterns in IRs' critical paths, instead of requiring large amounts of code to help us find them. Once a human brain finds a critical path pattern, then it can more easily be translated into code that can run on thousands of traces.

There are some significant differences between how the AEV can be rendered versus how the existing track system works.
First, the AEV requires no heading. The vertical position of a ThreadSlice in an AEV is meaningless, whereas the vertical position of a ThreadSlice in the TimelineTrackView indicates its thread and subSlice depth in its ThreadSlice hierarchy in that thread.
Second, ThreadSlice hierarchies in an AEV are boxed and the boxes are bin-packed to reduce vertical height and the need for scrolling.

https://codereview.chromium.org/1278593002

**Comment by natduca** [comment]
Not sure we need this for PI-alpha. 1.0 yes,

**Comment by paulirish** [comment]
Screenshot: 
![image](https://cloud.githubusercontent.com/assets/39191/9397068/f6d9fa90-474d-11e5-8f86-f388c43a746c.png)

**Comment by benshayden** [comment]
@zeptonaut had a great idea that might help address some of the concerns about duplicating UI and code: a button!

UI proposal:
In single-interaction-record-sub-view, the 'Focus on associated events' button would switch the entire timeline-track-view into a new thread-free mode. It would only display events in a given EventSet, rather than the entire model. It would bin-pack them using a new algorithm to minimize both flow event absolute length and overall vertical height. The left-side headers would be hidden. You would still be able to select events and navigate using the mouse as currently. The analysis panel might navigate away from the single-interaction-record-sub-view. A giant button would appear in the top-controls to exit the looking glass back to viewing the entire model.

Intermediate UI proposal:
In single-interaction-record-sub-view, the 'Focus on associated threads' button would raise the tracks for a given set of threads up to the top of the timeline-track-view. Nothing would be hidden. A button might be added to the top-controls to restore the default vertical position of all affected thread tracks, or separate buttons might be used in each thread track's header or right-click context menu.

@natduca @dj2 Thoughts?

**Comment by natduca** [comment]
We would still want to use the track view in the new ui mode. The main issue with your first patch was that you weren't reusing code, you'd written completely new code.

**Comment by natduca** [comment]
Gonna remove the RAIL and M-label on this, this is squarely in the overall viewing space.

**Comment by natduca** [comment]
Closing in favor of the new overhaul bug
