### ISSUE TITLE
Code review BUG= links point to ancient crbugs

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1203]
E.g. https://codereview.chromium.org/1279933002/ links to https://code.google.com/p/chromium/issues/detail?id=1182

**Comment by dj2** [comment]
Where do you see the link to chromium? That just says BUG=#xxxx for me and doesn't link anywhere?

**Comment by dj2** [comment]
Ah, I see, you're using the non-deprecated UI whereas the old one doesn't do that. I think that's a bug against rietveld as the new UI is doing something strange.

**Comment by anniesullie** [comment]
This was fixed in the new rietveld UI
