### ISSUE TITLE
map_traces* needs unit test coverage

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1208]
Was implemented in a hurry. Haz no tests.

Status: still needing tests:
* map_runner: needs tests
* local_directory_corpus_driver: needs smoketest

Done:
* map_traces: has tests
* perf_insights_examples: has tests

**Comment by natduca** [comment]
I'll take this if nobody else gets to it before me.

**Comment by natduca** [comment]
@dstockwell is there a chance you could throw together a smoke test of map_runner? I'd just pass in a fake/stub of the actual map_single_trace function, and use in_memory_trace_handle so you don't have to deal with actual real directories either.

**Comment by dj2** [comment]
Does this need to block alpha?

**Comment by natduca** [comment]
Good enough. Closing.
