### ISSUE TITLE
run_tests devserver has fixed portnumber

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1209]
Means you can't run_tests when devserver is running. And, in fact, run_tests fails if you do, and the script leaves a still-running browser instance.

The run_tests version should probably figure out its portnumber automatically during bind.

**Comment by natduca** [comment]
@anniesullie can you poke at this?

**Comment by anniesullie** [comment]
Taking a look now...

**Comment by anniesullie** [comment]
Put up a bandaid fix in https://codereview.chromium.org/1279643003/ but wanted a review before submitting because I'm not sure how surprising it will be to have the port number change if it's already in use.
