### ISSUE TITLE
Update slave scripts post-directory-overhaul

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1213]
As part of #1122, we've moved a bunch of our run_ scripts around. I left behind stub files so that the waterfalls still work, because I don't have the slave scripts checked out.

Can someone update the slaves and remove the stub files? git grep anniesullie will find them all. :)

**Comment by natduca** [comment]
@nedn @anniesullie

**Comment by nedn** [comment]
@dave-2 , can you help?

**Comment by anniesullie** [comment]
https://codereview.chromium.org/1273773007/ and https://codereview.chromium.org/1281253002/ out for review should fix this.
