### ISSUE TITLE
Make Model import less console.log-chatty

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1217]
Model import is super chatty. As a result, when you map a bunch of measurmt traces, all you see is minor import issues:

[       OK ] rail_expectations.json (491 ms)
[ RUN      ] reload_mobile_HN_webapp.json
Warning: Unrecognized metadata name: overhead
Warning: Unrecognized event phase: R (navigationStart)
Warning: Titles do not match. Title is LayerTreeImpl::UpdateDrawProperties::UpdateTiles in openSlice, and is LayerTreeImpl::UpdateTilePriorities in endSlice
Warning: At 494014072431, no slice named RendererSchedulerIdlePeriod was open.

[  FAILED  ] reload_mobile_HN_webapp.json (1043 ms)
[ RUN      ] search_nojank_60fps_m43_n5.json
Warning: Titles do not match. Title is LayerTreeImpl::UpdateDrawProperties::UpdateTiles in openSlice, and is LayerTreeImpl::UpdateTilePriorities in endSlice
Warning: Unrecognized metadata name: overhead
Warning: At 22950946505, no slice named RendererSchedulerIdlePeriod was open.
Warning: Different phases of LatencyInfo.Flow provided values for argument step. The last provided value will be used.
Warning: Found flow phase t for id: 0x300000053 but no flow start found.

@dj2 can you poke at this if you've got some free time? Ideally, we'd only see showstopper stuff get logged to the console, at least in deep reporting mode.

**Comment by dj2** [comment]
Disable warning logging when running headless:  https://codereview.chromium.org/1280333003
