### ISSUE TITLE
map_function_side_panel overflow:auto doesn't seem to work in X direction

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1218]
The map_function_side_panel can get quite large, because it shows the map result in a generic object view. I have overflow:auto set in the logical place, but it doesn't actually seem to get X scrolling.

I tend to think there's something set up wrong in the flexbox containment hierarchy.

To repro:
http://127.0.0.1:8009/perf_insights_examples/perf_insights_viewer.html#/perf_insights/test_data/googlemaps_ipc_newbinding.html

Result:
![image](https://cloud.githubusercontent.com/assets/412396/9169204/5d75963e-3f0f-11e5-93b5-b524d952eab2.png)

Side panel shouldn't get so crazily big.

**Comment by natduca** [comment]
@nedn this might be useful for you...

**Comment by dj2** [comment]
I'm not sure how to repro this. Did you open the file with trace-viewer or with perf-insights? The link above goes to perf-insights?
