### ISSUE TITLE
Test systrace after large file migration

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1223]
https://codereview.chromium.org/1283543006 may have broken systrace. Zhen, can you test it out and help triage what needs to be fixed?

**Comment by wangzhen127** [comment]
Fixes by dsinclair:
https://android-review.googlesource.com/#/c/166982/
https://android-review.googlesource.com/#/c/167260/

**Comment by dj2** [comment]
With https://android-review.googlesource.com/#/c/167490/ systrace should be up to ToT. Closing this bug as everything due to us moving stuff around is fixed.
