### ISSUE TITLE
Test adb_profile_chrome after large file migration

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1224]
https://codereview.chromium.org/1283543006 may have broken paths for adb_profile_chrome. Zhen, can you test it out and help triage what needs to be fixed?

**Comment by wangzhen127** [comment]
Are Catapult changes automatically rolled to Chromium src? If not, who is rolling it? adb_profile_chrome may break when the changes are rolled, but not before.

**Comment by anniesullie** [comment]
We roll DEPS manually. It would be great to be able to roll DEPS without breaking it though. How do we test?

**Comment by wangzhen127** [comment]
Chrome src/tools/profile_chrome/run_tests runs unit tests for adb_profile_chrome. But I don't think it has test to use trace2html.

We just need to update https://code.google.com/p/chromium/codesearch#chromium/src/tools/profile_chrome/trace_packager.py&q=tracing.build&l=21
to "tracing.tracing_build" after the DEP roll.

Let me know after it is rolled manually. I will then update accordingly for adb_profile_chrome

**Comment by natduca** [comment]
Deps rolled, should we bump priority on this?

**Comment by anniesullie** [comment]
Yep, sorry about that! Zhen, can you take this?

**Comment by wangzhen127** [comment]
Should be fixed by https://codereview.chromium.org/1310703002/.
