### ISSUE TITLE
Port telemetry's smoothness metrics to javascript 

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1228]
Moving forward, we would want all of our timeline based metrics to be written in javascript. This allows telemetry to reuse trace parsing logic of the tracing project & allows the chrome://tracing UI to have these metrics available.

(https://code.google.com/p/chromium/issues/detail?id=518960)

**Comment by nedn** [comment]
Won't fix because we may just use Rails' metrics to replace legacy smoothness.

**Comment by benshayden** [comment]
To clarify, ResponsivenessMetric does use the same discrepancy algorithm for the smoothness metric, and will use the same checkerboarding algorithm.
