### ISSUE TITLE
Lets find some traces that have bad IR coverage

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1232]
Step 1.
ir_coverage.html - has coverage info
hook that up to wr.html

Step 2.
run map_traces using that modified wr. Use jq or somesuch to find problematic traces.
corpuses to use: hand traces, measuremt corpus, bulk reports dump [ill send you a link], and windows deep reports dump [ill send you a link]

https://github.com/natduca/measurmt-traces

Then we can file bugs and maybe mark this closed.

**Comment by natduca** [comment]
This is our GoodFirstBug for @vmpstr to get going

**Comment by natduca** [comment]
So this bug seems to be slow to progress. How can we make some specific next steps here to drive things forward?

**Comment by vmpstr** [comment]
That sounds good, I'll close this and file specific bugs that outline the steps needed for this.
