### ISSUE TITLE
[trace-viewer] Stack Sampling Summary view using a Tree View + Call Stacks

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1233]
Historically, the stack samples summary view was not in use because we combined the stack samples into slices to construct what would be a normal slice representation (i.e. sync slices hierarchy as described in the #622). This construction was confusing more than helpful as it it did not come from real trace events.

The second attempt was to use a sunburst chart in the Analysis panel, which at hindsight seemed like a good idea, but practically, but again it was confusing as it did not allow for any easy association and debugging.

The Suggestion is to have a Tree View, the tree view will represent the slices in a top-down as well as a bottom up view. For each selection on the Tree view, the Call Stacks part will display all the possible call stacks leading to the selected node in the tree.
A prototype taken form @paulirish, as follow:
![stacksamplessummaryprototype](https://cloud.githubusercontent.com/assets/1760798/9207350/ebe26dbc-4021-11e5-9f96-19f79b031e14.png)

A sample Implementation of the Tree View part as follow:
![prototypeimplementation](https://cloud.githubusercontent.com/assets/1760798/9207363/0831c152-4022-11e5-997e-73fe14a95d68.png)
(The code for that prototype can be found <a href="https://codereview.appspot.com/251240043/">here.</a> which was based on an older version of trace-viewer.

Challenges (some of these challenges might already have been addressed):
<ul>
<li>We need to transform Stack Samples transformed into a Tree. Where each node in the tree represents a Stack Frame with a parent, set of children and a samples count. The Tree should be accessible by any visualization (for example, can be accessed by the Tree View as well as the Sunburst)
<li>Split all data specific code from the current sunburst implementation and make it work Top-Down as well as Bottom Up.
<li>We need to generalize the tab system in the analysis view to allow for sub tabs.
<li>Construct the visualization needed for the Call Stacks.
</ul>

**Comment by dj2** [comment]
The removal of the sunburst and addition of a tree-view have now landed.

Currently the tree-view only displays in a bottom-up fashion. If we'd like top-down, we can file a separate bug to add.

I'm not sure I understand what the callstacks section is, what about closing this bug as complete and then if we decide we want callstacks we can open a new bug to track?

**Comment by fmeawad** [comment]
The call stacks is what appears on the right in the original bug. Which when selecting a tree node, would display all call stacks that can lead to that node.

Closing the bug. I agree that we should file separate bugs for call stacks and top-down.
