### ISSUE TITLE
Make a corpus_driver that connects to perfinsights appengine instance

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1234]
map_traces is set up so that it gets its traces via a corpus driver. We currently only have a local directory corpus driver, but we probably want to add a corpus driver that connects to the actual deep reports server directly.

Design doc: https://docs.google.com/document/d/1nx9LQe2Ee0nGxr_Ja1KuRwG-3oBSvN2ZH030_SXd3Ho/edit

**Comment by dj2** [comment]
I don't think this needs to block Alpha. We're still working off local directories which I think will work for the Alpha. Moving the milestone to V1.

**Comment by philippebeaudoin** [comment]
I've been looking at this a little, so taking ownership. I think I can make progress here, but probably not in the Alpha timeframe. I support punting to V1.

**Comment by natduca** [comment]
I posted a design doc on how to do this, it is now linked from the top of the bug.

**Comment by simonhatch** [comment]
I'm wrapping up the AppEngine instance for Bulk Reports, I'll help Philippe on this.

**Comment by benshayden** [comment]
What about Drive folders?

Are slow reports going to be on the same server as deep reports?

**Comment by simonhatch** [comment]
I'm guessing drive folders would be a new corpus driver?

Currently the Slow Reports appengine instance is pretty much the perf insights server + a cron job to sync traces from the crash backend.

**Comment by dj2** [comment]
Yea, drive folders are a different corpus and would get their own driver. If we don't have one, and drive folders are something we want to support, we should file a bug to track it separately.

**Comment by simonhatch** [comment]
Added a while ago.
