### ISSUE TITLE
Contributing guide doesn't say how to do development within chromium/third_party

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1236]
A lot of folks have catapult in third party when they come to us. So then they think they have to git clone to somewhere else.

Iirw, there's a simple set of scripts you can do to change over. Either by adding a new origin or removing the old one and using the new one [I forget if gclient sync works in that case].

Can we add steps there? Old trace-viewer contributing had stuff for this.

**Comment by natduca** [comment]
@anniesullie @dj2

**Comment by anniesullie** [comment]
Sorry I missed this, it should definitely be there!

Is this still accurate? https://github.com/google/trace-viewer/wiki/Contributing/283c0365326003694c6b685704f889880cc3c000#contributing-from-a-chromium-checkout

**Comment by natduca** [comment]
mmmhm!

**Comment by anniesullie** [comment]
Added some updates pulled from that page to https://codereview.chromium.org/1287873003/
