### ISSUE TITLE
Count long idle tasks

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1242]
If there's a task > 75ms in an Idle IR, then it could probabalistically impact the pain of a subsequent Response. If a site consistently schedules long idle tasks which inconsistently impact Responses, then we can surface a stronger signal of that bad behavior by defining it to be pain on the Idle, instead of leaving Idle pain undefined. This could also let us remove the long task alerts by folding that information into the RAIL schema.

**Comment by philippebeaudoin** [comment]
Stealing this from you Ben. Hopefully I'll be done before you're back. :)

**Comment by philippebeaudoin** [comment]
No progress done here, not expecting to work on it. Dropping.

**Comment by tdresser** [comment]
This raises a few interesting questions.

If a page consistently runs over their idle budget, but it never causes a response to be delayed, is it causing user pain?

If the page has a bunch of idle tasks, some of which are 60ms and some of which are 6000ms, but only the 60ms idle tasks cause responses to be delayed, is that worse than a page which only has 60ms idle tasks?

It seems like there's going to be some ambiguity here.

**Comment by benshayden** [comment]
Good points, thanks!

Nat and I were talking about this earlier today. We still don't have any clear ideas, but one observation that was made was that long idle tasks are not directly painful, as you say, but they are hazards that would cause pain if the user started interacting during them. So, a hazard is probabilistic pain, it might sometimes actually cause pain, but the hazard should be removed even if it hasn't been observed to cause actual pain. This concept of a hazard could also be used to describe memory consumption: using all of the memory is not a problem until the user tries to do something that would require memory. Using all of the memory might sometimes actually cause thrashing and OOM, but we should reduce memory consumption even before we observe thrashing and OOM.

Long tasks are a hazard during Animations as well as Idle, since users can click buttons during some Animations. Search for [lady gaga] on mobile, click the knowledge expando, try to click the back arrow while she animates in.

If a 74ms idle task (so it isn't a "long" task) delays a Response by 74ms, then it would theoretically have an insignificant impact on the Response's comfort score, depending on the subtype. Hm. That would significantly impact Scroll Responses. We could smooth out that transition from "short" task to "long" task with a sigmoid transfer function, so that 8ms tasks are perfectly "short", 75ms tasks are perfectly "long", and durations between 8 and 75ms have some scalar length score that depends on the comfort functions of the subtypes of Responses that those long tasks could impact. That might be unnecessarily complicated, or not complex enough. :-P

Nat likes to draw a cube of 3 kinds of scores: Responsiveness, Efficiency, and either Hazards or Memory. If you want, then you could summarize them by taking the distance from the origin to a 3d
point (responsiveness, efficiency, hazards), or some weighted average or something like that. You could also have more than 3 dimensions, but 3 is a magic number for our meat-brains.

So, yes, there's a lot of ambiguity around how to frame RAIL scores right now, and long idle tasks are one of the many thorns. If you have any ideas that might cut the gordian knot, please speak up!

**Comment by tdresser** [comment]
Could there exist a page with many hazards, but no user pain?

The web developer has more information than we do - could they identify a situation in which a long running idle task wouldn't cause user pain? If a developer could do this, should those long running tasks impact their rail score?

I think it would probably be reasonable to say that long idle tasks that have no negative user impact do still negatively impact the rail score, as developers shouldn't be using requestIdleCallback for those tasks.

The difference between long idle tasks and high memory usage is that the developer can have pretty good knowledge of the impact of long idle tasks, but they don't have good knowledge regarding the impact of high memory usage.

The requestIdleCallback API constrains how we're able to score idle callbacks. If a developer runs within the allocated time, we can't reasonably penalize them. I can imagine a world where we try to predict what's going to happen next (e.g., the user is going to start to scroll in 10ms), and give a different amount of idle time depending on our prediction (the scheduler already does some of this scary prediction). I'm not too fond of that complexity though.

**Comment by benshayden** [comment]
I think I agree that pain-free long idle tasks should be penalized. Another reason why is that those long tasks could impact other tabs or apps by hogging a cpu, like how memory consumption can impact other tabs or apps.

Yeah, I wasn't really a fan of scoring idle task length, either. So our recommendation for Scroll Response comfort sort of conflicts with our long idle task recommendation. Good to keep in mind, definitely **a** problem, probably not on our top 10 problems.

I'm leery of trying to think of times when the developer might know that a long idle task would not cause pain. Maybe it's my college Agile training showing, but I think I'd rather start with the simplicity of the original RAIL proposal and only take on complexity when a specific and important concern requires it.

Speaking of simplification, I'm still not entirely sure that "hazards" need to be as high-profile as basic responsiveness. [Using requestIdleCallback](https://developers.google.com/web/updates/2015/08/using-requestidlecallback?hl=en) mentions that it can help pages be more "efficient" from a scheduling point of view, so maybe the "efficiency" RAIL sub-score could be reframed as a combination of battery efficiency, memory efficiency, bandwidth efficiency, and scheduling efficiency? Long idle tasks can impact scheduling inefficiency, as could load resource ordering, and browser scheduler inefficiency. "Efficiency" has always felt to me like a sufficiently broad term that it could contain a lot more than just battery efficiency. WDYT?

**Comment by natduca** [comment]
Does it help if we think of "railscore === perceptualBlend(responsivenessScore, hazardScore, ... otherPrimaryScores)"? Imagine perceptualBlend is some weighted blending that makes lower scores dominate. In a page with real responsiveness problems due to long tasks, but no hazards,, then the repsonsiveness score would be low and the hazard high, but due to the blend function, the overall score would trend lower, which is what we want. But, if a page had hazards, then the hazard score would be low, responsiveness high, and the final perceptual score would tend toward low due to hazard.

It might even be that a long idle task penalty should have about the same penalty on hazardScore as a missed response. E.g if you have a long idle task of 170ms, then that could have the same score as a response of 170ms in duration.

Food for thought.

**Comment by benshayden** [comment]
I think we already have that perceptualBlend function?
[weightedAverage2](https://github.com/catapult-project/catapult/blob/6fe1e1ac36ca12a14225df881ac7b3551ee9fbec/tracing/tracing/extras/rail/rail_interaction_record.html#L180) and [RAILScore](https://github.com/catapult-project/catapult/blob/6fe1e1ac36ca12a14225df881ac7b3551ee9fbec/tracing/tracing/extras/rail/rail_score.html), though they might need to be refactored a bit if you want to surface overall sub-scores like an overall responsiveness metric and an overall efficiency metric etc. And they aren't grounded in psychophysical research like the Response comfort histograms will be. But I think they encapsulate the weighting you're looking for?

I was more trying to figure out how to structurally combine metrics in order to make individual RAIL scores explainable (or more self-explaining) as auto-generated documents that answer the System Health questions "How responsive and efficient is Chrome?" and "Why is it not perfectly responsive and efficient?".

Maybe I should write a design doc exploring different ways to frame and structure combined scores, after we compile a list of all of the metrics that we might want to combine?

**Comment by tdresser** [comment]
> Yeah, I wasn't really a fan of scoring idle task length, either. So our recommendation for Scroll Response comfort sort of conflicts with our long idle task recommendation. Good to keep in mind, definitely a problem, probably not on our top 10 problems.

I may be forgetting what conclusion we came to on that. I thought we'd decided something along the lines of allowing a 66ms response time for scroll response, 50ms of which is potentially taken up by idle time, so you get 16ms for your actual scroll response work.

I didn't see a conclusion drawn particularly clearly anywhere in #1798 though.

> I'm leery of trying to think of times when the developer might know that a long idle task would not cause pain. Maybe it's my college Agile training showing, but I think I'd rather start with the simplicity of the original RAIL proposal and only take on complexity when a specific and important concern requires it.

Avoiding this complexity sounds correct to me.

**Comment by benshayden** [comment]
See #1696 . We're currently planning on setting the comfort histograms directly from experiments, without reasoning about idle tasks. If experiments show that discomfort doesn't start for scroll responses until 66ms, then there would not be a conflict between scroll response comfort and long idle tasks.

**Comment by natduca** [comment]
I'm not sure I agree the point of view that we'll initialize these scores with experiments in the short term. For Q1/Q2 timeframe, we should just pick numbers that Tim likes and run with them. He is an expert in this area and can give us completely reasonable targets.

And, perceptualBlend implemented as weightedAverage2 is fine for now. I just call it perceptualBlend because thats explains the intention behind the function. We don't need to revisit its design, I am just calling it something so that it makes sense to engineers like Tim. "WeightedAverage2(responsiveness, efficiency, hazard)" doesn't scream "this is a perceptual weighting" whereas perceptualBlend(...) says what it does (even though the implementation is the same). This is all about clearly explaining the *abstractions* we use.

IMO its also not a goal to make the final railscore self-explaining. I think the final railscore as a perceptualBlend  is a fine way to do things, and possibly always displaying railScore plus its three primaries next to it in one widget: first the railscore, big, then the three subscores. Clicking one could give you problems. Thats plenty. We should probably focus just on the railscore being correct and comparable, and leave making it self-explaining to whomever drives lighthouse.

**Comment by tdresser** [comment]
I think 4 or 5 frames of latency is a reasonable threshold. It's definitely annoying on some pages at 4/5 frames of latency, but it's tolerable everywhere.

Given the fact that it will simplify dealing with the idle callback time, I propose we go with 66ms for the moment.
