### ISSUE TITLE
Need passive way to make IR finder import warnings visible to user

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1243]
Context: https://codereview.chromium.org/1285903003

**Comment by benshayden** [comment]
Nat, feel free to describe how you want this done and assign it to somebody else to do.

**Comment by natduca** [comment]
Model has importWarnings and importErrors.

ImportWarnings are eaten silently, thats fine.
TimelineView checks if importErrors length is nonzero, and adds a tr-ui-b-info-bar to the top of the screen in response, with a clickable button to see the errors.

As far as owners, dunno.

**Comment by dj2** [comment]
This seems more like a nice to have then a requirement for PI Alpha?

**Comment by benshayden** [comment]
Agreed. And I think I understand Nat's directions.

**Comment by benshayden** [comment]
It appears that Nat has some new thoughts about how he wants this done.

> With this patch landed, please put yourself in the position of explaining to a noogler or someone who isn't familiar with this code why this;:
>   throw new Error('some error')
> doesn't show up in importErrors.
> And, please also think through how confusing it is to call to model.importTraces. Now you have to check whether there are import warnings, but also now you have to check for import errors. Strange.
> So you can see, I am not just trying to annoy you. I'm pretty darn sure i'm asking a good question here! Here's a way you could have done things that would be clearer... you'll note that importWarning takes an object that has a type and message field.
> What if you modify the docstring to also say there we support a third field saying {showToUser: true}. Then in the implementation, before pushign to data, we do this:
> if (data.showToUser===undefined)
>   data.showToUser = false;
> this way the field is always set.
> Now you modify auditor to push a warning like always. And then you just add a method down below saying importWanringsToShowTouser () that extracts the importWarnings that should be showToUser and returns those. Then you hook up the GUI and proceed on your way.

**Comment by benshayden** [comment]
I think this is done? Feel free to re-open.

**Comment by natduca** [comment]
\o/
