### ISSUE TITLE
Switch AnimationInteractionRecord.normalizedUserPain to use smoothness and discrepancy metrics

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1245]
Blocked on https://code.google.com/p/chromium/issues/detail?id=518960

**Comment by dj2** [comment]
Is this required for the Alpha? If so, do we know the status of the smoothness/value port?

**Comment by benshayden** [comment]
I pinged Ned on 518960.
I think that "we could show some real insights" (per the Alpha milestone) without these metrics since AnimationIR has simple FPS and long-frame metrics, but we still have a couple weeks before the Alpha is due, so let's see what Ned says before punting this to V1.

**Comment by benshayden** [comment]
#1228 is the catapult version of crbug 518960.
Ned has already ported discrepancy to js, so I think that I can now switch AnimationIR.normalizedLongFramePain to use that.
When 1228 is closed, then I can switch AnimationIR.normalizedFPSPain to the smoothness metric.

**Comment by benshayden** [comment]
Hm, it looks like I misunderstood. Smoothness is computed using discrepancy. FPS is just FPS.
So I think this is done? Feel free to reopen if I misunderstand now.
We might change Animation jank comfort to use brianderson's RMS, but that's just an idea, not a plan.
