### ISSUE TITLE
trace or metadata needs to signal when a device was running in power saver mode

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1248]

**Comment by anniesullie** [comment]
@fmeawad @vinterstum

**Comment by dstockwell** [comment]
Any thoughts on this one? It's preventing me from using my device on low battery for fear of polluting my data set.

**Comment by fmeawad** [comment]
I will look at it.

**Comment by fmeawad** [comment]
Currently, AFAIK, such signal is not passed to chrome. The only thing we can do is extract the CPU frequency and store that as well. I filed a bug in chrome to start tracking that signal.

For now, to avoid polluting the dataset, if you can tag your traces, we can be careful while processing them.
You can use /upload?tags=PossiblyPowerSaver

I will stop working on it for now, maybe @vinterstum can pick it up as part of his Metadata enhancement efforts.

**Comment by natduca** [comment]
Lets solve #1480 and then we can revisit this as a feature request when that is done. Also, in the interests of keeping our bugs super actionable, we will add this to our backlog (go/perf-insights) and archive the item here.

**Comment by natduca** [comment]
Lets reopen this as a chromium trace bug...
