### ISSUE TITLE
Add v8 costs to wr.html and wr_report.html

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1257]
We now have a weather report skeleton. Lets start adding the v8 costs to it.

**Comment by dj2** [comment]
The V8Samples parsing has landed on ToT so we should be able to start using this in the weather report. @chiniforooshan can you look into this?

**Comment by dj2** [comment]
Closing this as done. We still need to get more sampling data into the traces, but we go the rest of the bits done to show in the demo.
