### ISSUE TITLE
Prepare a deep reports corpus for the alpha demo and stage it in drive

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1258]
@paulirish can you drive this?

**Comment by paulirish** [comment]
* Where does the corpus live?
    * Lets tackle remote corpii in Alpha.

**Comment by natduca** [comment]
Lets also include in the corpus set for our demos the 800 trace set from @chiniforooshan that has page loads with and without adblock

**Comment by natduca** [comment]
Paul, any progress?

**Comment by natduca** [comment]
@philippebeaudoin lets just get a bunch of traces from deep reports, with @fmeawad help, ideally with v8 sample data in them, and then make sure that things work on that.

**Comment by philippebeaudoin** [comment]
I got a bunch from tag = 'TestingTeam' (Windows traces from the testing team). Running the mapper I get a bunch of
- Error: Invalid ProtoIR: ignored(NaN NaN MouseMove)

These errors don't seem to be happening when viewing individual traces. I get a number of warnings in the console though. For example:
- Unrecognized metadata name: trace_buffer_overflowed
- E phase event without a matching B phase event.
- Unrecognized event phase: R (navigationStart)
- Titles do not match. Title is LayerTreeImpl::UpdateDrawProperties::UpdateTiles in openSlice, and is LayerTreeImpl::UpdateTilePriorities in endSlice
- Different phases of StartProcessWithAccess::LAUNCHPROCESS provided values for argument id. The last provided value will be used.
- At 794157607514, no slice named TimeoutMonitor was open.
- Flow consumer 0x41001402 does not have a flow producer

I wasn't able to use them to generate a PI yet. I'll keep investigating today. If anyone has an idea feel free to chime in. @benshayden

**Comment by benshayden** [comment]
Does the mapper use a stale baked trace-viewer, or does it import the fresh tracing/tracing/ sources?

Those NaNs mean that the start and end times of at least one MouseMove InputLatencyAsyncSlice were undefined. I suppose I could filter those out, but it'd be better to figure out why they were undefined.

**Comment by philippebeaudoin** [comment]
It seems to be working well enough:
https://drive.google.com/corp/drive/folders/0Bwye9Aa8pAMnSllzYnpRZGFld2s

**Comment by natduca** [comment]
Awesome. Shall we mark closed? I'll put this url on our script.

**Comment by natduca** [comment]
Agh, crap: this data set doesn't have v8 samples.... calling @philippebeaudoin @fmeawad

**Comment by fmeawad** [comment]
V8 was enabled on Wednesday last week (09/23/2015),(#1304) it should start showing in the different traces this week. Not sure when @philippebeaudoin collected his set of traces, I would wait until next Wednesday and collect again.

**Comment by natduca** [comment]
Do we have a way to get data before wednesday? We'd like to do a demo weds morning...

**Comment by fmeawad** [comment]
I am looking into it now.

**Comment by fmeawad** [comment]
The windows traces should have enough CPU profile (last 300+ traces), I am working on the android traces.

**Comment by natduca** [comment]
Windows is fine for tomorrow. Would you mind putting what you've got in a drive folder so I can use em for our demo tomorrow?

**Comment by fmeawad** [comment]
Will post the link shortly.

**Comment by fmeawad** [comment]
https://drive.google.com/a/chromium.org/folderview?id=0B7Nc8cbDG517bmdOOWVsYkdzUzA&usp=sharing

(Still being uploaded)

**Comment by benshayden** [comment]
I'd recommend removing e5ac2e48-734b-4d86-9a0e-9cfb25aa3c58.gz from that folder for the demo.
I'm still not sure what's wrong with it, but it's the only one in that folder whose input latency events' bounds are broken. I think that one of start or duration is undefined, but I'm still looking.
There are a few unhandled MouseDowns in other files in that folder, which I'm also looking into, but are less of a problem than the NaNs.

**Comment by benshayden** [comment]
Oh, sorry, that trace is from a different folder.

**Comment by natduca** [comment]
Thanks! Lets run with this, thanks all!

**Comment by benshayden** [comment]
I found the trace in Philippe's "traces" folder that caused the NaN MouseMove errors: e5ac2e48-734b-4d86-9a0e-9cfb25aa3c58.gz

I made RAILIRFinder ignore input latency events whose start time isNaN.
The next step towards root cause is finding why this trace has a bunch of input latency events whose start times are NaN. Filed a new issue: https://github.com/catapult-project/catapult/issues/1567

**Comment by chiniforooshan** [comment]
I've talked with Fady about this, but thought maybe should mention it here too, as a heads up, in case anyone is using the 300 Windows traces in https://drive.google.com/a/chromium.org/folderview?id=0B7Nc8cbDG517bmdOOWVsYkdzUzA&usp=sharing.

If you look at didStartProvisionalLoad events in these traces, they all have URLs either from google sites (chromium.googlesource.com, code.google.com, cluster-fuzz.appspot.com, etc) or Chrome extensions. So be careful when you base a conclusion on an analysis done on this set. For example, this was not a good set for my Ads analysis report.

**Comment by fmeawad** [comment]
I am preparing a new set from the traces we got after enabling deep reports in chrome://flags. I will post the link here when it is ready.

**Comment by natduca** [comment]
Is there a query that we could just run to get the traces? @simonhatch created a pi reports driver so now we can in theory do map_traces --driver=perfinisghts --query="whatver" and it'll just work. Maybe we should dogfood using that approach?

**Comment by fmeawad** [comment]
tags=flags,Other (not sure about the format that is used by the reports driver)

**Comment by natduca** [comment]
@simonhatch we should probalby make --query help print something informative huh

**Comment by simonhatch** [comment]
Please, give it a shot!

@fmeawad : Format should be any valid corpus_query. Since these are converted to GQL queries later, some common sense restrictions like the property exists as part of the TraceInfoEntity. Maybe something as simple as --query="date > Date(2015-10-01 00:00:00.00)"

@natduca : Yeah definitely, good idea. I'll log something to improve on that.
