### ISSUE TITLE
Loading work, netlog before Loading IR

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1260]
Currently, Loading IRs are defined to start at didCommitProvisionalLoad, but this sometimes appears to be too late in the loading process. Should it start earlier? When?

Is there documentation somewhere about the different phases of the loading process?
I don't know enough about the loading process.

**Comment by benshayden** [comment]
Fadi supplied this trace: https://x20web.corp.google.com/users/be/benjhayden/www/rail1260.gz

**Comment by benshayden** [comment]
Related: Fix Load IR associatedEvents https://github.com/catapult-project/catapult/issues/1221
Related: Load IR should use first meaningful paint: https://github.com/catapult-project/catapult/issues/1147

**Comment by natduca** [comment]
Lets ping Bryan and Nate for help.

**Comment by natduca** [comment]
@bryanmcquade @natechapin fyi

**Comment by natechapin** [comment]
You may want didStartProvisionalLoad? That's fired just before blink starts a main resource request.  didCommitProvisionalLoad occurs when a load has enough data to justify leaving the old page and showing the new one (i.e., once the main resource's headers and the first bytes of its body are received).

I think the closest we have to documentation is a talk I gave at BlinkOn 1.  It's a bit out of date and very Blink-internal focused, but the most relevant slide is still accurate (if not terribly detailed): https://docs.google.com/presentation/d/1RgnNJL04CxMHpturEpIXSsuZhQCRVeJSTh90joQKTP0/edit#slide=id.g107454bce_037

**Comment by fmeawad** [comment]
Owning this temporarily, if I do not make progress will relinquish.

**Comment by fmeawad** [comment]
didStartProvisionalLoad should work (I use it as the trigger for Deep Reports/Navigation Tracing)

But the TRACE_EVENT is called before the observer where I trigger deep reports from is called
https://code.google.com/p/chromium/codesearch#chromium/src/content/renderer/render_frame_impl.cc&q=%22didStartProvisionalLoad%22&sq=package:chromium&type=cs&l=2537

So the event is not included

I think switching it to a B/E event instead of an X event might work, or moving the X event till after the observers.

**Comment by dj2** [comment]
@fmeawad what's the status of this? It sounds like we should switch our code to use didStartProvisionalLoad and then a second issue created to track making it work correctly for deep reports?

**Comment by fmeawad** [comment]
Assigning this original back to @benshayden since he is back. I will create a new one to track the effect in Deep Reports.

**Comment by benshayden** [comment]
Started: https://codereview.chromium.org/1350943002

**Comment by benshayden** [comment]
The new strategy for this issue is to use a Load async event and frameblamr, tracked in #1807 .
