### ISSUE TITLE
Startup Trace creates spurious Response IR with bad related events

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1263]
The trace at:
  https://github.com/natduca/measurmt-traces/blob/master/desktop/startup/startup_osx.json.gz
Is essentially just a trace of Chrome starting up with little/minimal user interaction. However the IR show spurious response events with a large number of unexpected related events.

<img width="1396" alt="screen shot 2015-08-13 at 9 56 47 pm" src="https://cloud.githubusercontent.com/assets/11399419/9265802/44e867d2-4206-11e5-9d19-d3ef96772929.png">

**Comment by philippebeaudoin** [comment]
Ping @benshayden

**Comment by philippebeaudoin** [comment]
@natduca Probably not MVP since it's on Chrome startup, but I'll let you judge.

**Comment by natduca** [comment]
Lets leave this on alpha, and then @philippebeaudoin we can debug this if/when we feel like we need it sooner.

**Comment by benshayden** [comment]
I can look at this this week if that's ok.

**Comment by benshayden** [comment]
That Response corresponds to a MouseMove event, which has a huge number of associated events, one of which must be a frame event.
It looks like InputLatencyAsyncSlice is gathering the entire CrBrowserMain thread, and every flow event that touches it. ILAS works on entire slice hierarchies.

Philippe, did you add tracing for BrowserMain, BrowserMain::MESSAGE_LOOP, and ChromeBrowserMainParts::MainMessageLoopRun?
If those slices weren't there, then the "toplevel" slices that they contain would be separate hierarchies. So maybe ILAS needs to ignore those BrowserMain slices when building hierarchies?

**Comment by benshayden** [comment]
The same thing is happening on the renderer thread with RendererMain and RendererMain.START_MSG_LOOP and the GPU thread with GpuMain and "Run Message Loop".

**Comment by dj2** [comment]
Do we have a way forward for this? Not sure what the solution is, blacklist?

**Comment by benshayden** [comment]
I'll just make ILAS stop at toplevel slices when building hierarchies. I can do it this week.

**Comment by benshayden** [comment]
Huh. So. I did that, and it worked.
But it appears that that Response IR is less "spurious" than initially thought.
There's a flow event from the WebViewImpl::handleInputEvent at 999.7ms to the BeginMainFrame at 1014.5ms, then from that to the ThreadProxy::ScheduledActionDrawAndSwap at 1016.2ms, which contains a BenchmarkInstrumentation::ImplThreadRenderingStats event at 1016.4ms.

So maybe one of those flow events is not matched up to one of its end points correctly?
Or maybe one of them shouldn't exist at all?
Who is our flow event expert these days?

**Comment by philippebeaudoin** [comment]
Dan and I argued pretty vehemently on flow V2 and he won, so I'd nominate him as the resident expert. :)

Still, I'll take a look to see if we're running into the known issue here.

**Comment by dj2** [comment]
Depending on when the trace started/terminated it's perfectly possible for a start/end flow event to be missing.

**Comment by benshayden** [comment]
The two flow events in Philippe's trace that link the MouseMove to the BenchmarkInstrumentation::ImplThreadRenderingStats event both have both start and end events. They are not near the beginning or end of the trace.

**Comment by benshayden** [comment]
Philippe: Could you change the startup slices to async slices? Or instant events if you really just need the start timestamp? That way, I wouldn't need to overload the meaning of "top level" slices.

**Comment by natduca** [comment]
Some context to Ben's comment: My theory here is that the real bug here around startup traces is that threads shouldn't have a trace event around their run loop. When a thread is created and destroyed should be a separate event, either a new event type (metadata or other) or just a pair of instant events... having it be a slice confuses the general notion of toplevel-ness and has a lot of knock-on complications from there.

**Comment by philippebeaudoin** [comment]
Ok. I'm guessing you're talking about these slices:
- RendererMain (ETW Trace Event)
- RendererMain.START_MSG_LOOP (ETW Trace Event)

I can dig through Chromium to turn them into Async slices, but the ETW in there leads me to believe they were added by someone else for some purpose that Async slices may not capture. I'm going to ping Georges.

**Comment by philippebeaudoin** [comment]
Here's a crbug talking about this:
https://code.google.com/p/chromium/issues/detail?id=489720

The consensus was to keep them because they're used by sawbuck. (Someone talked about semi-chaotic downstream dependencies? ;))
Options at that point:
1) Convince sawbuck to migrate to async events. (Maybe it would "just work"?)
2) Convince sawbuck that it doesn't really need that.
3) Move "ETW Trace Event" to "Disabled by Default Categories" and see how it would affect sawbuck.

**Comment by natduca** [comment]
Guhhhhhhhhh

A variant on using async events is to make custom metadata records for when threads start/stop... we've always played fast and loose about that, so maybe its something to just bite the bullet on now. Technically, right now, if you create a thread, delete it, then create another and they have the same pid, we show the slices on the same thread, whereas technically we should show these as two totally different threads. If we ever did want to fix that, we'd probably want thread created/deleted events to be their own custom type instead of a magical async slice. This all having been said, I don't really mind if we do async events because its easier! This is an area where we can absorb some more technical debt. :)

I like option 3.

**Comment by PhilBeaudoin** [comment]
I was suggesting we move them to disabled-by-default and not create new ones.

Do we need async slices for thread start/stop? I don't think RAIL or any other of our analyses depend on them.

**Comment by natduca** [comment]
I don't think we strictly need them. But they'd be a little bit missing for people who care about the distinction between a thread starting and it running its first task. DBD-ing would be a regression for that use case, but again, not a strictly-bad regresssion. I'm mostly shrug about the whole thing... if I were to hack this up, I'd do what you said, and then do an async-begin-end around the whole thread using the this pointer as the id.

**Comment by philippebeaudoin** [comment]
Francois: this is the bug tracking the top-level task problem that you'll be looking at during the hackathon. Let's talk to Chrisha and Siggi and see how much they care about these events.

**Comment by fdoray** [comment]
Done.
https://codereview.chromium.org/1384953004/
https://codereview.chromium.org/1386193002/
