### ISSUE TITLE
Add getEventsGroupedByBlinkRenderingFrames() to chrome_renderer_helper

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1264]
RendererHelper has a mainThread, and off of that is a sliceGroup.

If you sort that sliceGroup by time, you will find slices called ThreadProxy::BeginMainFrame.

These represent blink beginning a new frame of work.

Lets make a function that walks the sliceGroup's toplevel slices in ts order and uses this BlinkRenderingFrame as a delimiter for new frames.

Lets then wrap that in an actual class
```
   BlinkRenderingFrame()
     this.associatedEvents = new EventSet();
```

Using a class so we can dangle other stuff off it in the future [like frame number and what url it was from], and be strongly typed because I'm OCD like that :)

Could then return the resulting array.

**Comment by natduca** [comment]
@benshayden fyi

**Comment by natduca** [comment]
https://codereview.chromium.org/1284143007

**Comment by benshayden** [comment]
Is this still needed?

**Comment by natduca** [comment]
In the interests of focus, lets double down on all the other crazy things we've got to do, and reopen this down the road if we have a specific use case that forces this.
