### ISSUE TITLE
Generalize code to go from a slice to the associated samples.

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1275]
We currently have code in the analysis view that lets us view the samples which fall over a given event. We need to move this code up to the general slice model code so we can re-use it for the weather report.

**Comment by dj2** [comment]
@philippebeaudoin can you point out where this code is so we can move it around as needed?

**Comment by dj2** [comment]
Blocks #1257.

**Comment by philippebeaudoin** [comment]
Look for addOverlappingSamples_ in tracing/ui/analysis/related_events.html
