### ISSUE TITLE
Need to calculate domain time from sample data.

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1276]
With v8 samples we'll have a bunch of samples with the same stack. We need to write the code to say, given this set of samples, tell me the time for each domain inside that sample. It will need to walk over the samples, find the start of a given stack frame, and the last time we see that stack frame and subtract the first start time from the last one to get the time we were in that frame.

This won't be completely accurate, it can be off by 2 x sample rate because we miss the very start and very end but should be close.

**Comment by dj2** [comment]
Blocks #1257.

**Comment by chiniforooshan** [comment]
Another way to estimate domain time is to just sum up sample weights, as noted by Nat.

**Comment by dj2** [comment]
At least from the last trace I got the weights don't come in from tracing. I believe they were calculated after the fact by the devtools code.

**Comment by chiniforooshan** [comment]
Samples in test_data/chrome_v8.json have weights, and I verified that the two approaches give roughly equal estimates for domain costs.

**Comment by dj2** [comment]
Hm, I wonder if it isn't consistent then?

{"pid":30265,"tid":1,"ts":2067060413419,"ph":"P","cat":"disabled-by-default-v8.cpu_profile","name":"V8Sample","args":{"data":{"stack":["0x1f7ef4ce1418"],"vm_state":"external"}},"tts":37793,"id":"0x0"},

from chrome_v8.json

**Comment by chiniforooshan** [comment]
My bad. It looks like the weights are set in the trace_event_importer and are not coming from the trace file itself. The importer always uses a default weight and I guess the 2 approaches gave similar numbers because samples are taken at a constant rate (almost).

**Comment by dj2** [comment]
I believe this is done with the first version of the report.
