### ISSUE TITLE
Document the maths in computeNormalizedPain and weightedAverage2

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1281]
The maths in rail_interaction_record.html is quite involved and should be documented. See comments on https://codereview.chromium.org/1282343002/ 

/cc @benshayden @dj2

**Comment by benshayden** [comment]
I started a presentation and doc about this, but they aren't ready for review yet.

**Comment by benshayden** [comment]
PTAL go/railscoresdoc
I can share it outside google.com and give it a bit.ly when it LGTY.

**Comment by benshayden** [comment]
Ping? I'll close this in a couple days if there are no more comments.

**Comment by dj2** [comment]
I think you can push it out to public and link it from ..... somwhere.

**Comment by benshayden** [comment]
http://bit.ly/1LXShKe
