### ISSUE TITLE
Move html5lib-python to $catapult/third_party

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1283]
Didn't notice it there over in dashboard. Wanna use it in tvcm.

**Comment by natduca** [comment]
@qyearsley can you?

**Comment by qyearsley** [comment]
html5lib isn't currently used by dashboard (except indirectly by bs4) -- so I think to add it we'd still have to commit https://codereview.chromium.org/1288843004.

**Comment by natduca** [comment]
Huh? I'm confused. Its in dashboard/third_party already.

**Comment by qyearsley** [comment]
I don't see it -- catapult/dashboard/third_party is currently a symlink to catapult/third_party, and I don't see html5lib in https://github.com/catapult-project/catapult/tree/master/third_party now

**Comment by natduca** [comment]
huh?! dashboard/third_party isn't a real file?

**Comment by dj2** [comment]
Have I mentioned you don't really want to be comitting symlinks into git?
Heh

Dan

**Comment by qyearsley** [comment]
Fortunately, the symlink is unnecessary and can be deleted (should be deleted by https://codereview.chromium.org/1305603002/)

I guess this issue can now be closed since in order to add html5lib we'll use https://codereview.chromium.org/1288843004/?
