### ISSUE TITLE
[tracing] Incorrect rendering of blocks with exact same start time.

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#1284]
It seems like tracing sorts the events based on `ts`, but doesn't handle well the case where the `ts`s are equal.

```json
[
  {"name": "foo", "tid": 1, "pid": 1, "ph": "X", "ts": 0, "dur": 100},
  {"name": "bar", "tid": 1, "pid": 1, "ph": "X", "ts": 0, "dur": 110}
]
```
<img width="422" alt="screen shot 2015-08-19 at 8 35 20 am" src="https://cloud.githubusercontent.com/assets/211662/9360808/53633f6c-464d-11e5-8710-84cfafb85c2a.png">

If you swap the order of the events, the rendering is correct:

```json
[
  {"name": "bar", "tid": 1, "pid": 1, "ph": "X", "ts": 0, "dur": 110},
  {"name": "foo", "tid": 1, "pid": 1, "ph": "X", "ts": 0, "dur": 100}
]
```
<img width="423" alt="screen shot 2015-08-19 at 8 34 57 am" src="https://cloud.githubusercontent.com/assets/211662/9360810/58f8d9dc-464d-11e5-9030-ef6b581e0f5a.png">

**Comment by dj2** [comment]
We combined foo and bar into a single slice? That's .... very broken.

@natduca

**Comment by dave-2** [comment]
No, I think it just drew two slices that overlap.

**Comment by natduca** [comment]
We use position in the file to resolve timestamp overlaps. Your first example is malformed...

**Comment by natduca** [comment]
Closing due to working-as-intended
