### ISSUE TITLE
Flaky Windows Perf Dashboard Test (auto_bisect_test.AutoBisectTest)

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1285]
auto_bisect_test.AutoBisectTest.testPost_FailedJobRunOnce_JobRestarted fails a lot like this:

```
Traceback (most recent call last):
  File "E:\b\build\slave\catapult\build\catapult\dashboard\dashboard\..\..\third_party\mock\mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "E:\b\build\slave\catapult\build\catapult\dashboard\dashboard\auto_bisect_test.py", line 54, in testPost_FailedJobRunOnce_JobRestarted
    try_job.TryJob.query(try_job.TryJob.bug_id == 222).get())
  File "E:\b\build\slave\catapult\build\catapult\dashboard\dashboard\..\..\third_party\mock\mock.py", line 845, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected to be called once. Called 0 times.
```

Examples:
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/508/steps/Dashboard%20Tests/logs/stdio
https://build.chromium.org/p/client.catapult/builders/Catapult%20Windows/builds/189/steps/Dashboard%20Tests/logs/stdio
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/508/steps/Dashboard%20Tests/logs/stdio
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/506/steps/Dashboard%20Tests/logs/stdio

@qyearsley - Should we disable this test on Windows?

**Comment by qyearsley** [comment]
Yesterday I observed stats_test being flaky due to depending on the order that things are put and fetched from the datastore -- maybe this might be similar? How would you disable a specific dashboard unit test on a specific platform?

**Comment by anniesullie** [comment]
I think this should do it, running through CQ dry run now: https://codereview.chromium.org/1288643005

**Comment by qyearsley** [comment]
Update: Using print statements and try jobs (https://codereview.chromium.org/1312393003/), I narrowed down the cause to [_IsBisectJobDueForRestart](https://github.com/catapult-project/catapult/blob/ed03538f4baf72bdeaa9c7b76fbe6b5c9ad14d90/dashboard/dashboard/auto_bisect.py#L184)
