### ISSUE TITLE
v8.run events have file name, too. Do we need V8 samples to extract JS origin?

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1286]
An example of a v8.run event: 

{"pid":24011,"tid":1,"ts":220658981682,"ph":"X","cat":"v8","name":"v8.run","args":{"fileName":"http://static.bbci.co.uk/news/1.82.0388/js/compiled/all.js"},"dur":15299,"tdur":14608,"tts":795457}

**Comment by dj2** [comment]
@natduca @fmeawad Is the filename on v8.run new?

**Comment by fmeawad** [comment]
It was added about a year ago: https://codereview.chromium.org/289283008/diff/1/Source/bindings/v8/V8ScriptRunner.cpp

**Comment by natduca** [comment]
caseq@google and alph@google are great folks to ping for advice on sample analysis. They're in MTV timezone. I'm trying to get their github accounts added here for the future....

**Comment by dj2** [comment]
I believe we want to stick to extracting from samples. The reason being, the samples give us function/line information as opposed to just file level detail.

We could probably surface the fileName info from v8.run events which would be useful if there are no samples, but I don't think it replaces.

Feel free to re-open if you disagree.
