### ISSUE TITLE
Support to view trace files in Chrome on a touch-screen device

### ISSUE THREAD

**Issue by XSJoJo** [catapult-project/catapult#1287]
It would be nice to be able to view trace files directly on Chrome on a touch-screen device. Currently, this works so far but has the following usability issues:
- Vertical Scrolling doesn't work at all.
- Everything is tiny, and zooming with pinch-to-zoom doesn't work.
- Most selection tools don't work.

**Comment by dj2** [comment]
Closing as a duplicate of #348.

**Comment by natduca** [comment]
Lets simplify the original issue description though, and indicate the items on this bug as p1.
