### ISSUE TITLE
Make map_runner.py always use its progress reporterer

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1288]
In #1270 we modify the devserver to be able to run mappers. This causes console spew, because maptraces always outputs to the devserver's stdout.

@dstockwell any ideas? I tried a dirty patch here where I just shifted progress reporting to after-the-fact. But that only works for j>1... with j=1 we then are completely silent until all mapping is done.

**Comment by dstockwell** [comment]
This TODO? https://github.com/catapult-project/catapult/blob/master/perf_insights/perf_insights/map_runner.py#L33

I think an API like this would work:
```
run_reporter = self.progress_reporter.WillRun(run_info)
...
run_reporter.DidRun(output, had_failure)
```

**Comment by natduca** [comment]
Yeah. I'm not sure what the limitation is that makes it hard to call the reporter directly. Is the issue the interleaving or...?
