### ISSUE TITLE
Switch weather report to use UserFriendlyCategory instead of title

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1290]
There are too many titles when we group by slice title.

The hard part of this is using the category parts, instead of the category.

E.g. if you have a slice with category x,y... which category does it get counted inside?

**Comment by natduca** [comment]
https://codereview.chromium.org/1285293006 is a wip. But, it doesn't handle category parts correctly.

**Comment by natduca** [comment]
base/category_util.html is probably useful. But not sufficient.

**Comment by benshayden** [comment]
After discussion with Nat, WorkGroup will be re-imagined to UserFriendlyCategory.fromEvent(event).
