### ISSUE TITLE
Remove long-task-warning in chrome auditor

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1297]
Just adds noise.

**Comment by natduca** [comment]
Would be fine to just kill this entire function

https://github.com/catapult-project/catapult/blob/master/tracing/tracing/extras/chrome/chrome_auditor.html#L87

**Comment by dj2** [comment]
Is this not something we think people should worry about anymore, or is it just that the alert UI is too cluttered when we show the alerts?

**Comment by natduca** [comment]
It was only ever added as an example of how to use an auditor. As a feature, its not very useful because our UI for it only shrug level quality. We definitely don't have time to improve the uI, so our best option for now is I think hide the alert.

**Comment by sylvesterwillis** [comment]
Hello, 
I've opened a Code Review at https://codereview.chromium.org/1354493002/ for this issue.
