### ISSUE TITLE
Vsync highlighter is not included in Android systrace conf

### ISSUE THREAD

**Issue by aschulm** [catapult-project/catapult#1306]
The vsync highlighter already works with Android traces, but it isn't included yet in trace-viewer's systrace conf.

**Comment by anniesullie** [comment]
@wangzhen127 @zeptonaut

**Comment by zeptonaut** [comment]
I'll take care of this.

**Comment by zeptonaut** [comment]
Looks like aschulm@ is already handling this in https://codereview.chromium.org/1307933002/.
