### ISSUE TITLE
Trace viewer needs integration tests to ensure necessary wrapper scripts work

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1308]
Several of our trace viewer wrapper scripts have been broken due to relying on an out-of-date import method for the past three days (since d901061). These breakages are being fixed in [this patch](https://codereview.chromium.org/1307993002/).

Unfortunately, the breakage wasn't caught by any unit tests. This is bad.

It seems reasonable to:

- Reevaluate to make sure that all of viewer wrapper scripts are necessary
- Write small integration tests for each necessary wrapper script to make sure that it's able to start up and import traces as expected

**Comment by natduca** [comment]
Its not so clear how to write tests for this, tbh. The bin/index.html file depends on an asset that isn't even checked in, so we'd need to autogenerate it before running a browser test on it. And, our current test running infrastructure doesn't really make it easy to just point a chrome at a url and then run it. We'd have to do nontrivial eng to make this work.

My preference here is that we simply try to keep our public apis for embedding trace-viewer stable, understanding that when we break it, we create pain like this.

**Comment by zeptonaut** [comment]
SGTM. Closing as "won't fix"
