### ISSUE TITLE
appengine_dev_server.py uses __file__, which can point to pyc files

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1310]
I'm trying to run `dashboard/bin/dev_server` on my Mac, and I'm running into an issue where `appengine_dev_server.DevAppserver` tries to refer to the App Engine SDK's dev server using `dev_appserver.__file__`, which at least on Mac points to a pyc file, which isn't executable.

I'm going to test this on Linux to see what happens, but basically the fix here is to come up with something better than `__file__` for pointing to the .py (which _is_ executable)

**Comment by eakuefner** [comment]
Okay, indeed, this fails as well on Linux after a first invocation of dashboard/bin/dev_server because the pyc file is created on import.

**Comment by anniesullie** [comment]
@qyearsley
