### ISSUE TITLE
tr-ui-b-table row highlighting-on-hover works inconsistently

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1311]
It seems like the current table is set up so that hover-highlighting works fine when supportsSelection is true.

But, when supportsSelection=false, it row hovering seems to not work. Is that intentional?

Whats weird is that this test case has supportsSelection=false but row hovering works.

http://localhost:8003/tracing/tests.html?testFilterString=sequentialRebuildsBehaveSanely&testSuiteName=tracing.ui.base.table_test

IDGI. @petrcermak any ideas?

**Comment by petrcermak** [comment]
The current intended behavior is as follows:

1. **Disabled selection** (<tt>table.supportsSelection = false</tt>): no hover highlight
2. **Enabled selection** (<tt>table.supportsSelection = true</tt>):
  1. **Row selection mode** (<tt>table.cellSelectionMode = false</tt>): row hover highlight
  2. **Cell selection mode** (<tt>table.cellSelectionMode = true</tt>):
    1. **Disabled row highlight** (<tt>table.rowHighlightEnabled = false</tt>): cell hover highlight
    2. **Enabled row highlight** (<tt>table.rowHighlightEnabled = true</tt>): cell hover highlight + light row hover highlight

This is arguably a very complex behavior. In addition, the footer *always* has row hover highlight enabled (even when selection is disabled or the table is in the cell selection mode), which is inconsistent with the rest of the table.

Unless there is a use case where we *don't* want to enable hover, I think that the **cleanest solution would be to always enable hover**. Furthermore, to make the behavior consistent, the <tt>cellSelectionMode</tt> and <tt>rowHighlightEnabled</tt> properties would affect the hover highlight as described above (even if selection were disabled).

WDYT?

**Comment by natduca** [comment]
It seems like my patch makes these orthogonal.... I don't think we have to go so far as to force highlighting.

**Comment by petrcermak** [comment]
OK, so you're suggesting that there should be no row highlighting at all by default (even in row selection mode)?

What about cell highlighting? Would it always be enabled in cell selection mode and disabled otherwise (or would there be a separate flag as well)?

**Comment by natduca** [comment]
I guess so. I'm just trying to find orthogonal pieces here and call them that.

The cell highlight sounds like a separate feature. If you look at your tree, the row behavior is actually separable as long as when selection is disabled, we've got .

I do btw think that the way we've implemented hovering is impacting maintainability: we have this all done with css :hover and crazy selectors. I think it'd be more maintainable in the medium run to just listen to mouseenter/leaves on the table element itself, and then set state accordingly based on the target.

**Comment by petrcermak** [comment]
How about we had three enums:

  1. Selection mode: <tt>NONE</tt>, <tt>ROW</tt>, <tt>CELL</tt> (this would be easy to extend with options like <tt>MULTI_ROW</tt> in the future).
  2. Row highlight: <tt>DEFAULT</tt> (depending on selection mode), <tt>NONE</tt>, <tt>LIGHT</tt>, <tt>DARK</tt>.
  3. Cell highlight: <tt>DEFAULT</tt> (depending on selection mode), <tt>NONE</tt>, <tt>DARK</tt>.

Where <tt>DEFAULT</tt> would be the default option for row and cell highlighting, whose behavior would depend on selection mode:

  * Disabled selection: <tt>NONE</tt>, <tt>NONE</tt>
  * Row selection mode: <tt>DARK</tt>, <tt>NONE</tt>
  * Cell selection mode: <tt>LIGHT</tt>, <tt>DARK</tt>

I think that this approach would make the API both simple to use (unless you want any special visual behavior, you just set the selection mode) and very powerful. WDYT?

**Comment by natduca** [comment]
I tried to fix this but I can't understand the code and the constraints. Petr, can you please drive this?

**Comment by petrcermak** [comment]
I should be able to get to it in a few days if it's not super-urgent.

**Comment by natduca** [comment]
I'm going on vacation so anytime before I get back would be cool :)

**Comment by petrcermak** [comment]
That should be fine :wink:

**Comment by petrcermak** [comment]
I think this is now **fixed**.
