### ISSUE TITLE
Vulcanize performance dashboard in catapult with py_vulcanize (tvcm).

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1312]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-09T01:45:25.000Z_
_Originally opened as http://crbug.com/508372_

---

This requires:
- Adding tvcm to catapult
- Verifying that it works with jinja templates.
- Making a script that vulcanizes each template in dashboard/templates before deploying, putting the vulcanized versions in some other directory.

This script should then be called by the deploy script. Deploying should ideally work with and without vulcanization.

**Comment by qyearsley** [comment]
Note, tvcm is of course in catapult now, although it's currently in catapult/tracing/third_party and should probably be moved to catapult/third_party or somewhere else.

**Comment by natduca** [comment]
#1266 is related

**Comment by qyearsley** [comment]
Last week I was experimenting with this, and I got py_vulcanize to vulcanize templates but places where there were Jinja directives didn't appear to be handled correctly, so we may want to try to "de-jinjafy" the dashboard first, and re-visit this later. We'll want to first do #1710, (and possibly #1712 and #1329).

**Comment by benshayden** [comment]
Reopening in #3824
