### ISSUE TITLE
Trace from polymer team loads but is empty

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1314]
This

https://drive.google.com/a/google.com/file/d/0B0THUw4v2YF2UE4xVXN6bUw4ZFk/view?usp=sharing

shows up as this
![image](https://cloud.githubusercontent.com/assets/412396/9419904/bd5622e0-4814-11e5-81c4-ef87f7b67bcc.png)

**Comment by natduca** [comment]
@dj2 any ideas?

**Comment by dj2** [comment]
What version of chrome? Loading with ToT trace-viewer seems to work correctly for me.

**Comment by natduca** [comment]
I tried on osx, 44.0.2403.155 stable and 46.0.2489.0 canary

**Comment by dj2** [comment]
Works correctly on 46.0.2486.0 (Official Build) dev (64-bit) Linux. Let me upgrade and see if it still works.

**Comment by dj2** [comment]
Also works on 46.0.2490.6 (Official Build) dev (64-bit) Linux. Possibly a mac only issue?

**Comment by dj2** [comment]
This fails for me on mac with 47.0.2496.0 and 44.0.2403.157.

**Comment by natduca** [comment]
Duping into 1780
