### ISSUE TITLE
Make revision range selector show data for first selected trace, not just first trace in the legend.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1315]
**Issue by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2013-10-03T21:36:27.000Z_
_Originally opened as http://crbug.com/303910_

---

Ex: https://chromeperf.appspot.com/report?masters=ChromiumWebRTC&amp;bots=chromium-webrtc-rel-7&amp;tests=webrtc_manual_browser_tests_test%2Fmemory%2Fws_final_r&amp;checked=ws_final_r&amp;start_rev=221875&amp;end_rev=226772

**Comment by qyearsley** [comment]
**Comment by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2013-10-04T19:12:52.000Z_

----

What's actually happening here is that the revision range selector just shows the data for the first graph in the legend. So it's correct for that graph:

https://chromeperf.appspot.com/report?masters=ChromiumWebRTC&bots=chromium-webrtc-rel-7&tests=webrtc_manual_browser_tests_test%2Fmemory%2Fws_final_r&checked=private_mem_final_b&start_rev=221875&end_rev=226772

Usually this works fine, because the first graph is an average, sum, etc. Like "page_load_time" for page cyclers. Not sure if I'll have time to implement a revision range selector that flips with the list of selected graphs.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2013-11-26T00:43:18.000Z_

----

This also seems like a UI feature that would be nice. Should involve changing chart-container.html and chart-revision-range.html so that when the selection in the legend changes, the revision range minigraph also gets updated.

**Comment by qyearsley** [comment]
**Comment by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2013-12-18T15:53:44.000Z_

----

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-07-15T00:58:49.000Z_

----

**Comment by benshayden** [comment]
Archiving. V2SPA always displays in the minimap the first timeseries that is displayed in the main chart. That still isn't perfect, so I'll make a note in chromeperf-v2-status to see when the minimap can be made clearer.
