### ISSUE TITLE
Remove update_test_metadata.py.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1317]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-05-15T18:56:15.000Z_
_Originally opened as http://crbug.com/488607_

----

Now, after the work done to get test descriptions sent with test data in chartjson, update_test_metadata now only fetches unit-info.json from src/tools/perf.

Ideally we should first ensure that Buildbot is sending improvement direction and ensure that add_point_queue.py updates improvement direction appropriately.

Additionally, we might still want to have a list of units to improvement direction which is used in case improvement direction isn't explicitly specified. This could potentially be hard-coded or kept only in datastore.

**Comment by anniesullie** [comment]
@eakuefner - What do we need to do in order to get improvement direction sent to dashboard in chartjson?

**Comment by eakuefner** [comment]
Note: crbug.com/459450 is related to this.

This has been blocked in the past on the idea that we would make a type system for units, but I'm not sure we have bandwidth for that just yet. I think it should be fine to pick up the approach @anniesullie took in crrev.com/809393002 without any bikeshedding, and revisit the idea of a unit system later when we have a better idea of what it should look like.

I'm happy to make this a priority after I finish the timeline-based measurement plumbing.

**Comment by qyearsley** [comment]
After Ethan's CL https://codereview.chromium.org/1372413007/, I think this can be done now :-)
