### ISSUE TITLE
Page scrolls to top when chart tooltip closed when there's a warning set on the page.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1319]
To reproduce:
1. Go to a page with charts that has enough charts so that the page scrolls vertically.
2. Open and close a tooltip either by hovering or clicking on a point and hovering past or clicking outside.

Example pages:
 - https://chromeperf.appspot.com/report?sid=49bb76ee6ff0d492f8af29a0ca880e6c09351f171c08c72e14279e8aca7e7219
 - https://chromeperf.appspot.com/group_report?bug_id=517502

Note: There haven't been any changes to [chart-tooltip](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-tooltip.html) since last week when dashboard moved to catapult. There was one change to chart-container (https://github.com/catapult-project/catapult/commit/f035bc88c3fdcddba1944a80980bc608361a934d), but that appears unrelated.

This could potentially be a new issue which now happens after interacting with Polymer 0.5.5 (since previously it was using Polymer 0.5).

**Comment by qyearsley** [comment]
@chrisphn 

One possible first step to eliminate the possibility of Polymer being an issue: deploy a version with Polymer 0.5.0 by updating third_party/polymer/bower.json, running the deploy script and trying it out.

**Comment by chrisphn** [comment]
Hm, can't reproduce ATM.

**Comment by qyearsley** [comment]
I'm not reproducing it either; let's close this and file a new bug if we see it again.
