### ISSUE TITLE
Using ASYNC_NESTABLE seems to cause trace events to be written with the wrong category

### ISSUE THREAD

**Issue by rmcilroy** [catapult-project/catapult#1320]
https://code.google.com/p/chromium/issues/detail?id=504656

 - I have no idea what was going on with the begin event having the
worker.scheduler category and the end event having the renderer.scheduler
event - as far as I can see there would be no way for this to happen unless
there was a bug in the trace_event code somewhere (it went away when I
moved back to ASYNC_STEP_INTO trace events).

To repo, revert https://code.google.com/p/chromium/issues/detail?id=504656 on Chromium. Start chrome and start tracing on a page, then use the debugger to pause (suspend) the page for a while (e.g., 10 seconds), then resume the page and finish the trace, you should see the issue.

**Comment by natduca** [comment]
Is this still happening?

**Comment by rmcilroy** [comment]
Sorry, no idea. We rewrote the code to use ASYNC_STEP_INTO instead.

**Comment by benshayden** [comment]
Feel free to reopen?
