### ISSUE TITLE
Provide access to real traces corpus 

### ISSUE THREAD

**Issue by vmpstr** [catapult-project/catapult#1325]
It would nice to be able to access at least a small set of real world traces, or if that's already possible to have some guidelines/docs on how to do this.

**Comment by vmpstr** [comment]
@natduca, do you know if this is possible already? Or who would be a good person to look into this?

**Comment by natduca** [comment]
#1234 is I think what we want here...

**Comment by natduca** [comment]
Dupe to #1234
