### ISSUE TITLE
Any PERF=note annotations on commits should be available in the hover text of a dashboard alert

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1327]
**Issue by [nd...@chromium.org](https://code.google.com/u/102435256078839283966/)**
_2014-03-20T14:45:16.000Z_
_Originally opened as http://crbug.com/354441_

---

Suppose I land a patch to chrome or blink with the text
  PERF=This added a new page to page_cycler. Numbers are expected to get worse.

When a sheriff or anyone hovers the alert bubble in a graph, or hovers an alert in the table, the dashboard code should scan the blamelist for that range for any commits with the PERF= line and give that text immediately.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-03-21T00:08:55.000Z_

----

Sounds potentially useful. As I understand it, the suggestion is: when a chart-tooltip gets shown, the JS in the tooltip would fetch CL descriptions for Chromium SVN revisions (the changelog) and display some text in the tooltip if it finds "PERF=".

Although, this might create a lot of extra requests to the changelog; not sure if this would be an issue.

**Comment by qyearsley** [comment]
**Comment by [tonyg@chromium.org](https://code.google.com/u/tonyg@chromium.org/)**
_2014-03-21T00:13:46.000Z_

----

Yeah, I think this would be super useful. People try to do this in an adhoc way all the time.

Quinten, once you click an alert, we start querying the log anyway right? So couldn't this strictly be done in JS or something after the log has loaded? It would be fine if the alert box expanded dynamically after the change log loads.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-03-21T00:26:35.000Z_

----

It is true that once you click an alert the dashboard front-end JS adds an iframe which loads the changelog -- after loading this changelog we could check if the contents of that iframe are there and then search for PERF=.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-04-30T19:34:36.000Z_

----

Update:

First of all, a similar idea was mentioned by another developer today -- if they have a doubt that their CL might possibly cause a performance regression but they're not sure, they could also add a PERF=note annotation; hypothetically, apart from showing comments in tooltips on the dashboard, maybe other actions could be taken, e.g. email a http://chromeperf.appspot.com/group_report?rev=... link to the CL author so that they can track when alerts come in.

Secondly: The way that the change logs are shown is now a bit different, since I just did away with the iframe at the bottom of the page. Now, we would want the chart-container element itself to make a XHR to get the CL descriptions whenever someone clicks on a point on the chart.

**Comment by qyearsley** [comment]
**Comment by [pasko@chromium.org](https://code.google.com/u/pasko@chromium.org/)**
_2015-04-29T14:05:14.000Z_

----

**Comment by qyearsley** [comment]
**Comment by [pasko@chromium.org](https://code.google.com/u/pasko@chromium.org/)**
_2015-04-29T14:08:10.000Z_

----

We have discussion about a similar feature in issue 481783, but the usecase would rather be "the perfbot requests an annotation", not a commit. Can this be unified?

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-30T00:49:10.000Z_

----

I do think adding annotations/comments to charts upon explicit request (from a bot or human) (issue 454988) would serve much of the same function that this feature would serve, but they're different potential features -- maybe later on it will be possible to add this feature (PERF= annotations in change descriptions) separately?

**Comment by qyearsley** [comment]
**Comment by [pasko@chromium.org](https://code.google.com/u/pasko@chromium.org/)**
_2015-04-30T11:53:29.000Z_

----

re #7: it you think unifying does not make it overall easier, up to you, let's keep it separate

**Comment by qyearsley** [comment]
Next step to implement this is to expand chart-tooltip so that: When a new tooltip is opened, it should make a request to `https://chromium.googlesource.com/chromium/src/+/<commit-hash>` to fetch the commit description, and look for PERF=. If there is something there it can add it to the tooltip.

It might be a bit faster to fetch content from gitiles if one appends `?format=TEXT` which returns base64-encoded file (which can be decoded with `base64.decodestring`).

**Comment by qyearsley** [comment]
@anniesullie noted (in an email thread) that making network requests on mouse hover for tooltips can put really unpredictable load on a service, and if we do this we'd likely want to pre-compute or cache the commit descriptions.

I think pre-computing sounds like it would involve fetching all commit descriptions for all revisions, which may be too many requests?

Caching, I think would involve, instead of always making a direct request to gitiles, make a request to chromeperf.appspot.com/get_commit_descriptions, which then checks the datastore and either returns a cached map of revisions to commit descriptions, or fetches it and returns it?

**Comment by anniesullie** [comment]
I think ideally we'd have the full data outside of the tooltip. For example, when a bug is filed, the PERF= note should be pasted there too.

Maybe having an hourly cron that ingests CL descriptions and associates them with commit positions, so that we can make those annotations on Row entities?

**Comment by qyearsley** [comment]
Yeah, that sounds reasonable.

If there are properties set on Row entities, then displaying this information would be a small change to [graph_json.py](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/graph_json.py#L155), [chart-container.html](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-container.html#L1826) and [chart-tooltip](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-tooltip.html#L112) to surface the Row annotation.

Another possibility for getting the annotations on to the Rows, besides an hourly cron job:

In [build/scripts/slave/results_dashboard.py](https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/results_dashboard.py), get the commit description and add any PERF= field as a row annotation. (Pros: No need for cron job which makes requests to gitiles; cons: this would make results_dashboard.py more complicated).

**Comment by benshayden** [comment]
The Histogram Pipeline simplifies this bug: results_dashboard.py now just needs to add a shared Diagnostic (with a new reserved name like commitNotes) containing all PERF=notes from the commit descriptions since the last time the benchmark ran, and V2SPA will display them like any other SparseDiagnostics. @eakuefner

**Comment by eakuefner** [comment]
@anniesullie Does this seem like something we still want? I feel like "this CL added a new story" will eventually be covered automatically by the sparse diagnostic annotations we have planned for the perf dashboard, so maybe we should just wontfix this.

**Comment by eakuefner** [comment]
`git log | grep "PERF="` shows that PERF= has been used exactly once in the entire history of Chromium. I'm preemptively wontfixing this; please reopen if you object.
