### ISSUE TITLE
De-jinjafy: Add a handler to fetch revision_info, and fetch revision_info with an XHR.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1329]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-13T17:48:40.000Z_
_Originally opened as http://crbug.com/520601_

----

Currently, the dashboard embeds most data on the page using jinja. This has the advantage of being relatively fast and simple.

However, in order to make it easier to test with real data from a local instance of the perf dashboard, it would be nice to fetch the revision_info from an end-point like chromeperf.appspot.com/revision_info.

Related possible future changes:
The same could be done for other data that is embedded now, including the TEST_SUITES dict. All of these XHR requests could be conditionally made to the host chomeperf.appspot.com if running on a dev server, or app_identity.get_default_version_hostname() otherwise.

**Comment by qyearsley** [comment]
Related: #1712

**Comment by anniesullie** [comment]
This is fixed.
