### ISSUE TITLE
App ID and hostname should be configurable.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1331]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-05-15T04:11:23.000Z_
_Originally opened as http://crbug.com/488338_

----

The string &quot;chromeperf&quot; is hard-coded in several places in the perf dashboard code, e.g. in:

load_graph_from_prod.py
email_template.py
auto_triage.py
bench_find_anomalies.py

The staging server hostname also shouldn't be hard-coded anywhere.

**Comment by anniesullie** [comment]
We'll re-open if this is requested.
