### ISSUE TITLE
Perf dashboard: Save y-zoom state in the URL.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1332]
**Issue by [nd...@chromium.org](https://code.google.com/u/102435256078839283966/)**
_2014-11-14T07:53:08.000Z_
_Originally opened as http://crbug.com/433185_

---

I keep having to open new tabs to have different charts up because so many state transitions don't work in the UI. But, Y zoom keeps getting lost. When I zoom in, then copy the URL and paste it, zoom state goes away.

The real bug may be that you have to have all these tabs...

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-11-21T20:01:47.000Z_

----

Sounds potentially useful; this would be an improvement.

The relevant code is in dashboard/elements/chart-container.html, in the onPlotClick method, where the y-axis is changed. The URL/history would have to be updated there, and the intialization of the chart would also have to include checking a y-axis range URL parameter.

As a side-note, I think a y-axis range URL parameter would have been useful for Ryan last week as well.

One possible draw-back: If there's one y-axis range specified in the URL parameter, then all charts on the page would be zoomed to the same range if it's specified, which in some cases could be confusing.

**Comment by Apeliotes** [comment]
This could be useful. We should look into it after the polymer migration lands.

**Comment by benshayden** [comment]
Archiving and making a note to do this in V2SPA.
