### ISSUE TITLE
Charts should be able to change order on /report page

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1333]
**Issue by [chrisp...@chromium.org](https://code.google.com/u/109509802684846018332/)**
_2015-05-18T18:40:20.000Z_
_Originally opened as http://crbug.com/489358_

---

Charts on report page can change order either by drag/drop or move up/down button.

**Comment by qyearsley** [comment]
@chrisphn

**Comment by benshayden** [comment]
Archiving
