### ISSUE TITLE
load_from_prod is broken

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1338]
@qyearsley @anniesullie 

load_from_prod broke because the app ID changed (it's now 'None' instead of 'auto'), but then I realized reading the comment about app_identity that it's correct to call app_identity.get_application_id(), but you have to preface it with 'dev~' which is a namespacing thing (it appears that the partition will always be 'dev~' on the dev server)

Fix incoming.

**Comment by qyearsley** [comment]
Thanks Ethan!
