### ISSUE TITLE
Range selection cursor icon shifted left ~100px

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1340]
**Issue by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2015-08-10T14:09:34.000Z_
_Originally opened as http://crbug.com/518841_

----

To reproduce:
1) Open a group_report page, like this one: https://chromeperf.appspot.com/group_report?bug_id=509618
2) Hover the cursor over the range selection widget under the graph

Observe that ~100px left of the start of the current selection, the cursor changes to the '|' icon. Then the '+' icon, then ~100px left of the end of the selection it changes to '|' icon. Its cursor icon changes are shifted ~100px left of where they should be.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-10T16:54:15.000Z_

----

I'm also seeing this, but I'm not sure why it happens yet. I don't remember seeing this before last week.

Chris, would you like to look into this?

**Comment by qyearsley** [comment]
**Comment by [chrisp...@chromium.org](https://code.google.com/u/109509802684846018332/)**
_2015-08-10T17:28:23.000Z_

----

Sure

**Comment by qyearsley** [comment]
**Comment by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2015-08-12T00:13:28.000Z_

----

I'm also seeing this, FWIW.

**Comment by tednakamura** [comment]
I'm also seeing this. For possibly helpful reference, below are some screenshots that demonstrate the problem (sorry for the low quality).

![cursor1](https://cloud.githubusercontent.com/assets/9001650/9527671/51de400c-4ca5-11e5-874a-e6aa79f781f4.png)
![cursor2](https://cloud.githubusercontent.com/assets/9001650/9527675/54b2f2fa-4ca5-11e5-913b-23312dc16c5f.png)
