### ISSUE TITLE
On load, automatically populate selection menus in /report page for the first chart

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1342]
**Issue by [chrisp...@chromium.org](https://code.google.com/u/109509802684846018332/)**
_2015-08-14T22:44:05.000Z_
_Originally opened as http://crbug.com/521175_

----

It would be nice for the selection menu to contain the last added test.  

We also get URL like below, which selection menu can fill in the test suite, master and bot.

https://chromeperf.appspot.com/report?masters=ChromiumFYI&amp;bots=android_cronet_builder&amp;tests=sizes&amp;rev=343258

**Comment by qyearsley** [comment]
@chrisphn @rschoen

**Comment by anniesullie** [comment]
Duping against #2048
