### ISSUE TITLE
On the alerts page, the quick-log element requests "auto_triage/undefined".

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1345]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-17T23:56:28.000Z_
_Originally opened as http://crbug.com/521829_

----

Just noticed in the dashboard logs:

  /get_logs:  Log name auto_triage/undefined does not exist.

The auto_triage log entries are filed under namespace = &quot;auto_triage&quot;, where the log name is the sheriff name. It appears that currently on the alerts page the quick-log element isn't initialized correctly to have the sheriff name.

**Comment by anniesullie** [comment]
I'm not seeing any 404s when loading alerts or group_report.
