### ISSUE TITLE
Improve test coverage to > 90% of lines for back-end code.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1346]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-01-09T01:19:07.000Z_
_Originally opened as http://crbug.com/447432_

----

Specific goals:
 - I'd like there to be no modules with &lt; 90% coverage
 - Anything that appears could be risky if it fails should be covered.
 - Any new test methods should be clear and readable.

(This test should be marked fixed when the above is true)

Rationale:
 - There are still lots of uncovered lines in the perf dashboard.
 - Since Python is dynamically typed, it's never certain whether a line will blow up until it's at least run.
 - Making sure everything is covered with good tests will make future modifications a bit easier.

**Comment by qyearsley** [comment]
Related note: I'd like to add a code coverage check in catapult/dashboard/bin/run_tests so that it:
 1. Fails if the overall coverage is lower than some threshold
 2. Gives a link to a HTML file showing coverage for the tests that were just run (may be useful when developing locally)

**Comment by anniesullie** [comment]
We are happy with backend test coverage, will add more tests as problems arise.
