### ISSUE TITLE
Get coverage information when running dashboard unit tests.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1347]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-14T17:01:40.000Z_
_Originally opened as http://crbug.com/510085_

----

Current, dashboard gets awesome coverage for free from using the google internal infrastructure. After migrating to catapult, we want to continue making sure that we're aware of test coverage and we have any easy way to check up on it.

We may also decide to enforce a minimum coverage, in order to prevent people from adding new modules without adding corresponding tests.

**Comment by qyearsley** [comment]
Something that could be possibly changed: add a code coverage check in catapult/dashboard/bin/run_tests that:
 1. Fails if the overall coverage is lower than some threshold
 2. Gives a link to a HTML file showing coverage for the tests that were just run (may be useful when developing locally)

**Comment by anniesullie** [comment]
Could also upload coverage % to perf dashboard ;)

**Comment by anniesullie** [comment]
I think we are pretty happy with backend test coverage.
