### ISSUE TITLE
Refactor chart-container showTooltip method and move most of the logic to chart-tooltip.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1348]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-10T17:43:19.000Z_
_Originally opened as http://crbug.com/508991_

----

The method showTooltip is 100 lines long, and most of the logic belongs in chart-tooltip. The method resetTooltip should also be a method of the chart-tooltip element.

**Comment by anniesullie** [comment]
Closing since we're doing larger-scale thinking about UI refactoring.
