### ISSUE TITLE
Add error handling for graph_json request

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1349]
**Issue by [chrisp...@chromium.org](https://code.google.com/u/109509802684846018332/)**
_2015-07-17T06:02:57.000Z_
_Originally opened as http://crbug.com/511079_

----

We've seen a lot of errors from making request to /graph_json handler, e.g., malformed parameters, deprecated tests and internal errors.  ATM we don't load any graphs.  We should update UI on error to inform users.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-17T16:09:40.000Z_

----

Agreed. Specifically:

1. Currently graph_json does do some validation of the arguments; if they don't pass that validation then /graph_json responds with the non-JSON text "Bad Graph JSON Request". 

2. If something else goes wrong, it's generally ignored, and some kind of response is returned (possibly empty). It may be better to return JSON with {"error": "description of what happened"} so that it would be easier for the front-end to display it.

Two current related issues:
 - graph_json.py could be refactored: it has a lot of room for improvement in terms of readability and modifyability
 - graph_json_test.py is the slowest test we have, any improvements there would be welcome as well.

**Comment by anniesullie** [comment]
Is there more to do here?

**Comment by qyearsley** [comment]
I don't think so; the original bug report doesn't have an example page that we can use to verify the fix, but anecdotally, after the above fix (and other changes Chris made) I don't remember seeing a graph failing to load completely because one of the series had an error in graph_json.

The other things I mentioned above are separate issues from the original bug.
