### ISSUE TITLE
Dashboard does not update bugs associated with recipe bisect jobs.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1350]
**Issue by [robert...@chromium.org](https://code.google.com/u/114810703796781371055/)**
_2015-06-10T20:25:32.000Z_
_Originally opened as http://crbug.com/498972_

----

The bugs associated with bisect jobs launched with the 'use recipe' option do not get updated when the jobs complete whether successful or not.

**Comment by qyearsley** [comment]
@vuppalapu @ro-berto I think I've seen bugs where /update_bug_with_results has automatically pasted results from recipe bisect jobs, we should verify this with an example before closing.

**Comment by anniesullie** [comment]
This is fixed.
