### ISSUE TITLE
Tests may not be saved/re-put after editing sheriffed tests.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1351]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-12-17T16:37:14.000Z_
_Originally opened as http://crbug.com/443215_

----

For both Chromium Perf Sheriff and V8 Perf Sheriff, some tests have remained marked as monitored even though the list of monitored tests was changed at /edit_sheriffs. In both of these cases, the list of monitored tests was fixed when they were re-put.

This bug should be updated if we notice another case, or closed if something is done to make sure it won't happen again.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-01-06T01:02:41.000Z_

----

One possible change that might be made to edit_sheriffs which would help in some cases but probably wouldn't solve the underlying problem:

Upon editing a Sheriff (upon submitting the form at /edit_sheriffs), re-put all Test entities for the Sheriff even if they aren't being newly added.

**Comment by anniesullie** [comment]
I fixed this in https://codereview.chromium.org/2085523002/
