### ISSUE TITLE
Multiple (duplicate) bugs filed on issue tracker sometimes.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1352]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-08T20:13:19.000Z_
_Originally opened as http://crbug.com/475177_

---

Sometimes, when a sheriff files a bug from the perf dashboard, multiple bugs get created and the alert gets associated with the later bug number.

Example:
  bug 474381
  bug 474382

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-06T15:25:59.000Z_

----

This has been happening for a long time (at least 6 months, probably more) at a low rate (~1%, sometimes less or more) and it has been easy to work around, but is confusing when one encounters it the first time.

To investigate later, we may want to look at the logs for /file_bug.

To guarantee that the dashboard is doing the right thing, we need to guarantee that the dashboard makes exactly the right number of requests to the issue tracker: two requests, one two make the bug and the other to post a follow-up with a link.

It's also possible that this happens when the two requests to the issue tracker are too close together.

**Comment by benshayden** [comment]
Archiving.
