### ISSUE TITLE
units module is in tracing/base for non-ui but tracing/ui/units for ui

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1354]
Should converge to something coherent.

**Comment by dj2** [comment]
Should probably move the base stuff to base/units and leave the UI stuff at ui/units.

**Comment by natduca** [comment]
I think probably tracing/units would be best matched to ui/units

the two options that are consistent are

- tracing/units and tracing/ui/units
- tracing/base/units and tracing/ui/base/units

**Comment by natduca** [comment]
@petrcermak fixed this.
