### ISSUE TITLE
gjslint line numbers are wrong in presubmit warnings

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1355]
When you make a presubmit error in an html file, the line numbers are typically 4 lines off. I suspect its not including the html lines in the error reporting... but, I think this once worked...

**Comment by qyearsley** [comment]
I noticed this too before, using some version of closure-linter that's not in our third_party directory.

I just tried this 
```
     1	<html>
     2	  <head>
     3	  </head>
     4	  <body>
     5	    <script>
     6	      var a = 123;
     7	      var b = a
     8	    </script>
     9	  </body>
    10	</html>
```
and it correctly identified line 7, in the catapult presubmit with our version of closure linter, so I think it's probably also including the HTML lines. I think next time a case is observed an issue could be filed at https://github.com/google/closure-linter/issues.

**Comment by natduca** [comment]
Okie! I'll close this and reopen if I find a repro.
