### ISSUE TITLE
Focus issues in chrome://tracing

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1356]
_[Reported at http://crbug.com/522911]_

**What steps will reproduce the problem?**
1.Lunch chrome,navigate to chrome://tracing.
2.Press 'Tab' key and observe.

Unnecessary focus is seen on header part of chrome://tracing.

Unnecessary focus should not seen.

**Comment by petrcermak** [comment]
The **focus behavior is quite broken** at the moment. Here's another problem:

  1. Go to chrome://tracing
  2. Press Tab multiple times until the search input box is focused (6 times on the current Chrome Stable)
  3. Press Tab one more time

Expected behavior: The left arrow button next to the search input box should be focused.
Actual behavior: Nothing is focused. Moreover, pressing Shift+Tab (any number of times) does *not* return focus back to the input box.

**Comment by natduca** [comment]
If its okay I'd like to close this due to inactivity.
