### ISSUE TITLE
Missing stdio link on ChromiumPerf/linux-release/page_cycler.intl_ja_zh/... points.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1357]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-14T20:21:36.000Z_
_Originally opened as http://crbug.com/521104_

----

See:
https://chromeperf.appspot.com/group_report?bug_id=517531

There is no a_stdio_uri annotation in the JSON returned by /graph_json.

When I open that page and enter the following in the JS console:

  $('chart-container')[0].json.annotations[0][75]

I get:

{
  a_trace_rerun_options: null,
  error: 0,
  r_chromium: &quot;57767fecb49073e18c26d4e41208f5e754438232&quot;,
  r_commit_pos: &quot;337743&quot;,
  r_webkit_rev: &quot;198424&quot;,
  timestamp: 1436325216000,
}

**Comment by anniesullie** [comment]
New points are showing stdio links.
