### ISSUE TITLE
Use API keys instead of whitelist for /add_point.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1359]
Implementation notes:
- Using API keys requires creating a new backend endpoint API in app engine. The new API  would have just one method add_point, the client just has to send in the API key with the request. See: https://cloud.google.com/appengine/docs/python/endpoints/ 
- API key has to be generated in the developers console - you can limit API keys to certain user agents or IP’s however it is unlikely this would be used.

Advantages:
- Having API keys would allow another app engine app to post points to the perf dashboard
- It would also make things easier for the Chrome OS team -- they frequently have new machines with new IP addresses.

**Comment by anniesullie** [comment]
Note: there is a detailed proposal for this [here](https://docs.google.com/document/d/1ZZCx9RwtMKPFySHudHEprWVAeuR1EuUkGpZSoPOvEXs/edit)
