### ISSUE TITLE
Cannot scroll horizontally all the way on alerts page.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1362]
**Issue by [robert...@chromium.org](https://code.google.com/u/114810703796781371055/)**
_2015-06-22T20:25:32.000Z_
_Originally opened as http://crbug.com/503254_

----

When my browser is sized below a certain width (around one third of my screen approx.) I cannot scroll horizontally far enough to the left to see the graph links, same thing happens when scrolling right. This happens at least on Chrome stable linux.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-22T21:07:34.000Z_

----

I noticed this too on my chromebook, when one of the test names is long, the alerts table is too wide. Looks like the alerts table should have a max-width, and we should make sure the long test names get truncated appropriately when they can't fit.

**Comment by qyearsley** [comment]
To reproduce:
 1. Go to https://chromeperf.appspot.com/alerts
 2. Resize the browser window to be very thin (< 400 px)
 3. Observe that the check-boxes on the left are cut off.

**Comment by anniesullie** [comment]
This is fixed now.
