### ISSUE TITLE
Test-picker positioning changed in new versions of Chrome

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1364]
On version 46.0.2490.4 at https://chromeperf.appspot.com/report:
![image](https://cloud.githubusercontent.com/assets/3926653/9480333/4fef110a-4b37-11e5-9473-7d634d85ad01.png)

On version 44.0.2403.157 at https://chromeperf.appspot.com/report:
![image](https://cloud.githubusercontent.com/assets/3926653/9480338/622c7b64-4b37-11e5-8dcc-54233b9b84fb.png)

Still haven't confirmed whether this is considered a dashboard bug or Chrome bug, or specifically which version of Chrome it changes for.

**Comment by chrisphn** [comment]
This looks fixed in canary 47.0.2519.0.

**Comment by qyearsley** [comment]
Indeed! I'm not observing it anymore on linux dev channel Chrome either.
