### ISSUE TITLE
Display unit scaling

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#1366]
I have traces on the order of hours or days, and thus the ruler at the top has ticks every "500000s," and I have events with wall times like "10,229,600.104 ms." It would be helpful to either:

1. Automatically scale the display units (to minutes, hours, days) with the size of the number, or
2. Allow trace data to manually express the scale(s) of the trace or trace events. (Maybe this would be related to issue #624.)

@fmeawad expressed interest in doing this. If not, I can take a look.

**Comment by fmeawad** [comment]
Go for it.

**Comment by natduca** [comment]
Lets merge into #1531
