### ISSUE TITLE
Please migrate energy_consumption_mwh on ANDROID ONLY to application_energy_consumption_mwh

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1372]
See https://codereview.chromium.org/1220463002/ for background. Will need to migrate the following:
ChromiumPerf/android\*/\*/energy_consumption_mwh
ClankInternal/\*/\*/energy_consumption_mwh

I've already updated monitoring.

**Comment by qyearsley** [comment]
Migration job now started for the two sets of test paths listed above.

**Comment by qyearsley** [comment]
This is now done.
