### ISSUE TITLE
Bisect dialog box and tooltip is very small when opened on the bottom of the page

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1373]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-24T21:16:15.000Z_
_Originally opened as http://crbug.com/504114_

----

I think that after cl/95576574 some of the dialog boxes now have variable height; might be a good idea to add a min-height so that they don't get too small.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-26T16:21:46.000Z_

----

Issue 521109 has been merged into this issue.

**Comment by qyearsley** [comment]
Note: I tried setting a min-height on [chart-tooltip](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-tooltip.html) but that didn't appear to solve the problem. This problem still might be solved by adjusting the CSS of something inside chart-tooltip, or by otherwise changing something about the paper-action-dialog inside chart-tooltip.

**Comment by anniesullie** [comment]
I think this is fixed now.
