### ISSUE TITLE
Keep track of alerts triaged by each user.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1375]
**Issue by [jeffgri...@chromium.org](https://code.google.com/u/102197112613496205360/)**
_2014-06-17T15:57:25.000Z_
_Originally opened as http://crbug.com/385658_

----

Create Google badges for people's who pages that they unlock after accomplishing various sheriffing achievements like triaging 100/1000/10000 alerts, filing 10/100/1000 bugs, etc.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-07-12T01:06:31.000Z_

----

This would be pretty cool.

Currently the dashboard doesn't keep explicit track of who is the active sheriff for a sheriff rotation -- it just checks who the "current" sheriff is by reading from a particular URL before sending an email alert.

But, the dashboard can tell who's logged in when someone performs some action like triaging an alert.

I imagine this would be done by:
 (1) Add a User model which keeps tracks of dashboard users by email address and keeps track of what they've been doing.
 (2) In bug_create and bug_comment etc, update this data.
 (3) Somewhere (main page or alerts page when logged in?) display some of this info.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-08T19:50:58.000Z_

----

Note: A log could be kept of triage actions even without having User entities stored in the perf dashboard. One possible way to do this would be to add calls to QuickLogger.Log() in edit_anomalies.py, associate_alerts.py and file_bug.py.

**Comment by anniesullie** [comment]
I'm closing this but will consider a mini leaderboard in the sheriff mail that gets sent out.
