### ISSUE TITLE
Allow user to manually create alerts.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1381]
**Issue by [primi...@chromium.org](https://code.google.com/u/109349271600817121881/)**
_2015-07-22T13:38:54.000Z_
_Originally opened as http://crbug.com/512806_

---

For more context see the discussion

[chromium-dev] Perf dashboard: How to attach bugs when there is no exclamation mark?

It looks like there is no easy way to manually create an alert (exclamation mark) through the chromeperf dashboard. The use case, which seems legit, it to click on a regression which was not automatically detected by GASP, attach a bug to that and create an exclamation mark.
I might be wrong, but I am convinced I did see that at some point.
Was it deliberately removed or just got lost by accident?

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-22T16:02:46.000Z_

----

I don't think that feature existed. (Possibly related features: it's possible to nudge nearby alerts, and it's possible to start bisects if there's no alert.)

In any case, if an alert didn't fire and the series is monitored, then this is generally because the current alerting thresholds for that test weren't satisfied for that point; so the thresholds should be adjusted. (Note: perf dashboard no longer uses GASP).

So, it's probably a good idea to figure out why the dashboard didn't fire an alert there, and fix that -- this page can be useful:
https://chromeperf.appspot.com/debug_alert?test_path=ChromiumPerf%2Fchromium-rel-mac9%2Fmedia.tough_video_cases%2Fidle_wakeups_gpu&rev=339234 (the "test path" can be copied from above a graph)

**Comment by benshayden** [comment]
Archiving, and making a note in chromeperf-v2-status to do this in V2SPA.
