### ISSUE TITLE
Stoppage alerts may not always be marked as recovered when new points arrive for the test.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1387]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-02T23:18:50.000Z_
_Originally opened as http://crbug.com/495872_

----

When I look at and try to use the new stoppage alerts table, the first thing I wonder when looking at an alert is: &quot;Is the test running again, or is it still stopped?&quot; (i.e. should I do something about this now or not?)

This would involve adding a new boolean property called &quot;recovered&quot; to the StoppageAlert model, and this information would then be shown in the alerts table.

Implementation notes:

I think that this should be implemented by:
 - Add a key property to the Test when a stoppage alert is made.
 - When a new point is added to the Test, update the stoppage alert.

This would mean that stoppage alerts would be marked as recovered as soon as new data arrives, and this is parallel to the way it works for the &quot;deprecated&quot; property.

Alternative:
 - In auto_triage, fetch all recent stoppage alerts.
 - For each one, fetch the latest row of the test.
 - Use that information to update each stoppage alert.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-12T17:07:02.000Z_

----

cl/95757487.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-01T18:07:19.000Z_

----

Apparently not fixed, see bug 506165.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-07-08T17:13:36.000Z_

----

A couple days ago I made a change to show the recovered status of the alert (in the bug ID field of each row, cl/97698885).

Now, it is clear that some of the recovered alerts are being marked as recovered but others are not: https://chromeperf.appspot.com/group_report?bug_id=506165

Currently, the place where stoppage alerts are being marked as recovered is in add_point_queue, in _GetOrCreateTest:

  ...
  if existing.stoppage_alert:
    alert = existing.stoppage_alert.get()
    alert.recovered = True
    alert.put()
    existing.stoppage_alert = None
    properties_changed = True
  ...

So, if there is no stoppage alert associated with the test, it won't get updated. Querying the datastore confirms that this is the case:

  from dashboard.models import stoppage_alert
  q = stoppage_alert.StoppageAlert.query(
      stoppage_alert.StoppageAlert.bug_id == 506165)
  for a in q.fetch(limit=50):
    if not a.recovered:
      print a.test.get().stoppage_alert  # Prints None every time

The stoppage_alert property of the test should be set when the stoppage alert is created, in stoppage_alert.CreateStoppageAlert.


One possible explanation is that an error (datastore error, timeout error, etc.) happens at some point in either add_point_queue._GetOrCreateTest or stoppage_alert.CreateStoppageAlert.

In order to guarantee that the alerts are properly updated, maybe some extra checks need to be added -- or maybe some different strategy should be used.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-27T22:14:55.000Z_

----

**Comment by anniesullie** [comment]
Duping this against #2187
