### ISSUE TITLE
Send improvement_direction when starting bisects.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1390]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-12-17T16:58:04.000Z_
_Originally opened as http://crbug.com/443221_

---

Now that bisect supports the parameter improvement_direction, we can start actually using it when making the config dict when starting bisect jobs from the perf dashboard.

This will be a change in start_bisect.py. The Test entities have a property called improvement_direction.

**Comment by qyearsley** [comment]
@ro-berto

Correction to initial post: this will be a change in [start_try_job.py](https://github.com/catapult-project/catapult/tree/master/dashboard/dashboard/start_try_job.py).

Note, we should keep in mind that sometimes people want to bisect to find the cause of an improvement, so aborting just because it's an improvement doesn't always make sense. If we implement this we may also want to add a control for the user to explicitly say they expect it to be an improvement.

Another possible enhancement related to this would be to send the *expected relative change* to bisect (#1401).

**Comment by benshayden** [comment]
Archiving.
