### ISSUE TITLE
Split the RAIL score report by RAIL type and RAIL name

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1391]
Follow-up on #1335

@dj2 @natduca

**Comment by dj2** [comment]
Any progress on this? What are the followup pieces to be completed in this bug?

**Comment by philippebeaudoin** [comment]
I was trying to remember what this was standing in for and couldn't. As a first step, I'm be working on splitting the RAIL score report by RAIL, process and thread.

**Comment by dj2** [comment]
Updated the title to match. We can file followup issues if there are more things we want to do later.

**Comment by philippebeaudoin** [comment]
Doesn't really make sense to split it by process/thread, but by type and name it does. (Updated title.)

**Comment by philippebeaudoin** [comment]
Screenshot:
<img width="713" alt="screen shot 2015-09-10 at 1 34 33 pm" src="https://cloud.githubusercontent.com/assets/11399419/9795833/f28dad50-57c0-11e5-99ce-d7aec6bf7ffa.png">

**Comment by dj2** [comment]
Suggestions from seeing this
* can you round off the rail score values? 2-3 digits precision is probably enough.
* can you drop the rail_ from the titles? Seems redundant when we really want to see Load, Animate, Response, etc
* can we display the keys in RAIL order?

**Comment by benshayden** [comment]
In the vein of eliminating redundancy, can you multiply scores by 100 and round to eliminate "0."?

Is there just one Succeeded Load in that screenshot, or is that all of the Succeeded Load IRs averaged?

When you average IR scores, do you use RAILScore so that low scores aren't hidden by high scores?

Do you want to display pain and efficiency sub-scores somehow?

**Comment by philippebeaudoin** [comment]
Thanks for the excellent ideas! I think we should do them all. I'll implement the straightforward ones but I suggest we have follow-up CLs for:
1) Removing the rail_ prefixes
2) Sorting in RAIL order 
3) Display pain and efficiency
Rationale: (1) and (2) are easy to do in a hacky way but I'd rather have a cleaner mechanism that other clients could rely on. (3) is just a natural thing to do in a follow-up CL, I'd rather keep this one as simple as possible.

Answers:
- Is there just one Succeeded Load in that screenshot, or is that all of the Succeeded Load IRs averaged?
  - It's the average of all Succeeded Load from all loaded traces. If you click on the line you get the histogram for individual Succeeded Load IR scores. Eventually you should be able to click on one of the bin and see a sample of the traces+IR that fall in this bin so you can dig further.

- When you average IR scores, do you use RAILScore so that low scores aren't hidden by high scores?
  - I do use RAILScore to compute the "overall score" from individual IRs in a trace, then I average all the scores from all the traces. I think it's better than to consider "all the traces as one" and let a bad trace bring the overall RAIL score up.
  - I do not use it on deeper levels for similar reasons. I'm more interested in the distribution of RAIL scores per RAIL type (and name) than I am in a "score for all Animation IRs in a trace". Identifying slow IRs is still possible using the histograms.
  - Note that the above screenshot is wrong, there should be more than 1 sample in the `rail_animate > CSS` bin I'm changing the CL so that even with a single trace you get a full distribution of RAIL scores for a given RAIL type or name.

**Comment by natduca** [comment]
Re the rounding to 2 digits, lets avoid that. Right now, I'm trying to get all formatting centralized in the scalar span code. That currently I think implies that we do the same number of digits of precision for everything. I'd prefer to just leave that and get us to common presentation code, than for us to have perfectly refined UI.

**Comment by philippebeaudoin** [comment]
Used the scalar_span for this so I'll benefit from any improvement you do
there.
