### ISSUE TITLE
Create a "power consumption" highlighter

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1392]
It would be great if there were a power highlighter, similar to the vsync highlighter. The highlighter could create vertical stripes on the tracks, similar to how the vsync highlighter does, except the saturation of the stripe would be determined by how much power is being consumed during that timestamp.

**Comment by dj2** [comment]
I don't think a highlighter would work. Drawing vertical lines through the trace can be very intrusive. Having a track for power which does that is fine, but extending it over other tracks makes things hard to read.

You could also have something like an auditor alert for significant power draw.

**Comment by zeptonaut** [comment]
I don't agree. Drawing vertical lines through the trace isn't intrusive at all as long as they can be turned off, like they can with the vsync highlighter. I imagine this is a feature that will be turned off most of the time. However, when someone's investigating battery problems and wants to correlate battery usage with what's happening on a track that's all the way at the bottom of the page, it's going to be really useful to not have to scroll up and down all the time. This is something that someone (I think Chris Cameron?) has already mentioned is a huge pain in the butt and has slowed down analysis of some of the traces that Aaron put together for him by hand.

**Comment by dj2** [comment]
The better solution to that problem is to allow drag and drop of tracks. You can re-order them as you need to see the content you want grouped together.

Our UI is already hard to use, adding more knobs is going to make it worse. I've already made the mistake several times of thinking flow events are broken when they were just turned off. It's easy to turn things off and forget, then two months later not be able to figure out why the don't work.

**Comment by zeptonaut** [comment]
I'm definitely not convinced that adding a highlighter for this is the best solution. However, I'm also not convinced that reordering tracks would entirely solve this problem.

It seems like there's at least some consensus that trace viewer has a data locality problem. By this, I mean that the data may be there, but it's not close enough on the screen for you to draw the conclusions that you need to. The more tracks there are, the more likely this is to happen.

Collapsing tracks isn't sufficient for two reasons:

1. Even if you collapse all of the tracks, there may be enough of them that the data is still too far apart.
2. Keeping the right tracks *uncollapsed* requires knowing beforehand exactly which tracks you care about, which isn't always true.

Allowing dragging and dropping of tracks solves the first problem. If there are two tracks you know you want to compare, just drag them close to each other.

It doesn't solve the second problem, though, because you'd still need to know which tracks you want to drag next to each other. In other words, dragging and dropping helps solve the examination problem, but not really the exploration problem.

Technically, the time span selector tool does alleviate the second problem. Have a couple of areas of high power usage that you want to compare to other tracks to find out why? Highlight one of them and scroll down to find out why. Rinse. Repeat.

This is menial, though, and we already know that power is the sort of global information that you probably want to compare against lots of other tracks. Why can't we automatically show these vertical lines for you? In my mind, that's essentially what the highlighters allow for - it's an automatic, more flexible version of the time span selector tool. (This matches up well with how it's already being used for frames.)

If all of these highlighters are off by default, then it doesn't clutter up the UI at all. We could make them available really quickly to the user with shortcuts like:

* `CTRL-p` Toggle the power highlighter.
* `CTRL-v` Toggle the vsync highlighter.
* `CTRL-g` Toggle the GPU highlighter.
* `CTRL-c` Toggle the CPU highlighter.

(Warning: didn't verify these are available. Just giving examples.)

What do you think?

**Comment by dj2** [comment]
The problem is, if they're off, people don't know they're there. They forget their off and think the information isn't available. We'd also have to provide toggles in the View Options dialog and end up with a lot of options.

I thinking doing this as a highlighter isn't the right approach. Your highlighter also doesn't solve issue number 2 as if you have the highligher off (the equivalent of collapsing the track) you can't see the information.

Dragging and dropping lets you get the information you need closer together without making the rest of the trace hard to read.

**Comment by zeptonaut** [comment]
> The problem is, if they're off, people don't know they're there. They forget they're off and think the information isn't available. 

There are useful options in lots of programs that people forget about if they're off. In Gmail, tons of users don't know filters exist. Lots of people never use keyboard shortcuts, either. That doesn't mean that both aren't really useful for those of us that use them.

> We'd also have to provide toggles in the View Options dialog and end up with a lot of options.

Why is this bad? It seems like that's what the menu is there for. Also, at least for power usage, we should only be showing this option for the small percentage of users that actually have power data from a BattOr.

> Your highlighter also doesn't solve issue number 2 as if you have the highlighter off (the equivalent of collapsing the track) you can't see the information.

True. But, if you have the power highlighter off, all that's required to turn it on is a quick press of `CTRL-p`, whereas with dragging and dropping, you have to click on the track and drag it to the top of a (potentially very long) list of tracks. Also, like I said earlier, dragging and dropping doesn't scale well if you want to compare a single track against lots of other tracks, like you might want to do when figuring out what's consuming power. A highlighter does, though.

I honestly have no idea whether the power highlighter would be too distracting if it were actually enabled. It's possible it would be. Luckily, it's pretty trivial to implement, so I think I'm just going to go ahead and do it tomorrow in a branch and see what it looks like. I'll upload it and let you check it out for yourself once I do this, and then we'll at least have a better idea of what it might look like.

**Comment by zeptonaut** [comment]
Closing this now, as I think that we'll fix this problem with the more-general pinning of tracks instead of a highlighter.
