### ISSUE TITLE
Load and Idle IR collect related events outside their scope.

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1395]
In the following example:
```
[        Load IR        ][       Idle IR       ]
           [          SLICE  1           ]
                                   [ S2 ]
```
Where slice 1 and slice 2 have not been associated to any IR.
We would expect Slice 1 and 2 to be part of the Load IR because Slice 1 starts during load and S2 is in its hierarchy. However they get associated to the Idle IR.

**Comment by philippebeaudoin** [comment]
False alarm, this seems to be working. I'm adding a test nonetheless.

**Comment by dj2** [comment]
Is this now done?
