### ISSUE TITLE
Alignment of alert indicators in some graphs seems off.

### ISSUE THREAD

**Issue by ro-berto** [catapult-project/catapult#1398]
https://chromeperf.appspot.com/group_report?bug_id=519204

![screenshot 2015-08-29 at 5 32 29 pm](https://cloud.githubusercontent.com/assets/1222692/9565168/3ca80b70-4e74-11e5-86c2-39283292bc3f.png)

**Comment by chrisphn** [comment]
The above link no longer has alerts.  Another example:

https://chromeperf.appspot.com/report?sid=47353a76aeddefde4a42d1425bd9fa87c5d0f86a7b66671533f852b2bec5d4f5&rev=346005
