### ISSUE TITLE
Can't view graphs for blink_perf.bindings on perf dashboard /report page

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1400]
To reproduce, load https://chromeperf.appspot.com/report

Notice on the JavaScript console, there is a 404 error for https://chromeperf.appspot.com/dashboard/elements/xhr-element.html

Now select Test suite "blink_perf.bindings" and Bot "linux-release". A subtest menu never appears, so it's not possible to add a chart to the page. I can get this to work with sunspider, so not sure what the problem is--is the data missing? 

(Hit this while trying to investigate crbug.com/500958)

**Comment by qyearsley** [comment]
Not reproducing this anymore... this bug is probably obsolete.
