### ISSUE TITLE
Send "expected relative size" (expected regression size) to bisect.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1401]
Proposal: the dashboard might send the "regression size" (or improvement size), and if the initially reproduced regression between the given revisions isn't within an order of magnitude, then we could abort.

e.g. expected regression is 12.4%, reproduced regression is 2.1%, we could probably just abort. Or if the expected relative change is 3.5% and the reproduced relative change is -1.2% (i.e. the other direction) then it would also make sense to abort.

**Comment by anniesullie** [comment]
@dave-2 should we still do this?

**Comment by benshayden** [comment]
[This appears to be done.](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/pinpoint_request.py#L296)
