### ISSUE TITLE
Migrate to Google Cloud SDK

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#1407]
Not completely certain, but I think the [Cloud SDK](https://cloud.google.com/sdk/cloudplatform#appengine) is intended to replace the App Engine SDK. [This change](https://codereview.chromium.org/1305953002/) assumes the App Engine SDK is installed. Do we want to switch the dev server and deployment over to the Cloud SDK?

**Comment by qyearsley** [comment]
You're right,  looks like the gcloud tool for managing app engine apps is still in beta, but it will likely be replacing dev_appserver.py and appcfg.py, and it has a somewhat cleaner-looking command interface.

```
$ appcfg.py upload --application=chromeperf <app_dir>
```
is replaced by
```
$ gcloud preview app deploy --project=chromeperf <app_dir>
```
and
```
$ dev_appserver.py
```
$ gcloud preview app run <app_dir>
```

It looks like both `catapult_build/appengine_deploy.py` and `catapult_build/appengine_dev_server.py` could be replaced by one script which invokes `gcloud preview app` and passes command line arguments (including run, etc.) on to gcloud.

As far as depending on the libraries goes: the Cloud SDK includes all the same third party libraries as the App Engine SDK, including httplib2, six, uritemplate, oauth2client, and apiclient. As long as the deployment script can find out where the SDK is, then it can use these libraries.

**Comment by dave-2** [comment]
Great! Those libraries will make migrating even easier.  One other difference is that the application name and version are specified using the gcloud command, instead of in app.yaml.

**Comment by qyearsley** [comment]
@simonhatch 

I believe the next steps are:

 1. Add a script in catapult to download the latest gcloud SDK (later this can be done with binary manager)
 2. a) Change deploy/dev-server scripts to use Google Cloud SDK

 b) Change [catapult recipe](https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/recipes/catapult.py) to download gcloud SDK (and set up paths when running dashboard tests)

**Comment by anniesullie** [comment]
@Apeliotes since binary manager was mentioned

**Comment by simonhatch** [comment]
https://codereview.chromium.org/1452333002/

There's also another issue we found using gcloud, we needed to make changes to the TempDeploymentDir to copy instead of using symlinks, gcloud seemed to have a lot of problems with those.

**Comment by dave-2** [comment]
lol we are duplicating work. Firefighter also has a module that deals with the symlink issue. (Quick summary: Docker doesn't follow symlinks when building a container image, so you can't deploy with symlinks. But dev server still runs, since it doesn't build a Docker container.)

https://codereview.chromium.org/1288193004/diff/350001/firefighter/bin/packaging.py

**Comment by vinterstum** [comment]
Yep that's literally the exact same issue we have hehe.

Note there's one recent change to the Cloud SDK here: 'gcloud preview app run' is no longer the recommended thing to do, it's back to just running 'dev_appserver.py' directly now.

**Comment by simonhatch** [comment]
Yeah the docker issue and also I think we also ran into some issues when deploying managed vm modules, and just copied everything as the nuclear option so that we could move on.

Also https://codereview.chromium.org/1452333002/diff/140001/perf_insights/bin/deploy_perfinsights, gcloud recommends deploying each module individually, rather than all at once.

**Comment by simonhatch** [comment]
Will the binary manager always check for/download the latest version of the sdk? I just ran into an issue running local dev_server where a python lib threw a NotImplemented exception (1.9.26, tempfile), which doesn't happen in a new version 1.9.28.

**Comment by dave-2** [comment]
**Done.**
