### ISSUE TITLE
Shift-click select in the alerts-table is broken in M44.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1410]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-27T18:56:59.000Z_
_Originally opened as http://crbug.com/481605_

---

<b>What steps will reproduce the problem?</b>
1. Navigate to https://chromeperf.appspot.com/alerts?triaged=true
2. Click the first checkbox.
3. Shift-click the third.
4. Shift-click the fifth.

<b>What is the expected result?</b>
Upon shift-clicking the third, the second and third checkboxes will be selected.
Upon shift-clicking the fifth, the fourth and fifth checkbox will then be selected.

What happens instead of that?
Upon shift-clicking the third, the third checkbox is selected.
Upon shift-clicking the fifth, the second and fifth is selected.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-27T19:06:26.000Z_

----

Note: This bug apparently doesn't manifest in stable (M42) but does in M44.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-27T19:06:50.000Z_

----

**Comment by qyearsley** [comment]
Now I know it's not just me who sees this (since #1580 was filed). I believe this is currently the most annoying front-end bug, thus marking it as P1.

**Comment by qyearsley** [comment]
Still haven't looked at this and nobody else has complained about it since October, so downgrading priority.

**Comment by benshayden** [comment]
[Fixed](https://github.com/catapult-project/catapult/commit/817b8684be607f1ac5aad1e6ef5713188a8cfb2c)
