### ISSUE TITLE
bench_find_anomalies is broken.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1414]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-07T03:11:11.000Z_
_Originally opened as http://crbug.com/497528_

----

I tried to run the following:

from dashboard import bench_find_anomalies

NAME = 'steppiness_0_1'
DESC = 'June 6'
print 'Running BenchFindAnomalies.'
bench_find_anomalies.BenchFindChangePoints(NAME, DESC)

After this, there some errors in the logs for the endpoint /_ah/pipeline/run as follows:

    D 20:06:22.566 Running dashboard.bench_find_anomalies.SimulateAlertProcessingPipeline(*(u'steppiness_0_1', 5610913336918016L), **{})#a2e0db92c47d4923b2c70811904d7df0
    E 20:06:22.622 Generator dashboard.bench_find_anomalies.SimulateAlertProcessingPipeline(*(u'steppiness_0_1', 5610913336918016L), **{})#a2e0db92c47d4923b2c70811904d7df0 raised exception. TypeError: &lt;lambda&gt;() takes exactly 1 argument (2 given)
      Traceback (most recent call last):
        File &quot;dashboard/zipped_libs/mapreduce.zip/mapreduce/third_party/pipeline/pipeline.py&quot;, line 2120, in evaluate
          self, pipeline_key, root_pipeline_key, caller_output)
        File &quot;dashboard/zipped_libs/mapreduce.zip/mapreduce/third_party/pipeline/pipeline.py&quot;, line 1094, in _run_internal
          return self.run(*self.args, **self.kwargs)
        File &quot;dashboard/bench_find_anomalies.py&quot;, line 166, in run
          change_points = find_change_points_func(test, data_series[0:i])
      TypeError: &lt;lambda&gt;() takes exactly 1 argument (2 given)

It's likely that the CL (cl/87664851) which added &quot;steppiness_0_1&quot; and other &quot;find anomalies&quot; functions was incorrect.

**Comment by qyearsley** [comment]
First change that needs to be done:

When I run `bench_find_anomalies.SetupBaseDataForBench()` I get a NeedIndexError on bench_find_anomalies.py line 451 in _CreateTestBench for index:

```
- kind: Row
  properties:
  - name: internal_only
  - name: parent_test
  - name: revision
    direction: desc
  - name: value
```

This should probably be fixed by using datastore_hooks.SetSinglePrivilegedRequest.

**Comment by anniesullie** [comment]
ping on this?

**Comment by qyearsley** [comment]
Today I made a little CL to try to get `SetupBaseDataForBench` working again: https://codereview.chromium.org/1730803002

After that, I tried running this on the interactive console:
```python
from dashboard import bench_find_anomalies
bench_find_anomalies.BenchFindChangePoints('segment_size_4', 'test bench run')
```

The next thing that goes wrong is:

```
Traceback (most recent call last):
  File "pipeline/pipeline/pipeline.py", line 2144, in evaluate
    self, pipeline_key, root_pipeline_key, caller_output)
  File "pipeline/pipeline/pipeline.py", line 1110, in _run_internal
    return self.run(*self.args, **self.kwargs)
  File "dashboard/bench_find_anomalies.py", line 166, in run
    change_points = find_change_points_func(test, data_series[0:i])
TypeError: <lambda>() takes exactly 1 argument (2 given)
```

Note that the entry for that experimental function in bench_find_anomalies.py is:
```python
_EXPERIMENTAL_FUNCTIONS = {
    'find_change_points_default': find_change_points_exp.RunFindChangePoints,
    'find_change_points_absolute_change_threshold':
        find_change_points_exp.FindChangePointsWithAbsoluteChangeThreshold,
    'segment_size_4': lambda(test, series):
                      find_change_points_exp.RunFindChangePoints(
                          test, series, min_segment_size=4),
}
```

The root cause for this is a mistake in my understanding of lambda syntax in Python. `lambda(x, y): ...` is actually a function that takes one tuple as an argument, and not a function that takes two arguments. The correct way to do that should have been `lambda x, y: ...`.

**Comment by qyearsley** [comment]
Next steps:

1. Run bench_find_anomalies.SetupBaseDataForBench (done)
2. Start experiments (done, started experiments with steppiness_0_1 and steppiness_0_5 
3. Check results: https://chromeperf.appspot.com/get_logs?namespace=bench_find_anomalies&name=report

**Comment by qyearsley** [comment]
Results for those experiments there; now we want to run an experiment for #1898.
