### ISSUE TITLE
The revision range of a stoppage alert should ideally be a range of the first build that didn't report the metric.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1415]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-25T22:55:02.000Z_
_Originally opened as http://crbug.com/504594_

---

When tracking down the cause of a stoppage, it would likely be more useful to know the revision range for the first build that _didn't_ report data, rather than the revision of the last build that did.

However, this may be non-trivial since, for the test/platform that has a stoppage alert, there's no data about the first build that didn't report that metric; this information would have to be collected from data about other tests, or maybe from build.chromium.org.

Additionally, of course, not all data comes from Buildbot, and we can't assume that all data is related to a build on a waterfall.

**Comment by benshayden** [comment]
Stoppage alerts are gone.
