### ISSUE TITLE
Changing revision range with slider in performance dashboard resets set of selected graphs.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1416]
**Issue by [brucedaw...@chromium.org](https://code.google.com/u/104060862261843546941/)**
_2015-06-20T00:19:30.000Z_
_Originally opened as http://crbug.com/502507_

---

When looking at graphs on the Chrome Performance Dashboard (such as https://chromeperf.appspot.com/group_report?bug_id=491920) it is sometimes useful to enable additional data points to be graphed. It is also useful to change the time-range being viewed by dragging or sizing the green bar on the bottom graph.

Unfortunately, every time that the green bar is moved or size the selected set of graphs is reset. The users choice of data points to be graphed should be respected.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-21T02:19:35.000Z_

----

Just tried this and confirmed that the series selection gets reset after changing the revision range, on both the /report and /group_report page, and I agree that would be better if it weren't reset.

**Comment by qyearsley** [comment]
I think that this might have been fixed now, when I try to reproduce this again I'm not seeing this bug.

@chrisphn Do you remember what might have fixed this?

**Comment by chrisphn** [comment]
Nope.
