### ISSUE TITLE
Perf dashboard should highlight when a page in pageset is added/removed.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1417]
**Issue by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2015-04-28T15:15:53.000Z_
_Originally opened as http://crbug.com/481986_

----

It's not clear right now when you're looking at an alert that was caused by adding a new page to a pageset.

It would be awesome to have the perf dashboard expose this somehow, especially in the /group_report page.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-28T17:43:45.000Z_

----

I agree -- I've seen alerts before that are just caused by adding/removing a page, and it is confusing.

Here's how I think this might be done:

After finding an Anomaly:
 1. Fetch the Row entities of all descendant tests for the revision with the alert (the Anomaly's end_revision).
 2. Likewise, fetch all Row entities of all descendant tests for revision just before the alert (Anomaly's start_revision - 1).
 3. If the number fetched is different, add a property to the Anomaly entity which indicates that a sub-test was added or removed (properties will have to be added to Anomaly).
 4. Surface this information in alerts-table (add a column) and chart-tooltip (add warning text).

**Comment by qyearsley** [comment]
**Comment by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2015-04-28T17:47:09.000Z_

----

I like it!

**Comment by anniesullie** [comment]
I think we'll end up doing something more like per-page alerting here.
