### ISSUE TITLE
No graph and no submenu show for link from chromium.perf (for android-nexus4/smoothness.tough_animation_cases)

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1418]
**Issue by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2014-12-23T15:04:33.000Z_
_Originally opened as http://crbug.com/444861_

----

Chrome version: 39.0.2171.71 (Mac)
Url: https://chromeperf.appspot.com/report?masters=ChromiumPerf&amp;bots=android-nexus4&amp;tests=smoothness.tough_animation_cases&amp;rev=309546

Please copy and paste any errors from JavaScript console (true to open):
No errors, just this output:
 graph.update started
report_bin.js:164 graph.update returned after no selection was given.

Please describe the problem:
I am logged into my google.com account. No third menu and no graph shows up at this url, which came from the buildbot page that posted data to the graph. When I log out, I get &quot;no data available&quot;.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-12-23T17:21:57.000Z_

----

Note:

When I load that URL, I get a page with a third menu which is by default set to "input_event_latency_discrepancy", and the chart-container shows the "No data available" warning.

But if I select something else in the third menu, then there is data.

New points for this test:
https://chromeperf.appspot.com/new_points?pattern=ChromiumPerf%2Fandroid-nexus4%2Fsmoothness.tough_animation_cases%2F*&num_points=100&max_tests=30

**Comment by anniesullie** [comment]
This is super old, n4 doesn't exist anymore
