### ISSUE TITLE
Filter pages (and show average series) dynamically in charts on the dashboard.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1419]
**Issue by [epen...@chromium.org](https://code.google.com/u/103125687372269366442/)**
_2014-07-14T21:51:58.000Z_
_Originally opened as http://crbug.com/393746_

----

All the new page-sets I see getting added lately are basically just to get an average over a different subset of pages. It would be awesome if one could filter out a set of pages from an existing page set, resulting in what looks like a different page-set on the bots (with a different average, etc.).

It doesn't need a good dashboard UI or anything, just a custom URL param, or an entry in a file somewhere.

The same would also be useful for results (ie. filter out all but one result, for clarity).

I imagine bisects might be more difficult, but even without that it would be nice feature. The filter string might be the same as a --page-filter, in which case a bisect could still be performed?

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2014-07-16T23:10:24.000Z_

----

Are you thinking of just using this to experiment with running the tests locally with different page sub-sets, or were you suggesting making it so that you could do this with charts on the perf dashboard?

If we wanted to do this on the perf dashboard, then we'd have to add functionality so that it computes the averages itself from existing data, perhaps on the front-end; currently, the averages are all sent to the dashboard already-computed.

**Comment by anniesullie** [comment]
We'll probably take a different approach based on tbmv2 if we do this, so closing for now.
