### ISSUE TITLE
Use material-icons icon font for icons on the dashboard.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1421]
Currently the dashboard is using a mix of unicode characters and core-icon and core-icon-button characters for icons. Now for alert icons it's using the [material design icons](http://google.github.io/material-design-icons/#icon-font-for-the-web) icon font.

Using the core-icon Polymer has a couple little disadvantages - the size can't be controlled without using the deprecated ::shadow pseudo-selector and also issues like #1361. Using unicode characters is generally simple but some icons don't look quite as nice as some of the [material design icons](http://google.github.io/material-design-icons/#icon-font-for-the-web).

After submitting https://codereview.chromium.org/1321213004, it would be nice to make the rest of the icons consistent.

**Comment by qyearsley** [comment]
@chrisphn does this sound like a good idea? Or, not so important?

**Comment by chrisphn** [comment]
I think core-icons and core-icon-buttons are fine.  I got core-icons to work as alerts as well (https://dev-chrisphan-7c2844ed-dot-chromeperf.appspot.com/report?sid=1fcd95f64cc59a56e4701223a3e860e61ce674853fb244155829a93b1a8c459f&start_rev=342572&end_rev=346324).  core-icon size can be changed with style.  Most of the time for quick use, the style doesn't need to be changed.  And in the future more options when upgrade to Polymer 1.0:  

https://github.com/polymerelements/iron-icons

**Comment by qyearsley** [comment]
Makes sense; I'll close this issue for now since I don't think we're planning to change all the icons now.
