### ISSUE TITLE
Performance/Test dashboard background turned black again

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1423]
**Issue by [miu@chromium.org](https://code.google.com/u/miu@chromium.org/)**
_2015-08-01T22:30:31.000Z_
_Originally opened as http://crbug.com/516185_

----

Not all renderers of performance/test dashboard pages default to a white background.  While Chrome desktop uses a white background by default, flinging to Chromecast results in very hard-to-read graphs/summaries because it defaults to a black background.

There was a change about 6 months back (IIRC?) to add a CSS style to default everything to a white background.  It appears someone took that out again.  Perhaps someone could add it back and add a comment to make sure it isn't removed again in the future?  ;-)

**Comment by qyearsley** [comment]
**Comment by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2015-08-01T22:37:56.000Z_

----

Chris, can you take a look, since you've been doing some style changes? We want to explicitly add a white background to the body of the page so that it renders white on all user agents (some user agents default to black)

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-09-01T20:23:16.000Z_

----

Screenshots no longer visible, thus removing Restrict-View-Google

**Comment by qyearsley** [comment]
@chrisphn

**Comment by chrisphn** [comment]
Can't reproduce this.  Just tried it on my Chromecast.  Let me know if this is still a problem.
