### ISSUE TITLE
Some test data is not being added due to error in add_point_queue "Request was aborted after waiting too long..."

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1424]
**Issue by [hadd...@chromium.org](https://code.google.com/u/hadd...@chromium.org/)**
_2015-04-16T20:30:34.000Z_
_Originally opened as http://crbug.com/477755_

----

For some request the /add_point handler returns 200, however the testdata is not making it to the datastore and is being lost.

The logs reveal the following error that might be related and should be resolved.

Request was aborted after waiting too long to attempt to service your request.

This seems to be related to the /add_point_queue handler.

Please investigate and fix this issue to prevent data loss.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-16T20:36:19.000Z_

----

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-20T20:26:26.000Z_

----

Update: The first thing I'll try here is to change the task queue config in app-engine to retry requests more often. (cl/91613917.)

I'm not sure if I'll be able to see if this solves the problem though, since some requests will still fail before being retried, which means this error may still appear in the logs.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-23T18:00:42.000Z_

----

This problem is still not really solved. As of today, I still see many entries in the logs with that same message: "Request was aborted after waiting too long to attempt to service your request."

The reason why this is an issue in the first place is because we decided to make a trade-off to put the time-consuming datastore operations in a separate request, so that senders of data wait a shorter time for a response.

Now, for chromium.perf data, AFAIU, it would be generally acceptable if very occasionally data wasn't added, and it's worth it to reduce the time spent sending data.

Maybe we could add a request parameter to /add_point to indicate whether to add immediately in that request (slow but guaranteed to fail if the datastore put isn't completed) or to add it to a task queue (faster, only validating the data before returning a response).

**Comment by qyearsley** [comment]
**Comment by [hadd...@chromium.org](https://code.google.com/u/hadd...@chromium.org/)**
_2015-06-23T18:19:06.000Z_

----

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-09-01T20:32:21.000Z_

----

**Comment by chrisphn** [comment]
I do see a reduction in contention errors, roughly base on number of errors per minute.  We can try 10 max_concurrent_requests?  It looks like there are idle times when tasks are all completed, so we have room to go even lower; 10 max_concurrent_requests?

Taskqueue:
https://pantheon.corp.google.com/appengine/taskqueues?project=chromeperf&moduleId=default&tab=PUSH

Current deployed version:
https://pantheon.corp.google.com/logs?project=chromeperf&key1=default&service=appengine.googleapis.com&key2=clean-qyearsley-8974f250&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=500&expandAll=false&filters=text:%22too%20much%20contention%20on%20these%20datastore%20entities%22&lastVisibleTimestampNanos=1458837787747175000

Some old version:
https://pantheon.corp.google.com/logs?project=chromeperf&key1=default&service=appengine.googleapis.com&key2=clean-qyearsley-7bb21d0c&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=500&expandAll=false&filters=text:%22too%20much%20contention%20on%20these%20datastore%20entities%22&lastVisibleTimestampNanos=1457649030301936000

**Comment by qyearsley** [comment]
Alright -- another way of seeing the rate of contention errors is on the errors page:
https://console.developers.google.com/errors?project=chromeperf

There we can see that at least in the past couple days the rate of contention errors is low (2 instances of this error in Test._pre_put_hook), but that could also be because there happened to not be a lot of new tests added at once in the past couple days.

Another possible thing to try tweaking a bit more will be the retry parameters in cron.yaml.

**Comment by anniesullie** [comment]
Data contention errors were fixed in #2351
