### ISSUE TITLE
Bug ID in bisect configuration UI should default to the bug that's linked to the data point (state of alerts table and charts should be updated after triaging an alert)

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1425]
**Issue by [mile...@chromium.org](https://code.google.com/u/111768621731422639755/)**
_2015-04-27T19:33:44.000Z_
_Originally opened as http://crbug.com/481619_

---

When I am triaging an alert, I would first click on &quot;New bug&quot; to create
a bug for it. Then I usually want to click on &quot;BISECT&quot; button to send out
an bisect job. In the popped up bisect configuration UI, it would be great if the Bug ID field can be default to the bug I just created for this
alert.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-04-27T19:47:57.000Z_

----

Two notes that may be helpful for now:

1. Currently when you file a new bug, the dashboard will automatically start one bisect job for you (with some default parameters).
2. If you refresh the page now after the filing the bug, the new bug ID for the alert will be shown in the UI. If you click on the alert then click on the bisect button, the bug ID should then be filled in.

There is a change which I think should ideally be made which made which would satisfy this issue: After filing a bug, the triage-dialog should fire an event (I'm not sure if it does this now upon filing a new bug). The alerts-table and all of the charts on the page should be updated with the new bug ID for the alert.

**Comment by benshayden** [comment]
Archiving. This is redesigned in V2SPA.
