### ISSUE TITLE
Dashboard needs to be updated to use std from telemetry value rather than computing it itself

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1426]
**Issue by [nedngu...@google.com](https://code.google.com/u/105270153271635518855/)**
_2015-09-01T18:34:50.000Z_
_Originally opened as http://crbug.com/527134_

----

Telemetry list-of-scalar-value now has the std field in it.
Dashboard needs to be updated to use std from telemetry value rather than computing it itself.

**Comment by eakuefner** [comment]
**Comment by [nedngu...@google.com](https://code.google.com/u/105270153271635518855/)**
_2015-09-01T18:34:53.000Z_

----

**Comment by eakuefner** [comment]
@nedn FYI

**Comment by nedn** [comment]
This is P1 cuz it's blocking a P1 issue.
