### ISSUE TITLE
Strange Animation IRs and Associated Events

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1430]
Looking at [1] there are two animation IRs stacked on top of each other near the end of the trace. This, I believe, is my slight scroll at the end.

The top level animation seems to have a lot of associated events that are outside the actual time of the animation. The child animation IR does not appear to have any associated events.

Steps to record:
1- Load cnn.com.
2- When the page looks visually complete tap once.
3- When the page load indicator goes away scroll slightly.

This trace was taken on Android 40.0.2214.89 (the stock chrome for this device).

[1] https://drive.google.com/open?id=0BwBaQQ4lL3m2M0h4cWJXQWhrbm8
[2] https://drive.google.com/file/d/0BwBaQQ4lL3m2WDJWWkVaQ0VoSUU/view?usp=sharing

**Comment by dj2** [comment]
@benshayden @philippebeaudoin

**Comment by dj2** [comment]
This also happened in 44.0.2403.133 [1]  just with the order reversed. The top animation appears to have no events while the bottom one has events through the whole timeline.

[1] https://drive.google.com/open?id=0BwBaQQ4lL3m2dTQ5TTBXeWRDblE (shared with @chromium)

**Comment by benshayden** [comment]
Yep, there's a short scroll Animation with lots of associated events, then a long CSS Animation with no associated events, and a very short Fling Animation with some associated events.
Paul requested that different kinds of animations should not be merged.
I thought that #1160 would add the "name" to the displayed title. I'll follow up on that.
I'll file a bug about finding associated events for css animations. #1433

Is there anything else in particular that seems strange about those Animations?

**Comment by dj2** [comment]
Well, the IR with no associated events is what struck me as odd.  How can you have an animation that doesn't cause anything at all to happen in the system? Seems broken.

**Comment by benshayden** [comment]
Yep, #1433 will fix that.

**Comment by dj2** [comment]
Closing as a dupe.
