### ISSUE TITLE
Perf Dashboard: "Error" text overlaid in graph

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1432]
Chrome version: 47.0.2498.0 (Windows)
URL: https://chromeperf.appspot.com/report?sid=208c9aa07e91243024b4f7500b9ef69e883afa6dc67ded3eca374c7bd307b12e&rev=346879

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
None displayed

Please describe the problem:
Near the right edge of the graph, the text "Error" is present. Nothing shows up in the js console if I either hover or click on that text, so I don't know what "Error" means in this context. :)

![error-in-graph](https://cloud.githubusercontent.com/assets/9001650/9635353/f791765a-514a-11e5-9473-d1f1abf6fb73.png)

**Comment by qyearsley** [comment]
Aye -- same as #1427.

This happens after https://codereview.chromium.org/1321213004/; error in this case is the back-up text when the icon font is not loaded.
