### ISSUE TITLE
Loading spinner never hidden when test in chart container is invalid.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1435]
Currently, when the test path of a series group in a chart-container element is invalid, the legend is shown with the items grayed out, and the loading spinner never gets hidden.

Example: https://chromeperf.appspot.com/report?sid=e60253e1206dabbe478a537cac5aeb6ac5a0b6a4ef977d96ee6d201409c352de

Ideally, as soon as chart-container discovers that there is no data for all items in the legend, the spinner should be hidden, and an error message should be shown.

**Comment by anniesullie** [comment]
This is fixed.
