### ISSUE TITLE
Store site config in datastore.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1436]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-06-08T17:15:53.000Z_
_Originally opened as http://crbug.com/497829_

----

There are lots of special strings that are hard-coded now, could all be stored in the datastore. They should be stored in datastore in a consistent and simple way, and reasonable fallbacks should be used if they’re not present in datastore.

This is a meta-issue for the below list of issues:

 - issue 488335 Page title should be configurable.
 - issue 488333 IsLoggedIn function domain should be configurable
 - issue 488338 App ID and hostname should be configurable (might not need to be stored in datastore).
 - issue 488342 Alerting email (for migrate_test_names) should be configurable.
 - issue 488519 Alert mail sender address should be configurable.
 - issue 488527 Hard-coded info about repositories should be configurable.

Issue 497825 (make an admin page for viewing and editing these things) is also related.

**Comment by qyearsley** [comment]
Related doc: https://docs.google.com/document/d/1HQw_aRnxcxR0WE_hdrNdvtqRsOX1Ov45jjKtffhP6iE/edit

**Comment by anniesullie** [comment]
I think we've gotten this to a good point, may re-open if we get further requests to generalize the dashboard for other use cases.
