### ISSUE TITLE
Error in console upon re-assigning alert to a bug

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1438]
**Issue by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2015-08-17T18:32:51.000Z_
_Originally opened as http://crbug.com/521721_

----

1) Find an existing alert (I can't link to a stable one, since doing this breaks things)
2) Un-associate it with a bug
3) Nudge it (not actually sure if this is needed)
4) Re-associate it with the bug

The console produces:
&quot;Uncaught TypeError: Cannot read property 'map' of undefined&quot;

I *think* this caused other issues for me down the line, but I'm having trouble reproducing right now. Will keep investigating...

**Comment by qyearsley** [comment]
**Comment by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2015-08-17T18:34:57.000Z_

----

Sometimes I also get

Uncaught TypeError: Cannot read property '0' of undefinedPolymer.onBugTriaged @ chart-container.html:1649utils.fire @ polymer.js:9031(anonymous function) @ triage-dialog.html:125

I get that if unassociate/reassociate the first alert at https://chromeperf.appspot.com/group_report?bug_id=521114

**Comment by qyearsley** [comment]
**Comment by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2015-08-17T18:36:04.000Z_

----

I ultimately ended up having issues with these bugs where (I think) they would appear to be reassociated but weren't actually doing it in the backend, but I can't repro that right now. Hopefully fixing these two error messages resolve the root cause anyway.

**Comment by qyearsley** [comment]
**Comment by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2015-08-17T18:36:35.000Z_

----

Do we have tests around unassociating/nudging/associating bugs?

**Comment by qyearsley** [comment]
**Comment by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2015-08-17T18:41:23.000Z_

----

Reproduced what I was talking about in #2, but I think that's actually a fully separate bug. Filed issue 521724.

**Comment by anniesullie** [comment]
Haven't seen anything here in a long time.
