### ISSUE TITLE
When there may be internal-only alerts that aren't shown because the user is not logged in, show a warning on /group_report.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1440]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-03-04T19:09:30.000Z_
_Originally opened as http://crbug.com/463984_

---

This change could prevent some possible confusion in the future.

On the /group_report page, if the user is not logged on with a google.com account and there are no alerts fetched, show a message that says &quot;Some alerts may not be visible if you are not logged on.&quot; with a link to log on.

**Comment by qyearsley** [comment]
**Comment by [isherman@chromium.org](https://code.google.com/u/isherman@chromium.org/)**
_2015-03-04T19:21:26.000Z_

----

Issue 463980 has been merged into this issue.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-05-04T16:52:44.000Z_

----

Issue 484197 has been merged into this issue.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-05-04T16:52:55.000Z_

----

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-05-04T16:53:24.000Z_

----

**Comment by bhavybarca** [comment]
@simonhatch what about this? Still on?

**Comment by simonhatch** [comment]
Yes, this is also fixed already.
