### ISSUE TITLE
Return code bisect doesn't work from dashboard.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#1441]
Been trying to get a return code bisect going, doesn't seem like it's getting initiated properly from the dashboard. Here's latest attempt: http://build.chromium.org/p/tryserver.chromium.perf/builders/linux_perf_bisector/builds/354

The nexus5 run is here: http://build.chromium.org/p/tryserver.chromium.perf/builders/android_nexus5_perf_bisect/builds/2093

Config says "test_type": "perf", should it be something different?

**Comment by qyearsley** [comment]
@ro-berto Have we observed successful return_code bisects for recipe bisect yet?

The config for that job was:
```
{
  "bad_revision": "3eee4a88259c179d02cf082ed20c4b118bc1dfdd", 
  "bug_id": 527156, 
  "builder_host": null, 
  "builder_port": null, 
  "command": "src/tools/perf/run_benchmark -v --browser=android-chromium \
--output-format=chartjson --also-run-disabled-tests blink_perf.parser", 
  "good_revision": "5ed6d7dbd78e779945a16566e0d04192aea782a2", 
  "gs_bucket": "chrome-perf", 
  "max_time_minutes": "20", 
  "metric": "html-parser/html-parser", 
  "recipe_tester_name": "android_nexus5_perf_bisect", 
  "repeat_count": "5", 
  "test_type": "perf", 
  "truncate_percent": "0"
}
```

Does the recipe bisect have a config parameter "bisect_mode", or was there a plan to handle this in a different way?

**Comment by vuppalapu** [comment]
Made changes to recipe and CL is up for review https://codereview.chromium.org/1328853002.
This also needs changes on dashboard, I work on that and update this thread.

**Comment by qyearsley** [comment]
Prasad also submitted https://codereview.chromium.org/1313623004/ which I believe fixes this.

Do we have an example case now to verify that return code bisect works?

**Comment by anniesullie** [comment]
@eakuefner Submitted some return_code bisects this week. Ethan, did they work? If not, can you re-kick?

**Comment by anniesullie** [comment]
These have been working for me.
