### ISSUE TITLE
Dashboard graph (which should have data) never loads

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1444]
**Issue by [rsch...@chromium.org](https://code.google.com/u/102170992385696224052/)**
_2015-08-14T22:17:18.000Z_
_Originally opened as http://crbug.com/521154_

----

https://chromeperf.appspot.com/report?sid=323fcb4f08d508d4305f155afbdd6b0cccceec6e49fb15287084dd94af8bb3b8&amp;start_rev=338286&amp;end_rev=343431

I see this: https://screenshot.googleplex.com/aaCW0RNTbX5

If I uncheck and recheck the metric on the right, it appears.

**Comment by qyearsley** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-14T22:19:18.000Z_

----

Confirmed.

Note, there are recent points for this graph:
https://chromeperf.appspot.com/new_points?pattern=ChromiumPerf%2Fchromium-rel-mac8%2Fstartup.cold.blank_page%2Ffirst_non_empty_paint_time

**Comment by qyearsley** [comment]
**Comment by [chrisp...@chromium.org](https://code.google.com/u/109509802684846018332/)**
_2015-08-14T23:04:12.000Z_

----

**Comment by qyearsley** [comment]
**Comment by [chrisp...@chromium.org](https://code.google.com/u/109509802684846018332/)**
_2015-08-14T23:04:25.000Z_

----

**Comment by qyearsley** [comment]
Note: The request that's being made here is:

curl 'https://chromeperf.appspot.com/graph_json' --data 'graphs=%7B%22sid%22%3A%22323fcb4f08d508d4305f155afbdd6b0cccceec6e49fb15287084dd94af8bb3b8%22%2C%22start_rev%22%3A%22338286%22%2C%22end_rev%22%3A%22343431%22%2C%22test_path_dict%22%3A%7B%22ChromiumPerf%2Fchromium-rel-mac8%2Fstartup.cold.blank_page%2Ffirst_non_empty_paint_time%22%3A%5B%5D%7D%2C%22is_selected%22%3Atrue%7D'

curl 'https://chromeperf.appspot.com/graph_json' --data 'graphs=%7B%22sid%22%3A%22323fcb4f08d508d4305f155afbdd6b0cccceec6e49fb15287084dd94af8bb3b8%22%2C%22start_rev%22%3A%22338286%22%2C%22end_rev%22%3A%22343431%22%2C%22test_path_dict%22%3A%7B%22ChromiumPerf%2Fchromium-rel-mac8%2Fstartup.cold.blank_page%2Ffirst_non_empty_paint_time%22%3A%5B%22first_non_empty_paint_time%22%5D%7D%2C%22is_selected%22%3Atrue%7D'

That is, the request is being made with "test_path_dict" as
```{"ChromiumPerf/chromium-rel-mac8/startup.cold.blank_page/first_non_empty_paint_time" : []}```

But it should be:
```
{
"ChromiumPerf/chromium-rel-mac8/startup.cold.blank_page/first_non_empty_paint_time" : [
  "first_non_empty_paint_time"
]
}
```
That is, no values in the test path dict should be empty.

One possible fix: in chart-container, whenever the test path dict is set, always "fix" it so that if any array is empty, put the trace name (the last part of the test path, which is the key) into the list.

@chrisphn Any thoughts?

**Comment by chrisphn** [comment]
Looks like it's now loading.

**Comment by qyearsley** [comment]
Yay :-)
