### ISSUE TITLE
Perf Dashboard: Dashboard looks busted

### ISSUE THREAD

**Issue by esprehn** [catapult-project/catapult#1445]
Chrome version: 47.0.2500.0 (Mac)
URL: https://chromeperf.appspot.com/group_report?bug_id=521536

Please describe the problem:

Page looks really broken, lots of overlapping dialogs and content.

Google Chrome	47.0.2500.0 (Official Build) canary (64-bit)
Revision	ec94f8068261e1ccfcea20e6e0bc70a9685e4d8b-refs/heads/master@{#347062}
OS	Mac OS X 
Blink	537.36 (@201681)

**Comment by qyearsley** [comment]
Same as https://code.google.com/p/chromium/issues/detail?id=528201; this only affects canary (47.0.2500.0) currently, not earlier versions of Chrome.

**Comment by chrisphn** [comment]
Will look into this.  Thanks for reporting.

**Comment by chrisphn** [comment]
Don't see this issue anymore.

**Comment by qyearsley** [comment]
Possibly a bug in canary which is now fixed.
