### ISSUE TITLE
Automatically enforce benchmark ownership in tools/perf across Catapult components

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1448]
**Issue by [eakuef...@chromium.org](https://code.google.com/u/113455657570966801301/)**
_2015-04-30T00:02:29.000Z_
_Originally opened as http://crbug.com/482772_

----

This is a tracking bug for enforcing benchmark ownership across Catapult components (chiefly, Telemetry and the Performance Dashboard) as described in https://docs.google.com/document/d/1qlbrSRtqZpCyp1R1HCt0xLklMHno-Mvuz5U24QyQKh4/edit

**Comment by qyearsley** [comment]
**Comment by [eakuef...@chromium.org](https://code.google.com/u/113455657570966801301/)**
_2015-04-30T00:02:58.000Z_

----

Also, I wonder if we should request/agree on a Catapult label while we're still figuring the bugtracker situation out.

**Comment by qyearsley** [comment]
**Comment by [nedngu...@google.com](https://code.google.com/u/105270153271635518855/)**
_2015-04-30T03:33:06.000Z_

----

I am confused about this bug. We are not gonna put perf/ directory in Catapult. What do you mean by enforce benchmark ownership across Catapult?

**Comment by qyearsley** [comment]
**Comment by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2015-04-30T13:34:33.000Z_

----

The tough part here is that ownership can sometimes be a little fine-grained. I think these two things are the only exceptions to per-benchmark ownership:

1) Some benchmark owners are per-platform. For example, pasko@ owns android startup, and gab@ owns windows startup.
2) Some metrics have owners across benchmarks, and these can be per-platform, too. For example, ccameron/shrike own power on Mac, pasko owns memory on android.

Re comment 2: I think Ethan means that this is only really valuable if the information about ownership is shared between telemetry and the perf dashboard. I believe the right way to do this is to put the annotations in benchmarks in the perf/ directory, but then have some way to have them sent to the perf dashboard via chartjson.

**Comment by qyearsley** [comment]
**Comment by [eakuef...@chromium.org](https://code.google.com/u/113455657570966801301/)**
_2015-04-30T15:50:10.000Z_

----

Annie is correct, I'm mostly trying to imply that there should be synergy between the dashboard and Telemetry with regard to enforcing ownership in tools/perf, maybe with a general mechanism that can be applied to other Catapult client developments. I've updated the title of the bug to make it a little more clear.

I agree (and I think Ned does as well) that the best way to do this will be to export the annotations in JSON somehow, since it's easy to add new metadata to chart JSON.

**Comment by eakuefner** [comment]
Archiving because we're not going to be doing this -- especially with System Health, we're moving away from policing benchmarks directly to simply being more opinionated up front, and trying to develop partnerships with metric authors and ownership over story sets.
