### ISSUE TITLE
mapping is limited to result sets that fit in memeory

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1450]
It should be possible to stream the results to a file. Python's memory usage grows as more and more traces are processed and there's a noticeable pause when outputting a few hundred MB of JSON. This likely requires changes to the output format, or to split the run info and values into separate files.

**Comment by natduca** [comment]
Are you seeing crashes, or is the issue more about the pause? Trying to understand severity.

My mental model so far is that the results json isn't so big that it can't be loaded... that is, you might produce a ton of data, but if your json blob is so big that it exceeds 256mb of trace data, then we cant' even get it into our frontend for visualization.

If we intend to process so many traces that the map reuslts will never fit in JS, thenmaybe we need to be thinking about having a proper mapreduce style pipeline that the UI bits interact with.

**Comment by dstockwell** [comment]
Not severe. Not crashing yet, issue is mainly the pause.

**Comment by natduca** [comment]
I'm gonna retitle slightly and move off of v1. Definitely agree we need to think about this at some point thoug.

**Comment by dstockwell** [comment]
Was thinking about this somewhat, I think it would be better to move to a streaming format.

Where currently the data is exported as a dictionary structure:

```javascript
{
  "runs": {
    "run-1": {run-info},
    "run-2": {run-info},
    ...
  },
  "values": [
    {value1, run_id="run-1"},
    {value2, run_id="run-2"},
    ...
  ]
}
```

We could move to a list of tagged entries:

```javascript
[
  {kind=run, run_id="run-1", run-info},
  {kind=value, run_id="run-1", value1},
  {kind=run, run_id="run-2", run-info},
  {kind=value, run_id="run-2", value2},
  ...
]
```

Transforming between the two formats is trivial if necessary. For bonus points if we ensure that each of the entries is formatted on a single line, writing a streaming parser is trivial.

**Comment by dj2** [comment]
You could also do a series of dictionarys:

```
[
  {
    'name': 'run-1',
    'run-info': run-info1,
    'values': value1
  },
  {
    'name': 'run-2',
    'run-info': run-info2,
    'values': value2
  }
]
```
Which keeps the related information together.

**Comment by dstockwell** [comment]
> Which keeps the related information together.

I think that has other scalability problems -- I often output thousands of values per run.

**Comment by natduca** [comment]
Yeah, lets dupe this into #1497
