### ISSUE TITLE
Selecting a single power sample should show both the timestamp and power measurement

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1451]
Right now, we only show the event's timestamp. This is because we use the `single_event_sub_view`, which displays attributes that all events have.

**Comment by zeptonaut** [comment]
Probably the right thing to do here is to create a new simple sub view for single power samples that just uses the same `power_sample_table` that the `multi_power_sample_sub_view` uses.

**Comment by dj2** [comment]
Should be fixed with d6b687f
