### ISSUE TITLE
Visualizations to explain RAIL scores

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1455]
Per discussion with @paulirish , the weather report can use histograms with 2 vertical axes to explain the relationship between Response/Load duration and score while displaying the number of IRs in the corpus with a score in a histogram bucket.
Here are 4 graphs that could be added to the weather report:

Response pain
horizontal axis: duration
left vertical axis: number of IRs
right vertical axis: score for a hypothetical IR with a duration in the middle of the histogram bucket

Load pain
horizontal axis: duration
left vertical axis: number of IRs
right vertical axis: score

Animation Speed
horizontal axis: average frame time
left vertical axis: number of IRs
right vertical axis: score

Animation Smoothness
horizontal axis: smoothness score
left vertical axis: number of IRs
right vertical axis: score

**Comment by natduca** [comment]
I'd learn toward closing this, so that our bugs track the stuff we absolutely must do.
