### ISSUE TITLE
Replace Weather Report's Self Time with Scheduled%

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1456]
Scheduled% = cpuSelfTime / selfTime
Or should it be Descheduled% = (selfTime - cpuSelfTime) / selfTime?

Per discussion with @paulirish

**Comment by fmeawad** [comment]
Why not cpuSelfTime?

Can you elaborate more about the discussion/rationale behind the change?

**Comment by benshayden** [comment]
Paul can probably explain it better than I can, but I'll give it a shot.

cpuSelfTime is already displayed, and it's more consistent and interesting than selfTime.
selfTime = cpuSelfTime + time when the thread was pre-empted by the kernel. The descheduled time is essentially random, for our purposes, but it should generally scale linearly with the cpuSelfTime.
Different threads have different priorities, so the ratio between cpuSelfTime and selfTime should be somewhat consistent among slices in the same thread and different between threads with different priorities.

**Comment by fmeawad** [comment]
Gothcha, then I would vote for Scheduled% seems to be more linear.

**Comment by natduca** [comment]
Lets stick with self time for now, and come back to this idea when we get to a polishing stage.
