### ISSUE TITLE
Allow annotations on the Dashboard

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#1458]
We don't currently make configuration changes obvious on the dashboard, which can lead to wasted time tracking down false regressions or missing real regressions due to the reference build changing independently of the project.

It would be useful to be able to create annotations on the graphs to alert sheriffs of things like reference build updates, bot configuration changes, etc.

**Comment by qyearsley** [comment]
Thanks for re-filing Kari - writing a design doc for this idea is actually in our OKRs. After deciding on the scope, design, and required work, we can decide specifically what we want to do. Doc (limited to google.com domain): https://goo.gl/JdG3Hu

**Comment by benshayden** [comment]
#3680
