### ISSUE TITLE
Make it easier to view graphs for deprecated tests.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1460]
On https://chromeperf.appspot.com/report, when using the menus, "deprecated" tests aren't listed (since when they're listed they clutter the menus). Still, occasionally, people may want to view results for old tests that don't have recent results.

This would involve changing [change list_tests.GetSubTests](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/list_tests.py) to fetch (optionally?) fetch deprecated tests.

**Comment by chrisphn** [comment]
We can add a 'deprecated' checkbox next to the test selection menu.

**Comment by qyearsley** [comment]
I think that sounds fine to me -- this would be a change in the [test-picker](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/test-picker.html) element that controls the XHR that's sent to list_tests.

**Comment by chrisphn** [comment]
Design:
A toggle that opens a section with a list of filters such as 'deprecated tests', 'monitored tests', etc.  Test selection would only show the results for checked filter.

![filters_sample_ui](https://cloud.githubusercontent.com/assets/11621527/10149541/130180de-65ef-11e5-8545-03aff3d96630.png)

**Comment by qyearsley** [comment]
Seems reasonable To me - Any other things that might be filtered besides 'deprecated' and 'monitored'?

Also, the behavior of the check boxes should be clear. One possible way that it could be would be:

 * Only show tests with recent data [x]
 * Only show tests monitored for alerts [ ]

(The first is checked by default; un-checking shows deprecated + undeprecated tests)

**Comment by chrisphn** [comment]
Ok, that looks clear to me.

**Comment by chrisphn** [comment]
Actually, how about either show recent tests or deprecated tests, because if we can show both recent and deprecated tests, why not show both by default.

* Only show deprecated tests
* Only show tests monitored for alerts

**Comment by anniesullie** [comment]
In my opinion, we should show all the tests with a note (like we currently say "unmonitored", we could have it say "deprecated"). It's not such a problem to have tons of tests in the menu now that you can autocomplete

**Comment by chrisphn** [comment]
Right, just had a offline talk, and that's what we agreed with.

**Comment by benshayden** [comment]
Archiving.
