### ISSUE TITLE
Update go/railscore

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1462]
It should link to bit.ly/1LXShKe and go/performance-insights-reports

And make it public with a bit.ly.

**Comment by benshayden** [comment]
@natduca Anything else in particular should be done to go/railscore?

**Comment by natduca** [comment]
It should represent our current thinking and algorithm.

**Comment by benshayden** [comment]
I switched the per-interaction RAIL score over to my detailed RAIL Scores Algorithms doc bit.ly/1LXShKe and cleaned up some of the verbiage and added a link to Writing Perf Insights Reports.
I didn't make a bit.ly for go/railscore because some of the links are google-only, like go/chrome-performance-insights at the bottom.
Closing this issue, but feel free to reopen or comment on the doc if there's something I still need to change.

**Comment by natduca** [comment]
This looks awesome. Thanks ben!
