### ISSUE TITLE
Dogfood railscore on msn article (on windows) for actionability

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1466]
This URL came up in a discussion internally about feeling laggy in R and A stage responses in chrome, but good in Edge.

Lets check out its rail score. Does our railscore for it represent reality?

http://www.msn.com/en-us/news/politics/clinton-campaign-biden-would-shake-up-race/ar-AAdVhL9?ocid=spartandhp

**Comment by natduca** [comment]
@philippebeaudoin @benshayden 

maybe we can get a trace from @yufengshen ...

**Comment by benshayden** [comment]
Tried to repro on Fadi's windows machine. Scrolling and clicking "home" and the gear feel pretty fast.
webpagetest gave us a pretty good trace of loading that revealed a bug in RAILIRFinder, and a few long tasks in chrome that could explain laggy R/A, but that's just loading.
Unable to repro, I guess?
