### ISSUE TITLE
Overhead slices are showing up overlapping toplevel slices

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1469]
This trace for instance:
https://drive.google.com/open?id=0BwBaQQ4lL3m2M0h4cWJXQWhrbm8

at 12.2 seconds on CrBrowserMain has overhead slices that overlap the main slices.

![image](https://cloud.githubusercontent.com/assets/412396/9916749/e70087d0-5c72-11e5-92f9-d630a7f6337c.png)

The real data stream is this:

```
    [  toplevel    ]   [ toplevel ]
        [x]                  [y]
```

but then there is this overlapping the toplevel:
```
      [overhead        ]
```

This is messing with a ton of assumptions in trace viewer: rendering, and analysis. We need to fix this p0.

**Comment by natduca** [comment]
@dj2 @benshayden fyi

**Comment by anniesullie** [comment]
Fadi is going to take a look

**Comment by fmeawad** [comment]
It seems that the consensus is to kill the overhead code, despite that it might be really useful, it has proven to be really hard to maintain.

I will remove the TODO in the code, and update the comment once the code in chrome is removed.

**Comment by natduca** [comment]
Adding @wangxianzhu to the thread.

**Comment by natduca** [comment]
Is this still moving?

**Comment by dj2** [comment]
I believe this is finished. @fmeawad landed code to skip overhead in the importer and @wangxianzhu removed the overhead from the Chrome side so they won't be emitted.

So, this should no longer be an issue with ToT.
