### ISSUE TITLE
"Bypass no-repro check" checkbox in bisect dialog doesn't work as expected.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1470]
To reproduce: First, go to any bug that you want to start a bisect for (e.g. any in https://goo.gl/b8MjDS). Then open the graph, click on an alert, open the the bisect dialog, check the no-repro checkbox, and submit. View the job on the buildbucket job status page.

Expected result: "required_confidence": "0" should be in the config.

Actual: It doesn't appear to be. For example, I just submitted this job with the bypass no-repro checkbox ticked: https://chromeperf.appspot.com/buildbucket_job_status/9034489907880508048

**Comment by wangzhen127** [comment]
What does this check box mean? What's the behavior with and without this config?

**Comment by qyearsley** [comment]
Not checked: After getting the results for the "known good" and "known bad", the bisect will compare the two groups of numbers to see whether there's a significant difference (whether it appeared to reproduce the regression). If it didn't appear to reproduce a regression, it aborts the bisect job. This is helpful in cases where the regression is actually not reproduced on the given try bot (which occasionally happens).

Checked: Skip this "not reproduced" check.

**Comment by wangzhen127** [comment]
Do you mind taking a look at https://code.google.com/p/chromium/issues/detail?id=532525, where I think there should be regression, but the bisect bot was aborted?

prasadv restarted the bisect with "not reproduced" checked, it is still aborted. Is that due to this bug?

**Comment by qyearsley** [comment]
I believe so - note that there's a current CL to change this: https://codereview.chromium.org/1351713002/ After that gets committed we'll deploy a new version and try again

**Comment by qyearsley** [comment]
I believe that this is fixed after Prasad's commit last month. (Not properly verified; this bug should be re-opened if anyone observes this issue again.)
