### ISSUE TITLE
Update blink's trace_event.h to include flow events v2

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1472]
In chromium, we added a new flow event api...

commit 21c55cb65ef294af3e5479c34473786281168aef
Author: yuhaoz <yuhaoz@google.com>
Date:   Wed Jul 29 16:51:34 2015 -0700

    Implement a new flow event API that allows binding flow events and regular events.
    CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel

    Review URL: https://codereview.chromium.org/1239593002

    Cr-Commit-Position: refs/heads/master@{#341023}

We have to update Blink's copy nao.

**Comment by natduca** [comment]
@vinterstum not sure if we should make a label for this? Shrug...

**Comment by natduca** [comment]
@dstockwell fyi

**Comment by vinterstum** [comment]
Update:

Chrome-side CL has landed (https://codereview.chromium.org/1354453002/) but the main Blink-side one has a few failing tests. Investigating: https://codereview.chromium.org/1347113004/

**Comment by vinterstum** [comment]
Final Blink CL landed: https://codereview.chromium.org/1359973003/

Flow Events v2 should be usable in Blink now, @dstockwell
