### ISSUE TITLE
invalid tags are silently discarded

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1476]
I was trying to apply a tag of `exp2-style-sharing-disabled` but I couldn't find any tags in my datastore.

The upload script contains:
```
if re.match('^[a-zA-Z0-9,]+$', tags_string): # ignore non alpha-numeric tags
  trace_object.tags = tags_string.split(',')
```

If we're going to restrict the content of tags we should error on these requests, not silently drop them. But I'm not sure why the limitation is necessary in the first place.

**Comment by fmeawad** [comment]
Added a warning, and allowed for '-' as it seems a common case.

The limitations comes for security and simplicity.
