### ISSUE TITLE
No UI to add to dashboard IP whitelist

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1484]
There is no /ip_whitelist or any other UI I can find (or anything in the dashboard code that sets stored_object 'ip_whitelist'). I needed to add an IP this morning and did it through the interactive console, which is scary.

**Comment by qyearsley** [comment]
The page is now:
https://chromeperf.appspot.com/edit_site_config?key=ip_whitelist

What kind of link would be good? Should we add links to the nav menu, or would it be enough to add links to https://chromeperf.appspot.com/edit_site_config?

**Comment by anniesullie** [comment]
Two things:

1) I looked for it in the nav menu, we should add links there
2) Some documentation at the top of /edit_site_config explaining that if you want the value to be the same for internal/external users, just fill out the first box.
