### ISSUE TITLE
Get a copy of typ (test your projects) in catapult and use it to run Python tests.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1487]
Related issues:
 * Move tvcm (and remove its own test_runner module) (https://github.com/catapult-project/catapult/issues/1266).
 * Refactor test runners in catapult (https://github.com/catapult-project/catapult/issues/1478).
 * Get test coverage information (https://github.com/catapult-project/catapult/issues/1347).

@dpranke @natduca 

Would it be OK to make a CL to check in typ like the other libraries in third_party?

**Comment by dpranke** [comment]
fine by me.

**Comment by qyearsley** [comment]
@nedn 
By the way this did speed up the tests a lot, definitely at least 2x. Very rough estimate:
Dashboard tests (on my workstation): before: at least 2m 30s; after: 35s
Perf insights tests (on my workstation): before: 8s; after: 4s
