### ISSUE TITLE
Vinn crashes with oom on all the traces in measurmt/desktop/v8-samples

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1488]
This is urgent to fix.

calling @chiniforooshan @dj2

**Comment by dj2** [comment]
Steps to reproduce?

**Comment by natduca** [comment]
./bin/map_traces_locally ~/Local/measurmt-traces/desktop/v8-samples/  ./perf_insights/mappers/weather_report_map_function.html

**Comment by dj2** [comment]
What machine are you running on? On my z620 this worked correct:

```
third_party/catapult/perf_insights % ./bin/map_traces_locally ~/Development/measurmt-traces/desktop/v8-samples/ ./perf_insights/mappers/weather_report_map_function.html 
[ RUN      ] trace_aol.json.gz
...
[       OK ] trace_webmd.json.gz (25450 ms)
[  PASSED  ] 10 tests.

{
  "runs": {
...
 }
}
```

**Comment by dj2** [comment]
Running -j10 I can see MEM% get up to a max of 2.8% (~1.6gig resident, ~2.6gig virtual) (and around 2 - 2.5% for each process). When running without -j I can see the MEM% of d8 getting up to a max of 2.8% but then it drops back to 0.x% as soon as each file is processed.

So, it doesn't seem like this would be a leak between traces. Possibly something that is happening in a single trace?

**Comment by dj2** [comment]
Running on my Mac it looks like it takes ~1.5gig max memory to run singly. Running -j10 required ~10gig of ram. Both completed successfully.

Are you using any other flags when running?

**Comment by dj2** [comment]
(Or, does your measurmt-traces/desktop/v8-samples have more then the 10 traces which are on github?)

**Comment by natduca** [comment]
-j 1 still crashes. Its on a macbook pro mid 2014 with 16gbs of stuffs.... but, if its useful, map_traces runs every trace in a different process.

**Comment by chiniforooshan** [comment]
Hmm, I cannot reproduce on my X230 laptop neither... Can you attach the output?

**Comment by natduca** [comment]
The output is:
(histograms) ~/Local/chrome/src/third_party/catapult/perf_insights $ ./bin/map_traces_locally ~/Local/measurmt-traces/desktop/v8-samples/  ./perf_insights/mappers/weather_report_map_function.html  -j 1
[ RUN      ] trace_aol.json.gz

#
# Fatal error in Scavenge promotion failed
# Allocation failed - process out of memory
#

Error: Invalid ProtoIR: a(5985 5985 undefined) File a bug with this trace!
vinn runtime error while mapping trace.
[  FAILED  ] trace_aol.json.gz (31506 ms)
[ RUN      ] trace_cnet.json.gz

#
# Fatal error in Scavenge promotion failed
# Allocation failed - process out of memory
#

vinn runtime error while mapping trace.

@nedn any ideas?

**Comment by nedn** [comment]
Can you upload your desktop/v8-samples somewhere? I can help with debugging.

**Comment by chiniforooshan** [comment]
https://github.com/natduca/measurmt-traces/tree/master/desktop/v8-samples

**Comment by dj2** [comment]
I was able to process this with -j1 on my Air. (Trying for -j10 ran for 45 minutes before I killed it).  It looks like there is a flag we could try: --max-old-space-size=10000 (from https://code.google.com/p/v8/issues/detail?id=847). @nedn how do we pass flags to vinn so @natduca can try this?

**Comment by nedn** [comment]
https://codereview.chromium.org/1349313006/

**Comment by natduca** [comment]
Agh, I just pulled ToT and this doesn't repro on my mac now. I was so sure I had a ToT checkout, and it turns out I had a build from Aug 25th. I am so intensely sorry for the churn here folks. I owe all drinks and apologies next time I see y'all.

**Comment by nedn** [comment]
Oh, so that was before @zeptonaut 's work for updating the binary. Anyway, with the command line flags added, we can add "--log_..." to trace the d8 execution now.
@fmeawad : are you aware of any command line we can pass to d8 to get a detailed trace of javascript functions's calls?
