### ISSUE TITLE
Create domain categories for more user-friendly reports

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1490]
Categories can be 'Ads', 'Analytics', 'Google', etc. Use https://codereview.chromium.org/1345593002/ as the guideline. It may make sense for a domain to be in more than 1 category (e.g. 'Google' and 'Ads')... in which case, we should be careful in the report to not double-count...

**Comment by natduca** [comment]
Awesome! Next step is to do a patch like 
https://github.com/catapult-project/catapult/commit/8969e4f896ffa72fbe412edf0e8af10a2aa1bf53

that allows slice_report to include this

**Comment by natduca** [comment]
Oh wait, I'm an idiot. YOu did that. Wanna close this?
