### ISSUE TITLE
Slowly and steadily rename RAIL to SH

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1492]
RAILScore is actually about a lot more than just whether we fit the r/a/i/l goals. Its also about efficiency issues, etc.

As such, I suggest we start renaming our labels, docs, doclinks like go/railscore, and code names to be about user satisfaction index, or something similar that has broader appeal.

**Comment by natduca** [comment]
@benshayden @paulirish fyi

**Comment by natduca** [comment]
I think we should write a design doc.

**Comment by benshayden** [comment]
The term "User Happiness" is from https://product-excellence.googleplex.com/initiatives#investing_in_excellence
"Index" is as in "Speed Index".

**Comment by natduca** [comment]
Design doc: https://docs.google.com/document/d/1BW-owCB_RcH0ooYNAVGJ76igTlnF7pT64YAplwauobE/edit#heading=h.4g6iiaw7hzmm

**Comment by benshayden** [comment]
Is this WontFix? The design doc seems to end on a note of uncertainty.

**Comment by natduca** [comment]
Nope, still very much alive and kicking. I think we'll bump it to m49 but lets definitely keep working toward this. The steps here are more social than eng, I think... lemme assign it to me to get the renaming socialized and then we can followup again in a bit.

**Comment by benshayden** [comment]
I think we're changing to "sh" now? All stakeholders bought in? Pull the trigger?

**Comment by natduca** [comment]
Lets give the renaming another week... I discovered yesterday evening that the name isn't polling well with dglazkov, so we need something but I'm not sure what. @rschoen and I have more discussions next week to get something figured out. In the short term, maybe focus on #1902 and landing benchmarks etc (use the sh name for those) and then if we hit Friday with no name, we'll take our best bet and run with it.

**Comment by natduca** [comment]
We're good to go: system health.

**Comment by benshayden** [comment]
![cheering minions](http://www.reactiongifs.us/wp-content/uploads/2013/06/cheering_minions.gif)

I'll put a patch up as soon as I have a hard drive.

**Comment by natduca** [comment]
Details, yo!
