### ISSUE TITLE
Move error display from weather_report to pi_app_main

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1493]
Each report should not have to show its error count.

**Comment by natduca** [comment]
@chiniforooshan wanna pick this up?

**Comment by chiniforooshan** [comment]
Can you help me understand this issue? Where is the error count displayed, currently? I cannot see it in the slice cost report or the script generating the report.

**Comment by natduca** [comment]
Ah, I'm sorry. I was wrong about where this code lives.

In weather_report.html 's updateContents you will find code:
```
      this.$.infobars.clearMessages();
      this.maybeAddFailuresInfoBarMessage_(results);
```

This looks through the results of the mapping run [that json] and takes the failed runs and shows them in an info bar. Right now that is done by the weather report, but it would be better if the overall pi_app_main .html did that, and actually just passed the successful values down to the reports. Then, the report object itself could focus on displaying the real values, instead of having to deal with the corner cases.
