### ISSUE TITLE
Implement Mappers v2 (and pi reports v2)

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1497]
We want composable, brushable reports.

Mappers v2 is described here:
https://docs.google.com/document/d/1BMqQzPb-YAPASaF_eUpsHoOPEHX2xZi1JfoCo-QNFKQ/edit

Brushing is then a layer on top of mappers v2, described here:
https://docs.google.com/document/d/1pL_-ZXvK6mDGYcVi1EMU67VFO2MhG5SMIx5XQEeK9iE/edit.

@natduca will do toplevel implementation while @benshayden will work bottom-up to get the individual reports ready for this system.

**Comment by nedn** [comment]
Cool.

**Comment by natduca** [comment]
Ethan did this. So reassigning and closing.
