### ISSUE TITLE
Deep report metadata indicate URL

### ISSUE THREAD

**Issue by paulirish** [catapult-project/catapult#1501]
For many of the deep reports, I want to know where it was recorded. 

Can we include the URL of the page in the trace metadata?

**Comment by dstockwell** [comment]
Typically the page URL is already in the trace, I usually use the first `devtools.timeline ParseHTML` entry (`beginData.url`).

**Comment by paulirish** [comment]
True true. That's a good workaround.

My current usecase: I'm processing a big pile of DR's and want to make sure it's not dominated by a single obscure site.

If this was in the trace-level metadata, we could get the value much faster and wouldn't have to learn this one clever trick :)

**Comment by natduca** [comment]
Should we WontFix and revisit when we push harder on this space?
