### ISSUE TITLE
Typing in complete Test Suite/Bot name doesn't update menus

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1509]
To reproduce:
1. Go to https://chromeperf.appspot.com/report
2. Type "sunspider" in the Test Suite name. Bot menu does not update, even after pressing enter.
3. Same thing after selecting sunspider from the menu and typing a bot name/pressing enter, Sub Test menu does not update.

This should at least handle pressing enter, but ideally the menus should update when a key is typed that completes a valid menu item.

**Comment by chrisphn** [comment]
Currently the test suite will need to be selected by pressing arrow-down or clicking on it.  I agreed to automatically select if suggestion is an exact match.

**Comment by chrisphn** [comment]
Menus should now auto-select exact match item and update subsequent menus.
