### ISSUE TITLE
Show UserFriendlyCategory in single-event-subview and friends

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1511]

**Comment by benshayden** [comment]
@natduca

**Comment by benshayden** [comment]
@chiniforooshan

**Comment by natduca** [comment]
What makes this hard is that UserFriendlyCategory is currently chrome-specific. Whereas single event sub view is model-specific. So we need to figure out some way to move UserFriendlyCategory into the model core.. 

I'm wondering if we had Model.userFriendlyCategoryDrivers_[], and Model.getUserFriendlyCategoryFromEvent(event) iterates the drivers, and the existing UFC is renamed to ChromeUserFriendlyCategoryDriver, and ChromeAuditor pushes the driver.

**Comment by natduca** [comment]
Patch up at https://codereview.chromium.org/1412003009/

**Comment by natduca** [comment]
@lpy want to drive this?

**Comment by lpy** [comment]
sure.

**Comment by lpy** [comment]
What do you think about we put getProcess and `get model` inside slice.html?

**Comment by lpy** [comment]
CL: https://codereview.chromium.org/1459523002/

Close as fixed
