### ISSUE TITLE
Trace coverage is low

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1513]
Based on android navigation traces over the top 1000 pages, toplevel slices make up:

* 88% of browser cpuSelfTime
* 13% of renderer cpuSelfTime
* 13% of other cpuSelfTime

**Comment by natduca** [comment]
I'm wondering how to keep this bug actionable over the crush of time while leaving it unassigned... any ideas doug? Right now I can't route this to anyone, and I worry that as phrased its going to rot...

**Comment by dstockwell** [comment]
We should track 'toplevel' separately from 'other' user-friendly-category, then the current state of the issue should be obvious in the UI.

One way to make progress on this issue would be use the sampling profiler to find out what's happening during these toplevel slices.

**Comment by anniesullie** [comment]
Not for the top 1000 pages, but maybe for the top 10 we could have a telemetry test that tracks it?

**Comment by dstockwell** [comment]
Telemetry test is a good idea and does not need a dependency on the classification code. It's probably sufficient to just sum the total self time in top level slices.

**Comment by natduca** [comment]
This is still a bug but lets track it at an OKR/overall health level instead of as a bug, because the next step on this is a bit imprecise right now.
