### ISSUE TITLE
Update ThreadGrouping to recognize gpu as its own thing

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1514]
I think we want to detect the thread named CrGpuMain and then call that thread gpu.

In desktop mode, it'd be all the threads in the process that owns the CrGpuMain thread.

In android, there's more nuance: i think we need the gpu thread, and the async uploader thread. sievers@chromium.org might be the one to ping on chat for advice, or aelias@chromium.org ...

**Comment by natduca** [comment]
@dstockwell can you poke at this?

**Comment by dstockwell** [comment]
This is mostly done, but it doesn't extract the GPU threads when they are part of another process.

**Comment by natduca** [comment]
Should we close this and file a new bug that explaisn the remaining issues and gaps? That way its more actionable and we can put GoodFirstBug label on it and route it somewhere else if you're swamped
