### ISSUE TITLE
[Dashboard] There's no way to tell in the UI if there are more unselected series still loading.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1522]
Example:
https://chromeperf.appspot.com/group_report?bug_id=502254

On this page, the request for the selected traces is fast (only two series) but there are a lot of unselected per-page series and it takes several seconds to load. Until they're loaded, there's no indication that anything will happen.

Proposed fix: a loading spinner should be made visible when a request for data is sent, and hidden when all requests for data (the two /graph_json requests) are finished. See [chart-container sendGraphJsonRequest](https://github.com/catapult-project/catapult/blob/29fff400a6971d3e16bb44f6bc4a314478dba22a/dashboard/dashboard/elements/chart-container.html#L604).

**Comment by qyearsley** [comment]
Hey, I took a look at this today and have one proposed change -- can you take a look? https://codereview.chromium.org/1386533002

**Comment by chrisphn** [comment]
Sure, I'll take over this.

**Comment by qyearsley** [comment]
Verified!
