### ISSUE TITLE
Perf Dashboard: 

### ISSUE THREAD

**Issue by selavazhagan** [catapult-project/catapult#1523]
Chrome version: 44.0.2403.155 (Linux)
URL: https://chromeperf.appspot.com/report?sid=656e99907677349ae1dd58e04539c1bd1d758840c4a24bf7fbbd0668075f8ea6

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
There are no errors seen in the JavaScript console as seen in the attachment.
![screenshot from 2015-09-24 11 19 05](https://cloud.githubusercontent.com/assets/9001606/10082352/1a4c2086-62ae-11e5-90d8-208bfb57693c.png)

Please describe the problem:
There are no graphs seen for the device Parrot for the parameter peer_connection_1_video_goog_max_decode_ms

**Comment by chrisphn** [comment]
I don't see any data in our datastore for peer_connection_1_video_goog_max_decode_ms:

https://chromeperf.appspot.com/new_points?pattern=ChromeOSPerf%2Fcros-parrot%2Fwebrtc.webrtc_cases%2Fpeer_connection_1_video_goog_max_decode_ms&num_points=111&max_tests=5

Points for 720p_call_45s:

https://chromeperf.appspot.com/new_points?pattern=ChromeOSPerf%2Fcros-peppy%2Fwebrtc.webrtc_cases%2Fpeer_connection_1_video_goog_max_decode_ms%2F720p_call_45s&num_points=111&max_tests=5

**Comment by anniesullie** [comment]
@selavazhagan - It really helps to post a link to the log of the test, and specifically point out:
1. What data was sent to the perf dashboard in the POST request
2. The http response code returned from the dashboard.

**Comment by qyearsley** [comment]
Note, the data is actually at "ChromeOSPerf/cros-parrot/webrtc.webrtc_cases/peer_connection_1_video_goog_max_decode_ms/peer_connection_1_video_goog_max_decode_ms". Viewable at:

https://chromeperf.appspot.com/report?sid=1dcd54a8d5d885dc7bc6ef9058675065c52ae6cebdff06704162f7198fdfe149

Feel free to file a separate bug if you have any other issues or suggestions.
