### ISSUE TITLE
Be able to split out V8 samples costs by optimized/deoptimized

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1525]
When v8 deopts a function, I gather that a trace event is emitted that says that its stack frame is deopted.
```
{"pid":87583,"tid":1299,"ts":299077929171,"ph":"I","cat":"disabled-by-default-v8.cpu_profile","name":"JitCodeAdded","args":{"data":{"code_len":126,"code_start":"0x162208533ca0","name":"Builtin:NotifySoftDeoptimized"}},"tts":6599609,"s":"t"},
```

So, when we have a stack sample, we can look at the leafStackFrame, and see if it is deopted, right?

That makes me wonder, we go build the slice cost report for a v8 slice, can we understand not just the cpu Time spent in that code, but also how much of it was deopted?

**Comment by natduca** [comment]
@chiniforooshan @dj2 @paulirish thoughts?

**Comment by dj2** [comment]
I'm not sure if the above sample would give you want you want, as there is no stack associated. But, I think we have this information already, we just strip it out.

We have basically the same parsing code as DevTools (given I copied theirs) so looking at [1] we strip off the prefixes on the function names. But, those prefixes tell you if the function is compiled, optimizable or optimized. We could store that into the stack frame and do stuff with it if it's sufficient for your purposes.

[1] https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/timeline/TimelineJSProfile.js&sq=package:chromium&q=stackframe%20file:%5Esrc/third_party/WebKit/Source/devtools/front_end/timeline/&l=414

**Comment by natduca** [comment]
Mmm that would be sooooo cooooooool

**Comment by dj2** [comment]
Should these be recorded as separate stack frames in the different states? If so, the UI can look a bit weird (but it's also interesting)

![screenshot from 2015-09-28 13 51 26](https://cloud.githubusercontent.com/assets/9611/10143778/0e96213c-65e8-11e5-8623-311776bff79a.png)

I'm not sure if it's a bug or expected that we don't show anything as being called from the optimized versions?

**Comment by dj2** [comment]
See https://codereview.chromium.org/1371173002/ for prototype. I just added the information to the JSSourceInfo struct as I'm guessing it's pretty JS specific.

**Comment by natduca** [comment]
So cool! Would be awesome if we could update slice_costs.html and slice_cost_report.html to show this data too

**Comment by chiniforooshan** [comment]
1- Add the JSSourceState to the domain name.
2- Add a new grouping by JSSourceState.

I would vote for 1 until we solve #1521. WDYT?

**Comment by natduca** [comment]
How about instead we add three more time columns? ms-in-optimized, ms-in-deopt, etc?

**Comment by chiniforooshan** [comment]
Wouldn't it be confusing that these columns make sense only for "script" rows? Or you are thinking about dynamically changing columns based on what is expanded?

**Comment by natduca** [comment]
You're right they'd only make sense there. We could just leave them empty for the others... its not ideal but I think it'd work for now. Another thing we could do is allow clicking on a row to show details about the row --- instead of it being a column, we could have a split like this:
```
<table></table>
<div>info on selection>
```
Where details on the selection are shown in the div...

**Comment by paulirish** [comment]
I think we can do something lo-fi to start. 
The ads thread is finally putting some numbers to this, but it looks like addressing deopts requires high developer effort and produces limited impact. 

That said, we should start with 1) if things are deopted and 2) the reason. This would help to indicate how much of the JS that V8 encounters is deopted due to try/catch. (My guess is a lot!)

**Comment by natduca** [comment]
I'm not so clear here... how much data do we really have that shows what %
of code is running on the web unoptimized vs optimized vs deopted? There
are three states.... I agree deopt may not be the issue, but it seems a bit
premature to say "because i think deopt isn't a big deal, unoptimized is
also unintresting to get coverage on"

**Comment by natduca** [comment]
Following up with some context from a chat with Paul offline.

I think there're two bits of discussion here: what we wanna show for perf insights [bulk analysis, top down analysis is the goal], versus what we wanna show in the gui for a single trace.

I think Paul's comments about deopt apply mainly for individual trace viewing of sample data: there, he's suggesting that we can just show deopt reasons, instead of showing percentages. I tend to think there's a point there, though I do think we should show what %age of the samples we hit are in optimized, deopted, etc code. I realize there're some tough visualization challenges here so may need to iterate.

As for showing this in perf insights, I think still want to show that topdown data pretty directly: what % of left time is spent in optimized vs deoptimized vs unopted code [assuming thats the right triplet breakdown].

**Comment by chiniforooshan** [comment]
Should I close this?
