### ISSUE TITLE
Sampling summary panel raises exception on trace_cnn.json.gz

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1526]
If you put this trace into trace-viewer:
https://github.com/natduca/measurmt-traces/blob/master/desktop/v8-samples/trace_cnn.json.gz

And then you select all the traces in the first renderer thread, you get this:
```
sampling_panel.html:93 Uncaught TypeError: currentNode.getOrCreateChild is not a function
```

**Comment by natduca** [comment]
Calling @dj2 @chiniforooshan

**Comment by dj2** [comment]
@petrcermak as he's looked into selection a few times.

**Comment by chiniforooshan** [comment]
Funny bug :) The issue is that the title of a frame in the stack is "hasOwnProperty" and so line 34 of sampling_panel.html wrongly thinks the frame is in the map (well, since all objects have "hasOwnProperty"):
```
if (this.childFrameMap[frame.title] !== undefined)
```

I can fix by simply prefixing map keys with an space or something similar...
