### ISSUE TITLE
HistogramSpan needs to dispatch specific brushing events (or mouse events) instead of letting bar chart events bubble

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1527]
The current approach violates layering: the user of a histogramspan should get events about the brushing range of a histogram changing *in terms of bins that are selected.* Right now, you listen for events on the mousedown on the bar charts items, as far as I can tell.

**Comment by natduca** [comment]
@philippebeaudoin fyi, @benshayden fyi 

I'll make this change if you're swamped ben

**Comment by benshayden** [comment]
Looks like this is already done. histogram-span stops the item-mouse{down,move,up} events from propagating, and updatedBrushedRange_ dispatches brushed-bins-changed.
