### ISSUE TITLE
Heap:** counter graphs consume UI hungrily

### ISSUE THREAD

**Issue by paulirish** [catapult-project/catapult#1528]
Working in traceviewer is a bit more difficult now with almost a screenful of each renderer taken up with memory counters.

Can we solve the UI solution by having them collapsed by default or something similar?

**Comment by paulirish** [comment]
cc @primiano

**Comment by petrcermak** [comment]
@paulirish: Could you please provide a screenshot?

**Comment by natduca** [comment]
https://github.com/natduca/measurmt-traces/blob/master/desktop/v8-samples/trace_cnn.json.gz

**Comment by petrcermak** [comment]
Thanks. These counters come **directly from Oilpan** (not through Memory-Infra): https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/platform/heap/Heap.cpp&l=623

**Comment by petrcermak** [comment]
This should most probably be merged into the Memory-Infra UI.

**Comment by primiano** [comment]
Right all that stuff is not memory-infra, it's oilpan and co, and probably could be deprecated. I think we have most of that in memory-infra (which is not enabled in that trace) so we should just remove those.
I have to doublecheck with haraken@

**Comment by paulirish** [comment]
Cool cool. Nat indicated it probably wasn't memory-infra but this extra context helps. 

Awesome. Let us know what haraken says about those counters. Would def love to clean that up.

**Comment by petrcermak** [comment]
Discussion on oilpan-reviews: https://groups.google.com/a/chromium.org/forum/#!topic/oilpan-reviews/AGegKLIIou8

**Comment by petrcermak** [comment]
This should be **fixed** by https://codereview.chromium.org/1372313003/.

**Comment by paulirish** [comment]
Excellent. Thanks all for the help!
