### ISSUE TITLE
Ensure every representative candidate for a histogram bin has equal probability of being chosen.

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1530]
In HistogramBin.add() and .addBin() we discard any new incoming sourceInfo when the sourceInfos buffer of a bin is full. Instead we should implement a mechanism to uniformly and randomly draw from a stream of elements.

To uniformly draw a single element one can prove that you should keep the n-th element of a stream with probability 1/n, then every element of an N-element stream has probability 1/N of being chosen. It's slightly trickier since we want to draw M elements, but the maths can be worked out and they're not too complex.

**Comment by natduca** [comment]
Mmmmmm awesome. 1 plz of these

**Comment by benshayden** [comment]
In case I forget in the code review, it'd be awesome if this math lived in base so it could be used by a Reducer whenever that system comes online. Maybe Statistics?
