### ISSUE TITLE
"undefined" showing up in domain cateogry

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1537]
measurmt traces, desktop, v8 samples, cnn and aol produce:

![image](https://cloud.githubusercontent.com/assets/412396/10148493/b68061fa-65e8-11e5-8b85-0cc191a683bb.png)

@chiniforooshan can you take?

**Comment by chiniforooshan** [comment]
This is because non V8.Execute events like V8.run are grouped as "script", too. Currently, they don't have domain information. If for example we group by "Event Title", undefined should not appear any more. I'll mark this as a dup of #1504.

**Comment by natduca** [comment]
I think undefined though is the wrong label for this? Thats pretty confusing for users... whats the proper reporting?

**Comment by chiniforooshan** [comment]
Yeah, undefined is not acceptable.  I'll find a proper label when I figure out what are v8.run - v8.execute parts exactly, as part of #1504 (maybe something general as "JS engine" or "V8"?).

**Comment by natduca** [comment]
v8.internal? might ping alph

**Comment by chiniforooshan** [comment]
Also, Lan Wei noticed that sometimes the domain is an empty string.

**Comment by chiniforooshan** [comment]
Link to a trace by @SummerLW with empty-domain samples: 

https://drive.google.com/a/google.com/file/d/0B6aINcG6kDLXaF9PRVo0VDktRUk/view?usp=sharing

**Comment by benshayden** [comment]
This doesn't look like it would be needed for anything besides perf-insights. Feel free to reopen?
