### ISSUE TITLE
Sampling panel fails to load for some traces.

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1538]
If you open the trace at https://drive.google.com/open?id=0B7Nc8cbDG517WTF3a3Q1ZldjZFk

And select all samples in the V8 Sampling track, you get:
![screenshot from 2015-09-28 16 12 34](https://cloud.githubusercontent.com/assets/1760798/10151375/c64465b0-65fb-11e5-9d34-7bbc0fdf54a0.png)

And the sampling panel is not loaded.

FYI: @chiniforooshan

**Comment by chiniforooshan** [comment]
This looks identical to #1526. Are you sure you have a ToT checkout?

**Comment by fmeawad** [comment]
Probably yes, I did not sync in couple of days, and looks identical.

Marking as dupe of #1256, I will reopen if the behavior remains after a syncing to ToT.
