### ISSUE TITLE
We might be double-counting domain costs

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1540]
because we can have nested V8.Execute events.

@natduca, FYI

**Comment by benshayden** [comment]
Ethan, you're working on this, right?

**Comment by eakuefner** [comment]
Yes, this is #2190 and I'm working on it this week.

**Comment by eakuefner** [comment]
I'm closing this bug because #2190 is done and it seems like this is a (really old) dupe of that bug. Please feel free to reopen, rename, and reassign if that's not correct.
