### ISSUE TITLE
Add a function to find the page/sub-test with the clearest regression, and use it for bisect.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1544]
Background:
When starting a bisect, the [default "metric"](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/start_try_job.py#L235) (chart/trace name) to use is currently the chart/trace name of the series that the alert occurred on. However, often we find that we get better results when specifying a particular page and looking at results for that particular page. Currently, part of the regular manual triaging process involves looking through per-page results to find the page with the clearest regression.

Proposal:
When starting a bisect, the default "metric" should be the page/sub-test with the clearest regression at a particular revision. The name of the page/sub-test with the clearest regression could also perhaps be displayed somewhere (but I'm not sure where).

There could be a function `SubtestWithClearestRegression(test_key, revision)` that returns the test key of the subtest with the biggest step at that revision. This would likely involve fetching a bunch of rows for each subtest and running [FindChangePoints](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/find_change_points.py#L70) on them.

Advantages: Implementing this could lead to a greater number of successful bisects, and help sheriffs more quickly find the relevant pages to look at.

[Note: This issue was filed based on the team meeting about bisect today.]

**Comment by randomascii** [comment]
This would be great. When investigating a regression the first thing I usually have to do is figure out how to reduce the test case to something that can run more quickly so that I can iterate on it.  Having this done as part of the bisection would be excellent.

**Comment by anniesullie** [comment]
@randomascii makes a great point--we should not only ensure the bisect has information about the clearest regression, but also ensure that it is clearly printed on the bug for anyone diagnosing the regression to see.

**Comment by benshayden** [comment]
Archiving. We discourage alerting on summary timeseries.
