### ISSUE TITLE
[Question] Does histogram span handle the underflow and overflow bins correctly?

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1550]
Histograms have a normal range and an under- and overflow- bin. Do we show those properly in the UI?

**Comment by natduca** [comment]
calling @benshayden cc @philippebeaudoin

**Comment by benshayden** [comment]
I believe so.
http://localhost:8003/tracing/tests.html?testSuiteName=tracing.ui.units.histogram_span_test
The "basic" test has a linear histogram from 0 to 1000 and adds (-1, 'a') and (1000, 'd'). Its histogram-span starts at the left at -100, and ends at the right at 1,100. I inspected the histogram-span and logged brushedBins when it dispatches brushed-bins-changed, and it prints 'a' when I select the first bin, and 'd' when I select the last. Same thing happens when I change 'a' to -100 and 'd' to 2000, just to make sure they're well outside of the explicit range.

**Comment by natduca** [comment]
I think my main concern though is that its not labeled. I think the typical ideal way to display these things is with two bars outside the axis that indicate the over and underflow...

**Comment by benshayden** [comment]
Do you have a picture of what you're thinking? A few minutes googling didn't turn up anything obvious.
I could let the histogram-span configure updateXAxis_ to draw text labels like "<0" and ">100" as if it were a NameBarChart in addition to the normal d3.svg.axis. How does that sound?

**Comment by natduca** [comment]
mmm that'd be pretty cool. i think the basic hope is that those two bars don't mess up the labeling of the central range. I was mostly looking at how uma.googleplex.com/histograms/ works

or chrome://histograms does this:
```
Histogram: AsyncDNS.TimeoutSpentHistogram recorded 561 samples, average = 300.4 (flags = 0x1)
0    ... 
68   ---------------------------------------------O                            (65 = 11.6%) {0.0%}
81   ------------O                                                             (17 = 3.0%) {11.6%}
96   ------------------------------------------O                               (60 = 10.7%) {14.6%}
114  ------------------------------------------------------------------------O (103 = 18.4%) {25.3%}
135  ---------------------------O                                              (38 = 6.8%) {43.7%}
160  ----------------------------------O                                       (48 = 8.6%) {50.4%}
190  -------------------O                                                      (27 = 4.8%) {59.0%}
226  -----------------O                                                        (24 = 4.3%) {63.8%}
268  -------------------------------O                                          (45 = 8.0%) {68.1%}
318  -----O                                                                    (7 = 1.2%) {76.1%}
378  --------------------O                                                     (29 = 5.2%) {77.4%}
449  ------O                                                                   (8 = 1.4%) {82.5%}
533  O                                                                         (0 = 0.0%) {84.0%}
633  ----O                                                                     (6 = 1.1%) {84.0%}
752  --------O                                                                 (12 = 2.1%) {85.0%}
894  --------------------------------------------------O                       (72 = 12.8%) {87.2%}
1062 ... 
````
