### ISSUE TITLE
Allow histogram[or barchart?] to truncate Y-values above 95%-ile

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1552]
A lot of our histograms have a single outlier, usually at the 0 or 1 bin that is way higher than everything else.

![image](https://cloud.githubusercontent.com/assets/412396/10186015/64b09e9c-6702-11e5-8470-1d4ba400cba7.png)

This causes us to lose the rest of the data. Could we do something simple like put a \* above the truncated items, and then be able to tell the chart to just set the limit at a %-ile instead of at max?

**Comment by natduca** [comment]
paging @benshayden

**Comment by benshayden** [comment]
I think BarChart would need to be the one to handle this.

**Comment by natduca** [comment]
Should we mark available and GoodFirstBug to allow triage to other team members?

**Comment by benshayden** [comment]
Done :-)
