### ISSUE TITLE
Throughout trace-viewer and perf-insights, remember sorting as much as possible

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1562]
When the user sorts a table anywhere in trace-viewer or perf-insights, that selection should be remembered and re-used whenever any similar table is created.
Per @paulirish .

Half-baked design proposal:
Clients set tr-ui-b-table.sortPersistenceKey = 'string' such as 'rail-score-side-panel' or 'pi-task-info-report'.
When a table is sorted, it stores sortColumnIndex_ and sortDescending_ in localStorage[SOME_PREFIX + sortPersistenceKey].
When a table is rebuild()ed, it looks up localStorage[SOME_PREFIX + sortPersistenceKey] and sets sortColumnIndex_ and sortDescending_.

Super-tables such as the grouping-table can proxy the sortPersistenceKey.
For more magic, the sortPersistenceKey could be a hash of JSON.stringify(tableColumns).

**Comment by natduca** [comment]
Seems solid but generalize it. settingsKey then have it internally += '.sort' for sorting state. The selected row should be restored by its label path as well [e.g. if i have a > b > c seleted, then tableRows changes, ideally i re-select a > b > c by title]

**Comment by natduca** [comment]
I'm wondering if we should mark this available to allow load balancing to other team members?

**Comment by natduca** [comment]
Lets WontFix due to inactivity. We should figure out how to do this long haul, but units issues are probably more pressing.
