### ISSUE TITLE
Why are these input latency events' start times NaNs?

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1567]
Use your @ chromium account to download this trace:
https://drive.google.com/open?id=0Bwye9Aa8pAMnazhqb0dTZ1RGRE0

**Comment by benshayden** [comment]
Make sure your catapult has this CL: https://codereview.chromium.org/1377443003

The trace still doesn't load in trace-viewer because it's too large, but it can now be processed by map_traces without spewing errors.

**Comment by philippebeaudoin** [comment]
Ooops Missed that closing my dupe at #1568

**Comment by philippebeaudoin** [comment]
When this is fixed, remove the TODO and defensive coding bit in tracing/tracing/extras/rail/rail_ir_finder.html
