### ISSUE TITLE
Perf Dashboard: when linking an alert to an existing bug, ask user if a link to the alert/graph should be added as a new comment

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1569]
Chrome version: 47.0.2522.0 (Windows)
URL: https://chromeperf.appspot.com/report?sid=f14e4f5e00c18b8066e9446f05841e528c558533e50f72f8197a3d19b1fc2171&rev=10104

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
N/A

Please describe the problem:
This alert is part of ~100 other alerts that fired at the same CL. I kept getting backend timeouts while trying to create a new bug linked to all those graphs, so I then took the alternate approach of manually creating [bug 538634](http://crbug.com/538634) first, then tried to link those graphs to that bug. 

In the dashboard UI, that seemed to work because graphs like this one now show the bug link in the alert data point. However, in the bug, I still don't see any linked graphs. I'm guessing this is currently working by design because the dashboard doesn't necessarily know if a bug already has linked graphs. However, it would be nice if, when associating an alert with an existing bug, the dashboard provided an option to add a graph link (e.g. https://chromeperf.appspot.com/group_report?bug_id=538634) in a new comment if, after a quick scan, it didn't see a similar comment already in the bug.

I consider this a P2 feature request at best since I have a workaround - manually add the summary graph link as a comment.

**Comment by qyearsley** [comment]
How I imagine this would be implemented:

 * In [associate_alerts.py](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/associate_alerts.py) `_AssociateAlertsWithBug`, take a parameter to specify whether to add a comment. When adding a comment, we'll require the user to be logged in and use [issue_tracker_service.py](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/issue_tracker_service.py) to post a comment.
 * In the [associate bug HTML form](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/templates/bug_result.html), add a checkbox to say whether to add a comment.

**Comment by benshayden** [comment]
Archiving.
