### ISSUE TITLE
Message for internal-only dashboard data should suggest logging in.

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1573]
Example: log out and load https://chromeperf.appspot.com/report?sid=81237b97ddeafa3408df8a6d57e00d1b48199ea389c50261a9f70af9e6936219&start_rev=336229&end_rev=346831

I get the message: "No data available" and "Failed to fetch graph data". It should remind me to check if I am logged in. Same thing should happen on the group_report page.

**Comment by chrisphn** [comment]
Right, forgot to put that back.

**Comment by chrisphn** [comment]
verified
