### ISSUE TITLE
Perf Dashboard: Alerts page is too slow to load

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1575]
Chrome version: 45.0.2454.101 (Linux)
URL: https://chromeperf.appspot.com/alerts

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
N/A
Please describe the problem:
The alerts page is too slow to refresh. As alerts get triaged, they need to disappear from the alerts page.
Maybe we can do XHR updates of the page, with a refresh time of 30 seconds?

**Comment by anniesullie** [comment]
Duping against #1787
