### ISSUE TITLE
Perf Dashboard: After you click "Show Triaged", the text should change to "Hide Triaged"

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1577]
Chrome version: 45.0.2454.101 (Linux)
URL: https://chromeperf.appspot.com/alerts?sortby=bot&sortdirection=down&triaged=true

Please describe the problem:
In the alerts page, after you click "Show Triaged", the new page should have the ability to hide the triaged alerts, but now, the new page still says "Show Triaged"

I suspect the behavior is the same for "Show Improvments"

**Comment by qyearsley** [comment]
Correct; currently the "show triaged" and "show improvements" buttons are "active" (shown in darker color) when they're "on"; and it would likely be clearer if the text changed as well to show the on/off state.
