### ISSUE TITLE
Dev Server Performance

### ISSUE THREAD

**Issue by egonelbre** [catapult-project/catapult#1579]
I finally was able to start inspecting issue #1156, and I did some modification to the style. The speed that the dev_server starts either tests or the UI is pretty appalling. It takes 24s to fully boot up the UI. *And, I'm usually used to things changing live while modifying CSS/JS.*

Anyways wrote a quick alternative Go dev server, and now the whole thing boots under 3s.

Is there something I'm missing in the workflow ... should it really take 24s to see the changes or are people using some thingy that automatically replaces components while they code? Or is it Windows that is causing such long reload time.

I put the Go server here https://gist.github.com/egonelbre/2cf28c556061a5862c0c. I kept adding things until I was able to run tests and tracing. I assume by normalizing the paths and adjusting as necessary would make the code nicer... (put it into "tracing" folder and run from there)

So, I'm not sure what to do with this knowledge. If people are having to wait 24s for every change then it would be a significant improvement.

1. Maybe, we don't have to use Go for the server and it would be sufficient to tune Python server (I'm not that familiar with internals of how the servers work).
2. Maybe, it's just fine to add the fast-server alternative, after normalizing the URL paths with the file paths. That way there wouldn't be a significant need to keep things in sync when third_party packages need.
3. Completely replace Python dev-server.

The most reasonable seems 2... not sure whether it's worth normalizing the paths, but it should be easy to use even without the normalizing, although there could be more maintenance.

**Comment by egonelbre** [comment]
I just realized that it would be possible to do live reloading of styles.

1. While serving templates attach a unique identifier to each style node... e.g. `class='timeline_view_0`
2. Monitor file changes on disk.
3. When a file changes, push the new CSS content to server via web socket
4. in browser, `el = document.querySelector("body /deep/ timeline_view_0"); el.innerText = new_css_content;`

Shouldn't be too difficult to implement. I.e. the stupid version could just use `/<style>.*</style>/` to find the style content and add identifiers accordingly.

**Comment by dj2** [comment]
I've never seen dev_server take this long to boot. The server starts instantaneously and the UI comes up in a reasonable time. The longest pole seems to be loading the actual first trace that it pulls up. It's possible this is a windows issue.

You also don't need to restart the dev server when changing files on disk (unless you're modifying the dev_server itself.) You should be able to just reload the browser and it comes back pretty much instantaneously here.

**Comment by egonelbre** [comment]
Yeah, I know the server restart is not necessary to see changes.

What do you consider reasonable? For me to see my changes --> tolerable is under 10s, reasonable is under 5s and good is under 1s.

With Go server I have the "Android Systrace" example loaded and showing at 3s mark (cache disabled).

I guess it's just a Windows issue then.

**Comment by dj2** [comment]
From the point I click the link to launch trace_viewer it's about 2s. Probably less because it doesn't start to load until you switch to the tab it's in I believe.

**Comment by egonelbre** [comment]
Tested it under a linux VM, with Go server 2.99s until loaded and rendered, with Python 3.56s until loaded and rendered.

I guess, it's not worth adding to the repo, since it's Windows only problem and keeping servers in sync would be annoying.

I will further extend the Go version to allow live updating CSS. Only for Go, because I already know how to implement it and I want a version that handles page refresh on Windows reasonably. It would be probably nice to have that in python server, but I don't know Python http/websocket libs, so I can't really help there.

I guess I'll close this issue as "python is slow on Windows and no easy fix". If someone else has the issue then he can always grab the go server; I'll keep the gist updated as much as I personally need to. :)
