### ISSUE TITLE
Demo trace theverge_trace.json refuses to open

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1581]
Trying to open theverge_trace.json causes an error "Cannot read property 'time_frame_us' of undefined".

**Comment by dj2** [comment]
Do you mean 'frame_time_us' ?

**Comment by dj2** [comment]
Revert https://github.com/catapult-project/catapult/commit/52904860ef2d751599c9847aa287b0dd16aea1a8 and it works.

**Comment by philippebeaudoin** [comment]
Yup, frame_time_us. Sorry for the typo.

You're fast, I just found out. Pinging @zeptonaut 

We should probably just revert, it causes problems with other traces I tried opening last week.

**Comment by dj2** [comment]
I cheat. I reviewed the CL, so I when I saw it was in the VSync code I guessed, heh.

**Comment by philippebeaudoin** [comment]
Cool. I have a revert CL up for review. Linking you.

**Comment by zeptonaut** [comment]
Sorry about this guys. Looks like it's only been within the past couple of months that these frame arguments have been added to the `BeginFrame` event, so (as Dan initially suggested might be a good idea in the code review), I need to add some checks to make this backwards compatible.

Thanks for finding this, and sorry about the inconvenience.
