### ISSUE TITLE
The sense of "pain" is inverted relative to the senses of "efficiency" and "score".

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1586]
Higher numbers should always be better. "Pain" should be un-inverted to "comfort" or whatever positive word.

"Joy" is short and easy to type, but doesn't conjugate naturally. The graphs would talk about "joy", but you would occasionally want an antonym. We're used to talking about "pain" now, but when you're looking at the word "joy", it would be easier to try to find an antonym starting from "joy". "Ads are unjoyful, they are a source of anti-joy."
"Comfort" is still shorter than "efficiency", and conjugates naturally. When you're looking at charts talking about "comfort" and you reach for an antonym, it's right there. "Ads are a source of discomfort. Our animations are uncomfortable."
"Happiness" also conjugates naturally (unhappy, unhappiness), but is longer and already heavily overloaded.

**Comment by benshayden** [comment]
https://codereview.chromium.org/1357983002

**Comment by natduca** [comment]
Looks like you're working on this, ben.

**Comment by benshayden** [comment]
I think this is done.
