### ISSUE TITLE
Category defaults in "Manually select settings" behave unpredictably on new profiles

### ISSUE THREAD

**Issue by randomascii** [catapult-project/catapult#1587]
If you create a new profile and go to chrome://tracing, Manually select settings, then the default categories (the left column) are unselected the first time you go to record. The second time they are all selected. This suggests there are two bugs:

1) The first time "Manually select settings" is used the left column should be fully selected (or perhaps partially selected if that is desirable, but none seems user hostile).
2) The second time the selection should match whatever the state was when the user left the "Record a new trace..." dialog. Presumably the set of categories associated with "Manually select settings" should be retained so that it is always as the user left it, even if the user uses other tracing options in-between, restarts Chrome, etc.

This odd behavior is not seen by tracing experts because they are long past the first-time usage scenario but this odd behavior is seen by all first-time chrome://tracing users and it confuses them.

**Comment by natduca** [comment]
Gonna dupe into #1943 so we can see the big picture through the details.
