### ISSUE TITLE
Collect unassociated events under IdleExpectations

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1590]
Wouldn't it be natural to just collect any unassociated event overlapping an Idle IR into the associated events for that IR?

Pinging @natduca @benshayden

**Comment by benshayden** [comment]
That is already what happens.
https://github.com/catapult-project/catapult/blob/master/tracing/tracing/extras/rail/rail_ir_finder.html#L164

**Comment by philippebeaudoin** [comment]
Right. Are we sure this works all the time? The reason I'm asking is that I had to put a "0" for the number of associated events to the Idle IR for this test to pass:
https://codereview.chromium.org/1391523004/diff/20001/tracing/tracing/extras/rail/rail_ir_finder_test.html

**Comment by benshayden** [comment]
Ah, that is a puzzle. Does chrome_test_utils set up the processes, threads,
and slices in a way that getUnassociatedEvents can find them?
