### ISSUE TITLE
Collect unassociated events under Load IRs

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1591]
Similarly to #1590  it would feel natural to me if we collected unassociated events overlapping a load IR into that IR. At least for startup Load that would make a lot of sense.

Pinging @natduca @benshayden

**Comment by philippebeaudoin** [comment]
@benshayden You said you were working on this in the team meeting, want to grab this issue?

**Comment by benshayden** [comment]
The RAILIRFinder already vacuums overlapping unassociated events into Loads.
https://github.com/catapult-project/catapult/blob/79a9e9616102784dab85e6751929a79fc6d2b6d0/tracing/tracing/extras/rail/rail_ir_finder.html#L181
Are you not seeing this behavior?

I'm working on only collecting the events that should actually be associated with the Load in a more principled manner based on following flow events: http://go/loadevents
But we can keep that vacuuming behavior for startup loads.

**Comment by benshayden** [comment]
@philippebeaudoin Do you see unassociated events being vacuumed for Startup Load IRs? If not, can you link me to a trace?
