### ISSUE TITLE
Simplify UserExpectation.initiatorTitle

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1595]
Rail IRs and ProtoIRs have a name field at the moment. When we merge them together, as part of the normal process of cleaning up IRs, these names are smashed in an ugly comma separated list like 'Scroll,Tap,Touch'.

I propose we instead:
- When IR names are compatible, merging them should promote them to the dominant concept. ie. 'Scroll,Tap,Touch' --> 'Scroll'  (or 'Tap Scroll?')
- If IR names are not compatible, the IRs should never be merged. ie. 'Pinch' never merges with 'Scroll'.

Ping @benshayden @natduca

**Comment by natduca** [comment]
A common point of confusion when I give a demo is what the names mean when you see 'Mouse,Keyboard'. They get confused. I agree we should try to reduce confusion. Look at this for instance:
![image](https://cloud.githubusercontent.com/assets/412396/10343118/52aa82f6-6cea-11e5-9996-ce56daefe240.png)

I think we want the final name to be the semantic meaning of what is happening, at a user level. IRs are about "user intent" --- when a user is intending to scroll, then there should be a ir named "scroll". Or, if we want, "scroll with mouse". In the long run, you could imagine subcategorization, e.g. "scroll/withMouse" vs "scroll/withFinger" that lets you separate out the different things but I think that is another thing for another day. For now, I think we should aspire to the semantic meaning always being pretty clear.

**Comment by benshayden** [comment]
Yep, names should be a set.

Yep, there should a hierarchy of name specificity. MouseWheel is more specific than Mouse, Tap is more specific than Touch, etc.

Responses and Animations should not have more than one name, but Load will.

I think at one point I had mergeIntersectingResponses() avoid merging keyboard ProtoIRs with anything. I think that feature was lost somewhere in the epic codereview.

**Comment by PhilBeaudoin** [comment]
I think the consensus is for name _not_ to be a set, at least not for the moment.

**Comment by benshayden** [comment]
Maybe we can make progress if we can agree on a complete list of allowable names, names that should make sense to users, and then work backwards and find structure from there?

Let's say that these names cannot mix, so name is a singular string.

Do any of these names not make sense?
Are there any names that are missing from these lists?
Should any of these names be changed?

Response:
Keyboard
Click
Tap
MouseWheel
TouchScroll
Pinch

Animation:
CSS
Javascript (RAF, setTimeout)
MouseWheel
MouseDrag
TouchScroll (includes trackpad scrolling, even on platforms that spell it with "MouseWheel" input events)
Pinch
Fling

**Comment by philippebeaudoin** [comment]
I really like that idea.

Did you intend for TouchScroll to be in both? What about scrolling via
other mechanisms? (ie. click/drag a scrollbar.) Is there enough structure
in traces to identify theses?

Anyway... If we build the architecture around a finite set of
user-understandable response/animation names then we can always add new
concepts (and their structure) when we figure them out.

The challenge may be: what to do when we encounter a structure we don't
know of... My first intuition would be: report it so we can somehow figure
out what the user was doing.

**Comment by benshayden** [comment]
Yes, per #1798, the first frame of a scroll animation is separated into its own Response.

Dragging the scrollbar currently causes MouseMove input events, which RAIL IR Finder separates into a Mouse Response and a Mouse Animation. I think it would make sense to rename both of those from "Mouse" to "MouseDrag", so, yes, I should add "MouseDrag" to the list of Response names. Good catch!

Response: Keyboard, Click, Tap, MouseWheel, MouseDrag, TouchScroll, Pinch
Animation: CSS, Javascript, MouseWheel, MouseDrag, TouchScroll, Pinch, Fling

Currently, RAIL IR Finder ignores any input events whose typeName is not in a whitelist. I think that whitelist is comprehensive, but I could see a defensive programming argument to be made for infobar-ing when an unfamiliar input type is found. Want to file a separate bug?

**Comment by PhilBeaudoin** [comment]
Not sure we need to infobar. This is going to be mostly useless to normal
users. Let's take an approach where we can have a mapper to catch these
weird cases, WDYT?

**Comment by benshayden** [comment]
Oh, I like that. It might fit the Problem framework described in #1758 .

**Comment by benshayden** [comment]
Rick Byers pointed out that trackpad scrolling feels different than touchscreen scrolling, and might want a different comfort curve. He mentioned that the difference is less than 10ms, which is beyond the capabilities of current hardware, so I'm not going to try to split trackpad scrolls from touchscreen scrolls for now. Just FYI.

Relatedly, Macs spell their trackpad scrolling with MouseWheel events, but I have a heuristic to recognize them as TouchScroll IRs anyway. Just FYI.

**Comment by benshayden** [comment]
Have a cartoon about how naming fuzzy concepts let us predict the weather. :-)
https://blog.adafruit.com/2015/11/28/how-did-clouds-get-their-names-saturdaymorningcartoons/

**Comment by natduca** [comment]
I think a quick design sketch doc would be nice --- restate the problem, list a few design options, present a recommendation and a rationale...

**Comment by benshayden** [comment]
Sure!

**Comment by philippebeaudoin** [comment]
On 2 December 2015 at 12:35, Ben Hayden <notifications@github.com> wrote:

> Have a cartoon about how naming fuzzy concepts let us predict the weather.
> :-)
>
> https://blog.adafruit.com/2015/11/28/how-did-clouds-get-their-names-saturdaymorningcartoons/
>
That might explain why I have had this urge to write poetry about IRs. ;)

**Comment by benshayden** [comment]
var INITIATOR_TYPE = {
CLICK: 'Click',
KEYBOARD: 'Keyboard',
SCROLL: 'Scroll',
...
};
var INITIATOR_HIERARCHY = [INITIATOR_TYPE.PINCH, INITIATOR_TYPE.SCROLL, ...];
ProtoExpectation(..., initiatorType) { this.initiatorType = initiatorType; }
PE.merge(...) { if (INITIATOR_HIERARCHY.indexOf(this.initiatorType) < INITIATOR_HIERARCHY.indexOf(other.initiatorType)) { this.initiatorType = other.initiatorType; } }

// or, straight-line code like this instead of a hierarchy, idk
if (other.iT === PINCH) this.iT = other.iT;
if (other.iT === SCROLL && this.iT !== PINCH) this.iT = other.iT;

PE.createInterationRecord() { ... new ResponseExpectation(... this.initiatorType ); new AnimationExpectation(... this.initiatorType) }

**Comment by benshayden** [comment]
@Alex319 , you did it! Want to go ahead and close this?

There are still some ideas in the design doc that aren't done yet, but we have other bugs for most of them, and they can wait until they have a specific motivating force.
