### ISSUE TITLE
Self CPU time > Self time?

### ISSUE THREAD

**Issue by progers** [catapult-project/catapult#1596]
In tracing we noticed that self cpu time is actually greater than self time which doesn't make sense. Are these columns mislabeled?

**Comment by natduca** [comment]
Might be a bug... do you have a trace?

**Comment by progers** [comment]
Wkorman and I were catapulting using the view where you can see many selections at once and the self cpu time is frequently over the self time. We were quite confused. I just tested this again and see that there's a little notification in the single-selection view that says this is a known limitation of the system.

This issue is less scary now that I've seen the notification. This only reproduces on linux btw. We could add the little notification to the view with multiple selections.

**Comment by natduca** [comment]
Wanna turn that last part into a fresh bug? Then we can close this and get that one piece on someone's radar?

**Comment by progers** [comment]
Done!
https://github.com/catapult-project/catapult/issues/1618
