### ISSUE TITLE
Tracing keyboard shortcuts and Chrome shortcuts interfere

### ISSUE THREAD

**Issue by jeremyroman** [catapult-project/catapult#1600]
I sometimes have two traces open in Chrome tabs. When I use Ctrl+1 and Ctrl+2 to switch between the tabs, trace-viewer also switches tools (e.g. when I switch to tab 2, I see the zoom tool selected, followed by the drag tool).

This is inconvenient as I then have to select the right tool, constantly, as I compare two traces.

**Comment by eakuefner** [comment]
This no longer appears to be an issue, since tracing tools are selected using unprefixed numbers (1,2,3). I couldn't repro on Mac.
