### ISSUE TITLE
Rewrite Dashboard trace URLs to point to new bucket

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1601]
@qyearsley @nedn @Apeliotes 

We want to switch buckets for storing Telemetry output, from `chrome-telemetry` to `telemetry-output`. I see two possible schemes for handling this from the Dashboard side:
1.  Rewrite the datastore entities containing the URLs -- we could probably reuse some of the `migrate_tests` logic since this is basically just "change this prefix into that other prefix"
2.  Dynamically detect uses of the `chrome-telemetry` bucket and rewrite them -- this would be a much easier hack, but has a much higher amortized computation cost.

Quinten, WDYT?

**Comment by qyearsley** [comment]
The trace URLs are stored with the Row entities, so option 1 (getting all row entities with a tracing URL, changing it and re-putting the entities) would take a long time and would either involve adding a new temporary handler based which puts tasks on the task queue (probably would take a very very long time) or adding a mapper function (I don't think this would work; we're already having problems with mapreduce jobs on Test entities that never finish, I don't think jobs with Row entities would finish.

So, option 2 sounds better to me. On the dashboard side, this would just mean changing [graph_json._GetTracingUri](https://github.com/catapult-project/catapult/blob/4e049bc357279c00a1f4c55cf3be10234267236d/dashboard/dashboard/graph_json.py) to replace "chrome-telemetry" with "telemetry-output". Also, of course, new points can be sent with a tracing_uri with the new bucket name.

**Comment by anniesullie** [comment]
Any reason not to leave old traces in `chrome-telemetry` bucket and move new ones to `telemetry-output`?

If not, I think we should go with @qyearsley's suggestion.

**Comment by anniesullie** [comment]
@eakuefner is this fixed?

**Comment by eakuefner** [comment]
Sort of. New traces are being uploaded to `telemetry-output` as of October 2015: https://codereview.chromium.org/1392973004 but we haven't copied the old traces over from `chromium-telemetry`. I think @Apeliotes's argument for not keeping the old traces in `chromium-telemetry` was just that they clutter that bucket, which is used for the day-to-day functioning of Telemetry (stores dependencies and recordings).

I've marked this as a good first bug, so here's what someone would need to do to close this out:

1. List the contents of `chromium-telemetry`, and filter all the trace paths into a file.
2. For each trace, copy it from `chromium-telemetry` into `telemetry-output`.
3. Make a dashboard change that rewrites the trace URLs as @qyearsley suggested
4. Write a temporary unit test that uses an actual old trace URL and makes sure it can be retrieved from the new bucket
5. If it works, delete all the old traces from `chromium-telemetry`.

**Comment by nedn** [comment]
TBH, I am not sure whether the old traces are still useful to many people :-)
Maybe we can just copy them all to telemetry-output and call it a day?

**Comment by benshayden** [comment]
Archiving.
