### ISSUE TITLE
Rename "Allocator" to "Subsystem" in the Memory UI

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1603]
_[suggested by @primiano in https://codereview.chromium.org/1388933002/]_

Stuff like skia, webcache are not really "allocators".

**Comment by petrcermak** [comment]
If we want to do this, then it should be done in both the _analysis_ and _timeline_ views. Unfortunately, "subsystem" is longer than "allocator" and it **doesn't fit into the track heading**:

![screenshot from 2015-10-23 15 00 22](https://cloud.githubusercontent.com/assets/2546601/10694611/06e5aaa8-7997-11e5-81e4-5daec29b1977.png)

One option would be to **abbreviate** "subsystem", but the result looks a little odd to me:

![screenshot from 2015-10-23 15 03 32](https://cloud.githubusercontent.com/assets/2546601/10694661/524ca618-7997-11e5-9a77-415556e2d32a.png)

Another option is to add a **tooltip**, but there's a good chance no one will ever know it's there:

![screenshot from 2015-10-23 15 05 15](https://cloud.githubusercontent.com/assets/2546601/10694708/9561fb06-7997-11e5-8c45-676efcd08c0a.png)

Yet another possibility is to completely drop the word "allocated" (at which point we should perhaps rename "Used memory" as well):

![screenshot from 2015-10-23 15 09 09](https://cloud.githubusercontent.com/assets/2546601/10694789/11463b38-7998-11e5-90a1-cee1c0c3abf4.png)


@primiano: Any thoughts?

**Comment by primiano** [comment]
Memory per subsystem LGTM.
Also this made me realized that allocated was not great as we are trying to move to a model where we report the resident memory per subsystem (when we know it)

**Comment by petrcermak** [comment]
Should I also rename "Used memory"  to "Memory per process"?

**Comment by petrcermak** [comment]
One more idea: Use "component" instead of "subsystem".

**Comment by primiano** [comment]
Memory per process LGTM, it's also consistent with the new name.
Component also LGTM, I'm happy with both, you chose :).

**Comment by petrcermak** [comment]
This is now **done** :tada:
