### ISSUE TITLE
Trace didStartProvisionalLoad in Deep Reports

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1604]
C.f. https://code.google.com/p/chromium/issues/detail?id=541635

Deep Reports starts tracing in the didStartProvisionalLoad observer callback, after the RenderFrameImpl::didStartProvisionalLoad trace event would have started, but before it will end.

RAILIRFinder requires a non-async slice named RenderFrameImpl::didStartProvisionalLoad or similar to be a parent of the attending ResourceFetcher::requestResource trace event.

**Comment by natduca** [comment]
I think we do slow reports bugs in chromium

**Comment by fmeawad** [comment]
Closing the issue, as it will be tracked in crbug.
