### ISSUE TITLE
run_py_tests for py_vulcanize in wrong place

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1605]
The recipe looks for it in third_party/py_vulcanize/bin/run_py_tests but it is not in a bin dir.

**Comment by qyearsley** [comment]
Note:
https://codereview.chromium.org/1395593003/ (Annie's CL) and https://codereview.chromium.org/1388233006/ (my CL) were created to try to address this but the py_vulcanize tests didn't pass.

Note that tvcm tests were last run on the waterfall before https://codereview.chromium.org/1378893002/, which also changed the test runner to use typ; tvcm tests haven't been successfully run on the waterfall with typ yet, although the tests all pass when I run them locally.

**Comment by anniesullie** [comment]
I found the problem. html5lib imports six, and the pythonpath was not always set up for that, but since it's still an import error bs4 reports it as not having html5lib installed. **fixed**.
