### ISSUE TITLE
Update Systrace to follow the tracing clock sync architecture

### ISSUE THREAD

**Issue by wangzhen127** [catapult-project/catapult#1607]
We need to update Systrace to follow the tracing clock sync architecture.

The master bug: https://crbug.com/534578

@wangzhen127 @ChrisCraik @nedn

**Comment by wangzhen127** [comment]
Currently atrace uses sync mode. We need to update atrace to use async mode. And some tricks for pre-M devices should be kept in mind due to some atrace bug. For more details, see https://code.google.com/p/chromium/issues/detail?id=512891

I expect the new way will be similar to the systrace_controller in adb_profile_chrome:
https://code.google.com/p/chromium/codesearch#chromium/src/tools/profile_chrome/systrace_controller.py

Eventually, systrace_controller in adb_profile_chrome and systrace_agent in systrace.py should be merged.

**Comment by wangzhen127** [comment]
@Alex319

**Comment by nedn** [comment]
Hmh, should we block this bug on the bug that overhaul tracing_controller_bin?

**Comment by wangzhen127** [comment]
I think so. I will check with @ChrisCraik about this next week. He is currently OOO.

**Comment by wangzhen127** [comment]
@Alex319, this is the thing I mentioned in the meeting. If you want to add battor_agent to systrace.py, you will need to refactor systrace to follow the tracing clock sync architecture. Otherwise, there is no way to sync the clock.

This is different from what @randalnephew  is doing in Telemetry.
