### ISSUE TITLE
GPU helper doesn't know about gpu threads outside the gpu process 

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1608]
Follow on to https://github.com/catapult-project/catapult/issues/1514

The code in `tracing/tracing/extras/chrome/chrome_gpu_helper.html` bails out when the process contains a renderer or browser main thread. But on some android devices the GPU threads run in other processes. In this case we should extract the GPU threads by name and exclude them from the other lists.

**Comment by benshayden** [comment]
Is this still needed for anything in particular?
