### ISSUE TITLE
Distinguish "0.0 B" value and diff

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1609]
_[suggested by @primiano offline]_

The new memory dump multi-selection analysis sub-view (#1369) doesn't visually distinguish between _zero_ values and diffs:

![screenshot from 2015-10-13 11 18 17](https://cloud.githubusercontent.com/assets/2546601/10452277/220ad91e-719c-11e5-98fd-f6c759eaa7df.png)

Ideas how to address this:
  * Make zero diffs grey.
  * Prefix zero diffs with "±".
  * Prefix zero diffs with "Δ".

**Comment by natduca** [comment]
Drive by: does our scalar span do this part of the feature? It seems like getting this right is pretty tough so it'd be great if it was reusable code. :)

**Comment by petrcermak** [comment]
The scalar span adds the "+" or "-" prefix. "+" is only added when <tt>span.alwaysShowSign = true</tt>. The color is currently performed externally.

I suppose it would make sense to make the span perform all of the above (prefix + color) and rename the property to <tt>isDelta</tt> (instead of <tt>alwaysShowSign</tt>)?

**Comment by natduca** [comment]
Mmmmm that sounds nice. Again, this is all under the "this'd be great if" heading ...

**Comment by petrcermak** [comment]
I **renamed** the property from <tt>alwaysShowSign</tt> to <tt>isDelta</tt> and added the "±" **prefix** to zero deltas.

Regarding the **colors**, I want to wait with this until the new memory dump multi-selection analysis (#1369) sub-view is sufficiently stable.

**Comment by petrcermak** [comment]
I've given this some thought and I think that <tt>\<tr-ui-u-scalar-span\></tt> could have an __<tt>improvementDirection</tt> property__ (possible values: <tt>ImprovementDirection.UP</tt>, <tt>ImprovementDirection.DOWN</tt> or <tt>undefined</tt>). This is analogous to the [<tt>ScalarValue</tt>](https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/value/scalar.py&sq=package:chromium&type=cs&l=16) class and the [<tt>improvement_direction</tt>](https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/value/improvement_direction.py&sq=package:chromium&type=cs) module in Telemetry.

Proposed patch: https://codereview.chromium.org/1640593003/

@natduca: WDYT?

**Comment by anniesullie** [comment]
@eakuefner @nedn @dave-2 since we've all been thinking about how to manage values across catapult.

**Comment by natduca** [comment]
Can the unit object have the direction instead of the span?

**Comment by petrcermak** [comment]
I agree that <tt>isDelta</tt> and <tt>improvementDirection</tt> should be associated with the value rather than the span. Wouldn't it make the most sense to __formalize the concept of <tt>{unit+delta+improvementDirection}</tt>__ (can't think of a good name, maybe "descriptor"?):

```
var descriptor1 = {
  unit: sizeInBytes,
  isDelta: false
};
var descriptor2 = {
  unit: sizeInBytes,
  isDelta: true,
  improvementDirection: UP
};
...
```

In my opinion, this neatly avoids the need for combinatorial explosion whilst not adding new fields to scalars, histograms, etc. (they would have to have a descriptor instead of a unit reference though).

**Comment by natduca** [comment]
I think thats kinda what I had hoped units to be. I like the descriptor concept though. I wonder if what you call descirptor is really unit, and what is currently called unit is really unitPresentationInfo. And, I wonder how Unit.preferredTimeUnit works in this world.

**Comment by petrcermak** [comment]
Following yesterday's discussion with @natduca (document: https://goo.gl/pmW6F2), I rewrote the patch to store the <tt>isDelta</tt> and <tt>improvementDirection</tt> flags on units instead: https://codereview.chromium.org/1654243004/

**Comment by petrcermak** [comment]
This is now **done** :tada:
