### ISSUE TITLE
Change /stats to report the number of AlertGroup entities.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1614]
In order to tell how our reporting is going, it may be helpful to change [stats.py](https://github.com/catapult-project/catapult/blob/155650a8b278f6eafb6a7422682e8f2646b889ac/dashboard/dashboard/stats.py) to query AlertGroup entities; number of AlertGroups is a proxy for "amount of sheriff work".

Note: Currently AlertGroup doesn't have a "time-created" property, but AlertGroup entities can be gotten from Anomaly entities.

**Comment by anniesullie** [comment]
This endpoint was removed.
