### ISSUE TITLE
Write C++ library to communicate with the BattOr

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1617]
In order to communicate with the BattOr from within Chromium, systrace.py, Telemetry, etc., we want some common C++ library that knows how to start and stop tracing and record clock sync markers on the BattOr, given its serial path. For more info on how this decision was reached, see this @chromium.org doc: http://bit.ly/1jwqGpT.

Parallel Chrome bug: https://goo.gl/ThaR2g

**Comment by aschulm** [comment]
In order to achieve this, we must implement USB clock sync in Trace-viewer. Therefore, I will attach patches related to USB clock sync to this issue.

**Comment by zeptonaut** [comment]
We've implemented clock sync for the BattOr in trace viewer now, so I'm going to go ahead and mark this as closed. The way that we're doing that clock sync is going to change soon, but the functionality is in place and will stay put
