### ISSUE TITLE
Update alert grouping rule so that alerts for the same Telemetry measurement are grouped together.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1624]
Currently, the AlertGroup model contains a list of test suites (aka benchmark names). For Telemetry measurements, I can see we'd usually get better grouping if we grouped only the part before the first period in the benchmark name (e.g. "smoothness", "dromaeo").

It may be worthwhile to extend [AlertGroup](https://github.com/catapult-project/catapult/blob/2091404475cbba9b786442979b6ec631305275a6/dashboard/dashboard/models/alert_group.py) so it also stores test suite prefixes?

**Comment by benshayden** [comment]
Archiving
