### ISSUE TITLE
Add support for Chromium Heap Profiling tracing data

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1625]
Chromium design document: https://docs.google.com/document/d/1xMbBA0w5UunhTzZkdUfFIS63nRNjU6PP3wd2vf1_Ca8/edit?usp=sharing

**Comment by petrcermak** [comment]
I built a **working prototype** of the "Heap details" view in the Memory UI today:

![screenshot from 2015-10-21 18 11 00](https://cloud.githubusercontent.com/assets/2546601/10644201/422998be-781f-11e5-8e5f-f91dd1128856.png)

_Important question:_ Do we want the **self size** to be a **row**, or a **column**?

Option 1: **Row** (Trace Viewer screenshot)
![screenshot from 2015-10-21 18 17 16](https://cloud.githubusercontent.com/assets/2546601/10644403/703da4ec-7820-11e5-8fb2-a5fc366d5174.png)

Option 2: **Column** (DevTools screenshot)
![screenshot from 2015-10-21 18 16 05](https://cloud.githubusercontent.com/assets/2546601/10644427/96208f08-7820-11e5-9843-62443935d63f.png)

**Comment by primiano** [comment]
At the risk of sounding boring, this is terrifyingly cool :)

Only two comments.
1) As regards the row vs column, I think the approach I've seen more often is having two columns: a cumulative one (total for this and all children) and a "this node only" one (what you call self I guess).

2) I don't like too much the fact that, in the main tracing table, we have an extra column for "partition_alloc_heap". Would like to keep that at a minimum.
Can we say that when you click to the standard PartitionAlloc, if it has a heap dump, you get an extra pane somewhere (maybe just below the table, as a starter) ?
i think the magic which triggers the extra pane should be: the heap dumps should have a key like "partition_alloc/objects" or just "partition_alloc" which should match the name of a memory allocator dump. When it matches you trigger the extra pane.
Does it make sense?

**Comment by petrcermak** [comment]
> At the risk of sounding boring, this is terrifyingly cool :)

That never gets boring :blush:

> Only two comments.
1) As regards the row vs column, I think the approach I've seen more often is having two columns: a cumulative one (total for this and all children) and a "this node only" one (what you call self I guess).

Acknowledged.

> 2) I don't like too much the fact that, in the main tracing table, we have an extra column for "partition_alloc_heap". Would like to keep that at a minimum.
Can we say that when you click to the standard PartitionAlloc, if it has a heap dump, you get an extra pane somewhere (maybe just below the table, as a starter) ?
i think the magic which triggers the extra pane should be: the heap dumps should have a key like "partition_alloc/objects" or just "partition_alloc" which should match the name of a memory allocator dump. When it matches you trigger the extra pane.
Does it make sense?

I knew you'd say that. It's fine with me not to have an extra column for the heap data (to be honest, I added it mostly to speed up development). The only issue is: What do we do if there *isn't* a memory allocator dump, but there *is* a heap dump (for the same allocator)?

I'm afraid that simply adding another pane at the bottom of the analysis sub-view won't work well in terms of UX (because the sub-view will lose your scroll position each time you change the selection). Nevertheless, I might do it as a starter (as you suggested) and then try to come up with something better as a follow-up :smile:

**Comment by primiano** [comment]
> The only issue is: What do we do if there isn't a memory allocator dump, but there is a heap dump (for the same allocator)?

We call it a bug and you do whatever it's easier for you :)

> I'm afraid that simply adding another pane at the bottom of the analysis sub-view won't work well in terms of UX (because the sub-view will lose your scroll position each time you change the selection). Nevertheless, I might do it as a starter (as you suggested) and then try to come up with something better as a follow-up :smile:

Make sense. Of course, "you are the expert" (cit. https://www.youtube.com/watch?v=BKorP55Aqvg)
As long as the heap dumps are all perpendicular to each other I'm happy.
Also, could you please make sure to draw the PartitionAlloc dumps with invisible ink?

**Comment by natduca** [comment]
I'd follow devtools' lead. Maybe we could also get opinions from tokyo memory members... I don't know their github ids tho hehe so I'll IM this thread to them :)

**Comment by ruud-v-a** [comment]
For reference, this is what the VS2013 tools look like:
![vs2013-memory-profiling](https://cloud.githubusercontent.com/assets/506953/10667491/8929cf9e-78cf-11e5-9ad1-aca51a1d4e30.png)

**Comment by petrcermak** [comment]
Here's a link to the design document for global stackframes in Chrome traces (for future reference): https://docs.google.com/document/d/1YpPnj5DGX2XaZiSOCuQ96YKXQd_qf-CuSfe1LSzVeaU/edit?usp=sharing

**Comment by petrcermak** [comment]
So here's a screenshot of the **first version of heap dump visualization in Trace Viewer** (patch coming up shortly):

![screenshot from 2015-10-30 11 32 41](https://cloud.githubusercontent.com/assets/2546601/10844774/66cee016-7efa-11e5-9f62-d63d42aabdca.png)

**Comment by petrcermak** [comment]
**Object types** in the heap dump UI are only two patches away!

![screenshot from 2016-01-11 12 24 42](https://cloud.githubusercontent.com/assets/2546601/12233351/8008821a-b85e-11e5-9dc3-a707bbcc880f.png)

**Comment by petrcermak** [comment]
For anyone who wants to get their hands on object types in the heap dumps UI before they make it to master, here's a **patch** which you can apply locally: **https://codereview.chromium.org/1577073003** (it already includes (https://codereview.chromium.org/1528543002/).

**Comment by petrcermak** [comment]
Now they're only _one review_ away :tada: (https://codereview.chromium.org/1585983004):

![screenshot from 2016-01-14 15 48 16](https://cloud.githubusercontent.com/assets/2546601/12329070/69d81670-bad6-11e5-8ff4-a4ccccba1542.png)

**Comment by petrcermak** [comment]
The Chromium tracking bug (https://code.google.com/p/chromium/issues/detail?id=524631) has been closed and the Trace Viewer UI supports all relevant features, so I'm marking this as **fixed**.
