### ISSUE TITLE
Speed up import on trace_aol by 2x

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1626]
https://github.com/natduca/measurmt-traces/blob/master/desktop/v8-samples/trace_aol.json.gz

**Comment by nedn** [comment]
Some insights:
<img width="1264" alt="screen shot 2015-10-15 at 3 55 19 pm" src="https://cloud.githubusercontent.com/assets/911877/10525866/319559da-7355-11e5-847a-3473197c6706.png">
<img width="1279" alt="screen shot 2015-10-15 at 3 56 29 pm" src="https://cloud.githubusercontent.com/assets/911877/10525900/551d1bfe-7355-11e5-90f5-adec3d044a5e.png">

**Comment by chiniforooshan** [comment]
- Note that traces in that directory may have too many categories enabled. Their sizes are much larger than deep report traces, for example.

- I'm not sure, but this and #1486 may be the same...?

**Comment by natduca** [comment]
@nedn how'd you get the data for that graph?

**Comment by nedn** [comment]
Nat: just add '--prof' to v8_args when you invoke vinn's RunFile . Then after a run, look for v8.log file & open it with traceviewer.

**Comment by benshayden** [comment]
Can you tell if findAllInteractionRecords is spending more time in findLoadInteractionRecords, findInputInteractionRecords, findIdleInteractionRecords, or collectUnassociatedEvents_? And so on within those methods?

**Comment by nedn** [comment]
Ben, you can play with the v8 trace here: https://crash-staging.corp.google.com/browse?q=reportid=%27861a4adf5fe0a67e%27#6

**Comment by benshayden** [comment]
Thanks!
This appears to confirm that a huge fraction of findInputInteractionRecords is spent in getSortedInputEvents, which is eminently cacheable. CSS and Fling async slices can also probably be sped up by making them more targeted.
collectUnassociatedEvents_ accounts for almost half of findAllInteractionRecords, however. I'm hoping that Load associatedEvents will help with that. I don't immediately see any other way to speed it up.

Anything else need to be done for this issue?

**Comment by natduca** [comment]
I'm updating the title to make the bug more actionable. :)

Lets take discussion of the findInputInteractionrecords to #1654. When we have that resolved [which sounds worth resolving] we can come back to this bug to figure out "what else" :)

**Comment by fmeawad** [comment]
@lpy fyi. Nat, do you need to own this one?

**Comment by natduca** [comment]
Mmmm lets give it to @lpy

**Comment by nedn** [comment]
Is this bug dropped?

**Comment by benshayden** [comment]
This has been fixed, I think?
