### ISSUE TITLE
In test-picker for latest version, monitored suites are marked as unmonitored

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1627]
Example:
https://clean-qyearsley-11e899db-dot-chromeperf.appspot.com/report
In the first test-picker enter the name of a benchmark that we know is monitored, e.g. sunspider; note that everything is marked as unmonitored.

Likely cause:
https://codereview.chromium.org/1390913009

@chrisphn

**Comment by chrisphn** [comment]
I need to clear and repopulate the cache for test suite and subtest dict since they were restructured in that CL.  Will do it tonight during down time.

**Comment by anniesullie** [comment]
If this has potential to make menus not work while it's repopulating, please use https://chromeperf.appspot.com/set_warning_message

**Comment by chrisphn** [comment]
Vacuuming indexes.

**Comment by chrisphn** [comment]
It's done.  Deployed new version.

Notice few deprecated test suites are at the bottom.  And if you navigate through sub-selection menus, they should also show 'deprecated' label.
