### ISSUE TITLE
Gsutil license prevents rolling Catapult in Chromium

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1628]
I've just tried updating Catapult in Chromium DEPS (https://codereview.chromium.org/1411493004/) and got the following checklicenses failure (http://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_rel_ng/builds/127504/steps/checklicenses%20%28with%20patch%29/logs/stdio):

```
'third_party/catapult/third_party/gsutil/gslib/exception.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/boto_resumable_upload.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_help.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_naming.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_plurality_checkable_iterator.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_util.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_wildcard_iterator.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_parallelism_framework.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_parallel_cp.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/tests/test_update.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/gslib/third_party/storage_apitools/credentials_lib.py' has non-whitelisted license 'UNKNOWN'
'third_party/catapult/third_party/gsutil/gslib/__init__.py' has non-whitelisted license 'BSD MIT/X11 (BSD like)'
'third_party/catapult/third_party/gsutil/third_party/httplib2/libhttplib2.tex' has non-whitelisted license 'UNKNOWN'
'third_party/catapult/third_party/gsutil/third_party/httplib2/python3/httplib2/iri2uri.py' has non-whitelisted license 'UNKNOWN'
'third_party/catapult/third_party/gsutil/third_party/httplib2/python3/httplib2/__init__.py' has non-whitelisted license 'UNKNOWN'
... (853 lines in total) ...

FAILED

Please read http://www.chromium.org/developers/adding-3rd-party-libraries
for more info how to handle the failure.
```

**Comment by petrcermak** [comment]
@anniesullie, @simonhatch FYI

**Comment by primiano** [comment]
Why do we have our own gsutil and don't use the one from depot_tools?

**Comment by petrcermak** [comment]
@primiano: No idea. It was copied here from Telemetry (https://codereview.chromium.org/1377933002).

I've just requested whitelisting the licences in Chromium: https://codereview.chromium.org/1412653004.

**Comment by nedn** [comment]
We use the one from depot_tools because it's more up to date. We have been seeing cloud storage flakiness in the past due to the gsutil being outdated. Also sometimes clients don't sync the depot_tools up to date, and that causes telemetry failure as well. So it would simplify the support if we have more control of the software stacks.

**Comment by natduca** [comment]
Erm, does using catapult require depot tools? I get the argument here at an eng level but remember people try to use our tools just by cloning catapult. If we are saying you have to have depot tools, then we probably want to enforce that somehow...

**Comment by nedn** [comment]
No, that's why we copy gsutil to catapult/third_party.

**Comment by petrcermak** [comment]
This has been **resolved** (https://codereview.chromium.org/1412653004) and I successfully rolled Catapult in Chromium (https://codereview.chromium.org/1411493004/).
