### ISSUE TITLE
[trace-viewer] Allow for top-down as well as bottom up views of the Stack samples tree

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1629]
Currently, the stack samples analysis view only displays a bottom-up tree, we would like to have a top-down as well a bottom-up trees.

The array reverse here need to be optional:
https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/extras/analysis/sampling_panel.html#L87

And the UI should have a check box for it.

The original implementation of the tree view landed in https://codereview.chromium.org/1315843003 and tracked by #1233

**Comment by natduca** [comment]
Is the current code really bottom up? I looked at it in the gui and it does what I think of as top-down... the top of the tree is the root stack frame, rather than the leaf stack frame... bottom up implies to me leaf stack frames as the top of the tree.

Anyway, we should stil do this. But we should agree on which words mean which, too. :)

**Comment by randomascii** [comment]
We can all agree on what the top of the screen is, but there is no consistent agreement on what the top of the stack is. Equally convincing arguments can be made for 'top' being the root or the leaf of a call stack.

I think the terms 'root' and 'leaf' are much clearer. That would mean that the options could be described as "root at top" or "leaf at top". Or, maybe "root to leaf" versions "leaf to root". I'm not really happy with any of these options, but bottom-up is meaninglessly ambiguous to me.

**Comment by natduca** [comment]
@lpy fyi!

**Comment by natduca** [comment]
@paulirish which word does devtools use for top-down?

**Comment by paulirish** [comment]
Call tree. 
That's also what Instruments uses.

**Comment by natduca** [comment]
But what do they call it when it goes the other direction?

**Comment by randomascii** [comment]
@natduca said:

> @paulirish which meaning does devtools couple to the word top-down?

Your question is ambiguous! I honestly don't know for sure what people mean when they say top-down stack. Luckily it usually doesn't matter - I just choose the other option if I don't like the first one.

**Comment by paulirish** [comment]
here's a quick perusal of various profilers:

#### devtools tree-view:
top-down: "Call tree"
bottom-up: "Costly functions"

#### Devtools CPU profiler
top-down: "Tree (top-down)"
bottom-up: "Heavy (bottom-up)"

#### Instruments 
top-down: "Call tree"
bottom-up: "Invert call tree" (as a setting)

#### YourKit 
top-down: "Call tree"
bottom-up: "Hot spots"

#### VTune 
top-down: "Top-down Tree"
bottom-up: "Bottom-up"

I've also seen "Entrypoints" for top-down, which I like.

**Comment by natduca** [comment]
That is awesome Paul, thank you!

**Comment by fmeawad** [comment]
lpy@ is working on it.

**Comment by lpy** [comment]
The array reverse is now at https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/analysis/multi_sample_sub_view.html#L88

**Comment by fmeawad** [comment]
We need to agree on a a name, since the CL is ready (by @lpy) at https://codereview.chromium.org/1408123007/

**Comment by paulirish** [comment]
I'd recommend:

* "Call tree (top-down)"
* "Heavy (bottom-up)"

based on what i'm seeing in that CL, bottom-up is actually bottom-up. ;)

**Comment by petrcermak** [comment]
Assigning this to myself because I'm improving the bottom-up (heavy) view to be in line with DevTools and factoring out the views so that they could also be used in memory heap dumps (#1625): https://codereview.chromium.org/1428803002/

**Comment by fmeawad** [comment]
@lpy landed a CL that has a good starting point for bottom-up / top-down views. And it is up and running now.

@petrcermak I think this bug should be closed and the changes you are working on should be filed in a new bug.

**Comment by petrcermak** [comment]
Well, the "damage" is done now: I've just landed the refactor :innocent:

Anyway... I'm closing this because it's indeed **fixed**.
