### ISSUE TITLE
Unify sampling panel back into multi_sample_sub_view.html

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1635]
originally, sampling panel was separated from multi sample sub view because samplign panel used d8 and thus bloated our code size. But, it has been rewritetn to use tables. So I think we should move all the code from sampling panel out of extras and into the main mssv.html file.

**Comment by natduca** [comment]
@lpy want to take this bug?

**Comment by lpy** [comment]
This issue is resolved due to https://github.com/catapult-project/catapult/commit/0da2025db75bcf946433c75e4a4241291428afd5
