### ISSUE TITLE
Teach PI knows how to vulcanize & run d8 on the vulcanized file instead of using vinn directly

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1636]
According to the investigation in https://codereview.chromium.org/1403203002/, running d8 directly on the vulcanized js helps saving the initial import of vinn, which is slow due to the slow html parsing & eval. The saving is around 300 - 400ms per mapper job.

FYI: @natduca

**Comment by nedn** [comment]
I think this should be done at vinn level, because we still need to load the d8_boostrap.js properly anyway. The other option is to exposed s.t like vinn.GetD8BootStrapCode(), which I feel a bit weird.

Question: if we go with the first route, is it sane for vinn to depend on py_vucalnize? Or if not, can it depend on py_vucalnize in short term? Given the html parsing logic we already have in vinn, it's not that bad to create a js_base_vulcanizer in vinn/.

**Comment by nedn** [comment]
nvm, we can vulcanized & run vinn.EvaluateFile(..) on the vulcanized file to get the boot strap file

**Comment by natduca** [comment]
I'm not sure I like the idea of vinn doing this. It seems like that bloats the role of vinn, which was supposed to be a simple d8 wrapper. Now its a strange optimizer too?

**Comment by nedn** [comment]
Won't fix.
