### ISSUE TITLE
validateConnectedEvents test fails on Chrome 48 because of RequestIdleCallback, but not on CQ

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1637]
On Chrome 48 and catapult ToT, validateConnectedEvents fails. I've verified that reverting:
  https://codereview.chromium.org/1387793002/
fixes the issue. That patch moves our RequestAnimationFrame-based task chaining to RequestIdleCallback when available.

It looks like it may have passed CQ because the CQ bots are not running a version of Chrome that supports RIC. However it fails locally.

I haven't reverted the CL yet since trace-viewer itself doesn't seem broken, it's just that the test relies on a utility function to consume the RAF queue which no longer works. At that point fixing the test might be the right thing to do.

We should also have a post-mortem on this, figure out if we should have a more robust CQ.

Ping @natduca @skyostil @anniesullie

**Comment by philippebeaudoin** [comment]
Also happend on tracing.ui.timeline_viewport_test.locationObj

**Comment by natduca** [comment]
@skyostil i'm thinking maybe the core bug here is that we have code that forces rafs/idles to run. Maybe we should revisit how our raf.html works a bit?

**Comment by philippebeaudoin** [comment]
@skyostil Has this been fixed? I don't see the problem anymore.

**Comment by natduca** [comment]
This needs fixing, its still happening. P1. @philippebeaudoin please revert the setIdle if needed.

**Comment by skyostil** [comment]
Sorry, I never saw the email notification about this. I'll try fixing the patch.

**Comment by anniesullie** [comment]
@skyostil -- I see tracing.ui.timeline_viewport_test.locationObj failing on chrome 48, did this get relanded?

**Comment by philippebeaudoin** [comment]
@skyostil should probably own this one.

**Comment by skyostil** [comment]
@anniesullie -- No, I did not do anything here yet.

**Comment by natduca** [comment]
Do we have failures still? Lets open a fresh bug if we have known failures... I believe this specific issue to be fixed due to a revert, but I forgot to close it. So, lets close this, I'll file one for the reland, and maybe if we have known failures, we can crack open a new bug.

**Comment by anniesullie** [comment]
#1745 describes the current failures on canary. (I haven't retested since it was filed, but don't know of any fixes--the revert was before the failures I saw)
