### ISSUE TITLE
Table doesn't have any way to unselect a row.

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1638]
Unless I'm missing it, I couldn't find an easy way to unselect a row in table. I would have expected
table.selectedTableRow = undefined;
to do this, but it raises an exception.

Once this is fixed, use the feature in startupReport, which is currently slightly broken when trying to "sync" the selected row when no matching row exists in the other table.

**Comment by natduca** [comment]
I like the idea of setting it to undefined clearing the selection.

**Comment by natduca** [comment]
@petrcermak may have advice and/or reviewing bandwidth on a patch that fixes this
