### ISSUE TITLE
Support for Node.js throughout the tracing & pi & RAIL codebase

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1640]
I'm not sure if this is already possible, but it would be great have this support or know how to use it. As a use case we would like to be able to process traces inside https://github.com/GoogleChrome/erlnmyr

For now, this is my workaround. It's mainly dealing with `tr` being defined in the global scope and the math library assuming that `gl-matrix` is loaded into the global scope:

1. Create `entry.html` in `catapult/`
```
<!DOCTYPE html>
<script>
var glmatrix = require('./tracing/third_party/gl-matrix/dist/gl-matrix.js');
global.vec2 = glmatrix.vec2;
global.vec3 = glmatrix.vec3;
global.vec4 = glmatrix.vec4;
global.mat2d = glmatrix.mat2d;
global.mat4 = glmatrix.mat4;
// (function() {
this.isVinn = true;
</script>
<link rel="import" href="/tracing/base/base.html">
<link rel="import" href="/tracing/extras/lean_config.html">
<link rel="import" href="/tracing/importer/import.html">
<script>
// }).call(global);
module.exports = global.tr;
</script>
```
2. `npm install -g vulcanize && npm install -g cripser`
3. Execute `vulcanize --redirect "/tracing|tracing/tracing" --redirect "/gl-matrix-min.js|tracing/third_party/gl-matrix/dist/gl-matrix-min.js" entry.html |  crisper -h build.html -j build.js`
4. Edit `build.js` and uncomment the two lines from above.
5. Now you can execute something like this under node:

```
var tr = require('./build.js')
var m = new tr.Model()
var i = new tr.importer.Import(m)
var f = fs.readFileSync('trace.json', {encoding: 'utf8'})
i.importTraces([f])
```

I don't understand the API yet, but the trace seems to be in `i.model_`

**Comment by dstockwell** [comment]
@shans

**Comment by natduca** [comment]
Its definitely our goal to allow the whole darn system to work inside nodejs. Haven't worked through the various details yet, but I'm open to figuring out how to make this work long haul...

**Comment by bolinfest** [comment]
It would be great if @dstockwell's script could be included as part of catapult and maintained by the team. As someone new to [HTML imports](http://www.html5rocks.com/en/tutorials/webcomponents/imports/) and [vulcanize](https://www.npmjs.com/package/vulcanize), putting JavaScript business logic in `.html` files and using `<link>` instead of `require()` seems a bit backwards to me. As much as I love Chrome, I don't want to have to launch it in order to munge some JSON :)

**Comment by bolinfest** [comment]
@dstockwell Did you hit any issues with `'use strict'` violations? I just tried to build the JS for `Model` following your suggestion:

```
vulcanize \
  --redirect "/tracing|tracing/tracing" tracing/tracing/model/model.html \
  --redirect "/gl-matrix-min.js|tracing/third_party/gl-matrix/dist/gl-matrix-min.js" \
  | crisper -h /tmp/build.html -j /tmp/build.js
```

And then using Node v0.12.0, I tried running:

```
node -e 'require("/tmp/build.js")'
```

which failed with:

```
/private/tmp/build.js:352
    function HeadlessEvent(type, opt_bubbles, opt_preventable) {
    ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

This is at commit 01ad120 of the repo.

**Comment by bolinfest** [comment]
It seems like, for use in Node, it would be ideal to assume `tr.isHeadless` is `true` and to propagate that through `build.js` and then eliminate the dead code.

**Comment by natduca** [comment]
Mmm I'm very supportive of making this work ToT automagically. We need to make this all work together. @paullewis had done some prototyping work for this too. I'm going to slightly retitle this bug, and mark it M49

**Comment by bolinfest** [comment]
Can anyone explain why this code works in Chrome? AFAICT, the declarations of `HeadlessEvent` and `TrEvent` in `event.html` [should be considered strict mode violations](http://whereswalden.com/2011/01/24/new-es5-strict-mode-requirement-function-statements-not-at-top-level-of-a-program-or-function-are-prohibited/), no? Is `'use strict'` not properly enforced when used inside an HTML import?

**Comment by natduca** [comment]
At long last I'm making progress on this. I expect to have most of the basics here working in a few days, though map_traces support may take a bit longer.

**Comment by natduca** [comment]
I believe this to be mostly done. I will make a Node label for followon issues.
