### ISSUE TITLE
Show milestones branch points on the dashboard.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1648]
Fetch and store the mapping of commit positions to Chrome milestone branch points, and surface it on the front-end, possibly by drawing vertical lines where the branch points are.

This was originally a feature suggestion from Jared Duke.

**Comment by benhenry** [comment]
I would really really love to have this.

**Comment by anniesullie** [comment]
@jessimb @eakuefner @simonhatch @benshayden 

I think in the long-term, we're planning to write a new charting UI on top of trace-viewer. Should we consider adding small features like this in the flot version in the short term?

**Comment by eakuefner** [comment]
I'm not sure about the timeframe for being able to use tracing-based charts on the dashboard, but we're also looking at adding annotations for diagnostic changes as part of histogram pipeline MVP. If we can't afford to block either use case on the new charts, then I think that implies that we do have to invest in doing this on top of Flot.

**Comment by benshayden** [comment]
Archiving. V2SPA hard-codes branch points in the frontend for reports. I'll make a note to add marks to charts.
