### ISSUE TITLE
Make perf dashboard chart titles and legend item strings smarter

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1664]
Example chart I just sent out:
https://chromeperf.appspot.com/report?sid=b0cda36dd8fefe1680dd67e61d67b7ff850dfeab7cdea95f93a74c04f5769bdf&rev=355302

Ideally, this would have the chart titles be "startup.large_profile.cold.blank_page" and "startup.cold.blank_page", and in the legend I could select "chromium-rel-mac-hdd", "chromium-rel-mac-retina", etc.

I know it's hard to figure out good legend and chart names when the user could potentially put any combination of charts together, but i think we could use some simple heuristics, at least for common cases:
1. If all the series on a single chart are the same test suite, show the test suite name and help as the title of the chart.
2. For the legend, try to show what is different about each item. For example, if a person selected the same test on 3 bots, show the bot name in the legend. If the person selected 3 test suites on the same bot, show the test suite in the legend.

@chrisphn @qyearsley @dave-2

**Comment by qyearsley** [comment]
Aye, more sophisticated behavior here would be nice :-)

Chart title is determined by [elements/chart-title.html](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-title.html), and [elements/chart-legend.py](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-legend.html#L239) of course determines what is shown in the legend.

**Comment by qyearsley** [comment]
This issue was brought up today in http://crbug.com/579795. UI improvements aren't really in our planned OKRs now, but we should revisit this later and if anyone has time to make improvements that would be good.

**Comment by benshayden** [comment]
Archiving. V2SPA redesigns the title and legend.
