### ISSUE TITLE
In py_vulcanize, (optionally) don't check doctype & strict mode for "third-party" modules.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1665]
I think this is a required change for #1312 (using py_vulcanize with perf dashboard).

Perf dashboard depends on a bunch of Polymer elements, some of which don't use `<!DOCTYPE html>` or `'use strict';`. py_vulcanize halts processing when it finds a HTML module missing a doctype declaration or a script tag without a use strict directive. In order for dashboard to use py_vulcanize, it will have to tell py_vulcanize to ignore these checks for some modules.

Maybe this could be done by checking if "third_party" is in the module directory name somewhere, and turning off the checks.

@natduca

**Comment by natduca** [comment]
What label should this bug have? ^_^

I would be okay moving some of these checks to a presubmit. The key thing is architecting this cleanly. A key dance that is hard to get write is reliably parsing an html module.

**Comment by qyearsley** [comment]
It would seem to fit to put these checks in a presubmit. Without parsing  most naive simple check that could be added in the presubmit would be simple rules like:
 1. If the file ends in .html it must contain <!DOCTYPE html> as the first line.
 2. Everywhere <script> appears, there must be a 'use strict'; immediately following it.

I noticed though that there apparently was already a mechanism in place for skipping checking of the Polymer components -- just made a CL to make this work for Polymer components in third_party/polymer/components: https://codereview.chromium.org/1406083003/

**Comment by qyearsley** [comment]
Adding presubmit checks; see #1700.
