### ISSUE TITLE
MemoryInfra: Tracing discounting should not be discounted from PSS if not provided

### ISSUE THREAD

**Issue by ssiddhartha** [catapult-project/catapult#1667]
Context: memory-infra in Trace Viewer.

Malloc will not be dumped when mallinfo fails (the int value sizes overflows). But, the tracing overhead is still discounted from malloc which makes the value negative. This should ideally display 0.

**Comment by ssiddhartha** [comment]
![malloc_fix](https://cloud.githubusercontent.com/assets/15266982/10698589/b45dbf9c-79a9-11e5-9b49-f629e4f97d19.png)

**Comment by petrcermak** [comment]
The issue is actually _not_ malloc, which should be dumped every time, but **PSS**, which is **not provided on Mac**.

**Comment by petrcermak** [comment]
This is now **fixed** on the Trace Viewer side.
