### ISSUE TITLE
Perf Dashboard: There are no tests run for Peppy in the CrOS lab

### ISSUE THREAD

**Issue by selavazhagan** [catapult-project/catapult#1670]
Chrome version: 46.0.2490.80 (Linux)
URL: https://chromeperf.appspot.com/report?sid=e937ec2120344154a4995db51d0f00da053abe023e1afad770139aaa7739af29

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
There are no errors as such seen in JS Console

Please describe the problem:
The graphs related to Peppy is not showing the updated results, instead i do see the message 'Graph out of date! Last date received 2015-10-16T10:08:43.000Z'

**Comment by anniesullie** [comment]
This isn't a perf dashboard issue, it's an issue with the bots in the lab not sending the data. Maybe the test is failing or the connection is bad? Please file a bug in the appropriate bug tracker for Chrome OS issues.

**Comment by selavazhagan** [comment]
Thank you.  Have filed the bug in the Chromium 547839
<https://code.google.com/p/chromium/issues/detail?id=547839>.

Regards,
Shankari.
