### ISSUE TITLE
No logged in status on /group_report

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1671]
I notice there is no longer a navbar on /group_report, which means that logged in status is unavailable. This is super confusing for users because sometimes you click on a bug and can't see the data because you're not logged in.

Assigning to @qyearsley because I think it's fallout from https://codereview.chromium.org/1414463007/

**Comment by qyearsley** [comment]
Aye, that's right, it was fallout from that CL (I thought I tried it out before committing, but I missed group_report). Fix: https://codereview.chromium.org/1409333008/

**Comment by qyearsley** [comment]
New version now deployed.
Example page: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAgfTttQoM
