### ISSUE TITLE
Make instantiation tests for perf dashboard.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1674]
In the tracing project unit tests, there are many tests named "instantiate_*" which create an instance of a custom element and call addHTMLOutput in the body of the test method. It will be useful to do this for dashboard too.

@chrisphn

**Comment by qyearsley** [comment]
This was an OKR in 2015 Q4.

I I think it should be considered "done" when the instantiation tests for alerts-table and test-picker are committed, but in the last two patches that Chris tried above we hit some issues.

Next step: Try Chris's patch again and diagnose the issues that we came across.

**Comment by anniesullie** [comment]
Would be interesting to know if the same command line to run the tests that the bots use runs locally for Chris. It seems to be a timeout waiting for the browser to respond; would be great to figure out why that happens.

**Comment by anniesullie** [comment]
There are basic instantiation tests now.
