### ISSUE TITLE
On /alerts, if invalid sheriff is given, show an error message.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1678]
Currently, if an invalid sheriff is given for the /alerts page sheriff query parameter, e.g. https://chromeperf.appspot.com/alerts?sheriff=Foo,  the dashboard shows an "All alerts triaged" message, but it would be more helpful to show a "Sheriff Foo not found" message.

**Comment by eakuefner** [comment]
Looks like this has been fixed.
