### ISSUE TITLE
Tracing broken on all E-series Intel CPUs

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1680]
Looking at bulk reports it seems like tracing is broken on all E-series Intel CPUs (at least under Windows). The issue seems to be that timers are snapped to the nearest millisecond (ie. "ts" always ends in 000 as in "ts":56241445000) This creates a gazillion 0ns long events all lined up on the same timestamp, which then get turned into super deep stack hierarchies by trace viewer. Even without that parenting problem, though, the traces are basically unusable because too coarse. Not sure what to propose here, beside filtering out all such traces from any Perf Insights reports.

Pinging @natduca @fmeawad and @simonhatch who helped me diagnose this.

Attached is an image from a trace where you clearly see the events lining up on an ms boundary.

![image](https://cloud.githubusercontent.com/assets/11399419/10794847/467c497c-7d6d-11e5-925f-94457d5388a3.png)

**Comment by natduca** [comment]
@zeptonaut

**Comment by philippebeaudoin** [comment]
Did a slightly more thorough analysis. It looks like E-series intel are unaffected (E6600, E4500, E6550) and some AMD are (AMD A4-5000, AMD Athlon 5600+, AMD Sempron, AMD A4-5000, AMD E1-2100, AMD A6-3410MX) This is far from an exhaustive list. The problem seems to appear on a various Chrome versions (47, 48). I've only observed Windows oses for now. Full data below. 

*Here's some metadata for traces where all timers are snapped to the nearest MS:*

DisplayName =  00f33c57aeabd423.gz  cpu-brand = Intel(R) Pentium(R) Dual  CPU  E2140  @ 1.60GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00f2d3359c288e9f.gz  cpu-brand = AMD Sempron(tm) 145 Processor  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00dd5040b3703cde.gz  cpu-brand = Intel(R) Core(TM)2 CPU          6420  @ 2.13GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 1
DisplayName =  00235a9bc0dc1a91.gz  cpu-brand = AMD E1-2100 APU with Radeon(TM) HD Graphics      os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 1
DisplayName =  00f33c57aeabde2a.gz  cpu-brand = Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00f33c57aeabdf1b.gz  cpu-brand = AMD Athlon(tm) 64 X2 Dual Core Processor 5600+  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00f33c57aeabd423.gz  cpu-brand = Intel(R) Pentium(R) Dual  CPU  E2140  @ 1.60GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00dd5040b3703cde.gz  cpu-brand = Intel(R) Core(TM)2 CPU          6420  @ 2.13GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 1
DisplayName =  02f0cc8ca18468c5.gz  cpu-brand = Pentium(R) Dual-Core  CPU      E5200  @ 2.50GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00f2d3359c288e9f.gz  cpu-brand = AMD Sempron(tm) 145 Processor  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  03104d560e014031.gz  cpu-brand = Intel(R) Pentium(R) Dual  CPU  T2310  @ 1.46GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  02a3f79a00ff3496.gz  cpu-brand = Intel(R) Pentium(R) Dual  CPU  E2160  @ 1.80GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 1
DisplayName =  00f33c57aeabdcde.gz  cpu-brand = Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  033136422a5e11b8.gz  cpu-brand = AMD Sempron(tm) Processor 2800+  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  01273a80439b81bf.gz  cpu-brand = Intel(R) Celeron(R) CPU          530  @ 1.73GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  02836e6c40ee3f7f.gz  cpu-brand = AMD A4-5000 APU with Radeon(TM) HD Graphics      os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00235a9bc0dc1a91.gz  cpu-brand = AMD E1-2100 APU with Radeon(TM) HD Graphics      os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 1
DisplayName =  0340cb67fb653ca4.gz  cpu-brand = Pentium(R) Dual-Core CPU       T4300  @ 2.10GHz  os-name = Windows NT  product-version = Chrome/48.0.2530.0  snapped % = 1
DisplayName =  02a3f79a00ff3856.gz  cpu-brand = Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 1
DisplayName =  05b315c12d745d07.gz  cpu-brand = Intel(R) Pentium(R) Dual  CPU  E2180  @ 2.00GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  00dd5040b3703b89.gz  cpu-brand = Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.9996505787289801
DisplayName =  00dd5040b3703b89.gz  cpu-brand = Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.9996505787289801
DisplayName =  02a3f79a00ff358d.gz  cpu-brand = AMD A6-3410MX APU with Radeon(tm) HD Graphics  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 1
DisplayName =  02f0cc8ca1846727.gz  cpu-brand = Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  0553168c9aeccf4d.gz  cpu-brand = AMD Sempron(tm) 145 Processor  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 1
DisplayName =  05242867b5fa73e1.gz  cpu-brand = AMD Phenom(tm) II X2 565 Processor  os-name = Windows NT  product-version = Chrome/48.0.2533.0  snapped % = 1

*Here's some metadata for traces where timers are NOT snapped to the nearest MS:*

DisplayName =  000c6ee67ca1cdec.gz  cpu-brand = Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0
DisplayName =  00dd5040b370312f.gz  cpu-brand =         Intel(R) Celeron(R) CPU 1007U @ 1.50GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0.0007594936708860759
DisplayName =  00dd5040b37033c5.gz  cpu-brand =       Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.001377110966152062
DisplayName =  00f33c57aeabd216.gz  cpu-brand =         Intel(R) Pentium(R) CPU G2010 @ 2.80GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 0.0006469700237222342
DisplayName =  00dd5040b3703230.gz  cpu-brand = Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2541.0  snapped % = 0.0011670959433354798
DisplayName =  00f33c57aeabd216.gz  cpu-brand =         Intel(R) Pentium(R) CPU G2010 @ 2.80GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 0.0006469700237222342
DisplayName =  00f33c57aeabdc6d.gz  cpu-brand =         Intel(R) Celeron(R) CPU G1620 @ 2.70GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 0.0008625837701546015
DisplayName =  00dd5040b370312f.gz  cpu-brand =         Intel(R) Celeron(R) CPU 1007U @ 1.50GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0.0007594936708860759
DisplayName =  02a3f79a00ff30c4.gz  cpu-brand =         Intel(R) Pentium(R) CPU G2010 @ 2.80GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0009865060071169362[       OK ] 02a3f79a00ff3496.gz (3801 ms)
DisplayName =  00dd5040b37033c5.gz  cpu-brand =       Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.001377110966152062
DisplayName =  02448f4c0b526d41.gz  cpu-brand = Celeron(R) Dual-Core CPU       T3500  @ 2.10GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0
DisplayName =  02a3f79a00ff3b32.gz  cpu-brand =       Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0008660195576083426
DisplayName =  03104d560e0145b2.gz  cpu-brand = Pentium(R) Dual-Core  CPU      E6600  @ 3.06GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0
DisplayName =  03104d560e014f54.gz  cpu-brand = Intel(R) Core(TM)2 Duo CPU     E4500  @ 2.20GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0.001296792599636898
DisplayName =  000c6ee67ca1cdec.gz  cpu-brand = Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0
DisplayName =  00dd5040b3703230.gz  cpu-brand = Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2541.0  snapped % = 0.0011670959433354798
DisplayName =  0322ba8196a688f2.gz  cpu-brand =          Intel(R) Pentium(R) CPU G620 @ 2.60GHz  os-name = Windows NT  product-version = Chrome/48.0.2541.0  snapped % = 0.0008815162078775494
DisplayName =  00f33c57aeabda44.gz  cpu-brand =         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 0.001288825879623663
DisplayName =  03104d560e0144cf.gz  cpu-brand = Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0
DisplayName =  04de45a31c1fc73b.gz  cpu-brand =        Intel(R) Core(TM) i3-2367M CPU @ 1.40GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0008658008658008658
DisplayName =  033136422a5e1d18.gz  cpu-brand = Intel(R) Core(TM) i3 CPU         530  @ 2.93GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 0.0009892347977887694
DisplayName =  03104d560e01488b.gz  cpu-brand =         Intel(R) Pentium(R) CPU G2030 @ 3.00GHz  os-name = Windows NT  product-version = Chrome/48.0.2542.0  snapped % = 0.0011452735441811294
DisplayName =  05c6b80c864dc2ee.gz  cpu-brand = Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0010517617008489219
DisplayName =  0553168c9aeccdf0.gz  cpu-brand =         Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz  os-name = Windows NT  product-version = Chrome/47.0.2526.8  snapped % = 0.0009488952148569879
DisplayName =  05e32f27688e851a.gz  cpu-brand = Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0012892738025168868
DisplayName =  05bcd419afd5e4cb.gz  cpu-brand =        Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0.001060511540860886
DisplayName =  05c6b80c864dca0a.gz  cpu-brand = Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0010690287110568112
DisplayName =  0356f0dc14657d97.gz  cpu-brand =        Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz  os-name = Windows NT  product-version = Chrome/48.0.2530.0  snapped % = 0.001006507989157164
DisplayName =  03104d560e0142b8.gz  cpu-brand =        Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz  os-name = Windows NT  product-version = Chrome/48.0.2540.0  snapped % = 0.0010501081196846913
DisplayName =  02a3f79a00ff3097.gz  cpu-brand =        Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz  os-name = Windows NT  product-version = Chrome/48.0.2537.3  snapped % = 0.001393121462777536
DisplayName =  0322ba8196a6814c.gz  cpu-brand =         Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0012908564335953662
DisplayName =  05c6b80c864dcc7f.gz  cpu-brand = Intel(R) Pentium(R) CPU        P6200  @ 2.13GHz  os-name = Windows NT  product-version = Chrome/48.0.2535.0  snapped % = 0.0008674420098952644

**Comment by randomascii** [comment]
The one ms granularity must mean that these CPUs do not have a constant-rate TSC so we are falling back to using timeGetTime. We'll either have to discard these results as being useless, or not collect them in the first place if we don't have a constant-rate TSC, or else use QueryPerformanceCounter instead.

I haven't actually checked the timer code but logically that must be what is happening. Note that in some cases the timer granularity will be even worse - timeGetTime only gives one ms granularity if the timer frequency has been raised.

**Comment by zeptonaut** [comment]
To add to @randomascii's comment, [this mailing list post](http://www.gossamer-threads.com/lists/xen/devel/185419) seems to suggest that the constant TSC is only available on Intel Nehalem edition processors and later. The E5000 came before the Nehalem, so there's not much we can do besides ignore those traces.

**Comment by zeptonaut** [comment]
It also might be worth noting: there's a whole host of processors for which this is true. It's probably worth coming up with some common way to identify and ignore traces (for the purposes of bulk processing) with low-resolution timestamps. Maintaining a whitelist of these processors is likely going to be really difficult.

**Comment by randomascii** [comment]
It is easy to detect whether a processor has a constant-rate TSC. It sounds like the ideal situation would be to not enable tracing in the first place on machines without a constant-rate TSC. There's no good reason to record traces (slowing down users' machines) that we are just going to ignore.

**Comment by philippebeaudoin** [comment]
They are easy enough to detect just by looking at the events timing...  That's what I did to get the list above. It looks quite robust too. The question is: is it worth filtering upstream or we're OK having the mappers filter out the broken ones?

**Comment by vinterstum** [comment]
Filed https://crbug.com/548756 to disable background tracing on CPUs without a constant-rate TSC, if we're all agreed that those traces aren't useful. Or possibly add a flag for the slow reports scenario to check for it, in case there's scenarios where we want reports from the older CPUs too (what's the situation on non-desktop?)

**Comment by philippebeaudoin** [comment]
I think it's safe dropping them entirely. (ie. I support this bug.)

**Comment by philippebeaudoin** [comment]
Closing. This has turned into #1698 and #1694.
