### ISSUE TITLE
Possible adjustment: "No data available" warning could include which series is missing data.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1681]
On [this graph](https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAxYDd-QgM) I'm seeing multiple "No data available" warnings for different series:
![screenshot from 2015-10-28 14 27 51](https://cloud.githubusercontent.com/assets/3926653/10803571/16c7af4c-7d80-11e5-99be-7518a850392a.png)

It would have been more helpful if the warning said which series had no data. Changing this would probably involve a change in: [chart-container.html](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-container.html#L718)

**Comment by qyearsley** [comment]
We bumped into this again recently: https://code.google.com/p/chromium/issues/detail?id=557348#c13

**Comment by benshayden** [comment]
Archiving.
