### ISSUE TITLE
Possible change to grouping logic: Don't change alert groups upon bug ID change

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1683]
Usually on the dashboard, one alert group will contain alerts for a particular test suite/benchmark, but when alerts are triaged and associated with an existing bug, alerts get moved into the alert group associated with the bug.

There's an assumption (on [this line](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/alert.py#L139) that for each bug ID there's only one alert group; this makes the idea of an alert group somewhat flexible so that one alert group can contain alerts from different rev ranges and test suites if the alerts ever get associated with one bug ID.
 
Proposed change:
When changing an alert's bug ID, don't update the group; this will make it so that one bug ID may contain several alert groups, and one alert group will basically just mean "all alerts for a particular test suite in a revision range".

The code that would be changed is in [models/alert.py](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/alert.py#L80).

@anniesullie @chrisphn WDYT?

**Comment by chrisphn** [comment]
Ok with me.  Originally, I thought grouping could be also for manual grouping, but then that's like associating an alert with a bug.

In this case for example, /group_report?bug_id=x can show multiple groups?

**Comment by qyearsley** [comment]
Right, I /group_report?bug_id=x could show multiple groups.

In theory we're using the group bug IDs now to auto-triage alerts, so we still want groups to have a bug_id. This may make the logic for determining what bug ID to assign to auto-triaged alerts more complicated.

One possible solution for this would be to make AlertGroup.bug_id a computed property, which is obtained by getting the most common bug ID for alerts associated with that group; does that sound OK?

**Comment by qyearsley** [comment]
Before marking this fixed, I should verify that the behavior works as expected, maybe I should do another 1-day per-page sheriff rotation shift.

**Comment by qyearsley** [comment]
https://codereview.chromium.org/1556573002 has been committed and deployed, but the fix hasn't been verified. Next step here is to check whether this is still an issue.
