### ISSUE TITLE
Perf Dashboard: some tests are listed as deprecated even when they have some non-deprecated subtests.

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1688]
Chrome version: 48.0.2541.0 (Linux)
URL: https://chromeperf.appspot.com/report?sid=7283ff061c1d1b25a427787be97349a88352b054961ab7c2bca6f543da9d3e1e

Subtests all say "deprecated" but there's no context about exactly what is deprecated.

**Comment by dstockwell** [comment]
![screenshot 2015-10-29 at 15 59 15](https://cloud.githubusercontent.com/assets/539597/10810536/0c8be47c-7e56-11e5-85ce-fb7cf757c993.png)

**Comment by qyearsley** [comment]
"Deprecated" actually means "no data received for at least 2 weeks for this test".
Does https://github.com/catapult-project/catapult/issues/1690 seem like a fair solution for this?

**Comment by dstockwell** [comment]
That seems reasonable, but there must be another issue since there is new data.

**Comment by qyearsley** [comment]
Ah, that's true. When blink_style.top_25 and android-nexus6 are selected in the test picker, when the front end makes a request to `/list_tests` to get the list of sub-tests, the response says that all of the subtests are deprecated, but directly fetching the Test entity from datastore and checking it shows that 


The last CL to change list_tests.py an

@chrisphn

**Comment by chrisphn** [comment]
Going to clear the subdict data cache.

**Comment by qyearsley** [comment]
I'm still seeing this problem now; maybe the cached data wasn't fully cleared or there is still a bug in list_tests?

**Comment by chrisphn** [comment]
The fix wasn't deployed, just cleared the cache again.  Should work now.

**Comment by qyearsley** [comment]
Awesome, fixed now :-)
