### ISSUE TITLE
Perf Dashboard: No visible button state changes when clicking "show triaged" or "show improvements" buttons

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1689]
Chrome version: 48.0.2547.0 (Windows)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down&improvements=true

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
None seen

Please describe the problem:
1) Click either the "Show Triaged" or "Show Improvements" buttons

Expected result:
I'm pretty sure that in the past, the button color would change on click to indicate that you were now viewing (alerts+triaged) or (alerts+improvements). 

Actual result:
No button change visible, so I can only tell if I'm in the "view triaged" or "view improvements" state by either reading the page content, or looking at the URL (e.g. "...&improvements=true")

**Comment by qyearsley** [comment]
That's right -- in the past it used to change color. @fmeawad suggested changing the button text to say "hide triaged" or "hide improvements" (#1577), which also seems like a fair solution.
