### ISSUE TITLE
/deep/ and ::shadow are being removed

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1691]
Chrome version: 48.0.2547.0 (Windows)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

Please describe the problem:
1) Open the dashboard URL mentioned above
2) Open Chrome's js console
3) See deprecation warnings

**Comment by qyearsley** [comment]
This is because we're using Polymer 0.5, and some of the Polymer elements use this.

Nothing can be easily done about this until we upgrade Polymer (#3).

**Comment by ChrisCraik** [comment]
Still getting warning about /deep/ on tip of tree master, and #3 has been closed.

**Comment by benshayden** [comment]
These files use /deep/:
```

tracing/tracing/ui/base/chart_base_2d.html
tracing/tracing/ui/base/chart_base.html
tracing/tracing/ui/base/dom_helpers.html
tracing/tracing/ui/base/line_chart.css
tracing/tracing/ui/base/list_and_associated_view.css
tracing/tracing/ui/base/list_view.css
tracing/tracing/ui/base/pie_chart.css
tracing/tracing/ui/base/quad_stack_view.html
tracing/tracing/ui/base/tool_button.css
tracing/tracing/ui/extras/chrome/cc/display_item_debugger.html
tracing/tracing/ui/extras/chrome/cc/display_item_list_view.css
tracing/tracing/ui/extras/chrome/cc/layer_picker.css
tracing/tracing/ui/extras/chrome/cc/layer_tree_host_impl_view.css
tracing/tracing/ui/extras/chrome/cc/layer_tree_quad_stack_view.html
tracing/tracing/ui/extras/chrome/cc/layer_view.css
tracing/tracing/ui/extras/chrome/cc/picture_debugger.html
tracing/tracing/ui/extras/chrome/cc/picture_ops_chart_summary_view.css
tracing/tracing/ui/extras/chrome/cc/picture_ops_chart_view.css
tracing/tracing/ui/extras/chrome/cc/picture_ops_list_view.css
tracing/tracing/ui/extras/chrome/cc/picture_view.css
```

**Comment by benshayden** [comment]
The charts should grow up into real polymer elements and style their shadow roots like everything else. I don't know what any of those other files are doing.

**Comment by benshayden** [comment]
These CSS features are being removed in M63, which branches on Oct 12, putting a hard deadline on fixing this. [765447](https://bugs.chromium.org/p/chromium/issues/detail?id=765447)

**Comment by benshayden** [comment]
Relatedly, I just noticed this warning:

[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

**Comment by benshayden** [comment]
Fixed, assuming the change sticks.
