### ISSUE TITLE
In chart-legend, if there are no "important" tests, show all tests.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1692]
For some charts (for data from other sources besides chromium.perf), there are sometimes now "chart-level" series and no monitored series. For example: https://chromeperf.appspot.com/report?sid=5e92cae75a4c780606caed0cacf39ae15877e165011f7a2e42153c7393d268bf

When there are no "important" series, it may be best to show all the series.

**Comment by qyearsley** [comment]
@chrisphn

There are several possible changes which might help here.

One would be to not "collapse" series groups in the legend if collapsing would result in nothing being displayed. I think this would involve changes in chart-container.

Another separate possible change would be to change addTestPathFromSubtestDict in test-picker so that when a test is added from the test picker, the "selected" list is always non-empty.

**Comment by ppiet** [comment]
As a temporary workaround, how do we mark our series as "important"?

**Comment by qyearsley** [comment]
"Important" means "either monitored (i.e. there's a sheriff rotation that would receive alerts for regressions on that series) or the test path has four parts ("Master/bot/benchmark/metric)".

Would it be OK to set up a "sheriff" that receives alerts for regressions in some series? See http://crbug.com/552444

**Comment by benshayden** [comment]
Archiving. V2SPA redesigns the legend.
