### ISSUE TITLE
Add Model.isTimeHighResolution to Model and teach TraceEventImporter to import it

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1694]
https://code.google.com/p/chromium/issues/detail?id=549306 adds a metadata record for whether time is high resolution.

We should ad a isTimeHighResolution field to the model, and then grab it from the trace metadata.

**Comment by natduca** [comment]
@lpy @philippebeaudoin @fmeawad @vinterstum

**Comment by natduca** [comment]
https://codereview.chromium.org/1427063002/ will give us the right stuff in trace data. Now we just need to do the importer etc

**Comment by philippebeaudoin** [comment]
See also: https://codereview.chromium.org/1430833005/ which adds it to the metadata dict and  makes it possible to detect (reject?) these as they're uploaded.

**Comment by wangzhen127** [comment]
@wangzhen127 @zeptonaut @nedn
