### ISSUE TITLE
PerfInsights should not process traces whose Model.isTimeHighResolution=false

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1698]
They're just too bad to deal with. I'd be open to a --allow-lowres-traces if we wanted, but tbh its fine to just drop them always.

@philippebeaudoin can drive. May be blocked on https://github.com/catapult-project/catapult/issues/1694

**Comment by natduca** [comment]
I forget, do we have a bug (or really just work planned still) that puts up an info bar when you load a lowres time trace? I imagine using the existing info-bar-group on timeline_view.html and a little bit of code in the model setter would be sufficient...

**Comment by philippebeaudoin** [comment]
I dont remember adding a bug for that, let me do it. I'll do this before EOW.
