### ISSUE TITLE
trace-viewer embedding example doesn't work

### ISSUE THREAD

**Issue by johnmccutchan** [catapult-project/catapult#1699]
Hi,

I'm trying to embed trace-viewer into my application and have followed the directions on the wiki.

$ pwd
~/workspace/catapult/tracing
$ ./bin/vulcanize_trace_viewer
$ python -m SimpleHTTPServer

Browse to localhost:8000/bin

Console error about "m" being undefined.

Edit bin/index.html and replace "model" with "var m"

Reload localhost:8000/bin

I see an empty trace.

The code snippets in the wiki also seem out of date.

Is there a working example of embedding trace-viewer I can look at?

**Comment by natduca** [comment]
Sorry about that, fixes incoming. Will peek at wiki now.

**Comment by natduca** [comment]
Wiki updated.
