### ISSUE TITLE
Move doctype/strict mode checks from py_vulcanizer to presubmit.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1700]
In [py_vulcanizer.html_module.Parse](https://github.com/catapult-project/catapult/blob/master/third_party/py_vulcanize/py_vulcanize/html_module.py#L162), HTML files that are not third-party Polymer components are checked to verify that they have `<!doctype html>`, and `<script>` elements are checked for `'use strict';`.

This check would probably be more suitable to be done as a presubmit check; once this is checked in the catapult presubmit then it can be removed from py_vulcanizer.html_module.Parse.

**Comment by natduca** [comment]
This is happening way too often and is causing damage. We need to make this happen in the next ~3wks. @qyearsley does that fit in your timeframe or should we seek alternative owner?

**Comment by qyearsley** [comment]
I believe it should fit in my time-frame; will update by next week.

**Comment by natduca** [comment]
Thanks!
