### ISSUE TITLE
Implement a cron job for regularly clearing very old data.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1701]
"Datastore stored data" now makes up a large part of the costs of the perf dashboard. The cost is:
~27,417.72 GB @ $0.006 / GB-day = $164.50 per day

Most of the stored data is for "deprecated" tests, including many tests that haven't received data in over a year.

If tests that haven't received data in over a year were removed, I estimate that this might reduce the cost by at least $60/day ($20,000/year) and would also make operations like the deprecate_tests_mapper faster.

Proposal: Add a handler which: 
 * Makes a paged query for Test entities with deprecated = True, and adds tasks to a task queue to look at each of them individually and to continue to query the tests, since this may take too long for one request.
 * Looks at individual deprecated tests and checks how old the newest data point is; if it's older than some cut-off, add tasks to delete rows.
 * If the test is deprecated and there are no rows, delete it. If the bot/master above it doesn't have any more tests, delete those too.

@anniesullie I think we thought about this before and decided it wasn't worth it then, and we don't plan to do this in the next milestone, but in general do you think it's worth it? (Do you think we'll continue to use the perf dashboard without starting from an empty datastore for at least the following year?)

**Comment by anniesullie** [comment]
Yeah, it does seem like it's worth it at this point.

**Comment by anniesullie** [comment]
I'm working on this in https://codereview.chromium.org/2056673003.

@eakuefner FYI

**Comment by anniesullie** [comment]
This is done.

**Comment by qyearsley** [comment]
Good work on this one, by the way!
