### ISSUE TITLE
Perf dashboard: bug not updated with bisect results.

### ISSUE THREAD

**Issue by ro-berto** [catapult-project/catapult#1702]
A couple of bisect jobs finished successfully on this bug: https://chromeperf.appspot.com/group_report?bug_id=546086 but the bug was never updated with the results.

Is there a problem with the cron job that is supposed to do this?

**Comment by ro-berto** [comment]
Also detected with: https://chromeperf.appspot.com/group_report?bug_id=546085

**Comment by ro-berto** [comment]
https://chromeperf.appspot.com/group_report?bug_id=542746

**Comment by chrisphn** [comment]
I've been looking into this.  Dup bug from crbug.com/546759

**Comment by qyearsley** [comment]
Another case: https://code.google.com/p/chromium/issues/detail?id=544141

**Comment by qyearsley** [comment]
I believe we're expecting that change to fix the issue; in all of those cases pasted above, it appears that the suspect culprit author line contained something like "X, X@chromium.org". Chris's CL above should fix the handling of this case.
