### ISSUE TITLE
Use MapperHandlers throughout

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1703]
That way mappers dont have to register

**Comment by natduca** [comment]
diff --git a/catapult_build/dev_server.py b/catapult_build/dev_server.py
index 9ed8317..7b27b6e 100644
--- a/catapult_build/dev_server.py
+++ b/catapult_build/dev_server.py
@@ -226,6 +226,14 @@ class DevServerApp(webapp2.WSGIApplication):
     for route in routes:
       self.router.add(route)

+  def IsValidRelPath(self, filename):
+    for p in self._all_source_paths:
+      join(p, filename) # be sure to not let '../../../etc/passwd' work
+      if exists
+        return True
+
+    if not then return False
+
   def GetURLForAbsFilename(self, filename):
     assert self.server is not None
     for mapped_path, source_path in self._all_mapped_test_data_paths:
diff --git a/perf_insights/perf_insights_build/perf_insights_dev_server_config.py b/perf_insights/perf_insights_build/perf_insights_dev_server_config.py
index 9ea1a1d..6e3b417 100644
--- a/perf_insights/perf_insights_build/perf_insights_dev_server_config.py
+++ b/perf_insights/perf_insights_build/perf_insights_dev_server_config.py
@@ -36,10 +36,14 @@ class TestListHandler(webapp2.RequestHandler):

 class RunMapFunctionHandler(webapp2.RequestHandler):
   def get(self, *args, **kwargs): # pylint: disable=unused-argument
-    map_function = kwargs.pop('map_function')
+    map_file = kwargs.pop('map_file')
+
+    if not self.app.IsValidRelPath(map_file):
+      self.abort(405)

     map_function_handle = map_function_handle_module.MapFunctionHandle(
-        map_function_name=map_function)
+        filename=map_file)
+

     corpus_driver = local_directory_corpus_driver.LocalDirectoryCorpusDriver(
         trace_directory = kwargs.pop('_pi_data_dir'),

**Comment by natduca** [comment]
calling @eakuefner

**Comment by natduca** [comment]
Some other files that may need hacking upon: perf_insights_viewer.html and possibly pi_app_main.html

**Comment by eakuefner** [comment]
1. Fix FunctionHandle
2. Add Validation
3. Pass FunctionHandle instead of name
3a. Fix xhr

**Comment by natduca** [comment]
Some context: the various map scenarios that we need to support are the following:
1. map_traces on a local mapper file, mapping locally
2. map_traces on a local mapper file, mapping on cloud
3. map_traces from the web, where the mapper is already on the server [eg devserver], mapping on the server
4. map_traces from the web, where the mapper is fetchable via the server, where mapping runs in browser for debugging
and
5. map_many_traces: variant of the above where we specify running N map jobs at once to optimize for the trace loading time

After looking through all these use cases, there are a lot of corner cases where you can have >1 mapper loaded in memory at once, and need to specifically identify them by name. Especially 5 and 4. So in these cases, we need to actually have MapHandles say both "what files to import" AND "what functions to use " --- meaning that in these cases, you really need an object that is both the filename and the function.

From this, we concluded that the right thing to do is centralize more of this `)@#*$` behind the MapHandle (soon to be called function handle, #1705) abstraction. The more we just pass around opaque function handles that are loadable and identifiable, the more agility we have for these use cases.

@simonhatch @nedn fyi

**Comment by nedn** [comment]
How would we tell MapHandles "what files to import"? I propose that we have a mappers_config.html files that contain a bunch of html imports, and give it to MapHandles instead of specifying a list of html files in python. 
It seems to me that these mappers_config.html is similar to what we have in tracing/tracing/ui/extras/..

**Comment by natduca** [comment]
I don't think that works. We eventually want a map engine separate from the mappers themselves. The "all files" thing is I think a bug, rather than a feature. Rather, when you make a FunctionHandle you instead ofsaying mapperName xor mapperFilename, you instead specify what files need to be imported and then what mapper names to load once those imports are done.

**Comment by eakuefner** [comment]
Based on the most recent CL, reducers can be built on top of the "new way" (list of modules to load + function name for entry point), but there are two hacks to get rid of still.

The first is `all_mappers.py`, which is important for the TBM 2.0 use case.

The second is the loadFromFilename hack that looks for exactly one mapper to have been registered and then assumes that that's the mapper we want to use. This one not as pressing, but it does preclude the use case where we have a file that registers more than one mapper, since this ambiguates the 1:1 relationship between files and mapper functions that loadFromFilename assumes.

**Comment by natduca** [comment]
Should we kick off a fresh bug to delete all_mappers.html?

**Comment by eakuefner** [comment]
Sure, and I'll also make a new one for introducing userFriendlyStrings. This bug can be closed since we're using `FunctionHandle` everywhere now, just not necessarily with the new codepath.
