### ISSUE TITLE
Frame viewer is broken

### ISSUE THREAD

**Issue by danakj** [catapult-project/catapult#1706]
1. Record a trace with Frame Viewer settings
2. Click on one of the LayerTreeHostImpl circles
3. Expect to see the compositor's output
4. But it's empty.

There's at least one bug in chromium related to this, I think. I see a js error about a Rect type not having four values.

The following patch resolves that error, then I don't see any console output of interest anymore. But the frame viewer is still empty. :( It's been broken for a few weeks at least.

|diff --git a/cc/playback/drawing_display_item.cc b/cc/playback/drawing_display_item.cc
|index a2740f9..cee9c1d 100644
|--- a/cc/playback/drawing_display_item.cc
|+++ b/cc/playback/drawing_display_item.cc
|@@ -8,6 +8,7 @@
| 
| #include "base/strings/stringprintf.h"
| #include "base/trace_event/trace_event_argument.h"
|+#include "base/values.h"
| #include "cc/debug/picture_debug_util.h"
| #include "cc/proto/display_item.pb.h"
| #include "third_party/skia/include/core/SkCanvas.h"
|@@ -92,11 +93,14 @@ void DrawingDisplayItem::AsValueInto(
|     base::trace_event::TracedValue* array) const {
|   array->BeginDictionary();
|   array->SetString("name", "DrawingDisplayItem");
|-  array->SetString(
|-      "cullRect",
|-      base::StringPrintf("[%f,%f,%f,%f]", picture_->cullRect().x(),
|-                         picture_->cullRect().y(), picture_->cullRect().width(),
|-                         picture_->cullRect().height()));
|+
|+  array->BeginArray("cullRect");
|+  array->AppendInteger(picture_->cullRect().x());
|+  array->AppendInteger(picture_->cullRect().y());
|+  array->AppendInteger(picture_->cullRect().width());
|+  array->AppendInteger(picture_->cullRect().height());
|+  array->EndArray();
|+

**Comment by danakj** [comment]
FWIW I do get this error too I guess:

Uncaught Error: Multiple hotkey controllers attached to this host(anonymous function) @ tracing.js:4471
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by natduca** [comment]
@vmpstr can you investigate? I'm pretty swamped

**Comment by sidrees** [comment]
I am not seeing the pictures for the layers as well. I am using following Chrome version:
Chromium	47.0.2526.16 (Developer Build) (64-bit)
Revision	866d98134590c1389ce9cc348e7a08501883f472
OS	Linux 
Blink	537.36 (@a6d719a27caff8e732e8fc94b13f826ebc77cdbe)
JavaScript	V8 4.7.80.9
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.16 Safari/537.36
Command Line	./out/Debug/chrome --no-sandbox --enable-skia-benchmarking --flag-switches-begin --flag-switches-end

And i select cc and cc:debug from chrome://tracing and gets the following message:
Missing picture
Your trace didnt have pictures for every layer. Old chrome versions had this problem.
