### ISSUE TITLE
tr-ui-b-color-legend has no colors

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1713]
__Expected:__
![screenshot from 2015-11-02 12 08 55](https://cloud.githubusercontent.com/assets/2546601/10881447/969a42f6-815a-11e5-9acf-4eb4ca793cfd.png)

__Actual:__
![screenshot from 2015-11-02 12 06 09](https://cloud.githubusercontent.com/assets/2546601/10881396/34bf6110-815a-11e5-8328-4fd29622c674.png)

I bisected the issue and it was caused by fa87f45 (https://codereview.chromium.org/1417553005)

**Comment by petrcermak** [comment]
This is now **fixed**.

**Comment by natduca** [comment]
Sorry about that!
