### ISSUE TITLE
Regularly clear out TryJob entities with no config or bot.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1717]
There are currently 421 bisect jobs in datastore with no config or bot. I'm not sure how they were created, but it makes sense that they should be cleared.
```
from dashboard.models import try_job
jobs = try_job.TryJob.query().fetch()
jobs = [j for j in jobs if not j.config]
print len(jobs)
```

Something should be added to auto_bisect.py (or possibly update_bug_with_results.py) to delete these jobs.

**Comment by qyearsley** [comment]
Thanks for taking a look at this Chris :-)

**Comment by chrisphn** [comment]
Found two more places that didn't delete failed try jobs.  Going to manually delete these 421 jobs since they don't contain necessary info to run/restart bisect.

**Comment by chrisphn** [comment]
This should be fixed and also we may not delete TryJobs anymore.
