### ISSUE TITLE
Figure out what Renderer "Resource" async events are and delete them if needed

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1722]
We have netLog and resource async events. Lets figure out their roles and delete one if needed.

**Comment by natduca** [comment]
Any updates?

**Comment by chiniforooshan** [comment]
This is a little bit complicated.

- "Resource" async events are generated in blink's ResourceFetcher.
- There are also instant events generated in blink's FrameFetchContext. They log an ID to group the events related to a resource together.
- Outside blink (still renderer side), we log duration events in ResourceDispatcher when sending/receiving IPCs to the browser.
- On the browser side, we have a NetLog observer that logs async events for all NetLog entries. They are grouped by source IDs that are generated on the browser side.

I think this is a mess :) We should clean up by grouping all of the above-mentioned events together. I'm working on it...

I think after the clean up we shouldn't have the blink's async resource events. They have little value in the trace viewer and don't deserve a separate track. IMO, we should either delete them (if they have little value when bulk processing) or turn them into duration events (with enough information to group them to other resource-related events).

**Comment by natduca** [comment]
Sounds like a design doc on the planned cleanup would be a good step. We could then share with loading-dev and tracing folks for their feedbcak?

**Comment by benshayden** [comment]
@chiniforooshan Any update? Should this be closed?

**Comment by chiniforooshan** [comment]
Going to replace these with async slices that show the life cycle of a resource request with timing information: https://docs.google.com/document/d/1s0DKjNJk85hDuRp5IqujwZvPML-MPsyAtDeksMwBw7s/edit?ts=577ff544#heading=h.8rp0govnm1lf
