### ISSUE TITLE
Connect up NetLogAsyncSlices and renderer-side resource requests

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1725]
Probably blocked on deciding #1723. Once we decide the canonical source of resource creation/etc events, then we can start figuring out how to get these connected up.

**Comment by chiniforooshan** [comment]
My original goal was to build a dependency graph and have the connection between netlog async slices and render-side resource requests in the dependency graph. We have abandoned that plan in favour of Net Instrumentation V2: https://docs.google.com/document/d/1s0DKjNJk85hDuRp5IqujwZvPML-MPsyAtDeksMwBw7s/edit?ts=577ff544#heading=h.8rp0govnm1lf

I'll create new issues for Net Instrumentation V2.
