### ISSUE TITLE
Perf dashboard uses substring "x64" in bot name to find appropriate bisector

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1726]
In [this doc](https://docs.google.com/document/d/1NUVRt24cgF3ZmggZC-YXkWfZphj4P4HcqAUo1aTlw_M/edit#) we are discussing improving naming conventions for chromium.perf bots and making them consistent with tryserver.chromium.perf bots.

One thing we noticed was that the chromium.perf Windows bot names have rotted a bit as we've moved from 32 bit Windows being more prevalent, to 64 bit Windows being more prevalent. These are the only Windows bots that are actually 32 bit:
- Win 7
- Win 7 Low-End
- Win XP

These will be renamed to:
- Win7 32
- Win7 32 Low-End

We need to make sure the code that chooses a bisect picks the correct bisector for 32 vs 64.

@qyearsley @vuppalapu @ro-berto @chrisphn @dave-2

**Comment by qyearsley** [comment]
If builders on tryserver.chromium.perf are renamed, there are two things that would have to be updated now; both of them can be edited through https://chromeperf.appspot.com/edit_site_config.

1. The dashboard decides the tester bot name (the bot on tryserver.chromium.perf) based on prefixes of the bot name according to the table of prefixes at https://chromeperf.appspot.com/edit_site_config?key=bisect_bot_map; if we rename builders on tryserver.chromium.perf we'll just have to update that.

2. The dashboard decides whether to use --browser=release or --browser=release_x64 in the Telemetry command depending on the bisect bot name. This is decided based on another table of prefixes (https://chromeperf.appspot.com/edit_site_config?key=bot_browser_map).

**Comment by anniesullie** [comment]
@dave-2 is this bug still accurate? Any thoughts on the broader problem of these types of checks everywhere?
