### ISSUE TITLE
Add bisect integration tests handler to Perf Dashboard

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#1730]
This is related to setup bisect FYI bots for end to end integration coverage of bisect jobs.
Idea is to add a bisect_fyi handler in dashboard to bisect jobs with different configs by setting up cron job.
Please refer to crbug.com/549702

**Comment by qyearsley** [comment]
There is a [bisect_fyi](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/bisect_fyi.py) handler and it has been running regularly as a cron job for a while.
