### ISSUE TITLE
Browser tests need to use canary

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1732]
We have had two regressions now in trace-viewer due to canary changing, that we didn't catch until someone's local workflow broke.

I think we need to modify the testers to use a more recent build.

@anniesullie can I assign this to you to drive? It isn't p0 but I'd love to see it moving eventually, hence my request to mark it assigned instead of just available... I guess we could also put a milestone on it.

**Comment by natduca** [comment]
The other breakage as #1637

**Comment by anniesullie** [comment]
This is a pretty easy fix: we need to just pipe arguments into run_dev_server_tests to switch the channel= param in the omahaproxy url: https://github.com/catapult-project/catapult/blob/master/catapult_build/run_dev_server_tests.py#L22

I'm super swamped and might have trouble getting this done soon due to BlinkOn. But I'd be happy to do it when I get more time. Should I unassign?

One question in case I find a chance to do this: we want to run on BOTH stable and canary, not switch from stable to canary, right?

**Comment by natduca** [comment]
Mmm yeah I wouldn't say P0 and before blinkon. Probably P1 for M49 is the right framing, since that'd imply blocks M49 milestone which is erm, a little bit out. :)

To the both vs one, I think the main challenge is cq cycle time, right? Maybe we do both and we put a day into figuring out how to get the tests to run a bit faster...

**Comment by anniesullie** [comment]
I just checked on timings. The slowest tryserver is windows, where it pretty consistently takes 2:30 for tracing dev_server tests and :30 for pi dev_server tests. So submitting my CLs as-is would increase our CQ time by 3 minutes. Is that acceptable?

**Comment by natduca** [comment]
Fine by me!

**Comment by anniesullie** [comment]
Blocked on #1745.

Revert the revert of https://codereview.chromium.org/1427583010/  when unblocked.

**Comment by anniesullie** [comment]
Now blocked on #1745

**Comment by natduca** [comment]
Looks like this bit us again this week due to a change in removeEventListener. Very excited to see this change happen!

**Comment by anniesullie** [comment]
Sorry for the slowness here! Current status is that my code works locally on Mac, but hangs on the Mac trybot and I'm having some trouble vnc-ing into the Mac trybot to debug.

**Comment by natduca** [comment]
No worries! Just reiterating my happiness that we have a tracking bug for it :) I totally get that this stuff is painful.

**Comment by anniesullie** [comment]
Windows canary tracing tests are still failing, #1816 has details. I'm working on turning the tests on for all other projects/platforms.

**Comment by anniesullie** [comment]
Canary tests are on for all platforms/projects except Windows tracing. I'm calling this fixed.
