### ISSUE TITLE
In top down mode, as we drill down, sample counts dont add up

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1741]
In this trace:
https://drive.google.com/a/google.com/file/d/0B5oQxJwHXgm1ck9zUnF2TFFaVDA/view?usp=sharing

Select the samples in the "Simple Embedded Viewer" process from about 3.4s to 4.4s. Then expand the samples until you have a row that has ~8 children. Add up the child sample count. it should add to the parent sample count.

**Comment by natduca** [comment]
Calling @lpy

**Comment by lpy** [comment]
From my understanding, the total of a `StackFrameTreeNode` equals to total of its children plus self count of itself, for example

<img width="971" alt="screen shot 2015-11-10 at 4 29 48 pm" src="https://cloud.githubusercontent.com/assets/1453861/11080432/5dd85146-87c8-11e5-9a50-fa1bad08a4c6.png">

we can see that the `total` of `http://localhost:8003/tracing/importer/import.html:160` is 54, which equals to total of its two children plus its own self count, 27, 25, and 2 respectively. That is to say, there are two stack frames in this selection, that `http://localhost:8003/tracing/importer/import.html:160` is on top of these two frames.

@natduca @fmeawad

**Comment by petrcermak** [comment]
@lpy is right. This matches what DevTools does. Anyway, we should discuss this at our meeting tomorrow.

**Comment by natduca** [comment]
So are we saying this is WontFix? I'm fine closing this as long as we're sure that things are correct.

**Comment by fmeawad** [comment]
Marking as WontFix, if we decide otherwise, will reopen
