### ISSUE TITLE
UserFriendlyCategory categories need to be updated for SynchronizedPaint shipping

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1744]
Synchronized paint is shipping soon. This will cause attribution of UpdateLayerTree to be misattributed by our user friendly category code. Devtools will have similar issues.

That is, the meaning of this function is changing in newer chrome revs to mean something totally different. New trace points need to be added, and this trace point has to be updated: https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/frame/FrameView.cpp&l=2398

Overall, we have this general problem: both devtools and perf insights need to make simplifying assumptions about performance in on order to make things make sense at a high level. We do this by having tables like our userFriendlyCategory system that map from lowlevel concepts to high level.

This leads to two problems:
1. We each have our own table, devtools and perf insights. They sometimes dont match. Often.
2. Perf optimization projects ship but we find out that the tables are wrong via bug reports.

Ideally we'd do better. This bug tracks us finding a better plan.

**Comment by natduca** [comment]
@paulirish maybe this is the thing we should use to beta-test the devtools-catapult codesharing ideas?

**Comment by natduca** [comment]
Self assigning but I think we need help from various people.

**Comment by progers** [comment]
We could write a layouttest that dumps the current list of high-level trace categories and verifies that they don't change for a simple document lifecycle. We could add a comment in the test that a change should both update the test expectation and consider updating tracing et al.

Chris is leading the synchronized painting effort, I'll point him at this bug.

**Comment by ianvollick** [comment]
For the curious: synchronized painting does painting during the document lifecycle as opposed to having it pulled by cc. Some details here https://codereview.chromium.org/1373983004

**Comment by natduca** [comment]
I think probably we need to wontfix this and deal with this by learning the hard way down the road when things break.... right now I can't quite see a route to us giving this out as a task, due to the magnitude of the other issues we've got that dwarf this hehe.

I'm going to reluctantly WontFix. We'll definitely re-discover this though!
