### ISSUE TITLE
Integration testing strategy for PI

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1749]
@natduca @philippebeaudoin @nedn 

It seems like the Python/JS/Vinn boundary is a pain point in PI. For example, in https://codereview.chromium.org/1408033011 I fixed a bug I created wherein I referred to a dict field in JS style, that was actually named in Python style.

It would be nice to have an integration testing strategy for these places, so that I could make assertions like "given a dict produced by this Python call, it can be deserialized properly from JS".

**Comment by natduca** [comment]
Gonna close this due to inactivity. We can totally open it if we think up a specific direction that we plan to move forward.
