### ISSUE TITLE
Add connection type (2G, 3G, WiFi...) to trace metadata

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1750]
Ensure the trace contains metadata for connection type (2G, 3G, WiFi, Wired...)

The connection type can change at any time so we probably need to store it as a phase=m event.

Thread discussing the inclusion of this on UMA:
https://groups.google.com/a/google.com/forum/#!msg/chrome-loading/h3uvlNfyDbs/tiO0BaMpEwAJ

@natduca @vinterstum @simonhatch

**Comment by natduca** [comment]
Is this using the network quality estimator? Maybe now that our metadata system is cleaner, we could ask for help on this patch from charles harrison....

**Comment by benshayden** [comment]
Looks old. Open a new bug with more information if there's something you still want to do here?
