### ISSUE TITLE
Select samples causes a Uncaught TypeError

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#1751]
When I select a sample, I got a `Uncaught TypeError: currentNode.getOrCreateChild is not a function`.

From what I found, it's because the code in [here](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/analysis/stack_frame_tree.html#L161), will return an empty object, because the title is `__proto__`, which was not supposed to be found in `this.childMap` and should be created.

The reason is that `childMap = {}` has `__proto__`.

Thoughts?

**Comment by lpy** [comment]
Please see the trace [here](https://github.com/catapult-project/catapult/issues/1741)

**Comment by lpy** [comment]
<img width="622" alt="screen shot 2015-11-09 at 2 06 26 pm" src="https://cloud.githubusercontent.com/assets/1453861/11048168/240cc0d8-86eb-11e5-9d83-ab905fb6bc6f.png">

**Comment by natduca** [comment]
Guess thats just how v8 works. So lets use Map(), add a quick unit test for this specific case so that it doesn't regress, and be happy that you're awesome and figured out the issue so quickly!

**Comment by lpy** [comment]
Close as fixed.
