### ISSUE TITLE
IRs for Load and response/animate often overlap

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1756]
It seems to me that in the end, IRs should never overlap. Right now, I routinely see cases where load and R/A stages overlap. This seems problematic.

for instance, measurmt traces desktop/v8-samples/trace_aol has:
![image](https://cloud.githubusercontent.com/assets/412396/11067491/a10c1868-8781-11e5-980a-d552c8ded670.png)

**Comment by natduca** [comment]
@benshayden can you drive?

**Comment by benshayden** [comment]
I suspect that's a subframe Load, so I think this should be fixed now that subframe Loads are suppressed.
I'll check to confirm and close this on Monday.
