### ISSUE TITLE
Reorganize front end directory structure

### ISSUE THREAD

**Issue by chrisphn** [catapult-project/catapult#1760]
The current structure is pretty easy to navigate, but some thoughts:

Motivation:
 - Dashboard is getting larger
 - A place to add models to make json data more transparent

<pre>
dashboard/
    static/
        favicon.ico
    dashboard/
        models/
            anomaly.py
            bug_data.py
            graph_data.py
        ui/
            /common
                bisect_utils.html
                uri.html
            /models
                series_group_data.html
                alert_data.html
                test_suite_data.html
            /elements
                chart_container.html
                chart_legend.html
                test-picker.html
            report.html
            group_report.html
            main.html
        add_point.py
        alerts.py
        main.py

By feature:

dashboard/
    static/
        favicon.ico
    dashboard/
        models/
            anomaly.py
            bug_data.py
            graph_data.py
        ui/
            /common
                bisect_utils.html
                uri.html
            /graphing
                chart-container.html
                chart-legend.html
                series_group_data.html
                report.html
                group_report.html
            /alerting
                alerts-table.html
                alert_data.html
                alerts.html
            /bisect
                bisect-form.html
                bisect-status.html
                bisect_status.html
            /testselection
                test-picker.html
                report-container.html
                report.html
        add_point.py
        alerts.py
        main.py

</pre>

**Comment by qyearsley** [comment]
Sounds good; we at least want to move the JS that's currently in static/ to somewhere that makes more sense. I like the first directory layout a little better; one possible confusion with the second layout example above is that I wouldn't know where to look for some templates, e.g. report.html (in "graphing" or "testselection")?

**Comment by anniesullie** [comment]
We're going to close this for now; may revisit in a new bug about code-sharing with trace-viewer.
