### ISSUE TITLE
Lots of strange response records in wikipedia cats scroll

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1764]
This trace:
https://drive.google.com/file/d/0B2UAouCtyY6-Wkg1aExrcWNsUFU/view?usp=sharing

has lots of spurious response records:
![image](https://cloud.githubusercontent.com/assets/412396/11079131/f2b2d8e0-87be-11e5-8b91-c01a610d0b70.png)

I think as the fling slows down on mac, we start getting responses again?

**Comment by natduca** [comment]
calling @benshayden

**Comment by benshayden** [comment]
I don't see them.
https://x20web.corp.google.com/~benjhayden/1764.png

**Comment by natduca** [comment]
Great! Shall we close this?
