### ISSUE TITLE
associatedEvents should include v8 samples

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1766]
Should V8 Samples be included in IR.associatedEvents? SliceCostReport has this hand-coded in now, but maybe it should be more formalized.

**Comment by natduca** [comment]
Calling @fmeawad @lpy @benshayden

**Comment by benshayden** [comment]
To clarify: when an InputLatencyAsyncSlice adds a 'V8.Execute' ThreadSlice to its associatedEvents, then it should use Range.filterArray(slice.parentContainer.samples, ...) to find the v8 samples that intersect the V8.Execute slice.

Eventually, when Load IRs get V8.Execute slices associated with them, they'll do the same thing, so we might want a general function for getting the samples that intersect a slice.

Maybe a method on Thread like "getSamplesIntersectingSlice"? "getSliceIntersectingSamples"?

**Comment by natduca** [comment]
Mmm I like the idea of Thread helper method!

**Comment by lpy** [comment]
This is fixed.
CL: https://codereview.chromium.org/1841993004/
