### ISSUE TITLE
Auto-CC when filing bugs for certain tests with alerts above a certain severity.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1768]
Use case: Somebody (or some team) wants to always be CCd for all alerts above a certain magnitude.

I think that this could be implemented perhaps as a mapping between test path patterns (e.g. `ChromiumPerf/*/my-test/important-result/*`) and dicts with thresholds and email addresses (e.g. `{"min_relative_change": 0.05, "emails": ["foo@chromium.org"]}`) and email addresses.

Current work-around: add a label to be auto-added (using the admin page https://chromeperf.appspot.com/edit_bug_labels). People interested in alerts would have to subscribe to that label and manually filter through the bugs filed (which may contain bugs for smaller alerts).

**Comment by anniesullie** [comment]
I think this should be done with labels.
