### ISSUE TITLE
Roll chrome catapult DEPs to include current catapult

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1769]
We want to make sure Friday's canary has our sampling sub view fixes

**Comment by natduca** [comment]
Copy this:
https://codereview.chromium.org/1343903003

Fady, or I can review the patch.

**Comment by petrcermak** [comment]
If you have a Chromium checkout, just run <tt>roll-dep src/third_party/catapult _\<CATAPULT-COMMIT-SHA\>_</tt> in the repository. This will automatically create the patch for you.

**Comment by lpy** [comment]
close
CL: https://codereview.chromium.org/1437983002/
