### ISSUE TITLE
counters

### ISSUE THREAD

**Issue by araud** [catapult-project/catapult#1770]
When playing with counters I noticed set of unexpected things.

Please open this trace:

{
"traceEvents": [
{"ph":"C", "pid":1, "tid":1, "ts":1, "name":"a", "cat":"Example", "args":{"sinus":100}}, 
{"ph":"C", "pid":1, "tid":1, "ts":2, "name":"b", "cat":"Example", "args":{"counter":200}},
{"ph":"C", "pid":1, "tid":1, "ts":3, "name":"a", "cat":"Example", "args":{"sinus":200}}, 
{"ph":"C", "pid":1, "tid":1, "ts":4, "name":"b", "cat":"Example", "args":{"counter":400}},
{"ph":"C", "pid":1, "tid":1, "ts":5, "name":"a", "cat":"Example", "args":{"sinus":300}}, 
{"ph":"C", "pid":1, "tid":1, "ts":6, "name":"b", "cat":"Example", "args":{"counter":600}},

{"ph":"C", "pid":1, "tid":1, "ts":1, "name":"two", "cat":"Example", "args":{"a":1, "b":2, "c":5}}, 
{"ph":"C", "pid":1, "tid":2, "ts":2, "name":"two", "cat":"Example", "args":{"a":3, "b":2}}, 
{"ph":"C", "pid":1, "tid":3, "ts":3, "name":"two", "cat":"Example", "args":{"a":5}}, 
{"ph":"C", "pid":1, "tid":4, "ts":4, "name":"two", "cat":"Example", "args":{"a":1, "b":2}}, 
{"ph":"C", "pid":1, "tid":5, "ts":5, "name":"two", "cat":"Example", "args":{"a":1, "b":3, "c":5}}, 

{}]}
1. Track sorting is not alphabetical. If I have many counters I'd like to have them sorted to ease vertical navigation.
2. Last chunk of data is always lost. For example last value of b/counter == 600, but I can see only 400
3. When counters packed to series, skipped counter is always considered 0. That's not true, we don't know its value at this point, so last value or None would be righter. Because 0 means big problem for some counters. (Mind heart beat per minute :) )

I know I can workaround 2 with repeating last value for each counter in the end of trace.

I know I can workaround 3 by making sure I have all of counters in pack every time one of them is  changed. This could do for small traces. But in my case I pack counters together because the trace is too high (overhaul, stops rendering) and thus has much of data. Multiplying all counters of each instance change will make trace considerably bigger. Which increases probability to be not opened at all. 

But how to make sure the sorting is alphabetical?

**Comment by benshayden** [comment]
All of these issues appear to be fixed.

![](https://i.imgur.com/eTKTabq.png)
