### ISSUE TITLE
Warn when a trace lacks events required for the UserModel

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1776]
Currently, users can record chrome traces without enough categories to find RAIL IRs, and the RAILIRFinder will happily say "Idle!" #1709 

This is confusing to users who know that they interacted with chrome, and can see some evidence of their interaction, and don't understand why the RAILIRFinder can't find their interactions.

RAILIRFinder should explain which categories it requires to find interactions.

RAILIRFinder should not intrude with infobars when the user knows that they traced Android, not Chrome.

The first step towards accomplishing this is figuring out which categories RAILIRFinder requires, and which categories were captured in a trace.

**Comment by natduca** [comment]
@philippebeaudoin is doing some work that makes the categories for a trace available in the model... 

Once you've got that done, maybe you could make the IR finder push a userVisibleError to the model warnings list? That'd then propagate to the UI properly and create a butter bar n stuff....

**Comment by benshayden** [comment]
Duplicate #2336
