### ISSUE TITLE
Get rid of FunctionHandle.loadFromFilename_

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1779]
We no longer want to support loadFromFilename_ because the hack it uses blocks registering multiple functions in a single source file. Currently, map_traces and gce_instance_map_job are the last two places where mappers are specified solely by filename, and they specify what to run on the command line.

We'll introduce user-friendly strings to functionhandle with the syntax:
`file1:file2:...:fileN:function_name`, and error if no function name is passed.

@natduca @simonhatch

**Comment by natduca** [comment]
\o/ bombs away!
