### ISSUE TITLE
MRE Results + Failures

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1781]
We want to refactor the PI results/value systems into a general system for reasoning about JSON results and failures in a MapReduce pipeline called TinyMR.

@natduca

**Comment by eakuefner** [comment]
Short design doc: https://docs.google.com/document/d/1MpVcvSrqi9GbQCYjHnOwaLWq3buwFWJeqw-rxCGFWrc/edit
WIP CL: https://codereview.chromium.org/1447323002

**Comment by natduca** [comment]
Done?
