### ISSUE TITLE
If the exact point for an Anomaly is unclear, use a range encompassing two points

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1784]
Sometimes on a graph, it's not clear exactly which of two points is the "real" change point where a regression may have occurred. Example:

![screenshot from 2015-11-17 09 13 21](https://cloud.githubusercontent.com/assets/3926653/11218797/ed4850e0-8d0b-11e5-9b3a-3baf4e142e21.png)

Anomaly entities have a start and end revision; currently de facto is always start is always (revision of point before end revision + 1), but it could theoretically be earlier.

In http://crbug.com/556528, Dave suggested possibly having alerts encompass multiple points.

In order to do this, we'd have to first decide on a way to decide when to make the anomaly encompass two points (in the vast majority of cases, the step is clearly at one point).

**Comment by anniesullie** [comment]
@dave-2

**Comment by benshayden** [comment]
Archiving.
