### ISSUE TITLE
Perf dashboard should send an alert mail when it fails to kick off a bisect job

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1785]
We want to be informed immediately when bisect fails to kick off. It should send a mail to the alerting address.

**Comment by qyearsley** [comment]
Note, for background: currently when start_try_job fails to start a bisect job for a user (because of a failed request to Rietveld or Buildbucket), some bold red error text is shown in the UI. However, in practice users often ignore that and don't file a bug, and the dashboard team are not necessarily aware of the problem.

**Comment by nodirt** [comment]
To repeat what I said in the doc: I recommend:

1) Log the event of a failure, e.g. "Failed to schedule build ...."
2) Create a "Logs to Metrics" metric in Cloud Console with that pattern
3) Add an Alert Policy in Cloud Monitoring when this number reaches some threshold, email team or something.

**Comment by anniesullie** [comment]
Thanks for clarifying, Nodir! A question about this, though: these jobs are kicked off by users manually, at far less than once per minute. Is it possible to create an alerting policy that works reliably with very low volume?

**Comment by nodirt** [comment]
Unfortunately not using Cloud Monitoring.

You can use https://github.com/luci/luci-py/tree/master/appengine/components/components/ereporter2 to decrease the volume to 1/hr, but it may be too low too.

**Comment by anniesullie** [comment]
I think since that there are very few instances when we really just want an email, actually writing the code to just send an email in-band is okay here. It doesn't scale very well, but if we needed it to scale the other solutions work fine.

**Comment by nodirt** [comment]
Would this email be sent to the person who requested a tryjob or service maintainer? ereporter2 sends an email every hour on any errors in GAE log happened that hour. It is useful to monitor state of an app. They are not mutually exclusive.
