### ISSUE TITLE
Count of alerts does not get updated after triaging unless the page is reloaded

### ISSUE THREAD

**Issue by ro-berto** [catapult-project/catapult#1787]
If you go to [the alerts page](https://chromeperf.appspot.com/alerts) and triage some alerts, the number of untriaged alerts (just above the triage button) does not get updated unless you refresh the page.

**Comment by qyearsley** [comment]
I would have phrased this as a feature (update count of alerts on the alerts page upon triaging) rather than a bug...

One way to do this would be to make the count part of elements/alerts-table rather than part of the alerts page itself.

**Comment by benshayden** [comment]
Archiving. V2SPA recomputes the summary when the alertGroups array changes.
