### ISSUE TITLE
ResponseExpectations's associatedEvents in cats trace need tweaking

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1792]
In this trace:
https://drive.google.com/file/d/0B2UAouCtyY6-Wkg1aExrcWNsUFU/view?usp=sharing

The reponse IR at 1,475.861 ms has may many frames worth of associated events that really should be part of the animation's associated events.

Ideally, the associated events for this R event would just be the work for that one frame.

**Comment by benshayden** [comment]
Next steps: dig into why InputLatencyAsyncSlice attributed all those ThreadSlices to the Response instead of the Animation.
