### ISSUE TITLE
measure of performance API doesn't show up right at the top of V8 samples

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#1793]
Please see the picture

<img width="251" alt="screen shot 2015-11-18 at 2 59 34 pm" src="https://cloud.githubusercontent.com/assets/1453861/11257225/2bf81272-8e05-11e5-88f5-4aa722b6590b.png">

Here, `createImports`, `finalizeImport` and `importSampleData` are measure using `performance.measure`. I think it would be clear if they can show up right at the top of V8 samples rather than in alphabet order.

WDYT?

**Comment by fmeawad** [comment]
In general, we would like to be able to re-order the tracks in a way that makes more sense. This is one of many examples.

Can you place the screen shot with part of the tracks that shows the mark/measure slices as well? as well as link a trace to the bug?

**Comment by lpy** [comment]
The trace is https://drive.google.com/a/google.com/file/d/0Bx-NDXy3mYCuQzJYeWhzeEtTTHM/view?usp=sharing

And here's the screen shot

<img width="1440" alt="screen shot 2015-11-18 at 3 52 49 pm" src="https://cloud.githubusercontent.com/assets/1453861/11258249/72e30d0c-8e0c-11e5-81ad-6d1e10445653.png">

**Comment by fmeawad** [comment]
I am thinking that on top of what you mentioned, these should be on the same track and not one track for each, is the track name the name of the "measure" entity?

**Comment by natduca** [comment]
if memory serves, I think the way to fix this is to make a measure_async_slice.html in the style of net_async_slice and then have that override the groupingTitle accessor or something like that..

**Comment by lpy** [comment]
the category of mark/measure on trace viewer is `blink.user_timing`, but `blink.user_timing` is also being used for other events.

Any suggestion we group the mark/measure things into one track? How about we file a crbug to change the category for mark/measure, like `blink.mark_measure`? And then we can group them using category.

WDYT?

**Comment by fmeawad** [comment]
calling @zeptonaut for advice?

**Comment by fmeawad** [comment]
I am wondering if the context has diverted from the original bug reported, if so please file a new bug.

**Comment by fmeawad** [comment]
Never mind, it turns out that the other stuff that uses blink.user_timing are not using the nestable async events, and nat's suggestion works on those only.

**Comment by lpy** [comment]
CL: https://codereview.chromium.org/1464863002/

Close as fixed
