### ISSUE TITLE
"select all | deselect all | core" selector in chart-legend only applies to first group

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1795]
To reproduce: Open a chart with multiple series groups (e.g. https://chromeperf.appspot.com/report?sid=97b3acea7c556fda16156b5ccab94c059cae9161f81210dcd7e8b37b24a5ad60) and click "select all" "deslect all" or "core only". Only the first series group changes.

@chrisphn I just noticed this -- maybe we can either get rid of it, or make it apply to all series groups in the legend?

**Comment by chrisphn** [comment]
Hm, I thought it worked before.

**Comment by benshayden** [comment]
Archiving.
