### ISSUE TITLE
Surface individual result descriptions to the dashboard.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1799]
In Telemetry, we have detailed descriptions of many individual results for benchmarks, which are provided by passing the optional argument `description` when constructing a value ([example](https://code.google.com/p/chromium/codesearch#chromium/src/tools/perf/benchmarks/kraken.py&l=110)) -- however, we're not making use of these anywhere yet.

In order to actually use these detailed result descriptions, we need to:
1. Include description in chartjson results format from Telemetry. ([example current chartjson](https://build.chromium.org/p/chromium.perf/builders/Mac%2010.11%20Perf%20%284%29/builds/273/steps/kraken/logs/json.output))
2. Change add_point: Make sure that when points are added (via /add_point) all of the the descriptions for each chart in the chartjson are used to update the relevant Test entities.
3. Surface to front-end: chart-container should take the description from the response from /graph_json, and pass the relevant descriptions to chart-legend, and chart-legend should display them in tooltip-test-description elements.

**Comment by anniesullie** [comment]
This is already in the chart_json, and it used to be pushed to the test and the UI but seems to have broken :/

**Comment by benshayden** [comment]
Archiving. V2SPA will display full Histograms in a table below charts, including description.
