### ISSUE TITLE
Benchmark description not updated from chartjson.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1803]
Benchmark descriptions are supposed to be updated from the description in chartjson whenever they change, but this is apparently not happening now.

Example case: service_worker.service_worker:
To check, go to https://chromeperf.appspot.com/report, open the JS console and check `TEST_SUITES['service_worker.service_worker'].des`. It should be the same as the description in recent chartjson received (e.g. https://build.chromium.org/p/chromium.perf/builders/Win%207%20Nvidia%20GPU%20Perf%20%285%29/builds/2553/steps/service_worker.service_worker/logs/json.output).

**Comment by anniesullie** [comment]
@eakuefner

**Comment by benshayden** [comment]
Obsolete. Let's file a fresh bug if we want to plumb this through SparseDiagnostic.
