### ISSUE TITLE
Update tr.b.Statistics.discrepancy to use O(n) algorithm

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1805]
Currently, Statistics.discrepancy uses an O(n^2) algorithm, as it was ported from Chromium's tools/telemetry/telemetry/util/statistics.py.

Recently, that algorithm was re-implemented in telemetry using a modification of Kadane's algorithm: https://en.wikipedia.org/wiki/Maximum_subarray_problem
https://codereview.chromium.org/1409143006/

Statistics.discrepancy should be updated to use the new O(n) algorithm for speed and to make it easier to verify that the client metrics are comparable.

@nedn Feel free to unassign or reassign. Thanks!

**Comment by natduca** [comment]
@eakuefner if you have free cycles, this'd be a useful thing for the tbm -> tbm v2 transition

**Comment by nedn** [comment]
Fixed by @ulan in https://codereview.chromium.org/1883143002/

Yay, thanks Ulan!

**Comment by nedn** [comment]
Hmhh, not sure why I can't put ulan@ as the assignee.
@anniesullie

**Comment by anniesullie** [comment]
@nedn: @ulan was not a committer. I added him, but he'll need to accept the github invitation before we can assign him.

**Comment by ulan** [comment]
Thanks, Annie. I accepted the invitation.
