### ISSUE TITLE
Tests fail because of Uncaught TypeError in overlay.html

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#1806]
`Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.` because event type is missed. See the picture below for more details.

<img width="1435" alt="screen shot 2015-11-25 at 3 57 52 pm" src="https://cloud.githubusercontent.com/assets/1453861/11412110/52a3007a-938d-11e5-89eb-de367e94b116.png">

**Comment by natduca** [comment]
Is this happening on tip of tree? Or does it take some specific step to reproduce...

**Comment by fmeawad** [comment]
I was not able to reproduce on ToT on either linux or mac. 
@lpy: if you still think this is reproducible, please provide a reproduction scenario, otherwise close it.

**Comment by lpy** [comment]
I can still reproduce it.

1. update to the latest commit
2. run the dev server
3. open http://localhost:8003/tracing/tests.html

There are 3 failures.

**Comment by natduca** [comment]
Ah, its the #1732 bug again. Canary looks like its got a change thats not in Stable.

**Comment by fmeawad** [comment]
That makes sense, I just verified that it fails on chromium 49.0.2578.0.

**Comment by lpy** [comment]
CL: https://codereview.chromium.org/1476843003/

close as fixed
