### ISSUE TITLE
When bisecting on a per-page trace, add --story-filter to the test command.

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1811]
**Issue by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-01-14T02:38:55.000Z_
_Originally opened as http://crbug.com/448628_

---

Currently, when bisecting per-page traces, the full test is run, including all pages in the page set for a benchmark.

If --page-filter=... was added, this could significantly decrease the time required to run the bisect, especially if the builds are already available.

This could be done in the dashboard in start_try_job.GuessCommand.

**Comment by eakuefner** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-03-10T00:52:03.000Z_

----

--page-filter is being renamed to --story-filter, see issue 444425.

**Comment by eakuefner** [comment]
**Comment by [sl...@chromium.org](https://code.google.com/u/106172715164152410941/)**
_2015-03-18T23:21:45.000Z_

----

--page-filter has been renamed to --story-filter.

**Comment by eakuefner** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-08-24T21:17:41.000Z_

----

Bulk edit: Archiving feature requests that we don't have any current plans for. New feature requests should be filed at https://github.com/catapult-project/catapult/issues.

**Comment by eakuefner** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-10-13T18:09:12.000Z_

----

Re-opening -- we talked about this again today.

**Comment by eakuefner** [comment]
**Comment by [pras...@chromium.org](https://code.google.com/u/116704265016059607269/)**
_2015-11-16T18:23:45.000Z_

----

**Comment by eakuefner** [comment]
**Comment by [qyears...@chromium.org](https://code.google.com/u/107012661329935444717/)**
_2015-11-26T01:45:56.000Z_

----

The main challenge with implementing this guessing (based on information in the dashboard), what is a page/story name and what is not. We can't assume that story names will have http or www in the name; we also probably shouldn't assume that they're at the 5th level of the test path (master/bot/benchmark/chart/story).

We can probably assume that the lowest level of the test hierarchy for Telemetry tests are story names. Except of course for page_cycler, where page_load_time is at the same level in the hierarchy as all of the individual page names...

**Comment by eakuefner** [comment]
**Comment by [sulli...@chromium.org](https://code.google.com/u/117088883005658624950/)**
_2015-11-30T15:38:37.000Z_

----

Maybe it is time we passed some additional information from telemetry chartjson to the perf dashboard? There is a need for additional information about telemetry commands in bug 561992 as well.

**Comment by eakuefner** [comment]
**Comment by [nedngu...@google.com](https://code.google.com/u/105270153271635518855/)**
_2015-11-30T16:27:44.000Z_

----

I think this is block on ensuring that there are no two pages/stories with a same name in a telemetry benchmark. Once that is done, the simplest way to achieve this is add a "name" field in Page.AsDict() & Story.AsDict() that can (https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/page/__init__.py&l=104)

**Comment by eakuefner** [comment]
**Comment by [nedngu...@google.com](https://code.google.com/u/105270153271635518855/)**
_2015-11-30T16:34:28.000Z_

----

Turn out that all stories already have a 'name' & 'display_name' fields, and to make it even more confusing, story filter uses both (https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/story/story_filter.py&l=26)

The AsDict() method of Story & Page already include 'name' but not 'display_name'. 

+Quinten: Is the dashboard using 'name' field of page in anyway?

**Comment by eakuefner** [comment]
**Comment by [eakuef...@chromium.org](https://code.google.com/u/113455657570966801301/)**
_2015-11-30T18:30:12.000Z_

----

Ned: The way chart JSON currently works, the trace names are given by Value.GetChartAndTraceNameForPerPageResult. The implementation currently uses the display_name of the page, because not all pages have a name: https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/value/__init__.py&l=154 .

The display_name is the name if there is one; otherwise it's the URL.

I think the straightforward, backwards incompatible approach here is to do something similar to what Ned describes:

0. Force Telemetry to guarantee that no two stories have the same name or display_name
1. Add display_name to Story.AsDict
2. Add the same 'pages' dict that maps page IDs to page dicts that appears in Telemetry JSON https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/internal/results/json_output_formatter.py to Chart JSON (I will probably do this by just making chart JSON translate Telemetry JSON once and for all)

On the dashboard side, based on the bug that Annie linked about memory_health_plan, I think it might be time we introduced a new kind of entity to store Telemetry-specific information about values that will be used in constructing bisect commands, so that we can stop trying to find increasingly clever and outrageous ways to work around the impedance mismatch between the dashboard's notion of test hierarchy and Telemetry's notions of results, stories, values, and interaction records.

My sketch of the dashboard side work here is:

0. Add a new kind of entity, TelemetryMetadata, which stores information about values produced by Telemetry that will be used to construct bisect commands.
1. Add an optional, updatable field to Test that holds a key to a TelemetryMetadata.
2. When adding points, if we're dealing with Telemetry data, add and/or update the TelemetryMetadata for the associated tests, like we do for the unit -> improvement direction map.

Does this sound reasonable to folks? If it does, I'll write a design doc about this so we can work out the high-level issues.

**Comment by qyearsley** [comment]
Ah, for some reason I missed Ethan's proposal above before.

>I think it might be time we introduced a new kind of entity to store Telemetry-specific information about values that will be used in constructing bisect commands, so that we can stop trying to find increasingly clever and outrageous ways to work around the impedance mismatch between the dashboard's notion of test hierarchy and Telemetry's notions of results, stories, values, and interaction records.

Agreement!

> 1. Add a new kind of entity, TelemetryMetadata, which stores information about values produced by Telemetry that will be used to construct bisect commands.
> 2. Add an optional, updatable field to Test that holds a key to a TelemetryMetadata.
> 3. When adding points, if we're dealing with Telemetry data, add and/or update the TelemetryMetadata for the associated tests, like we do for the unit -> improvement direction map.

This may be a good idea; the main alternative is to add extra properties to Test (without "a_", must exist on all Test entities), or use set extra annotation properties (starting with "a_", more flexible, not necessarily present on any particular Test entity).

So, for example, based on the chartjson, when adding data, we could set "a_telemetry_page_id" and "a_telemetry_interaction_label" on some Test entities. Or, we could create TelemetryMetadata entities with this information.

Ethan, could you still write a design proposal?

**Comment by eakuefner** [comment]
@anniesullie has been thinking a lot about how to deal on the dashboard side with the common value system's more flexible notions of grouping, and I think we may want to wait to build on top of a sane solution there.

**Comment by anniesullie** [comment]
Here's the [doc](https://docs.google.com/document/d/1LwkUuqEzWe1NhLEpY_o6FJe7gTm8zRzDKvUW3TdOX3M/edit#) I've been writing up around how the data might be stored.

Would things like test owner, telemetry command, etc just be diagnostic data? Or should there be more properties on metric?

**Comment by eakuefner** [comment]
Yes, owner, command, and so on would be diagnostics.

In the big data context, diagnostics are meant to be lossy, so that if you map on a million traces, you know that you don't have to preserve diagnostics, but in the dashboard context, we probably have few enough diagnostics that we can just keep them around, like we currently do for trace files.

**Comment by eakuefner** [comment]
Let's archive this -- there was some discussion with @dave-2 and @nedn yesterday about how we could do this without compromising statistical soundness by using --story-filter as a fast path and running the whole benchmark if that doesn't reproduce, but there are technical challenges with trying to run individual pages because the benchmark is the atomic runnable unit -- in particular, it's hard to make guarantees about what --story-filter will do when custom shared states are used.

**Comment by anniesullie** [comment]
Thanks to @petrcermak benchmark stories can now be an atomic unit. Re-opening. @eakuefner do you have thoughts on how to pipe the --story-filter flag through to the dashboard?

**Comment by dave-2** [comment]
Do you or @petrcermak have more information on what changed that makes it permissible to divide up benchmarks?

**Comment by nedn** [comment]
If the benchmark has ShouldTearDownStateAfterEachStoryRun return True (this is a class method).

**Comment by dave-2** [comment]
How can dashboard/bisect tell if that field is true?

**Comment by nedn** [comment]
We can probably add a convenient script like: tools/perf/is_benchmark_stories_independent <benchmark name> that return 0 or 1. Then bisect recipe can run that script to determine whether it should allow --story-filter?

Another alternative is we pass this info to the chart_json_results & dashboard can use that data to know whether benchmark is --story-filter applicable.

**Comment by perezju** [comment]
> Another alternative is we pass this info to the chart_json_results & dashboard can use that data to know whether benchmark is --story-filter applicable.

That sounds more sate to me.

**Comment by eakuefner** [comment]
@perezju I think I actually prefer the other solution Ned proposes, because a benchmark could have independent stories for one revision but not another, since the benchmarks are run from whatever the state of tools/perf was at the revision being bisected.

**Comment by eakuefner** [comment]
Although now that I think about it, there's exactly one caveat with this approach, which is that the script in question may not be present in too early of a revision: in that case, we can conservatively assume that we should not pass --story-filter.

**Comment by eakuefner** [comment]
I will do the tools/perf side of this, and @dave-2 should do the recipe side.

**Comment by perezju** [comment]
> @perezju I think I actually prefer the other solution Ned proposes, because a benchmark could have independent stories for one revision but not another, since the benchmarks are run from whatever the state of tools/perf was at the revision being bisected.

Actually, trying to bisect through a change between independent <-> dependent benchmark is going to be of little value. I can guess that whatever regressions we're seeing in that range are precisely due to that change. Conservatively, maybe the dashboard can check the chart jsons before/after and, if the "independent" bit changed, force to run without --story-filter ?

**Comment by eakuefner** [comment]
Dave, `run_benchmark check_independent` has landed. Are you planning to work on the recipe side of this change?

**Comment by perezju** [comment]
@picksi FYI

**Comment by picksi** [comment]
Do we have agreement over the way to proceed on this? There was a discussion back in August about alternative solutions, has this now been resolved?

Are there any other blockers we need to fix?

**Comment by anniesullie** [comment]
We had a discussion at our team meeting on Wednesday. I think the conclusion was that we should add a flag to telemetry that does something like `--story-filter-to-use-if-stories-are-independent`, and have bisect pass that in always for telemetry tests. @eakuefner @perezju is that right?

**Comment by nedn** [comment]
I recall our resolution is to just always enable "--story-filter" when bisect on page because there are not many pages that restart the browser between pages, and for ones that do, it's not useful to bisect them because they take a very long time to run.

**Comment by anniesullie** [comment]
My recollection is that @perezju found some benchmarks which are not independent when he switched the default beyond the long-running memory ones. Juan, what were those? I agree if there are few enough we should just always pass `--story-filter`.

**Comment by eakuefner** [comment]
+1 to just always enabling `--story-filter` if possible. What are the dependent benchmarks other than the long-running memory runs (which I think we said we would not anyway be able to bisect on)?

**Comment by perezju** [comment]
Yes, I'm actively working on this. To answer some of the existing queries, the only benchmarks where stories are *not* independent are:

* memory.dual_browser_test
* memory.top_10_mobile
* tab_switching.five_blank_pages
* tab_switching.top_10
* tab_switching.tough_energy_cases
* tab_switching.tough_image_cases
* tab_switching.typical_25

We could probably special-case for these on the dashboard side.

Also since the dashboard only has a long "metric path" and does not really know which part of it is the "story", we'll need to guess that anyway using some heuristics based of the benchmark/metric name.

I already have some code for this guessing that doesn't look too horrible, but I'm going through the list of all existing benchmark/stories/metrics to make sure that it works as expected in al the typical cases.

**Comment by anniesullie** [comment]
Thanks for the list! We plan to deprecate the tab_switching benchmark in favor of system health browsing stories with BattOr support, so I think it is fine for the bisecting on those to use `--story-filter` in the short term. So always passing `--story-filter` is fine with me.

@eakuefner @nedn didn't we have a bug on the "metric path" vs "story" before? Weren't there some ideas on how to get it right 100% of the time? (Maybe sending it to the dashboard in chartjson??)

**Comment by anniesullie** [comment]
Oh, silly me, the discussion I'm referring to about how to get the story name is in this same bug, see the earlier comments like https://github.com/catapult-project/catapult/issues/1811#issuecomment-160723488

(Note we've done a lot more thinking about how to push data between telemetry and perf dashboard, so ignore the older docs on that and just add comments to the bug if you think we should be sending the exact story-filter value here and we'll work out how to do it.)

**Comment by perezju** [comment]
After looking around at lots of data (metric names, Telemetry stories, etc.), I would like to propose to start on the dashboard side **using a simple heuristic to determine a suitable --story-filter pattern, and then present it to the user in the [bisect-form.html](https://github.com/catapult-project/catapult/blob/6c8709c0cc9df527cc7f9bdee99f9152fa820df7/dashboard/dashboard/elements/bisect-form.html) to confirm**.

This allows to:
* Un-block faster system health bisects ASAP, no need to wait for Telemetry-side changes.
* Works for revisions in the past too, again because it does not depend on Telemetry-side changes.
* It is virtually imposible to come up with a heuristic that works *all* the time (and any that does will be eventually broken in the future). But a simple heuristic can be made to work *most* of the time, and when it doesn't users can still edit or remove the filter.
* For power users, allowing to edit the story-filter also unlocks more opportunities (e.g. on system_health benchmarks, being able to filter by story groups; not only individual stories).
* The heuristic can be later improved by adding more information from the Telemetry-side and storing new data entities on the dashboard with the proper story names (e.g. following the approach that Ethan proposed before).

I'll start implementing this approach unless I hear any objections.

**Comment by nedn** [comment]
Can you explain your heuristic?

**Comment by perezju** [comment]
Yes! Simple: if the metric is a leaf (i.e. has no subtests) it's probably a story name. Also, because the `--story-filter` is a regex pattern, escape all active regex characters and replace any `_`'s to `.`'s (the dashboard mangles a bit some story names, replacing "unsafe" chars with `_`).

**Comment by perezju** [comment]
As I've mentioned a few days ago, this is working now fine as expected on most benchmarks. Except for `memory.top_10_mobile` where we knew it would have troubles because the benchmark itself does not support `--story-filter` very well.

For example in [crbug.com/656725](https://bugs.chromium.org/p/chromium/issues/detail?id=656725), all of the bisects on background stories (story name starts with `after_`) do not work because those assume that the previous story did load some page (e.g. ran story `cnn_com` and then `after_cnn_com`).

A simple temporary fix, until the benchmark is deprecated, would be to introduce a special case for `memory.top_10_mobile` on the dashboard side which just strips the `after_` prefix from the `--story-filter`, so that the filter matches both the foreground-background parts of the "story". Will prepare a CL for that, where we can comment whether the temporary fix would be acceptable.

**Comment by eakuefner** [comment]
Can this bug be closed? If not, what remains to be done, and can we bump the milestone?

**Comment by perezju** [comment]
I think there is nothing else to do in the short term (so closing), but I guess this is something to keep in mind while designing the new pipeline to get data from benchmarks to the dashboard.

**Comment by perezju** [comment]
Re-opening because I just noted that bisects auto-started during triage when filing a new bug do not use the story filter. I'll try to get this fixed too.

Relevant source code pointers for that flow:
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/file_bug.py#L154
