### ISSUE TITLE
Requests to /graph_json time out for CT graphs.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1815]
To reproduce, navigate to:
https://chromeperf.appspot.com/report?sid=8a67e3494ee82b98349fa0b496169a043935cbc98503d282706b6ec33a628180

Expected: graph for rasterize_time, with sibling series (record_time etc.) listed in the legend. No errors.
Actual: Warning message "Failed to fetch graph data." No sibling series shown in the legend.

The request to /graph_json for the non-selected series  is timing out; maybe this is happening for this tests but not others because the number of points for the CT tests is relatively high, or the rate of adding new points is relatively high.

Related tests:
https://chromeperf.appspot.com/new_points?pattern=ChromiumPerfFyi%2FLinux+CT+Top1K+RR+Perf%2F*%2F*&num_points=100&max_tests=10

**Comment by qyearsley** [comment]
I just realized that the request to graph_json which is timing out (the request for data for unselected series) may be timing out because for these particular tests, the number of subtests is > 100. For most of the data on the dashboard, there are < 30 items.

In the request for all the data for all unselected series, it's fetching the past 150 points for each of the subseries and timing out.

We may want to add a special case in graph_json to just abort and return nothing in this case (if we're getting data for unselected series and there are more than 100 series to get data for).

**Comment by qyearsley** [comment]
@anniesullie @chrisphn Can you think of any solution for this besides just having /graph_json return nothing when there are too many unselected series to get data for? I think that this would mean that just the average/summary series would be shown in the legend in this case, which I think would be OK.

**Comment by chrisphn** [comment]
- Parallelize fetching points
- Not fetch points for unselected series (do it on checking series in chart-legend)
- Multiple requests, fetch chunk of series at a time  (more work)

**Comment by qyearsley** [comment]
It still takes some time to load the data from /graph_revisions for the revision slider, but now navigating to https://chromeperf.appspot.com/report?sid=8a67e3494ee82b98349fa0b496169a043935cbc98503d282706b6ec33a628180 no longer tries to load all of the subtest series.

I filed #1876 as a follow-up to improve the handling of cases like this.
