### ISSUE TITLE
Write case study for "Closing a message with inbox [with and without Roboto enabled]"

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1817]
Closing a message with inbox [with and without Roboto enabled] is a great A/B test for RAILscore being comparable. This bug tracks us trying to use this case to dogfood railscoring.

To do this, we should probably reach out to jeff yuen for a fresh trace pair. Our existing traces have broken input events. Once we have that, we can study the interesting sub-region of the trace and see if the scores that we compute reflect the conclusion that:
- efficiency decreases by about 5%
- responsiveness is the same

And thus, the final "user perceieved performance" impact of this is probably quite a bit less than 5% --- on the basis that efficiency is mostly about power consumpiton from an upp pov, and responses are quite few so even a heavy but short response is probably trivial.

**Comment by benshayden** [comment]
Not sure if we're performing the correct steps and looking at the correct things.
We open inbox.google.com, wait for it to finish loading, open a thread, open chrome:tracing, start tracing, go back to inbox, hit Escape, go back to chrome:tracing and stop tracing. We're looking at the Response that represents hitting Escape and the CSS Animation that directly follows it. It looks like the Response is correctly identified now, so either Chrome updated with a fix for that or we're looking at a different Response.
Now we are consistently seeing efficiency is significantly higher for the roboto case (0.9) than non-roboto (0.7). The comfort in the roboto case is 0.9, versus 1.0 in the non-roboto case.
The real story here seems to be the animation comfort: 0.27 in both cases.

What else should we do with this?

**Comment by natduca** [comment]
That is awesome. Opportunistically, I think what we should do is turn this into a case study. 

For the short term, can you maybe attach the two traces to this bug?

Then, can you schedule a meeting for us to write a case study doc about this together? I think schedule it +4wks out... its not urgent, and its useful for us to do, but its not urgent.

**Comment by benshayden** [comment]
I put a note on my calendar to get ready to do this at the rail-party on 29 Feb. SG?

**Comment by natduca** [comment]
Awesome!

**Comment by benshayden** [comment]
I think we've gotten everything out of this that we realistically expect to?
