### ISSUE TITLE
Attribute video work to video Animation IRs

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1820]
Currently, video playback is not represented as an Animation IR. Ideally, the web media player would trace an async event delineating when video starts and stops. Ideally, flow events would associate thread slices to those async events, similar to how InputLatencyAsyncSlices uses flow events.

@natduca Who should I talk to about tracing web media?

**Comment by natduca** [comment]
When the time comes to move this forward, we'll probably want to talk to @dglazkov to figure out who the right contacts are. As I understand it, the main issue is that there are a few...
