### ISSUE TITLE
Try job status is not updated for incomplete bisect jobs.

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#1821]
There are instances where bisect try job failed due to timeout on job queues or because of invalid buildbucket configs.

UnexpectedJsonError: No "url" in try job results. This could mean that the job has not started. Buildbucket response: {"status": "COMPLETED", "cancelation_reason": "TIMEOUT", "bucket": "master.tryserver.chromium.perf", "result_details_json": "null", "status_changed_ts": "1447542963203900", "created_ts": "1447456505122540", "created_by": "user:425761728072-pa1bs18esuhp2cp2qfa1u9vb6p1v6kfu@developer.gserviceaccount.com", "result": "CANCELED", "utcnow_ts": "1449100393490540", "parameters_json": "{\"builder_name\": \"linux_perf_bisector\", \"properties\": {\"bisect_config\": {\"bad_revision\": \"348852\", \"bug_id\": 532512, \"builder_host\": null, \"builder_port\": null, \"command\": \"python src/tools/perf/run_benchmark -v --browser=release_x64 --output-format=chartjson --also-run-disabled-tests blink_perf.shadow_dom\", \"good_revision\": \"348842\", \"gs_bucket\": \"chrome-perf\", \"max_time_minutes\": \"20\", \"metric\": \"LargeDistributionWithoutLayout/LargeDistributionWithoutLayout\", \"recipe_tester_name\": \"winx64ati_perf_bisect\", \"repeat_count\": \"20\", \"required_initial_confidence\": \"0\", \"test_type\": \"perf\"}}}", "id": "9029225563643562496", "updated_ts": "1447542963204000"}

UnexpectedJsonError: No "url" in try job results. This could mean that the job has not started. Buildbucket response: {"status": "COMPLETED", "created_ts": "1447456505648890", "completed_ts": "1447456514863320", "bucket": "master.tryserver.chromium.perf", "result_details_json": "{\"error\": {\"message\": \"builder_name parameter is not set\"}}", "status_changed_ts": "1447456514863300", "created_by": "user:425761728072-pa1bs18esuhp2cp2qfa1u9vb6p1v6kfu@developer.gserviceaccount.com", "failure_reason": "INVALID_BUILD_DEFINITION", "result": "FAILURE", "utcnow_ts": "1449100393682020", "parameters_json": "{\"builder_name\": null, \"properties\": {\"bisect_config\": {\"bad_revision\": \"338459\", \"bug_id\": 509617, \"builder_host\": null, \"builder_port\": null, \"command\": \"src/tools/perf/run_benchmark -v --browser=android-chromium --output-format=chartjson --also-run-disabled-tests smoothness.tough_canvas_cases\", \"good_revision\": \"338445\", \"gs_bucket\": \"chrome-perf\", \"max_time_minutes\": \"20\", \"metric\": \"CanvasAnimation-jank_count_http___www.effectgames.com_demos_canvascycle_/CanvasAnimation-jank_count_http___www.effectgames.com_demos_canvascycle_\", \"recipe_tester_name\": \"android_one_perf_bisect\", \"repeat_count\": \"20\", \"test_type\": \"perf\"}}}", "id": "9029225563091310400", "updated_ts": "1447456514863430"}

**Comment by petrcermak** [comment]
This is already being tracked in a [Chromium bug](https://crbug.com/564208).
