### ISSUE TITLE
Compare RAIL scores for wikipedia cats vs tedx

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1824]
This would be a good dogfood test case.
Do the differences between the scores for fullscreen mode and windowed mode look right?

**Comment by fmeawad** [comment]
Can you provide the links?

**Comment by benshayden** [comment]
https://en.wikipedia.org/wiki/Cat
http://tedxguc.com/
Tedxguc has a parallax scrolling effect that can sometimes be janky, though it seems pretty smooth to me now. Could be because I turned on smooth scrolling.
