### ISSUE TITLE
Send the full command used to run the test to the dashboard, and use this for bisects.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1825]
From perezju in https://code.google.com/p/chromium/issues/detail?id=561992:

> The real solution, it seems to me, is---starting from Telemetry, via the perf dahsboards, and up to the bisect bots---to record and keep track of the full command that was used to run the test.

Right now the dashboard guesses what command to use based on the benchmark name on the dashboard, but there's no guarantee that that's the right command.

Some issues to consider:
 - Extra options are added to the command by the dashboard, e.g. --also-run-disabled-tests. Also, currently, the --output-format option used on Telemetry commands changes depending on whether we're using legacy bisect or recipe bisect.
 - The dashboard guess commands for other tests besides Telemetry -- we'd probably want the test runner (i.e. build/scripts/slave/runtest.py) to add the command info.

**Comment by anniesullie** [comment]
We actually don't want the recipe to need to do any configuration, the test should be run with default args.
