### ISSUE TITLE
Find and categorize RAIL IRs for alternative input devices

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1827]
Do gamepads go through the InputLatencyInfo system? It doesn't look like it, but I need to check.

What about Leap Motion?

If these devices are polled by javascript timers or rAF, then it would make sense to categorize them as JSInterval or JSAnimation Animations and maybe Responses. Otherwise, there may be a patch to LatencyInfo in order.

**Comment by natduca** [comment]
You could ask @bajones or @scheib... probably not.

**Comment by benshayden** [comment]
Honestly, I probably won't get to this until something forces me to: WontFix.
