### ISSUE TITLE
[Unconfirmed] Bisect dialog may sometimes fill in bug ID with an incorrect value. 

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1829]
A couple people have started bisects with the wrong bug number:
https://code.google.com/p/chromium/issues/detail?id=538367#c4
https://code.google.com/p/chromium/issues/detail?id=564323#c7

It's possible that there's a bug with the bisect form?

**Comment by anniesullie** [comment]
Haven't seen this lately, hopefully we'll open a new bug with some debugging info if this happens again.
