### ISSUE TITLE
Catapult CQ not working

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1832]
I ticked the "Commit" box on my [patch](https://codereview.chromium.org/1479253002/) ~100 minutes ago, but __all trybots are still [gray](https://chromium-cq-status.appspot.com/patch-status/1479253002/1)__. The most recent Catapult patch (bae6aa5f) landed on Friday (3 days ago).

**Comment by anniesullie** [comment]
I'm tracking this on the chrome infra side in crbug.com/567180

**Comment by petrcermak** [comment]
Thanks!
