### ISSUE TITLE
What is catapult/base directory is used for?

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1837]
I thought the base/ directory is used as a place store library that are used across telemetry projects, e.g: cloud_storage.py (https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/catapult_base/cloud_storage.py), dependency_manager...

But seems like it now contains util/perfbot_stats, which I am not sure is used by any other top level projects? I think perfbot_stats/ should be moved to catapult/experimental/

@natduca @anniesullie @qyearsley @Apeliotes

**Comment by anniesullie** [comment]
The perfbot_stats are used in a "production" type context--they run a nightly cron job to upload stats to the perf dashboard about success rates, and they have unit tests. I think "experimental" isn't a great fit, maybe "scripts"?

**Comment by natduca** [comment]
Yeah, I'm not so clear what base is now. Though, there's js stuff in tracing/tracing/base that could easily go into base/base...

**Comment by nedn** [comment]
Nat: what you says make sense.

Assign the bug to Ethan to move perfbot_stats to scripts/

**Comment by eakuefner** [comment]
The perfbot_stats move has been done by @nedn, and the state of the art in Catapult project structure is being tracked in #1972 so this bug is very stale. Closing.
