### ISSUE TITLE
No quick-log messages are posted for cancelled (timed-out) buildbucket bisect jobs.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1844]
Example: For the perf regression bug [538367](https://chromeperf.appspot.com/group_report?bug_id=538367), there were several bisect jobs started which ended up being cancelled (buildbucket says timed out), but no message was put into the quick-log at https://chromeperf.appspot.com/group_report?bug_id=538367.

**Comment by benshayden** [comment]
Archiving.
