### ISSUE TITLE
Object.observe is undefined, traceviewer broken

### ISSUE THREAD

**Issue by paulirish** [catapult-project/catapult#1848]
Upstream bug: [Issue 569417 - chromium - Catapult doesn&apos;t work on 49.0.2590 canary because Object.observer is disabled by V8](https://code.google.com/p/chromium/issues/detail?id=569417)

![image](https://cloud.githubusercontent.com/assets/39191/11790606/88d76834-a251-11e5-9121-3e38f95c61d7.png)

Why? v8 [disabled O.o on friday](https://chromium.googlesource.com/v8/v8/+/ebdd90142b7de7696979c27f2286128dfad7c259).

While Polymer has some internal uses of this, those are safely behind feature detects. We have one exposed use that throws the exception; it's here: https://github.com/catapult-project/catapult/blob/6f514e152dc3a42da19025f3ba4c88d78ee39560/tracing/tracing/ui/base/polymer_utils.html#L17

This is a P0, who can take a look?

**Comment by natduca** [comment]
I'll try to figure this out.

**Comment by natduca** [comment]
https://codereview.chromium.org/1526863002 in flight

**Comment by natduca** [comment]
Fixed on this side. Will do deps roll and fix crbug
