### ISSUE TITLE
In bisect FYI failure emails, give a link to the logs.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1853]
Suggested by Annie:
When checking a bisect FYI result (https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/bisect_fyi.py#L130), get the env var `REQUEST_LOG_ID` (see https://cloud.google.com/appengine/docs/python/requests#Python_The_environment) and use it to make a link to the log for that request, e.g. something like `.../logs?project=chromeperf&label:appengine.googleapis.com%2Frequest_id:<request-id>`

This may make debugging issues faster.

@vuppalapu @anniesullie

**Comment by anniesullie** [comment]
The link to the build is already there.
