### ISSUE TITLE
Use pep8 on presubmit and suggest auto-fixing with autopep8.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1854]
[pep8](https://pypi.python.org/pypi/pep8) is a tool similar to pylint, but by default it's a bit stricter and sometimes it complains about different things.

[autopep8](https://pypi.python.org/pypi/autopep8) is a tool that automatically reformats Python code to conform to pep8.

We could put these in catapult, run pep8 to check some things that pylint doesn't catch that pep8 does, and if it catches anything, we can prompt the user whether they're OK with running autopep8 to auto-fix that particular formatting issue.

**Comment by nedn** [comment]
+1

**Comment by natduca** [comment]
My only $0.02 is that where possible, we shoudl follow the lead of the chrome infra team. They were the ones that have linting in depot tools, so we just built on top of their leadership. If we go this route, are we striking out on our own... or are we tryign to get overall infra moving this way? Lets make an excellent choice that includes us contemplating the multi-year consequences of our local decisions.

**Comment by nedn** [comment]
@dpranke : do you think it's possible to put pep8 support in depot_tools/ ?

**Comment by dpranke** [comment]
I think we could put *something* into depot_tools, but I would probably recommend we use [yapf](https://github.com/google/yapf]) instead of autopep8 .

git-cl actually already has optional support for yapf but doesn't preinstall it IIUC.

(I used to be a fan of autopep8, and in fact lint-webkitpy uses it, but I think yapf is supposed to produce better results. I haven't stared at the diffs enough to have a good opinion there, though).

**Comment by qyearsley** [comment]
Ooh, neat, there's a `git cl format` that formats Python code, and that's been there for 6 months! (https://codereview.chromium.org/1156743008/)

So I just installed yapf (by running `pip install --user yapf` and adding `$HOME/.local/bin` to my path) and yapf --style=chromium --in-place works well (default behavior looks a little better than autopep8). Example: https://codereview.chromium.org/1536633003/

I tried `git cl format --full --python` but for some reason it didn't use chromium style so it indented four spaces. This probably needs to be fixed.

The canned presubmit check
[CheckPatchFormatted](https://code.google.com/p/chromium/codesearch#chromium/tools/depot_tools/presubmit_canned_checks.py&l=1094) looks like what we want -- we just have to make sure that git cl format works as we want, and until yapf is bundled with depot_tools, it would be possible to put it in catapult and add it to the path before running presubmits.

**Comment by natduca** [comment]
I tend to think that given that depot tools has attempted this, and continues to have opinions in this space, we should move in step with them, instead of ahead.

**Comment by nedn** [comment]
Is yapf purely python? If it's, would be great if we can preinstalled it in depot_tools

**Comment by dpranke** [comment]
I believe it is, and adding it to depot_tools seems reasonable to me.

**Comment by qyearsley** [comment]
I filed a couple bugs related to git cl format:

https://code.google.com/p/chromium/issues/detail?id=571669
https://code.google.com/p/chromium/issues/detail?id=571670

If those are fixed, then we can add a presubmit to check formatting and suggest users run git cl format. Meanwhile, I don't think we're planning to add/use pep8/autopep8 in catapult now.
