### ISSUE TITLE
Bug: for/in appears to be used on an array

### ISSUE THREAD

**Issue by bolinfest** [catapult-project/catapult#1857]
See https://github.com/catapult-project/catapult/blob/2091404475cbba9b786442979b6ec631305275a6/tracing/tracing/model/process.html#L129

In `shiftTimestampsForward`, `instantEvents` is iterated using for/in instead of for/of or a traditional for loop.

**Comment by lpy** [comment]
Closed as fixed.

CL: https://codereview.chromium.org/1538033002/

Thank you.
