### ISSUE TITLE
Modify timing.html to support hierarchy and arguments

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1858]
We would like timing.html to support the proposed convention of hierarchy & arguments in user timing.

This will allow us to trace the hierarchy of import step and have that show up in tools. And, it will allow us to see information about why a step runs long, e.g. how many events were being processed.

The doc describing the convention for hierarchy & arguments is here: https://docs.google.com/document/d/1-44PszmhQ0-M6Sf2dZpVu-9jAOa7w2_vKAKckRWXJms/edit#heading=h.jfcxhinll4ju

**Comment by natduca** [comment]
@lpy want to self-assign?

**Comment by lpy** [comment]
Closed as fixed.

CL: https://codereview.chromium.org/1538353003/
