### ISSUE TITLE
Update bugs with a failure message if the bisect has already failed many times.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1860]
The auto_bisect cron job retries bisect jobs a limited number of times, and then give up and deletes the TryJob entity. When it does this, it could also send a request to update the bug with a message saying that bisect failed N times -- this would make people aware that bisect is not working, while hopefully not being too spammy.

@vuppalapu @anniesullie @dave-2 @chrisphn

**Comment by benshayden** [comment]
This looks done.
