### ISSUE TITLE
Remove and vacuum unused indices from perf dashboard

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1863]
We'd like to clean up unused indices, but there's not a great way to figure out whether they are actually in use. So Quinten did a scan through all of them and tried to map them to code and noted which ones are likely unused in https://codereview.chromium.org/1534943002/ and we are going to try to remove and vacuum one by one during the holiday downtime.

@qyearsley

**Comment by qyearsley** [comment]
A lot fewer indexes, especially Row indexes!
https://pantheon.corp.google.com/datastore/indexes?project=chromeperf

Cost per day a couple weeks ago: $194.29
Cost per day yesterday: $148.94

$46 per day over a year is $16790 :-D

**Comment by anniesullie** [comment]
Marking fixed
