### ISSUE TITLE
Perf dashboard should use app engine modules

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1864]
This would allow us to tune scaling and hardware for frontend/backend separately. Doc: https://docs.google.com/document/d/1AX5cLwHwkj3hHTrYI_Sl0Khtz-bGav2XxdVA4eQQMjY/edit#

Hopefully this would help with both:
   * Getting the backend running managed VMs so that we can use scipy in alerting
   * Reducing costs and allowing us to tweak scaling better for per-page alerting

@dave-2 @qyearsley @chrisphn

**Comment by qyearsley** [comment]
Scaling up hardware for back-end (add_point_queue in particular) might help with #1424 

(add_point_queue requests sometimes get aborted after waiting to be executed; [this stackoverflow page](http://stackoverflow.com/questions/2463916/google-app-engine-request-was-aborted-after-waiting-too-long-to-attempt-to-ser) suggests that this can be avoided by making sure there are always enough instances to handle the load.)

**Comment by qyearsley** [comment]
Notes about how the directory structure might be reorganized: https://docs.google.com/document/d/1UEkGJCkWoweu5rt55kyg2WA9PcSTaTB9ciMpUyMHX8s/edit

**Comment by qyearsley** [comment]
@anniesullie, could you take a quick look at that doc about how the directory layout might be changed? Basically, as we talked about before, it might be separate it into "backend" (add_point and everything related), "bisect" (everything related to bisect jobs) and "frontend" (everything else). Some code would need to be shared between these modules, including data models and utility code.

**Comment by anniesullie** [comment]
It would be awesome to see the individual .py files binned into categories. I think there are some code categories missing, like it seems that bug triage should be a module.

**Comment by qyearsley** [comment]
Possibly, although bug triage is of course closely related to viewing graphs, in general -- when deciding whether to file a bug and whether it's recovered, you also have to see graphs.

In the future dashboard, alerts to triage will probably also have bisect results associated with them; we'll still want to view graphs (and bisect results) while filing bugs.

Just modified the doc to list out a first draft at where all of the current .py files would belong.
