### ISSUE TITLE
Add a handler for updating and processing TryJob entities.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1870]
As part of the plan to post bisect results directly to the dashboard (doc: https://docs.google.com/document/d/1ImzqOIWbmkyQV03aWGrrXZ7lOoXDyet0m6WQZW38dag/edit#), we want to add a handler to fetch TryJob entities, check their status, log failures and delete finished TryJob entities.

**Comment by qyearsley** [comment]
Related to #1869

**Comment by qyearsley** [comment]
Chris, after your change, we're not using Buildbucket to check job statuses/failures -- is it the case that we're waiting for results to be posted, and if there are no results posted after some time, then we assume failure?

Or would it still be good to make requests to Buildbucket to confirm failures?

**Comment by chrisphn** [comment]
I think it should assume that it's a failure if bisect bot can't make it to the last step.  There's no useful info to get from Buildbucket at that point.

**Comment by qyearsley** [comment]
SG, so we're not planning to make more changes to get statuses from Buildbucket etc.; OK to close this bug?

**Comment by chrisphn** [comment]
Sure.
