### ISSUE TITLE
De-jinjafy perf dashboard

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1871]
I [wrote a doc](https://docs.google.com/document/d/1skt9ed6RBGrhQzMeVjK2BFs07qq6qVJhAiiNB4ZrnJM/edit#heading=h.ig6zvd3dkk6e) on the things that would need to happen here.

#1710 and #1325 are blocking.

@qyearsley @chrisphn

**Comment by qyearsley** [comment]
(Second blocking bug should be #1329)

**Comment by anniesullie** [comment]
At this point, the major pages are de-jinjafied, but there are still a lot of smaller endpoints using jinja, the most major of which is `main`. Two thoughts on direction at this point

  1. I think we should simplify `main` by removing the bug list from it, since it's not clear which account to get that list from and no one has complained since the monorail migration.
  2. We have a lot of endpoints where there is a `GET` request to a mostly static file and then a `POST` request which fills in a separate jinja template as a response. I think we should switch it so the results template is in polymer in the same template as the `GET` request, and we make an XHR instead of a `POST` to a separate endpoint. As part of this, we may end up making a polymer element that does the same thing as `results.html`.

Do those sound reasonable? If so, I'll work on this in the background.

@chrisphn let me know if the timing of working on smaller elements later this week and throughout next week conflicts with the polymer 1.0 update.

**Comment by qyearsley** [comment]
1. I also agree on removing the bug list from main. Two more reasons:
 - it slows down requests to "/"
 - I usually don't use it; if I want to see the recent bugs I view it on the issue tracker site itself

2. Sounds reasonable, I also think that's a good idea.

**Comment by anniesullie** [comment]
Great. I'll look into making these changes late this week or next, assuming it doesn't cause problems for polymer 1.0 conversion.
