### ISSUE TITLE
group_report/?rev= broken; need to re-add index for Anomaly entities.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1873]
We removed one too many indexes in https://codereview.chromium.org/1554653003.

To reproduce: Open https://chromeperf.appspot.com/group_report?rev=359864 in an incognito window.

Visiting that page when logged out yields a NeedsIndexError:
The suggested index for this query is:
- kind: Anomaly
  properties:
  - name: internal_only
  - name: end_revision

**Comment by anniesullie** [comment]
Thanks for taking this, Quinten! Adding indexes for anything except Row entities should be fine (Row takes at least 10x more than anything else)

**Comment by qyearsley** [comment]
NP :-) Just made CL https://codereview.chromium.org/1560433004
