### ISSUE TITLE
Add a "bad result" link in bisect results.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1874]
Problem: It's difficult to get "correctness/accuracy" statistics about bisect jobs.

Proposal: Add a link which people can click in bisect results which posts a message to the dashboard.

Subtasks:
 * Modify TryJob model
 * Make a handler which takes a TryJob id and changes the entity
 * Change the results posting code to post a link

@dave-2 @chrisphn @ro-berto @vuppalapu

**Comment by qyearsley** [comment]
https://codereview.chromium.org/1666793002/

**Comment by chrisphn** [comment]
Last CL for this is here: https://chromiumcodereview-hr.appspot.com/1812113002/

**Comment by chrisphn** [comment]
I do see the link attached in the bisect report.

List of marked bad bisect can be viewed here (non atm):
https://chromeperf.appspot.com/get_logs?namespace=bad_bisect&name=report

**Comment by qyearsley** [comment]
Excellent :-) I hope this is useful.
