### ISSUE TITLE
Bisect shouldn't assign bugs when results are "Status: Negative"

### ISSUE THREAD

**Issue by randomascii** [catapult-project/catapult#1875]
When looking at crbug.com/525243 I found the results confusing. There were three bisects that succeeded enough to assign the bug to a suspect CL and its author. However in all three of those cases the message included:

    ===== BISECT JOB RESULTS =====
    Status: Negative: Completed, but no culprit was found with high confidence.

This seems contradictory and confusing to me. I think it would help with parsing the results if "Status: Negative" was not included if the bisect succeeded enough to assign the bug to someone.

I don't know if the problem is that the status is displayed incorrectly or if the problems is that the bug is assigned when the bisect results were negative, but I think the contradiction should be resolved in some way.

**Comment by qyearsley** [comment]
You're right, no owner should be assigned when no culprit was found with high confidence (such as in that case on Dec 25).

There may be a bug in https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/update_bug_with_results.py#L475. The last change in related code was https://codereview.chromium.org/1531533003; that CL might have introduced a bug.

**Comment by randomascii** [comment]
That could be it. The other two times this happened on that bug were Dec 18, see comment 21 and 23. The suspect CL you mention was Dec 16, so the dates make sense.

**Comment by qyearsley** [comment]
Added a test to confirm that the behavior there was wrong then fixed it in the above CL; this shouldn't happen any more.
