### ISSUE TITLE
Disable "Bisect" button on bisect form for un-supported masters on dashboard.

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#1882]
We notice some failures on linux_perf_bisect bots since the bisect config was not complete and also was executing legacy bisect which is now deprecated for linux bisect.
Eg: https://build.chromium.org/p/tryserver.chromium.perf/builders/linux_perf_bisect/builds/5266

The main cause for this is because we where trying to bisect on the perf master on dashboard that doesn't support bisect yet or the bisect form is not completely filled. eg: 
https://chromeperf.appspot.com/report?sid=5d6caa5afe939dae04d5f5b8f829e77ea92e948e931be913311fc724c1249c9f&rev=305568

**Comment by qyearsley** [comment]
Ah, didn't know we didn't check master.

Well, we have a blacklist of bisectable test suites, we could either have a whitelist of bisectable masters and check it here: https://github.com/catapult-project/catapult/blob/5bb87c077c8030b35fa344d553ddd7d41b49ba71/dashboard/dashboard/auto_bisect.py#L142

**Comment by qyearsley** [comment]
Just realized that if we want to prevent bisecting through the front-end, https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/static/bisect_utils.html has been the place to do it. But we don't want to have internal master names in that list, so directly listing all supported masters including internal masters won't be very good.

**Comment by qyearsley** [comment]
So, since master names can be internal only, it seems the only way to solve this without putting master names in the code is by storing them in the datastore. There's a list of supported masters already in datastore (the keys of https://chromeperf.appspot.com/edit_site_config?key=bisect_bot_map).

**Comment by qyearsley** [comment]
So I think I want to disable bisecting from the front-end (in https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/static/bisect_utils.html) but there's not currently a way to directly fetch stuff from stored_object or namespaced_stored_object with an XHR.

I think I'd like to add an endpoint to fetch stored objects from datastore as JSON. @chrisphn or @anniesullie, do you see any disadvantages with doing that?

**Comment by qyearsley** [comment]
Deployed and confirmed
