### ISSUE TITLE
Move web-page-replay to catapult/

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1891]

**Comment by natduca** [comment]
Is this a good idea? In general, if we have a system that has a clearly defined interface, it doesn't necessarily jump out to me that we should move it into catapult/tools. The main reason to unify is when we need to radaically change/merge/blur a module between other catapult core components... 

In general, i think we should be aspiring to kick out our own well defined components to other catapult-project git repos that we roll into catapult. That may not happen right now, but I think we should resist the temptation to become a single monolith, at least not without some reason to do so.

@anniesullie

**Comment by anniesullie** [comment]
What's the reasoning for moving WPR to catapult?

**Comment by nedn** [comment]
Moving web-page-replay to catapult as a top level project and having telemetry's using directly will add an extra layer of integration tests for web-page-replay as every commits of catapult run telemetry_unittests. catapult/ also provide a great infrastructure for running test on multi-platforms, unlike the travis-ci that I set up for web-page-replay only run on linux.

I think there is a dichotomy between how do we land code safely & effectively (which is solved by monolithic repo) & how do we make sure that customers of individual projects have what they need without pulling the giant repo (by having individual repo).

Here is my proposal for getting the best of both worlds:
1) Make https://github.com/chromium/web-page-replay a mirror of catapult/web-page-replay
2) Catapult CQ test of web-page-replay uses isolated-testing to ensure that all web-page-replay tests pass with only files in web-page-replay/

**Comment by natduca** [comment]
This smells funny. Can we leave this be and discuss our multi-repo/test strategy in Q2? Or is there a reason this is urgent?

**Comment by nedn** [comment]
I plan to spend more work in WPR to fix its various issues in Q2 that has been punted in the past. A major problem with WPR has been it being in separate repo & do not have great testing support. Any change to wep-page-play risks breaking telemetry & only discovered once we roll WPR to telemetry/third_party, which slows down patch works significantly.

**Comment by natduca** [comment]
But maybe the right thing is us figuring out how to stand up a watefall of the quality of catapult, but for other repos.

**Comment by anniesullie** [comment]
I can help set up a CQ for WPR if we think that's the right thing to do.

**Comment by eakuefner** [comment]
Archiving this bug.
