### ISSUE TITLE
Allow a per-sheriff set of users to edit sheriff configs.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1892]
Background: Every time someone wants to edit the set of tests that they're monitoring they have to file a bug or send an email to the perf dashboard team to do it, because chromeperf.appspot.com/edit_sheriffs is an admin-only page, because we don't want random users to be changing sheriff configs.

But for some people who care about monitoring their data themselves, this process is more cumbersome than it could be.

Proposal:
 * Change the Sheriff model to include a list of owners (email addresses).
 * Make the edit_sheriffs page non-admin, but *only* list the Sheriff entities that the current user is an owner of (and list all if the current user is an admin).
 * Also allow anyone to create new sheriff rotations and set the owner by default to be the creator of the rotation.

This would make it easier in the future for other groups and teams to take control of monitoring different sets of tests.

@anniesullie How does this sound? I put it as P3 because the current process of filing a bug to request monitoring is working OK and I don't remember anyone expressing that they feel it's too inconvenient.

**Comment by anniesullie** [comment]
I'm working on the first part in crbug.com/575318

For the second and third part, maybe it makes sense to also directly configure monitoring in telemetry? @nedn @eakuefner I think have talked with me about this at various points too

**Comment by qyearsley** [comment]
We mentioned this a couple times in the last week -- in the original bug I was thinking of just allowing people to access /edit_sheriffs but still have monitoring configured via dashboard, but the approach of crbug.com/575318 is to allow benchmark owners to specify monitoring in the benchmark code itself; if this can be done, then it may be unnecessary to allow non-admins to access /edit_sheriffs, and the list of monitored benchmarks per sheriff could generally be a list of benchmark names "*/*/my.benchmark/*/*" which is updated when /add_point receives new data with metadata about benchmark monitoring.

But these things aren't mutually exclusive; we could potentially both allow some users to access /edit_sheriffs, and accept monitoring updates via /add_point.
