### ISSUE TITLE
Use Base64.atob and Base64.btoa, get rid of window.atob and window.btoa

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#1895]
We currently use window.atob and window.btoa to decode and encode between string and base64 for converting arguments of user timing. But when we are using mapper, we don't have atob and btoa, which means we can't extract arguments, but arguments are important and we want it.

See the code here:
https://github.com/catapult-project/catapult/blob/master/tracing/tracing/base/timing.html#L22

https://github.com/catapult-project/catapult/blob/master/tracing/tracing/extras/importer/trace_event_importer.html#L1067

**Comment by natduca** [comment]
hmm I think maybe d8's polyfill does this?

**Comment by nedn** [comment]
@lpy With the polyfill route, you can add those methods here: https://github.com/catapult-project/catapult/blob/master/third_party/vinn/vinn/d8_bootstrap.js#L65

**Comment by lpy** [comment]
OK. I find `atob` in vinn: https://github.com/catapult-project/catapult/blob/master/third_party/vinn/vinn/d8_bootstrap.js#L149

@nedn looks like this is what we want? I think we can just get rid of `window.` prefix in code.

**Comment by nedn** [comment]
sgtm

**Comment by lpy** [comment]
Closed as fixed.

CL: https://codereview.chromium.org/1592853002/
