### ISSUE TITLE
MemoryInfra diff view depends on selection order

### ISSUE THREAD

**Issue by ruud-v-a** [catapult-project/catapult#1899]
When selecting two memory dumps, the sign of the differences depends on the order of selection. According to @petrcermak’s comment in https://crrev.com/1598393004, this is a bug, not a feature.

Version: dc74f19

**Comment by petrcermak** [comment]
Fix pending: https://codereview.chromium.org/1637943002/

**Comment by petrcermak** [comment]
This is now __fixed__.
