### ISSUE TITLE
Should we use safe process IDs?

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1900]
Real process IDs are not (should not be) revealed to the child processes for security reasons. So, if we ever need to reference an object from another child process (in a child process) we cannot use the ref_pid mechanism proposed in the [Multi-process Object Refrences](https://docs.google.com/document/d/1e7vTbGW9EvCyMKwor7v4Q9G_5ahAjiCxp1x_pr4NQAQ/edit#) doc.

Will we need this feature? Can we use tracing process IDs instead (no security concern in passing around tracing PIDs)? How?

Please discuss in the [SPID vs PID](https://docs.google.com/document/d/17zKWtXI1Q-BNLr-RiGqz-KthoKwnk4qmQKUvYEr3mjw/edit#heading=h.cos8nk4kffcs) doc.

**Comment by benshayden** [comment]
@chiniforooshan Any update?
