### ISSUE TITLE
Memory Results are under "Time", time results are under "Memory" in results html output

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#1901]
Here is the chromium bug filed: https://code.google.com/p/chromium/issues/detail?id=576945

Here is the problem: http://storage.googleapis.com/chromium-telemetry/html-results/results-2016-01-12_13-54-45 If you click on "Time", then you get memory results and vice versa.

**Comment by chromy** [comment]
I'm going to close because I think this is fixed now? :)
