### ISSUE TITLE
Blank import dialog

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1911]
The import doesn't show any messages:

![screenshot from 2016-01-22 11 36 36](https://cloud.githubusercontent.com/assets/2546601/12509738/7a974acc-c0fc-11e5-91f4-eae4d996d868.png)

**Comment by petrcermak** [comment]
I manually bisected the issue and found that it was caused by 24f62dd8e7f2c7bf38bc32fb588ba24080487c0a _(Reland: Use requestIdleCallback to schedule idle work if available)_, so I'm assigning this to @skyostil.

**Comment by skyostil** [comment]
Fix here: https://codereview.chromium.org/1636453003/
