### ISSUE TITLE
Put a warning in the bisect form when the revision range is huge.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1912]
When a test fails to run for some time and then runs again, the dashboard sometimes creates an alert with a revision range of 1000+ revisions; in this case, bisect is rarely successful and generally times out.

It may be helpful to add a warning to users in this case, so that they know that they'll likely only get partial results, and if possible it would be helpful to try looking at the graph of another bot.

This would be a change in dashboard/elements/bisect-form.html.

@vuppalapu

**Comment by SasankYadati** [comment]
I would like to take this up!

**Comment by bhavybarca** [comment]
@qyearsley so basically i need to add a warning code to the part when the bisect begins and the warning should say something like"likely to get only partial results while using bisect".
did i got it right?
P.S. i am a beginner

**Comment by simonhatch** [comment]
I think we can actually close this, recipe bisect is deprecated and Pinpoint is more robust to these kind of problems.

**Comment by bhavybarca** [comment]
@simonhatch anything else i can do as a beginner to contribute

**Comment by simonhatch** [comment]
I can probably dig up a bug for you, do you have any specific area you'd like to work on? Dashboard, bisect, telemetry, etc.?

**Comment by bhavybarca** [comment]
@simonhatch thanks a lot, i can code in golang and python so webpage relay or dashboard but i am juat beginning so no fixed preference.

**Comment by simonhatch** [comment]
https://github.com/catapult-project/catapult/issues/2829
https://github.com/catapult-project/catapult/issues/4255

Here are 2 that you can look into if you're interested, otherwise I'd just browse anything in https://github.com/catapult-project/catapult/labels/Good%20First%20Bug
