### ISSUE TITLE
RAILIRFinder is too big

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1920]
Some parts of the RAILIRFinder are entirely separable.
Startup Load IRs
Rendering Load IRs
Input (most Response and Animation IRs)
CSS Animation IRs

Names and file structure all up for debate, but here's a straw man:
extras/chrome/rail/rail_ir_finder.html
extras/chrome/rail/input_ir_finder.html
extras/chrome/rail/proto_ir.html
extras/chrome/rail/startup_ir_finder.html
extras/chrome/rail/load_ir_finder.html
extras/chrome/rail/css_ir_finder.html

It seems to me that maybe System Health or whatever name should describe the scoring, which should move out of the RAILIR subclasses, and RAIL is an apt name for the IRs and IR finders.

It also seems awkward for rail/ to be side-by-side with chrome/ and android/ when these IR finders are chrome-specific. Android has some IR finding, but it doesn't look like RAIL. Even if they were to find RAIL IRs, they'd need to use different logic since they'd need to use different trace probes, so it seems like they'd need separate extras/android/rail/ code to find android rail IRs, but IDK.

I'm not sure if the RAIL IR classes should stay in extras/rail/ or move to model/ or extras/chrome/rail/ or what? Or maybe we don't really need them if the scoring code is going to move out of them? Maybe I'm trying to do too much.

**Comment by natduca** [comment]
I think it'd be useful to first tackle the separation of "building our user interaction model"  from "scoring" --- that is going to clarify what an RAIL IR vs IR really is. With that in hand, I think we'll be able to understand better how to structure whatever results.

I could imagine for instance tracing/interaction_model/ or tracing/model/interactions/  as a core concept that contains the IR finder. And model/interaction_record.html with maybe subtypes for user interaction types. Metrics would stay in some other location, though...

In general, I think android not supporting IR finding is more a bug than a feature. IMO we should take whatever is an IR in android side and do something reasonable with it, than trying to continue to support cases where IRs are something other than a "period of time in which a user had a steady and specific expectation."

**Comment by benshayden** [comment]
Sounds good.

Are you thinking that android and chrome should contain the same async trace events (Load, Input, CSS, Video, etc.) so that there is no platform-specific ir finding code (sounds organizationally challenging), or should tracing/model/interactions/ let something like extras/{chrome,android}/interactions/ handle the platform-specific bits?

Metrics in something like tracing/metrics/{responsiveness,battery,memory}/? Or am I getting ahead of myself?

**Comment by natduca** [comment]
Oooh good question! Probably its untenable that we get android and us to agree on actual event names. So we'll need it to be plugggable. But, I'm not sure if that means that it should be so modular as we have importers/ or extras/. I could just imagine the animation_finder for example just looking for both, or having a big if statement in it. The observation I have here is that we're not as sure if/when that we'll make this work for android so adding upfront abstractionss here to distinguish between core and extras is probably 100% pure drag.

**Comment by benshayden** [comment]
Sorry, I got lost. Are you suggesting to just do the tear-off now and not worry about pluggability until later? If so, sgtm.

Ned made a point that mappers are functions and not objects in order to discourage people from glomming state onto them. Maybe that reasoning should apply here, too?
tr.e.rail.findInteractions(model) -> [Interactions]

Is renaming "InteractionRecord{,Finder}" to Interaction{,Finder} a separate bug?

**Comment by natduca** [comment]
Yeah, my point is pluggability later.

But I tend to think we should combine this, and a few other bugs into a single bug that is about "Initial steps in TBMv2, RAIL, Metrics unification." There's too much swirling right now to give precise advise on any of the leaf pieces. I'll have the doc available for review tomorrow mornign, and we can begin duping bugs.

**Comment by benshayden** [comment]
This has morphed into #1940 .
