### ISSUE TITLE
Manual test plan for about:tracing?

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1924]
It looks like the QA team has some kind of manual tests they run on trace-viewer. I know we've had breakages in the past that are hard to test automatically; should we consider trying to get them to adapt a formal manual test plan we write as a stopgap?

@natduca @primiano @petrcermak

**Comment by primiano** [comment]
Yup. Is there a doc / something that explains what do they test today? Maybe we just need to extend their testing scenarios.

**Comment by petrcermak** [comment]
I think that we should test some __basic scenarios__:

* Record a trace on Desktop (large with many categories to see if we OOM)
* Record a trace on Android
* Load a saved trace
* ...

**Comment by anniesullie** [comment]
I pinged Anantha to see if she can help us figure out where it's documented. Agreed with @petrcermak that basic scenarios are the best for manual testing; they seem like a good high-level integration test, so we can do a better job at preventing problems like crbug.com/576292

**Comment by anniesullie** [comment]
I confirmed with the test team that they're just doing ad-hoc testing (trying to cover the feature the best they can without any test plan or documentation). I like @petrcermak's ideas, so I took them and made a draft test plan: https://docs.google.com/a/chromium.org/document/d/1-4myFLT5tV8fkPz8Ffep6LdyCGg2UsI7X7mMPzOkLv0/edit?usp=sharing

Please review and give feedback!

**Comment by anniesullie** [comment]
The test team is going to start using the test plan outlined in our doc.
