### ISSUE TITLE
[Telemetry] Memory timeline metric mistakenly assumes a single renderer

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#1926]
The bit of code to [split a global dump into process dumps](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/web_perf/metrics/memory_timeline.py#L64) by their name, mistakenly assumes that different processes (i.e. with different pids) will have different process names. This is of course not true for renderers, all of which are called `'renderer'`, and that code will just randomly pick one of them to report.

Instead we should group all processes with the same name into a new "global" dump for that kind of processes, so we get aggregated memory usage for _all_ renderer processes

cc: @primiano

**Comment by primiano** [comment]
ouch +@ssiddhartha  +@petrcermak 
I think this is not an issue on Android, but very likely this is screwing up the desktop measurements.

**Comment by perezju** [comment]
Just FYI. I'm already working on a patch to fix this.
