### ISSUE TITLE
Ditch attributes in favor of scalars

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1928]
Once #1883 is resolved, there will be very little difference\* between <tt>tr.model.Attribute</tt> (Memory-Infra-specific) and <tt>tr.b.u.Scalar</tt> (Catapult-wide), so it would make sense to **replace attributes with scalars**.

@eakuefner: FYI

_\* As far as I'm aware, the only real differences are that attributes can be strings (not just scalars) and can have infos (almost phased away by #1883)._

**Comment by petrcermak** [comment]
Now that #1883 has been resolved, we're very close to ditching Memory-Infra-specific attributes. There are three relatively minor issues blocking this:

  1. Unlike generic scalars, __attributes can have [infos](https://github.com/catapult-project/catapult/blob/10686bf964a479dae1d9cf734c73127e1e3ff641/tracing/tracing/model/attribute.html#L26)__. However, this is only used for [warnings regarding the <tt>size</tt> attribute](https://github.com/catapult-project/catapult/blob/10686bf964a479dae1d9cf734c73127e1e3ff641/tracing/tracing/model/global_memory_dump.html#L240), which can easily be moved to the associated <tt>MemoryAllocatorDump</tt> instead.

  2. The __values of attributes can be strings__. However, this feature is [utilized only 3 times in Chromium](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/fetch/Resource.cpp&q=dump%5C-%3Eaddstring&l=773) and none of the 3 cases has units. Therefore, we could simply replace string attributes with plain strings (i.e. <tt>tr.model.ScalarAttribute</tt> → <tt>tr.b.u.Scalar</tt> and <tt>tr.model.StringAttribute</tt> → <tt>string</tt>).

  3. The attributes generated by Chrome have two possible units: <tt>"bytes"</tt> and <tt>"objects"</tt>. While <tt>"bytes"</tt> can easily be mapped to <tt>tr.b.u.Unit.byName.sizeInBytes_smallerIsBetter</tt> (which we [already use for formatting bytes attributes](https://github.com/catapult-project/catapult/blob/10686bf964a479dae1d9cf734c73127e1e3ff641/tracing/tracing/ui/analysis/memory_dump_sub_view_util.html#L711) anyway), __there is no corresponding unit for <tt>"objects"</tt>__. However, given that we [already use it for formatting non-bytes attributes](https://github.com/catapult-project/catapult/blob/10686bf964a479dae1d9cf734c73127e1e3ff641/tracing/tracing/ui/analysis/memory_dump_sub_view_util.html#L711), we could simply map all non-bytes units to <tt>tr.b.u.Unit.byName.unitlessNumber_smallerIsBetter</tt>.

@natduca,@eakuefner: What are your views on this? Are you happy with my proposed solutions?

**Comment by eakuefner** [comment]
Whoa, I totally missed this.

Let's punt on the strings for now if possible, but I support this, and I think we should be focusing on standardizing around `tracing/value/value.html`.

We only have `Scalar` for now in the value system, but my CL https://codereview.chromium.org/1711213002 adds a new notion of 'grouping keys' to the value system, which will support programmable grouping in the long term and which Telemetry will use for merging in the short term (so you'll be able to record dump IDs as a grouping key).

I think it would also be prudent to switch the common value system to using tracing units as they exist now, and in that case I think the units you propose are fine.

**Comment by petrcermak** [comment]
What is the exact relationship between <tt>tr.b.u.Scalar</tt> and <tt>tr.v.ScalarValue</tt>? Is the latter intended to replace the former?

Should I now:

  1. Replace memory-infra <tt>Attribute</tt> with <tt>tr.b.u.Scalar</tt> and <tt>string</tt>?
  2. Replace memory-infra <tt>Attribute</tt> with <tt>tr.v.ScalarValue</tt> and <tt>string</tt>?
  3. Replace memory-infra <tt>Attribute</tt> with <tt>tr.v.ScalarValue</tt> and <tt>tr.v.StringValue</tt> _(new class)_?
  4. Wait until <tt>tr.b.ScalarValue</tt> is finished and ready to be used in Trace Viewer?

**Comment by natduca** [comment]
I'm not sure. We should have a brainstorm in a 1:1 if you don't mind.

**Comment by petrcermak** [comment]
<tt>Numeric*X*</tt> sounds good to me. The only issue I can see with this is that it is inconsistent with the current treatment of values of units and values: <tt>units</tt> are a property of <tt>tr.v.Value</tt> while the actual <tt>value</tt> is set on <tt>tr.b.ScalarValue</tt>:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  BEFORE                                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

+==================+
|    tr.v.Value    | ---> units
+==================+      +=============+
         ^                | tr.b.u.Unit |
         : extends        +=============+
         :
+==================+
| tr.v.ScalarValue | ---> value
+==================+      +========+
                          | number |
                          +========+


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  AFTER???                                                            %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

+==================+
|    tr.v.Value    |
+==================+
         ^
         : extends
         :
+==================+             
| tr.v.ScalarValue | ---> numeric 
+==================+      +======================+
                          | tr.b.u.NumericScalar | ---> unit
                          +======================+ -+   +=============+
                                                    |   | tr.b.u.Unit |
                                                    |   +=============+
                                                    |
                                                    +-> value
                                                        +========+
                                                        | number |
                                                        +========+
```

Even though I understand the motivation behind the current model, I personally find it very strange that units are more "basic" than actual values (i.e. every value has a unit, but not necessarily a value). Perhaps this implies that there should be no type-specific subclasses of <tt>tr.v.Value</tt>, e.g. <tt>tr.b.ScalarValue</tt> → <tt>tr.b.Value[value = tr.b.u.NumericScalar]</tt>. In that case, "numeric" is probably not the right prefix because values can be non-numeric (e.g. a dictionary or strings).

We could, of course, decompose the fields of <tt>Numeric*X*</tt> objects instead (and keep the existing <tt>tr.v.(Scalar)Value</tt> "layout"), but that seems to go against the OOP paradigm.

**Comment by petrcermak** [comment]
I increased the priority of this issue because it's relevant to porting MemoryTimelineMetric to TBM 2.0 (https://bugs.chromium.org/p/chromium/issues/detail?id=581716).

**Comment by petrcermak** [comment]
Catapult Values & Numerics design document: https://docs.google.com/document/d/190WyAmgexaSpr8KlOKlMFLbMRiL8_CDX5442SrECvtg/edit?usp=sharing

Summary of discussion with @natduca and @eakuefner:

  1. <tt>mv tracing/units/* tracing/value/</tt> and <tt>s/tr\\.u\\./tr\\.v\\./g</tt>
  2. We introduce the intermediate <tt>tr.v.Numeric</tt> class proposed by @natduca (by renaming <tt>tr.u.Scalar</tt>)
  3. Memory allocator dumps will have the following structure:

```
=== BEFORE ===
MemoryAllocatorDump {
  name: string,
  attr: Map<string, Attribute>
}

=== AFTER ===
MemoryAllocatorDump {
  name: string,
  values: Map<string, Numeric>,
  diagnostics: Map<string, string>
}
```

**Comment by petrcermak** [comment]
Linking this to the parent issue #1940 ("Create common metrics + interactions + values + units code").

**Comment by petrcermak** [comment]
This is blocking https://bugs.chromium.org/p/chromium/issues/detail?id=581716 (_"Port MemoryTimelineMetric to TBM 2.0"_).

**Comment by petrcermak** [comment]
Following 00ce707, it remains to actually replace attributes with numerics:

### _Before_ replacement
![before ditching attributes](https://cloud.githubusercontent.com/assets/2546601/13409819/7a18f8d8-dee9-11e5-81d5-b0876774acb4.png)

### _After_ replacement
![after ditching attributes](https://cloud.githubusercontent.com/assets/2546601/13409827/7f34a268-dee9-11e5-8a86-602e586e11dc.png)

As discussed with @natduca and @eakuefner, the rationale for separating scalar and string attributes is that: 

  * It is consistent with the existing <tt>[tr.v.Value](https://github.com/catapult-project/catapult/blob/0f6704fc4f775a4f3840d0e08c284fcd0631709a/tracing/tracing/value/value.html#L23)</tt> model.
  * Unlike scalars, strings are _not_ values because they are not _bisectable_.

@primiano Is this fine with you?

**Comment by primiano** [comment]
You guys seem to have full control of the situation. I'm sure you don't want another cook in the kitchen.  From my viewpoint this sounds s/ScalarAttribute/ScalarNumeric/ and I don't have any objection to that :)

**Comment by petrcermak** [comment]
__Done__ :white_check_mark:
