### ISSUE TITLE
Add d8 build for vinn on windows

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1929]
This is required to make trace mappers work on windows.

**Comment by nedn** [comment]
fyi: @eakuefner

**Comment by anniesullie** [comment]
@zeptonaut didn't you have a WIP script to build vinn (or d8) at some point?

**Comment by zeptonaut** [comment]
Yep - it was actually completed, but only for Mac and Linux because we didn't need it on Windows at the time. ([link](https://github.com/catapult-project/catapult/blob/master/third_party/vinn/bin/update_v8))

I'm going to spend some time this week updating it to work with Windows as well.

**Comment by nedn** [comment]
Thanks Charlie!
