### ISSUE TITLE
Need a catapult/systrace/bin/systrace_android

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1936]
Right now we have catapult/systrace/ but there is nothing but run_tests in the bin directory. This is really confusing to people who we tell to "just try systrace."

Can we add a simple pair of bin/ scripts?

1 that does android_target
2 that does local target

I'd be okay with a very minimalist optparse interface --- i'd prefer that the script exist, and be architected for future compatibility [eg not carrying over the existing systrace.py interface], but incompelte on features.

@ChrisCraik @wangzhen127 @zeptonaut

**Comment by wangzhen127** [comment]
We are going to start from one systrace bin which works in the most flexible way in bin/.

There were also some related discussions when ftrace was added:
https://codereview.chromium.org/1421373008/#msg10

**Comment by wangzhen127** [comment]
Now we have catapult/systrace/bin/systrace. It is a wrapper and all the detailed logic are in catapult/systrace/systrace/systrace.py. It by default uses --target=android. One can use --target=linux to get ftrace on local linux machine.

This should be enough for current usage. We may need to revisit after the tracing tools are unified.
