### ISSUE TITLE
Move adb_profile_chrome to Catapult

### ISSUE THREAD

**Issue by wangzhen127** [catapult-project/catapult#1937]
We should move adb_profile_chrome to Catapult too. Then we can try to reuse a lot of the tracing functionalities.

@nedn @skyostil @natduca

**Comment by skyostil** [comment]
Moving it there is a good first step I think. After that we should evaluate folding it into systrace.py.

**Comment by wangzhen127** [comment]
[chromium]/tools/profile_chrome/ has dependencies on
- devil.android
- pylib

I see that devil is now in Catapult, but not pylib. @nedn, how did Telemetry resolve the dependency on pylib?

**Comment by nedn** [comment]
Telemetry just switch to use devil/ entirely.

@jbudorick

**Comment by jbudorick** [comment]
We moved everything that telemetry depended on that was in pylib over to devil.

Most of the pylib uses in tools/profile_chrome/ appear to be trivial to change. The exceptions are:
 - the use of constants.PACKAGE_INFO. Those constants are chrome-specific, and I've generally tried to keep such things in pylib (i.e., in chromium) rather than moving them to devil.
 - the use of flag_changer. It wouldn't be too difficult to move up into devil.

**Comment by skyostil** [comment]
Switching to devil sounds like the right way. IIRC telemetry also has that same package info -- we could try using that if the dependency isn't an issue.

**Comment by wangzhen127** [comment]
I created an issue in crbug to remove the dependency on pylib: [https://crbug.com/583785](https://crbug.com/583785)

**Comment by wangzhen127** [comment]
@nedn I see the package info in Telemetry is in catapult/telemetry/telemetry/internal/backends/chrome/android_browser_finder.py, which is internal logic. Can we pull that out to some common place, so that adb_profile_chrome can also use it?

**Comment by nedn** [comment]
There are two options I can see here:
1) Move those package info to devil/
2) Make adb_profile_chrome part of telemetry toolset.

**Comment by jbudorick** [comment]
Just make a devil/android/constants/chrome.py and put them in there.

**Comment by wangzhen127** [comment]
adb_profile_chrome and adb_profile_chrome_start are in Catapult now.

**Comment by nedn** [comment]
You rocks!

**Comment by skyostil** [comment]
Indeed, great job!

**Comment by progers** [comment]
There's still adb_profile_chrome in the chromium repository. Should that be updated to point to the catapult version?

**Comment by wangzhen127** [comment]
It already does that.

**Comment by progers** [comment]
Ah, it does! Don't mind my noise..
