### ISSUE TITLE
Dev Server Tests on Canary fail, blocking catapult CQ

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1939]
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Mac%20Tryserver

**Comment by nedn** [comment]
Disable patch in https://codereview.chromium.org/1648813003/

**Comment by nedn** [comment]
This test is not reenabled on canary yet. Ping Annie.

**Comment by anniesullie** [comment]
I'm marking this **fixed** for now, but please re-open if it happens again.

**Comment by nedn** [comment]
Now it's very flaky on linux: https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Linux%20Tryserver

**Comment by anniesullie** [comment]
I see 2/20 builds failing with a failed lookup to omahaproxy. We won't need to do this step once we can pull reference builds from telemetry cloud storage bucket. @Apeliotes do you have an estimate on that? (I understand there are lots of other things happening at the same time, maybe we can chat at our meeting tomorrow)

**Comment by anniesullie** [comment]
Downgrading to P2 because it's flake and not consistent failure
