### ISSUE TITLE
Create common metrics + interactions + values + units code

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1940]
We want TBMv2, System Health, RAIL to have some common code to work with, and eventually we want to make Telemetry and Bisect able to work well with TBMv2, System Health, RAIL as well.

To do this, we are going to create a common system for writing interactions, metrics, values, and units.

This work entails two design docs, so far:

* [Common Metrics System](https://docs.google.com/document/d/190WyAmgexaSpr8KlOKlMFLbMRiL8_CDX5442SrECvtg/edit): A design doc that creates a metrics object, formalizes the notion of interaction records, clarifies RAIL and "system health"

* [Common Value and Units System](https://docs.google.com/document/d/1l-zTTKca66uypoIjo_uA9--SP8JCp9OimB7YjftPgYE/edit): A doc that takes the perf_insights value system and tracing's existing units system and unifies them into a common value and units system. The intent is that this system can be used by telemetry and bisect in the very near future. The existing telemetry/ and bisect/ code will get merged into the common values system.

**Comment by natduca** [comment]
@benshayden will be doing some patches for this too!

**Comment by natduca** [comment]
Ethan is doing a lot of this, so I think its only fair to say assignee is him :)

**Comment by eakuefner** [comment]
@benshayden, @nedn and I had a discussion this morning about a lot of lingering issues in the value and metrics systems which have come up while trying to implement the system health metric/benchmark, and we have a lot of concrete next steps here, so I'll be filing bugs that reference this one.

Overall, the metrics/values pipeline is currently in a feedback loop with SH, where SH is turning out to drive a lot of design refinements and "fix-first" bugs for TBMv2, and those improvements in turn drive 'correct' implementations of the various system health features.

**Comment by benshayden** [comment]
(Don't panic, I'm just scrubbing RAIL labels.)
