### ISSUE TITLE
Idiom of var test_utils = tr.c.TestUtils is busted

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1942]
We have this idiom throughout the test codebase of:

```
var test_utils = tr.c.TestUtils;
```

Basically, I think what happened is test_utils became a staticclass with methods, where it once was a namespace with functions. Though the tests were updated to not fail, the names were left as-was. This can get pretty confusing though to new readers of the code.

Calling @zeptonaut

**Comment by zeptonaut** [comment]
Agreed that this could be confusing. Can you link to a concrete example?

**Comment by natduca** [comment]
https://github.com/catapult-project/catapult/search?utf8=%E2%9C%93&q=var+test_utils+%3D+tr.c.TestUtils%3B

**Comment by zeptonaut** [comment]
Ah, yea, that's a really weird idiom. What do you think about just replacing `test_utils` with `TestUtils`, as is already used in some places? `TestUtils.callHelperFunction()` looks a lot more like a static function than `test_utils.callHelperFunction()` to me.

**Comment by natduca** [comment]
I think yeah, all we have to do is say var TestUtils = ...TestUtils; and update the references and we're done.
