### ISSUE TITLE
Perf dashboard cost goes up on weekends.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1944]
https://appengine.google.com/billing/history?&app_id=s~chromeperf

Recently, the cost of chromeperf on weekend days is around 2x-4x as high as week days.

**Comment by qyearsley** [comment]
The scheduled backup cron job is now disabled; I should check up on this in one or two weeks.

**Comment by qyearsley** [comment]
This weekend, the cost for the weekend days was the same as for weekend days (~$400 per day).

I think that we can conclude that doing the cron job in the way that we're doing it (with all of those Row entities etc.) is going to cause the cost to go up a lot.

Maybe we could re-instate the cron job when #1701 is done and the amount of stored data goes down? Or maybe there's some other way that we could do a scheduled backup that doesn't cost so much?

@anniesullie @chrisphn

**Comment by anniesullie** [comment]
Thanks for following up! I think you're right that the current backup strategy isn't really feasible. I wonder if we should consider implementing something that backs up 1 month's monitored tests or something simple like that?

**Comment by chrisphn** [comment]
I don't think the backup is necessary all to blame, though it is part of the cause.  The weekend spike pattern started around Dec 2015 which is around the time we enabled per-page series monitoring.  We had backup cron job running before that.

From the logs and stats right before Dashboard went down, there were ~80 idle instances and ~10 active.  And we are charged for idle instances. There's probable a bottle neck in read/write to Test entities with long hierarchy chain which raises queue latency so new instances get spawn.  So probably should look into /add_point_queue.

**Comment by anniesullie** [comment]
@chrisphn - The weekend-specific cost issue seems to stem from the backups. @qyearsley changed them to use cloud storage in December IIRC, so that's likely the cause for the spike in billing. Per-page monitoring was added in October. The cost is the same on weekdays and weekends now that it's been disabled.

I think the backup is the cause for this bug, but we should update the doc for per-page alerting to clarify problems it may be causing, and file bugs to investigate those.

**Comment by qyearsley** [comment]
Cost on weekends is no longer an issue since that change went in, so I'll close this issue.

Note though, that we now definitely have no backups of recent data.
