### ISSUE TITLE
Minimize telemetry.isolate & telemetry/BUILD.gn

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#1953]
Currently, telemetry.isolate & telemetry/BUILD.gn include all the files in catapult/. We should only include what's needed for the telemetry.

**Comment by nedn** [comment]
@Apeliotes

**Comment by zhenyao** [comment]
This is addressed in https://bugs.chromium.org/p/chromium/issues/detail?id=872521

I guess we can close this issue now?
