### ISSUE TITLE
Simplify display of function names in sampling sub view

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1954]
RIght now we show full url plus filename and line number as one column.

In devtools, they show just the function name, and then the files basename (minus the url) afterward, right hand aligned. This lets the information show through the context.

Can we do the same?

**Comment by natduca** [comment]
@lpy @fmeawad

**Comment by lpy** [comment]
I am doing some experimentation.
This is the original display:

<img width="1264" alt="screen shot 2016-03-31 at 6 05 52 pm" src="https://cloud.githubusercontent.com/assets/1453861/14195214/95e3783c-f76b-11e5-835b-9099c5e71222.png">

and this is what I added:

<img width="1242" alt="screen shot 2016-03-31 at 6 07 30 pm" src="https://cloud.githubusercontent.com/assets/1453861/14195224/b7808480-f76b-11e5-849e-82ca20e52fa9.png">

Here's the trace I am using. https://drive.google.com/file/d/0B0DRpwuGZfeGVzM2LTBmeUNidVE/view?usp=sharing 

Any suggestion? @paulirish @natduca

**Comment by natduca** [comment]
This is really nice! I like this!

**Comment by lpy** [comment]
This is fixed.
CL: https://codereview.chromium.org/1860443004/

**Comment by paulirish** [comment]
Nice work!

I have a bug open for eliding filenames in the big hashes (like what we see
on github.com).. But that's quite superficial. :p

This change is quite nice. Good stuff

**Comment by natduca** [comment]
Can you reference the bug #?
