### ISSUE TITLE
Trace Viewer test failures when running all tests

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1956]
### If I run *all tests*, there are *failures*:

![screenshot from 2016-02-03 11 33 46](https://cloud.githubusercontent.com/assets/2546601/12781072/048050d2-ca6a-11e5-989d-5a3921ec49db.png)

### On the other hand, If I run the failing tests *separately*, they all *pass*:

![screenshot from 2016-02-03 11 35 54](https://cloud.githubusercontent.com/assets/2546601/12781111/4e104ea0-ca6a-11e5-89f4-94f6754d03b9.png)

![screenshot from 2016-02-03 11 36 22](https://cloud.githubusercontent.com/assets/2546601/12781124/5f0b4444-ca6a-11e5-9390-c6e9d2ceaa29.png)

I have to say this really caught me by surprise. We typically get the opposite issue (due to missing imports).

Anyway, I manually bisected the issue and it was caused by 2e6399f.

**Comment by petrcermak** [comment]
Two observations:

  1. The issue __only happens when _"Short format"_ is enabled__ (this also explains why the original patch got through CQ).
  2. When the issue does occur, __some tests do not run at all__ (e.g. only 1251 out of 1559 tests were run in the first screenshot).

**Comment by natduca** [comment]
Darn! Sorry!!! Is it random when it happens, or is it deterministic?

**Comment by petrcermak** [comment]
It seems to be __completely deterministic__ (always occurs in "Short format" from 2e6399f onwards, never occurs before it).

BTW, apart from this, the speed-up is absolutely amazing :tada:

**Comment by natduca** [comment]
Okie! I'll work on this as soon as I can (probably ~11am PST)

**Comment by petrcermak** [comment]
I found that the following failure in perf_insights/tests.html was also caused by the patch:

![screenshot from 2016-02-03 16 47 49](https://cloud.githubusercontent.com/assets/2546601/12789541/30ec287c-ca96-11e5-8e6d-30eb7d33da4e.png)

**Comment by natduca** [comment]
I can't reproduce the second failure. You're sure that http://localhost:8003/perf_insights/tests.html fails? Is your devserver out of date?

**Comment by natduca** [comment]
Patch incoming for the original reported failure: https://codereview.chromium.org/1663053004

**Comment by petrcermak** [comment]
Thanks for fixing this!

I refreshed the dev server and the second failure persists. I'll look into it next week.

**Comment by petrcermak** [comment]
I've just updated Chrome and I cannot reproduce the second failure anymore, so I'll assume it was a Chrome bug that has already been fixed.
