### ISSUE TITLE
Windows TryServer doesn't find python

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1960]
The windows tryserver fails for [my patch](https://codereview.chromium.org/1494173003/) with the following error:

```
'E:\b\build\scripts\slave\.recipe_deps\depot_tools\python' is not recognized as an internal or external command,
operable program or batch file.
```

Doesn't seem to be related to the patch itself. Other tryservers pass. Could it be related to #1958?

**Comment by anniesullie** [comment]
Apologies for the late response. I think there was a widespread outage; the catapult roll had a bunch of patch failures for several hours this morning as well. More recent runs on the Windows Catapult bot have succeeded. Can you try again?

**Comment by chiniforooshan** [comment]
Thanks Annie. I tried again and this time it passed.
