### ISSUE TITLE
Generate buildbot steps in catapult repo instead of recipe

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1962]
@nedn pointed out to me that our current way of adding tests could be way less brittle if the recipe had some way of listing out the tests that should be run from the catapult repo, and then dynamically generating the steps it runs from there. That way we don't need to add new steps with three-sided patches. We should do this.

We could either have some config file that lists which tests to run, or some annotation in tests themselves.

Major requirements:
   * Each different suite of tests must be its own step (no running trace-viewer dev_server tests and telemetry unit tests in the same step!!!)
   * It must be quite clear what failed and how to run locally when there are failures.
   * The step name should be a descriptive name of the test suite. ("tracing dev_server tests" not "step 1")

**Comment by nedn** [comment]
This works like a charm. Thanks Annie!

**Comment by anniesullie** [comment]
All working now.
