### ISSUE TITLE
py_trace_event should use monotonic time

### ISSUE THREAD

**Issue by wangzhen127** [catapult-project/catapult#1964]
Currently py_trace_event uses time.time(). It should use monotonic time.

time.monotonic() is available starting from Python 3.3 [1, 2]. There is an equivalent implementation for Python 2 [3, 4]. We should try them out.

@randalnephew @zeptonaut @nedn @natduca 

Reference:
1. https://www.python.org/dev/peps/pep-0418/#time-monotonic
2. https://bugs.python.org/issue14428
3. https://pypi.python.org/pypi/monotonic
4. https://github.com/atdt/monotonic/blob/master/monotonic.py

**Comment by natduca** [comment]
Wow! That's awesome :D

**Comment by zeptonaut** [comment]
Interesting:

On Windows, QueryPerformanceCounter() is not used even though it has a
> better resolution than GetTickCount() . It is not reliable and has too many
> issues.


How high resolution of time do we need?

On Wed, Feb 3, 2016 at 2:07 PM, Nat Duca <notifications@github.com> wrote:

> Wow! That's awesome :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/catapult-project/catapult/issues/1964#issuecomment-179495878>
> .
>



-- 

Charlie Andrews |  Software Engineer |  charliea@google.com

**Comment by nedn** [comment]
We should make sure the python version of time use the same clock as tracing binary on windows. What clock do we use in chrome tracing/?

**Comment by wangzhen127** [comment]
Does Chrome use QueryPerformanceCounter? Looking at the python source, it seems not super complex. We may be able to roll out our own Chrome consistent version.

**Comment by zeptonaut** [comment]
Chrome does use QPC when it's deemed reliable: here's the actual code
<https://code.google.com/p/chromium/codesearch#chromium/src/base/time/time_win.cc&q=time_win.cc&sq=package:chromium&type=cs&l=445>
.

On Wed, Feb 3, 2016 at 3:00 PM, Zhen Wang <notifications@github.com> wrote:

> Does Chrome use QueryPerformanceCounter? Looking at the python source, it
> seems not super complex. We may be able to roll out our own Chrome
> consistent version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/catapult-project/catapult/issues/1964#issuecomment-179519495>
> .
>



-- 

Charlie Andrews |  Software Engineer |  charliea@google.com

**Comment by natduca** [comment]
@nedn py_trace_event doesn't necessarily have to use the same clock, right? It just has to clocksync well... or is the notion here that it should at least try to be the same so that the clocksync system doesn't have to work as hard....

**Comment by nedn** [comment]
Nat: py_trace_event will clock sync with battor's clock. Though the question here is whether it should clock sync with battor_agent_bin, the C++ binary that directly control battor.

Adding another clock_sync between py_trace_event & battor_agent_bin will make it's even more complicated to understand how the timestamps of "issue battor marker" & "finish issuing battor marker" are acquired in the python tracing_controller & create more precision error.

**Comment by natduca** [comment]
Makes sense.

**Comment by randalnephew** [comment]
Both py_trace_event and trac-ing_controller_backend now use trace_time to get monotonic time.

**Comment by nedn** [comment]
Great work, Randy!
