### ISSUE TITLE
Create an endpoint for others to use Perf Dashboard's change-point detection function.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1966]
Context: Findit for Chromecrash ([proposal doc](https://docs.google.com/document/d/1OW_MwCpNK-atJVztOHfHbwnxDh9OOoH-5ClrDYlzWG0/edit), will also need to find steps up and down in time series in order to find regressions in time series, just like the perf dashboard.

If the perf dashboard has an endpoint for making requests for the perf dashboard to run the FindChangePoints function, then the dashboard code wouldn't have to be copied over to the Findit for Chromecrash codebase.

If this is an open endpoint that doesn't require authentication, it could potentially be a target of abuse, so ideally it would be good if it required an API key or something like that.

@anniesullie What do you think?

**Comment by anniesullie** [comment]
@natduca FYI

Other way to go about it is to factor the anomaly detection into a library in common, I think catapult is likely pulled into whatever repo findit would need it from.

I'm okay with this as long as there is authentication, and we can track usage in case it is substantial.

**Comment by anniesullie** [comment]
Any update on this?

**Comment by benshayden** [comment]
Archiving. Findit uses a different algorithm, IIUC.
