### ISSUE TITLE
Switch legacy pending jobs to recipe bisect jobs.

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#1974]
There are bunch of legacy bisect jobs which were kicked off before we switch to recipes on all platforms. Old jobs with legacy scripts are repeatedly failing due to conflict in job configuration as reported in.
crbug.com/583278
https://build.chromium.org/p/tryserver.chromium.perf/builders/linux_perf_bisect/builds/5995/steps/steps/logs/stdio

**Comment by qyearsley** [comment]
@vuppalapu, is this considered done now?
