### ISSUE TITLE
Rehome HTTP Server & WPR in Telemetry

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#1977]
_Moving over from [crbug.com/404771](https://crbug.com/404771)_

Move the in-memory HTTP Server and Web Page Replay (WPR) under platform. They are current under the browser.

With this change, platform owns the LocalServerController. The MemoryCacheHTTPServer and ReplayServer are managed by the LocalServerController. 

[Design Document](https://docs.google.com/a/chromium.org/document/d/1VFKLVpJ8r6cYS2rL5YuQLKoPnjhS3Z01I-Q-sCebTNM/edit?usp=sharing)

@natduca @nedn @eakuefner

**Comment by rschoen** [comment]
I think this is old news, but I wanted to make sure you were aware of the regression with the original patch: http://crbug.com/587561. Given that this has relanded and the regression didn't appear, I think we're fine.

**Comment by perezju** [comment]
Yes. That regression was probably due to my breaking change in WPR. Good to see that metrics recovered back to normal after the fix.

**Comment by eakuefner** [comment]
I'm about to close the Chromium-side bug in favor of this one, so let me just paste the search that shows the to-be-done followups:

https://code.google.com/p/chromium/codesearch#search/&q=TODO%5C(crbug.com/404771%5C)&sq=package:chromium&type=cs

**Comment by perezju** [comment]
I might get to finish this work after migrating the bug back to crbug again :stuck_out_tongue_winking_eye:

**Comment by perezju** [comment]
This is now blocking [crbug.com/784319](https://crbug.com/784319). So raising Pri. I'm working on this now.

**Comment by perezju** [comment]
I think there are mainly two tasks left here.

* Both Android and CromeOS use a "reverse" forwarder to get the devtools connection out of the device and back into the host where Telemetry is running. Such forwarder should probably live in the network controller as well.
* Move the [MemoryCacheHTTPServer](https://github.com/catapult-project/catapult/blob/86c17b98f5364a8a3f903df3d946ea7afe4d729b/telemetry/telemetry/core/platform.py#L390) currently in the platform to the network_controller.

On a somewhat related note, we have this `forwarders.PortPair` class to hold and pass around `(local_port, remote_port)` pairs. I think this actually hinders readability since callers have to do, e.g.:

    from telemetry.internal import forwarders

    # which port is which??
    forwarder_factory.Create(forwarders.PortPairs(0, self._devtools_port))

Rather than simply:

    # usually no extra import!

    # ah, now it's clearer
    forwarder_factory.Create(local_port=0, remote_port=self._devtools_port)

Any votes pro or con on killing `forwarders.PortPair`??

**Comment by nedn** [comment]
+1 to killing port_pair. I only find it make the code more verbose & less readable.

**Comment by perezju** [comment]
For my own reference, that last CL rolled into chromium at [r521661](https://chromium-review.googlesource.com/c/chromium/src/+/808127). Will keep an eye as it rolls though bots to make sure nothing broke.

**Comment by perezju** [comment]
List of [remaining TODOs](https://cs.chromium.org/search/?q=TODO%5C\(%5C%231977+-file:%5Esrc/third_party/android_tools&type=cs).

**Comment by nedn** [comment]
+1 to close this bug & open more specific ones. I think you can add "GoodFirstBug" & CodeHealth label for those two bugs as well. IMO, they are not blocking the Go startup work, so probably not very urgent.
