### ISSUE TITLE
500 error on new_points due to missing index, when logged out.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1979]
To reproduce, visit these pages in an incognito window:
 * https://chromeperf.appspot.com/new_points
 * https://chromeperf.appspot.com/new_points?pattern=ChromiumPerf%2Fandroid-nexus4%2Fsmoothness.tough_animation_cases%2F*&num_points=100&max_tests=30

When querying for recent points from a specific set of tests, logged out:
```
NeedIndexError: no matching index found.
The suggested index for this query is:
- kind: Row
  properties:
  - name: internal_only
  - name: parent_test
  - name: timestamp
    direction: desc
```

When querying for recent points from any test, logged out:
```
NeedIndexError: no matching index found.
The suggested index for this query is:
- kind: Row
  properties:
  - name: internal_only
  - name: timestamp
    direction: desc
```

In the case of new_points, it's slower or not feasible to use the datastore_hooks.SetSinglePrivilegedRequest approach, since in order to do that we want to assert that all of the tests that we're getting rows for are not internal only if the user is not logged in.
 * When getting points for particular tests, this requires getting test entities when currently we only get test keys.
 * When getting points for any test, this can't be done (given the way the points are currently fetched).

@anniesullie

**Comment by anniesullie** [comment]
Can we require login for this page?

**Comment by qyearsley** [comment]
Ah, yes, that would also be an option -- and if login was required, then people would be prompted to login before viewing test data, which would also mean that they would be able to view internal-only data. This is good, because one of the main purposes of this page is to allow devs who have just started sending data to verify that it's being received, and new data is marked internal-only by default.

**Comment by qyearsley** [comment]
Committed & deployed. Now viewing those pages in an incognito window prompts me to log in.
