### ISSUE TITLE
Get rid of tr.b.u.TimeDuration and tr.b.u.TimeStamp

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1981]
Both classes are unnecessary <tt>tr.b.u.Scalar</tt> wrappers around <tt>tr.b.u.Unit.byName.timeStampInMs</tt> and <tt>tr.b.u.Unit.byName.timeDurationInMs</tt>. I think we should get rid of them.

@natduca: Sounds good?

**Comment by natduca** [comment]
Thats fine!

**Comment by petrcermak** [comment]
Patch pending: https://codereview.chromium.org/1687043002/

**Comment by petrcermak** [comment]
This is now **done** :tada:
