### ISSUE TITLE
Move perf dashboard documentation into md files with the code.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1984]
Possible advantages:
 * Easier to make doc changes with code changes
 * Other projects in catapult have more md docs.
 * One main place to put documentation.

Some documentation lives here:
http://www.chromium.org/developers/speed-infra/performance-dashboard/

Ideally I'd also like to add more documentation at the directory level when splitting dashboard into App Engine modules (And maybe possibly when re-organizing other code, e.g. #1760)

@chrisphn, @anniesullie

**Comment by anniesullie** [comment]
I am 100% in favor of documentation in .md files in catapult repo. Telemetry team and perf sheriff rotation have moved documentation to .md files and it's working out well for both.

**Comment by qyearsley** [comment]
Docs have now been moved to https://github.com/catapult-project/catapult/blob/master/dashboard :-)

Docs on http://www.chromium.org/developers/speed-infra/performance-dashboard have now been updated to point there.
