### ISSUE TITLE
ClockSyncRecord should be split into two types

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1985]
The two types are:

* `InstantClockSyncRecord`, which represents a clock sync that happens instantaneously (e.g. this `QueryPerformanceCounter()` time equals this `timeGetTime()` time).
* `PingPongClockSyncRecord`, which represents a clock sync that requires the agent to contact something remote and wait for a response in order to sync clocks. The long-term goal is, for these types of clock syncs, to sync the *midpoint* of the "send clock sync" and "received clock sync ack" times to the remote timestamp that was recorded.

**Comment by zeptonaut** [comment]
@natduca hoping to get to this today or tomorrow - just wanted to let you know that I hadn't forgotten about it.

**Comment by natduca** [comment]
\o/!
