### ISSUE TITLE
ClockSyncRecord "name" field should be changed to "id"

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1986]
The `ClockSyncRecord` class currently has a `name` field. There's also a a method `getClockSyncRecordsNamed` that returns all clock sync records with the specified name.

This makes it sound like it's sometimes the case that there are multiple clock sync records with the same name. However, that's not true.

Another important point is that we'll soon be importing clock syncs from Chrome that need to be matched up by a GUID. Currently, the only way to do this is to set their name to their GUID (something like `045c11d8-9af8-4524-8864-72b7887ce403`) from within the Chrome trace importer, then look up that GUID with `getClockSyncRecordsNamed('045c...')` from the subtrace importer... and so on.

Given all of this, it seems like it makes a lot more sense to change the `name` field to an `id` field. Then, it's not surprising that it isn't always human readable. Then, we can also enforce the contract that duplicate IDs aren't allowed.

@nedn @aschulm

**Comment by nedn** [comment]
Hmhh, you may want to make sure that the clock sync still works for legacy data of chrome + systrace. We may drop support for battor's old data but we still need to keep chrome & systrace's old data working.

**Comment by zeptonaut** [comment]
Sounds reasonable, but I don't think this bug should affect that. This is more a matter of just changing a parameter name w/in the javascript constructor of `ClockSyncRecord`.

**Comment by zeptonaut** [comment]
Closing this as wontfix: this API is going to be removed after the new clock sync logic is fully implemented anyhow, so I don't think it makes sense to spend too much effort here
