### ISSUE TITLE
PRESUBMIT is requiring jsdocs on global.x = y statements

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1989]
It looks like some aspect of our jslinting stack is seeing these as API definitions, and requiring that we put jsdocs on them. Who knows how to disable this?

Calling @nedn @qyearsley @zeptonaut

**Comment by zeptonaut** [comment]
Unfortunately, I don't have the bandwidth to pick this up right now with the BattOr stuff coming to a head, but this definitely seems important to fix!

**Comment by anniesullie** [comment]
I don't have the time to dig into it right this moment either, but if you could link to a sample patchset that exhibits the problem it would likely save time when someone gets the chance.

**Comment by nedn** [comment]
Patch in https://codereview.chromium.org/1679333002/ . Maybe a bit aggressive but I think it's code reviewers' job to review the API documentation anyway :-/

**Comment by anniesullie** [comment]
Huge +1 that it is reviewers' job to review API documentation. Every automated lint for documentation I've ever seen just ends up with piles and piles of useless docstrings. I think @zeptonaut had to remove a bunch of redundant file overviews because of a previous linter policy.

**Comment by zeptonaut** [comment]
Yep.

In event.html:



Mmmm. So useful.

On Tue, Feb 9, 2016 at 11:53 AM, anniesullie <notifications@github.com>
wrote:

> Huge +1 that it is reviewers' job to review API documentation. Every
> automated lint for documentation I've ever seen just ends up with piles and
> piles of useless docstrings. I think @zeptonaut
> <https://github.com/zeptonaut> had to remove a bunch of redundant file
> overviews because of a previous linter policy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/catapult-project/catapult/issues/1989#issuecomment-181954222>
> .
>



-- 

Charlie Andrews |  Software Engineer |  charliea@google.com

**Comment by natduca** [comment]
Y'all rock, thank you so much!!!
