### ISSUE TITLE
Perf Dashboard: 400 response when trying to 11 graphs at the same time

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1994]
Chrome version: 50.0.2646.0 (Windows)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
N/A

Please describe the problem:
Currently, there is a single aggregated alert with a total of 11 associated tests. I selected all the corresponding checkboxes:
![screenshot](https://cloud.githubusercontent.com/assets/9001650/12958661/967f5fa0-cfe7-11e5-9441-42cfcd00eacd.png)

Then pressed the Graph button. That opened a new tab to [this long URL](https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyoQELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InNDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3Jlc29sdXRpb25fc2VuZG9ubHkvZ29vZ19mcmFtZV93aWR0aF9yZWN2DAsSDVN0b3BwYWdlQWxlcnQY0t4WDA,agxzfmNocm9tZXBlcmZymQELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImtDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3J4X3NlbmRvbmx5L2dvb2dfY3VycmVudF9kZWxheV9tcwwLEg1TdG9wcGFnZUFsZXJ0GNLeFgw,agxzfmNocm9tZXBlcmZykgELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImRDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3J4X3NlbmRvbmx5L2dvb2dfZGVjb2RlX21zDAsSDVN0b3BwYWdlQWxlcnQY0t4WDA,agxzfmNocm9tZXBlcmZymQELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImtDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3J4X3NlbmRvbmx5L2dvb2dfaml0dGVyX2J1ZmZlcl9tcwwLEg1TdG9wcGFnZUFsZXJ0GNLeFgw,agxzfmNocm9tZXBlcmZylgELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImhDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3J4X3NlbmRvbmx5L2dvb2dfbWF4X2RlY29kZV9tcwwLEg1TdG9wcGFnZUFsZXJ0GNLeFgw,agxzfmNocm9tZXBlcmZymAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImpDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3J4X3NlbmRvbmx5L2dvb2dfcmVuZGVyX2RlbGF5X21zDAsSDVN0b3BwYWdlQWxlcnQY0t4WDA,agxzfmNocm9tZXBlcmZymAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImpDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3J4X3NlbmRvbmx5L2dvb2dfdGFyZ2V0X2RlbGF5X21zDAsSDVN0b3BwYWdlQWxlcnQY0t4WDA,agxzfmNocm9tZXBlcmZylwELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImlDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3RvdGFsX2J5dGVzX3JlY3Zvbmx5L2J5dGVzX3NlbnQMCxINU3RvcHBhZ2VBbGVydBjS3hYM,agxzfmNocm9tZXBlcmZylwELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImlDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3RvdGFsX2J5dGVzX3NlbmRvbmx5L2J5dGVzX3JlY3YMCxINU3RvcHBhZ2VBbGVydBjS3hYM,agxzfmNocm9tZXBlcmZylgELEhNTdG9wcGFnZUFsZXJ0UGFyZW50ImhDaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3R4X3JlY3Zvbmx5L2dvb2dfYXZnX2VuY29kZV9tcwwLEg1TdG9wcGFnZUFsZXJ0GNLeFgw,agxzfmNocm9tZXBlcmZyjAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50Il5DaHJvbWl1bVdlYlJUQ0ZZSS9jaHJvbWl1bS13ZWJydGMtdHJ1bmstdG90LXJlbC1saW51eC9icm93c2VyX3Rlc3RzL3ZpZGVvX3R4X3JlY3Zvbmx5L2dvb2dfcnR0DAsSDVN0b3BwYWdlQWxlcnQY0t4WDA).

That URL unfortunately returns a 400 ("Error: Bad Request Your client has issued a malformed or illegal request."). The js console simply says:
Failed to load resource: 
(same URL as above)
the server responded with a status of 400 ()

For now, I'm able to work around this by opening the graphs individually. If I confirm they all are tied to the same culprit CL, I'll try my luck at bulk triaging them. :)

**Comment by qyearsley** [comment]
Same underlying issue as #1408.

The reason is that the stoppage alert keys are really long, and when making the URL for opening the graph page, it constructs a URL that includes all of the urlsafe URLs for all selected URLs, which can easily be over a couple thousand characters.

Annie mentioned a possible solution in #1408; until that's fixed we'll have to use the workaround of only triaging a small number of alerts at a time :-/
