### ISSUE TITLE
Get rid of <tr-ui-u-time-stamp-span> and <tr-ui-u-time-duration-span>

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2003]
_[Follow-up for #1981]_

Both elements are unnecessary wrappers around <tt>\<tr-ui-u-scalar-span\></tt>. I propose doing the following:

  * Replace <tt>\<tr-ui-u-__time-stamp__-span\></tt> with <tt>\<tr-ui-u-__scalar__-span __unit="timeStampInMs"__\></tt> and
  * Replace <tt>tr.ui.units.create**TimeStamp**Span(x)</tt> with <tt>tr.ui.units.create**Scalar**Span(__new tr.b.u.Scalar__(x, __tr.b.u.Unit.byName.timeStampInMs__))</tt>.

@natduca: Sounds good?

**Comment by natduca** [comment]
very!

**Comment by petrcermak** [comment]
_Option 1_: We could add a __unit argument__ to the function's signature (i.e. <tt>function createSalarSpan(value, opt\_config)</tt> → <tt>function createScalarSpan(value, **opt\_unit**, opt\_config)</tt>):

* The __advantage__ is that we could then do <tt>tr.ui.units.createScalarSpan(x, tr.b.u.Unit.byName.timeStampInMs)</tt> or perhaps even <tt>tr.ui.units.createScalarSpan(x, 'timeStampInMs')</tt>, which is considerably less verbose (plus we can always drop the <tt>tr.*</tt> prefix by naming the import).

* The __disadvantage__ is that the case when you actually do have a <tt>tr.ui.u.Scalar</tt> and a config becomes slightly awkward because the scalar already contains a unit: <tt>tr.ui.units.createScalarSpan(scalar, **undefined**, { ... })</tt>.

_Option 2_: We could have a __dynamic function signature__ by using <tt>arguments</tt> (think function overloading in C++):

* 3 arguments for numbers: <tt>tr.ui.units.createScalarSpan(numeric\_value, unit, opt\_config)</tt>
* 2 arguments for scalars: <tt>tr.ui.units.createScalarSpan(scalar\_value, opt\_config)</tt>

**Comment by natduca** [comment]
What about just merging config?

createScalarSpan(numericIsh, config)

if numericIsh is just a raw value, then config must contain unit and we'll construct a ScalarNumeric internally.

**Comment by petrcermak** [comment]
Sounds good.

**Comment by petrcermak** [comment]
Patch pending: https://codereview.chromium.org/1770953005/

**Comment by petrcermak** [comment]
This is now **done** :white_check_mark:
