### ISSUE TITLE
Presubmit requiring Catapult BUG= is too restrictive

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2006]
It's often the case that bugs filed in Chromium require simple fixes in Catapult. In such cases, it is useful to be able to set BUG= to a Chromium bug, both to get Bugdroid to comment on the bug that requires the fix, which is great for archaeology purposes, as well as to not have to file an extraneous Catapult bug.

I think we should remove the BUG= sanity check from Catapult's presubmit, since in my experience it only seems to add procedural overhead.

Such scenarios are especially common with Telemetry because it interacts so heavily with `tools/perf`, Chromium itself, and infra. (Example CL: https://codereview.chromium.org/1685233003)

@nedn @anniesullie

**Comment by eakuefner** [comment]
Actually, an interesting insight here is that originally, this check may have been intended to prevent users from referring to Catapult issues without the catapult:# prefix, since bugdroid/rietveld/etc interpret those as low-numbered Chromium bugs.

I think the fix here is to either accept six digit unprefixed bugs, or arbitrary-digit Catapult-prefixed bugs. That will work until Catapult has hundreds of thousands of issues, after which all bets are off :)

**Comment by anniesullie** [comment]
I like the CL! Can this be closed?

**Comment by nedn** [comment]
Can you update the description in the bug too?
