### ISSUE TITLE
Use Math.log10()

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2015]
It would be nice to have in ruler_track and chart_base_2d for those of us who take a moment to recall the logarithmic identities.
See #2019 about checking that it's in the runtime.

**Comment by natduca** [comment]
Nice. Is it in vinn?

**Comment by benshayden** [comment]
Yes, it looks like it is in vinn.

Also, to clarify, it is not in node v0.10.25, the standard version in aptitude. I'm not sure which node version range you want to support.

**Comment by natduca** [comment]
Oh! Hmm. I think maybe we should modify base.html to explode with node < v5 maybe...

**Comment by benshayden** [comment]
Math.log10 is in v5.6.0, so I'll update the issue description. Is nodejs going into third_party?

**Comment by benshayden** [comment]
It's also in v4.3.0 LTS. Would you rather depend on v.4.3.0 LTS or v5 stable?

**Comment by natduca** [comment]
Hmmm how about filing a fresh bug about "Pick a minimum node.js version" and we can focus conversation on the node version, then we can resolve this bug based on that. I think we'll need to ask around with stakeholders to figure out versioning requirements.

**Comment by benshayden** [comment]
#2019 

If we use the system version, then should we support the v0.10.25 in aptitude, or require devs to download and install a tarball?

**Comment by shreab373** [comment]
hello I'm new i would like to work on this, could you guide me as to how to move ahead?

**Comment by benshayden** [comment]
Hi, sure!
First please see the [Contributor's guide](https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md).

This bug has mostly been fixed, but there are a few lines in [chart_base_2d.html](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/base/chart_base_2d.html#L328) that still need to be fixed to use `tr.b.lesserPower(minValue) - 1` from [math.html](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/base/math.html#L180).

The functional tests don't cover this kind of change very well (sorry :-), so we'll need a screenshot of the instantiation tests in codereview:
1. Start the dev server as described in the [tracing README](https://github.com/catapult-project/catapult/blob/ff40d4569c8bcf2eed27ed49682e7b8198d24dc1/tracing/README.md)
1. Run all of the tracing tests and make sure they all pass
1. Run the yLogScale instantiation tests specifically at http://localhost:8003/tracing/tests.html?testSuiteName=tracing.ui.base.column_chart_test&testFilterString=yLogScale
1. Take a screenshot of that test output. It should look just the same as without your change. I use Chrome devtools' Network tab with "Disable cache" checked to make sure that it's running the new code instead of old code in the browser's cache.
1. Upload the screenshot to imgur.com - I use [smartshot](https://chrome.google.com/webstore/detail/smartshot-screen-capture/edjbamdongkhmagbpppagfjbcojajeae) but you don't have to.
1. Upload your change for review as described in the [Contributor's guide](https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md)
1. Add the imgur link to your issue description in codereview.chromium.org

Thanks!

**Comment by AP-whitehat** [comment]
I have fixed this little issue , but I can't import math.html 
git cl upload        gives this error
'''
In tracing.ui.base.chart_base_2d, the <link rel="import" href="/tracing/tracing/base/math.html"> cannot be loaded because it is not in the search path
'''

**Comment by anniesullie** [comment]
I made a demo CL with the import and it does not have that error: https://codereview.chromium.org/2676133002/

**Comment by benshayden** [comment]
Thanks!
