### ISSUE TITLE
Hot keys

### ISSUE THREAD

**Issue by araud** [catapult-project/catapult#2016]
CTRL doesn't work anymore for temporary zoom.
Navigation was much easier having hot keys working.

**Comment by petrcermak** [comment]
This issue has already been raised in #1789. As @zeptonaut suggested, does Alt+mousewheel work for you instead?

_Background:_ The reason for removing the feature is that Ctrl+click is now used for adding events to the current selection (#1529), which is a common practice across pretty much all tools which support multi-selection.

**Comment by araud** [comment]
Yes, it works! Thank you! Will you please update the [?] help menu also?

**Comment by petrcermak** [comment]
Patch pending: https://codereview.chromium.org/1701703002/ (note that the Alt+mousewheel behavior is already documented under "Mouse Controls")

**Comment by petrcermak** [comment]
__Done__.
