### ISSUE TITLE
Make base.html explode if node.js version < 4

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2019]
What features does/should catapult require of nodejs?

When a minimum version of nodejs is picked, base.html should throw if it's running in an earlier version.
(Or should base.html check for the features required directly instead of checking the version?)

v0.10.25 (in aptitude) lacks Math.log10(), which is re-implemented in ruler_track and chart_base_2d.
v4.3.0 LTS contains Math.log10, though earlier versions might as well.
We could also pick a version of nodejs that lacks features that can be easily polyfilled, such as log10.

What other features should be required/polyfilled?

**Comment by natduca** [comment]
@paulirish @paullewis  I'm leaning toward restricting to v5 for now, and then we can broaden support later. Any objections?

**Comment by natduca** [comment]
@benshayden by Aptitude you mean goobuntu's nodejs image?

**Comment by benshayden** [comment]
Yep, `apt-get install nodejs` installs 0.10.25. To get anything else, it looks like you need to download a tar ball, unless there's a secret package manager.

**Comment by natduca** [comment]
I'm not so worried about google configs, since we don't expect googlers to really ever run the node version. But, what versions are popular in the wild? @paulirish @paullewis i really need your advice here.

**Comment by paullewis** [comment]
I'm of the 4+ mindset. 4.3.1 is current stable, and I think it's 100% valid to go to the current stable version (which also gives us ES2015 primitives, should we want them).

**Comment by paulirish** [comment]
Same!

**Comment by natduca** [comment]
Thanks all!
