### ISSUE TITLE
Update findLoadExpectations() to use FirstMeaningfulPaint

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2022]
Currently, tr.importer.findLoadExpectations() uses a custom heuristic to find the first meaningful paint in order to find the end of a load.

Devtools uses a new instant event "FirstMeaningfulPaint" to find the end of a Load.

We're planning on designing the Best Load Finder Ever... at some point.

But for now, our findLoadExpectations should use the FirstMeaningfulPaint instant event when available in order to better match devtools, and fall back to its current heuristic when that event is not available.

From https://code.google.com/p/chromium/issues/detail?id=546448

**Comment by natduca** [comment]
Awesome. When we don't see this we probably want to fall back to our heuristic so that old traces still work. In the long run we can ditch the old stuff too, but I think we'll want to do best-effort backcompat until we've got a clear case for wanting to simplify/etc.
