### ISSUE TITLE
Perf Dashboard: WebRTC perf sheriff rotation is missing

### ISSUE THREAD

**Issue by phoglund** [catapult-project/catapult#2024]
Chrome version: 48.0.2564.109 (Linux)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down&improvements=true

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
Uncaught SyntaxError: Unexpected token ;
core-overlay.html:348 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
core-overlay.html:348 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
Please describe the problem:
The page says:
Sheriff "WebRTC Perf Sheriff" not found.

The rotation has not been removed as far as I know, so it should be there.

**Comment by phoglund** [comment]
Never mind, it came back when I signed in.

**Comment by anniesullie** [comment]
Note: that means it's marked internal-only. Should it be publicly visible?
