### ISSUE TITLE
Trace loads with no trace events in Chrome 48

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2027]
The traces supplied in [this bug](https://code.google.com/p/chromium/issues/detail?id=587844#makechanges) aren't loading in Chrome 48.

Possible errors causing this:

- When the first trace is loaded, it always generated an `UNHANDLED INPUT EVENT! mouseleave` error.
- When the second trace is loaded, it always generates an `Unrecognized metadata name: trace_buffer_overflowed` error.

Not sure if these are the causes, but I'm investigating now.

**Comment by zeptonaut** [comment]
Omahaproxy indicates that Chrome Mac stable (Chrome 48) maps to version number 48.0.2564.109. When I run `git checkout 48.0.2564.109` in my Chromium repo, it leaves me with Catapult commit 704c402, so that's the version of the Catapult repo that I'm going to be debugging this on.

**Comment by zeptonaut** [comment]
The trace loads perfectly at Catapult HEAD, which makes me question how worthwhile it is to look into this error. It seems likely that whatever it is, it's already been fixed. @natduca, thoughts?

**Comment by natduca** [comment]
You mean ToT chrome or ToT catapult, or both?

**Comment by zeptonaut** [comment]
I tried it on ToT catapult (I didn't have a built Chromium handy)

**Comment by natduca** [comment]
Odd! Guess lets wontfix and we can open fresh if we have a repro?

**Comment by zeptonaut** [comment]
SG (opening a fresh bug if we see this on ToT)
