### ISSUE TITLE
Implement Numeric and NumericValue

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2034]
We need to hack the value system to start using tracing units ASAP to help people start hacking with TBM2.

Without using tracing units, we would force users to specify a unit string and an improvement direction as they currently do in Telemetry.

As I understand, tracing units already exist, so e.g. memory-infra should be able to use them, and then while we procrastinate on making Telemetry use the common value system natively, we can shim that aspect of the translation to extract the unit name and improvement direction for the perf dashboard.

@petrcermak @natduca

**Comment by natduca** [comment]
mmm ideally value's constructor would take a unit object, from units.html in tracing/base/

**Comment by petrcermak** [comment]
Memory-Infra already uses tracing units for _formatting_ in the UI. I'd like to start using them in the _model_ as well (#1928).

**Comment by eakuefner** [comment]
As seen in #1928 we are centralizing the numeric reasoning around a new type tr.v.Numeric and we'll end up porting units into the value system as well. Renamed bug accordingly.

The steps here are:

1. Implement `Numeric`, `ScalarNumeric`, and `NumericValue` (me)
2. Switch the trace viewer UI bits to use `ScalarNumeric` instead of `tr.b.u.Scalar` ( @petrcermak )
3. Port `unit.html` to tracing/value/unit ( @petrcermak )

**Comment by petrcermak** [comment]
Linking this to the __parent issue__ #1940 (_"Create common metrics + interactions + values + units code"_).

**Comment by petrcermak** [comment]
There's _one more step_ before we close this issue: Move <tt>tracing/ui/units/*</tt> to <tt>tracing/value/ui/</tt>.

**Comment by petrcermak** [comment]
This is now __done__ :tada:
