### ISSUE TITLE
Move MRE to tracing and delete perf_insights

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2035]
We need to move MRE to tracing. As a preparatory step we need to move the various pieces of PI that belong to MRE (map_runner, map_single_trace, and so on) into perf_insights/mre.

I think enough of #1885 is implemented that we're basically just pending reduction to do the move.

**Comment by eakuefner** [comment]
One annoying side effect of this bug being open is that the TBM 2.0 code (which lives in tracing/metrics) has a dependency on PI. It's not _quite_ a circular dependency, but from a standpoint of layering hygiene it's a bit eh.

**Comment by natduca** [comment]
Lets definitely fix this once we get our MVP for tbmv2

**Comment by benshayden** [comment]
@vinterstum

**Comment by eakuefner** [comment]
Alright, this is happening.

We need to delete the cloud mapper stuff so that we can delete `CorpusQuery`, which is a thorn in my side as far as moving MRE to tracing is concerned. Once that's done, we can proceed with moving MRE out, remove random PI crap that's left over, and move the remaining trace upload/corpus cleanup stuff into trace_processor.
