### ISSUE TITLE
New bugs not showing up on associate_alert page

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2044]
Repro:

1) Associate an alert with a new bug, i.e. file a bug through the dashboard
2) Find another alert, click to associate with existing bug - https://chromeperf.appspot.com/associate_alerts opens
3) Bug filed in #1 isn't on the list of existing alerts

I can't currently demonstrate this because I've triaged all alerts (yay!) but the next time one comes up I'll let it continue to exist so you can see.

**Comment by anniesullie** [comment]
@qyearsley @chrisphn is this related to the monorail migration? Should it be in the list to follow up on this week?

**Comment by chrisphn** [comment]
Confirmed.  Taking a look.

**Comment by qyearsley** [comment]
Fixed by Chris's CL :-)
