### ISSUE TITLE
FunctionRegistry v2

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2045]
For TBMv2's purposes we only need to provide metrics a way to register so that the metric mapper can pick them up.

Eventually we want the ability to attach metadata to metrics ( @benshayden - why?) which switching MetricRegistry to be a proper instance of ExtensionRegistry will allow us to do.

@natduca @nedn

**Comment by natduca** [comment]
For posterity, the reason we're landing a non-registry-based version of metrics and doing the fixup as a followup is because we're feeling great urgency on TBMv2 working, and it looks like we can cleanly switch to extension registry afterward.

**Comment by benshayden** [comment]
We'd discussed annotating metrics as "per UE (fka IR)", but I'm not sure if that flag would be necessary.
Maybe regression direction ("higher=better" vs "lower=better") would be a metadata flag? Units?

I can't think of any other specific kind of metadata we'd want to attach to metrics, but the extension registry is a core utility, and reusing it can reduce code duplication and conceptual impedance mismatch.

Landing non-registry-based then fixing later sgtm.

**Comment by natduca** [comment]
The regression direction hopefully is a feature on units. I do think the per-ir stuff is an interesting use case, as is stuff like "user friendly names" for metrics.

**Comment by benshayden** [comment]
Merge FunctionRegistry with MetricRegistry
Require metadata to contain enum describing whether the function is a metric, mapper, or reducer

**Comment by eakuefner** [comment]
To do this, we need to port function handle to tracing.

FunctionHandle is already a self-contained piece of MRE, so moving it should not be any trouble.

**Comment by eakuefner** [comment]
Calling @lpy preemptively

**Comment by eakuefner** [comment]
We had a follow-on discussion where we decided that we really do still just want to port MetricRegistry to ExtensionRegistry, and not bother porting FunctionHandle to tracing/ or merging FunctionRegistry and MetricRegistry.

**Comment by eakuefner** [comment]
@lpy has done this \o/
