### ISSUE TITLE
Performance dashboard popups are too small

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2054]
I keep getting into this state, but I haven't figured out how to reproduce it. Opening this bug, but will continue investigation.

https://screenshot.googleplex.com/btSfYKsdM0d

@qyearsley @chrisphn I feel like we've run into this issue before.

**Comment by anniesullie** [comment]
I've seen things like this happen when the tooltip is too close to the bottom of the page (seems like the tooltip would have rendered partially below the bottom of the screen, so the bottom got pushed up, but the top was not adjusted properly.

**Comment by qyearsley** [comment]
I think I can reproduce the small popup by opening a window with limited height and clicking on an alert icon at the bottom of the page.

Interestingly, I seem to get this only after clicking on the alert (thus getting the [triage-dialog](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/triage-dialog.html) element), but not when just hovering (and getting only the chart-tooltip element). So the problem doesn't always happen for all paper-action-dialog elements.

**Comment by chrisphn** [comment]
Yea it's annoying, we'll look into.

**Comment by chrisphn** [comment]
Verified fix.
