### ISSUE TITLE
Yellow is unreadable on the dashboard

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2056]
We should avoid this color, it's impossible to read what it says (at least on my monitor). Also doesn't help that you can't select the text.

https://screenshot.googleplex.com/KfuJDjx3vrM

**Comment by qyearsley** [comment]
Those colors are determined by a function called [stringToColor](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/static/graph.html#L32) which generates a color somewhere in the range #000000 and #FFFFFF based on a hash-code for the test string.

@chrisphn Do you think there's a way to modify this function to return, say, a color somewhere in the range #000000 to #AAAAAA?

**Comment by chrisphn** [comment]
Yea, that can be done.  Avoid yellow.

**Comment by qyearsley** [comment]
Note, bright yellow is red + green (#FFFF00), so as long as red and green are kept within a certain range, yellow should be avoided, right?

**Comment by chrisphn** [comment]
Yea quick fix is to stay below #FFFF00,  but I think there may be other hard to see colors.  Maybe get the similarity of the background color to the generated color and then shift it to make it darker.

**Comment by chrisphn** [comment]
Or have a large list of safe colors, and spread the hash over that range.

**Comment by catleeball** [comment]
Talking to ellyjones@, she linked me to some helpful accessibility specs on determining if colors are readable. https://www.w3.org/WAI/GL/WCAG20/#visual-audio-contrast

We could implement a checking function to ensure the contrast ratio of the font color to the background remains below 4.5:1, or ideally modify the hashing function to only produce colors in this range.

Do you mind if I assign this bug to myself? I'm interested in seeing what I can do with it. :)

**Comment by anniesullie** [comment]
@catleeball sounds great! Please assign the bug to yourself :)

**Comment by picksi** [comment]
Can we also take red/green colorblindness into account while we're at it?
Do we have the ability to use other non-color differentiators too, i.e.
thickness, dashes, periodic dots/crosses/boxes etc?

Simon

**Comment by catleeball** [comment]
@picksi that would be a wonderful feature! Ideally color won't be the only differentiator to accommodate for color blindness and visual impairments. I'll continue working with the color assignment for now; would it be prudent for me to break the variant lines feature into another discreet bug?

**Comment by anniesullie** [comment]
@catleeball agreed the variant lines feature should be a separate bug. Thanks!

**Comment by nedn** [comment]
@catleeball are you still working on this bug?

**Comment by anniesullie** [comment]
No, she's not.

**Comment by anniesullie** [comment]
Ideally we can use https://codereview.chromium.org/2274643003/ for this.
