### ISSUE TITLE
Request to get recent bugs on main page needs to be updated after monorail switch.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2058]
On the main page (/), perf dashboard fetches a list of recent perf bugs, using an URL for the old issue tracker.

This needs to be updated. Today @chrisphn made a change to fix the requesting of bugs for associate_alerts (https://codereview.chromium.org/1721203002); a similar change should be done in main.py.

One decision to make regarding this: When making the request to monorail for recent bugs, should it use the service account credentials, or user credentials? If it uses user credentials then non-logged-in users won't see a list of perf bugs listed on https://chromeperf.appspot.com/.

**Comment by anniesullie** [comment]
Do you know whether internal-only bugs would be shown by the service account? If so, we should use the user account.
