### ISSUE TITLE
battor_agent target does not work on clank checkouts

### ISSUE THREAD

**Issue by randalnephew** [catapult-project/catapult#2063]
If you have a clank checkout and try to build battor_agent you get an error where the target does not exist.

'ninja -C out/Debug battor_agent'
ninja: Entering directory `out/Debug'
ninja: error: unknown target 'battor_agent'

This may cause problems on android bots, since telemetry will require the binary to exist but it is not being built.

**Comment by zeptonaut** [comment]
Closing this after yesterday's discussion - we're likely just going to generate a binary and drop it on the machines rather than compiling it there.
