### ISSUE TITLE
update_bug_with_results is not posting bisect results to Monorail

### ISSUE THREAD

**Issue by chrisphn** [catapult-project/catapult#2072]
No errors seen in logs.  We do have some cases that results are being posted.  This bisect job for example did not: 
https://chromeperf.appspot.com/group_report?bug_id=589850

Related bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=589957

**Comment by anniesullie** [comment]
On the bisect side, I see the actual post data in the stdio, which is great, but I don't see the response code from the perf dashboard. Maybe some more logging from the bisect code that posts the result would help?

**Comment by chrisphn** [comment]
Response code should be there under "status_code".  
https://build.chromium.org/p/tryserver.chromium.perf/builders/linux_perf_bisect/builds/6240/steps/Post%20bisect%20results/logs/json.output

**Comment by chrisphn** [comment]
Further looking, jobs that are failing to post results to Monorail are the ones without a Bug entity.  This is a case when someone send a bisect job and manually entering a bug id.  On the other hand, we automatically create a Bug entity when alerts are triaged.

Sent a change to fix this.

**Comment by anniesullie** [comment]
Is this fixed now, besides the follow up in #2088?

**Comment by chrisphn** [comment]
Don't see error with missing Bug entity anymore.  Going to send a bisect job without a bug id to verify:

https://chromeperf.appspot.com/buildbucket_job_status/9017907741092843968

**Comment by chrisphn** [comment]
This is fixed.
