### ISSUE TITLE
Allow stories to specify grouping keys

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2077]
We want stories to be able to specify grouping keys; for instance, for page cycler v2 we'd like to be able to specify the cache state as a grouping key.

Of course, these grouping keys need to eventually end up on values, so let's make it so that values add a story's grouping keys on construction as well

@nedn

**Comment by ulan** [comment]
The value constructor mutates the provided groupingKeys object:
`this.groupingKeys = opt_groupingKeys || {};`
`this.groupingKeys.name = name;`
This creates an implicit assumption that each Value object has a separate groupingKeys object and can lead to subtle bugs if values share grouping keys.
The constructor should probably copy the groupingKeys?

**Comment by benshayden** [comment]
@ulan git pull. I fixed that a few days ago.

**Comment by petrcermak** [comment]
I raised the priority of this issue because it's blocking porting memory-infra to TBMv2: https://bugs.chromium.org/p/chromium/issues/detail?id=581716
