### ISSUE TITLE
Need a benchmark for Chrome tracing system itself

### ISSUE THREAD

**Issue by wangzhen127** [catapult-project/catapult#2078]
We need a benchmark to understand the performance of the Chrome tracing system itself. Will go with TBMv2 directly.

@natduca @nedn @primiano @vinterstum @simonhatch @eakuefner

**Comment by eakuefner** [comment]
One of the main blockers here is getting information about the size of the trace file into the model itself, so that it can actually be queried by a metric.

**Comment by vinterstum** [comment]
Yeah we probably want something like this to work on the raw trace itself rather than the model, since there's not really a 1:1 relationship in terms of event rates and other things impacting the client-side performance of traces.

**Comment by nedn** [comment]
@natduca has a prototype of gathering trace event's string size during importing phase.

**Comment by vinterstum** [comment]
The full string size of traceEvent = []? That would definitely help, though ideally we'd want to track this with a bit more gradunarity. Check the trace_stats report, I think we want something similar on the waterfall but which actually gathers stats from the raw trace. Maybe not as the first step (anything would be better than nothing), but it'd be a good place to end up.

**Comment by primiano** [comment]
So I think there are two different things we want to check here:
1) tracing with -* filters should be effectively clean. There are always events that in a way or another are emitted even if they are not enabled.
2) we should keep track effectively of the rate of the various categories and make sure that it doesn't bump like crazy over over time. In my mind there is one "rate" metric for each category

**Comment by wangzhen127** [comment]
As discussed offline, the benchmark will test
1. the size of trace
2. the spam of trace buffer

And we probably want to have some metrics like max events/sec or bytes/sec (e.g. in a sliding window).

**Comment by wangzhen127** [comment]
I have drafted a doc here: [https://goo.gl/65LuOR](https://goo.gl/65LuOR).

PTAL

**Comment by wangzhen127** [comment]
@petrcermak

**Comment by wangzhen127** [comment]
@fmeawad @lpy

**Comment by wangzhen127** [comment]
Benchmark is added at https://codereview.chromium.org/1776583003/.

It currently run tracing with debug overhead for top 10 pages. And we will start from there.
Debug overhead: https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/telemetry/telemetry/timeline/tracing_config.py&q=SetDebugOverheadFilter&l=128
