### ISSUE TITLE
Monorail doesn't accept requests to set some accounts as bug owners.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2088]
In bug_update_with_results, dashboard sends requests to Monorail to post bisect results, and if there's a culprit, update the bug owner and cc list.

But, some accounts which were allowed to be owners before with codesite issue tracker are not allowed to be with Monorail. Specifically, we've seen this response from Monorail:

```
<HttpError 404 when requesting
https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues/534467/comments?alt=json&sendEmail=true
returned "The user does not exist: [u'chrome-tpm@google.com']">
```

Possible changes:
 * Only add chromium.org accounts as owners
 * Retry adding comment requests without trying to set owner after the first request fails

@anniesullie

**Comment by anniesullie** [comment]
Was a bug filed for this on monorail side? I think retrying after fail would be the best option, we do have some owners who are active with their opera accounts which should have editbugs privileges.

**Comment by qyearsley** [comment]
It's possible that those opera accounts would still be able to be set as owners; I'm not actually sure whether there's a bug on the monorail side; just filed an issue to ask: https://bugs.chromium.org/p/monorail/issues/detail?id=1037

**Comment by chrisphn** [comment]
Ok, just going to do one retry without setting owner here.

**Comment by qyearsley** [comment]
I think this should now be fixed, but I'm not sure if it has been verified.

**Comment by chrisphn** [comment]
I don't see the errors in the log anymore and also verified manually running AddBugComment from interactive playground.
