### ISSUE TITLE
Bisect report is now hard to read.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2093]
Example: https://bugs.chromium.org/p/chromium/issues/detail?id=589725. Specifically, this section of the bisect report is hard to read:

```
===== TESTED REVISIONS =====
Revision                Mean Value  Std. Dev.   Num Values  Good?
chromium@377245         37236.203   253.886188  5           good
chromium@377247         37158.309   272.159284  5           good
chromium@377247,v8@74cf73009837360.438667120.840938  5           good
chromium@377247,v8@3c6a3ca7b037073.025333202.128313  5           good
chromium@377247,v8@1353b37d4037783.045667191.522599  5           bad
chromium@377247,v8@b3de78c19137938.664333144.274233  5           bad
chromium@377248         37720.474333173.507699  5           bad
chromium@377250         37941.887667133.510736  5           bad
chromium@377254         37988.404   298.120903  5           bad
chromium@377263         37761.096   134.275305  5           bad
```

If the revision section is longer than expected, then there is no space between a value and the next value, and it pushes the next value over so it's mis-aligned.

Specifically, we need to fix [_PrettyTable in dashboard/bisect_report.py](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/bisect_report.py#L141).

Requirements:
1. The width of a column should be expanded to the width of the widest value in that column.
2. There should always be at least one space between columns.

@ro-berto or @chrisphn, do either of you want to take this one?

**Comment by chrisphn** [comment]
_PrettyTable in dashboard/bisect_report.py was a port of a longer and more complicated version by hard coding the spacing.

What about doing something like this?  This adds sub-rows and truncates mean values.

```
===== TESTED REVISIONS =====
Revision                           Mean Value  Std. Dev.        Num Values  Good?
chromium@377245         37236.203    253.886188    5                   good
chromium@377247         37158.309    272.159284    5                   good
chromium@377247         37360.438    120.840938    5                   good
    v8@74cf730098
chromium@377247         37073.025    202.128313    5                   good
    v8@3c6a3ca7b0
chromium@377247         37783.045    191.522599    5                   bad
    v8@1353b37d40
chromium@377247         37938.664    144.274233    5                   bad
    v8@b3de78c191
chromium@377248         37720.474333173.507699  5                   bad
chromium@377250         37941.887667133.510736  5                   bad
chromium@377254         37988.404   298.120903     5                   bad
chromium@377263         37761.096   134.275305     5                   bad
```

Also, are newlines missing around the culprit row?  I remember it was there before.

**Comment by qyearsley** [comment]
I think that with the line breaks is better than the current format. Truncating the values to some reasonable number of decimal places (e.g. 3) is usually good, although occasionally all of the values are very small (< 0.001) so we should be careful about truncating -- ideally we want to always leave at least 6 significant digits.

I know we had a special case before to add blank lines around the first "bad" revision; in the version Roberto wrote, there was a little arrow added pointing to the first "bad" revision, which I think is at least as effective as blank lines. This was done by adding another column with an empty string header, and a value "<-" in just the culprit row.

Personally, I would prefer it to be formatted like this:

```
===== TESTED REVISIONS =====
Revision                       Mean Value Std. Dev. Num Vals  Good?
chromium@377245                37236.203  253.886   5         good
chromium@377247                37158.309  272.159   5         good
chromium@377247, v8@74cf730098 37360.438  120.840   5         good
chromium@377247, v8@3c6a3ca7b0 37073.025  202.128   5         good
chromium@377247, v8@1353b37d40 37783.045  191.522   5         bad   <-
chromium@377247, v8@b3de78c191 37938.664  144.274   5         bad
chromium@377248                37720.474  173.507   5         bad
chromium@377250                37941.887  133.510   5         bad
chromium@377254                37988.404  298.120   5         bad
chromium@377263                37761.096  134.275   5         bad
```

If _PrettyTable can be made to have non-hard-coded spaces (with column width dependent on widest value in the column) in a relatively simple way, I think that would be good.

**Comment by chrisphn** [comment]
The original used pretty_table method:

https://chromium.googlesource.com/chromium/tools/build/+/7e7506dbf9d84ee89cffe03c6df2e0bed169fcb0/scripts/slave/recipe_modules/auto_bisect/bisect_results.py#250

**Comment by qyearsley** [comment]
Thanks Dave :-)
