### ISSUE TITLE
TBMv2 debugging workflows

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2094]
@nedn @natduca 

We should support and document a number of workflows in the TBMv2 development lifecycle:

1. Running against real traces in-browser
2. Writing synthetic unit tests with minimal boilerplate
3. Running against a body of real traces to analyze metric behavior
4. Writing and running a Telemetry benchmark that uses your metrics

For 1 I think we should probably iterate on Ned's mapper debugger. MVP is probably:

1. Persist the path of the loaded trace in local storage (just redo importing on refresh)
2. Textbox to specify <metric1,metric2>
3. Maybe a Run button to re-XHR the metric

**Comment by eakuefner** [comment]
This turns out to be an integral piece of #1940 because it's a key part of how we tell people to use this system.

Specifically focusing on the debug use case, we think that the debugger will end up being a generalization of @benshayden's `system_health_side_panel`. The core idea behind the metric debugger is that it should accept a list of values, and display them as a grouping table.

This is related to but not blocked on #2096, since it's a clear example of a case where we have a model and we just want to run a metric on it, without appealing to MRE.

There's a final point here, which is that since this would be part of trace-viewer, we'd want to probably prune the set of metrics we ship with about:tracing to just SH. The devserver would support running all metrics.

**Comment by eakuefner** [comment]
Following up on the extended design session we had on Friday, just an update to this point: we'll ship all the metrics with about:tracing, and introduce all_metrics.html. In terms of these debugger workflows, this means that the debugger simply needs to include all_metrics.html to become aware of all the available metrics.

**Comment by benshayden** [comment]
Nat mentioned yesterday that there should be a layer between the metrics-side-panel (aka metric debugger?) in trace-viewer and grouping-table, call it metric-value-view or whatever, that could be used by a revamped results.html or what-have-you.
Using metric-value-view for results.html suggests that it might want to support multiple ValueLists as columns for easy diff-ing.

**Comment by eakuefner** [comment]
Assigning to @benshayden because he's doing the bulk of this work right now.

**Comment by benshayden** [comment]
The metrics-side-panel and results2.html is nearly MVP.
The next step is to add an Open button to trace-viewer as Nat describes in #1933 , then we can deprecate Ned's metric-debugger, so I'll close this in favor of #1933 if that's ok.
