### ISSUE TITLE
We need a sustainable way to specify multiple metrics

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2095]
A problem that's come up recently is that we haven't thought through our story for how metrics ought to be combined thoroughly.

Let's start conservatively to allow ourselves time to talk through these issues. The concrete first step here is to change Telemetry's `SetTimelineBasedMetrics` to `SetTimelineBasedMetric`: it's easier to tell benchmark authors that they must specify one metric than to constrain this later down the line.

I'll come back here and post some of the brainstorm I've been having with @natduca and separately @nedn after I've done that.

@natduca @benshayden @nedn

**Comment by natduca** [comment]
\o/

**Comment by eakuefner** [comment]
Actually, I'm closing this since the fixes above make it clear that metrics ought to be combined at the level of metrics, so that they can be specified everywhere.

Hierarchy-of-metrics is maybe not a thing, so we should just revisit this with a more concrete plan in mind if something comes up.
