### ISSUE TITLE
Loading a metric is conflated with specifying that it should be run

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2098]
This is the first piece of the #2095 puzzle after switching the moving pieces to operate on a single metric, rather than a list of metrics (which I have already landed).

This is what currently happens when you specify a metric to run:

1. You specify a filename that points to a file that defines and registers a metric function.
2. `metric_runner` constructs an MRE function handle that has the metric filename and `metric_map_function` as modules to load, with `MetricMapFunction` as the entry point.
3. `map_single_trace` loads both modules, and among other things, the metric registers itself.
4. `metric_map_function` queries the metric registry for all the metrics and runs all of them.

Step 4 is the black magic we are trying to eliminate: it should not be that metrics communicate implicitly with the mapper to tell it that they should be run. Instead, users should explicitly specify to the map function that they want to run a particular metric.

The steps to untangle this are:

1. Make `MetricRegistry` an `ExtensionRegistry` so that we get being able to get individual items out of the registry for free. This is #2045.
1. Introduce `all_metrics.html` which we have decided we want.
1. Extend `FunctionHandle` to contain an optional `options` dict to pass to the function in question.
1. Make `FunctionHandle.load` return a lambda that does typechecking and currying.
1. Force `metric_map_function` to expect an option that is the name of a registered metric.

@lpy Would you be interested in picking up some of this work? Steps 1 and 2 should be self-contained, and would be a good way to develop some expertise with the way all these moving pieces fit together :)

@benshayden @nedn @natduca

**Comment by nedn** [comment]
After chatting offline, you may want to update your description?

**Comment by eakuefner** [comment]
I've already updated the comment above :)

**Comment by benshayden** [comment]
ETA? No particular rush, just wondering if I should split [moving tracingMetric](https://codereview.chromium.org/1811193002/) into a 3-sided patch or wait for this.

**Comment by eakuefner** [comment]
@lpy is working on https://codereview.chromium.org/1811823002 which should be the last piece.

**Comment by benshayden** [comment]
Thanks! No rush.

**Comment by lpy** [comment]
I think this is done.
CLs:

https://codereview.chromium.org/1805703002/
https://codereview.chromium.org/1811823002/
