### ISSUE TITLE
Update cached test suites list when new data is added.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2099]
Background:
In order to list available test suites on the /report page, the dashboard keeps a cached list of test suite (benchmark) names. In production, this is a very large list that is updated infrequently when new data is added, so we update the cached list with a cron job (which does requests to /update_test_suites).

Occasionally this causes confusion when people check /report immediately after sending new data with new names, e.g. with a local instance.

**Comment by anniesullie** [comment]
Note that we used to always kick off this job when any new test was added, but we removed the feature after it started getting called too often.

Maybe just do this once if it has never been run?

**Comment by qyearsley** [comment]
This might potentially be useful for local testing, and isn't a very big change: https://codereview.chromium.org/1774213002

Although it *might* potentially lead to confusion if someone tests locally by sending data for test suite A, then looks at the graphs, then sends data for test suite B and then looks at the graphs again; it will be updated for A but not B.
