### ISSUE TITLE
No Link After Starting Bisect From Dashboard

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2104]
Kicked off a return code bisect from the dashboard. Normally I see a link show up after submitting so that I can find my bisect and track it, but didn't seem to get one this time. Ended up digging up the bisect by looking up the slave and jobs running.

**Comment by anniesullie** [comment]
@chrisphn @qyearsley 

Simon, did you see any errors on the js console?

**Comment by simonhatch** [comment]
Ah sorry already closed the tab, I'll keep my eye out next time.

**Comment by simonhatch** [comment]
Uncaught TypeError: Cannot read property 'updateContent' of null
Polymer.showMessage @ base-form.html:45
successCallback @ bisect-form.html:246
handleLoad_ @ simple_xhr.html:41

**Comment by simonhatch** [comment]
Took a quick look since I just had to submit another bisect, looks like report-page is a shadowRoot and message-bar is a child of that

Messing around a bit and grabbing the shadowRoot and searching from there seems to yield the message-bar element properly.

document.getElementById("report-page-TEST").shadowRoot.getElementById("message-bar")

**Comment by chrisphn** [comment]
Thanks for reporting.  Sent a fix for this.

**Comment by chrisphn** [comment]
In the meanwhile,  if you enter a bug id, and track the try job at: 
https://chromeperf.appspot.com/group_report?bug_id=xxxx

**Comment by chrisphn** [comment]
Confirmed this is now fixed.
