### ISSUE TITLE
Move vinn/ to a separate github repo 

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2112]
I am thinking of moving vinn/ project to a separate github repo. I am thinking about putting it in  https://github.com/catapult-project/. Thoughts?

@natduca @Apeliotes @anniesullie

**Comment by natduca** [comment]
Fine by me.

**Comment by anniesullie** [comment]
This is okay with me, too. I'd be happy to create a repo in catapult-project, just let me know the name (I'm assuming `vinn`?).

How would you like to handle testing? Some options, from least difficult to most:
  1. Use the catapult waterfall and only test on rolls
  2. Use Travis CI
  3. Set up a CQ with Linux VMs
  4. Set up a CQ with VMs on Linux/Mac/Windows

If we set up trybots for the vinn/ repo, I think we can share the VMs with additional CQs we set up for more repos in the future.

**Comment by nedn** [comment]
Yes, I intend the repo name to be `vinn`

I would want to pursue option 4, because it's critical for vinn to have test coverage on Windows.

**Comment by fmeawad** [comment]
Can you elaborate on why you want to do that?

**Comment by nedn** [comment]
From a theoretical standpoint, vinn is a self-contained library that does polyfill for html-import. It does not depend on any thing else in catapult, and hence should be a standalone project.

From practical standpoint, It's currently in catapult/third_party/, which make it inconvenient for @vinterstum copy this library to google3. Maturing it to be a in a standalone github repo will make copying catapult projects to google3 easier.

**Comment by fmeawad** [comment]
Thank you for the explanation

**Comment by anniesullie** [comment]
Created https://github.com/catapult-project/vinn/ and gave @nedn admin permissions.

Ned, can you file an issue for a CQ and assign to me?

**Comment by nedn** [comment]
I just copy vinn to the new repo. https://github.com/catapult-project/vinn

However, one issue I am having now is vinn/ depend on mock library, so I would probably need to add mock to vinn/third_party.

When we roll vinn to catapult/third_party, do we need to remove typ from catapult/third_party/vinn/third_party/ dir  & update the reference so it use typ in catapult/third_party/ or do we not care about the problem of duplicate typ libraries?

**Comment by anniesullie** [comment]
@vinterstum - see the previous comment about vinn's third_party dependencies: does it matter from the perspective of importing into google3 whether third_party/vinn has its own third_party?

**Comment by nedn** [comment]
The project is moved here: https://github.com/catapult-project/vinn
