### ISSUE TITLE
Test suite cache is incorrect for speedometer -> ChromiumPerf/linux-release

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2113]
@fmeawad found a case where where the test suites list was missing a master/bot.

Specifically, there is data for speedometer from ChromiumPerf/linux-release: https://chromeperf.appspot.com/report?sid=812510e37c8c76b5b7b5904aa8236873579752fff3e1f5084e18c6f94887cec3

But it's not in the test suites list when I load /report: `$('report-page')[0].testSuites['speedometer']['mas']['ChromiumPerf']` yields a list without 'linux-release'.

It's worth noting that many recent requests to /update_test_suites failed, although some passed.

@chrisphn

**Comment by fmeawad** [comment]
Not sure if it is related, but I could not display the ref values for that benchmark as well.

**Comment by fmeawad** [comment]
Never mind, it seems I can select it if I have only one Metric selected.

**Comment by anniesullie** [comment]
This is fixed now.
