### ISSUE TITLE
webpagereplay/adb_install_cert fails due to invalid su command

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2115]
Not sure if this ever worked, but the [script to install a certificate](https://github.com/catapult-project/catapult/blob/master/telemetry/third_party/webpagereplay/adb_install_cert.py#L59) seems to always fail on newer devices. All of the commands of the form:

    adb shell su -c <cmd>

Fail with the error:

    su: invalid uid/gid '-c'

Since the output is never checked the error message is silently ignored. Probably never noticed since telemetry will use --ignore-certificate-errors when the cert install fails.

**Comment by anniesullie** [comment]
@nedn @eakuefner @dave-2 @simonhatch sounds like crbug.com/593152

**Comment by eakuefner** [comment]
I think this is done.
