### ISSUE TITLE
Share math and regression-detection code between bisect and perf dashboard.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2118]
Original bug: http://crbug.com/537623

> First, it's worth noting that the two systems have different information: Bisect has values for multiple runs on one revision, whereas dashboard has values for multiple revisions in a series. But both are, at some point, looking at two sets of numbers, and evaluating a hypothesis: Null hypothesis: No regression. Alternative hypothesis: The two sets of numbers are different (e.g. because a performance regression occurred).
> 
> The dashboard answers this question now by applying a series of thresholds. The bisect answers this question by applying the t-test.

**Comment by benshayden** [comment]
This is a nice idea in theory, but I haven't heard a way to bridge the algorithmic gap between comparing 2 points and comparing N points. @dave-2 Please feel free to re-open this or open a new bug.
