### ISSUE TITLE
Power samples are displayed with too high precision.

### ISSUE THREAD

**Issue by aschulm** [catapult-project/catapult#2120]
When power samples are selected they are displayed in the table with much higher precision than most power measurement devices can provide. We should limit the precision to 1 mW.

**Comment by aschulm** [comment]
@zeptonaut CC'd

**Comment by aschulm** [comment]
This issue also applies to the per-frame power graph.

**Comment by natduca** [comment]
I woulda liked to see us fix this with units somehow. @petrcermak

**Comment by aschulm** [comment]
I'm happy to switch to a scheme where units takes care of the conversion between the internal storage units for the raw power samples of milliwatts to the display units of watts. It actually may be a super simple change if I understand the goal of units correctly. 

So right now if we have a function in the units code called powerInWatts(). If I understand what you are suggesting then that function really means that it will take a power sample from our raw milliwatt power samples that we store internally and format it as a watt unit power sample. If that's the case then all I can do is just move the divide by 1000 that we are doing in many places as we pass in power samples to powerInWatts() to just doing that inside powerInWatts(). Does that make sense?

**Comment by natduca** [comment]
You could also add a unit called powerInMilliwatts (or get rid of powerInWatts) and then have it stored as milliwatts and modify that unit to present as milliwatts. The idea here is to centralize the string formatting and separate out the storage format from the presentation logic. We don't want code scattered around that goes foo.textContent = round(this.powerInMw) + 'mW'

**Comment by aschulm** [comment]
ok I created a CL to address this problem (https://codereview.chromium.org/1810053002/). We want the power units to be shown in Watts and the internal representation is mW so now the units code is doing the conversion between the two.

However, there is one remaining part of the code where we are doing this conversion outside of the units code. That is in the frame power graph code. The issue is that the design of the units code right now is to output a user-facing string rather than a scalar that can be used in other libraries.

**Comment by aschulm** [comment]
@zeptonaut suggested that we just switch to internal units of Watts in order to cleanly address this problem, I agree that this is the cleanest solution, so I just put up a CL to do this.

**Comment by petrcermak** [comment]
As far as I know, you are the only users of <tt>powerInWatts</tt> (please double-check this), so you can just change the unit's formatting to suit your needs.
