### ISSUE TITLE
Perf dashboard /update_test_suites cron job occasionally fails.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2122]
It is timing out every other run, possibly leading to the test suites dict from not being updated, and this is possibly responsible for #2113 as well.

**Comment by qyearsley** [comment]
Not failing currently, and I haven't yet investigated this. We should re-open a new bug if it starts failing again.

**Comment by chrisphn** [comment]
Still occasionally timeouts.  Specifically update_test_suites.FetchSuitesWithMonitoredProperty for internal and external run just about 10 minutes which is at the cron job limit.  Sent a quick fix to split them up into two cron jobs.

https://chromeperf.appspot.com/get_logs?namespace=task_runner&name=report

**Comment by chrisphn** [comment]
@qyearsley I was wondering if there's rollback since [splitting update_test_suites ](https://github.com/catapult-project/catapult/commit/ff3b6b40b4eb5eb357e6d97356fc5ecbd89be244),  I don't see two /update_test_suites cron jobs.

**Comment by qyearsley** [comment]
Looks like there wasn't a rollback, but the project cron job list isn't updated until `appcfg.py update_cron` is run. Just ran that, and now I see the two separate update_test_suites entries at https://console.developers.google.com/appengine/taskqueues?tab=CRON&project=chromeperf.

**Comment by chrisphn** [comment]
Ah I see.  Thanks

**Comment by benshayden** [comment]
Let's file a new bug about this if it's still a problem.

**Comment by simonhatch** [comment]
FYI: This has been a problem, we were blowing out memory limits a few months back: #3470 

Ideally we just stop computing this thing: #3234
