### ISSUE TITLE
Allow specifying custom import options in MRE

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2125]
Currently, `map_single_trace_cmdline.html` constructs an `ImportOptions` and then sets some default importing options. We should make `extra_import_args` part of `TraceHandle` and then plumb them through to the import stage.

This will fix the issue in https://codereview.chromium.org/1775913004 where we need to be able to set `trackDetailedModelStats`, for example.

**Comment by eakuefner** [comment]
The plan here is the following:

1. Make `map_single_trace.MapSingleTrace` (Python) take an optional dict called extra_import_args
1. Pass it as an extra [`js_arg`](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/perf_insights/perf_insights/map_single_trace.py&l=86) to `map_single_trace_cmdline.html`.
1. Plumb the args through to [`createModelFromTraceData`](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/perf_insights/perf_insights/map_single_trace_cmdline.html&l=20)
1. On the Python side, plumb `extra_import_args` up to `metric_runner`.

@wangzhen127 does this make sense? Would you be willing to write the patch?

**Comment by wangzhen127** [comment]
Thanks for filing this. Will take this and send to you for review.

**Comment by eakuefner** [comment]
Long term, I think we actually want to associate extra_import_args with mappers and metrics somehow. Partially, this is blocked on #2098 since we need `MetricRegistry` to be an `ExtensionRegistry` so we can register import options as metadata.

For now I think it's fine to specify them out of band, and to just make it mandatory for `TimelineBasedMeasurement` to pass `trackDetailedModelStats`.
