### ISSUE TITLE
Add FindValues* helpers to ValueList

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2131]
Telemetry's `PageTestResults` has some good helpers for locating values that match certain characteristics. These helpers are often used by unit tests, and we should emulate this pattern in TBMv2, eg in https://codereview.chromium.org/1775913004/diff/60001/tracing/tracing/metrics/system_health/tracing_metric_test.html.

As a start let's port [`FindValues`](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/results/page_test_results.py#L214) and implement `FindAllValuesNamed` on top of it.

@nedn @petrcermak @wangzhen127

**Comment by wangzhen127** [comment]
This is done along with https://github.com/catapult-project/catapult/commit/76012722c6cf099b9ee3a3f4ec90195661185a8f
