### ISSUE TITLE
Cannot log out/switch account in perf dashboard

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2133]
Clicking on my email account on the top right of https://chromeperf.appspot.com/ doesn't do anything.

**Comment by qyearsley** [comment]
Note: This occurs when logged in with one account, without multi-login. To reproduce, open an incognito window, log in and click the email address link in the upper right.

**Comment by anniesullie** [comment]
This seems to have been some kind of transient issue in app engine which was fixed.
