### ISSUE TITLE
JS stacks not showing up in trace viewer, just as "js"

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#2134]
In Mac canary 51.0.2673.0 , if I turn on v8 samplign I get this in about:tracing

![image](https://cloud.githubusercontent.com/assets/412396/13719371/856fe3b8-e7a9-11e5-8480-94b43d9ba477.png)

Any ideas?

**Comment by natduca** [comment]
@lpy any ideas?

**Comment by fmeawad** [comment]
It appears to be showing the type, which is what is displayed in case we are not in "js" type (i.e. in case of "external").

**Comment by lpy** [comment]
This is fixed.

CL: https://codereview.chromium.org/1799803002/
