### ISSUE TITLE
Dev server tests canary very flaky on Linux & Mac. Switch these to use dependency_manager

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2138]
According to Annie, this is because urls it needs to download chrome return 400 for base_pos_lookup_url

**Comment by anniesullie** [comment]
I added a debugging print, but now the flakiness has disappeared again. I'm guessing there may be a problem with omahaproxy not updating info about versions fast enough.

**Comment by nedn** [comment]
Assign this bug to Kari for migrating dev_server to use dependency_manager for fetching canary & reference.

**Comment by nedn** [comment]
+Kari: can you work on this soon-ish? This is hurting our productivity/ products' stability really badly.

**Comment by nedn** [comment]
Status update in https://docs.google.com/document/d/1u0W7I2YYlPf5dw8dJXt4qL-FV6LtAJx5UWYtRet2s8M/edit?ts=57043822 (Googler only)

**Comment by nedn** [comment]
The dev server tests are failing again today on stable channel, blocking Juan's CL: https://codereview.chromium.org/1857173002/

I don't disable the stable channels because that's the only coverage we have left for dev server tests. @Apeliotes maybe we can prioritize moving the dev server tests to use the stable browser binaries in https://github.com/catapult-project/catapult/blob/master/catapult_base/catapult_base/chrome_binaries.json for now? At least we don't have to worry about updating the stable browser binaries too often.

**Comment by nedn** [comment]
@Apeliotes Can you reenable canary tests that was disabled by https://github.com/catapult-project/catapult/commit/7d8368de94731fb423bfaa4379efd6781cbd82a8?

**Comment by Apeliotes** [comment]
I verified that dev server tests are running on canary after the last cl.

**Comment by Apeliotes** [comment]
Please file a new bug or re-open if more flake is seen.
