### ISSUE TITLE
Perf Dashboard: Can't disassociate graph from bug

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#2142]
Chrome version: 49.0.2623.75 (Linux)
URL: https://chromeperf.appspot.com/group_report?bug_id=571188

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
simple_xhr.html:62 POST https://chromeperf.appspot.com/edit_anomalies 403 ()send @ simple_xhr.html:62Polymer.onRemoveBug @ alert-remove-box.html:53events.dispatchMethod @ polymer.js:9131(anonymous function) @ polymer.js:10715

Please describe the problem:
Can't disassociate graph from bug.

**Comment by anniesullie** [comment]
It looks like you got a 403 error. Are you logged into the perf dashboard? (With the monorail migration, we switched to chromium.org accounts for login)

**Comment by tdresser** [comment]
D'oh.

Sorry for the noise, wasn't logged in...

**Comment by tdresser** [comment]
Er, sorry, I am still getting a 403 when I'm logged in.

**Comment by anniesullie** [comment]
@qyearsley can you take a look? @tdresser logged in with your chromium.org account?

**Comment by tdresser** [comment]
Yes, I'm logged in with my chromium.org account.

**Comment by anniesullie** [comment]
@qyearsley I took a look at the logs. It seems the /edit_anomalies code is not running at all (it should log a warning if it exits with 403). I think the line in app.yaml with `login: required` for /edit_anomalies is causing the 403.

@tdresser could you try logging out and logging in again? Seems like the app engine framework is confused about whether you're logged in.

**Comment by tdresser** [comment]
I'm not sure how to log out.
Logging in with a different account and then logging back in with the @chromium account didn't fix the problem.

**Comment by qyearsley** [comment]
I'm also reproducing this bug, both when logged in with my google.com account and with my chromium.org account.

You *should* be able to log out by clicking on your username in the upper-right-hand corner, although that may not work if you're not using multi-login currently (#2133).

I'm not sure, but maybe now the bug-info element isn't getting the xsrf token and so it isn't able to send it when making the request?

**Comment by qyearsley** [comment]
https://codereview.chromium.org/1812083002/

**Comment by qyearsley** [comment]
I tried this again after the fix was deployed, and I believe it works now.
