### ISSUE TITLE
TBMv1 should not run all legacy timeline based metrics by default

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2143]
The implicit behavior of TBMv1 running all metrics by default is scary because it means that a new benchmark may be buggy due to behavior of an unrelated metric that the author did not expect. Instead, we should force all legacy timeline-based benchmarks to explicitly specify metrics of interest using `SetLegacyTimelineBasedMetrics`. This will require auditing existing benchmarks to make sure they all call this method.

@nedn

**Comment by nedn** [comment]
Totally agree, thanks Ethan!

**Comment by perezju** [comment]
exactly, sgtm!

**Comment by eakuefner** [comment]
Archiving.
