### ISSUE TITLE
DeadlineExceededError when adding add-point tasks to add-point-queue.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2144]
Occasionally in requests to /add_point this error has occurred:

Example stack trace:
```
  File ".../dashboard/add_point.py", line 155, in post
    _AddTasks(data)
  File ".../dashboard/add_point.py", line 264, in _AddTasks
    queue.add_async(task_sublist).get_result()
  File ".../google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File ".../1/google/appengine/api/taskqueue/taskqueue.py", line 1948, in ResultHook
    rpc.check_success()
  File ".../google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File ".../google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
DeadlineExceededError: The API call taskqueue.BulkAdd() took too long to respond and was cancelled.
```

Possible fixes: add fewer tasks at a time?

**Comment by qyearsley** [comment]
We still have some other timeout or deadline exceeded issues when adding new points; see #1439.

**Comment by chrisphn** [comment]
￼Yea it does take sometimes to spawn those tasks.  One method I was going to try awhile ago is add the task data to the datastore, and change /add_point_task_queue to a cron job and have it picks up the task from the datastore.

**Comment by qyearsley** [comment]
If the task data can be reliably added to the datastore, that sounds like a good way of making our data adding more reliable in add_point_queue as well, since if adding the test data fails, we'll be able to go retry until the data is successfully added.

Of course, we'd need to be failure sure that there wouldn't be any time-outs while adding the raw test data tasks to the datastore.
