### ISSUE TITLE
Perf Dashboard: Repeat Bisect

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#2145]
When a bisect fails, it would be convenient if there was an easy way to repeat the bisect exactly.

Currently, I end up manually copying the start and end ranges, and copying the page which was being bisected.

We could just add a "retry" button for failed bisects.

**Comment by anniesullie** [comment]
@dave-2 since he's been thinking about user experience and repeat bisects.

Where would you expect the retry button to be--in the "Bisect results" table?

**Comment by tdresser** [comment]
I was thinking it would probably show up when you expand a failed bisect in the bisect table.

**Comment by chrisphn** [comment]
I had plans to add it in the log:

https://docs.google.com/document/d/1p-enb96GGx_e7VwlfW2rMimS2yEVF5XWjW0h1d_F2IE/edit

**Comment by simonhatch** [comment]
Pinpoint has this.
