### ISSUE TITLE
Update atrace importer (ftrace) to check the marker to sync to monotonic clock

### ISSUE THREAD

**Issue by wangzhen127** [catapult-project/catapult#2147]
atrace or ftrace uses trace_clock. Android 6 or later versions write markers to sync to monotonic clock.

https://android.googlesource.com/platform/frameworks/native/+/marshmallow-release/cmds/atrace/atrace.cpp#264
Look at writeClockSyncMarker(), you will see trace_event_clock_sync in the atrace log.

So for us, we can check this in atrace log and determine the clock domain based on this information for Android 6+ devices.

@nedn @Alex319

**Comment by zeptonaut** [comment]
I talked to @Alex319 about this, and it looks like just setting `name` parameter of the clock sync event will work, like:

```
systrace.sh-8182  [000] 15186.203900: tracing_mark_write: trace_event_clock_sync: name=7WJ3-4JCQ
```
