### ISSUE TITLE
Prevent re-computing metrics 

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2154]
Should there be some explicit mechanism to avoid calling a metric more than once, even after #2098 is closed?

We're structuring some metrics to depend on other metrics: SystemHealthMetrics depends on ResponsivenessMetric, which depends on the animation metrics. This is fine for TBMv2, which will only explicitly run one metric, so if a metric is run more than once, then that's a bug in the metrics.

But, when we build the metric debugger, or perhaps TAP, it might be natural for them to iterate over all registered metrics and run them all. So it might run the animation metrics, then ResponsivenessMetric (which would re-run the animation metrics), then SystemHealthMetrics (which would re-run ResponsivenessMetric (which would re-run the animation metrics again) ).

Just to illustrate the kind of mechanism, I'm imagining a set of the names of metrics that have already been computed on ValueList, with a helper method like ValueList.maybeRunMetric(metric, model).

Calling @eakuefner .

**Comment by eakuefner** [comment]
It seems like we should be able to come up with some kind of a memoization table that maps metric pairs to results. I guess this would work as long as we flush the table between trace imports.

**Comment by benshayden** [comment]
This looks obsolete. Please re-open if you disagree.
