### ISSUE TITLE
Traces hang when importing and require you to click in order to make the import continue

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2156]
Forewarning: I've had problems reproducing this bug, but I still think it's out there.

Occasionally I'll have traces that hang while importing, and the import won't continue until I click somewhere on the screen.

I had this happen for a solid 2 or 3 days in a row a couple of weeks ago. However, on day 4 (when I went to file the bug), I was very frustratingly unable to reproduce it.

@natduca, @petrcermak, have you guys seen this in the past week?

**Comment by lpy** [comment]
I also have this problem.

**Comment by zeptonaut** [comment]
@lpy, have you seen it in any current checkouts?

I've tried to reproduce it on Mac Catapult HEAD, Mac Chrome Canary and Linux Chrome Stable, all unsuccessfully.

**Comment by petrcermak** [comment]
I've observed this for quite a while now, but wasn't sure if I'm not just imagining things. I suspect this could be due to 24f62dd8e7f2c7bf38bc32fb588ba24080487c0a which replaced <tt>requestAnimationFrame</tt> with <tt>requestIdleFrame</tt>.

@skyostil: any thoughts?

**Comment by zeptonaut** [comment]
Hmmm... that is suspicious @petrcermak. I don't see anything in that patch that looks blatantly wrong, but it does seem like it might be related.

**Comment by paulirish** [comment]
I have this all the time too. I'm sure it's due to using rIC. 

If we just yielded with setTimeout, I'd expect it to work much better. However if it's in a background tab, it'd still take forever.. to fix that would be yielding via the postMessage trick in the setImmediate polyfill.

**Comment by zeptonaut** [comment]
I don't think we're too concerned with whether it takes forever when in a background tab. From what I've seen, the current expectation is that no progress is made when tab's in the background anyhow.

**Comment by natduca** [comment]
I think its requestIdleFrame not ticking for some reason. @rmcilroy @skyostil HALPPPPPPPPP

(if anyone is up for it who has a repro, could you try hacking raf.html to not use requestIdleFrame and instead do the fallback path? If the repro goes away we know roughly whats going on)

**Comment by lpy** [comment]
@zeptonaut I have seen it on Catapult HEAD, Chrome Canary on Mac, but I couldn't successfully reproduce it continuously.

**Comment by petrcermak** [comment]
It would be nice if the background issue was fixed as well. I often open multiple traces simultaneously and have to cycle between the tabs to make sure that everything actually gets imported.

**Comment by skyostil** [comment]
If anyone can figure out repro steps that'd be great. Meanwhile, something we can try is passing a timeout argument to rIC so that it is guaranteed to make progress -- even if the tab is backgrounded.

**Comment by petrcermak** [comment]
If passing a timeout could indeed solve the issue, then I think it would be the best and simplest solution at the same time.

**Comment by zeptonaut** [comment]
@natduca verified that this is indeed a problem w/ not having a timeout. Sending out a patch now.

**Comment by skyostil** [comment]
Which platform(s) have you guys seen this bug on?

**Comment by zeptonaut** [comment]
Also, FWIW, it looked like on @natduca's computer it was a matter of just reloading the "SF gate" trace a bunch of times until it got stuck in the "Creating importers" phase. It seemed to happen once every 10 or so times.

The way that he verified that this was the problem was that he changed the code that read:

```javascript
window.requestIdleCallback(function(deadline, didTimeout) {
  processIdleWork(false /* forceAllTasksToRun */, deadline);
});
```

to read:

```javascript
console.log("Scheduled", Date.now());
window.requestIdleCallback(function(deadline, didTimeout) {
  console.log("Run", Date.now());
  processIdleWork(false /* forceAllTasksToRun */, deadline);
});
```

In the case where we let the trace hang for a bit, we saw a large difference between the "Scheduled" and "Run" timestamps. In normal cases, there was very little difference. In the case where we added a timeout, the maximum difference was 100ms.

**Comment by natduca** [comment]
I can repro this on mac canary pretty consistently. SFGate seems to hang on every fifth reload or so. Not sure...

**Comment by skyostil** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=597006

**Comment by zeptonaut** [comment]
**This should be live in Chrome Canary (51.0.2688.0) now, so please update this bug if you see the behavior again in Chrome Canary after 51.0.2688.0 or Catapult HEAD!**

This patch got rolled into Chromium [here](https://codereview.chromium.org/1825693002).
This roll was before last night's deps roll, which branched [here](https://chromium.googlesource.com/chromium/src/+/df372032b408542d782c18cfc057ed729e46665a).
