### ISSUE TITLE
Timeline view jumps to top whenever we select something

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#2157]
Something strange happens in ToT tracing: when you are scrolled down in the track view, and then select select something, the track view scrolls back to the top. This makes analysis really hard.

**Comment by natduca** [comment]
@paulirish who noticed this

**Comment by lpy** [comment]
It looks like when the `textContent` of the tab_view changed, it will scroll back to the top.

comment out this line https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/analysis/analysis_view.html#L157 , select any track, trace viewer will jump back to top only when tab_view changed.

Is there any event get triggered when textContent changed?

**Comment by natduca** [comment]
You're saying when you comment out :157 then the scrolltop doesn't change? Or it still changes, but less often? Or... I guess I got a little confused :)

**Comment by lpy** [comment]
it still changes, but less often.

**Comment by natduca** [comment]
With that commented out, whats a way to repro the change?

**Comment by lpy** [comment]
As we discussed offline.

With Catapult HEAD, this situation won't happen in Chrome Stable, but happen in Chrome Canary. You can use this bisect command
`./tools/bisect-builds.py --use-local-cache -g 369907 -b 381614 -a mac -- http://localhost:8003/tracing_examples/trace_viewer.html\#/tracing/test_data/sfgate.json`
to track down to this revision  https://chromium.googlesource.com/chromium/src/+log/fac6b170019e757ad6695c34429585406994a540..6a3bc7d3aa9920c8797a42ee883d313196adadad

**Comment by cbiesinger** [comment]
Probably https://bugs.chromium.org/p/chromium/issues/detail?id=593209

**Comment by lpy** [comment]
I think this is fixed in Chrome Canary. So I am closing it. If anyone continues to see this issue, please feel free to reopen it.

Thanks Christian.
