### ISSUE TITLE
ES6 feature introduction: arrow functions

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2165]
Arrow functions are the first feature from ES6 that we're trying to introduce into trace viewer. Based on [this thread](https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!msg/tracing/kaDgHPtRGz8/h6DdNhMcBAAJ), I don't think that anyone has any real objections to using arrow functions as long as they work with all of our dependents.

Because they're the first ES6 feature that we're introducing, we need to be extra careful to make sure that we don't break anything downstream in an unanticipated way. I've submitted https://codereview.chromium.org/1358233002/ as a means of introducing arrow functions in a very core part of the code that should break any dependents in an easily-revertable way. 

If, in a couple of weeks, nothing has blown up, we should be able to start using arrow functions throughout the codebase.

cc: @natduca @eakuefner @petrcermak

**Comment by natduca** [comment]
\o/

**Comment by petrcermak** [comment]
I suppose arrow functions can now (after more than 2 weeks of no downstream breakage reports) be marked as "stable". Perhaps we should have a Catapult guide on which ES6 features are considered "safe".

**Comment by eakuefner** [comment]
We do: https://github.com/catapult-project/catapult/blob/master/docs/style-guide.md

Charlie, do you want to update the table and close this bug?

**Comment by zeptonaut** [comment]
I'd love to!
