### ISSUE TITLE
Perf Dashboard: Can't click (i) icon for chart legend tooltip

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2166]
Chrome version: 48.0.2564.116 (Mac)
URL: https://chromeperf.appspot.com/report?sid=d0e366893d57e7b8ed3a3bc29432c1c936e966818c5732fad153a39de2770643

Please copy and paste any errors from JavaScript console (Command+Option+J to open):
```
chart-legend.html:296 Uncaught TypeError: Cannot read property 'set' of null
  Polymer.toggleDescription @ chart-legend.html:296
  events.dispatchMethod @ polymer.js:9131
  (anonymous function) @ polymer.js:10715
```
Please describe the problem:
When I hover over the metric name in the chart legend, I see a little (i) icon, which I am supposed to be able to click or hover on to see a tooltip. I get the above JS error instead.

@chrisphn @qyearsley can you take a look?

**Comment by qyearsley** [comment]
This is another case where we're assuming/requiring that an element with a particular ID exists at the page top-level (not inside of a shadow DOM), and now that it's inside of a polymer Element, it can't be found anymore.

Specifically, there's custom-tooltip element which used to be at the top-level but is currently inside of group-report-page and report-page.

https://github.com/catapult-project/catapult/blob/6fdf7ef/dashboard/dashboard/elements/chart-legend.html#L280

I think that the right thing to do here should be to remove the custom-tooltip from group-report-page and report-page and put one inside chart-legend where it's used.

**Comment by anniesullie** [comment]
That sgtm, assuming it's only used in chart-legend?

**Comment by qyearsley** [comment]
Yep, it's currently only used in chart-tooltip.

Looks like the main difference if it's moved is that its position must be calculated differently when its position is being set.

**Comment by qyearsley** [comment]
Update: I tried moving the custom-tooltip into chart-legend (https://codereview.chromium.org/1820813006), but my version doesn't work properly now.

Specifically, the custom-tooltip set method appears to take an X and Y coordinate that are not relative to the same thing as the X and Y coordinates that I get from the clientX and clientY properties from the click event, or the coordinates that I get crom event.target.getBoundingClientRect().

This *could* potentially be solved by using the same approach as with the warning message box (https://codereview.chromium.org/1771023002) -- move it to the top level outside of the report-page or group-report-page element, but that solution is probably not as neat.

**Comment by qyearsley** [comment]
Moving the tooltip to the top level so it can be found again does work:
https://codereview.chromium.org/1828733002

**Comment by qyearsley** [comment]
Fixed. Filed a separate issue #2172 for refactoring to move custom-tooltip inside of chart-legend which would be a bit neater.
