### ISSUE TITLE
Use the Monorail API to get current bug status to show in chart tooltips.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2175]
Background: In the past, dashboard would fetch current bug status from the issue tracker so that it could show whether a bug was closed or not; this didn't work as-is after the Monorail migration and was removed (https://codereview.chromium.org/1810383003). This would be a helpful little feature to re-add.

**Comment by Apeliotes** [comment]
Monorail API's v1 needs a whitelisted account to get this information. Pinging the monorail team about next steps for using the API.

**Comment by anniesullie** [comment]
I'm going to dupe this against #2271
