### ISSUE TITLE
ES6 feature introduction: classes

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2176]
Since @zeptonaut has initiated a procedure for opening up the tracing codebase to new ES6 features, we want to try classes next.

I'm doing some refactoring on `Numeric` right now, and it occurred to me that this would probably be a good place to start, since numerics are used by a fair amount of unit tested code, but not in so many places that any refactoring that has to be done would be insurmountable.

**Comment by zeptonaut** [comment]
Awesome! Thanks so much for doing this Ethan! I'd love to hear more as progress is made.

**Comment by zeptonaut** [comment]
Hey Ethan, any update on when you might be able to try this out?

**Comment by eakuefner** [comment]
It turns out that `Numeric` is not really a good place to start because it's heavily in flux right now.

I'm happy to push on this but we should find another place to do it -- I think you had another small class in mind?

**Comment by zeptonaut** [comment]
(We talked about this offline, and I suggested either `Event` or `PowerSample` - preferably `Event` because it's so core, as long as it works from Ethan's perspective.)

**Comment by eakuefner** [comment]
I'm working on a big patch to convert the `Event` hierarchy to classes. I don't think we need to exercise the same caution that we did for arrow functions in terms of "stuff blowing up", so I'm fine with this being a big patch, especially since people work with `Event`s so often that making it a class should be a nice usability improvement.

**Comment by eakuefner** [comment]
Revisiting this, folks are already using classes; I think we should turn them on in the style guide.

**Comment by petrcermak** [comment]
Should we convert all classes to use proper classes?

**Comment by benshayden** [comment]
Converting at least the Event hierarchy would fix the prototype.constructor link, which would vastly simplify EventRegistry as discussed in https://codereview.chromium.org/2242733002/

grep says there are 499 instances of '\.prototype = '. So that's a lot of typing. But there are only a dozen or two classes in the Event hierarchy, iirc.
