### ISSUE TITLE
Move grouping_table into /tracing/value

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2181]
This is related to #2180 because `grouping_table` is a pivotal (heh) part of the future of TBMv2.

I think there are two steps here:

1. Move `grouping_table` into /tracing/value/ui
2. Decouple the logic and UI bits into `grouping_table.html` and `ui/grouping_table_span.html`

Once this is done, we can make `ValueList` an instance of the `GroupingTable` class that will result.

@natduca

**Comment by benshayden** [comment]
We decided to make value-set-table use a fixed grouping key sequence, so we don't need grouping-table in value/ui/.
