### ISSUE TITLE
Quick logs are publicly visible, but could could potentially contain internal names/numbers.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2182]
Results from bench_find_anomalies are logged using quick_logger and viewed using /get_logs, which is publicly accessible (and quick logs don't have an internal_only property).

In order to avoid bench_find_anomalies from logging some internal test names, it would be good to make it only use publicly available tests. See #1898 for more context.

Note that even if the results of bench_find_anomalies contain some internal test names, the internal test data will still only be visible to internal users.

**Comment by anniesullie** [comment]
If quick logs don't have an internal only property, how do we handle internal only bisect results?

**Comment by qyearsley** [comment]
Good question -- in theory, anything that's logged with quick_logger could be fetched by anyone currently. For example, without visiting the group_report page for an internal bug, I could see the logged bisect results: https://chromeperf.appspot.com/get_logs?namespace=bisect_result&name=596487.

So far, practically all of such logs just contain links to started bisect jobs -- but after [bug 477448](https://bugs.chromium.org/p/chromium/issues/detail?id=477448) is finally really fixed, those logs will start containing some bisect results.

It seems like the real solution is that we want some quick-logs to be internal only (probably by making quick_logger.QuickLog inheriting from models.InternalOnlyModel), and quick_logger.QuickLogger should be modified to allow the caller to specify that the logs need to be internal-only.

I won't have time to work on this, but I think this looks like a general problem which should be fixed.

**Comment by anniesullie** [comment]
Is there a way to get results from bench_find_anomalies without using quick_logger? Even just the public results?

**Comment by qyearsley** [comment]
The results are also logged using logging.debug now, so making it not store results with quick_logger would be a matter of just removing [_AddReportToLog(results)](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/bench_find_anomalies.py#L236).

`bench_find_anomalies.py` could also be changed to store the results in some other way, e.g. using layered_cache.

**Comment by benshayden** [comment]
Archiving.
