### ISSUE TITLE
Inconsistent information about alerts overlapping when associating alerts with bugs.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2184]
Original issue reported by skyostil: https://bugs.chromium.org/p/chromium/issues/detail?id=586461

The yellow highlighting in that "associate with existing bug" dialog box and the warning "Alerts in bug X do not have overlapping revision range" is inconsistent.

Notes from the original bug:

> The reason for the "Alerts in bug 585757 do not have overlapping revision range" warning is that the alerts associated with that bug (https://chromeperf.appspot.com/group_report?bug_id=585757) already don't have a common intersection (i.e. the intersection of all revision ranges is empty). There is an alert in there with the range [374423, 374480] and another with the range [374245, 374263]. The warning is triggered when, with the addition of the new alert, the intersection would be empty. If the intersection is already empty, this warning will always be shown.
> 
> (In this case, those alerts cannot be caused by the same regression, so it might be helpful to split out some of those alerts into a new bug by selecting them and clicking triage -> new bug).
> 
> Now, the yellow highlighting in the dialog box is less sophisticated and more incorrect. It's only basing the highlighting off of the revision range in the bug title, which only reflects the original alerts when the bug was filed, not additional alerts later associated with that bug.

**Comment by benshayden** [comment]
Archiving. More testing will be done when the feature is added to V2SPA.
