### ISSUE TITLE
Data stoppage alerts not always properly marked recovered

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2187]
Example:
https://chromeperf.appspot.com/group_report?bug_id=591846

These all have new data, but about half of them are not marked recovered.

**Comment by bhavybarca** [comment]
@anniesullie should i take this one or is it fixed ?

**Comment by simonhatch** [comment]
Sorry @bhavybarca, this bug is out of date. Data stoppage alerts no longer exist.
