### ISSUE TITLE
Telemetry traces should contain metadata about what clock they're using

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2189]
Telemetry traces should contain metadata about the clock that Telemetry is using as the source of trace event timestamps. The purpose of this is to help trace viewer identify which clock a trace in the trace event format is using. This will be needed in order to make power tracing work for Telemetry. 

([Link to corresponding Chrome bug, which has more details.](https://bugs.chromium.org/p/chromium/issues/detail?id=597350))

@randalnephew, @nedn and @wangzhen127 suggested that I send this your way. Do you think you'd be able to take it on?

**Comment by zeptonaut** [comment]
A few things that I forgot to mention in the original bug:

The preferred format of this is:

```
{
  traceEvents: [
    ...
  ],
  metadata: {
    'clock-domain': 'LINUX_CLOCK_MONOTONIC'
  }
}
```

where `clock-domain` is one of `LINUX_CLOCK_MONOTONIC` (Linux), `MAC_MACH_ABSOLUTE_TIME` (Mac), `WIN_QPC` (Windows high-res), `WIN_ROLLOVER_PROTECTED_TIME_GET_TIME` (Windows low-res), or `IOS_CF_ABSOLUTE_TIME_MINUS_KERN_BOOTTIME` (iOS, although this probably isn't necessary for Telemetry). 

[Here](https://codereview.chromium.org/1824673002/)'s the corresponding Chrome patch implementing the logic on the Chrome side.

**Comment by natduca** [comment]
Bit confused how this works when you have chrome emitting this data too...

**Comment by nedn** [comment]
Nat: the way telemetry output trace data is currently this:
{
   "traceEvents": [...]  # <- Chrome trace part
   "battor": [.....],
   "telemetry": [....], # <- Telemetry traces, using the same format as traceEvent
}
(code in https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/timeline/trace_data.py#L170)

It currently doesn't have the "meta-data" part yet. And it's unclear how do we put both chrome's clock-domain & telemetry's clock-domain into the metadata part together. I think we can modify so that it becomes:

{
   "chrome": {'traceEvents': [...], 'metadata': {'clock-domain':...}}  # <- Chrome trace part
   "battor": ".....",
   "telemetry": {'traceEvents': [...], 'metadata': {'clock-domain':...}}, # <- Telemetry traces, using the same format as traceEvent
}

**Comment by natduca** [comment]
Hmmm thats interesting! Yeah, maybe if we do that then we should have a
multi_trace_importer.html that recognizes this as a compound file format or
something. I think we should do a 30min design session tomorrow on how
telemetry übertrace and this all work together. The problem here is I
thought when working with charlie on clocksync is that telemetry was
outputting a zip file with all the subfiles inside. Its kinda problematic
that chrome traces aren't outputting a full trace_event file...

**Comment by zeptonaut** [comment]
The way that I understood things, the controller trace is supposed to go in `traceEvents` with any subtraces going in their own field. I'm pretty sure that this would make the format something like this:

```javascript
{
  'traceEvents': {
    // Trace events for Telemetry
  },
  'metadata': {
    // Metadata for Telemetry
  },
  'chrome': {
    'traceEvents': {
      // Trace events for Chrome
    }
    'metadata': {
      // Metadata for Chrome
    }
  }
}
```

This would break backwards compatibility for Telemetry traces, which obviously isn't acceptable. I don't think there's any real _reason_ why the controller trace can't be a subtrace of one of its subtraces - it's not like we use the direction of the parent-child relationship for anything during the import (that I've seen at least).

That means we could have the Telemetry subtrace be a subtrace of Chrome, like:

```javascript
{
  'traceEvents': {
    // Trace events for Chrome
  },
  'metadata': {
    // Metadata for Chrome
  },
  'telemetry': {
    'traceEvents': {
      // Trace events for Telemetry
    }
    'metadata': {
      // Metadata for Telemetry
    }
  }
}
```

In fact, I'm pretty sure we wouldn't have to make any changes to trace viewer in order to get this to work.

**Comment by nedn** [comment]
*That being said, this would break backwards compatibility for Telemetry traces, which obviously isn't acceptable*

Actually I think we don't have to worried too much about backwards compatibility for Telemetry traces. Currently telemetry traces are output under vulcanized form, and we don't have use cases for computing TOT tracing metrics on historical data, at least yet.

Hence we can afford to nail down an ubertrace format that's easy to maintain & expand in the long run, at least for telemetry.

**Comment by zeptonaut** [comment]
Ah, interesting. If we're able to change it, then, I think my preference is for the first format.

**Comment by zeptonaut** [comment]
Oh - one more thing. I've always wondered - why don't we just do something like:

```javascript
{
  'traceEvents': [
    // Trace events for Telemetry
  ],
  'metadata': {
    // Metadata for Telemetry
  },
  'subtraces': [
    {
      'traceEvents': [
        // Subtrace 1 results go here
      ],
      'metadata': {
        // Subtrace 1 metadata goes here
      }
    }
  ]
}
```

This prevents us from having to change trace viewer to search for a `myNewSubtrace` field in the trace event data every time that we add a new subtrace. I don't think we actually _use_ the name of the trace for anything, although it definitely makes the trace more human-readable. For that matter, why have any concept of a "main trace" within the trace event format? Something like:


```javascript
{
  'traces': [
    {
      'traceEvents': [
        // Trace events for Telemetry
      ],
      'metadata': {
        // Metadata for Telemetry
      },
    },
    {
      'traceEvents': [
        // Trace events for Chrome
      ],
      'metadata': {
        // Metadata for Chrome
      },
    },
  ]
}
```

should work perfectly well as just a container for a bunch of traces. AFAIK, there's no real reason that we need a "main" trace for something in the trace event format.

**Comment by zeptonaut** [comment]
[Here's](https://docs.google.com/document/d/1a8c0tQGlwQapTruWoJTQz8n3kjwIcPnx4mnCBvi_guI/edit#heading=h.fm3bwr9tahnb) a doc created based on the decisions made in the meeting yesterday. 

There's quite a bit of work to be done based on the decisions we made. Probably the easiest place to start is to create a trace container importer within trace viewer, which I've created a tracking bug for [here](https://github.com/catapult-project/catapult/issues/2225).
