### ISSUE TITLE
corner case in filterArray doesn't work

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#2191]
An example from this test cast https://github.com/catapult-project/catapult/blob/master/tracing/tracing/base/range_test.html#L350

If we modify it to 

```
test('filter_numericField', function() {
  var r = Range.fromExplicitRange(1, 2);
  var array = [{start: 1},
                     {start: 2},
                     {start: 3},
                     {start: 4}];
  assert.deepEqual([{start: 1}, {start: 2}], r.filterArray(
      array, function(value) {return value.start;}));
});
```

I think this is supposed to pass, but it fails because `filterArray` returns only [{start: 2}]. Looks like we may have a bug in the binary search in filterArray? @chiniforooshan Could you verify this? If it's a bug I think I have a quick fix.

**Comment by chiniforooshan** [comment]
It's a bug!

**Comment by lpy** [comment]
Thanks for the confirmation.

**Comment by lpy** [comment]
This is fixed.
CL: https://codereview.chromium.org/1837043004/
