### ISSUE TITLE
Catapult CQ does not clean up stale *pyc files before running tests

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2198]
https://codereview.chromium.org/1848723002/ removes the python module telemetry.web_perf.metrics.repsonsiveness. It was landed successfully even though there are python tests that depend on that module. (See follow-up work in https://codereview.chromium.org/1845933002/)
I suspect the reason is because catapult cq bot does not remove stale *pyc files before it run the tests.

**Comment by anniesullie** [comment]
This should be **fixed**.
