### ISSUE TITLE
Perf Dashboard: allow the bug reporter to star the issue during the issue creation flow

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#2201]
Chrome version: 51.0.2693.2 (Windows)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
N/A

Please describe the problem:
When viewing that dashboard with my @chromium account, new bugs that I file aren't starred by me by default, which means I don't receive emails as changes are made to the bug. I think the dashboard has always behaved like this, so if you're not open to changing the default behavior, can you consider adding a setting? 

Partial justification - when I directly file new issues in crbug.com with my @chromium account, my account automatically "stars" the issue, so I get email updates without any additional manual steps after the bug is created.

**Comment by anniesullie** [comment]
Implementation notes:
*  You'd want to change the `NewBug` function in [issue_tracker_service.py](https://github.com/catapult-project/catapult/blob/a8a6fb7ea065c2df8ae129ad05ac80ba6ae7cc3a/dashboard/dashboard/issue_tracker_service.py#L122).
*  Looking at the fields editor in the [monorail api explorer](https://apis-explorer.appspot.com/apis-explorer/?base=https://monorail-prod.appspot.com/_ah/api#p/monorail/v1/monorail.issues.insert), you'd want to set `'starred': True` in the `body` field.

**Comment by anniesullie** [comment]
This is fixed.
