### ISSUE TITLE
SurfaceFlinger failures when running memory.memory_health_plan

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2205]
A developer trying to run the memory.memory_health_plan is stumbling with the following error message when trying to run the memory health plan benchmark:

```
File "/usr/local/google2/projects/android/src/third_party/catapult/devil/devil/android/perf/surface_stats_collector.py",
line 43, in Start
    raise Exception('SurfaceFlinger not supported on this device.')
Exception: SurfaceFlinger not supported on this device.
```

There are two issues here:

1. Try to reproduce and diagnose the issue, to see why this SurfaceFlinger is failing (the device is supposed to be a Nexus5 running L), and either fix the issue or provide a better error message.

2. Why is this SurfaceFlinger thing running at all on memory health benchmarks? I can [disable it globally for android](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/telemetry/telemetry/internal/platform/android_platform_backend.py&l=155) and the benchmark still runs fine, so it's probably not needed. But I don't see a way for the benchmark to selectively turn off some tracing agents. It looks like the [tracing_controller_backend](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/telemetry/telemetry/internal/platform/tracing_controller_backend.py&l=61), in fact, always starts all supported tracing agents for the platform. But maybe I'm missing something?

@nedn @primiano @eakuefner

**Comment by nedn** [comment]
Oh, enable_platform_display_trace should be set to False by default. I think we set it to True in https://github.com/catapult-project/catapult/blob/5d8aa077881612bbdc91463ca061e9ebcf3654c9/telemetry/telemetry/web_perf/timeline_based_measurement.py#L176 when we try to port Smoothness to TBM.

**Comment by perezju** [comment]
Ok! Thanks for those pointers, will try to get a CL to disable by default, and enable for smoothness only.

**Comment by nedn** [comment]
Thanks Juan!

**Comment by perezju** [comment]
Fixed!
