### ISSUE TITLE
Add a ListOfTraceValues to collect several traces of a single page

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2214]
When running a benchmark with --pageset-repeat, only the first trace of each page is kept/uploaded to dashboards.

From [crbug.com/599075](https://bugs.chromium.org/p/chromium/issues/detail?id=599075#c9):

> Telemetry team is going to talk about a roadmap here, but probably the right step forward here is to add ListOfTraceValues that:
> 
> 1. Is the result of merging TraceValues, in the same way that ListOfScalarValues is the result of merging ScalarValues, and
> 2. Does everything TraceValue does (in terms of uploading and all that meta stuff) for each trace in the list.

Additionally:

> The dashboard would also have to be modified to store and surface a list of URLs, rather than a single URL, per point.

@eakuefner

**Comment by eakuefner** [comment]
This is going to be comprehensively solved for TBMv2-based using diagnostics. I'm going to archive this bug and then we can revisit it in the context of diagnostics.
