### ISSUE TITLE
Telemetry should make it clear that PageTest is legacy

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2218]
Few teams use telemetry's PageTest to write benchmarks without being aware that it's deprecated. By the time they get to code reviewer, it's usually late, leading to wasteful engineering efforts. We should make it very clear that PageTest architecture is _legacy_.

So to make it clearer, I think we can:
- Rename PageTest to LegacyPageTest. 
- Update the docstring of LegacyPageTest to point to go/tbm2.

**Comment by eakuefner** [comment]
Ned, this is done, right?
