### ISSUE TITLE
Add min/max/std for Numeric

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2222]
We need to track min, max and stddev in `Numeric`. http://www.johndcook.com/blog/standard_deviation/ will probably be helpful here.

@petrcermak @primiano @perezju

**Comment by ulan** [comment]
+1 for min/max tracking. Percentiles would be also very useful.

Since there are already several of stats, how about adding options to the Numeric constructor about what stats to report? The options object would look like:
```
{
   min : true,
   max: false,
   avg : true,
   sum : false,
   cnt : false,
   pct : [50, 95]
}
```

I'd be happy to implement this feature.

**Comment by petrcermak** [comment]
I think it would be better to keep the set of tracked stats the __same across all numerics__ because _(i)_ it's not always clear which stats will be useful at the point where you emit a <tt>Numeric</tt> and _(ii)_ comparing numerics becomes unnecessarily complex. Furthermore:

- <tt>count</tt> is always indirectly tracked because you have counts for individual bins (otherwise there would be no point in having bins in the first place).
- <tt>avg</tt> is the same as <tt>sum</tt> (assuming you have <tt>count</tt>).
- You _cannot_ track percentiles without remembering all values precisely.

I think we should track the following stats on all numerics:

1. <tt>runningSum</tt>
2. <tt>runningSquareSum</tt> (for calculating standard deviation)
3. <tt>min</tt>
4. <tt>max</tt>

Note that <tt>numeric.min</tt> and <tt>numeric.max</tt> currently refer to the range of the central bins of <tt>numeric</tt>, so we might need to use different names (e.g. <tt>runningMin</tt> and <tt>runningMax</tt> for consistency).

**Comment by perezju** [comment]
Yeah, I would also love to have percentiles, but it's impossible to compute them without keeping the full list of values.

Re: stdev, +1 for @eakuefner suggestion, this is what I implemented on the [health dashboard code](https://cs.corp.google.com/clankium/src/clank/build/aupt_tests/utils/series_summary.py?l=54).

As a side not (not for now, but something to keep in mind), at some point we will also want to introduce [pooled stdev](https://en.wikipedia.org/wiki/Pooled_variance) to merge Numerics with data coming from different distributions.

**Comment by ulan** [comment]
> You cannot track percentiles without remembering all values precisely.
> Yeah, I would also love to have percentiles, but it's impossible to compute them without keeping the full list of values.

Numeric has bin counts. We can compute percentile based on that information at least approximately ignoring the underflow/overflow bins. Or am I missing something?

> I think it would be better to keep the set of tracked stats the same across all numerics

I agree that the implementation should be uniform and track all stats. I was referring to reporting the stats in [[link](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/value_list.html#L64)].

> (i) it's not always clear which stats will be useful at the point where you emit a Numeric

Most numerics should use the default options for reporting, which will include all stats. However, there are cases when we know for sure that a stat is not interesting/redundant. For example, in GC metrics we want to report the pause time of the whole GC and pause times for GC phases. The "count" stats of phases are redundant (= GC count), "min" and "sum" are not interesting. It would be great to filter out that noise.

>(ii) comparing numerics becomes unnecessarily complex.

I don't follow, where the complexity comes from?

**Comment by petrcermak** [comment]
> > You cannot track percentiles without remembering all values precisely.
> > Yeah, I would also love to have percentiles, but it's impossible to compute them without keeping the full list of values.
> 
> Numeric has bin counts. We can compute percentile based on that information at least approximately ignoring the underflow/overflow bins. Or am I missing something?

You're right, we can of course approximate percentiles.

> I think it would be better to keep the set of tracked stats the same across all numerics

I agree that the implementation should be uniform and track all stats. I was referring to reporting the stats in [[link](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/value_list.html#L64)].

> (i) it's not always clear which stats will be useful at the point where you emit a Numeric

Most numerics should use the default options for reporting, which will include all stats. However, there are cases when we know for sure that a stat is not interesting/redundant. For example, in GC metrics we want to report the pause time of the whole GC and pause times for GC phases. The "count" stats of phases are redundant (= GC count), "min" and "sum" are not interesting. It would be great to filter out that noise.

>(ii) comparing numerics becomes unnecessarily complex.

I don't follow, where the complexity comes from?

**Comment by petrcermak** [comment]
> > You cannot track percentiles without remembering all values precisely.
> > Yeah, I would also love to have percentiles, but it's impossible to compute them without keeping the full list of values.
> 
> Numeric has bin counts. We can compute percentile based on that information at least approximately ignoring the underflow/overflow bins. Or am I missing something?

You're right, we can of course approximate percentiles.

> > I think it would be better to keep the set of tracked stats the same across all numerics
> 
> I agree that the implementation should be uniform and track all stats. I was referring to reporting the stats in [[link](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/value_list.html#L64)].

As far as I understand (@eakuefner: please correct me if I'm wrong), <tt>ValueList.computeSummaryValuesForNumericValue</tt> is only a temporary hack until Telemetry can fully handle numerics.

> > (i) it's not always clear which stats will be useful at the point where you emit a Numeric
> 
> Most numerics should use the default options for reporting, which will include all stats. However, there are cases when we know for sure that a stat is not interesting/redundant. For example, in GC metrics we want to report the pause time of the whole GC and pause times for GC phases. The "count" stats of phases are redundant (= GC count), "min" and "sum" are not interesting. It would be great to filter out that noise.

I see your point. This depends on whether <tt>ValueList.computeSummaryValuesForNumericValue</tt> is indeed a temporary hack, or not.

> >(ii) comparing numerics becomes unnecessarily complex.
> 
> I don't follow, where the complexity comes from?

This was under the assumption that different <tt>Numeric</tt> objects keep different statistics, but as you explained, that was not your proposal, so my comment is not relevant anymore.

**Comment by eakuefner** [comment]
computeSummaryValuesForNumericValue is a temporary hack; that's correct.

Eventually we intend that numerics should be handled directly by the dashboard.

**Comment by eakuefner** [comment]
Okay, coming back to this as I've been able to claw my way out of my backlog somewhat.

I think that **because** `computeSummaryValuesForNumericValue` is a temporary hack, we can afford to do what @ulan suggests as a workaround until we have a dashboard capable of reasoning about histograms in a dynamic way.

So I agree with the general plan here:

1. By convention, have an option on `NumericValues` that contain `Numeric` (histogram) that's a dict of summary statistics to emit.
2. In `ValueList`, use this dict if present when flattening `Numeric`s, or do the default total/count/avg/std if not.

@ulan, are you still interested to pick this up?

Also, any volunteers to finish out min/max/std? I won't get to it this week, since I'll work on allowing stories to specify grouping keys.

**Comment by ulan** [comment]
Thanks, Ethan. That's awesome and unblocks us until better solution for dashboard arrives. I am interested in implementing the options and min/max/std. I'll upload patches shortly.

**Comment by ulan** [comment]
Now Numeric supports tracking of min,max,std, and percentiles.
