### ISSUE TITLE
Failure of a test suite blocks other suites from running in catapult CQ

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2226]
For example: 
https://codereview.chromium.org/1857173002/ fails because of dev server flakiness problem (https://github.com/catapult-project/catapult/issues/2138). The dev server test failure, however, also block further test suite from running.

Since this is telemetry-only CL, it would be great if the catapult CQ still run telemetry tests regardless of dev server tests' failure, so the cl author can still land the CL.

**Comment by nedn** [comment]
@anniesullie I suspect this could be a few line changes to the catapult cq recipe. Can you confirm?

**Comment by anniesullie** [comment]
yep, see `always_run` here: https://github.com/luci/recipes-py/blob/master/recipe_modules/generator_script/api.py#L36

note this change would make failures slower

**Comment by nedn** [comment]
That's a good point. Since the bots resource are quite limited, probably we better handle this using isolate/swarming testing (https://github.com/catapult-project/catapult/issues/1889)
-- Won't fix --
