### ISSUE TITLE
Catapult CQ down

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2227]
:fire: :fire: :fire:

https://build.chromium.org/p/tryserver.client.catapult/builders/

@anniesullie @nedn

**Comment by nedn** [comment]
@Apeliotes

**Comment by eakuefner** [comment]
I think this thread from chromium-dev is relevant: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/FsOMxGaufOM

**Comment by Apeliotes** [comment]
I'm moving it over to using the dependency manager. I'll just manually update the canary/dev builds until we get the bot running (should be in the next week).

**Comment by petrcermak** [comment]
Looks like this is now fixed (patches are landing), so I'm removing the _"P0"_ label.

**Comment by anniesullie** [comment]
Thanks, Petr! Before we close, still need to get the builds from the dependency manager updated automatically and re-enable canary tests.

**Comment by nedn** [comment]
Let's track that in https://github.com/catapult-project/catapult/issues/2138 & keep this bug about making catapult CLs landable (which is now).
