### ISSUE TITLE
Ensure responsiveness metric shows a regression in case where doghouse project found regressions

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2228]
Folks like dominicc are experimenting with ways to isolate frames in separate renderer processes. The new enable-top-document-isolation flag, for example, should improve responsiveness and efficiency.

We should play with that flag on some sites and check that the metrics bear out our expectations and check that we can explain why.

**Comment by natduca** [comment]
Well, let me clarify: the doghouse project used railscore and railscore said "yes this  is better." People were excited.

Then, kenji went and used doghouse himself. And it was way, way way worse.

So, there exist cases where railscore did *not* predict correctly that the experience was worse. That is quite problematic.

**Comment by nedn** [comment]
How did Kenji figured out that it was way way worse?

**Comment by benshayden** [comment]
The responsiveness metric has [d]evolved.
