### ISSUE TITLE
Add debugging utility for TBM 2.0 metrics

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2229]
@eakuefner

**Comment by nedn** [comment]
Ethan: can you update the tbm2.0 doc to include debugging guidline?

**Comment by eakuefner** [comment]
Yes, once it's landed.

**Comment by nedn** [comment]
Ooops, forgot to reference bug number.
https://codereview.chromium.org/1866043003/ is landed.

**Comment by eakuefner** [comment]
This is **done**. Added instructions to the migration guide: https://docs.google.com/document/d/1kC5ZGOYAzCIv3HJb0hrP4KTD6X1Xmf8n2-nmzbKL00s/edit#

**Comment by nedn** [comment]
Thanks Ethan!
