### ISSUE TITLE
500 error on dashboard page with lots of regressions

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2231]
https://chromeperf.appspot.com/group_report?bug_id=601790

![cbvdy154yxn](https://cloud.githubusercontent.com/assets/3644011/14388217/fbe135c4-fd61-11e5-8e67-fc986000d8fb.png)

**Comment by rschoen** [comment]
Getting the same thing on https://chromeperf.appspot.com/group_report?bug_id=593670

**Comment by benshayden** [comment]
Archiving. If we start to see this kind of error a lot again, then V2SPA can page in alerts using the cursors in the new /api/alerts handler.
