### ISSUE TITLE
Merging crbugs doesn't re-assign alerts

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2233]
I filed crbug.com/601894 on Friday, and then crbug.com/602299 today. Later I realized they were the same root issue, so I merged 602299 into 601894. However, the alerts didn't get moved over, all the ones originally assigned to 602299 are still there:

https://chromeperf.appspot.com/group_report?bug_id=602299

**Comment by rschoen** [comment]
FWIW happened again, when I merged 601797 and 601804 into 601835.

**Comment by rschoen** [comment]
I've been informed this never worked, so adding the right label :)

**Comment by benshayden** [comment]
Archiving. I'm not sure it would be worth the trouble to make the backend detect when crbugs are merged because they could be re-split. V2SPA allows users to unassign and re-assign alerts.
