### ISSUE TITLE
Presubmit parser chokes on arrow functions with braces

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2237]
Consider the following contrived example:

```
function foo(f, x) {
  return f(x);
}

foo(x => {
  doSomeStuff();
  return x + 2;
}, 3);
```

This is a completely valid syntax for an arrow function which executes statements (as compared with the syntax where for example you use () instead of {} to return an expression) but our linter chokes.

A workaround for single-statement expressions which I use in `slice_test` in https://codereview.chromium.org/1877773002 is to simply use (), since function calls without an lvalue are expressions.

**Comment by zeptonaut** [comment]
I think the metabug here might be that we're using the closure linter. As far as I can tell, closure linter doesn't really have any plans to support ES6. The only ES6 syntax test I can find is [here](https://github.com/google/closure-linter/blob/5c27529075bb88bdc45e73008f496dec8438d658/closure_linter/testdata/tokenizer.js#L77):

```javascript
// Syntax tests for ES6:
x = x => x;
```

The [google/closure-linter](https://github.com/google/closure-linter) project hasn't been updated in four months and appears not to have been seriously updated in longer than that. Given the speed with which Javascript is changing, I think it'd be a good idea to consider a newer alternative like [eslint](http://eslint.org/).

However, a shorter-term solution might be called for here. Possibly something like what @petrcermak [did for the for..of statements](https://github.com/catapult-project/catapult/blob/a8a6fb7ea065c2df8ae129ad05ac80ba6ae7cc3a/catapult_build/js_checks.py#L116-L118)?

**Comment by eakuefner** [comment]
I don't think a temporary fix is possible because this is a syntax error, so any possible fix would have to hack up the Closure linter parser. I'd really like it if we could switch to eslint -- how much work would that be?

**Comment by zeptonaut** [comment]
I honestly have no idea. I spent a few minutes looking into it this morning and it looks like it has a nice API with a command line interface and such. The big question mark is what types of warnings/errors it provides compared with closure, along with how easy it is to disable/enable new ones. In my brief investigation, that looked pretty easy.

If @natduca is amenable to the idea of using a new Javascript linter, I think it's worth spending some more time assessing the cost.

**Comment by eakuefner** [comment]
So, one thing is that eslint requires node, which historically we haven't figured out how to make work.

I did some poking around and some Infra code gave me an idea: they have an approach where they basically fetch a node binary (exe on windows, archive on mac/linux) and then use it to provide npm (see https://chromium.googlesource.com/infra/infra/+/master/node/)

It seems like we should be able to use a Catapult-wide `DependencyManager` instance to do exactly this, then provide an npm `package.json` file that lists node deps, and use this script to fetch node and do `npm install`.

@Apeliotes @anniesullie

**Comment by zeptonaut** [comment]
@Apeliotes @anniesullie 

/bump on @eakuefner's question:

>  they have an approach where they basically fetch a node binary (exe on windows, archive on mac/linux) and then use it to provide npm (see https://chromium.googlesource.com/infra/infra/+/master/node/)

> It seems like we should be able to use a Catapult-wide `DependencyManager` instance to do exactly this, then provide an npm `package.json` file that lists node deps, and use this script to fetch node and do `npm install`.

Do either of you dependency manager experts know how hard this would be?

**Comment by anniesullie** [comment]
The dependency manager should be usable for this. Documentation is [here](https://docs.google.com/document/d/1Xj841C1bPCLJrxgCNBsuohLA_XV-vqAbfF0Gx0bf8qI/edit). I won't have a chance to look into it until at least next week, but Charlie if you want to take a look I'm sure Kari and I would both be happy to answer questions.

**Comment by zeptonaut** [comment]
Great! I'll make a note to look into this when I have a few spare hours.

**Comment by zeptonaut** [comment]
Reassigning this to @eakuefner, who thought that he might have some spare time to work on this :)

**Comment by eakuefner** [comment]
Two exciting points:

1. Turns out lighthouse are already using eslint: https://github.com/GoogleChrome/lighthouse/blob/master/.eslintrc
2. What's more, turns out there is already a 'google' eslint config that they extend!

**Comment by zeptonaut** [comment]
Nice! That _is_ exciting news!

**Comment by eakuefner** [comment]
WIP CL: https://codereview.chromium.org/1887323002
Progress update:

1. Got node/npm working on Mac with `BinaryManager` - `w00t!` Thanks @Apeliotes for extensive help over chat.
2. Set up eslint/eslint-config-google/eslint-plugin-html and disabled a bunch of warnings Closure doesn't support (note: there's enormous fixit potential in enabling some of these warnings)

Couple of things before the patch is ready for review are:

1. Add bindings to Node/npm/eslint from Python.
2. Get node/npm working on Linux/Windows

Linting all of tracing all at once takes only a few seconds.

Finally, I want to call out one interesting thing about eslint: the `max-len` warning which warns on line length can ignore lines that match a regex, which we can use to ignore existing `// @suppress longLineCheck`, which a code search reveals is the only kind of Closure suppression we currently use at all in Catapult.

However, this isn't eslint style, so I think there are three possible approaches to dealing with `max-len` warnings initially:

1. Ignore the `@suppress` lines and do a bulk "fix" using eslint to convert these suppressions to eslint style, or
2. Make a hook that checks for warnings on `@suppress` lines and suggests the CL author update those suppressions to eslint style.
3. Continue supporting the `@suppress` style because people are familiar with it.

Option 1 is probably the easier of approaches 1 and 2, depending on how people feel. I'd be okay with 3 too, because the eslint disable syntax is clunkier.

**Comment by eakuefner** [comment]
@anniesullie mentioned that we should probably do a cursory sanity check with folks knowledgeable on security to see if it's okay to fetch node modules from the public registry on the fly like this.

@nedn was wondering if we know who the right folks to ask are yet.

**Comment by eakuefner** [comment]
@anniesullie mentioned that she's met with a TPM from Infra who's given this a green light from a security perspective.

I will sync with @Apeliotes on fixing #2261 next week, and then hook eslint up to `js_checks`.

**Comment by eakuefner** [comment]
Alright, so #2261 turns out to have a trivial fix and I'm trying to standardize the place to put Catapult's node and Python harnesses for it, which I think is probably `catapult_base` but I'm not entirely sure. Once we decide on that, I'll keep pushing on making sure we can at least run eslint reliably on all of the bots, and then have something ready for review.

**Comment by eakuefner** [comment]
This is **fixed**!
