### ISSUE TITLE
devil.android.sdk.fastboot has unfulfilled dependency

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2243]
The [devil.android.sdk.fastboot](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/sdk/fastboot.py#L28) module has an unfulfilled dependency on `android_sdk`, which is not listed in the [devil_dependencies.json](https://github.com/catapult-project/catapult/blob/master/devil/devil/devil_dependencies.json).

The dependency can be found on [//build/android/devil_chromium.json](https://code.google.com/p/chromium/codesearch#chromium/src/build/android/devil_chromium.json&l=22), but that is external to catapult.

I guess we could:
* Move the `android_sdk` out of chromium and into catapult.
* Add a dependency to the `fastboot` binary only, like we do for [`adb`](https://github.com/catapult-project/catapult/blob/master/devil/devil/devil_dependencies.json#L14)

Not sure what would be more appropriate, though.

@randalnephew @jbudorick @Apeliotes

**Comment by perezju** [comment]
Mostly for my own use until a proper fix is in place, the following workaround allows to run `flash_devices.py` if a chromium checkout is available at `$SRC`:

    ANDROID_SDK_ROOT=$SRC/third_party/android_tools/sdk devil/android/tools/flash_device.py -v [path_to_build]

(devil has some legacy support for env vars that, happily, allows to provide a path for the `android_sdk` dependency)

**Comment by jbudorick** [comment]
Sorry, just saw this. We should add fastboot into devil_dependencies.json.

**Comment by randalnephew** [comment]
This should work without your work-around now.
