### ISSUE TITLE
PushChangedFiles does not work if host paths contain symlinks

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2250]
A lot of the logic to compute and compare md5 hashes depends on having stable paths that won't change due to possible symlinks in them.

@jbudorick @agrieve

**Comment by agrieve** [comment]
I've run into this as well, although it's arguable what the behaviour should be (e.g. maybe you want to push symlinks), we don't do that atm either. So, I think we should just have it support symlinks and document it. (don't have a need to work on this myself atm though)

**Comment by perezju** [comment]
I'm going to close this as obsolete. Probably not worth thinking too much about it.
