### ISSUE TITLE
Use Unicode pathnames on Windows.

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2261]
Due to a bug in `ZipFile.extractall`, extracting long paths from zip files can fail. See https://codereview.chromium.org/1887323002 for an example (log file: https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/2706/steps/Node%20Smoke%20Test/logs/stdio).

Possible workaround that @nedn has proposed is the following: http://stackoverflow.com/questions/20520073/a-error-when-unzip-a-zipped-file-that-contains-a-very-long-filename-on-windows-s which could be combined with extended length paths (if you prefix a path with \\\?\ I guess it magically works).

**Comment by zeptonaut** [comment]
+1 for trying the Unicode path names before trying to move to 7zip. That seems like a lot less work (and a lot less maintenance in the future).

**Comment by eakuefner** [comment]
Calling extractall with the dirname prefixed by u'\\\\?\\' actually turns out to work and it's a one-line fix. First I want to make sure that we're standardizing the location where we'll dump these dependencies so we can add it to .gitignore so that bot_update doesn't choke on it (see https://codereview.chromium.org/2262783002 for why actually changing bot_update to just take this into account is too broad of a fix).
