### ISSUE TITLE
Split responsiveness diagnostic values back out

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2262]
Diagnostic values might be a great idea, but the dashboard isn't ready for them yet even if they are.

While the dashboard isn't ready for them yet, the diagnostic values in the responsiveness metric are unusable.

I'll split them back out to top-level values so that they are usable.

**Comment by benshayden** [comment]
@nedn @eakuefner

**Comment by benshayden** [comment]
Nevermind

**Comment by nedn** [comment]
Looks like this is still relevant after latest update?
@natduca

**Comment by benshayden** [comment]
Yeah, I owe y'all a new design doc. It will probably involve 6 Numerics (FP, FMP, response, FPS, discrepancy, latency).
