### ISSUE TITLE
Chrome profile directory should not be stored in /tmp

### ISSUE THREAD

**Issue by gabadie** [catapult-project/catapult#2268]
According to the [original Linux doc of tmpfs](https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt), this file system store everything in ram and the only difference from ramfs is that it allows to do memory page swapping.

> If you compare it to ramfs (which was the template to create tmpfs)
you gain swapping and limit checking. Another similar thing is the RAM
disk (/dev/ram*), which simulates a fixed size hard disk in physical
RAM, where you have to create an ordinary filesystem on top. Ramdisks
cannot swap and you do not have the possibility to resize them. 

As a result, catapult should make sure of what file system the chrome profile directory is stored in benchmark to ensure that the benchmark condition are exactly as same as on every day use.

**Comment by nedn** [comment]
According to @eakuefner, tmpfs & /tmp is not the same thing. "/tmp" folder is just another on disk like any other folders.

**Comment by nedn** [comment]
Won't fix.

**Comment by eakuefner** [comment]
(You can confirm this by running the `mount` command)
