### ISSUE TITLE
Perf Dashboard: Clicking revisions shows you all the graphs

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2269]
Chrome version: 50.0.2661.75 (Linux)
URL: https://chromeperf.appspot.com/

Please describe the problem:

On a page like https://chromeperf.appspot.com/alerts, any number under "revisions" should be a link
 on the graph itself: If I click on a revision, that should include the link to all the alerts for that revision.

![image](https://cloud.githubusercontent.com/assets/7190422/14712093/23b9cf82-07dc-11e6-98b5-a59cd23f0d7f.png)

**Comment by anniesullie** [comment]
Apologies, I'm having trouble understanding what you mean. Is it:

1.  When you click on `388227` in that screenshot, it is a link that goes to https://chromeperf.appspot.com/group_report?rev=388227 (and if you clicked `388303` instead you would get the report for that rev)
2. When you click on `388227-388303` in that screenshot it is a link that goes to https://chromeperf.appspot.com/group_report?rev=388227-388303 (not implemented currently, though see 3 below)
3. When you click on `388227-388303` in that screenshot it is a link that goes to the exact same place as if you had clicked the checkbox at the left for that row and hit the "GRAPH" button (this takes a specific alert ID and shows all overlapping alerts, but I think it has a slightly different presentation than 1 and 2 would)

Something else?

@Apeliotes FYI

**Comment by natorion** [comment]
I meant the third outcome. Thanks for clarifying.

**Comment by simonhatch** [comment]
Demo: https://dev-simonhatch-1cf62889-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down

@natorion is that the requested behaviour?

**Comment by natorion** [comment]
Exactly. One nit: When I hover my mouse cursor over the revision the mouse cursor does not change to a hyperlink mouse cursor.

**Comment by natorion** [comment]
Did something change recently? I triaged V8's general perf alerts (https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=V8%20Perf%20Sheriff) and noticed the following behavior:

1.) I click on the revision for the marked alert
![step1_selectrevision](https://cloud.githubusercontent.com/assets/7190422/23156498/76014be0-f817-11e6-9b87-8899b10e2ad3.png)

2.) Than I get the following result
![revision_select_step2](https://cloud.githubusercontent.com/assets/7190422/23156506/822765d0-f817-11e6-80ed-7725890526d0.png)

Let's compare that to the following workflow:

1.) Select checkbox for the group and click the "Graph" button on the alert page
![step1b](https://cloud.githubusercontent.com/assets/7190422/23156584/e833cf44-f817-11e6-9eea-c2752459657e.png)

2.) See all the alerts from the group on the report page
![step2b](https://cloud.githubusercontent.com/assets/7190422/23156599/f5b60d44-f817-11e6-8b6b-598257991451.png)

I think in the past the two workflows produced the same results. What is strange is that an alert from  RuntimeStats-Ignition shows up. Was there any change to the config recently because I can't recall that we added the Ignition related alerts to our general V8 perf alert. Ignition is normally triaged on a separate rotation (https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=V8%20Ignition%20Perf%20Sheriff) which does not show that alert anymore. Not sure about that though.

What is strange too is that the alerts when I use the second workflow, are not grouped anymore on the report page.

Maybe this is some negative side-effect from other changes?

**Comment by natorion** [comment]
With the following alert the bucketing works as expected:
![works](https://cloud.githubusercontent.com/assets/7190422/23158347/290a185a-f81f-11e6-8892-0b10fae52fa4.png)

There is still a difference to using the Checkbox->Graph button:
Not all alerts of the bucket are automatically selected and thus loaded on the report page.

**Comment by benshayden** [comment]
Archiving. V2SPA simplifies the alerts table. I plan to highlight overlapping alerts and add a button to open overlapping alerts in a new table.
