### ISSUE TITLE
Perf Dashboard: Comments for "Ignore"

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2270]
Chrome version: 50.0.2661.75 (Linux)
URL: https://chromeperf.appspot.com/alerts

Please describe the problem:

When we ignore issues, we should be able to provide a reason for posterity. It should be the light-weight version of filing a bug, explaining there why we don’t fix it and marking it as WontFix.

Maybe it makes sense to really create a bug in the background, adding a comment automatically and close it with WontFix. This at least would keep all the information assigned to it on the issue tracker.

**Comment by anniesullie** [comment]
@Apeliotes

**Comment by anniesullie** [comment]
I like the implementation suggestion (create a WontFix bug under the hood and associate the alert with it)

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917847
