### ISSUE TITLE
Perf Dashboard: Different colors for triaged alerts

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2271]
Chrome version: 50.0.2661.75 (Linux)
URL: https://chromeperf.appspot.com/alerts

Please describe the problem:

Issues with assigned bugs are marked black. It would be interesting to have a color indicator about the actual status of the bug e.g.:

-Black: Still open
-Light green: Fixed
-Light red: WontFix

This would enable one to quickly identify accepted performance hits (light red). This is especially interesting when investigating reported performance regressions from users.

**Comment by anniesullie** [comment]
@Apeliotes

**Comment by benshayden** [comment]
Archiving. Will keep this in mind when adding alerts to V2SPA.
