### ISSUE TITLE
Perf Dashboard: Sorting in group_report creates strange results

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2272]
Chrome version: 50.0.2661.75 (Linux)
URL: https://chromeperf.appspot.com/alerts

Please describe the problem:

Repro:
-Open https://chromeperf.appspot.com/group_report?rev=375485
-Show improvements
-Sort by "Delta %"

Observe how there are a handful of red numbers in the rightmost column. Now click any of the column headers to sort. Observe how all the red numbers but one disappear, and won't come back no matter which other column you sort by.
It's also suspicious that all results are from Android. And most of them are for a range of about 500 commits, which means they probably don't even apply to the revision I was interested in.

**Comment by anniesullie** [comment]
@Apeliotes this is the bug from the email you were cc-ed on.

**Comment by simonhatch** [comment]
Is this still valid? I'm unable to reproduce.

This code has changed substantially since the issue was logged. I did a bunch of work in here for the polymer 1.0 migration.

**Comment by anniesullie** [comment]
@jessimb Did some fixes to group sorting a few weeks ago.

**Comment by simonhatch** [comment]
I'll mark it closed, don't see anything resembling behaviour described by @natorion
