### ISSUE TITLE
Perf Dashboard: Chromeperf only renders on Chrome but no other browser

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2273]
Chrome version: 50.0.2661.75 (Linux)
URL: https://chromeperf.appspot.com/alerts

Please describe the problem:

Chromeperf graphs like https://chromeperf.appspot.com/report?sid=d56a657cd1ca3c0b0435b2b37c0c731f49f987ab5454ab1ffd63b4ee1faefa62&start_rev=381139&end_rev=383898 do not render on other browsers than Chrome.

See https://twitter.com/cpeterso/status/720079260635901953 for more context.

**Comment by anniesullie** [comment]
@Apeliotes let's take a look at this during polymer 1.0 migration--I think we are missing a script include for the polymer polyfill.

**Comment by eakuefner** [comment]
This has since been fixed.
