### ISSUE TITLE
memory-infra UI does not show gpu category if contains only memtrack

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2277]
The attached trace has only gpu/android_memtrack dumps (which have no size column, only pss). If there is no other gpu/ dump with a size, the gpu column is not shown at all.

[attached trace](https://drive.google.com/open?id=0B3KuDeqD-lVJYzU5MHA1cE8xa0U)

**Comment by petrcermak** [comment]
Fix pending (https://codereview.chromium.org/1919783002):

![memtrack_fallback](https://cloud.githubusercontent.com/assets/2546601/14783510/02ff5442-0ae8-11e6-803d-cf81ef2019e5.png)

**Comment by petrcermak** [comment]
This is now __done__ :white_check_mark:
