### ISSUE TITLE
When launching bisect jobs on windows, the command does not need to be prepended with 'python'.

### ISSUE THREAD

**Issue by ro-berto** [catapult-project/catapult#2283]
Since we have moved bisect to use runtest.py instead of running the naked command sent by dashboard, it is no longer necessary to special case windows this way.

**Comment by catleeball** [comment]
Thanks for flagging this! I just made a [pull request](https://github.com/catapult-project/catapult/pull/2303) trimming the bit where bisect bot prepends "python" to commands on Windows.

**Comment by catleeball** [comment]
Change was made at https://codereview.chromium.org/1939153002 , I'll close this bug out. Thanks again!
