### ISSUE TITLE
Move all the implementation of tracing/bin/merge_traces to a module

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2284]
@natduca  comment:
"The style in bin/ is to have the launcher script to be thin: have the
script just tweak the path and then import a module of the same name and then
call main on that.

i'd appreciate it if you could use that style here.

the reason is that this ensures that

cd bin/
./merge_traces

causes imports of other python modules have the same global python import
__name__ as if you did ./bin/merge_traces"

My other comment is by moving the builk of the logic to a module, it makes it easy to write test & share code later.

**Comment by petrcermak** [comment]
SGTM. I'll take care of this at some point in the (hopefully) near future.

**Comment by petrcermak** [comment]
This is now __done__ :white_check_mark:
