### ISSUE TITLE
Perf Dashboard: Unable to file new bugs

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2288]
Chrome version: 51.0.2704.29 (Linux)
URL: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5KPWogoM

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
```
triage-dialog.html:365 Uncaught TypeError: this.template is not a function

getBugTitleForAnomaly @ triage-dialog.html:365
getBugTitle @ triage-dialog.html:306
fileNewBug @ triage-dialog.html:196
```

Please describe the problem:
When I click on the "new bug" button in the triage dialog (either above the alerts table or in a tooltip), nothing happens.

This is broken in the latest version (clean-sullivan-377e8186), but works in the previous clean version (clean-sullivan-5021b9c2).

**Comment by qyearsley** [comment]
Fix is https://codereview.chromium.org/1931803004/ - fix is now live and filing bugs works with the current version

**Comment by anniesullie** [comment]
This is fixed.
