### ISSUE TITLE
Perf Dashboard: Improvements toggle on group_reports page doesn't do anything

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2289]
Chrome version: 51.0.2704.29 (Linux)
URL: https://chromeperf.appspot.com/group_report?rev=390000

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

```
group-report-page.html:164
Uncaught TypeError: improvementsToggle.hasAttribute is not a function
```

Please describe the problem:
Upon clicking the "show all improvements" button, it changes color, but the URL of the page doesn't change as I expected, and the above error appears in the console.

Note, however, that this bug isn't blocking anything in this particular case, since when rev= is in the query parameters, all improvements are shown by default anyway (e.g. https://chromeperf.appspot.com/group_report?rev=390116)

A better behavior might be: on the group report page, the "show all improvements" button could be "on" to start with; clicking it might then turn it off, hiding any improvement alerts.

**Comment by natorion** [comment]
The button is still not working. The error message is not shown anymore though.

When triaging alerts it would be a help to see the positive impact of a change e.g. https://chromeperf.appspot.com/group_report?sid=adc5f471c19c4cef3c43ea072df81a19dae14423100c76cd5e44e11a9a442b9c to assess if it is worth reporting.

Suggestion: Either remove the button altogether or make it working again. Currently it is missleading. Maybe open a a link to group_report?rev=xxx in a separate window if the button is clicked?

**Comment by anniesullie** [comment]
@jessimb @eakuefner @benshayden Can one of you take a look?

**Comment by eakuefner** [comment]
I think this is done.
