### ISSUE TITLE
Add hotkey to select all power samples that are within the timespan of the current selection

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2290]
The [SingleAsyncSliceSubview](https://github.com/catapult-project/catapult/blob/a8a6fb7ea065c2df8ae129ad05ac80ba6ae7cc3a/tracing/tracing/ui/analysis/single_async_slice_sub_view.html) currently doesn't provide any information about how much power was consumed during that slice. @aschulm mentioned that this would have been really useful when tracing through the libvpx stuff that he did recently.

I think that we can access the model through the `selection` object that's passed in. I think that each `Event` has a `model` object, so you can get to the `PowerSeries` via `model.device.powerSeries`, and then you can access the power samples from there. 

@Alex319 do you think that you could take this on?

**Comment by Alex319** [comment]
I can work on this issue.

**Comment by zeptonaut** [comment]
@Alex319 we should get this assigned to you as soon as you've joined the Google Github org. I sent you some instructions via email.

**Comment by Alex319** [comment]
After discussion this morning, we decided that the best way to implement this feature is not to add something to the model (as this will require adding this to lots of different views) but rather to add a hotkey that selects all the power samples from the timespan of the current selection. That way the user will only need to press one key to get the amount of power used in the timespan of the current selection, regardless of what the current selection consists of.

**Comment by zeptonaut** [comment]
Awesome. Thanks for the update Alex!

**Comment by zeptonaut** [comment]
Hey Alex, are we okay to close this out now?

**Comment by Alex319** [comment]
Yes
