### ISSUE TITLE
The semantics of --pageset-repeat is not clear

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2294]
Splitting off from [crbug/592380](https://bugs.chromium.org/p/chromium/issues/detail?id=592380)

The main point of the discussion is on whether --pageset-repeat should tear down the state (close and reopen a browser) between iterations or not.

I'll try to summarize the main contention points:

Tearing down the state:
* keeps different measurements of the same page statistically independent
* allows to reduce noise in measurements

*Not* tearing down the state [current behavior]:
* stresses the browser by creating a longer running story set
* allows to catch memory leaks that are not apparent on a single iteration

Copying the last comment from @nedn :

> Anyway, another reason why one should not use pageset-repeat for the purpose of stress testing the browser is telemetry treats page, e.g: google.com, in the first run the same way as in the 10th run. Hence for monitoring purpose, all you see is the summarized value of 10 runs of google.com which are not really statistically independent.
>
> Instead of using pageset-repeat, you should do:
>
>     class MemoryStorSet:
>       def __init__(self):
>          self.AddStory(GooglePage(..))  # Just navigate to google.com
>          ... 
>          ...
>          self.AddStory(GoogleHeavyPage())  # Navigate to google.com and make a lot of search queries
>          ...
>          ...
>
> This would allow you to track the memory metrics of the same google.com pages in two very different settings: when the browser is relatively cold & when it's has been around for a long time. I would expect this would also help drive down the noise a bit.

@primiano @anniesullie @dave-2 @picksi

**Comment by perezju** [comment]
Replying to @nedn :

When not tearing down the state, in fact, summarizing values for different results of the same page (*precisely* because they are not statistically independent) is what allows to easily spot regressions.

The `results.html`, in fact, provides a nice little red warning with the text "Detected a time dependency with slope ..." when such a leak is apparent from running the same page several times across different iterations.

Just adding more pages or more long running pages does not give us this benefit.

So I guess we really want to support these two different use cases.

**Comment by primiano** [comment]
+1 to the general need to figure out a way to make a benchmark longer. Not sure if --pageset-repeat or something else (can a benchmark itself have args?)
Will --page-repeat tear down the state?
Also, whatever thing we end up deciding here it would be nice if it was *clearly* documented in the --help section.

**Comment by perezju** [comment]
From our recent discussions it's clear we have a need for both kinds of benchmarks: some more "deterministic" and some more "realistic".

My proposal is to add a `ShouldTearDownStateAfterEachStorySetRun` method (similar to the existing one to tear down after each individual `Story`) that defaults to **`True`** in order to make all of our current benchmarks more deterministic. But allow new benchmarks to override this value when wanting to stress test the browser and keep it open for the whole duration of the test.

CL ready for review on it's way.

[(design doc with more details about rationale)](https://docs.google.com/document/d/1sa0u_-7P0r6ADPZX5cPh3VCpCMshWNVlwkgyBX5nY3E/edit#heading=h.r2m31qt1c8r6)

**Comment by perezju** [comment]
This is done. The final implementation is:

* Benchmarks by default tear down the state between page set repeats; this is what most users expect and yields more repeatable/deterministic results.
* Benchmark authors can, if really needed, switch to the alternative behavior to keep the browser open for longer periods of time, helping to catch leaks, etc.

These are now documented in [telemetry.benchmark](https://github.com/catapult-project/catapult/blob/b3e03f627f8f905a5ed63725c07f615dc1389eac/telemetry/telemetry/benchmark.py#L101).
