### ISSUE TITLE
BattOr smoke test in the CQ fails but the "smoke test" CQ step remains yellow

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2299]
It looks like even after the BattOr smoke test fails:

![screenshot from 2016-04-29 16 53 32](https://cloud.githubusercontent.com/assets/1407397/14929434/56c00fe0-0e2b-11e6-854e-664643e549c3.png)

the step in the try job continues to be yellow:

![unnamed image 4](https://cloud.githubusercontent.com/assets/1407397/14929409/41f16208-0e2b-11e6-9734-4f2c4f985a0f.png)

Randy, could you look into why this might be happening? [Here's the try job](https://codereview.chromium.org/1932373002/) in question: The good news is that it fails!

**Comment by randalnephew** [comment]
Problem was on windows the process hangs and crashes. We have work arounds for this, but the workaround failed when it failed during StartTracing. This problem has been fixed.
