### ISSUE TITLE
Make selecting of power samples faster

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2300]
When you select a range of power samples, the code iterates through the power samples and independently checks, for each one, whether it is in the range. Since the power samples are all in order with a fixed distance between each one, it should be possible to get the correct range in a faster way to improve UI responsiveness.

**Comment by Alex319** [comment]
Based on some other changes that I made, it looks like the culprit is not the looping through to check what is selected, but rather just the time it takes to print out the whole table of power samples in the UI. A solution may be to just not print out that table.

**Comment by zeptonaut** [comment]
Thanks so much for looking into this Alex!
