### ISSUE TITLE
Perf Dashboard: Can't see perf results of v8/JSTests/PropertyQueries.

### ISSUE THREAD

**Issue by isheludko** [catapult-project/catapult#2301]
This is a copy of crbug/607124.

When I try to open perf results for v8/xxx/JSTests/PropertyQueries on chromeperf.appspot.com I don't see any graphs. However if I also specify a test name I can see the graph just fine (for example, v8/xxx/JSTests/PropertyQueries/in--INTERN-prop).

I did two attempts to add PropertyQueries benchmark. The first attempt produced too many graphs so I reduced them to the following set:

in--INTERN-prop
in--DEINTERN-prop
in--NE-INTERN-prop
in--NE-DEINTERN-prop
in--el
in--el-str
in--NE-el
Object.hasOwnProperty--INTERN-prop
Object.hasOwnProperty--DEINTERN-prop
Object.hasOwnProperty--NE-INTERN-prop
Object.hasOwnProperty--NE-DEINTERN-prop
Object.hasOwnProperty--el
Object.hasOwnProperty--el-str
Object.hasOwnProperty--NE-el

I would very appreciate it if you could also remove the outdated graphs. It is also fine at this moment to clear all the perf data collected for PropertyQueries benchmark and let it start from scratch.

**Comment by anniesullie** [comment]
Thanks for the report! Strangely, I thought I was able to reproduce the first part (not seeing PropertyQueries in the second Subtest menu) when I read this report, but when I started to debug it the data all the sudden started showing up. Can you let me know if you're still seeing that problem, and if so, which bot?

I'll work on deleting the data that's not in the set above.

**Comment by anniesullie** [comment]
Oh actually when i was able to reproduce, I was looking at N5/N7 bots, which do not have data for this test.

**Comment by anniesullie** [comment]
All the old test data is deleted. I'm not able to reproduce the part where you can't see data on bots that have the data, but please re-open with clear repro steps (ideally checking the logs of the bot that is supposed to be uploading data, if it's just certain bots).

**Comment by isheludko** [comment]
It works now, thanks!
