### ISSUE TITLE
Variant lines on perf dashboard

### ISSUE THREAD

**Issue by catleeball** [catapult-project/catapult#2308]
From issue #2056 , @picksi suggested that we have a way other than colors to differentiate lines on the perf dashboard to accommodate for color blindness and visual impairments. This could be done with dotted lines, or with symbols marking lines such as in [this image](https://screenshot.googleplex.com/LnVDuY1nYV5.png).

**Comment by benshayden** [comment]
Archiving. V2SPA thickens lines when the corresponding legend entry is hovered. Symbols would add significant visual noise to charts that are already very noisy.
