### ISSUE TITLE
Dashboard tooltips are pretty janky

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2310]
It's hard to click a link, the legend occludes the tooltip sometimes. Let's circle back on this after the Polymer 1.0 migration.

**Comment by benshayden** [comment]
Polymer 1.0 has landed. Any more information on what is going wrong with tooltips and how to fix it? @Apeliotes @anniesullie @eakuefner

**Comment by benshayden** [comment]
Let's close this in favor of redesigning the legend.
