### ISSUE TITLE
"Value already has a tir_label" warnings are too spammy

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2312]
They're filling the output logs of memory health benchmark runs with lots of noise, which could make it hard to diagnose real failures.

**Comment by petrcermak** [comment]
@nedn @eakuefner 

We could add a Boolean <tt>_existing_tir_label_warning_already_shown</tt> field to [<tt>PageTestResults</tt>](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/results/page_test_results.py#L24) and only display the warning once. I'm happy to implement this. WDYT?

**Comment by perezju** [comment]
Ah, I had already started with [this](https://codereview.chromium.org/1951883002/)
