### ISSUE TITLE
page_cycler.typical_25 doesn't properly select "core" traces

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2313]
1) Go to https://chromeperf.appspot.com/report
2) Choose a test suite (page_cycler.typical_25)
3) Choose a bot (chromium-rel-win7-single)
4) Choose a metric (warm_times)
5) Click add
6) Space for new graph appears, but it's all collapsed and no loading spinner https://screenshot.googleplex.com/WjZPR1C695Y
7) Reloading fixes the issue.... kinda. I then have to check the metric, but that may be a separate bug. https://screenshot.googleplex.com/a61z35bsa2C

**Comment by anniesullie** [comment]
This is very strange! It happens consistently for me with your repo steps above, but if I pick a different test (ChromiumPerf/android-nexus5X/blink_perf.parser/html-parser) everything works fine.

When I select the test, the post data sent to /graph_json is:
```
{"test_path_dict":{"ChromiumPerf/chromium-rel-win7-single/page_cycler.typical_25/warm_times":[]}}
```
And the response is:
```
{"data": {}, "annotations": {}, "error_bars": {}}
```

When I reload the page, the post data sent to /graph_json is:
```
{"sid":"7c47152b24d7899825bb0c54c81c2a0beebdce9757949d7b54b265a300e2a89c","test_path_dict":{"ChromiumPerf/chromium-rel-win7-single/page_cycler.typical_25/warm_times":[]},"is_selected":true}
```

And the full data comes back. I think we'll need to add logging to /graph_json to see what is happening.

@Apeliotes @dave-2

**Comment by anniesullie** [comment]
I took another quick look. Two things are going wrong:

1. Now that we have ref builds, a 25-page page set with ref builds bumps up against the 50 page limit. I sent https://codereview.chromium.org/1950133004/ to increase it.
2. The dashboard is supposed to send two requests: one for the tests that will be selected by default, and one for the ones that will not. It's not selecting the summary metrics (page_load_time and page_load_time_ref) by default.

The second issue needs more investigation.

**Comment by benshayden** [comment]
Archiving. V2SPA organizes timeseries differently, without the "core" concept.
