### ISSUE TITLE
Error updating FYI status in update_bug_with_results

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2317]
This appears to be the cause of the stackdriver alert about UpdateBugWithResults.

I checked go/chromeperf-errors and found this:

```
KeyError: 'status'
at _CheckFYIBisectJob():162 (update_bug_with_results.py:162 in /base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard)
at _CheckJob():130 (update_bug_with_results.py:130 in /base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard)
at get():89 (update_bug_with_results.py:89 in /base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard)
```

Searching go/chromeperf-logs for `update_bug_with_results` yields several requests with logs including this:

```
08:33:01.436
Checking job 5873099786944512 (/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard/update_bug_with_results.py:108)
08:33:01.436
Checking FYI bisect job (/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard/update_bug_with_results.py:129)
08:33:01.437
URL being requested: GET https://cr-buildbucket.appspot.com/_ah/api/discovery/v1/apis/buildbucket/v1/rest?userIp=0.1.0.1 (/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/apiclient/googleapiclient/discovery.py:194)
08:33:01.487
URL being requested: GET https://cr-buildbucket.appspot.com/_ah/api/buildbucket/v1/builds/9013561478198864672?alt=json (/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/apiclient/googleapiclient/discovery.py:765)
08:33:01.568
Caught Exception KeyError: 'status' (/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard/update_bug_with_results.py:92)
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard/update_bug_with_results.py", line 89, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard/update_bug_with_results.py", line 130, in _CheckJob
    _CheckFYIBisectJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-829c320e.392562520478404832/dashboard/update_bug_with_results.py", line 162, in _CheckFYIBisectJob
    if job.results_data['status'] == FAILED or error_message:
KeyError: 'status'
```

The `URL being requested` lines appear to come from `buildbucket_service.GetJobStatus` called from `_ValidateBuildbucketResponse`. A few things seem strange to me:
  1. It's not clear where `job.results_data` is coming from. Should it have been set in `/post_bisect_results`? It appears to be set in `/update_bug_with_results` in `_ValidateBuildbucketResponse` lines 390-392, but that code does not copy the full data from the buildbucket API, only the url. Why?
  2. The actual job data says the status is completed, but it's not set. Why? (See https://cr-buildbucket.appspot.com/_ah/api/buildbucket/v1/builds/9013561478198864672?alt=json)
  3. Do we always expect to have a status in `_CheckFYIBisectJob`? Should `_CheckFYIBisectJob` say `job.results_data.get('status')` on line 162? Or should it log a clear error and throw an exception if status is not present?

@vuppalapu @ro-berto @dave-2 @Apeliotes

**Comment by vuppalapu** [comment]
> It's not clear where job.results_data is coming from. Should it have been set in /post_bisect_results? It > appears to be set in /update_bug_with_results in _ValidateBuildbucketResponse lines 390-392, but >that code does not copy the full data from the buildbucket API, only the url. Why?
job.results_data is set only when the dashboard receives results from the bisect bot, here https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/post_bisect_results.py#L73. In this case since the job didn't get to the step where it post results to the dashboard, tryjob's results_data was never set. As a special case for Bisect FYI jobs, we also check if the actual job has failed on the build bot by querying buildbcket API. Please not job.results_data is not same as full data from buildbucket API, this variable stores data received from bisect bot and partial data from buildbucket api.

>The actual job data says the status is completed, but it's not set. Why? (See https://cr->buildbucket.appspot.com/_ah/api/buildbucket/v1/builds/9013561478198864672?alt=json)
The results_data.status is the status set by the bisect recipe on when it tries to post the results back to dashboard, https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/recipe_modules/auto_bisect/bisector.py&q=post_result%20file:%5Ebuild/scripts/slave/recipe_modules/auto_bisect/&sq=package:chromium&type=cs&l=877

>Do we always expect to have a status in _CheckFYIBisectJob? Should _CheckFYIBisectJob say >job.results_data.get('status') on line 162? Or should it log a clear error and throw an exception if >status is not present?
Yes, we should job.results_data.get('status'), uploaded cl with changes. https://codereview.chromium.org/1946993005/patch/1/10001

**Comment by anniesullie** [comment]
> > It's not clear where job.results_data is coming from. Should it have been set in /post_bisect_results? It appears to be set in /update_bug_with_results in _ValidateBuildbucketResponse lines 390-392, but that code does not copy the full data from the buildbucket API, only the url. Why?

> job.results_data is set only when the dashboard receives results from the bisect bot, here https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/post_bisect_results.py#L73.

It's also set here, which seems wrong to me: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/update_bug_with_results.py#L391

Shouldn't it be set only in one place?

> In this case since the job didn't get to the step where it post results to the dashboard, tryjob's results_data was never set. As a special case for Bisect FYI jobs, we also check if the actual job has failed on the build bot by querying buildbcket API. Please not job.results_data is not same as full data from buildbucket API, this variable stores data received from bisect bot and partial data from buildbucket api.

> > The actual job data says the status is completed, but it's not set. Why? (See https://cr-buildbucket.appspot.com/_ah/api/buildbucket/v1/builds/9013561478198864672?alt=json)

> The results_data.status is the status set by the bisect recipe on when it tries to post the results back to dashboard, https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/recipe_modules/auto_bisect/bisector.py&q=post_result%20file:%5Ebuild/scripts/slave/recipe_modules/auto_bisect/&sq=package:chromium&type=cs&l=877

So it never gets reconciled?

> > Do we always expect to have a status in _CheckFYIBisectJob? Should _CheckFYIBisectJob say job.results_data.get('status') on line 162? Or should it log a clear error and throw an exception if status 
is not present?

> Yes, we should use ob.results_data.get('status'), uploaded cl with changes. https://codereview.chromium.org/1946993005/patch/1/10001

I'll ask for some clarifying comments in the CL review.

**Comment by nedn** [comment]
Is this bug  fixed?

**Comment by vuppalapu** [comment]
Yes, this is fixed
