### ISSUE TITLE
Make an end to end test between telemetry's result & dashboard results handling

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2319]
Working on telemetry's value system is hard because a not careful change can break the integration between telemetry & dashboard (example: [crbug.com/606698](http://crbug.com/606698)). Now the two projects are in the same code base, it would be ideal if we can make an end to end test between telemetry's result & dashboard results handling.

The easiest smoke test could be verifying that dash_board.add_point can handle different chartjson produced by telemetry. 
However, the most ideal smoke test should treat telemetry code base & dashboard code base as black boxes.
@anniesullie @eakuefner 
FYI: @perezju @petrcermak @benshayden

**Comment by anniesullie** [comment]
From the perf dashboard side, a few ideas:

  * You could run the dashboard devserver, then sends data to localhost:8080/add_point
  * You could make something that uses a mock server like the existing test, but pulls in both codebases: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/add_point_test.py

**Comment by nedn** [comment]
Annie: I think the first idea seems most promising. We can do something like create a dummy telemetry benchmark, run it to produce a chart-results.json file, then create a local dashboard server & send that chart-results.json file to localhost:8080/add_point

Do we have any integration test in catapult CQ that start up the local dashboard server yet?

**Comment by anniesullie** [comment]
Nope, all the catapult CQ dashboard tests use the mock server. The catapult recipe does pull in the app engine SDK, so it should be possible to start a dev server though.

**Comment by anniesullie** [comment]
Ethan, this is something to consider as you think about migrating dashboard towards tbm2

**Comment by eakuefner** [comment]
I'm probably going to treat this as one of my Friday fixit tasks.

**Comment by benshayden** [comment]
@simonhatch @eakuefner Is this still necessary in a Histogram Pipeline world?

**Comment by eakuefner** [comment]
We spoke to @nedn about something like this when we were in Waterloo, but I'm definitely not actively working on this. I think an end-to-end test that uses a devserver would be pretty nice, but I move to archive this and file a fresh bug if someone actually wants to go ahead with this. I recall that @ehanley324 may have been working on something similar, and if so she probably has a newer bug than this.
