### ISSUE TITLE
Power series model will report power used when no samples are present

### ISSUE THREAD

**Issue by randalnephew** [catapult-project/catapult#2324]
model.device.powerSeries.getSamplesWithinRange(1000000, 1000001)
[]
model.device.powerSeries.getEnergyConsumed(1000000, 1000001)
0.010242246920000002
model.device.powerSeries.getEnergyConsumed(1000000, 1000010)
0.10242246920000002
model.device.powerSeries.getEnergyConsumed(1000000, 2000010)
10242.3493424692
model.device.powerSeries.getSamplesWithinRange(1000000, 2000010)
[]

**Comment by zeptonaut** [comment]
I think what's make this tricky is that, if we have two samples at t=10s and t=20s, and we call `getEnergyConsumed(12, 18)`, I'd expect to receive a non-zero energy consumed. 

Maybe what makes sense is to have some logic that says power drops to zero after the samples end?

**Comment by Alex319** [comment]
That is what his CL does:

https://codereview.chromium.org/1958173002

**Comment by zeptonaut** [comment]
Closing this now that it's been resolved.
