### ISSUE TITLE
Flow V3

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#2327]
We would like to use flows for building a dependency graph on top of Chrome traces. Missing features are:

1- we want to attach flows to asyn events.
2- we want events to be part of several flows.
3- easy cross-process and in-process flows (similar to object refs).

Links: [Design doc](https://docs.google.com/document/d/1iNp9aDkuOARs0bWJS7ZJvc-f2P2dipXEfqh3rTjdefo), [CL](https://codereview.chromium.org/1970753002/)

**Comment by chiniforooshan** [comment]
This is abandoned for now.
The not-submitted patch: https://codereview.chromium.org/1970753002/

**Comment by rainkin1993** [comment]
The proposed Flow v3 is definitely useful to present causality relationships. It is disappointing for me that the Flow v3 is abandoned. 

Do you know whether there are any alternatives like Flow v3?
