### ISSUE TITLE
Perf Dashboard: Unclear how to select a time range

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#2330]
Chrome version: 50.0.2661.91 (Chrome OS)
URL: https://chromeperf.appspot.com/report?sid=83832b60c049833239337571fc8730adaa97179daf8b430462633127191271c1

Please describe the problem:

There's a historical graph (in blue), but it's not interactive. It was previously.

**Comment by anniesullie** [comment]
Do you get any errors on the JS console?

**Comment by dstockwell** [comment]
I didn't see anything. Loading it again now it is working :shrug: ...
