### ISSUE TITLE
Clarify ignore/invalid button labels

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2332]
They should say:

`Ignore valid alert`

and

`Report invalid alert`

**Comment by tdresser** [comment]
This change should be accompanied by an update of the perf regression sheriffing docs, with examples of when to use each button.

**Comment by anniesullie** [comment]
In case anyone picks this up on the `Good First Bug` label, the docs @tdresser mentions which should be updated are here: https://code.google.com/p/chromium/codesearch#chromium/src/tools/perf/docs/perf_regression_sheriffing.md

**Comment by anniesullie** [comment]
This is **fixed**.
