### ISSUE TITLE
Perf dashboard should no longer set sheriff as owner

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2333]
Having the sheriff who reported a performance regression bug be the owner of the bug is confusing because generally we expect the owner to take action on a bug, and after the sheriff's shift they are generally not the person who will take future action:
- For the bugs that the sheriff rotation triages, the current sheriff is expected to continue triage
- For bugs that get marked as release blockers, having a former sheriff as the owner is especially confusing. The person managing the release will have trouble understanding the bug state.

In the code, I think this can be accomplished by just not setting the owner in _ShowBugDialog here: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/file_bug.py#L101

This change should be announced on the perf-sheriffs@chromium.org mailing list, and sheriff documentation updated as necessary.

**Comment by Apeliotes** [comment]
We should cc them instead so they can still keep track of the bugs they filed.

**Comment by benshayden** [comment]
I took a swing https://codereview.chromium.org/2323993005

**Comment by anniesullie** [comment]
This is now fixed.
