### ISSUE TITLE
Perf dashboard needs a way to set thresholds for bug labels

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2334]
Currently, the dashboard allows admins to add a mapping of test paths to crbug labels. This should be extended to have a minimum percent change/absolute value change, so that release block labels can be applied only for regressions over a certain threshold.

I think this would involve modifying the code in these places:
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/edit_bug_labels.py
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/bug_label_patterns.py

**Comment by benshayden** [comment]
Let's use diagnostics instead?
