### ISSUE TITLE
Improve perf dashboard titling of bugs

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2337]
Currently the dashboard titles bugs `X% regression in <test suite> at <start>:<end>`. This is problematic in a few cases:
- With the memory_health_plan benchmark where we have a list of release blockers that all have very similar bug titles, even though different things (GPU, etc) regressed
- With the page_cyclers, where memory often regresses and the bug looks like page speed regressed.

Both of these cases would be addressed by switching the bug title to list the **metric** that regressed instead. But should we use the entire metric name (`memory_mmaps_private_dirty_total/foreground`) or just the first part (`memory_mmaps_private_dirty_total`)?

@rschoen @picksi @primiano @petrcermak opinions?

**Comment by primiano** [comment]
I'd just go for the full metric name, but defer to @petrcermak .
Definitely supportive to add the metric name, in some form, to the bug title. I missed this feature so many times.

**Comment by picksi** [comment]
Maybe the whole name but use a comma instead of a '/' to make it more human readable?

But the either way is an improvement :)

**Comment by petrcermak** [comment]
This is a great idea. I'd use the __whole name _without_ modifications__ (so that it matches the codebase and is easier to search for).

**Comment by benshayden** [comment]
Archiving. I just changed V2SPA to list measurement names instead of test suites.
