### ISSUE TITLE
Telemetry traces and BattOr traces don't align

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2341]
@randalnephew has now made it possible to collect a BattOr trace while running a Telemetry benchmark. However, when we do this, we get some funky results:

![image](https://cloud.githubusercontent.com/assets/1407397/15339506/b5229f5a-1c52-11e6-804b-ea9f4451c465.png)

(Notice the Chrome trace events aaaaaall the way over on the right side of the trace and the BattOr trace aaaaaaaaall the way over on the left.)

For some reason, the Chrome trace and the BattOr trace don't seem to be clock synced with each other. When I put a break point in `[TraceEventImporter.importClockSyncMarkers](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/tracing/tracing/extras/importer/trace_event_importer.html&q=importclocksyncmarkers%20trace_event_importer.html&sq=package:chromium&type=cs&l=859)`, it never seems to trigger. This indicates to me that we're somehow failing to

1) Find the clock sync markers in the Telemetry and Chrome traces and
2) Fail when these clock sync markers aren't found

I'll take over investigating this.

**Comment by zeptonaut** [comment]
Okay, after spending some time investigating this, there are a couple of pieces of work that need to be done to make this happen:

- **(Very easy)** In the trace event importer, start pulling the Telemetry subtrace out of the greater Telemetry trace that's recorded that also includes the BattOr trace, the Chrome trace. Right now we're ignoring this subtrace altogether.
- **(Easy to medium)** Change the output format of the Telemetry trace from just an array of trace events to a object. In other words, what current looks like:

```javascript
{
  powerTraceAsString: "...",
  telemetry: [
    // Telemetry trace events...
  ],
  traceEvents: [
    // Chrome trace events...
  ]
}
```

should be changed to look like:

```javascript
{
  powerTraceAsString: "...",
  telemetry: {
    traceEvents: [
      // Telemetry trace events...
    ]
  },
  traceEvents: [
    // Chrome trace events...
  ]
}
```

- **(Easy)** Add a `metadata` field on the Telemetry trace that includes a `clock-domain` field set to the output of [`trace_time.GetClock()`](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/common/py_trace_event/py_trace_event/trace_time.py&q=trace_event.py&sq=package:chromium&type=cs&l=228).

**Comment by zeptonaut** [comment]
/cc @fmeawad, who mentioned that he was interested during the instrumentation weekly yesterday

I'm looking into this right now. There are a couple of pieces that need to be in place for this to work:

- The Telemetry trace has to specify its clock domain (`TELEMETRY`). This is what was broken before, but my work last week fixed.
- The Telemetry trace has to contain its side of the clock sync marker to Chrome. I've confirmed that this is happening.
- The Chrome trace has to contain its side of the clock sync marker to Telemetry. I'm almost positive that this was happening before, but it doesn't appear that it's happening now. I haven't figured out why yet.

**Comment by zeptonaut** [comment]
I went ahead and tested to see if the Chrome-side clock sync marker is inserted at Chrome ToT - it isn't. Adding some logging statements to Telemetry seems to indicate that Telemetry is indeed calling out to Chrome to record these markers, so I'm going to add some logging statements to investigate the Chrome side of things.

**Comment by zeptonaut** [comment]
Fix incoming!

@vinterstum was immensely helpful in figuring this out.

Background: so when Telemetry tells Chrome that it wants to trace with an empty category filter list, Chrome assumes that Telemetry wants the full set of default categories enabled. However, if you pass a category filter list with _one_ entry, you instead get just that one category enabled. Basically, strictly adding categories to category filter list can actually result in _fewer_ categories being enabled.

@petrcermak recently did some great work in #2347 that made it so that we were much more explicit about what category filters we passed to Chrome. Part of this work resulted in passing a few categories in a place where before we had passed no categories. This meant that all of the other default categories were no longer being recorded among which was... \*drumroll\*... the `__metadata` category, which contains clock sync markers.

This explains why I was pretty sure I had seen these events in the trace before: it was a recent regression that caused them to no longer show up.

The underlying bug here is that `__metadata` events should really always be recorded, regardless of the category filter list. @vinterstum is working on a CL now that will do just that.

/cc @nedn @randalnephew

**Comment by nedn** [comment]
Interesting bug, hehe 
@wangzhen127

**Comment by vinterstum** [comment]
CL up, after a bit of plumbing: https://codereview.chromium.org/2040663002

**Comment by zeptonaut** [comment]
Marking this as closed now that the fix is submitted!
