### ISSUE TITLE
Move results2_template.html to telemetry

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2344]
Currently, results2_template.html is in tracing/tracing/ so that py_vulcanize can find its dependencies easily. But it really belongs in telemetry.

The source paths magic from perf_insights_project can be used to move it to telemetry.

**Comment by eakuefner** [comment]
Ah, I guess I misunderstood the intent of the TODO. I think we actually would like it to stay in tracing -- in particular, it would be nice to be able to use run_metric to get an HTML output, independently of whether Telemetry is used.
