### ISSUE TITLE
Metric selection dropdown list should include only items matching the entered text

### ISSUE THREAD

**Issue by ulan** [catapult-project/catapult#2348]
Steps to reproduce:
1. Go to chrome perf dashboard
2. Enter "v8.infinite_scroll" in Test Suite field
3. Enter "linux_release" in Bot field
4. Enter "Animation-v8-gc-latency"
5. Check items in the drop down list.
Expected:
Items in the list have "Animation-v8-gc-latency" as a substring. Items sorted alphabetically.

Actual:
There are unrelated items such as Animation-v8-gc-total, and items appear in seemingly random order.

![metric-selection](https://cloud.githubusercontent.com/assets/294429/15392509/cd0ed16c-1dc7-11e6-8423-dad53bc7bb95.png)

**Comment by anniesullie** [comment]
Agreed this dropdown definitely needs some work. Unfortunately, we are going to be a little slower than usual addressing UI issues as we are currently in the process of updating the underlying library to polymer 1.0, but we agree this should be addressed.

@Apeliotes

**Comment by benshayden** [comment]
This appears to have been fixed.
