### ISSUE TITLE
Perf dashboard: migrate timeseries data to bigtable

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2350]
We are stretching the limits beyond what app engine datastore was designed for. We need a datastore better suited to timeseries data, and it looks like [Cloud Bigtable](https://cloud.google.com/bigtable/docs/) is the way to go. We have some dated docs on the topic [here](https://docs.google.com/document/d/1LwkUuqEzWe1NhLEpY_o6FJe7gTm8zRzDKvUW3TdOX3M/edit) and [here](https://docs.google.com/document/d/1A_reV3HKf1020-ZcLv9cFL8d6r2wuPdPhhPZFQHgxlM/edit), but @eakuefner will write an up-to-date one.

**Comment by eakuefner** [comment]
Previously, we were uncertain about whether to use Cloud Bigtable, BigQuery, or some combination of the two. In TBMv2.1, we eliminate programmable grouping in favor of the [metric graphical model](https://docs.google.com/document/d/1_L9i0FMFTaZtfUngqjYl8jiTlUGmZ1200IThGudm09s/edit), which is a system in which values from a given run form a DAG by guid. This means that we can maybe make the row keys value guids.

One technicality about getting Cloud Bigtable to work with our Python codebase is that native Python bindings for it do not exist. Instead, we'll have to stand up our own HBase REST server on a GCE and then use that to connect to Bigtable.

**Comment by anniesullie** [comment]
Is switching to app engine VMs an option instead of a GCE? I vaguely remember some storage folks mentioning that, but perhaps I misunderstood.

**Comment by eakuefner** [comment]
It's possible that we might be able to do this with managed VMs by having the RPC server be hosted in the VM instance itself.

**Comment by eakuefner** [comment]
Closing; this is no longer part of our plan. We're working a datastore-based approach to handling histograms.
