### ISSUE TITLE
ChromePerf UI: test suite no longer allows partial filtering

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2352]
I go to chromeperf.appspot.com, type "health" in the "test suite" field, I get no result.
But there are definitely tests which contain "health" in the name. Why they are not shown? I am not sure I understand how the filtering logic works there. It was not the case until some weeks ago IIRC.
Can we make the filtering super dumb: when you type X just show everything that matches ._X._

@anniesullie @petrcermak @qyearsley

**Comment by anniesullie** [comment]
I agree we should do a simpler UI here, but we're going to wait on refactoring until after polymer 1.0 update.

**Comment by benshayden** [comment]
This seems to have been fixed.
