### ISSUE TITLE
ftrace importer crashes with error about not being able to add a third marker to sync "linux_clock_monotonic_to_ftrace_global"

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2355]
@Alex319 found this one.

Apparently, atrace sometimes includes multiple instantaneous clock sync markers between `LINUX_CLOCK_MONOTONIC` and `LINUX_FTRACE_GLOBAL`. I'm not sure why it would want to perform this sync multiple times but, because there are traces out there that have this functionality, we need to make sure we can handle them.

My plan is to have a simple boolean (`this.haveClockSyncedMonotonicToGlobal_`?) that just makes sure we only issue the first of these syncs.

**Comment by zeptonaut** [comment]
@natduca @ChrisCraik I'm not really sure about how we're rolled into Android/systrace as a dependency, but if there were any major releases cut while this bug was active, we probably want to get the Android team to patch this before sending this out to devs in general. Do you know how I might be able to find this out?

The original CL causing this problem was 702318be4fc0b8622259e33518f675131dcb3a0b and I'm about to submit the fix now.

**Comment by ChrisCraik** [comment]
That change never made it into the Android tree/SDK. We do manual syncs to catapult TOT, and the last one was end of March: https://android-review.googlesource.com/#/c/212200/

**Comment by zeptonaut** [comment]
Great! Thanks Chris. Just wanted to make sure that we didn't have a ticking time bomb buried in our code.
