### ISSUE TITLE
Add atrace as a tracing agent to Telemetry

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2356]
Significant regressions in Webview startup time are a potential release-blocker for Chrome, yet we currently have no Telemetry tests in place that monitor these regressions. We need to get such a test in place.

The main blocker in this effort is that we need the ability to use Android atrace events to power Telemetry tests. Once that's possible, we can create a simple TBMv2 metric that'll do what we want.

This will involve adding atrace as a tracing agent for TBMv2 Telemetry benchmarks. Thankfully, because systrace and Telemetry are both written in Python, we can probably reuse systrace's atrace agent within Telemetry.

**Comment by perezju** [comment]
Thanks Charlie. As noted, this is blocking [crbug.com/614371](https://bugs.chromium.org/p/chromium/issues/detail?id=614371).

**Comment by perezju** [comment]
Looks like this was done in [CL/2018643003](https://codereview.chromium.org/2018643003/), anything else missing? Or is there something else to be done?

**Comment by zeptonaut** [comment]
I think so. Thanks for taking care of this Alex!
