### ISSUE TITLE
low_resolution_timer import warning stacks and is uncloseable

### ISSUE THREAD

**Issue by randomascii** [catapult-project/catapult#2368]
While using ninjatracing (https://github.com/nico/ninjatracing) to convert .ninja_log files to chrome traces I've noticed that most of .json files created trigger the low_resolution_timer warning. This is because all of the times are integers, which actually isn't a problem for build traces. So that's one problem - it would be great to have an easy way to indicate that these warnings should be suppressed. Currently the only ways I am aware of to avoid the warnings are to perturb the numbers so that they are evenly distributed at various offsets from ms boundaries, or change the units from ms, but neither of those work well for this data which actually is ms precision.

The next problem is that the import warning bar cannot be closed, which seems too severe for what is ultimately just an informative warning.

The final problem is that when a new trace that triggers the warning is imported then the new warning stacks below the old one. This leads to amusing views like this:

![image](https://cloud.githubusercontent.com/assets/10800041/15559698/57e8a1c0-2299-11e6-902f-bff19c286b65.png)

None of these are extremely serious, but it would be nice to avoid them. I'm making some improvements to ninjatracing and will then be recommending that developers use it more often, so a way to indicate that the warning should not appear would be very helpful.

**Comment by anniesullie** [comment]
@vinterstum @zeptonaut

**Comment by randomascii** [comment]
I was looking at the buildbot build-time visualizations (accessible near the end of every compile stage, see http://chromium-build-stats.appspot.com/ninja_log/2016/05/27/build17-m1/ninja_log.build17-m1.chrome-bot.20160526-213850.4716.gz/trace.html for an example) and I noticed that the same issue occurs there so if a fix needs a change to how the .json file is generated then the server code that generates those trace.html pages should be updated as well - ukai is the author of that code.

**Comment by vinterstum** [comment]
I'm thinking we should just remove the heuristic which tries to autodetect this based on the timestamps; Chrome-generated traces have had a flag for this for a long time now, past the point where we need to care about older trace files I think.

Going to put up a CL for this, if there's no objections.

**Comment by vinterstum** [comment]
(Unless the heuristic is useful for detecting traces generated from other sources, but I'm thinking it creates more trouble than it's worth and the explicit flag would be better in all cases).

**Comment by zeptonaut** [comment]
+1 for preferring the explicit flag
