### ISSUE TITLE
Telemetry chartjson results have std of 0

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2369]
See e.g. this [results-chart.json](https://build.chromium.org/p/chromium.perf/builders/Android%20Nexus5%20Perf%20%282%29/builds/2908/steps/memory.top_10_mobile/logs/json.output). The `summary` metrics, in particular, should have been be computed using the *pooled standard deviation*, but all std's on the file have a value of `0`.

        "summary": {
          "grouping_keys": {
            "phase": "background"
          }, 
          "important": true, 
          "improvement_direction": "down", 
          "name": "memory_allocated_objects_partition_alloc_renderer", 
          "std": 0, 
          "tir_label": "background", 
          "type": "list_of_scalar_values", 
          "units": "bytes", 
          "values": [
            1301984, 
            2641451, 
            1626119, 
            ...

**Comment by anniesullie** [comment]
@eakuefner @dave-2

**Comment by perezju** [comment]
I had a look at this. The problem affects benchmarks (like `memory.top_10_mobile`) that always take a single measurement per page, and their corresponding metric returns this single value in a *list of scalar values*.

In this scenario, we gather individual measurements and, therefore, compute a `std` of 0 for all of them.

    - page1: values=[10], std=0
    - page2: values=[300], std=0
    - page1: values=[9], std=0
    - page2: values=[302], std=0
    - page1: values=[7], std=0
    - page2: values=[303], std=0

Values are then merged *per page*, and a new std is computed using [pooled standard deviation](https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/value/list_of_scalar_values.py?q=PooledStandardDeviation&l=35). However, since the variance of each group is taken as 0, the computed std is also 0.

    - page1: values=[10, 9, 7], std=0
    - page2: values=[300, 302, 303], std=0

Then, the final summary is computed, again using pooled standard deviation, and again getting a value of 0 since the variance of each group is assumed to be 0.

    - summary: values=[10, 9, 7, 300, 302, 303], std=0

Depending on how you look at it, this might or might not be the correct behavior.

I see at least three possible different ways to get the correct std values we would expect in `memory.top_10_mobile`:

1. Switch [memory_timeline.py](https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/web_perf/metrics/memory_timeline.py) (note this is the TBMv1 metric) to select always single dump and return it as a *scalar* rather than a *list of scalars*. --- @nedn always seemed to have strong feelings against this.
2. Keep returning a *list of scalar values*, but set `same_page_merge_policy=value.PICK_FIRST`. Has the same effect as above, but could be considered less hacky (depending on who you ask).
3. When merging *lists of scalars* coming from *the same page*, always use the regular (non-pooled) standard deviation. This is probably the right thing to do in most cases (usually same page == same random distribution), but depending on the benchmark this might not always be true.

Thoughts or preferences?

@petrcermak @primiano

**Comment by perezju** [comment]
Actually, solution 2 above does not work. PICK_FIRST would pick the first list with one scalar; not the first scalar of each list.

**Comment by eakuefner** [comment]
Does option 3 work here? That seems to be most pragmatic, since the reason option 1 is hard is the same as the justification that option 3 is good: we special case behavior when handling multiple numbers coming from the same page anyway.

**Comment by petrcermak** [comment]
I'd vote for option 3 as well.

**Comment by perezju** [comment]
sgtm, I'm writing a patch for this

**Comment by perezju** [comment]
I've just found that that option 3 clashes with other very typical (and a lot more common!) use case. That is when you run with --pageset-repeat 1, and your metric produced a single value.

In that case both on your individual measurements, and also after aggregating "per page", you get (correctly):

    - page1: values=[10], std=0
    - page2: values=[9], std=0
    - page3: values=[7], std=0
    - page4: values=[8], std=0

But then computing the summary std using pooled standard deviation, because the std of each page is 0, is also:

    - summary: values=[10, 9, 7, 8], std=0

which is arguably correct (different pages would produce different random distributions, so there isn't enough data to compute a std). But that is perhaps not what users expect to see?

Any suggestions to get out of this conundrum?

**Comment by nedn** [comment]
I think that's probably a good thing that we shows zero in that case rather than showing the false stat to the user: https://groups.google.com/a/chromium.org/d/msg/telemetry/BIKN9tgEZnc/PCsD3Eg8CQAJ

**Comment by perezju** [comment]
ok, sgtm, will continue with my patch and modify unittest expectations accordingly

we should probably send a warning to telemetry users after landing this CL, since a lot of their std's are going to suddenly vanish (not sure how many cared about them anyway).

**Comment by perezju** [comment]
This is now fixed and std's are [making it to the dashboard](https://chromeperf.appspot.com/report?sid=4c3eb9babc6a79fb2adfa2937c7b7f96ffdebe97bdd6ca92ac044903a765e23a)!

**Comment by petrcermak** [comment]
I suppose this also caused the standard deviation of page sets with no repeats to drop to zero: https://chromeperf.appspot.com/report?sid=3aceea5b58434863fcff844bdf38e272e0f2277913d8e62ed4b06f2261b1c1c5

**Comment by perezju** [comment]
Yes, that is correct and deliberate as per Ned's comment and the [announcement I sent](https://groups.google.com/a/chromium.org/forum/#!topic/telemetry-announce/rxZuqrBkI3Q) yesterday.
