### ISSUE TITLE
Telemetry does not clear the profile for WebView

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2370]
Just found out that on Chrome telemetry correctly clears the profile when starting a benchmark. This seems to be done passing a --user-data-dir (or whatever switch) to a fresh folder.
The same does not happen on webview (There is no equivalent switch). As a matter of facts webview profile is not cleared.

The possible solutions I see are:
1. telemetry should rm -rf /data/data/package.of.the.shell/app_webview (this should be done when the process is NOT alive).
2. Check if there is anything in the devtools protocol to achieve that.

**Comment by primiano** [comment]
@petrcermak suggested should be just a matter of properly fixing

https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/platform/android_platform_backend.py#L593

**Comment by anniesullie** [comment]
@case540 @yoland68

**Comment by perezju** [comment]
FYI: Found the cause of the issue, blocking on [crbug.com/552376](https://bugs.chromium.org/p/chromium/issues/detail?id=552376) to get this fixed.

**Comment by primiano** [comment]
Thanks Juan!
From  crbug.com/552376  looks like /bin/ls behavior has changed (\n -> space). These are the days when I want to leave everything and open a restaurant in central London. we cannot trust even /bin/ls consistency anymore :-/

**Comment by perezju** [comment]
After a long series of land, revert, reland, revert, reland, the fix finally stuck!

![xtcjmtevycg](https://cloud.githubusercontent.com/assets/16922344/15962289/e48a5bb8-2f01-11e6-8717-e8360d9bb6c6.png)
