### ISSUE TITLE
Rename linux_perf_importer to ftrace_importer

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#2371]
Still isn't renamed. @zeptonaut can you put this on Mr. Mont's backlog?

**Comment by zeptonaut** [comment]
Added. @Alex319, do you think that this would be something you could tackle after the `EventSet` refactoring?

**Comment by Alex319** [comment]
Yes. I should be able to do this.

**Comment by zeptonaut** [comment]
Awesome: thanks Randy! Went ahead and assigned it to you.

**Comment by zeptonaut** [comment]
Werd. I just went back and looked at this and said "thanks Randy!". I'm an idiot. 

A month after the fact, I'd like to revise this to "thanks Alex!"

**Comment by Alex319** [comment]
Just going back through old issues and checking their status. It looks like this was renamed a while ago.
