### ISSUE TITLE
Can't import telemetry traces with Atrace clock sync markers

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2373]
The following CL adds Atrace traces to telemetry (see https://github.com/catapult-project/catapult/issues/2356):

https://codereview.chromium.org/2018643003

In this code, if we add clock sync markers back in (by changing the output of atrace_wrapper_tracing_agent.RecordClockSyncMarker to True) the trace import will fail with the error:

TraceImportError: Unable to select a master clock domain because no path can be found from "TELEMETRY" to "LINUX_FTRACE_GLOBAL"

**Comment by zeptonaut** [comment]
Hi Alex,

Do you think you could upload a sample trace w/ this problem to Google Drive so that I could reproduce this locally?

**Comment by lpy** [comment]
We are still seeing this problem

**Comment by zeptonaut** [comment]
@lpy, can you link to an example of this?

**Comment by zeptonaut** [comment]
Actually, going to leave this closed. @lpy, can you confirm that the problem that you're seeing is the same on in https://bugs.chromium.org/p/chromium/issues/detail?id=797809#c13

This bug originally referred to the fact that we were reading in clock sync markers incorrectly from ftrace. That problem should be fixed now. I do think that there continues to be a problem where ftrace (or maybe Chrome?) isn't correctly emitting markers on Android, which is being tracked in the above bug
