### ISSUE TITLE
Right-align scalar columns in analysis view

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2375]
Suggested in an internal conversation by mmenke: _Numbers are left-aligned.  Right aligned values are a lot easier to visually compare._

**Comment by petrcermak** [comment]
__Before__

![left_align](https://cloud.githubusercontent.com/assets/2546601/15742595/db9804c4-28b7-11e6-8858-4a99c430869b.png)

__After__ (https://codereview.chromium.org/2033023002)

![right_align](https://cloud.githubusercontent.com/assets/2546601/15742598/e38dcf6a-28b7-11e6-8a31-85d4ce6dae5d.png)

The only downside is that there's now a _bigger gap_ between the titles and sizes (especially when allocation counts are not present, in which case the sizes are at the _right edge_ of the screen).

**Comment by benshayden** [comment]
Done?

**Comment by petrcermak** [comment]
Yes, thanks!
