### ISSUE TITLE
Display sizes in a column using a single unit

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2377]
Suggested in an internal conversation by mmenke: _Numbers are displayed in bytes, KB, MB, etc.  When navigating the through the hierarchy, it's much more difficult to compare values of different units.  It may be best to just display everything in bytes, with commas._

**Comment by petrcermak** [comment]
I experimented a little bit with units in the memory-infra pane...

## Overview pane

Here's what the pane looks right now (**automatic** units):

![auto](https://cloud.githubusercontent.com/assets/2546601/15933251/f00182ec-2e56-11e6-8448-44f3a66a9862.png)

___Option 1:___ This is what the same pane looks like if all sizes are shown in **kibibytes**:

![kib](https://cloud.githubusercontent.com/assets/2546601/15933282/0c8e0976-2e57-11e6-8235-458f23a48a57.png)

To me it seems that this is even _worse_ than the existing approach since some of the displayed numbers are huge. As a result, _(1)_ even fewer columns can fit onto the pane properly and _(2)_ the numbers are more difficult to interpret by humans.

___Option 2:___ Finally, here's what it looks like when all sizes are shown in **mebibytes**:

![mib](https://cloud.githubusercontent.com/assets/2546601/15933302/250d45c0-2e57-11e6-85f0-0f128e43a9c6.png)

I'd say that this looks _better_ than the current view. In fact, as you might have noticed, the pane requires less vertical space because more cells fit onto a single line.

## Details panes

The situation is even more complicated in the details panes (component details, heap details and memory maps):

![component_details](https://cloud.githubusercontent.com/assets/2546601/15935243/9204bf30-2e5e-11e6-80c6-834ac420603d.png)

While the total sizes of components on the overview pane roughly fall into the 0.1–3,000 MiB range, their descendants cover the whole spectrum from individual bytes to tens of mebibytes. Given this, I would argue that __using a single unit on the details panes just won't work__. If we use bytes, the details pane will become a mess (too many numbers). On the other hand, if we use kibibytes (or any higher prefix), some small values will incorrectly be displayed as zeros.

## Possible solutions

Here are some ways in which I think we could improve the current situation (not necessarily mutually exclusive):

  1. **Force all values in the _overview_ pane to be displayed in mebibytes**. As explained in the previous section, this doesn't make sense for the other memory-infra panes.
  2. **Provide users with a way to change the units manually** (e.g. a _dropdown_). This might need to be done at the pane level (so that the overview pane stays in mebibytes and the details pane can be, for example, in kibibytes).
  3. **Display magnitudes visually using sparklines**:
![sparklines](https://cloud.githubusercontent.com/assets/2546601/15936192/f8f27eaa-2e61-11e6-9f23-6d9543a8d4dc.png) The visual aspects of the sparklines would most probably need to be enhanced (reduce transparency, draw them under the actual values, etc). More importantly, we would need to figure out what the contexts for the sparklines would be. In simple terms, we need to determine what 100% stands for (column context → 100% is column total; allocator context → 100% is max column total of all allocators; common context → 100% is max column total over all columns). Note that if we used common context, component column sparklines (black) would be dominated by mmaps column sparklines (blue).

What are everyone's thoughts on this?

**Comment by primiano** [comment]
Sparklines there feels a bit weird to me, no strong opinions but would be fine with not having them.
As regards the units, I'd honestly leaning towards having KiB everywhere because that is the size we're more likely after. MB is a bit too coarse and hides things in the 10k range. Unrealistically we ever care about things in the order of bytes.
Maybe, if something is ~few bytes let's make the rounding thingy show them as 0.1 K, so they don't get confused with a 0?

**Comment by primiano** [comment]
Or thinking a bit more, can we haz MiB in the overview and KiB everywhere else?

**Comment by petrcermak** [comment]
It seems that virtually everyone (on the internal mailing thread) agrees on the following:
  * **MiB** on the **overview pane** and
  * **KiB** on the details panes (**component details**, **heap details** and **memory maps**),

so I'll implement that. To handle super-small values (bytes), I'm thinking about showing something like ">0.0 KiB" to make it clear that they're _not_ zero.

**Comment by petrcermak** [comment]
Done :white_check_mark:
