### ISSUE TITLE
Loading of available Benchmarks slow

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2387]
The loading of available Benchmarks slow if one of the Benchmark's on a bot has a lot of tests/subbenchmarks. Repro:

Bad: v8->x64->long load time->Whatever benchmark
Good: v8->Atom_x64->short load time->Whatever benchmark

I think this is because of the benchmark "RuntimeStats" which reports a lot of results.

**Comment by petrcermak** [comment]
This is related to https://docs.google.com/document/d/1rJOxhtm2MYGSPqDqa8uOt-ZXd1FIombl4uAtB-5n1_A/edit?usp=sharing

**Comment by camillobruni** [comment]
No not at all. We are talking about the choosing the benchmark on the perf dashboard on chromeperf.appspot.com not the trace viewer.

**Comment by anniesullie** [comment]
Most of the root cause here is #2305 (we can't cache the results of slow datastore queries). I hope to work on it this week.

**Comment by natorion** [comment]
Please note that this behavior has returned. The benchmarks are slow again.

@Apeliotes

**Comment by anniesullie** [comment]
The test case in the first comment is fast for me; does the slowdown for it repro for you? If not, what is the repro case?

**Comment by camillobruni** [comment]
I think it's a matter of initializing caches. I just tried <https://chromeperf.appspot.com/report?sid=a48dec5066f5d0028667e38d57ca2707ffcacd59b4122b94a99d14d0bc2ad0f6&start_rev=36921&end_rev=10000000> which took more than a minute to fully load the first time. Now it's done in roughly 10s.

**Comment by simonhatch** [comment]
FYI: I worked on this on friday and got loading down to the ~25s range or so. New dashboard with fixes has been deployed.

That should be about the uncached worst case. Subsequent visits loading the benchmark list should be super responsive. A longer term change in how we query the data is in the works, but at least in the short term this should be very usable now.

**Comment by eakuefner** [comment]
This is fixed.
