### ISSUE TITLE
"Debug Alert" does not catch a regression

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2388]
Reference: https://chromeperf.appspot.com/debug_alert?test_path=ChromiumPerf%2Fchromium-rel-mac10%2Foctane%2FGameboy&rev=361950&num_before=1000&num_after=1000&config=%7B%0D%0A++%22min_relative_change%22%3A+0.005%2C+%0D%0A++%22min_segment_size%22%3A+2%0D%0A%7D

I tried to tune the numbers for an anomaly detection in the Octane benchmarks run directly in Chrome. Specifically I would expect alerts around revisions 358525 and 361950. What is missing?

**Comment by anniesullie** [comment]
This chart is really noisy! We have a think called "steppiness" that represents how much there is a step-like shelf in the chart. It's filtering out these alerts, you could reduce it:

https://chromeperf.appspot.com/debug_alert?test_path=ChromiumPerf%2Fchromium-rel-mac10%2Foctane%2FGameboy&rev=361950&num_before=1000&num_after=1000&config=%7B%0D%0A++%22min_steppiness%22%3A+0.1%0D%0A%7D

**Comment by natorion** [comment]
Thanks, that clears things up.
