### ISSUE TITLE
Support custom value set views

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2390]
In order to facilitate custom metric UIs, value set view needs to be pluggable.

Back in perf-insights days, the pi-app contained a tab switcher between various reports. Let's use that concept, where a value-set-view takes the place of the old PI report.

The current value-set-view will be retained as a sane default view, but renamed to value-set-table, since it is primarily a table.

Custom views will be able to define and register a polymer element that takes a ValueSet and can present any subset of the values however it wants. The custom view interface is

 * supportsValueSet(values) -> bool; if this returns false, then the element will not be attached to the DOM; this is based on the existing side_panel.supportsModel(model) and model_helper.supportsModel(model).
 * set values(values); this can go ahead and update DOM contents.
 * get tabLabel(); this can rely on values

The value-set-view-container will remember selected tabs so that, if a dev primarily works with their custom view, then it will default to selecting that.

@natduca @eakuefner @nedn

**Comment by nedn** [comment]
Doc: https://docs.google.com/document/d/1CtRXNjt9BVRMyubHN7JdLOI6QQ5VQ0WPueWtTgjnk3s/edit

**Comment by petrcermak** [comment]
@primiano, @perezju (Memory-Infra): FYI
