### ISSUE TITLE
Catapult dep-roller is stuck

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2395]
First failed roll:
https://codereview.chromium.org/2042263003/
Suspecting Juan's CL: https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+/e90f8c0345c9bd7f96c6cabd51f5b7b45e50172e

Reverting it now..

**Comment by perezju** [comment]
Sorry and thanks for the revert! I have a new CL in review that should not introduce this problem.
