### ISSUE TITLE
Catapult rolls blocked on benchmarks.benchmark_smoke_unittest.BenchmarkSmokeTest.page_cycler.typical_25

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2399]
Log:
https://build.chromium.org/p/tryserver.chromium.android/builders/linux_android_rel_ng/builds/84439

  Traceback (most recent call last):
    RunBenchmark at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/internal/story_runner.py:312
      benchmark.ShouldTearDownStateAfterEachStoryRun())
    Run at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/internal/story_runner.py:225
      _RunStoryAndProcessErrorIfNeeded(story, results, state, test)
    _RunStoryAndProcessErrorIfNeeded at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/internal/story_runner.py:77
      state.WillRunStory(story)
    WillRunStory at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/page/shared_page_state.py:229
      self._StartBrowser(page)
    _StartBrowser at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/page/shared_page_state.py:190
      self._test.DidStartBrowser(self.browser)
    DidStartBrowser at /tmp/runVJJvAd/tools/perf/measurements/page_cycler.py:73
      self._memory_metric = memory.MemoryMetric(browser)
    __init__ at /tmp/runVJJvAd/tools/perf/metrics/memory.py:65
      start_memory_stats = self._browser.memory_stats
    memory_stats at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/internal/browser/browser.py:213
      result = self._GetStatsCommon(self._platform_backend.GetMemoryStats)
    _GetStatsCommon at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/internal/browser/browser.py:149
      child_cmd_line = self._platform_backend.GetCommandLine(child_pid)
    Cacher at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/decorators.py:34
      cacher.__cache[key] = obj(*args, **kwargs)
    GetCommandLine at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/internal/platform/android_platform_backend.py:276
      ps = self.GetPsOutput(['pid', 'name'], pid)
    GetPsOutput at /tmp/runVJJvAd/third_party/catapult/telemetry/telemetry/internal/platform/android_platform_backend.py:425
      cmd.extend('-p', str(pid))
  TypeError: extend() takes exactly one argument (2 given)
  
  Locals:
    cmd     : ['ps']
    columns : ['pid', 'name']
    pid     : 17771
  
  Traceback (most recent call last):
    File "/tmp/runVJJvAd/tools/perf/benchmarks/benchmark_smoke_unittest.py", line 81, in BenchmarkSmokeTest
      msg='Failed: %s' % benchmark)
  AssertionError: Failed: <class 'benchmarks.page_cycler.PageCyclerTypical25'>

Retrying failed tests (attempt #3 of 3)...

Suspect due to Juan's CL: https://codereview.chromium.org/2044413002/

**Comment by nedn** [comment]
Actually it's more like: https://codereview.chromium.org/2048933003/

**Comment by jbudorick** [comment]
https://codereview.chromium.org/2049773005/ should fix it

**Comment by jbudorick** [comment]
argh

**Comment by perezju** [comment]
Ooops :-S sorry for all the trouble and confusion!

Wondering if there are some tests that should be added to prevent this kind of braking CLs to land?

**Comment by nedn** [comment]
I think we need real android device on catapult CQ to effectively test these :-)

@anniesullie

**Comment by anniesullie** [comment]
@jbudorick does anyone on your team have time to help out with getting android devices on the catapult waterfall to test? We have a host and devices, just no clue how to set up the recipe.

**Comment by jbudorick** [comment]
@anniesullie Yeah, I can either do it or find someone to do so. Sounds like a good candidate for the [PE Fixit](https://crbug.com/617655)

**Comment by anniesullie** [comment]
Awesome! I realized we don't have a bug with everything in one place, so I filed #2403 with all the details.

**Comment by perezju** [comment]
Thanks for filing that issue. My CL finally landed without breaking the roll, so we can now close this one.
