### ISSUE TITLE
Some JSON files too large to upload to perf dashboard

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2402]
I have an example file that times out here: https://drive.google.com/a/google.com/file/d/0B_lQgYV0hGoNdlRRNHVWTGNvak0/view?usp=sharing

This isn't high priority because that data isn't currently being uploaded, but this will likely block tbm2.1 or 2.2.

**Comment by anniesullie** [comment]
@eakuefner do you still have your load test up? Does this file work with it? If so, let's close this bug.

**Comment by eakuefner** [comment]
Let's close this bug and revisit it, using that file as an ultra-load-test, when we're ready to talk about scaling up even more using the existing infra.
