### ISSUE TITLE
Add bot-related IterationInfo fields for dashboard

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2405]
TBMv2 Values need to contain the following fields:
- benchmarkName
- botName
- timestamp
- page repeat counter

What else? @eakuefner @nedn 

This information needs to be duplicated for each Value because Values can become separated from their ValueSets (in the dashboard), and ValueSets can be merged (in results2.html).

**Comment by anniesullie** [comment]
@dave-2 

First thing I'd like to clarify here is whether these should be added in telemetry or the recipe. What are the use cases here? Would anything that is not a buildbot want to record this data? Buildbot usecases include waterfall, bisect, try jobs, and cq.

Some examples of more things I'd like to see uploaded in diagnostics:

* Device id (so we can show an annotation when a new device runs the test)
* Hardware specs like RAM, CPU, etc
* Buildbot info so we can link back to buildbot status page (buildnumber, builder page)

**Comment by nedn** [comment]
Annie, not sure if we want stuff details such as RAM, CPU in every value. That seems more like to be covered by the "lightweight systrace" that @ZiqiXiong is working on.

**Comment by anniesullie** [comment]
The "lightweight systrace" is actually meant to get a list of other stuff running on the machine (debugging info for what might be happening on the machine to make perf tests noisy), not actual details about machine specs.

**Comment by nedn** [comment]
"top command" can also contains data about RAM & CPU. So if the data is already covered in the trace for debugging, I think we don't need to put these data in value's diagnostic again.

The thing here is our system have 3 main sources for debugging: bots' stdout log, trace, value's diagnostic data. The main question here seems to be which type of data go to what part. My rough mental model about this is:
Stdout log <-- for correctness data: browser's crash stack, python exception stack, test running's pass/fail state. 
Trace <-- for all performance data.
Value's diagnostic data <-- for performance data that directly related to the value.

Clearly, there is some vagueness about whether a value's diagnostic data points to all the possible related objects in the trace. I think this question can be answered on a value basis. For example, putting RAM as diagnostic info to battor power's values seems excessive whereas putting CPU info there seems reasonable.

**Comment by anniesullie** [comment]
Where do these go?
* android device id
* buildbot status/stdio page links
* Revision ranges (usually a chromium revision range but many tests upload multiple ranges for v8, skia, etc)

In your mental model, how does the dashboard store data like RAM, CPU, etc?

**Comment by nedn** [comment]
I think things like android device id, buildbot status/stdio page links, revision range should come from the recipe and not from telemetry & tbm2.1 values. 

Data like RAM & CPU are store in the trace which the dashboard has link to. For metrics that those data are strongly related, they can be computed as values & linked to by those metrics.

**Comment by anniesullie** [comment]
For things like RAM and CPU, we'll likely want to get to it more easily than have the user click through to a trace or have the dashboard have to do extra requests for related metrics. Generally the user would want to see it in two places:
* Some kind of top-level info on each chart or in the legend where they could get full details on what 'win-zenbook' hardware is exactly
* An automatic annotation in the chart any time one of these values changes.

For these reasons, it seems better to me to have it as a diagnostic on the value. @eakuefner will need to do some load testing on how big a value can be (both to be pulled efficiently from bigtable and processed efficiently on the client side), but putting things we'll want to show on one graph on separate values which reference each other can end up forcing us to make requests in serial to show a single timeseries.

**Comment by anniesullie** [comment]
Oh I missed your comment about things like device id not coming from tbm2.1 values. We had talked about the recipe being able to add context-specific diagnostics (and @benshayden's CL does that for buildbot info). Is that what you mean? Or do you mean it should actually be completely separate from tbm2.1 values?

**Comment by nedn** [comment]
I mean those should be completely separate from tbm2.1 values because they are things that non-telemetry based perf test also wants to have. Also include tbm1 & pre tbm1 telemetry benchmarks.

**Comment by anniesullie** [comment]
@eakuefner can you chime in on how the data added by the recipe should be serialized? To me it seems like not having it in the tbm2.1 values means multiple tables and data formats to keep in sync on the dashboard side. Seems much simpler to have the recipe add this info in the appropriate serialization format for the benchmark.

**Comment by eakuefner** [comment]
I'm going to come back to this after I do some reading and thinking, but just wanted to note here that we'll probably talk to @dave-2 about this tomorrow.

**Comment by eakuefner** [comment]
To update here, we had a meeting earlier this week and wrote a nice design doc about how `IterationInfo` should work: https://docs.google.com/document/d/12KvpnDUFUuCEgId7H-QL5PoRcsp99CXdqbZc-EOrpH8/edit

**Comment by benshayden** [comment]
Basic IterationInfos are recorded, so I'm redesignating this bug specifically for the bot-related fields required by dashboard and reassigning to @eakuefner .
