### ISSUE TITLE
MemoryCacheHTTPServer.UrlOf computes paths incorrectly in some situations

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#2411]
When called from a test run by telemetry/testing/browser_test_runner.py, telemetry/core/memory_cache_http_server.py's UrlOf computes the path incorrectly in certain situations.

To reproduce on Linux:
1) Build Chrome Release mode
2) cd out/Release
3) Run the following command:
/usr/bin/python ../../testing/test_env.py ../../testing/scripts/run_gpu_integration_test_as_googletest.py ../../content/test/gpu/run_gpu_integration_test.py webgl_conformance --show-stdout --browser=release -v --extra-browser-args="--enable-logging=stderr --js-flags=--expose-gc" --webgl-conformance-version=2.0.0 --webgl2-only=true --isolated-script-test-output=/tmp/foo.json --test-filter=conformance2_attribs

Note that the test will attempt to navigate to:
http://127.0.0.1:[port]/out/Release/conformance2/attribs/gl-vertex-attrib.html?webglVersion=2

The presence of "out/Release" in the path is the bug. The URL should actually be:
http://127.0.0.1:[port]/conformance2/attribs/gl-vertex-attrib.html?webglVersion=2

The bug is in the computation of:
relative_path = os.path.relpath(path, self._base_dir)

Somehow this is taking the current working directory into account. I don't understand fully how this code is supposed to work.

Changing the code to:
relative_path = path
makes it work for this case, but I'm sure would break it for other cases.

The code works if cd'd into src/ (i.e., not in out/Release), and run in this way:
/usr/bin/python testing/test_env.py testing/scripts/run_gpu_integration_test_as_googletest.py content/test/gpu/run_gpu_integration_test.py webgl_conformance --show-stdout --browser=release -v --extra-browser-args="--enable-logging=stderr --js-flags=--expose-gc" --webgl-conformance-version=2.0.0 --webgl2-only=true --isolated-script-test-output=/tmp/foo.json --test-filter=conformance2_attribs

Unfortunately, isolates, and swarming, change the current working directory in this way. UrlOf will need to be changed to handle this situation.

**Comment by nedn** [comment]
Ken has a WIP patch.

**Comment by kenrussell** [comment]
Thanks to Ned for discussion and help with this bug. https://codereview.chromium.org/2069193002/ is up for review fixing this.

**Comment by kenrussell** [comment]
Fixed in the above commit.
