### ISSUE TITLE
value_sets.getValuesWithName has a deceptive name

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2412]
It should be renamed to getValuesWithNameMatching(string) & we need another method like value_sets.getValueWithName

**Comment by eakuefner** [comment]
I don't see why the name is deceptive, but I do agree it's grammatically odd. I think the right convention here is `getValuesNamed` in line with `FindAllPageSpecificValuesNamed`, `findThreadsNamed`, `findTopmostSlicesNamed`, `findSliceNamed`, etc.

**Comment by eakuefner** [comment]
What do you mean by "& we need another method like value_sets.getValueWithName"?

**Comment by nedn** [comment]
I expect a method named "getValueWithName(name)" so that I can access a value from value set with value.name === name.
The  getValuesWithName's deceptive is is doing substring matching, hence ones can get multiple values whereas the contract of value_set is there can't be no two values with same name.

**Comment by eakuefner** [comment]
I see. The substring behavior is a little odd, I agree, and I don't think the current name implies to me that it might return multiple values.

I think this function should be reserved for "named exactly" and usages that need the partial match should use the version that takes a predicate instead.

**Comment by nedn** [comment]
How is the current name not implying it might return multiple values when the "values" in the name is plural?

**Comment by eakuefner** [comment]
Well, really, it's inconsistent. Obviously the s implies that it may return a list, but the fact that values should be unique as you said means that "named X" identifies a unique value.

**Comment by benshayden** [comment]
Hm, the ValueSet in results2.html might have a value named 'foo' from iter 0 and a value named 'foo' from iter 1, right?

**Comment by eakuefner** [comment]
I don't know about that. In fact, I'm wondering if we actually need to support merging ValueSets at all. What's the use case?

If you select cells from different ValueSets, then the merging happens at the histogram level, right?

**Comment by nedn** [comment]
Ben, that's a great point. Seems like we can't go the route of merging valueset, but need to have a list of valuesets here.

**Comment by eakuefner** [comment]
Alright, spoke offline with Ben: Values are unique up to name *and* `IterationInfo`, and there are cases where we need to support merging (e.g. for page-set-repeat or bisect).

That said, we don't need to reinvent the world here: let's just change `findValuesWithName` to `findValuesNamed` which does exact matching, but can return a list (of all values with that name, which may have different IterationInfos). It appears all the existing usages (which are all unit tests) don't even rely on this fuzzy matching behavior anyhow.

**Comment by eakuefner** [comment]
@ro-berto

**Comment by benshayden** [comment]
I'll scrub the ValueSet API when we simplify the Value hierarchy, so let's close this.
