### ISSUE TITLE
Animation jank/smoothness metric demo

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2414]
Currently, we use frame-time discrepancy, which is pretty noisy, and might not fit our conceptual model of what high or low jank means. Several people have proposed a few different ways of operationalizing jank, but we don't really know which of them might be better than discrepancy.

It might be useful to build a simple page that demonstrates various kinds of jank crossed with all of the proposed jank metrics. Something like a table where the rows are sample javascript animations with hard-coded frame times so that you can experience each animation, and the columns are all the various jank metrics.

One animation could be 60fps with one horrible frame in the middle, and another can alternate between 60fps and 30fps, but there's a huge landscape of frame times between those two extremes.

Think wine tasting: it can be difficult to know which of two subjective experiences is better, so experiencing them at the same time makes it much easier to decide.

Maybe also a wizard to let you control the frame times with sliders and see how the metrics respond. 

Maybe it could be checked into catapult as a test so that we can collaborate on it and build it like a readable Real Thing instead of an unreadable one-off jsbin.

Currently we can argue about which operationalization makes more sense to us, and this demo would not be the kind of scientific experiment that would resolve that debate, but it would make it easier for us to see how the different operationalizations play out in various scenarios. A user research study might still be necessary, but this demo would help.

@shubhie @nedn

**Comment by paulirish** [comment]
Generally like the idea of enumerating the various situations we have with real demos. http://google.github.io/latency-benchmark/ comes to mind, which is effective at showing latency vs jank.

**Comment by nedn** [comment]
I think this is probably already tracked by metrics team. Feel free to reopen if you disagree.
