### ISSUE TITLE
Getting energy used via powerSeries.getEnergyConsumed() takes too long.

### ISSUE THREAD

**Issue by randalnephew** [catapult-project/catapult#2415]
The power metric uses getEnergyConsumed() for calculating the power used in each frame. This takes ~ 30ms each frame. 
Metric:
https://cs.chromium.org/chromium/src/third_party/catapult/tracing/tracing/metrics/system_health/power_metric.html?q=power_metric.html+energyConsumedPerFrame&sq=package:chromium&l=21
powerSeries:
https://cs.chromium.org/chromium/src/third_party/catapult/tracing/tracing/model/power_series.html?q=f:catapult+getEnergyConsumed&sq=package:chromium&dr=C&l=63

Frame 1
Compute power per frame: 28.686ms
Add to numeric: 0.545ms
Frame 2
Compute power per frame: 28.937ms
Add to numeric: 0.197ms
....
Frame 2634
Compute power per frame: 26.292ms
Add to numeric: 0.007ms

@nedn

**Comment by nedn** [comment]
Charlie, is model.device.powerSeries.getEnergyConsumed using a linear algorithm?

**Comment by nedn** [comment]
I got a little bored, so steal this from Charlie.

**Comment by zeptonaut** [comment]
Thanks for handling this Ned!
