### ISSUE TITLE
Catapult roll is failing.

### ISSUE THREAD

**Issue by randalnephew** [catapult-project/catapult#2418]
Catapult roll failing:
https://catapult-roll.skia.org/

The first roll where it fails is:
https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+log/f7df8568ae1f..2ba7bda0ccf7

After that it fails with an import error.
https://codereview.chromium.org/2072163002 is the only CL in the roll. 
@anniesullie

**Comment by nedn** [comment]
There is also the failure of telemetry test:
[3/10] benchmarks.benchmark_smoke_unittest.BenchmarkSmokeTest.service_worker.service_worker failed unexpectedly 3.8110s:
  [ RUN      ] first_load
  Traceback (most recent call last):
    File "e:\b\swarm_slave\work\isolated\isolated_run8lv3sc\third_party\catapult\telemetry\telemetry\internal\story_runner.py", line 84, in _RunStoryAndProcessErrorIfNeeded
      state.RunStory(results)
    File "e:\b\swarm_slave\work\isolated\isolated_run8lv3sc\third_party\catapult\telemetry\telemetry\page\shared_page_state.py", line 306, in RunStory
      self._current_page.Run(self)
    File "e:\b\swarm_slave\work\isolated\isolated_run8lv3sc\third_party\catapult\telemetry\telemetry\page\__init__.py", line 94, in Run
      shared_state.page_test.WillNavigateToPage(self, current_tab)
    File "e:\b\swarm_slave\work\isolated\isolated_run8lv3sc\tools\perf\benchmarks\service_worker.py", line 102, in WillNavigateToPage
      self._timeline_controller.SetUp(page, tab)
    File "e:\b\swarm_slave\work\isolated\isolated_run8lv3sc\tools\perf\measurements\timeline_controller.py", line 37, in SetUp
      config.tracing_category_filter.AddFilterString(self.trace_categories)
  AttributeError: 'TracingConfig' object has no attribute 'tracing_category_filter'

**Comment by nedn** [comment]
Now it's a devil bug that is blocking the roll, *sigh*

**Comment by nedn** [comment]
https://build.chromium.org/p/tryserver.chromium.android/builders/linux_android_rel_ng/builds/89776/steps/mojo_surfaces_lib_unittests%20%28with%20patch%29%20on%20Android/logs/stdio

Traceback (most recent call last):
  File "/tmp/isolated_run16emxQ/build/android/test_runner.py", line 23, in <module>
    from devil.android import device_utils
  File "/tmp/isolated_run16emxQ/third_party/catapult/devil/devil/android/device_utils.py", line 39, in <module>
    from devil.android.constants import chrome
ImportError: cannot import name chrome

**Comment by nedn** [comment]
Now @eakuefner also involves in blocking catapult roll. Log:
[140/177] measurements.repaint_unittest.RepaintUnitTest.testRepaint failed unexpectedly 13.9010s:
  Chrome build location for win_AMD64 not found. Browser will be run without Flash.
  Requested remote debugging port: 0
  Starting Chrome ['e:\\b\\swarm_slave\\work\\isolated\\isolated_run7m6tg4\\out\\Release\\chrome.exe', '--enable-gpu-benchmarking', '--enable-impl-side-painting', '--enable-threaded-compositing', '--enable-net-benchmarking', '--metrics-recording-only', '--no-default-browser-check', '--no-first-run', '--enable-gpu-benchmarking', '--disable-background-networking', '--no-proxy-server', '--disable-component-extensions-with-background-pages', '--disable-default-apps', '--remote-debugging-port=0', '--enable-crash-reporter-for-testing', '--window-size=1280,1024', '--user-data-dir=e:\\b\\swarm_slave\\work\\isolated\\isolated_tmpggqp04\\tmpygbvlo', 'about:blank']
  Discovered ephemeral port 61477
  OS: win win7
  GPU device 0: VENDOR = 0x15ad, DEVICE = 0x405
  GPU Attributes:
    adapter_luid        : 0.0
    amd_switchable      : False
    basic_info_state    : 1
    can_lose_context    : False
    context_info_state  : 3
    direct_rendering    : True
    driver_date         : 11-11-2013
    driver_vendor       : VMware, Inc.
    driver_version      : 7.14.1.2032
    dx_diagnostics_info_state: 3
    gl_extensions       : 
    gl_renderer         : 
    gl_reset_notification_strategy: 0
    gl_vendor           : 
    gl_version          : 
    gl_ws_extensions    : 
    gl_ws_vendor        : 
    gl_ws_version       : 
    in_process_gpu      : True
    initialization_time : 0.0
    jpeg_decode_accelerator_supported: False
    lenovo_dcute        : False
    max_msaa_samples    : 
    optimus             : False
    pixel_shader_version: 
    process_crash_count : 0
    sandboxed           : False
    software_rendering  : False
    vertex_shader_version: 
    video_decode_accelerator_flags: 0
  Feature Status:
    2d_canvas           : unavailable_software
    flash_3d            : unavailable_software
    flash_stage3d       : unavailable_software
    flash_stage3d_baseline: unavailable_software
    gpu_compositing     : unavailable_software
    multiple_raster_threads: unavailable_off
    native_gpu_memory_buffers: disabled_software
    rasterization       : disabled_software
    video_decode        : unavailable_software
    video_encode        : unavailable_software
    webgl               : unavailable_off
  Driver Bug Workarounds:
    clear_uniforms_before_first_program_use
    disable_direct_composition
    disable_discard_framebuffer
    exit_on_context_lost
    scalarize_vec_and_mat_constructor_args
  PageCacheTemperature: any
  Trace config file string: {"trace_config": {"enable_systrace": false, "included_categories": ["webkit.console", "benchmark", "blink.console", "trace_event_overhead"], "record_mode": "record-as-much-as-possible"}}
  Start Tracing Request: {'params': {'transferMode': 'ReturnAsStream', 'traceConfig': {'enableSystrace': False, 'recordMode': 'recordAsMuchAsPossible', 'includedCategories': ['webkit.console', 'benchmark', 'blink.console', 'trace_event_overhead']}}, 'method': 'Tracing.start'}
  Trace of size 1205824 bytes saved.
  Trace of size 40 bytes saved.
  Successfully shut down browser cooperatively
  Traceback (most recent call last):
    File "e:\b\swarm_slave\work\isolated\isolated_run7m6tg4\tools\perf\core\path_util.pyc\..\..\measurements\repaint_unittest.py", line 46, in testRepaint
      self.assertEquals(len(frame_times), 1)
  AssertionError: 0 != 1

**Comment by eakuefner** [comment]
Roll is green -- this bug should be closed. Thanks @nedn for pasting the log -- I'll troubleshoot the CL today.
