### ISSUE TITLE
Figure out how to (automatically) set units based on context

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2420]
We want to provide the UI with the ability to **specify how units should be displayed**. For example, we want to show all sizes in memory-infra details panes in kilobytes (#2377).

Furthermore, this behavior should be **configurable** by the user. We should provide a simple means for the user to request things like _"show me all sizes in megabytes and timestamps in microseconds"_.

**Existing proposals:**
- @natduca's "My Controller is in my parent element chain" design document: https://goo.gl/OmnLs8
- Polymer data binding (suggested by @Apeliotes): https://www.polymer-project.org/1.0/docs/devguide/data-binding

**Comment by benshayden** [comment]
This doesn't look like a Values bug.

This is missing too much context and information to be a good first bug.

Why do we have both the Enhancement label and the Feature-Request label? Why do we need either one?

**Comment by petrcermak** [comment]
This bug is about displaying values (scalars), so I think it should have the "Values" label.

**Comment by benshayden** [comment]
https://docs.google.com/document/d/10r7us9S-WcnT9Ke469wR8fBffTvwV6tF7zsPRTWZ4N4/edit#heading=h.99zkamgg2xov

To summarize: It is difficult to reason about merging ScalarNumerics, so we are planning on requiring metrics to only produce histogram Numerics (single-sample Histograms are fine; the burden on metric authors amounts to asking them to specify the expected range of their numbers, which we can provide sane defaults for based on units if we want), so the NumericBase abstraction will not be necessary, so Scalar will move back into base/. Also, the Value hierarchy was a result of over-zealous failure handling, so it is also not necessary. The memory-infra UI can still use Scalars, and both Scalars and Histograms will have Units, but sharing a single field doesn't seem like sufficient justification for an abstraction hierarchy.

Please let us know if we forgot something that still needs the NumericBase abstraction!

**Comment by petrcermak** [comment]
Thanks for the detailed explanation :blush: I suppose we should have a different label for this.

**Comment by benshayden** [comment]
Trace Viewing seems like a good label for it, since both proposed solutions involve working in tracing/ui/, though I don't know if anybody owns the Trace Viewing label, so it might be a bit of a tragic commons.

**Comment by perezju** [comment]
@benshayden do you know if this is still something we might want to implement?

Also, does not sound memory-infra specific. I'll remove that label.

**Comment by benshayden** [comment]
I appreciate the generality of the Unit system and the utility of the controller-ancestor pattern, but this bug looks pretty vague and hasn't seen much activity in a while. I have no personal interest in this bug as is. Let's focus on specific requests and use cases. #2377 was satisfyingly specific, and appears to have been fixed. If there are other use cases for customizing scalar formatting, let's open new, more specific bugs. It's possible that we'll want a class of scalar formatting features, but let's start with specifics before generalizing. I'd be happy to help with that.
