### ISSUE TITLE
Add support for time ranges to the TBMv2 memory metric

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2421]
The current implementation of the memory metric takes the __whole trace__ and converts it to numbers:

_TRACE →
{<tt>memory:chrome:all\_processes:reported\_by\_chrome:v8:effective_size</tt>: N MiB, ...}_

The metrics framework has recently (https://codereview.chromium.org/2052593005/) started to support specifying a __range of interest__ as well:

_TRACE, [START ms, END ms] →
{<tt>memory:chrome:all\_processes:reported\_by\_chrome:v8:effective_size</tt>: N MiB, ...}_

The question is whether we want to add this functionality or not. According to @nedn: _"personally, I found [support for ranges of interest] handy for debugging & understand the tbm2 metrics in details"_. It should be relatively straightforward to do: we'd essentially just need to apply an extra filter to take only relevant global memory dumps (i.e. dumps within the range of interest) into account.

@primiano: WDYT?

@nedn, @zeptonaut, @eakuefner, @benshayden: FYI

**Comment by primiano** [comment]
What is the actual use case? In principle sounds a nice feature. In practice I think that the rule of thumb is to not do anything if we don't have a driving use case, to avoid introducing unnecessary complexity.

**Comment by nedn** [comment]
+1 to what Primiano says. If you knows someone who find this useful, then consider supporting it. Otherwise, more code is more burden :-)

**Comment by petrcermak** [comment]
In that case, I'll __close__ this bug now :closed_book: 

Anyone: If you need this feature, please __re-open__ :book:

**Comment by petrcermak** [comment]
Following a discussion with @primiano, it turns out that, by implementing this feature, we can solve a problem faced by the V8 team: https://bugs.chromium.org/p/chromium/issues/detail?id=625852.

**Comment by petrcermak** [comment]
This is __done__ :white_check_mark:
