### ISSUE TITLE
Add option in html2trace to put all the traces into one file

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2422]
I would like to have an option in html2trace to put all the traces into one file rather than split them up into multiple files. Ideally, given a standalone HTML file, the following two approaches should produce identical output: (a) open the standalone HTML file, and (b) run html2trace on the HTML file with this new option, then view that resulting trace in the trace viewer.

The purpose of this is to enable one to take a standalone HTML file, and then change the trace viewer and see how the trace looks after that.

**Comment by petrcermak** [comment]
I don't fully understand this feature request. What should be the output of option b? A zip file? Are you suggesting that we merge the sub-traces into a single JSON trace file? You can already import an HTML file into Trace Viewer, which I suspect is what you want.

**Comment by Alex319** [comment]
I am suggesting that we merge the sub-traces into a single JSON trace file.

The issue is the following. If I just open up the HTML file in Chrome, that's a standalone HTML file that has the trace viewer embedded in it. What I want to do is to be able to *edit* the trace viewer code itself on my local machine, then open up the full trace using the *new* trace viewer. If I just open up the standalone HTML file, that will just contain the trace viewer at the time the standalone HTML file was generated. (Or am I misunderstanding what's going on, and you can already extract the trace data from the standalone HTML file and load it in a different version of the trace viewer?)

**Comment by petrcermak** [comment]
You _can_ indeed open an HTML trace in a __different version__ of Trace Viewer. To give you an example, assuming you have the local Catapult dev server running:

```
$ bin/run_dev_server 
Now running on http://127.0.0.1:8003
```

Navigate to <tt>http://localhost:8003/tracing_examples/trace_viewer.html#/tracing/test_data/counter_tracks.html</tt> in your browser. This opens a sample HTML trace (which contains Trace Viewer from several months ago) in your _local_ version of Trace Viewer.

**Comment by petrcermak** [comment]
I'm closing this issue. Please let me know if you have any further questions.
