### ISSUE TITLE
Perf Dashboard: "📈" isn't displayed in a right glyph on ChromeOS

### ISSUE THREAD

**Issue by toyoshim** [catapult-project/catapult#2423]
Chrome version: 51.0.2704.79 (Chrome OS)
URL: https://chromeperf.appspot.com/alerts

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
*WARNING* /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
*WARNING* core-overlay.html:348 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

Please describe the problem:
The emoji of a graph is rendered by Arimo, local font, on Chrome OS, and it does not have a right glyph for this character code.

**Comment by eakuefner** [comment]
Thanks for reporting this bug! I actually don't think we should be using a glyph here at all.

The fix I propose is to use the `trending-up` icon from [core-icons](https://docs-05-dot-polymer-project.appspot.com/0.5/components/core-icons/demo.html). 1.0 has the `icon:timeline` icon that I think is even more appropriate, so I think switching to that after we're done migrating to 1.0 would be in order.

@anniesullie @Apeliotes

**Comment by anniesullie** [comment]
sgtm!

**Comment by eakuefner** [comment]
Here's what it looks like:
![graph_icon](https://cloud.githubusercontent.com/assets/75990/16245325/29fd51da-37b5-11e6-8c67-47be20cc60ba.png)

CL incoming.
