### ISSUE TITLE
Power metric should align its frames with Chrome's

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2426]
Right now, `power_metric.html` (which backs our power benchmarks) divides the trace into 16ms chunks from the first power sample until the last power sample and calculates the total energy consumed during each of those chunks. Ostensibly, this divides the trace into "frames", but we know that isn't actually the case.

Instead of dividing the frames at `first_power_sample_time + N * 16ms`, the metric should divide the trace into frames at `model.device.vSyncTimestamps`.

**Comment by randalnephew** [comment]
Is there a way in the metrics to translate one clock domain to another? 

The vsyncs are in chromes clock domain, and the power samples are in battors clock domain.

**Comment by zeptonaut** [comment]
By the time that they're stuck on the model, the power samples should already be in Chrome's clock domain. ([See this code](https://github.com/catapult-project/catapult/blob/dc09b776a2fe2c211d96f3e34dd906516f8f8b18/tracing/tracing/extras/importer/battor_importer.html#L88-L98))

**Comment by randalnephew** [comment]
Im using old sample data (battor_chrome in test_data/), Ill get some fresh data and try again.

**Comment by zeptonaut** [comment]
Ah, okay. Yea, that's probably problematic.

After you get fresh test data, would you mind updating the test_data trace
in Catapult?

On Thu, Jun 23, 2016 at 10:32 AM, randalnephew <notifications@github.com>
wrote:

> Im using old sample data (battor_chrome in test_data/), Ill get some fresh
> data and try again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/catapult-project/catapult/issues/2426#issuecomment-228069021>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABV5pQgrJJXHRAlwUIHBW7pGZkYB-8O1ks5qOpkYgaJpZM4I8Gqk>
> .
>



-- 

Charlie Andrews |  Software Engineer |  charliea@google.com

**Comment by zeptonaut** [comment]
Closing this as "won't fix" because our final metrics will no longer rely on frame boundaries.
