### ISSUE TITLE
Ensure story names are unique

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2429]
We've been meaning to do this for a long time, and now we need the guarantee to make plumbing IterationInfo through Telemetry trace metadata work.

@nedn @benshayden @zeptonaut

**Comment by nedn** [comment]
Any update on this?

**Comment by eakuefner** [comment]
I'm going to start using this bug to track my investigation for why this won't land on Windows. By diffing which tests complete successfully and which don't, I've figured out that at least `story_set_unittest.testSmoke` is hanging. I can repro this locally, so now I'm adding logging to `story_set_smoke_test` to figure out what might be happening.

**Comment by nedn** [comment]
This seems promising!

**Comment by eakuefner** [comment]
Okay, so I can say with certainty that `Alexa1To10000PageSet` is causing problems, and I'll keep digging to figure out why.

This actually jives with the other test that's failing, which is the other one in this file, `testNoPageDefinedSyntheticDelay`, which also tries to construct every story set.

**Comment by nedn** [comment]
Oh, is that because your assertion is slow & Alexa1To10000PageSet blows up the runtime?

**Comment by eakuefner** [comment]
Maybe, but if that's true I'm puzzled as to why it blows up on Windows but not other platforms. It's kind of my best hunch right now, but I'm adding more asserts to the page set itself to try to examine the behavior.

**Comment by eakuefner** [comment]
(If it does turn out to be the case, we can just do more memoization to make this sufficiently fast)

**Comment by nedn** [comment]
The algorithm you currently have is `O(N^2)` because you check the list for duplicated name. Maybe having a set data type for storing name could have with the lookup.

**Comment by eakuefner** [comment]
Agreed. And it's slowed to a crawl on my crappy Windows laptop, so this is definitely an issue.

**Comment by eakuefner** [comment]
Nice, using a set makes this much, much faster. I no longer see the hang on Windows. I'll update my patch and try again.

**Comment by eakuefner** [comment]
Closing as fixed; thanks Ned for the quick fix on the Chromium side.
