### ISSUE TITLE
Allow specifying multiple metrics to metric_runner

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2430]
Originally, when we expected Big Data to use TBMv2 more directly, we were concerned about metric configuration consistency between benchmarks and from-the-wild analysis. However, now we're focus mostly on Automation & Monitoring use cases for TBMv2. In this situation, it's often useful for people to be able specify additional metrics to be computed without having to submit to the cruft of defining a new meta-metric.

Examples: [[1]](https://codereview.chromium.org/2083973003/) [[2]](https://docs.google.com/document/d/1Us5rrFqbkw3PlHd7lG8bt_Z2QiQGrKE4CXpGChCF4RU/edit)

We should allow Telemetry benchmarks to specify a list of TBMv2 metric names, and we should allow multiple `--metric` arguments to be passed to `bin/run_metric` (which I think we should rename to `bin/run_metrics`).

@nedn

**Comment by nedn** [comment]
cc: @petrcermak 
@Alex319 @zeptonaut  @randalnephew (for integrating latency metric to existing battor benchmarks)

**Comment by zeptonaut** [comment]
+1 would use

**Comment by nedn** [comment]
@ulan this may also simplify how you're wiring the metrics together.

**Comment by eakuefner** [comment]
@zeptonaut We talked about interest in having @Alex319 or @randalnephew pick this up. The overview of how to do this would be:

1. Extend [`metric_runner`](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/metric_runner.py) and [`metric_map_function`] to reason about a list of metrics.
2. Fix [`run_metric`](https://github.com/catapult-project/catapult/blob/master/tracing/bin/run_metric) to allow specification of multiple `--metric` arguments that get parsed into a list
3. In Telemetry's `TimelineBasedMeasurement`, change `Options._timeline_based_metric` to be `Options._timeline_based_metrics`, patch `SetTimelineBasedMetric` to lift the passed string to a singleton list, add `SetTimelineBasedMetrics` that's like [`SetTimelineBasedMetric`](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/web_perf/timeline_based_measurement.py#L210) but handles a list, and change [`_ComputeTimelineBasedMetric`](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/web_perf/timeline_based_measurement.py#L302) to `_ComputeTimelineBasedMetrics`.

This is one patch. From here, there are two more sides to the patch:
1. In `tools/perf`, update all usages of `SetTimelineBasedMetric` to `SetTimelineBasedMetrics`.
2. Delete `timeline_based_measurement.Options.SetTimelineBasedMetric`

**Comment by nedn** [comment]
Since this is a API change, also please send out an announcement to telemetry-announce@ :-)

**Comment by eakuefner** [comment]
Done: https://groups.google.com/a/chromium.org/forum/#!topic/telemetry-announce/8_8sxrt0Naw

**Comment by ulan** [comment]
+1 looking forward to this feature.

**Comment by petrcermak** [comment]
_(I'm increasing the priority of this issue because it's blocking https://bugs.chromium.org/p/chromium/issues/detail?id=621035)_

**Comment by zeptonaut** [comment]
Ack - I'll make sure work starts on this as soon as possible

**Comment by petrcermak** [comment]
Thanks!

**Comment by Alex319** [comment]
Done
