### ISSUE TITLE
Bisect popup leads back to same page.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2433]
Kicked off 2 bisects today and clicked on the little popup, and I swear it just sent me back to the same url both times. Isn't it supposed to send me to info about the bisect?

**Comment by eakuefner** [comment]
@Apeliotes Interested in taking a look?

**Comment by petrcermak** [comment]
This is a __duplicate__ of https://bugs.chromium.org/p/chromium/issues/detail?id=622290.
