### ISSUE TITLE
Perf Dashboard: Alert link is broken

### ISSUE THREAD

**Issue by SummerLW** [catapult-project/catapult#2434]
Chrome version: 51.0.2704.106 (Linux)
URL: https://chromeperf.appspot.com/alerts?sortby=percent_changed&sortdirection=up

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
Error: Bad Request
Your client has issued a malformed or illegal request.
Please describe the problem:
I tried to open an alert, but it shows as a bad request.
https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgovq3pAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgovTvvQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgooiCoAsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgoobItQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgooKLsQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgoobItQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgoobcrAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgopnDsQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgou3YvgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwo309QkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgou3YvgkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgooaRogoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosvSpwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgooKfqAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwt_CowoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosL4uQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgou2WsQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosG3qwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwsvitAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwr2OrgsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgotn6tQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgooHmoQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosvOtgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgotm1vQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwpuFuwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwpuTpgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwpvKswkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosLipAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgws_ZoAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgou37pAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwt_WsgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwpv3twkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwt_WsgkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgotnfswoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgornEqgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosuDvgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosK2tQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgorrNpwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgoqibsAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgop2gtQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwremuwsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgoqGougoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgotSctAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgormSuwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgooa_uwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgooiC4AgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwt-JqwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosuXoAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwu28sgkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosKprAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosLdvQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgormOpgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosakpgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwq2epQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgormOpgkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosuXoAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgorn9rgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgop3eogoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgosbStwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgwriqiQgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgormnvwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgovKrvwoM

It is about 401942 - 401975 ChromiumPerf    chromium-rel-win7-gpu-intel...  smoothness.top_25_smooth    frame_times/ESPN... 182.9%.

**Comment by eakuefner** [comment]
I think the problem is that the browser truncates the URL in this case. We can probably add some handling that does a PUT instead of a GET for very long reports like this. We use GET because especially for smaller reports it's nice to be able to copy and paste the URLs, but in a case like this, it would probably be better for it to work at all.
