### ISSUE TITLE
CpuTracingAgent caused timeout on Windows buildbot

### ISSUE THREAD

**Issue by ZiqiXiong** [catapult-project/catapult#2439]
I am trying to land my [CL](https://codereview.chromium.org/2066413002/) for adding a new tracing agent that takes snapshots of CPU usage when running benchmark tests on telemetry. However, the build on Windows bots have been throwing exception due to timeout since patchset 13. Here is an [example](https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/3577).

@ro-berto @wangzhen127 @nedn @anniesullie

**Comment by ZiqiXiong** [comment]
I ran the telemetry tests on a local machine and was able to produce the same exceptions on the builder bot. Here is the stdout:  [text_output.txt](https://github.com/catapult-project/catapult/files/340259/text_output.txt)

**Comment by ZiqiXiong** [comment]
@ro-berto  @nedn  @wangzhen127

**Comment by wangzhen127** [comment]
I think your local test has more failures than the trybot example.

**Comment by ZiqiXiong** [comment]
@wangzhen127 Yeah, also the local test did not timeout after test 542 as trybot example did.
