### ISSUE TITLE
/migrate_test_names should list path the test will be migrated to

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2447]
Right now, when you go to `/migrate_test_names`, it lists the tests that will be migrated, but not what paths they will be migrated to. This makes it way too easy to incorrectly configure the migration. We should change the UI so that it shows both the test path that will be migrated and the test path it will be migrated to.

Currently, the `listTests()` function in `migrate_test_names.html` does an xhr to `/list_tests`: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/templates/migrate_test_names.html#L20

We should implement a simple endpoint in `migrate_test_names.py` which calls `list_tests.GetTestsMatchingPattern()` directly and calls `_GetNewTestPath()` on them to show the new path.

**Comment by bhavybarca** [comment]
@anniesullie is this fixed ? If not may i take it?

**Comment by anniesullie** [comment]
Sure, you can take it! 

@simonhatch This was the bug I mentioned wanting to fix yesterday.

**Comment by bhavybarca** [comment]
@anniesullie how do i create endpoint

**Comment by simonhatch** [comment]
Normally you'd declare it as a class and derive from request_handler.RequestHandler, you'll probably want to do it in (there are also examples in there): https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/migrate_test_names.py

Then you need to add it to the dispatcher:
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/dispatcher.py

**Comment by bhavybarca** [comment]
thanks, on it, also is there a chat room?

**Comment by simonhatch** [comment]
Unfortunately not one that we can add you to, but I'll try to be as responsive as possible on these bugs.

**Comment by bhavybarca** [comment]
so what does the dispatcher do ?
i mean how do add to i

**Comment by simonhatch** [comment]
It's pretty straightforward if you look. There's a mapping definition that maps urls to classes that handle them, just add the ones you need there.

**Comment by bhavybarca** [comment]
okay so basically i have to create a new function which calls "list_tests.GetTestsMatchingPattern()"
and on the outputs call "_ValidateAndGetNewTestPath()" and 
add '/test_lists', test_lists.TestListsHandler to dispatcher

i hope i am right?

**Comment by simonhatch** [comment]
Yes, you'll have to pass the old path to your new endpoint, figure out what calls you need to make to show the new paths, and then surface those in the UI. And yeah, you'll need to add something in the dispatcher to register your new endpoint's url. I'd prefer it nested under /migrate_test_names if possible.

**Comment by benshayden** [comment]
[Moved to crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=914101)
