### ISSUE TITLE
Summarize TBMv2 benchmark results by merging Histograms

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2449]
For everyone's sanity, we should move as quickly as possible to maintenance-mode `Summary`.

We're getting bugs like [crbug.com/624522](https://bugs.chromium.org/p/chromium/issues/detail?id=624522) wherein current progress is colliding with old hacks. By using TBMv2's summarization, we can sidestep all of the headache-inducing reasoning of summary v1 and stop piling hacks.

**Comment by benshayden** [comment]
merge_histograms_function.html should take an array of histogram dicts, load them into a ValueSet, call groupHistogramsRecursively(), then walk that tree to produce the same Histograms that [value-set-table.buildRow_()](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/value/ui/value_set_table.html#L650) produces, and return an array of just the merged histograms back to python. There should probably be some more code sharing between value-set-table and merge_histograms_function.html.

**Comment by eakuefner** [comment]
Huh, I didn't initiate that title change. More fodder for the bug report I've filed with GitHub.

Ben, I think your new title actually provides less context for what this bug is about. It would be better to provide a title that says what this overall effort is about, and detail what you think the concrete steps are in a comment.

**Comment by benshayden** [comment]
I had changed the title because we aren't using mapper functions. PTAL

**Comment by eakuefner** [comment]
LGTM. Also, it still shows me that this new title change was made by me, so that seems to provide a concrete repro.

Just to let folks know, the way you file bugs with GitHub is by emailing them, so I've gotten a response from a rep that the team will look at it but no promises.

**Comment by eakuefner** [comment]
Folks, apologies in advance for the noise; I'm trying to use this issue to get repro steps to report this bug properly to GitHub.

**Comment by eakuefner** [comment]
(Just an update: according to GitHub, there was an issue, but it has been fixed)

**Comment by eakuefner** [comment]
I think this is done.
