### ISSUE TITLE
Strange temp file names printed while running benchmarks

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2451]
When running a benchmark we get some strange temp file names being printed on the output without much context nor explanation, e.g.:

```
$ tools/perf/run_benchmark memory.top_10_mobile
69 KB/s (3387 bytes in 0.047s)
[ RUN      ] https_www_google_com_hl_en_q_science
/tmp/tmpSLAytK.html
[       OK ] https_www_google_com_hl_en_q_science (19514 ms)
[ RUN      ] after_https_www_google_com_hl_en_q_science
/tmp/tmpHiafO9.html
[       OK ] after_https_www_google_com_hl_en_q_science (16478 ms)
[ RUN      ] https_m_facebook_com_rihanna
/tmp/tmpoZbald.html
[       OK ] https_m_facebook_com_rihanna (15878 ms)
[ RUN      ] after_https_m_facebook_com_rihanna
/tmp/tmpo1Slbw.html
[       OK ] after_https_m_facebook_com_rihanna (16371 ms)
...
```

After some bisecting through the code I eventually pinned those strange looking lines of output coming out of [telemetry.value.trace](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/value/trace.py#L76). They started appearing after @randalnephew moved the trace to html conversion out of process. :-)

I'm considering just replacing that `check_call` to `check_output` so we just swallow the stdout of the subprocess. Does that sound reasonable?

**Comment by nedn** [comment]
sgtm
