### ISSUE TITLE
Alerts-table on /alerts doesn't obey sortby and sortdirection query parameters.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2452]
To reproduce/observe, open the following two pages:

  https://chromeperf.appspot.com/alerts?sortby=test&sortdirection=down&triaged=true
  https://chromeperf.appspot.com/alerts?triaged=true

According to the previous/expected behavior, the first should have alerts sorted by the "test" column. The actual behavior is that they appear to be the same.

This might have been this way since /alerts was dejinjified (https://codereview.chromium.org/1709073003), since that CL changed the way that query parameters are read on this page.

@anniesullie @eakuefner

**Comment by anniesullie** [comment]
@Apeliotes

**Comment by benshayden** [comment]
This seems to have been fixed in both V1 and V2SPA.
