### ISSUE TITLE
Reenable testCloseReferencedTab on Mac and Linux

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2455]
The Catapult roll has been failing since 4 hours ago due to a failing Telemetry unit test that looks to be due to a Chrome crash.

https://catapult-roll.skia.org/

First failing roll: https://codereview.chromium.org/2129583002

Chromium changelog beginning with `got_revision` for the above: https://chromium.googlesource.com/chromium/src/+log/HEAD/?s=51c4765d8e7934359e8f5793ad444c02e45a4d28

Last known good roll: https://chromium.googlesource.com/chromium/src/+/ea9687a5a1c2a04660b4857162b24216c78c698b

So ea9687a5..51c4765d is a good bisect range.

I'll start by disabling the failing unit test.

**Comment by eakuefner** [comment]
Unassigning myself, lowering to P2, and CCing folks who might have interest/expertise now that the disable is landing. What I don't get is, how it would have been possible for whatever Chrome change caused this issue to have passed the CQ in the first place. It doesn't look like there could be any responsible Catapult changes.

@Apeliotes @nedn @anniesullie

**Comment by nedn** [comment]
Did this also fail on other Chromium CLs?

**Comment by eakuefner** [comment]
Yes. The Swarming output for the `mac_chromium_10.10_rel_ng` bot is not really readable but you can see builds on [`linux_chromium_rel_ng`](https://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_rel_ng) which have this same failure but are unrelated to Catapult. It might be worth filing a crbug for this.

**Comment by nedn** [comment]
Thanks. Can you file a crbug for the crash?

**Comment by kenrussell** [comment]
Just noticed this bug and filed http://crbug.com/626203 about it.

**Comment by eakuefner** [comment]
Thanks @kenrussell -- we'll continue to use this bug to track reenabling the test.
