### ISSUE TITLE
Catapult rolls failing due to timeouts of telemetry_unittests on Windows

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#2456]
The last 4 attempted Catapult rolls have failed because telemetry_unittests is timing out on win_chromium_rel_ng and win_chromium_x64_rel_ng. Links to the failed rolls:

https://codereview.chromium.org/2122323002
https://codereview.chromium.org/2127703005
https://codereview.chromium.org/2124123002
https://codereview.chromium.org/2128153002

The cause is probably https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+/e25731717fa3b785d953afe417fa00272311657d and should be reverted.

CC @eakuefner @Apeliotes @nedn @ZiqiXiong

**Comment by kenrussell** [comment]
Attempting a revert in https://codereview.chromium.org/2121403003/ .

**Comment by eakuefner** [comment]
Thank you @kenrussell!

**Comment by eakuefner** [comment]
Roll went green, closing this bug.
