### ISSUE TITLE
V8 version for vinn on Windows should be updated

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2458]
It's stuck at 4.8.271.20, whereas Linux and Mac are both up to 5.1.281.59. This is preventing me from submitting https://codereview.chromium.org/2129533003/, which takes advantage of ES2015 destructuring:

```js
for (var [key, value] of myMap) {
  ...
}
```

**Comment by nedn** [comment]
Thanks. Can you fix the update script too? I was trying to update it on windows but script fails due to some reason.

**Comment by zeptonaut** [comment]
Yep! Will do. I have a fix working on my Windows computer, but I didn't have time to submit it yesterday before leaving. I'm tracking it in #2461.
