### ISSUE TITLE
Perf dashboard should only label bugs from main rotation as `Performance-Sheriff`

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2463]
Currently, the perf dashboard applies the label `Performance-Sheriff` to bugs from all perf sheriffing rotations. Then the Chromium Perf Sheriff triages all these. But they often don't have the context to triage the ones that don't come from their rotation.

We should only label bugs in monorail `Performance-Sheriff` if they come from the main Chromium perf sheriff rotation. Any objections? @rschoen 

@natorion would this be okay for the v8 rotations?

**Comment by rschoen** [comment]
Historically we've just used negative search filters to the search filter for perf sheriffs. For example, right now go/triage-backlog has -component:Blink>WebRTC. But, those labels aren't always applied, so sometimes they make it into the queue.

I'm not opposed to only applying it to the main perf sheriff rotation, but I have no insight into whether that would break other teams' workflows. Do we have a contact for each rotation?

**Comment by anniesullie** [comment]
We don't have a list, but v8 and WebRTC are the active rotations. We can easily add in new rotations with https://codereview.chromium.org/2138843003/

**Comment by rschoen** [comment]
Got it. SGTM then.

**Comment by anniesullie** [comment]
This is fixed.
