### ISSUE TITLE
Hovering over analysis link for "frame" in the alert sub view causes an error in the Javascript console

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2469]
The JS error is:

```
Uncaught TypeError: this.analysisLinkHoveredEvents_.contains is not a function
Uncaught TypeError: this.analysisLinkHoveredEvents_.equals is not a function
```

**Comment by benshayden** [comment]
Looks like brushing_state requires analysis-links to contain EventSets, or at least something that implements equals(). Maybe that restriction should be documented and supported by tr.v.Value, or else relaxed?

**Comment by zeptonaut** [comment]
I think generally everything that accepts a `selection` expects an EventSet, so I think it's probably okay not to relax the restriction. I do think that you're right that we may want to document it, though.

**Comment by zeptonaut** [comment]
It actually looks like the current documentation is just straight up wrong WRT this:

```js
    /**
     * |selection| can be anything except a function, or else a function that
     * can return anything.
     * ...
```

That sure doesn't seem right.

**Comment by benshayden** [comment]
Well, yes and no. Mostly yes. But also sort of no.
https://codereview.chromium.org/2143293002
analysis-link should be more forthright about its relationship with
BrushingStateController.

**Comment by zeptonaut** [comment]
Going to close this out, as the actual error is now fixed and we've improved some of the surrounding documentation.
