### ISSUE TITLE
Feature request: Record systrace in TBMv2 benchmarks

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2472]
_[on behalf of @rmcilroy]_

It is possible to get systrace in **non-TBM** benchmarks by adding the <tt>--profiler=android-systrace</tt> flag, e.g.:

```
tools/perf/run_benchmark --story-filter=theverge page_cycler.typical_25 --browser=android-chromium --also-run-disabled-tests --pageset-repeat=1 --profiler=android-systrace
```

However, this is not possible in **TBMv2**, e.g.:

```
tools/perf/run_benchmark --story-filter=theverge page_cycler_v2.typical_25 --browser=android-chromium --also-run-disabled-tests --pageset-repeat=1 --profiler=android-systrace
```

The command above gives the following assertion error:

```
AssertionError: This is a Timeline Based Measurement benchmark. You cannot run it with the --profiler flag. If you need trace data, tracing is always  enabled in Timeline Based Measurement benchmarks and you can get the trace data by using --output-format=json.
```

It would be great to be able to use other profilers (such as systrace) once TBMv2 is the standard way of running benchmarks. Is there a plan to add this support back to TBMv2?

**Comment by eakuefner** [comment]
I thought we had deprecated the profiler architecture because the logic was it should be possible to get these from traces, and the profiler architecture was always brittle.

@nedn

**Comment by nedn** [comment]
You don't need profiler for this. In your tbm_options configuration, just set enable_atrace_trace = True (https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/timeline/tracing_config.py#L38)

**Comment by petrcermak** [comment]
Would the systrace then be saved locally so that it could be inspected? Could we provide a command-line <tt>run_benchmark</tt> flag for this (so that it's not necessary to modify the benchmark config)?

**Comment by nedn** [comment]
Petr, I just updated my comment above to mention that the trace that are produced will be a combined trace of chrome + systrace. To have the extra command-line option, we can modify the signature benchmark.CreateTimelineBasedMeasurementOptions() to benchmark.CreateTimelineBasedMeasurementOptions(options) & people can customize their flag with benchmark.AddBenchmarkCommandLineArgs

**Comment by petrcermak** [comment]
So that would have to be done on a per-benchmark basis, right?

My first question still stands (@rmcilroy's use case): If you do this, can you inspect the systrace (or is it deleted after the benchmark finishes)?

**Comment by nedn** [comment]
If you run telemetry benchmark --output-format=json you will get the traces after benchmark finishes. 
I used to output all the traces file telemetry produced by default but chrome os folks complain about it piling up their disk spaces, hence this silly hack :-(
(https://bugs.chromium.org/p/chromium/issues/detail?id=435284)

I think we can now reconsider always output telemetry trace files in some output folder and have the bot clean up that folder properly instead.

**Comment by petrcermak** [comment]
I think that's fine (appending <tt>--output-format=json</tt>).

Regarding enabling systrace: It seems like something it would be _generally_ useful to get a systrace from an _arbitrary_ benchmark. Hence, I think we should provide a generic way to set <tt>enable_atrace_trace = True</tt> via a command-line flag.

**Comment by nedn** [comment]
Petr, mixing commandline flag logic with code logic is very hard to get right for all use cases. If the code specify enable_atrace_trace = True & commandline flag set --enable-systrace, what should be behavior? 

In general, I prefer each clients be responsible for specifying how their commandline flag interacts with their configuration done in code, rather than handling this logic from core telemetry.  In general, less commandline flags in core framework make it easier to maintain it (go/

**Comment by petrcermak** [comment]
OK, that makes sense. Thanks for the explanation :blush:

**Comment by petrcermak** [comment]
So to sum up, in order to get a systrace from a particular benchmark:

1. Set <tt>options.enable_atrace_trace = True</tt> in the benchmark's <tt>CreateTimelineBasedMeasurementOptions</tt> method and
2. Run the benchmark with <tt>--output-format=json</tt>.

**Comment by rmcilroy** [comment]
Ok, that works for my current use-case, thanks for the info.

What about the other profiler options (perf, vtune, etc). Is there a plan to support them in the v2 world?

**Comment by nedn** [comment]
@wangzhen127 has a long term plan for this.

**Comment by wangzhen127** [comment]
@peterwashington is working on merging adb_profile_chrome and Systrace. Once that's done, we could start to support other profiler options in the way atrace is don right now.
