### ISSUE TITLE
Cannot triage a large number of alerts simultaneously on dashboard (chart page)

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2474]
I'm currently dealing with a large number (261) of alerts which I would like to assign to the same bug:

![screenshot from 2016-07-13 17 27 21](https://cloud.githubusercontent.com/assets/2546601/16811191/226baa90-491f-11e6-95c6-6d736174e409.png)

However, ticking the relevant checkbox leads to the UI try to display charts for every single alert, which causes the page to freeze. Consequently, I have to assign the alerts to the bug in small groups, which is very tedious.

**Comment by anniesullie** [comment]
@simonhatch and @jessimb made some great fixes here, this is way better now.
