### ISSUE TITLE
Analysis tab view assumes that every tab is associated with a different element

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2477]
__To reproduce:__

1. Open the memory_dumps.json test data file in Trace Viewer (http://localhost:8003/tracing_examples/trace_viewer.html#/tracing/test_data/memory_dumps.json).
2. Select _both_ global and process memory dumps on the timeline view (you might as well select everything): 
![screenshot from 2016-07-14 18 51 39](https://cloud.githubusercontent.com/assets/2546601/16849804/1f2e353e-49f4-11e6-8f91-8410c15b5e18.png)
3. Click on the "Process Memory Dumps" analysis tab:
![screenshot from 2016-07-14 18 53 29](https://cloud.githubusercontent.com/assets/2546601/16849868/57b49a06-49f4-11e6-8410-ed1b1d6d93a0.png)

__Expected behavior__ (<tt>master</tt> branch): The "Process Memory Dumps" tab should be displayed.

__Actual behavior__ (<tt>polymer10-migration</tt> branch): Nothing happens.

I assume that this has something to do with the fact that both global and process memory dumps use the _same_ Polymer element for their analysis (<tt>\<tr-ui-a-container-memory-dump-sub-view\></tt>).

I'm assigning this to @zeptonaut, because he has worked on the analysis tab view.

**Comment by zeptonaut** [comment]
You're 100% right about why this is broken (and who broke it for that matter :grin:). Looking into how to fix it now.

**Comment by petrcermak** [comment]
@zeptonaut: Thanks a lot for the quick fix :blush:

**Comment by zeptonaut** [comment]
Thanks for the report!
