### ISSUE TITLE
Change 'page' field in Value to 'story_name'

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2478]
This is a migration of crbug.com/492844 (manual because crbug-to-github is broken in light of Monorail). The original text from the bug is:

> Currently, Telemetry values refer to pages by reference, and we should flatten this so that it's by name for a host of serialization-related reasons.
> 
> This will probably involve rewriting Page.name to return self._url in cases where self._name doesn't exist, since Pages sometimes don't have names, in cases where users expect to simply refer to these pages by URL. This will bring Page more in line with Story's interface, since it seems like you should be able to assume that any Story has a non-None name.

Note that since this bug was filed, we've started using `display_name`, which should be unique per-story in Telemetry (see #2429 for context) and acts exactly as described above without any extra coding., so Values should probably just contain `story_display_name`.

I was assigned to the original bug, but I'm unassigning this and marking it as a Good First Bug.

@nedn @Apeliotes @ehanley324

**Comment by ankittripathi92** [comment]
Hi @eakuefner I would like to work on this issue. Can you please guide me further on what needs to be done ?

**Comment by eakuefner** [comment]
Hey @ankittripathi92 -- if you want to get started on this, you should rename the `page` field in `Value` to `story_display_name` and update all the references to deal with story display names rather than `Story` instances.

To learn how to make a changelist and upload it, check out the [contributors' guide](https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md)

**Comment by Warewolf96** [comment]
Hello @eakuefner 

Is this issue resolved, I cloned catapult and checked for 'page' field in all the files but couldn't find any

**Comment by eakuefner** [comment]
Nope, it's not.

**Comment by gurunathpr** [comment]
How can I ( a beginner) get started on this
?

**Comment by eakuefner** [comment]
@gurunathpr Take a look at the [comment above](https://github.com/catapult-project/catapult/issues/2478#issuecomment-233446743) where I describe what to do.

**Comment by jaibhavaya** [comment]
Is this still not completed? If so I would like to work on this

**Comment by anniesullie** [comment]
This is not completed, you can go ahead and work on it.

**Comment by snoopying** [comment]
Hi, has this issue been resolved? I'm seeing story_display_name referenced in the following files..

/catapult/tracing/tracing/value/histogram.py
/catapult/telemetry/telemetry/internal/results/page_test_results.py

If it's still an open issue could you point me the files that I should be looking at? 
Thanks

**Comment by eakuefner** [comment]
No. You can take a look at the [comment above](https://github.com/catapult-project/catapult/issues/2478#issuecomment-233446743) where I describe what to do.

**Comment by eakuefner** [comment]
It's finally time to close this bug, as we're getting ready to delete telemetry/value/.
