### ISSUE TITLE
Stack dumps should include arguments

### ISSUE THREAD

**Issue by randomascii** [catapult-project/catapult#2479]
While investigating crbug.com/625172 I had to spend about an hour reproducing the crash and then recovering the crash dump. If the call stacks printed by telemetry included arguments then I could, in theory, have diagnose the bug based purely on their information.

It would also be nice if there was an option to retain the crash dumps (I had to go through painful gymnastics to actually get the crash dump) and if there was an option to record full crash dumps instead of minidumps (some of the information that I wanted was not available because it was on the heap).

This diff (changing from 'k' to 'kb') will print the first four arguments to each function on the stack.

diff --git a/telemetry/telemetry/internal/backends/chrome/desktop_browser_backend.py b/telemetry/telemetry/internal/backends/chrome/desktop_browser_backend.py
index 3e9ac8e..118f16c 100644
--- a/telemetry/telemetry/internal/backends/chrome/desktop_browser_backend.py
+++ b/telemetry/telemetry/internal/backends/chrome/desktop_browser_backend.py
@@ -447,7 +447,7 @@ class DesktopBrowserBackend(chrome_browser_backend.ChromeBrowserBackend):
       # for the crashed thread, may not be as precise as the one
       # starting from the exception context record.
       output = subprocess.check_output([cdb, '-y', self._browser_directory,
-                                        '-c', '.ecxr;k30;~*k30;q',
+                                        '-c', '.ecxr;kb30;~*kb30;q',
                                         '-z', minidump])
       # cdb output can start the stack with "ChildEBP", "Child-SP", and possibly
       # other things we haven't seen yet. If we can't find the start of the

**Comment by randomascii** [comment]
When using kb instead of k the first line of output changes slightly to include "Args to Child". That doesn't affect things - the stacks are still recorded and displayed correctly. Here is what the new header looks like:

 # ChildEBP RetAddr  Args to Child

**Comment by anniesullie** [comment]
@nedn @ehanley324

**Comment by nedn** [comment]
@kenrussell wdyt?

**Comment by kenrussell** [comment]
Sure, sounds like a fine idea.

**Comment by randomascii** [comment]
CL created but I'm not sure who to list as reviewer. https://codereview.chromium.org/2149323002
