### ISSUE TITLE
Perf Dashboard: Invalid "Bisect bot" options

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2482]
Chrome version: 51.0.2704.79 (Linux)
URL: https://chromeperf.appspot.com/group_report?bug_id=628270

When I try to bisect the chart (see the URL above), the "Bisect bot" dropdown is empty and the only available option is <tt>android\_**webview**\_aosp\_perf\_bisect</tt>, but the chart is from a __Mac__ bot:

![invalid_bisect_bot_options](https://cloud.githubusercontent.com/assets/2546601/16876713/e1d35620-4a9c-11e6-8399-82939512d9cf.png)

_[This is blocking https://bugs.chromium.org/p/chromium/issues/detail?id=628270]_

**Comment by anniesullie** [comment]
I agree the UX is terrible here, but this is a bit of an edge case:
* The bot in question is an FYI bot meant for power testing
* We have no bisect coverage of FYI bots
* The system health sheriffing patterns look for **all** masters, which includes FYI bots like this that aren't fully supported.

Should we change the sheriffing rotation to just look at masters that have bisects?

**Comment by petrcermak** [comment]
I think that would be reasonable. Without bisects, there's not much we can do :disappointed:

@primiano, @perezju: Any objections?

**Comment by primiano** [comment]
Nope. dropping FYI SGTM

**Comment by petrcermak** [comment]
@anniesullie: In that case, could you please __drop FYI bots__ from SH perf sheriffing? Thanks!

**Comment by anniesullie** [comment]
Monitoring updated.
