### ISSUE TITLE
Catch failures of setUpClass in browser_test_runner

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#2484]
Per @nedn 's comment in https://bugs.chromium.org/p/chromium/issues/detail?id=628713#c7 , browser_test_runner should look for results._classSetupFailed, and report that all tests failed if that happened:

<pre>
python's unittest runner will set results._classSetupFailed to True (see " def _handleClassSetUp(self, test, result):" in https://svn.python.org/projects/stackless/trunk/Lib/unittest/suite.py). 
browser_test_runner can check for that property to set the failure list.
</pre>

cc @ehanley324 too.

**Comment by nedn** [comment]
I can take this.

**Comment by kenrussell** [comment]
Thanks.
