### ISSUE TITLE
Figure out how to get stack traces of browser and any renderers if browser hangs during start

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#2486]
In http://crbug.com/628765 , flaky failures to launch the browser are being observed in the Telemetry-based GPU tests. The frequency of the failures is distressingly high, and is seen on at least Mac and Linux, so it isn't a problem on just one particular operating system.

It would be really helpful if Telemetry could try to send a signal to the target process (on Linux and/or Mac, at least) which would cause it to generate a core file and/or minidump, so this problem can be diagnosed.

To test the new code, a hang could be injected into the browser's main loop.

**Comment by nedn** [comment]
Topic on Chromium-dev:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/kx77ScDBYXk

**Comment by nedn** [comment]
Looks like it was due to hardware failure.
