### ISSUE TITLE
Perf Dashboard: Blank graph

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2492]
Chrome version: 51.0.2704.79 (Linux)
URL: https://chromeperf.appspot.com/report?sid=b77f7b9429b7d9ace31b4a670364a832d01a14504b29241bf5cdd65e197647f1&rev=405370

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
```
chart-slider.html:264 Uncaught TypeError: Cannot read property '0' of undefined
```

Please describe the problem:

There's __no chart__ on the graph:

![screenshot from 2016-07-18 17 44 38](https://cloud.githubusercontent.com/assets/2546601/16922860/51ac764c-4d0f-11e6-96a7-68e973beb474.png)

@anniesullie: Could you please route this to the correct person?

**Comment by anniesullie** [comment]
This is no longer completely blank, but there are only 6 datapoints, all with value 4100, and no data for the ref build. I think this is a problem with data being sent to the dashboard and not the graph itself. Is it expected?

**Comment by petrcermak** [comment]
I've just hit the same problem again: https://chromeperf.appspot.com/report?sid=d99f661d599f5bcbfd100703886515b0e03dd6f9a3ef920ce86d8f7ef0de9f66&rev=409558:

![screenshot from 2016-08-08 14 05 17](https://cloud.githubusercontent.com/assets/2546601/17480744/44e50330-5d71-11e6-8a8d-cc9bb1477adc.png)

There were _no_ JavaScript errors this time.

**Comment by anniesullie** [comment]
For the second one, it's trying to get ChromiumPerf/chromium-rel-win7-gpu-nvidia/system_health.memory_desktop/memory:chrome:all_processes:reported_by_chrome:gpumemorybuffer:effective_size_avg/browse_social/browse_social_twitter at r409558 and only one data point is returned (r409558, 0). If you hover at the exact center of the chart you can get the tooltip, and then look at the run. Digging into the JSON, I see 0 being reported for that metric: https://build.chromium.org/p/chromium.perf/builders/Win%207%20Nvidia%20GPU%20Perf%20%283%29/builds/5307/steps/system_health.memory_desktop/logs/json.output

So then let's look at the next run: https://build.chromium.org/p/chromium.perf/builders/Win%207%20Nvidia%20GPU%20Perf%20%283%29/builds/5308/steps/system_health.memory_desktop/logs/json.output
Looks like it's changed from "browse_social" to "load_social"?

**Comment by petrcermak** [comment]
Thanks for digging into the issue, Annie :blush: It looks like the <tt>gpumemorybuffer</tt> is reported quite randomly. It doesn't really matter because the reported value is 0.
