### ISSUE TITLE
Vulcanized trace contains data with a singleton string list

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2497]
I've just come across a [trace from the perf dashboard](https://console.developers.google.com/m/cloudstorage/b/chrome-telemetry-output/o/trace-file-id_30-2016-07-05_21-59-14-7909.html) which, among others, contains the following  <tt>viewer-data</tt>:

``` html
<script id="viewer-data" type="text/plain">
H4sIAI2PfFcC/4tWSjUyTja2NLPQTbRITtQ1SUtL1rUwM0rTTUwxtUwxS0wzTDJJUooFAI7TUNwoAAAA
</script>
```

which translates (base64 decode + ungzip + JSON parse) to the following:

``` javascript
["e23c3968-a8ca-4ffc-862f-ad59d6af1b4b"]
```

I found this because it causes [<tt>tracing/bin/merge_traces</tt>](https://github.com/catapult-project/catapult/blob/master/tracing/bin/merge_traces) to crash. I was very surprised by it because the data typically contains either a list of events or an object containing a list of events:

``` javascript
[{ph: 'b', ts: 123456, ...}, ...]
{traceEvents: [{ph: 'b', ts: 123456, ...}, ...]}
```

Is this a bug or is this expected?

_Note that Trace Viewer essentially skips the data it because <tt>TraceEventImporter</tt> assumes that the string is an event but <tt>"e23c3968-a8ca-4ffc-862f-ad59d6af1b4b".ph</tt> is <tt>undefined</tt> ("Unrecognized event phase: undefined (undefined)" warning is shown)._

**Comment by benshayden** [comment]
Archiving.
