### ISSUE TITLE
Alerts Page: Clicking to expand grouped revisions doesn't quite work.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2503]
Click a few times and the list expands, but first click never seems to work.

**Comment by zeptonaut** [comment]
This is reproducible in the alerts page test > "webrtc-linux-large-tests". The first click only expands one item, but any following clicks expand all three.

**Comment by zeptonaut** [comment]
Grabbing this.

**Comment by zeptonaut** [comment]
When "expand" is clicked on the leader of the group, all children are getting the `hideRow` attribute set to false on them. 

In the data binding, the `hideRow` attribute affects visibility through the data binding:

```
  <tr class$="{{item.rowType}}"
            improvement$="{{item.improvement}}"
            triaged$="{{item.triaged}}"
            hidden$="{{item.hideRow}}"
            highlighted$="{{isHighlighted(commonRevisionRange, item)}}"
            expanded$="{{item.expanded}}"
            on-click="onRowClicked">
```

So, for some reason, even though `hideRow` is getting set to false, `hidden` is still true until the second time that you click this. Weird...

**Comment by zeptonaut** [comment]
Rather than having `item.hideRow` directly control the `hidden` attribute, I had it defer to a `computeHideRow` function that looked like:

```javascript
computeHideRow: function(alert, hideRow) {
  return hideRow;
}
```

which I then set a breakpoint in. As I suspected, while the `hideRow` attribute is changing for all of the alerts, this compute function is only getting called for the alerts that are ultimately shown (3/5 of the alerts, in my test case). Somehow, the `hidden` attribute isn't picking up the fact that `hideRow` is changing.

**Comment by zeptonaut** [comment]
I tried notifying the path manually, which had no effect.

I've also checked which of the children seem to be shown, but it seems completely random. When a leader of a group of 30 gets expanded,

- The first 5 children are shown.
- The next child is hidden.
- The next 7 children are shown.
- The next 4 children are hidden.
etc.

So weird.

**Comment by simonhatch** [comment]
Decided to fiddle with this a bit over lunch. This horrible hack seems to make it work as intended:

            this.setAlertList(i, 'hideRow', isExpand);
            this.setAlertList(i, 'hideRow', !isExpand);

**Comment by zeptonaut** [comment]
Do you want to submit a CL doing that, along with a comment about how we have no idea why it's necessary?

**Comment by simonhatch** [comment]
Sure.
