### ISSUE TITLE
Alerts Page: Expanding group revisions aren't highlighted properly.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2504]
They should all be highlighted light blue, but the first one isn't. This is after you stop hovering with mouse.

**Comment by anniesullie** [comment]
Did this get fixed with some of the other fixes to databinding on this page? I can't repro.

**Comment by simonhatch** [comment]
I'm not sure if that cl fixed it, but I can't repro either, so I'll close this.
