### ISSUE TITLE
Graphs Page: Hover over points on graph doesn't show menu.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2513]
Normally hovering over points on the graph shows info about that revision range, buildbot stdio, bisect button, etc. The menu shows up very briefly, as you stop hovering over a point but disappears.

Note: Seems to work the first time you hover, but not after that.

**Comment by Apeliotes** [comment]
I think this was from before I disabled the animation on the tooltip. Simon, can you let me know if you still see the issue in this demo: https://dev-aiolos-18ab8f1e-dot-chromeperf.appspot.com

**Comment by simonhatch** [comment]
Looks like it's working fine now!

**Comment by Apeliotes** [comment]
ok, great, thanks!
