### ISSUE TITLE
Graphs Page: Red "X" close button on metrics menu doesn't hide menu.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2515]
Normally clicking that close button clears the entire menu, not just the list of metrics.

**Comment by Apeliotes** [comment]
It should also be right-aligned, not left.

**Comment by anniesullie** [comment]
I'm really sorry, I thought this was unassigned and implemented a fix: https://codereview.chromium.org/2188743002

**Comment by simonhatch** [comment]
Right alignment issue is #2514, already fixed.
