### ISSUE TITLE
Merge Polymer10-migration branch 

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#2518]
Steps for merging:

1) (Optional?) Rebase a local copy of polymer10-migration branch onto master. This will be the vast majority of the work involved if we do it. But it will leave us with a linear history for the Catapult repo. It should at least be attempted to see if it's a reasonable amount of work.

Steps:
Create a local branch.
Rebase local branch onto master.

Fixing the conflicts will be the hardest part. I highly suggest using the following merge cl's as reference:
https://codereview.chromium.org/2101873002/ 
https://codereview.chromium.org/2162963002/

2) Verify you're working on a clean local version of master, and (locally) merge the (rebased) local branch of polymer10-migration.

If we rebased first, this should be trivial. If not, there will be a much smaller number of conflicts that need to be fixed at this stage instead. (Ie, all changes to master since the second merge cl above.)

3) Test.

Verify the end state of the diff against master and the polymer10-migration branch. Especially that there are very few changes to master outside of dashboard/dashboard/elements and tracing/

Verify all unit tests pass.

Manually test. Try creating a trace, and looking at it. Deploy dashboard, and try triaging an alert and looking for a graph. Ask anyone in the SI hangout to help poke at it. I'd suggest at least 3 people looking at tracing and dashboard.

4) Push the local copy of master to origin.

This has a fairly good explanation of how to merge both with and without a rebase: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by zeptonaut** [comment]
Seems like this section of that doc is particularly useful: https://www.atlassian.com/git/tutorials/merging-vs-rebasing/workflow-walkthrough#integrating-an

**Comment by eakuefner** [comment]
Can we close this bug now?
