### ISSUE TITLE
Perf Dashboard: Selecting a large group of alerts freezes the tab for several seconds

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2519]
Chrome version: 51.0.2704.79 (Linux)
URL: https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down

Please describe the problem:
Selecting a large group of alerts (![screenshot from 2016-07-21 15 05 24](https://cloud.githubusercontent.com/assets/2546601/17025646/b4c742f6-4f54-11e6-9d72-fb31d8864777.png)) __freezes__ the tab for ~5s in the Polymer 1.0.

This problem does _not_ occur on the non-Polymer 1.0 version: https://chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff (the checkbox toggles almost instantly).

**Comment by anniesullie** [comment]
@zeptonaut fixed this in https://codereview.chromium.org/2171443002/
