### ISSUE TITLE
Perf Dashboard: "Close" button in the "TRIAGE" pop-up doesn't do anything

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2520]
Chrome version: 51.0.2704.79 (Linux)
URL: https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down

![screenshot from 2016-07-21 15 17 23](https://cloud.githubusercontent.com/assets/2546601/17026009/7056b910-4f56-11e6-8b2b-c8b11bbc1015.png)

**Comment by zeptonaut** [comment]
Grabbing this.
