### ISSUE TITLE
Perf Dashboard: Cells shifted to the right

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2521]
Chrome version: 51.0.2704.79 (Linux)
URL: https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg6p6FzAgM

Please describe the problem:
The "Revisions" cells are shifted to the right by one column.

![screenshot from 2016-07-21 15 23 51](https://cloud.githubusercontent.com/assets/2546601/17026234/46cb6d42-4f57-11e6-972e-122d2eff05a4.png)

**Comment by anniesullie** [comment]
Can still repo at ToT: https://clean-sullivan-47a90721-dot-chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg6p6FzAgM

**Comment by Apeliotes** [comment]
Looks like we're missing a header for the bug number.
