### ISSUE TITLE
Perf Dashboard: Lots of chart-legend.html messages in the console

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2522]
Chrome version: 51.0.2704.79 (Linux)
URL: https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg6p6FzAgM

Please describe the problem:
![screenshot from 2016-07-21 15 28 03](https://cloud.githubusercontent.com/assets/2546601/17026369/c662f412-4f57-11e6-8bc3-fcec09abbcc5.png)

**Comment by anniesullie** [comment]
@simonhatch if you're interested in taking this one I think we should just delete the console message--the buildbots send this invalid range and there's not a lot we can do here.

**Comment by simonhatch** [comment]
I took a look at chart-legend.html, and computeIsPositive has been redefined as:

computeIsPositive: n => n > 0,

So I don't think this is relevant anymore.
