### ISSUE TITLE
Perf Dashboard: Invalid commit ranges

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2523]
Chrome version: 51.0.2704.79 (Linux)
URL: https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/report?sid=a1f473f06c4ae7489846766cf4c11058f6fc4d4b647b5da8ea53b26b38756fb0&rev=406222

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:
The tooltip below suggests that the point on the chart comes from a **single** Chromium commit ([r404798](http://crrev.com/404798)):
![second](https://cloud.githubusercontent.com/assets/2546601/17026562/5c67c37a-4f58-11e6-9b14-0c8b2fd302c7.png)

However, the previous point's range ends at [r404794](http://crrev.com/404794):
![first](https://cloud.githubusercontent.com/assets/2546601/17026596/7f435a30-4f58-11e6-9897-6823392c5bc6.png)

So the first point must have been from the **range** r404795-r404798. In fact, that's where the (purple) link from the first tooltip takes you: https://chromium.googlesource.com/chromium/src/+log/13e84dff8a9a31764ed276346d78d347458ba125%5E..3035c93dea581354140f512b4357c795c7ca310b?pretty=fuller

**Comment by Apeliotes** [comment]
Demo live here: https://dev-aiolos-18ab8f1e-dot-chromeperf.appspot.com
