### ISSUE TITLE
Very small slices (including instant events) don't render on the timeline

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2527]
This is the last major bug that we know of on the Polymer migration branch.

Usually, no matter how small slices get in trace viewer, they're always given at least 1px width worth of representation. This means that if you zoom really far out, things look like this:

![image](https://cloud.githubusercontent.com/assets/1407397/17041247/c4696216-4f72-11e6-8d2f-9948da276138.png)

However, in the current Polymer 1.0 branch of trace viewer, when you zoom really far out, pixels aren't guaranteed that 1px of representation. That means that things look like this:

![image](https://cloud.githubusercontent.com/assets/1407397/17041279/01529346-4f73-11e6-89f2-0dc58b7e3d2d.png)

This is really bad, and we should fix this ASAP.

Note that, if you zoom in, things still show up as expected. It's just when you're zoomed out that they don't.

This is true for everything except instant events, which just never show up because they're infinitesimally small (and thus are only ever given a 1px width, which becomes 0px in this branch).

**Comment by natduca** [comment]
This should fixerate it https://codereview.chromium.org/2172873002/

**Comment by zeptonaut** [comment]
Thanks for looking into this Nat! It was awesome coming in today and having this taken care of :+1:
