### ISSUE TITLE
Importing trace in Chrome Canary fails

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2529]
The failure stack trace is:

```
Error: Could not find an importer for the provided eventData.
    at Import.createImports (chrome://tracing/tracing.js:703:64)
    at Task.run (chrome://tracing/tracing.js:1289:13)
    at runAnother (chrome://tracing/tracing.js:1301:136)
    at runTask (chrome://tracing/tracing.js:1264:57)
    at processIdleWork (chrome://tracing/tracing.js:1270:116)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:1258:81)
```

Chrome version: 54.0.2802.2 (Official Build) canary (64-bit)

Looking into this now.

**Comment by zeptonaut** [comment]
Attaching trace:

[trace_trace.json.gz](https://github.com/catapult-project/catapult/files/378504/trace_trace.json.gz)

**Comment by petrcermak** [comment]
The trace seems quite small, but could this be related to #2378?

**Comment by zeptonaut** [comment]
Yep. Closing this as a duplicate of that bug.

**Comment by zeptonaut** [comment]
Reopening this: it turns out that bug had more to do with a trace that was too long and less to do with whatever problem I'm having.

Quoting the other bug:

> Going to do some initial investigation into this. It looks like the gzip inflation in trace viewer is working, so maybe I'm just not using the right command line arguments when I do it manually. I'm seeing a successful gzip inflation followed by a failed import. Still looking into it.

**Comment by zeptonaut** [comment]
I'm wondering if our gzip inflation implementation ([`gzip_importer.html`](https://github.com/catapult-project/catapult/blob/20358d6bf8c99ec34037b78e0f8b9022622d362a/tracing/tracing/extras/importer/gzip_importer.html)) is somehow more lenient about incoming compressed data than `gunzip` is. When I try to decompress the problematic trace from the command line I see:

```bash
$ gunzip trace_trace.json.gz
gunzip: trace_trace.json.gz: unexpected end of file
gunzip: trace_trace.json.gz: uncompress failed
```
compare this with a trace recorded in Chrome stable, which I can run gunzip on successfully.

If I then copy the Chrome stable trace into Catapult ToT's /tracing/test_data folder and open it up, things work fine. Both of the traces are approximately the same size (~2MB).

I think this is a regression around the way that Chrome writes out gzipped data, not around the way that trace viewer imports it.

/cc @natduca

**Comment by zeptonaut** [comment]
I'm now having problems reproducing this by recording new traces. Very confusing. My hunch is that this might have to do with some of [@caseq's work on tracing_controller_impl_data_sinks.cc](https://chromium.googlesource.com/chromium/src/+log/master/content/browser/tracing/tracing_controller_impl_data_sinks.cc) that happened within the last two weeks. [This revision](https://chromium.googlesource.com/chromium/src/+/74b804f9aeae18a6440424b3211e946ec14e9d1d) looks like it might be relevant, but I don't know nearly enough about the surrounding code to analyze it.

@caseq, do you have any idea what might have caused tracing to start producing incomplete .gz files recently?

**Comment by lpy** [comment]
I think caseq@ is working on a fix. https://codereview.chromium.org/2193323002/

**Comment by zeptonaut** [comment]
Note that this is a dupe of https://bugs.chromium.org/p/chromium/issues/detail?id=630030
