### ISSUE TITLE
Chrome reference builds haven't been updated since April

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2533]
Context: https://github.com/catapult-project/catapult/commits/master/catapult_base/catapult_base/chrome_binaries.json

@anniesullie @nedn

**Comment by petrcermak** [comment]
_Note: This is blocking https://crbug.com/612144._

**Comment by anniesullie** [comment]
@Apeliotes would you be willing to do a manual update? Or maybe @simonhatch could take this if you've got some documentation?

**Comment by simonhatch** [comment]
Yep I can take this off your hands if the process is documented somewhere.

**Comment by petrcermak** [comment]
@Apeliotes: Are you planning to reland the update?

**Comment by petrcermak** [comment]
Could someone please provide an update on this (what's blocking the roll, what's the current ETA, ...)? Thanks :blush:

**Comment by simonhatch** [comment]
I looked into this last week:

I fixed (I think) the issues with newer ref builds stalling out on windows.
After that, the catapult roll was failing on android trybots but the version downloaded was strange in that it didn't match any of the binaries for that version. I think we just need to upload a new apk for android and try again. I messaged Kari asking if anything special needs to be done to update the binaries, or if it's just a manual process, etc. once I hear back I can do that and we can try to roll again.

**Comment by Apeliotes** [comment]
It can be done via script or by hand. I'll poke Simon offline.

**Comment by petrcermak** [comment]
Any progress on this? Should the procedure for updating the reference build be automated?

**Comment by zeptonaut** [comment]
This was accomplished in https://codereview.chromium.org/2582303003
