### ISSUE TITLE
503 error on Catapult tryserver build pages

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2537]
I get the following error:

![screen shot 2016-07-25 at 19 22 15](https://cloud.githubusercontent.com/assets/2546601/17110352/e24d3fbe-529c-11e6-9308-476f75f1f373.png)

when I try to reach any of the following URLs:

https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/3863
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/
https://build.chromium.org/p/tryserver.client.catapult/

However, the result of the trybot is available on the Rietveld page for the patch: https://codereview.chromium.org/2178903002/

@anniesullie @nedn

**Comment by anniesullie** [comment]
I filed an infra bug on crbug for this: http://crbug.com/631132

In the meantime, you can use uberchromegw urls:
https://uberchromegw.corp.google.com/i/tryserver.client.catapult

Reducing to P1 since there is a workaround.

**Comment by anniesullie** [comment]
This is now **fixed**.
