### ISSUE TITLE
Telemetry should issue trace events for high-level tracing agent commands

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2538]
It would be super useful if Telemetry issued trace events into its own trace for different high-level tracing procedures (e.g. `StartTracing` for the BattOr agent and Chrome, `StopTracing` for the BattOr agent and Chrome). Right now we're having issues with BattOr agent cycle times, and being able to visualize these within trace viewer would be enormously helpful.

**Comment by zeptonaut** [comment]
Thanks for taking this on Alex! Note that there's a decorator for tracing a function (trace_event.traced("MyFunctionName")) that we can use.

**Comment by Alex319** [comment]
It looks like this setill needs to be done. Probably, rather than using the decorator it might be better to do:

with trace_event.traced("NameOfFunction", agent=<name_of_agent>)

**Comment by benshayden** [comment]
@nedn already did something along these lines using a metaclass to cover more methods with less code: https://github.com/catapult-project/catapult/commit/6dd81149598a684d96bdf3cd482e004580ea040a

What parts of telemetry still need to issue trace events?

**Comment by zeptonaut** [comment]
Looking at @nedn's CL, I don't see anything about tracing starting and stopping tracing, which is what @Alex319 is aiming to do.
