### ISSUE TITLE
Uncaught reference error: Polymer is not defined when navigating to chrome://tracing

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#2540]
Repro in a chromium checkout:

fetch/sync to tot and build chrome. Open chrome and navigate to about://tracing.

Tracing fails to load and the console has the following error:

Uncaught reference error: Polymer is not defined

**Comment by Apeliotes** [comment]
I'm still building chrome, so I haven't repro'd yet. I assume this is related to the Polymer 1 migration, but haven't verified.

**Comment by nedn** [comment]
This is also blocking results2.html from working. Investigating..

**Comment by nedn** [comment]
Should be fixed.
