### ISSUE TITLE
No metrics appear in metrics side panel

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#2544]
I'm not seeing any metrics show up at all in the metrics side panel (Chrome 53.0.2785.21).

This happens consistently – it doesn't matter what page I trace.

**Comment by tdresser** [comment]
This might be related to #2408?

**Comment by anniesullie** [comment]
@eakuefner @Apeliotes

**Comment by zeptonaut** [comment]
Going to grab this one: I know some about the metrics side panel.

**Comment by zeptonaut** [comment]
I'm having some trouble replicating this. I'm seeing the panel working on my local dev server:

![b2mzpypcp39](https://cloud.githubusercontent.com/assets/1407397/17150435/79223c28-533d-11e6-9931-3d1f04180483.png)

@tdresser, could you give some more specific repro steps?

**Comment by zeptonaut** [comment]
Actually, @tdresser, would you mind loading up a local Catapult dev server and making sure that the problem is fixed there? I anticipate this is something that's been fixed since M53.

**Comment by zeptonaut** [comment]
(Removing P1 label until we can confirm that this is happening at ToT. I don't think the metrics side panel did anything until recently, so I wouldn't be surprised if this didn't work in M53.)

**Comment by tdresser** [comment]
Hmmm, on ToT, I'm just getting a 

"Uncaught ReferenceError: Polymer is not defined", source: chrome://tracing/tracing.js (707) 

error when I try to open tracing, so I'm not sure if it repros on ToT.

**Comment by tdresser** [comment]
Can you link the appropriate instructions for getting the dev server running?

**Comment by Alex319** [comment]
FYI, I looked into this issue before but it was fixed by https://codereview.chromium.org/2061853002. Maybe it came back again after the Polymer migration?

**Comment by zeptonaut** [comment]
@tdresser It looks like you're using M53 (dev rather than ToT). I think the CL that @Alex319 pointed to has fixed the problem since then.

To check if it's fixed in ToT, you can do

**Comment by tdresser** [comment]
Yup, it works with the dev server, thanks!

Should something be merged back to M53?

**Comment by zeptonaut** [comment]
I'm not sure: my slight preference would be for, with the idea that it wasn't really a regression because the side panel was never really working before. Given that there's been a lot of work on the metrics side panel recently, it seems reasonable to expect users to have a ToT catapult (on Chrome Canary). You'd probably know better, though.

**Comment by tdresser** [comment]
Leaving this as is SGTM. Thanks!
