### ISSUE TITLE
Starting trace recording crashes chrome on linux

### ISSUE THREAD

**Issue by deepanjanroy** [catapult-project/catapult#2548]
To reproduce: 
- Get fresh build of chromium
- open chrome://tracing
- select at least one category
- click Record 

Chrome crashes immediately.

**Comment by deepanjanroy** [comment]
cc @zeptonaut @Apeliotes

**Comment by deepanjanroy** [comment]
I don't think this is a catapult / polymer migration issue. I narrowed down the crash to this revision that landed yesterday: https://codereview.chromium.org/2158123003/ 

`pending_buf_ = nullptr` is causing the crash.

**Comment by zeptonaut** [comment]
I'm verifying this locally and will revert the offending CL once I confirm it. Thanks for tracking this down @deepanjanroy!

**Comment by zeptonaut** [comment]
Hmmmm, if I do a `gclient sync` at the CL you mentioned, I still don't seem to have https://codereview.chromium.org/2187453002/ in. I'll try to patch that in and see if things are broken at the CL you mentioned.

**Comment by zeptonaut** [comment]
After patching Ned's CL, I can confirm that things are broken after https://codereview.chromium.org/2158123003/ was submitted. I'll revert that and see if it helps.

**Comment by zeptonaut** [comment]
Closing this now that it's known that this is a Chromium bug (https://bugs.chromium.org/p/chromium/issues/detail?id=631812).
