### ISSUE TITLE
 Vertical handle is missing after clicking on any tab in the side panel

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2551]
From https://bugs.chromium.org/p/chromium/issues/detail?id=631925#c1 

Image: https://bugs.chromium.org/p/chromium/issues/attachment?aid=244373&inline=1

**Comment by nedn** [comment]
@benshayden

**Comment by eakuefner** [comment]
Looks like this bug is stale -- Ben's CL above seems to have fixed it.
