### ISSUE TITLE
Alerts Page: Takes ~10x longer to show now.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2553]
Chromeperf shows in about 1-2s, newest polymer 1.0 version takes about 15s.

**Comment by anniesullie** [comment]
This is really bad if you load /alerts?triaged=true.

It's also really slow to load /group_report?bug_id=631396 -- not sure if there are additional bugs on top of what's slowing down the alerts table.

**Comment by anniesullie** [comment]
I found it a little bit tough to get a page that was fast enough to load and grab a devtools timeline, but slow enough to show the problem. V8 sheriffing is the right size today. I saved the timeline recording if anyone wants to take a look. Looks like addEllipsis is taking up a lot of time on load with a lot of calls to setAlertList. I'll take this if I have time to look into it today, but feel free to snatch it if I don't self-assign.

[alerts-page-load.zip](https://github.com/catapult-project/catapult/files/388695/alerts-page-load.zip)

**Comment by simonhatch** [comment]
Kinda tried going through with js debugger and I kinda think what's happening is we're hitting addEllipses() which sets all the additionalColumnValues to {}, which internally hit some paths like _forwardParentPath() which calls _clearPath(), both of which iterate through all __data__ properties, ending up with something O(n^3).

**Comment by simonhatch** [comment]
This isn't 10x slower now, there's definitely a couple seconds lag compared to the old one but at least it's pretty useable.

**Comment by anniesullie** [comment]
I'm going to mark this fixed with the recent changes.
