### ISSUE TITLE
Graphs Page: Full path of metric doesn't show up.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2555]
Ie. over graph:

ChromiumPerf/android-webview-nexus5X/thread_times.key_idle_power_cases / tasks_per_second_total_all / blank.html

"blank.html" is missing

**Comment by anniesullie** [comment]
I'm really sorry I'm missing where you mean, can you add a screenshot?

**Comment by simonhatch** [comment]
<img width="1548" alt="screen shot 2016-07-28 at 11 23 26 am" src="https://cloud.githubusercontent.com/assets/11619067/17218437/c825e8a0-54b5-11e6-82a5-8cec55711331.png">

**Comment by Apeliotes** [comment]
It's actually even more fun than that. Some graphs have the full name, and some have even less information.

Full name: https://clean-aiolos-f3881da3-dot-chromeperf.appspot.com/report?sid=023e091dba09023ace304e35665cc253dff40e2397aaeee9cfc47518b843aa61

Only showing ChromiumPerf/... : https://clean-aiolos-f3881da3-dot-chromeperf.appspot.com/report?sid=874e8cf6cd7bb49576ceb975b4045fa8d56f48183f35082d9a2ff6fe337093f6

**Comment by anniesullie** [comment]
Actually the ChromiumPerf/... is WAI from how Chris designed it: https://chromeperf.appspot.com/report?sid=874e8cf6cd7bb49576ceb975b4045fa8d56f48183f35082d9a2ff6fe337093f6

That is tracked in #1664.

**Comment by anniesullie** [comment]
Did a little debugging: what's happening here is that chart-container.indicesToGraphChanged gets called and then this.$.title.update() gets called, and in the chart-title element this.seriesGroupList is always just the seriesGroupList that the chart-container was initialized with; it never gets updated with the changes to chart-container.seriesGroupList that happen when boxes are checked/unchecked.

**Comment by rschoen** [comment]
Assuming this is the same bug, this gets really bad sometimes. All I see is the very first part, like "ChromiumPerf" or "ClankInternal"

https://chromeperf.appspot.com/report?sid=a0873cb61af49df494aaca7b89aedb1aa47631cf3d5168bf3f4cf11f0768117d
https://chromeperf.appspot.com/report?sid=c35af30ed3287a005d18e692904601f7c77f7958297577888cba4ab2e448a101
https://chromeperf.appspot.com/report?sid=ebbf0d2794164176dacb0274ec18d911ddde97c0c524c79718d99ea8304705f7

**Comment by benshayden** [comment]
Archiving. V2SPA redesigns the title.
