### ISSUE TITLE
Graphs Page: Metric panel has a "less" that's clickable but does nothing.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2557]
Doesn't seem to exist in current version.

**Comment by simonhatch** [comment]
Actually I noticed this is inconsistent, on some graphs it minimizes the metrics list and on others it doesn't nothing.

**Comment by anniesullie** [comment]
Is it consistent enough that you can link an example?

**Comment by simonhatch** [comment]
https://clean-aiolos-b623b2bf-dot-chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgusb8wQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICghtyXrgoM

**Comment by benshayden** [comment]
Archiving. V2SPA redesigns the legend.
