### ISSUE TITLE
Loading spinner never stops on some /group_report?bug_id= pages

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2566]
Example: https://clean-aiolos-b623b2bf-dot-chromeperf.appspot.com/group_report?bug_id=631396

This page loads fine on my z620 workstation, very slow on mac workstation.

**Comment by anniesullie** [comment]
@simonhatch can you investigate how widespread of a problem the bug pages are? If it's everything and not just this one, please elevate to p1

**Comment by simonhatch** [comment]
Went through the last 10 or so and only 1 stopped (had no alerts associated with it).

**Comment by Apeliotes** [comment]
Should be fixed. Demo: https://dev-aiolos-5171a09e-dot-chromeperf.appspot.com/group_report?bug_id=631034
