### ISSUE TITLE
Allow to give "short names" for long metric names.

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2569]
In the case of memory-infra, for some high-level metric names such as:

```
memory:chrome:all_processes:reported_by_os:system_memory:proportional_resident_size_avg
```

we would also like to provide convenient "short names", e.g. just `overall_pss`, to be used for more friendly display on dashboards and reports. We already do something like this on the [health dashboard](https://chrome-health.googleplex.com/health-plan/android-chrome/memory/nexus5/) (the high-level short names are links to the chrome perf dashboard where the long name is used).

It would be interesting if this could be supported directly within catapult, and to be used uniformly across other places.

@nedn @eakuefner @petrcermak

**Comment by eakuefner** [comment]
@natduca and I were talking about this last week. @benshayden had introduced `RelatedValueMap` to deal with the problem of long related value names, but unfortunately that only works for introducing a short name in that context. It seems like this is a broad usability feature for memory_infra, so I think it's a good idea. Spitballing some ways that it could be surfaced:

1. In the side panel and results2.html, display short names by default, but allow the fuzzy filtering mechanism to filter long names as well, and display the long name as a tooltip on hover.
2. On the dashboard, store the short name in the `Test` entity and display these in the list of tests on the report page.

**Comment by petrcermak** [comment]
I agree that this would be great, especially for the top-level names. However, there are two caveats:

Firstly, we would have make sure that the names are unambiguous. For example, should <tt>overall_pss</tt> alias <tt>memory:chrome:all_processes:reported_by_os:**system_memory**:proportional_resident_size_avg</tt>, or <tt>memory:chrome:all_processes:reported_by_os:proportional_resident_size_avg</tt>? The situation gets even worse once you have multiple browsers (Chrome + WebView) in the trace. Presumably, we'd then need something like <tt>overall_chrome_pss</tt> and <tt>overall_webview_pss</tt>.

Secondly, [history](https://bugs.chromium.org/p/chromium/issues/detail?id=617117) has taught us that modifying the names of values reported by the memory metric is a very complex process. Therefore, I think it would be better to perform value name simplification separately from the metric (similarly to what the dashboard does).

**Comment by eakuefner** [comment]
Agreed on the point about ambiguity, and I think that would just be a matter of coming to the right consensus within memory-infra team.

With regard to modifying the names of the memory metric values, I agree that actually changing the names is a bad idea, and this is why I suggest that short name should be separate field that we surface in context-appropriate ways. I think we should definitely not do away with the fully qualified value names.

**Comment by benshayden** [comment]
It sort of sounds like the "long name" is similar to the current "description", which is currently displayed in a tooltip in the value-set-table, so your "short name" should just be the Value.name. Making the search box look through descriptions as well as names is easy.
However, you use the long name in a special way so that it isn't just for human consumption, so it should be a separate field. Or should it? Can you describe how you use the long name that requires it to be a separate field from the description?

**Comment by perezju** [comment]
I don't think the "long name" is a "description", but more like the "accurate" or "fully qualified" name given to the particular metric. The long name is needed to make sense of a metric **when shown in the context of other low level metrics**. Expanding a bit on Petr's example, the fully qualified names are necessary to make sense of the differences for each of:

```
- memory:chrome:all_processes:reported_by_os:system_memory:proportional_resident_size_avg
- memory:chrome:browser_process:reported_by_os:system_memory:proportional_resident_size_avg
- memory:chrome:renderer_processes:reported_by_os:system_memory:proportional_resident_size_avg
- memory:chrome:gpu_process:reported_by_os:system_memory:proportional_resident_size_avg
- memory:chrome:all_processes:reported_by_os:proportional_resident_size_avg
- ...
```

And just replacing one of those with `overall_pss` is going to be ambiguous and pretty confusing.

The short names make sense **when showing only high level metrics**, and thus the extra level of detail becomes redundant/unnecessary.

**Comment by nedn** [comment]
I think we should first understand whether the solution space is in value system or in the dashboard side. Seems like these short names should only be surface when the dashboard only show a group of high level metrics, it seems to me this is a dashboard feature as it require the context of which other metrics are being shown.

**Comment by petrcermak** [comment]
+1 to what both @perezju and @nedn wrote

**Comment by benshayden** [comment]
@nedn, this seems like a feature that should be shared between the dashboard and results2.html, right?

**Comment by anniesullie** [comment]
I was just going to write what @benshayden said: it seems like if we have short summary names, showing them in results2 would be good (and eventually maybe we could make use in other places like bisect bug comments). So I think this should be in values system.

**Comment by eakuefner** [comment]
My understanding matches @benshayden's and @anniesullie's -- this seems like it should very clearly be on the values side.

**Comment by nedn** [comment]
You can put an extra field like "shortName" to value, but the logic that says "use shortName when the condition X is met" have to be hard-coded on the UI that surface those values?

**Comment by benshayden** [comment]
Ned: yes. Is that ok?

**Comment by nedn** [comment]
I think so. That's what I meant by finding the solution space as the change to value is small but mostly it's about changing different UI systems that surface the values.

**Comment by eakuefner** [comment]
@nedn I think that makes sense to me. I see this as sort of like stories, where they have a computed displayName that you have to explicitly refer to if you want to surface it.

I think we should add a displayName getter to Value and then have bits of the UI opt into displaying short names by referencing displayName.

**Comment by nedn** [comment]
About naming, I think "shortName" is less confusing since both name & displayName are displayed, just in different context?

**Comment by eakuefner** [comment]
shortName is the name of the field, yes, but displayName would be computed: if a shortName is defined, return the shortName, else return the fully qualified name.

**Comment by nedn** [comment]
Is displayName a field of Value? If so, how does it help since the logic of what name to display belongs solely to the UI that surface the values?

**Comment by eakuefner** [comment]
It's not a field, it's a getter. If we didn't have that, the logic of `var displayName = v.shortName || v.name;` would have to be duplicated in multiple places.

**Comment by nedn** [comment]
I am still confused. According to Juan, we want:
1) use shortName when the dashboard only show high level memory values.
2) use fullName when the dashboard show all the values.

The logic of what is the displayName isn't as simple as v.shortName || v.name.

**Comment by eakuefner** [comment]
Ah, yeah. Makes sense.

**Comment by benshayden** [comment]
https://codereview.chromium.org/2267053002

**Comment by perezju** [comment]
Thanks! Re:

> If you're asking if there should be a getter that contains fallback logic,
maybe, I'm not sure.

I would probably say no. Maybe a first approximation for the UI where this could get surfaced is to either:
* Show only a list of metrics that have shortName set, using said shortName (and maybe make  the long name available as a tool tip or something when hovering over); or
* Show a list of all metrics using their regular long name.

In particular, we should never "fallback" in any context and try to guess a shortName for a metric if it wasn't explicitly given.

**Comment by eakuefner** [comment]
I think this is done.
