### ISSUE TITLE
Bisect failures: Bug update doesn't have bisect link

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2577]
After crrev.com/2171603002 landed, I pushed crrev.com/2145173002 to production and let the update_bug_with_results cron run. But the code in that second CL doesn't get the bisect URL that should show up on the dashboard correctly; it always prints 'Unknown'. Example: crbug.com/631059

**Comment by ZiqiXiong** [comment]
How does dashboard gets the bisect url from a try job? Is the link stored in job.results_data['buildbot_log_url']?

**Comment by anniesullie** [comment]
Fixed in https://codereview.chromium.org/2145173002/
