### ISSUE TITLE
Bisect failures: partial results not displayed correctly

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2578]
After crrev.com/2171603002 landed, I pushed crrev.com/2145173002 to production and let the update_bug_with_results cron run. Many bugs were updated with a comment that had a failure status and listed partial results. This comment is pretty confusing; I thought there was supposed to be a clearer message for partial results.

Example: https://bugs.chromium.org/p/chromium/issues/detail?id=631398#c9

**Comment by anniesullie** [comment]
Any chance to look at this?

@ro-berto

**Comment by anniesullie** [comment]
Reassigning to @dave-2 since he'll be looking into improving bisect reporting from the dashboard.

**Comment by simonhatch** [comment]
Been a lot of work around output, think this can be closed.
