### ISSUE TITLE
trace-viewer should always use native Shadow DOM

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2580]
Trace-viewer doesn't always work with Shady DOM because we sometimes do out-there stuff with overriding DOM APIs that have fairly specific defined behavior (which is probably not a best practice, but that's another conversation).

Looks like atotic set Polymer to mandatorily use native shadow DOM in the unit test runner: https://github.com/catapult-project/catapult/commit/60ddb90fe1ff2b85816e84196451c8703925e47a

but this allowance is not made anywhere else, causing bugs whereby e.g. stacked bar charts function properly in instantiation tests but not in `results2.html`. We should probably just force Polymer to use native shadow DOM everywhere in `base.html`.

@zeptonaut @Apeliotes

**Comment by eakuefner** [comment]
@natduca also mentioned that the best idea here may actually be to just explode if native shadow DOM is not being used in base, to make sure that all trace-viewer embedders do so.

**Comment by benshayden** [comment]
Should we fix tracing to support shady dom? Where does tracing override DOM APIs?

**Comment by zeptonaut** [comment]
Based on the info here, I'd support:

**Comment by natduca** [comment]
A patch to do the long term fix is here:
https://codereview.chromium.org/2267503002
