### ISSUE TITLE
Dashboard and bug are confusing for re-triaged alerts

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2582]
In crbug.com/631431, the alert was re-triaged to a different bug. Although we do have some bookkeeping in the bug with the "original alerts" link, multiple sheriffs found it confusing and were unable to locate the alert. Two potential solutions:
- **Short-term**, we could improve the warning message when there are no alerts associated with a bug to ask sheriffs to check for this.
- **Long-term**, we should consider using the monorail API to post a comment on the bug or even dupe it when alerts are re-triaged.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917848
