### ISSUE TITLE
Traffic shaping support in telemetry using TsProxy

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2584]
Doc: https://docs.google.com/document/d/1xk2ZNGFSQZ8gjc5fCFSck4-WUQehU6GmetMlP-GXYRc/edit#

**Comment by nedn** [comment]
FYI: @nyaxt @perezju

**Comment by petrcermak** [comment]
Can we please get comment access?

**Comment by nedn** [comment]
Done. Sorry.

**Comment by nedn** [comment]
This was blocked due to a bug in tsproxy when dealing with HTTPS. The bug has been fixed today in https://github.com/WPO-Foundation/tsproxy/commit/16761160e67ee9559d99f41142b55df88e632d87

**Comment by nedn** [comment]
This is done.

@irori
