### ISSUE TITLE
Implement Breakdown diagnostic

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2587]
Currently, Composition forces users to build it using Values, which must be added to a ValueSet in order to be dereferenced, but sometimes we just want breakdowns that we don't want to regression track, in which case e.g. uploading these to the dashboard is meaningless.

We should make it possible to build a composition from non-values.

@natduca @benshayden

**Comment by eakuefner** [comment]
We will probably do this by implementing a separate Breakdown diagnostic type to deal with non-values.

**Comment by benshayden** [comment]
This is done :-)
