### ISSUE TITLE
Create time breakdown report on where Chrome spends time during Time To Interactive (code name: LAWM)

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2588]
This is an overall bug to land patches against for the LAWM effort.

@natduca

**Comment by eakuefner** [comment]
Some notes here as we've spoken to V8 and thought about how to make further progress on the breakdown report:

1. Instead of forming the breakdown tree as a raw object, we should probably use Composition.buildFromEvents. This takes an EventSet, bins them by user friendly category into RelatedEventSets, forms values from the total durations, and then builds a composition from them. In order to do this, rather than using @nedn's edge case calculation for when the boundaries overlap events, we should come up with a heuristic for whether to add the event to the EventSet (basically, is it overlapped sufficiently by the FMP-TTI window)
2. `RelatedValueMap` should be subsumed by short names, see #2569 
3. Value system needs documentation: I think there is a broad lack of understanding of how the value and diagnostics systems work and I need to write a tutorial to help explain the principles.
4. Numeric samples can be added alongside a single diagnostic; when @benshayden initially implemented this functionality  he foreshadowed that we might want to be able to add a `DiagnosticMap` instead. Jochen's deep reports use case means that we want to be able to record the FMP and TTI raw timestamps along with the breakdown; each of these needs to be a separate diagnostic.

**Comment by benshayden** [comment]
Does LAWM stand for anything or have a design doc?

**Comment by eakuefner** [comment]
Hi Ben, LAWM represents a backronym for the Arabic word for "blame" and stands for "loading analysis of web metrics". It's an attempt to provide (for multiple clients) a breakdown report of where time is spent between first meaningful paint and time-to-interactive, including salient visualizations and a meaningful, TBMv2-based data representation. You may see the (internal) design doc for more details https://docs.google.com/document/d/16TOoeFeF4ltmtzILXEhPjqNXRRbl3QwcSUeNsNA0NUs/edit#heading=h.z8lajz9br42e. There are many follow-ons which have resulted from @fmeadwad and my visit to Munich and I'm happy to sit with you on Tuesday to explain all of the context and the results.

**Comment by eakuefner** [comment]
It turns out that `Composition.buildFromEvents` takes an optional callback that could, e.g. be used to manage the prorating that Ned's algorithm already does (basically, how should the sample for each event be formed; by default it is the duration). This would make it so that we don't have to implement a heuristic that resizes the selection boundary just so that a whole event can be included.

**Comment by benshayden** [comment]
It looks like this bug is done, but there's a code health bug about refactoring ChromeRendererHelper.generateTimeBreakdownTree() with RelatedHistogramBreakdown.buildFromEvents() and a new Breakdown.buildFromEvents().
