### ISSUE TITLE
Perf Dashboard: Number of alerts is not updated after triage

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2593]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
![screenshot from 2016-08-01 13 49 06](https://cloud.githubusercontent.com/assets/2546601/17294430/bc14a7d6-57ee-11e6-876b-ba3133aac322.png)

Please describe the problem:
After triaging an alert on the Perf Dashboard, the alert is removed from the list, but the "N alerts." label at the top is _not_ updated. In the screenshot below, the label should show "26 alerts.":

![screenshot from 2016-08-01 13 48 19](https://cloud.githubusercontent.com/assets/2546601/17294464/e7dba8f6-57ee-11e6-8a61-667972946741.png)

**Comment by anniesullie** [comment]
@Apeliotes Let's ensure this is fixed in the polymer 1.0 version

**Comment by petrcermak** [comment]
Related problem: When you triage only some alerts from a group, the group size is not updated either (should be "9" instead of "18"):

![screenshot from 2016-08-01 16 19 29](https://cloud.githubusercontent.com/assets/2546601/17298903/dc1b63c0-5803-11e6-8470-46b013cece39.png)

**Comment by petrcermak** [comment]
Also, the group size is completely removed when the first alert in a group is triaged:

__Before triaging__
![screenshot from 2016-08-01 16 25 32](https://cloud.githubusercontent.com/assets/2546601/17299084/b5ff8aa8-5804-11e6-8a30-68b25a0d66ab.png)

__After triaging__
![screenshot from 2016-08-01 16 25 57](https://cloud.githubusercontent.com/assets/2546601/17299088/b9a172ac-5804-11e6-829e-0acaa4f0698c.png)

**Comment by benshayden** [comment]
I think this is fixed.
