### ISSUE TITLE
Perf Dashboard: Do not add "Performance-Sheriff" label to all bugs

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2594]
URL: https://chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff

Bugs created as a result of triaging regressions in _any_ perf sheriffing shift is automatically labelled with the "Performance-Sheriff" label. As a result, the bugs are included in the [_general_ Perf Sheriffing regression backlog](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=label%3APerformance-Sheriff+Type%3DBug-Regression+modified-before%3Atoday-6+-OS%3DChrome+-OS%3DiOS+-is%3Ablocked+-status%3AExternalDependency+-Restrict%3DView-Alloy+-Performance%3DDashboard+-Performance%3DWaterfall+-Performance%3DSheriff-V8+-component%3ABlink%3EWebRTC+-component%3APlatform%3ENaCl++-component%3AInternals%3EMedia+-label%3ADontPing&sort=-modified&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids) (linked from the [Perf Regression Sheriffing guide](https://chromium.googlesource.com/chromium/src/+/master/tools/perf/docs/perf_regression_sheriffing.md)). This adds more work to _general_ Perf Regression Sheriffs.

My proposal is that each sheriffing rotation should have a separate label (or two labels, e.g. the generic one "Performance-Sheriff" and a specific one "Performance-Sheriff-SystemHealth").

**Comment by anniesullie** [comment]
Agreed. Duping against #2463.
