### ISSUE TITLE
Systrace triggering 'adb kill server' multiple times per run

### ISSUE THREAD

**Issue by ChrisCraik** [catapult-project/catapult#2598]
Takes 15 seconds to capture a one second trace with different version of adb in your path. Appears from logging to be because we're triggering an 'adb kill-server' multiple times as we swap between multiple adb versions.

> export PATH=$PATH:/path/to/android-sdk/platform-tools
> time ./systrace/bin/systrace -t 1

real	0m15.569s

> export PATH=$PATH:devil/bin/deps/linux2/x86_64/bin
> time ./systrace/bin/systrace -t 1

real	0m5.338s

@wangzhen127 may be that we need to configure devil to default to use adb in $PATH ?

**Comment by jbudorick** [comment]
devil doesn't currently make much of an effort to find adb on PATH. I'm not sure off-hand if that's supported in dependency_manager or if we'd have to handroll it. @Apeliotes 

There are multiple ways to tell devil which adb to use (e.g. [what we do on the chromium side](https://codesearch.chromium.org/chromium/src/build/android/devil_chromium.py?rcl=0&l=151) or via [ADB_PATH](https://github.com/catapult-project/catapult/blob/master/devil/devil/devil_env.py#L39)), but I'm not sure if they're useful for systrace or not.

**Comment by wangzhen127** [comment]
Does devil always switch to use the adb in devil bin if adb path is not configured?

**Comment by jbudorick** [comment]
Yes.

**Comment by ChrisCraik** [comment]
Alright, seems reasonable to have systrace push the adb by querying its location, and passing it to devil_env then.
