### ISSUE TITLE
Chrome Telemetry traces are missing clock sync events

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2599]
Steps to reproduce:

1. Run any TBMv2 Telemetry benchmark (or download one from the perf dashboard)
2. Break apart the generated HTML file into its component traces (`tracing/bin/html2trace ~/Downloads/my_trace.txt /tmp/mytrace`)
3. Open up each of the component traces until you find the Chrome trace (`less /tmp/mytrace`, `less /tmp/mytrace.1`, ...)
4. Search for the clock sync marker in the trace (I did this by typing `/"c"` inside of `less`)

**Expected**
We find a clock sync event in the Chrome trace that shows the Chrome side of the Telemetry/Chrome clock sync.

**Actual**
We see no clock sync markers.

I thought that we were already testing for regressions just by virtue of TBMv2 benchmarks existing. However, due to #2547, the regression slipped through.

I think this might have something to do with the @wangzhen127's refactoring of the Telemetry filter strings. Zhen, do you think you could investigate this?

**Comment by zeptonaut** [comment]
Also, thought I should add some context on why I thought this might be related to filter strings: last time, the cause of this ended up being the fact that we thought the "metadata" Chrome category (that clock sync events are issued under) would be turned on no matter what. However, it turned out that it was only turned on when the other default categories were enabled. (I think.)

**Comment by nedn** [comment]
Zhen: ask you fix this, we should add a telemetry unittest that assert the 'c' event exists in the trace that collect from Chrome. If this is broken on ref build, we can add @Disable('ref') to the unittest.

**Comment by wangzhen127** [comment]
Will take a look today.

**Comment by wangzhen127** [comment]
I cannot reproduce. Steps I did:

Use Chrome ToT debug build and Catapult ToT, then
```
$ git cl patch 2205623004 # This just uses blank page set for tracing benchmark.
$ tools/perf/run_benchmark run --device=desktop --browser=debug --output-format=json tracing.tracing_with_debug_overhead
$ third_party/catapult/tracing/bin/html2trace tools/perf/blank_page_html0.html mytrace
```
Open mytrace.2, you will see clock sync marker (search for ```"c"```).

**Comment by wangzhen127** [comment]
Just double checked on perf dashboard, I can also find the marker. For example:

Try the most recent trace from https://chromeperf.appspot.com/report?sid=7dc98519c46459517293dec917c52a1be9a416a8c1f53ae3516ab3d984302920

By the way, using ```/"c"``` inside ```less``` does not work. This is weird to me. Actually, it doesn't work if you search any thing. Is that because the line is too long?

But if you open it in sublime, you can find it.

**Comment by zeptonaut** [comment]
Ahhhhh! So frustrating! Why would `less` just decide to stop reading a line?!?

You're absolutely right: the line was too long. When I used `less` on the prettified version of the trace:

```
python -m json.tool /tmp/mytrace.1 | less
```

and then did `/"c"`, everything worked as expected and the trace event popped right up. Sorry for the erroneous bug, Zhen :-(
