### ISSUE TITLE
Telemetry trace contains nonsensical timestamps

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2600]
Forking this off from #2547. 

> Some of the timestamps in the Telemetry trace are wacky. For a roughly 10 second trace, the first timestamp is 1469661779.115583 and the last timestamp is 17500309181.801: the two timestamps are about 9 years apart. The former seems to be a unix timestamp from today. I'm not sure, but I'm guessing that the latter is a mach_absolute_time() output, which is how Chrome keeps track of time on Mac. It looks like something is reinitializing the current trace_time in the middle of a Telemetry run. Alternatively, something is writing a trace event but isn't using py_trace_event.trace_time as its time source.

**Comment by nedn** [comment]
Any update on this? Would be great if you can fix this soon to unblock my CL in https://codereview.chromium.org/2301523007/

**Comment by nedn** [comment]
@Alex319

**Comment by zeptonaut** [comment]
@nedn, you ended up looking at this yourself, right?

**Comment by nedn** [comment]
Yes. this should be fixed.
