### ISSUE TITLE
Can't run Telemetry unit tests on a local Android device

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2604]
Steps to reproduce:

1. Attach an Android device
2. Run a Telemetry unit test that runs on Android (`$ telemetry/bin/run_tests --browser=android-system-chrome testFirstPaintMetricSmoke`)

**Expected**
The unit tests runs and succeeds.

**Actual**
The unit test runs, but fails with [this output (Google only)](https://goo.gl/1N9yYg).

**Comment by petrcermak** [comment]
What happens when you run the failing <tt>gsutil</tt> command locally?

**Comment by zeptonaut** [comment]
Ned and I already have the fix here: https://codereview.chromium.org/2207973002/
