### ISSUE TITLE
Triaging alert while signing in: no alert

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#2605]
We appear to be loosing a reference to the alert we're in the process of triaging when going through the sign-in flow.

Haven't verified if this happens on default or not.

**Comment by anniesullie** [comment]
I'm definitely seeing issues (errors on the console at least) after the sign-in flow is finished, so I think there might be more to this than that.

**Comment by petrcermak** [comment]
Happens every time when going through the sign-in flow on the perf dashboard.

**Comment by anniesullie** [comment]
I'm sorry I'm updating the wrong bug here.

**Comment by benshayden** [comment]
Archiving.
