### ISSUE TITLE
Fix bugs in CSS animation RAIL stage

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2608]
The code to handle CSS animations in the user model, if the Animation event has subslices, checks for the "args.state" member of the subslices to determine the state of the animation in that slice (running, stopped, etc.) However it appears that these subslices actually have their args member be an object that itself has a "data" member that has the state; thus this check is not extracting the state correctly.

**Comment by Alex319** [comment]
Upon further investigation it looks like there are actually two issues here.

What handleCSSAnimations does is it looks at the top-level "Animation" events. If such an event has no subSlices then it uses the start and end of that as the start and end of the animation expectation. If such an event does have subSlices then it uses the subslice that has the "running" state as the start, and the subslice that has the paused/idle/finished state as the end.

The two issues are:

(1) As mentioned above, the case with subslices is completely broken due to checking the wrong field of the trace event.

(2) In some cases, only the trace event that puts it in the "running" state gets properly assigned as a subslice of the top-level event; the trace event that puts it in the paused/idle/finished state does not get assigned as a subslice, possibly due to being a millisecond or two after the end of the top-level trace event.

Thus, if just issue (1) is fixed, we end up with the user model not realizing that the animation ends, and thinking the animation goes all the way to the end of the whole trace.

For now, rather than messing with how slices are placed in the slice/subslice hierarchy, I'm going to fix this issue by changing the algorithm so that if the "end" subslice is missing, it stops the animation expectation at the end of the top-level slice, rather than at the end of the entire trace.

(Possibly the reason we weren't running into this issue before is because if all the trace categories are enabled, the top-level events don't end up with any subslices, and then the bug is not triggered. I found the bug getting triggered when I started only looking at a small number of trace categories. I don't know why adding all the trace categories would change how slices are assigned to subslices, given that all the relevant events are in the small number of trace categories.)

**Comment by zeptonaut** [comment]
Great investigation Alex!

**Comment by benshayden** [comment]
Is this done?

**Comment by Alex319** [comment]
Yes. This was fixed by the commit shown above.
