### ISSUE TITLE
Perf Dashboard: UI incorrectly suggests that all alerts have been triaged

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2615]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down

**Please describe the problem:**
There are still data stoppage alerts to triage:
![screenshot from 2016-08-04 19 10 04](https://cloud.githubusercontent.com/assets/2546601/17412918/1fdac8a6-5a77-11e6-9208-bc1ea10873a8.png)

**Comment by anniesullie** [comment]
https://codereview.chromium.org/2215013002/ should fix this.

**Comment by anniesullie** [comment]
This is fixed, forgot to mark it.
