### ISSUE TITLE
MemoryMetric mapper should be able to process Background traces

### ISSUE THREAD

**Issue by ssiddhartha** [catapult-project/catapult#2618]
The memoryMetric mapper cannot process the Background mode traces:
1. The Background mode is not defined in the trace event importer.
2. Effective size property should not be added in the metric, and size should be added.
3. Dumps that do not have browser process should be identify the browser name as "Chrome" instead of "unknown_browser".
4. The process names are not detected and all the processes are shown as "unknown_process". Process names can either be identified from the thread names or from the components in the dump like partition_alloc or gpu or sqlite.

**Comment by ssiddhartha** [comment]
@petrcermak @primiano

**Comment by petrcermak** [comment]
sgtm. I've left my comments in your patch (https://codereview.chromium.org/2211263002/).

**Comment by benshayden** [comment]
This is not bug in tbmv2.

Is this bug done?

**Comment by petrcermak** [comment]
It's not done yet. Sorry, I used the "TBMv2" label to mean "metric-related".

**Comment by perezju** [comment]
@ssiddhartha do you know if this is now completed?

**Comment by ssiddhartha** [comment]
It should be fixed.
