### ISSUE TITLE
Perf Dashboard: Alert drawn over bisection dialog

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2619]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/group_report?bug_id=633196

Please describe the problem:
![screenshot from 2016-08-05 14 53 45](https://cloud.githubusercontent.com/assets/2546601/17438792/8421da02-5b1c-11e6-8b55-f93285490fa8.png)

**Comment by benshayden** [comment]
This seems to have been fixed.
