### ISSUE TITLE
RelatedEventSet should be iterable and have .legnth

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2620]
It is clunky to have to use the .events getter of `RelatedEventSet` every time we want to look at an event, or tell how many events there are. Instead, let's define Symbol.iterator and add a length getter.

@nedn

**Comment by benshayden** [comment]
class RelatedEventSet extends Set?

**Comment by eakuefner** [comment]
Probably that's the most appropriate solution, yes.
