### ISSUE TITLE
Perf Dashboard: Slider out of sync with plot

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2622]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/group_report?bug_id=631112

Upon loading a chart, the slider is first in sync with the plot (note the drop in the middle):
![screenshot from 2016-08-05 15 54 12](https://cloud.githubusercontent.com/assets/2546601/17440611/4423ce2a-5b25-11e6-9c70-81af8cab6b55.png)

However, a few seconds later (no user interaction), it becomes out of sync:
![screenshot from 2016-08-05 15 54 27](https://cloud.githubusercontent.com/assets/2546601/17440626/52eac850-5b25-11e6-9c20-e1e39c0c585e.png)

**Comment by petrcermak** [comment]
The slider has very strange behavior. The following two screenshots are from the same chart (URL in my first comment) with the slider dragged by the smallest possible amount to the right:

![screenshot from 2016-08-05 16 01 18](https://cloud.githubusercontent.com/assets/2546601/17440803/0ecbd50a-5b26-11e6-8d3e-2c91979b15ae.png)
![screenshot from 2016-08-05 16 01 33](https://cloud.githubusercontent.com/assets/2546601/17440802/0ec6a648-5b26-11e6-9e0c-5f60901c4a41.png)

While the slider is pointing to pretty much the same range, the plot is completely different.

**Comment by benshayden** [comment]
Archiving. This is rewritten in V2SPA.
