### ISSUE TITLE
Regression range in table is inconsistent with revision range on graph

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2623]
From https://chromeperf.appspot.com/group_report?bug_id=631396

See https://screenshot.googleplex.com/a0rwvACxFAY

The table reports only a single revision in the range. Hovering over the point reveals a range of 5 CLs.

**Comment by benshayden** [comment]
Archiving. Unable to repro in either V1 or [V2SPA](https://v2spa-dot-chromeperf.appspot.com/#bug=631396).
