### ISSUE TITLE
Perf Dashboard: Data stoppage revision incorrect

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2624]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down

According to the "Chrome Performance Alerts" page (System Health Perf Sheriff), the last value was reported in revision **410056**:
![screenshot from 2016-08-08 13 48 08](https://cloud.githubusercontent.com/assets/2546601/17480410/b1963c3a-5d6f-11e6-988a-a7258e029845.png)

However, the chart shows that the last value was actually reported in revision **407379**:
![screenshot from 2016-08-08 13 48 29](https://cloud.githubusercontent.com/assets/2546601/17480459/e44ad870-5d6f-11e6-89c7-4e969f71c07d.png)

**Comment by anniesullie** [comment]
Would you mind pasting in:

* The full test path for that timeseries
* The page you get to when you click "Graph" with that test checked? It should be /group_report?keys=... (getting the keys will hopefully help me debug)

**Comment by petrcermak** [comment]
The full test path for the timeseries is <tt>ChromiumPerf/android-nexus5/system_health.memory_mobile/memory:chrome:all_processes:reported_by_chrome:dom_storage:effective_size_avg/browse_news/browse_news_flipboard</tt>. I've already marked the alert as "Ignore" and I don't know how to retrieve the report page for it (sorry).

**Comment by benshayden** [comment]
Stoppage alerts are gone.
