### ISSUE TITLE
Command output in device errors is sometimes too verbose

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2625]
On [device_errors](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/device_errors.py) we include the full output of adb commands that fail for one reason or another.

This is often useful when things go bad; but more often than not this tends to pollute the logs with the very long output of commands (e.g. logcat or dmesg dumps), which nearly always succeed after a single retry.

My proposal is to limit the number of lines in the output show to only a few (~10).

@jbudorick

**Comment by jbudorick** [comment]
I'm not crazy about this. What about either not printing the exception or printing it at a lower log level if we're retrying the function that raised it?

**Comment by perezju** [comment]
Ok, that seems doable.

**Comment by perezju** [comment]
As per the CL, we settled for reducing the output of commands that failed due to exit status missing, which are retried anyway by RunShellCommand in "large output" mode. Also fixed a few clients that should have been using large_output=True in the first place.
