### ISSUE TITLE
Perf Dashboard: Data stoppage bisect

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2628]
As far as I'm aware, there is currently no way to bisect a data stoppage alert because the bisect fails when the relevant value is missing.

@anniesullie

**Comment by anniesullie** [comment]
@vuppalapu @ro-berto @dave-2 I'm not aware of a way to bisect a test that has a missing value but still passes, are you?

**Comment by benshayden** [comment]
Stoppage alerts are gone.
