### ISSUE TITLE
test-suite dropdown misbehaves on backspace

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#2633]
Steps to reproduce:
1. Select suite / bot / benchmark (for instance. blink_perf.bindings / linux-release / create-element).
2. Hit the "add" button.
3. Select the first dropdown and try to remove the suite name by means of backspace.
4. Focus jumps to the second dropdown after the first backspace but still shows the suite dropdown.

**Comment by chromy** [comment]
Should be fixed now.
