### ISSUE TITLE
Perf dashboard: can't use arrow keys to navigate between list entries

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2634]
When you click into a text box to select a test suite, bot, benchmark, etc., I'd expect that you'd be able to use the arrow keys to navigate between entries in the dropdown. However, pressing up or down has no effect.

**Comment by anniesullie** [comment]
Kari, something to check for in autocomplete libraries.

**Comment by chromy** [comment]
Works a bit better now.
