### ISSUE TITLE
Metrics side panel draws over analysis view

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2635]
("Memory Dumps" sample trace in ToT Trace viewer on http://localhost:8003)

![screenshot from 2016-08-09 16 53 15](https://cloud.githubusercontent.com/assets/2546601/17523254/dbb4015e-5e51-11e6-98cf-c0dd98387ed5.png)

@eakuefner

**Comment by petrcermak** [comment]
@benshayden: Ping. This __severely limits__ the functionality of the "Metrics" side panel.

**Comment by petrcermak** [comment]
(the reason why it's such a big problem is that you __can't scroll__ the view)

**Comment by benshayden** [comment]
Sorry, I'm still catching up on email from my leave. I'll look at this today!

**Comment by benshayden** [comment]
https://codereview.chromium.org/2248393003

**Comment by eakuefner** [comment]
This is done.
