### ISSUE TITLE
Ctrl-key resets dropdown

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#2640]
Pasting a new value over and existing selected item in the dropdown resets the selection and clears the text.
Trying to work around issue #2639 I resorted to copy-pasting the longest subtest name with medium success.
## Steps to reproduce
1. Select an test-suite e.g. "blink-perf.events".
2. Press Ctrl (On linux with chrome M52 - M54).
3. The test suite and all the subtest dropdowns are reset (though not the bot dropdown).

**Comment by simonhatch** [comment]
The test-picker code was completely rewritten back in Dec by @chromy, I don't think this is valid anymore and I can't reproduce it (I could repro it on an older dashboard).
