### ISSUE TITLE
Dashboard: Report deeplink does not restore subtest path

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#2641]
On a deep link like https://chromeperf.appspot.com/report?sid=7b3cbbecc9a38af84367e8edf6abdc3b8ccf545590b40ef0ec22c7be2ac6198d the dropdown selection is not restored.

Our scenario is that we usually have to check for flakes when looking at a graph. The most reliable way to do so is by adding the subtest from a different bot to see whether they regressed at the same time.

Without knowing the specifics of the whereabouts of each of the benchmarks its rather hard to figure out how to get there. Restoring the selection with the deeplink would greatly facilitate this task.

**Comment by simonhatch** [comment]
We spoke offline, recording here in case anybody takes this before I do. I believe we talked about making clicking the title auto-populate the picker path since you can potentially have multiple graphs.

**Comment by benshayden** [comment]
Sorry, I shouldn't have taken "clicking the title" so literally...

chart-title already supports clicking on the non-leaf test path components to browse subtest paths. That seems like a behavior that should be supported orthogonally to this new behavior. (Should we discuss later whether browsing subtest paths in chart-container should be supported at all?)

[This demo](https://dev-benjhayden-a077e9f7-dot-chromeperf.appspot.com/report?sid=ca6c52111f8337a0f6478573cd639ed39dbd8eb82d903d8c3932651f452b9fb9) adds a new paper-button using the [north west arrow to long bar](https://unicode-table.com/en/21B8/) unicode point.

![](http://i.imgur.com/W714lhW.png)

**Comment by simonhatch** [comment]
That's really nice, happy with that over clicking on the title.
