### ISSUE TITLE
Bisects no longer decending into V8 rolls.

### ISSUE THREAD

**Issue by rmcilroy** [catapult-project/catapult#2643]
During my perf regression stint I found that a number of bisects showed clear regressions on a V8 roll CL, but didn't decend into that V8 rolls to find the actual CL which caused the regression.

Example at:
https://bugs.chromium.org/p/chromium/issues/detail?id=635912

**Comment by petrcermak** [comment]
This is a duplicate of https://bugs.chromium.org/p/chromium/issues/detail?id=636310 (possibly also https://bugs.chromium.org/p/chromium/issues/detail?id=632712).
