### ISSUE TITLE
Perf Dashboard: Axis legend drawn over toast

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2654]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/group_report?bug_id=635920

The _"sizeInBytes (lower is better)"_ legend of the chart's y-axis is drawn over the _"Job submitted! View job [...]"_ toast:

![screenshot from 2016-08-10 13 05 432](https://cloud.githubusercontent.com/assets/2546601/17584123/c8dbc1fa-5fac-11e6-8574-711f300fba9c.png)

**Comment by benshayden** [comment]
Fixed in both V1 and V2SPA.
