### ISSUE TITLE
Systrace timeout parameter not used

### ISSUE THREAD

**Issue by peterwashington** [catapult-project/catapult#2660]
I have noticed that systrace allows the user to specify a timeout as well as a collection timeout. This user-specified timeout is passed through to the tracing agents, none of which use the timeouts in any way.

@ChrisCraik @wangzhen127 Is there any reason to keep the timeout, or can I refactor the code to remove the optional timeout parameter which is never used and also remove the --timeout and --collection-timeout systrace options?

**Comment by Alex319** [comment]
They are used. The StartAgentTracing, StopAgentTracing, etc. functions are decorated with @py_utils.Timeout, which passes the timeout value to timeout_retry.Run.  The decorator definition is in catapult/common/py_utils/py_utils/init.py - the default value you see on the decorator line (e.g. tracing_agents.START_STOP_TIMEOUT) is just the default value, which is overridden if you pass something into the timeout kwarg.

**Comment by peterwashington** [comment]
Ah I see, thanks for the clarification @Alex319.
