### ISSUE TITLE
AnalysisView tabs shouldn't scroll out of view

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#2665]
It looks like during the polymer1 conversion, tab view or analysis view or some part of it changed its scrolling behavior. When a child element of the tab view is very tall, the tabs of the tabview shouldn't scroll offscreen.

What I observe:
![image](https://cloud.githubusercontent.com/assets/412396/17608292/65f2f174-5fe0-11e6-894d-f7bde30190af.png)

What would be better is if the tab view labels were still visible and only the tab-contents were scrolling.

**Comment by anniesullie** [comment]
@zeptonaut
