### ISSUE TITLE
Catapult roll failing telmetry_perf_unittests

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2669]
[List of CLs in the roll](https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+log/e44cc4099066..ccf86548d411)

Failures:
`core.trybot_command_unittest.IsBenchmarkDisabledOnTrybotPlatformTest.testBenchmarkIsDisabledAll`
`core.trybot_command_unittest.IsBenchmarkDisabledOnTrybotPlatformTest.testBenchmarkIsDisabledOnMultiplePlatforms`

Failure examples:
[win_chromium_rel_ng](https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_rel_ng/builds/272376)
[linux_chromium_rel_ng](https://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_rel_ng/builds/278807)
[win_chromium_x64_rel_ng](https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_x64_rel_ng/builds/260599)
[linux_android_rel_ng](https://build.chromium.org/p/tryserver.chromium.android/builders/linux_android_rel_ng/builds/121258)

Failure logs:
```
[189/291] core.trybot_command_unittest.IsBenchmarkDisabledOnTrybotPlatformTest.testBenchmarkIsDisabledAll failed unexpectedly 0.0005s:
  Traceback (most recent call last):
    File "/b/swarm_slave/w/ir4I1D_Y/tools/perf/core/trybot_command_unittest.py", line 644, in testBenchmarkIsDisabledAll
      self.assertTrue(self.IsBenchmarkDisabled(FooBenchmark, 'all'))
  AssertionError: False is not true
```
```
[190/291] core.trybot_command_unittest.IsBenchmarkDisabledOnTrybotPlatformTest.testBenchmarkIsDisabledOnMultiplePlatforms failed unexpectedly 0.0003s:
  Benchmark trybot_command_unittest.FooBenchmark has ShouldDisable() method defined. If your trybot run does not produce any results, it is possible that the benchmark is disabled on the target trybot platform.
  Benchmark trybot_command_unittest.FooBenchmark has ShouldDisable() method defined. If your trybot run does not produce any results, it is possible that the benchmark is disabled on the target trybot platform.
  Benchmark trybot_command_unittest.FooBenchmark has ShouldDisable() method defined. If your trybot run does not produce any results, it is possible that the benchmark is disabled on the target trybot platform.
  Traceback (most recent call last):
    File "/b/swarm_slave/w/ir4I1D_Y/tools/perf/core/trybot_command_unittest.py", line 668, in testBenchmarkIsDisabledOnMultiplePlatforms
      self.assertTrue(self.IsBenchmarkDisabled(FooBenchmark, 'all-mac'))
```
Suspect [`Fix the @Disabled decorator so sub/superclass disables don't affect each other.`](https://codereview.chromium.org/2238673002). Reverting now.

**Comment by anniesullie** [comment]
@nedn @ehanley324 FYI

**Comment by nedn** [comment]
This if fixed.
