### ISSUE TITLE
[dashboard] Triage dropdown elements scattered

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2671]
https://screenshot.googleplex.com/prEu5eXAKz9.png

**Comment by anniesullie** [comment]
What OS/version of chrome? I can't repro on Mac 10.11/Chrome 52.0.2743.82. Any errors in the JS console? This is on /alerts and not /group_report, right?

**Comment by benshayden** [comment]
ChromeOS, Pixel 1, I'll check the version and try to repro tonight.

no devtools console errors iirc

yes /alerts

**Comment by benshayden** [comment]
54.0.2824.0 dev
Platform 8688.0 dev-channel link

Forgot to try to repro.

**Comment by benshayden** [comment]
Archiving.
