### ISSUE TITLE
DiagnosticMap should be iterable and have .length

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2678]
'Nuff said.

I wonder if we want to have a common base/ superclass for these things, or if we can rationally extend a builtin, because this issue seems to be cropping up a lot.

**Comment by benshayden** [comment]
@zeptonaut Any thoughts on subclassing ES6 builtins like Map/Set? The style-guide says "to be discussed".

**Comment by zeptonaut** [comment]
My opinion is that, if you have good reason to, give it a shot. [Proceed with caution, though](http://www.2ality.com/2013/03/subclassing-builtins-es6.html): it looks like there may be some sharp edges.
