### ISSUE TITLE
Map Traces with runtime call stats to callstats.py tsv format

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#2679]
Too verify the validity of the data we are collecting from the runtime call stats in tracing system, we need to transform the data to be visualized with the callstats.py tool.

We need to write a mapper (that will live in experimental) to extract the runtime call stats from the trace and dump them into the tsv format used as input for `callstats.py json` generator.

@simonhatch @lpy 

CL is in progress.

**Comment by benshayden** [comment]
This isn't really a results2 bug.

Is this done?

**Comment by fmeawad** [comment]
Almost, yes.

**Comment by fmeawad** [comment]
Fixed.
