### ISSUE TITLE
Make adb_profile_chrome's Telemetry dependencies accessible from Systrace without circular dependency

### ISSUE THREAD

**Issue by peterwashington** [catapult-project/catapult#2680]
The Perf profiling agent in profile_chrome will soon be moved into Systrace. The Perf profiling agent contains two Telemetry dependencies. However, because Telemetry currently depends on Systrace, using these Telemetry import statements would create a circular dependency between Telemetry and Systrace. Therefore, we must make an attempt to move this code from outside of Telemetry. 

The two dependencies are: 

1) `from telemetry.internal.platform.profiler import android_profiling_helper` → The android_profiling_helper is used extensively in the Perf tracing agent. It appears that a lot of the code in android_profiling_helper and the Telemetry files it depends on are not specific to Telemetry (although many of them certainly are).

2) `from telemetry.internal.util import binary_manager` → We will be able to replace this dependency to depend on `[catapult directory]/catapult_base` rather than using the Telemetry version of the binary_manager. The Telemetry binary_manager is actually just a lightweight wrapper over the binary_manager in [catapult directory]/catapult_base anyways, and the functionality the Telemetry wrapper includes can be refactored for use in Systrace.

**Comment by peterwashington** [comment]
@nedn @anniesullie @wangzhen127 Would you all be okay with me moving android_profiling_helper.py out of Telemetry and into catapult_base? 

It looks like the only two "customers" of android_profiling_helper.py are the Perf profiling agent (which is the reason I would like to move it out of Telemetry in the first place) and the vtune_profiler, which is in Telemetry. android_profiling_helper uses android_prebuilt_profiler_helper, which is used in a few more places In Telemetry (tcdump_profiler, android_platform_backend, and associated files). So this move would result in very limited changes elsewhere in the Telemetry codebase (which I would include in this CL).

The other  parts of Telemetry that are used in the android_profiling_helper aren't particularly specific to Telemetry and could be moved to catapult_base.

**Comment by nedn** [comment]
Moving it out of telemetry is fine, but I don't think catapult_base is the best place. Can its API be changed to compatible with the systrace_agent stuffs?

**Comment by peterwashington** [comment]
Sure, the API could be changed to go into systrace, if I understand correctly. Would you prefer to make a second copy of it in systrace that would just be used by systrace's Perf tracing profiler, or just keep one copy that the vtune_profiler/tcdump_profiler in telemetry would also depend on (since telemetry already depends on systrace)?

**Comment by peterwashington** [comment]
@ChrisCraik Would you be okay with the move of this code from Telemetry into Systrace. The (non-Telemetry-specific) code that we would be moving into Systrace would contain much of the functionality of [android_profiling_helper.py](https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/internal/platform/profiler/android_profiling_helper.py?is_navigation=1&q=package:%5E(chromium)$+file:(/%7C%5E)telemetry/internal/platform/profiler/android_profiling_helper(%5C.(swig%7Cpy%7Cspt)$%7C/(__init__%5C.(swig%7Cpy%7Cspt))?$)&l=1) which is currently in Telemetry. This code is responsible for {FILL OUT}. This android_profiling_helper would be used solely for the Perf tracing agent, although it will inevitably result in a few more dependencies to Systrace from Telemetry.

**Comment by peterwashington** [comment]
@wangzhen127

**Comment by peterwashington** [comment]
@ChrisCraik Would you be okay with the move of this code from Telemetry into Systrace. The (non-Telemetry-specific) code that we would be moving into Systrace would contain much of the functionality of android_profiling_helper.py which is currently in Telemetry. This code is responsible for getting the set of libraries needed to symbolize a Perf trace profile. This android_profiling_helper would be used solely for the Perf tracing agent, although it will inevitably result in a few more dependencies to Systrace from Telemetry. This change can be useful if even more tracing agents are added in the future (e.g. tracing agents in Telemetry that we may one day, probably after my internship, potentially want to add into Systrace as well).

**Comment by peterwashington** [comment]
Since we have decided to keep the perf tracing agent in adb_profile_chrome and instead use simpleperf in systrace, this issue no longer applies.
