### ISSUE TITLE
Perf Dashboard: toast usability issues

### ISSUE THREAD

**Issue by chcunningham** [catapult-project/catapult#2684]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgzqDe4wgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgzsHzvAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgjr-fsQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgjpuV8wsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgroz3qQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgztbOrAoM

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:
When running a bisect, the toast that pops up to notify that the job is submitted does not appear to open a new page when clicked (to view the job status). Worse, it dismisses the toast immediately when clicked, so I don't know the bisect job number either.

**Comment by anniesullie** [comment]
I can't reproduce on a Mac using Chrome 52. It looks like for both bisects, the bug was also updated with a link to the bisect, so you can use this as a workaround.

@dave-2 another bisect UX issue. In addition to the problems with the toast, there is no quicklog on the page listing bisects.
