### ISSUE TITLE
Perf Dashboard: Empty graph when start_rev and end_rev are provided

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2689]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/report?sid=4574cd726934a43ad26653742ccf9dd5a1d8c8a13d5ab01a90abd66fe71cfcfd&start_rev=403609&end_rev=406000

**Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):**
![screenshot from 2016-08-18 10 33 28](https://cloud.githubusercontent.com/assets/2546601/17769156/37d783f0-652f-11e6-8086-61727994e3ef.png)

**Please describe the problem:**
Both the graph and the legend are empty:
![screenshot from 2016-08-18 10 33 50](https://cloud.githubusercontent.com/assets/2546601/17769174/4915dd4c-652f-11e6-8d46-de17abf4eb30.png)

If I remove <tt>start_rev</tt> and <tt>end_rev</tt> from the URL, then everything works fine (https://chromeperf.appspot.com/report?sid=4574cd726934a43ad26653742ccf9dd5a1d8c8a13d5ab01a90abd66fe71cfcfd):
![screenshot from 2016-08-18 10 36 00](https://cloud.githubusercontent.com/assets/2546601/17769234/92becdb4-652f-11e6-88df-4a92145dc60a.png)

At this point it would seem that there's simply no data between the provided <tt>start_rev</tt> (403609) and <tt>end_rev</tt> (406000). However, that's _not_ the case. To see this, type "system_health.memory_desktop" into "Test type", "chromium-rel-win7-dual" into "Bot", "memory:chrome:all_processes:process_count_avg" into "Subtest" and click on "Add". The legend on the top graph shows that there _is_ data between the two revisions:
![screenshot from 2016-08-18 10 39 18](https://cloud.githubusercontent.com/assets/2546601/17769389/371f6dbe-6530-11e6-8e75-7c396c1b1cee.png)

Now refresh (F5) and both graphs are blank:
![screenshot from 2016-08-18 10 41 57](https://cloud.githubusercontent.com/assets/2546601/17769436/7044bfb8-6530-11e6-9411-9813884575ce.png)

I suspect this has something to do with the fact that the aggregated value was _not_ recorded during the selected range, but only its components (browse_media, browse_news, browse_social, load_games, ...) were.

@simonhatch

**Comment by benshayden** [comment]
Archiving.
