### ISSUE TITLE
Pass in custom options to Systrace agents

### ISSUE THREAD

**Issue by peterwashington** [catapult-project/catapult#2690]
Right now, the Systrace API's StartTracing method has the following signature:

`def StartAgentTracing(self, options, categories, timeout=None)`

The big problem here is that the `options` parameter is currently a global object that contains all the command-line options, which doesn't work now that Systrace will support multiple agents. Therefore, the `options` field will now contain a custom options class that will inherit from a base options class that contains common options. Something along the lines of:

```
class AgentOptions(class):
    def __init__(self):
        self.categories = [] # List with default categories
        ...

class ChromeAgentOptions(agent_options.AgentOptions):
    def __init__(self):
        self.ring_buffer = False # Set default options in the option classes
        ...
```

@skyostil @ChrisCraik Any thoughts / modifications to the above proposal?

**Comment by peterwashington** [comment]
@wangzhen127

**Comment by wangzhen127** [comment]
This will affect its clients like Telemetry. Remember to update the client side too.

@nedn

**Comment by peterwashington** [comment]
If we don't want to change the API to update all of the current instances where the client calls one of the Systrace agents, another option is to still have the custom options classes as proposed and pass in the list of categories separately, not changing the API. If changing the API to just take in a customized options/config object is approved, I would be happy to update the calls in Telemetry.

**Comment by wangzhen127** [comment]
I think it is cleaner to use configurations instead of passing in options and categories.

@ChrisCraik @skyostil @ned , what do you think?

**Comment by ChrisCraik** [comment]
When you say configurations, do you mean objects specifically for
controlling agents?

One of the difficulties of moving away from an options object is that there
are several specialized options that aren't fully generic, and just sort of
hacked in place (--from-file, --list-categories). Directing those to a
particular agent's configuration may be awkward, and leaving them in a root
config passed to everyone doesn't really provide any benefit vs the options
object.

**Comment by peterwashington** [comment]
The configurations would basically be the options+categories in one object. 

The issue you mention regarding the hacky non-fully generic options would probably remain regardless of this potential refactoring, if I understand correctly? That is, even without this refactoring effort, running `bin/systrace --help` would display these same semi-generic options like --list-categories. With all the profile_chrome agents in systrace, we can either list this option as systrace-specific or as a global option.  So I think the awkwardness you describe is something that we need to address regardless of whether we pass in a global options object like we currently do.

**Comment by wangzhen127** [comment]
Those specialized options are for atrace and ftrace, right? Can we just continue to use those for atrace agent only (which is the usual case for Android developers).

To list categories, we can use --perf=list to list perf categories. And similar to other agents, e.g., --ftrace=list to list ftrace categories.

Another related thing to consider is maybe Android SDK want to include some agents, but not all of them. When we run ```./systrace --help```, it should only print the relevant flags. For example, if Android SDK doesn't want to include chrome agent, it should not print anything related to chrome agent. This cannot be done because all flags are defined in one place: run_systrace.py

So I think one way of doing this is:

- run_systrace.py defines the common ones, e.g., output format.
- Each agent defines its own flags and decides how to handle/parse/process its own flags.
- Each agent's flag can be dynamically added to the option parser.
- In the main function in run_systrace.py, we get the parsed options for everything. Then each agent can create its own configuration object based on that.

Example pseudo code:

atrace_agent.py
```
def add_options(parser):
  options = optparse.OptionGroup(parse, 'Atrace options')
  options.add_option(...)
  return options

def get_config(options)
  // The passed-in options contain everything, including stuff from other agents.
  // But this should only construct the config from common and atrace flags only.
  ...
  return config
```
run_systrace.py
```
def main():
  parser = optparse.OptionParser('Systrace options')
  parser.add_option(... common ones ...)

  for module in AGENT_MODULES:
    module.add_options(parser)

  options = parser.parse_args(argv[1:])
  controller = systrace_runner.SystraceRunner(..., options, ...)
```
systrace_runner.py
```
def CreateConfigurationAndAgents(options):
  results = []
  for module in AGENT_MODULES:
    config = module.get_config(options)
    agent = module.try_create_agent(config)
    results.append((config, agent))
  return results
```

**Comment by peterwashington** [comment]
@wangzhen127 Your proposal sounds good to me.

@ChrisCraik @skyostil Does this sound good to you?

**Comment by nedn** [comment]
From my experience with telemetry, the paradigm of using the python's parser options to pass data around later turn out to be code debt as each options contain more info than the function consuming it needs to use ("You wanted a banana but what you got was a gorilla holding the banana and the entire jungle.”). If we can find a way to only pass the configs that are relevant for each agent, it would be ideal.

Having said that, I can see that whether this is a problem also depends on the code base's size and leave it to @ChrisCraik & @skyostil  to make the final calls.

**Comment by skyostil** [comment]
This seems fine to me. Per-agent configs make it pretty clear which options each agent provides and uses. The config parsers can run into that problem of finding the banana in the jungle, but it doesn't seem like a huge issue since it's localized to that one function.

**Comment by peterwashington** [comment]
Fixed in https://codereview.chromium.org/2276263003/.
