### ISSUE TITLE
PyVulcanizes reorders javascript in html files that mix imports, inline script and external script

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#2698]
If you have an html module that has a mix of inline scripts, external scripts, and imports, they get reordered by the vulcanizer. For instance, if you had:

<script src=a>
<script>
b
</script>

<link import=c>

these will always get reordered to be
- imports
- external scripts
- inline scripts

Eg, we'd run c, then a, then b.

Fixing this requires surgery on generate.py, html_module.py, and module.py's GenerateJS functions. What we need to do is output JS by walking through the elements in the module line by line, descending into imports and outputting their script precisely when we see them.

**Comment by eakuefner** [comment]
@natduca If you git revert ab02b4de94f7252989d70a0a6379706fe612b280 it should work.

**Comment by natduca** [comment]
Ugh, I began working on this on Friday and ran into a massive architectural mess that makes fixing this hard. I'm not giving up, but its going to take... work.

**Comment by deepanjanroy** [comment]
Closed by 6c40c273a7fe857803a56575644cfa81880673ad.
