### ISSUE TITLE
Catapult rolls failing

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#2699]
Catapult rolls have been failing since this attempt:
https://codereview.chromium.org/2265473002/

which contains this commit:
https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+log/04dd47e541e2..9fcccf0b6570

There are currently a lot of problems with telemetry-based tests failing on the Chromium tryservers. See in particular the telemetry_perf_unittests and telemetry_gpu_unittests failures here:
https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_rel_ng?numbuilds=200

Some of those failures are failed Catapult rolls, but some seem to be affecting other tryjobs. Investigation is needed.

**Comment by anniesullie** [comment]
@nedn @ehanley324

**Comment by nedn** [comment]
It has passed.
