### ISSUE TITLE
Remove hacky code to patch broken buildbot links  

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2704]
Remove this [hacky code](https://github.com/catapult-project/catapult/blob/0dcec6cdf90b7aea2053f659780d995983d335d3/dashboard/dashboard/graph_json.py#L236), probably after November 2016 when affected points are old enough.

@anniesullie

**Comment by benshayden** [comment]
[Done](https://chromium-review.googlesource.com/c/catapult/+/1096287)
