### ISSUE TITLE
side_panel_container has confusing control flow

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2705]
It's difficult to decipher exactly what's happening in side_panel_container around `updateContents_`, `setActivePanelType`, the `model` setter. There's some code duplication, and funky stuff like setting the model to itself to get stuff to update.

We should just make updateContents_ handle basically everything, in the same way that it does in most of the rest of tracing. Maybe there will be some extra stuff to encapsulate in another helper; we'll cross that bridge when we get there.

@zeptonaut @benshayden

**Comment by zeptonaut** [comment]
Thanks for taking this on Ethan: I had to interact with the side panel container some during the Polymer migration, and totally agree that it does some confusing stuff.

**Comment by eakuefner** [comment]
Archiving; this will probably be subsumed by Perfetto.
