### ISSUE TITLE
Toast in results2.html when user is expecting results(1).html

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2709]
https://elements.polymer-project.org/elements/paper-toast?active=paper-toast&view=demo:demo/index.html

**Comment by benshayden** [comment]
So can we use paper-toast now?

Also, I'm trying to figure out what this should say.
 * We rewrote results.html! [Email us](http://...) with questions or bugs or to tell us what a HUGE IMPACT this new version has on your life!

**Comment by eakuefner** [comment]
We're not going to bother with this, I don't think.
