### ISSUE TITLE
Perf Dashboard: 

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#2710]
Chrome version: 52.0.2743.116 (Linux)
URL: https://chromeperf.appspot.com/edit_sheriffs

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:

Usually, the "List monitored tests" button will list the tests that correspond to the patterns in the "Patterns:" box. However, right now it doesn't matter what patterns I put it the box: it always displays the same tests.

Steps to repro:
1. Go to https://chromeperf.appspot.com/edit_sheriffs
2. Edit existing config: -> Chromium Perf AV Sheriff
3. Change the list of tests in the "Patterns:" box (for example, remove all of the patterns)
4. Click "List monitored tests"
5. View the results. (If you removed all the patterns there will still be results.)

**Comment by CalebRouleau** [comment]
This is blocking https://bugs.chromium.org/p/chromium/issues/detail?id=640326

**Comment by anniesullie** [comment]
This actually hasn't changed, it's always the tests that are currently monitored that are listed by that button.

You could go to https://chromeperf.appspot.com/migrate_test_names to check if tests match patterns.

**Comment by CalebRouleau** [comment]
Thanks for the help!
