### ISSUE TITLE
Perf Dashboard: Can not drag graph onto existing graph

### ISSUE THREAD

**Issue by aschulm** [catapult-project/catapult#2712]
Chrome version: 52.0.2743.82 (Mac)
URL: https://chromeperf.appspot.com/report?sid=467dd3f8d0519d226cba87c496db5317a9340f8b8ef3219611db41ce1b7970b3

When I try to drag the 4 arrow icon to overlay two graphs the dashboard says "Saving Report" but then the graphs are never overlaid.

![screen shot 2016-08-24 at 11 59 36 am](https://cloud.githubusercontent.com/assets/7672081/17943912/4b2a60cc-69f2-11e6-999e-28c05e20db1c.png)

**Comment by anniesullie** [comment]
This is really weird, I can't get this to happen on my Mac with Chrome 52.0.2743.116.

Can you expand the error message in the console and paste it here? It looks like a problem in the autocomplete box, maybe you changed the menus multiple times and its state got messed up? (Still a bug of course, just the only explanation I can think of for why I'm not seeing it)

I think this is the url you're looking for? https://chromeperf.appspot.com/report?sid=c0ce29ca933016cdcb4df24fad34c59d280bad1b59f91fce561a4bf65763112a

@Apeliotes

**Comment by aschulm** [comment]
Apparently I was due for a Chrome update. Updated to 52.0.2743.116 and now it works.
