### ISSUE TITLE
Failed bisects keep state in datastore as 'COMPLETED'.

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2714]
One big blocker for getting a simple dashboard of bisect state up and running is that the `try_job.TryJob` object does not properly keep its status as `failed` when a try job fails. I am pretty sure the [code to do that](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/try_job.py#L138) runs, but it seems to be getting overwritten to `completed` somewhere after. Also would be good to track `cancelled` as well.

I hit this when running [these scripts](https://docs.google.com/document/d/15MHxbrr-qpPSCjeqQjEcUBa2AxcXgoXaYuVQ2dGhc1s/edit#) which are not close to production quality code, but give what I hope are some good pointers for where to poke at in writing a useful dashboard.

**Comment by simonhatch** [comment]
Obsolete with Pinpoint.
