### ISSUE TITLE
Rename ValueSet to HistogramSet

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2717]
We've started using MRE more heavily in the context of the metrics framework as part of the effort to simplify the value system. As part of this, we are threading MreResults through a stack that was originally designed to work with ValueSets. We want to turn ValueSet into a subclass of MreResult (and likely rename it MetricResult in the process) to reduce the amount of somersaulting we have to do to make this work properly.

**Comment by benshayden** [comment]
+1 to MetricResult, where |pairs| maps from uuid to Histogram (formerly Value).

Consequently rename value-set-{view,table} to metric-result-{view,table}.

**Comment by benshayden** [comment]
MetricResult can't be a subclass of MreResult. Let's just rename ValueSet without changing the inheritance.

Consequently rename value-set-{view,table} to metric-result-{view,table}.

**Comment by eakuefner** [comment]
This is done.
