### ISSUE TITLE
Custom value set view functionality should be deleted

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2718]
In the process of threading MreResult through various parts of the metric stack (see #2717), we've had to modify ValueSetTable to temporarily support MreResults in addition to ValueSets, and this has broken the (already broken, but now more broken) sample custom value set view.

We should consider either:

1. removing custom value set view support until it's sufficiently motivated, or
2. making it a behavior.

@benshayden

**Comment by benshayden** [comment]
YAGNI argues for option 1.

**Comment by eakuefner** [comment]
It does. I'm happy to go for that.
