### ISSUE TITLE
Making any Python changes in catapult_base causes a bunch of lint spew

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2726]
If I try to make any Python change in catapult_base, the presubmit fails with a bunch of Pylint warnings in GYP code. It seems like there is some issue where we are being overzealous about which extra paths we are adding in catapult_base/PRESUBMIT.py.

@anniesullie @nedn @Apeliotes

**Comment by eakuefner** [comment]
Anyone have any thoughts on this? It's preventing progress on https://codereview.chromium.org/1887323002

**Comment by anniesullie** [comment]
Can you link the errors? Which patchset?

**Comment by eakuefner** [comment]
Latest patchset. Here's a gist of the errors: https://gist.github.com/eakuefner/0a4673c06774b00d4ab1fd8173d8019d

I verified that it happens because of Python changes in catapult_base (any Python changes, even not the ones I've made in that CL), and not because of Python changes in catapult_build.

**Comment by eakuefner** [comment]
Solved it by running the presubmit with -vvv to turn on debug output, which indicated that it's trying to lint the node_modules, some of which have gyp code in them. So we just need to blacklist the node_modules and bin dirs in PRESUBMIT.py. Sigh.
