### ISSUE TITLE
Wrong way to access events in EventSet

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#2727]
We are using EventSet as an Array-like object [here](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/analysis/analysis_sub_view.html#L166) and [here](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/analysis/analysis_sub_view.html#L181), which will only return `undefined`, instead, we should use `for (var event of events)` to access event in EventSet since it's iterable.

cc @natduca @fmeawad

**Comment by fmeawad** [comment]
I think things were changed in https://codereview.chromium.org/2283953002.

**Comment by lpy** [comment]
refer to #2314

**Comment by lpy** [comment]
This is fixed.
