### ISSUE TITLE
d is not defined when opening loading metric in metric side panel

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2729]
https://console.developers.google.com/m/cloudstorage/b/chrome-telemetry-output/o/trace-file-id_0-2016-08-26_19-38-12-3819.html

**Comment by nedn** [comment]
I have a quick fix for my ct telemetry job but can you folks add unittest coverage?
@benshayden @eakuefner

**Comment by eakuefner** [comment]
Shown above, @nedn fixed the bug and I tested it. Closing.
