### ISSUE TITLE
Y-axis scale for power sometimes too large in Telemetry BattOr traces

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2730]
Looking at load:games:bubbles on the Android bot, it looks like the y-axis scale for power is sometimes so large that it basically makes all power data look like a flat line, making the power tracing far less useful.

@alex319, would you be willing to look into this?

/cc @aschulm @randalnephew

**Comment by zeptonaut** [comment]
(Adding a comment to send a notification to myself so that I can snooze this...)

**Comment by Alex319** [comment]
The problem wasn't that the Y axis was too large; it was that the data was not getting into the chart because it was looking for "power" field, when this field had been changed to "powerInW". CL submitted to fix https://codereview.chromium.org/2293893003
