### ISSUE TITLE
Move from "per frame" power metrics to frameless power metrics

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2734]
Right now, we're emitting several summary statistics for our TBMv2 metric:

- energy_consumed_per_frame_avg
- energy_consumed_per_frame_count
- energy_consumed_per_frame_max
- energy_consumed_per_frame_min
- energy_consumed_per_frame_std
- energy_consumed_per_frame_sum

Of these metrics, the only one that we actually care about regressing is energy_consumed_per_frame_avg. Given that, we should stop reporting all other summary statistics.

/cc @randalnephew @Alex319 @aschulm

**Comment by aschulm** [comment]
That's not entirely correct. We want two metrics, average power and total energy. As far as I understand, total energy is the same thing as "energy_consumed_per_frame_sum" but we don't have anything computing average power yet.

**Comment by zeptonaut** [comment]
Good point: I'll leave sum in for now.

**Comment by aschulm** [comment]
Can you change the name. Also the way it is computed may be based off of computing the energy per frame which would be a problem if we are getting rid of energy per frame.

**Comment by zeptonaut** [comment]
Changing the scope of this, as suggested by Aaron. Given that we've decided that we're not going to use the frame as the basic denominator of power metrics, we should instead kill the existing metrics in favor of two new metrics:

- energy_per_second_avg
- energy_total

We can relabel all old energy_consumed_per_frame_sum datapoints to be energy_total datapoints. However, we don't have any old historical data available for our new energy_per_second_avg metric, which will be sucky. @nedn, if a new metric that we're writing can be applied to old Telemetry traces, is there any way to backfill data points for a new metric?

**Comment by nedn** [comment]
@zeptonaut we currently don't have any way to backfill data points.

**Comment by aschulm** [comment]
If there is convention to put the units in the name I would do that. Also, "energy_per_second_avg" is confusing . I think we are just going to have to teach people that energy and power are different things. Therefore I suggest we do:

- power_avg_w
- energy_j

The only thing this doesn't capture is how long the power trace is. If it's longer for one benchmark run vs. another it will explain why there may be an apparent regression in energy_j. Maybe for that we do:

- power_trace_sec

I'm no good at naming this stuff so maybe @nedn or @anniesullie should double check to make sure outsiders will understand these names.

**Comment by aschulm** [comment]
Just wanted to check in on the status of this I think this change + making sure the period of time that these metrics are being captured is the same across runs (CC @Alex319, I think this was implemented in #2673) are the main two issues that we need to tackle to make it easy for users to understand the power data, and to lower the noise between runs.

**Comment by zeptonaut** [comment]
(Assigning this @Alex319, who's actually working on it)

**Comment by zeptonaut** [comment]
Actually, going to close this altogether: I think that, for the most part, this has been implemented, and the rest of the work would be better of being split into smaller bugs anyhow.
