### ISSUE TITLE
Tracing Dev Server Tests Canary  failing on all 3 desktop platforms

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2735]
Disabling CL: https://codereview.chromium.org/2285183004

**Comment by eakuefner** [comment]
Fixed in https://codereview.chromium.org/2288943002/ which will land once the CQ (not our CQ, but CQ the service) is fixed. P0 -> P1.

**Comment by nedn** [comment]
You meant https://codereview.chromium.org/2288423002/?

**Comment by eakuefner** [comment]
Yes, and it's landed, so closing.
