### ISSUE TITLE
Create tbm/ from value/ and the metric_runner component of metrics/

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2736]
In https://docs.google.com/document/d/1aAB-d52E2y28BqADqokKhq29KhXk_IhAiXS86fztOko/edit I described a need for a clearer layering relationship between metrics/ and the metric_runner stuff; as the Value system is being drastically simplified we are realizing that a sane structure for this whole picture looks like: metrics -> tbm -> mre. Especially now that MRE has been moved into tracing, it makes good sense to form a tbm module containing all the metric infrastructure pieces (what will have been values, metric_runner, all the UI, etc.) built on the foundation of MRE, and on top of which metrics will be built.

@benshayden

**Comment by benshayden** [comment]
"what will have been Values" = Histogram + diagnostics/ + ui/ + MetricResult

Unit, Scalar, GenericTable will move back to base/ since metrics shouldn't have to think about them.

**Comment by benshayden** [comment]
Update: GenericTable is dead.

Acronyms like "tbm" are not great names. What should we rename it to instead?

**Comment by eakuefner** [comment]
Archiving; there is a doc about rearranging Catapult.
