### ISSUE TITLE
Invalid ProtoExpectation when running battor.power_cases on perf waterfall

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2740]
[Link to STDIO (Google internal).](https://build.chromium.org/p/chromium.perf/builders/Win%2010%20High-DPI%20Perf%20%281%29/builds/48/steps/battor.power_cases/logs/stdio)

I got a message to file this bug in the STDIO of the benchmark run, in a line that looked like:

```
Error: Invalid ProtoExpectation: ignored(9315 9315 undefined) File a bug with this trace!
Error: Invalid ProtoExpectation: ignored(9315 9315 undefined) File a bug with this trace!
```

[Here's a link](https://github.com/catapult-project/catapult/files/445034/webkit.zip) to the offending trace.

**Comment by zeptonaut** [comment]
/bump to make sure you saw this

**Comment by benshayden** [comment]
Sorry, yes, I did see this. Is this breaking or blocking anything?

**Comment by zeptonaut** [comment]
Nope. Just thought I'd let you know about it :-)

**Comment by benshayden** [comment]
Sorry, too low priority. Please open a new bug if this type of issue causes a problem.
