### ISSUE TITLE
Tab view doesn't update tab labels upon setting selectedSubView

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2754]
Add the following code to tracing/ui/base/tab_view_test.html:

``` javascript
test('instantiate_twoTabsSwitch', function() {
  var tabView = document.createElement('tr-ui-b-tab-view');
  tabView.label = '3 items selected.';
  tabView.addSubView(createPowerSampleSubView());
  tabView.addSubView(createAlertSubView());
  this.addHTMLOutput(tabView);
  tr.b.requestAnimationFrame(function() {
    tabView.selectedSubView = tabView.tabs[1];
  });
});
```

And run the test in Chrome: [http://localhost:8003/tracing/tests.html?testFilterString=instantiate_twoTabsSwitch&testSuiteName=tracing.ui.base.tab_view_test](http://localhost:8003/tracing/tests.html?testFilterString=instantiate_twoTabsSwitch&testSuiteName=tracing.ui.base.tab_view_test)

**Expected output:**

![screenshot from 2016-09-01 17 42 02](https://cloud.githubusercontent.com/assets/2546601/18175971/71c12bce-706b-11e6-8480-361d1f1641f2.png)

**Actual output:**
![screenshot from 2016-09-01 17 42 17](https://cloud.githubusercontent.com/assets/2546601/18175974/7907918e-706b-11e6-8329-040308154bbd.png)

Even though the "Alerts" tab is displayed, the "Power samples" tab label is highlighted.

I suspect this has something to do with Polymer data bindings not firing upon the change. If I remove the <tt>tr.b.requestAnimationFrame</tt>, everything works fine:

``` javascript
test('instantiate_twoTabsSwitch', function() {
  var tabView = document.createElement('tr-ui-b-tab-view');
  tabView.label = '3 items selected.';
  tabView.addSubView(createPowerSampleSubView());
  tabView.addSubView(createAlertSubView());
  this.addHTMLOutput(tabView);
  tabView.selectedSubView = tabView.tabs[1];
});
```

@zeptonaut, @Apeliotes

**Comment by zeptonaut** [comment]
Assigning this to me, but can't make any great guarantees about when I'll be able to get to it. I'll make a note to myself to investigate this in a week (once perf has settled down).

**Comment by chromy** [comment]
This seems to been fixed, when I patch in the test it looks like the expected output now.
I uploaded a [patch](https://codereview.chromium.org/2690113013/) to add Petr's test so we don't regress this in future.
