### ISSUE TITLE
Tab view ends up with no selected tab labels after changing tabs

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2755]
Add the following code to tracing/ui/base/tab_view_test.html:

``` javascript
test('instantiate_twoTabsSwitchAndChange', function() {
  var tabView = document.createElement('tr-ui-b-tab-view');
  var tab1 = createPowerSampleSubView();
  var tab2 = createAlertSubView();
  this.addHTMLOutput(tabView);
  tabView.addSubView(tab1);
  tabView.addSubView(tab2);
  tr.b.requestAnimationFrame(function() {
    // Click on the "Alerts tab".
    tabView.$.tabs.querySelectorAll('label')[2].click();  // Work around #2754.

    // Click on the "Power samples" tab.
    tabView.$.tabs.querySelectorAll('label')[1].click();  // Work around #2754.

    tabView.clearSubViews();
    tabView.addSubView(createPowerSampleSubView());
  });
});
```

And run the test in Chrome: [http://localhost:8003/tracing/tests.html?testFilterString=instantiate_twoTabsSwitchAndChange&testSuiteName=tracing.ui.base.tab_view_test](http://localhost:8003/tracing/tests.html?testFilterString=instantiate_twoTabsSwitchAndChange&testSuiteName=tracing.ui.base.tab_view_test)

**Expected output:**
![screenshot from 2016-09-01 17 58 05](https://cloud.githubusercontent.com/assets/2546601/18176479/af69611a-706d-11e6-831b-d61f7f4139d1.png)

**Actual output:**
![screenshot from 2016-09-01 17 58 19](https://cloud.githubusercontent.com/assets/2546601/18176484/b543cc1a-706d-11e6-9069-eade240fdae7.png)

Similarly to #2754, I suspect this has something to do with Polymer data bindings not firing upon the change.

@zeptonaut, @Apeliotes

**Comment by zeptonaut** [comment]
Agreed: these two look very similar.

**Comment by chromy** [comment]
This seems to been fixed, when I patch in the test it looks like the expected output now.
I uploaded a [patch](https://codereview.chromium.org/2690113013/) to add Petr's test so we don't regress this in future.
