### ISSUE TITLE
Is it useful to segregate system_health/ metrics? blink/? v8/?

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2761]
Currently, there's only 1 blink/ metric, only 2 v8/ metrics not counting the unnecessary meta-metric, and only 2 metrics in metrics/ directly. There are currently 9 system_health/ metrics, not counting the unnecessary meta-metric. We have plans to move the metric_runner infra stuff from metrics/ to its own directory.

Directories of metrics made sense in TBM1 where there were significantly more metrics, but now it just requires more typing and clicking to see everything or find a specific metric. The total number of metrics is currently far from being large enough that directory structure is required, I think, and IIUC we plan to keep it that way.

Is there any definite reason not to place all metrics directly in metrics/ in order to reduce typing and clicking? Or are there definite plans for significantly more blink or v8 or non-SH metrics that ought to be segregated from SH metrics for some particular reason?

@eakuefner @nedn @natduca

**Comment by nedn** [comment]
The system_health/ is there to make it easy for people who ask "which are the most important metrics" in Chrome. Another way is to write good document to keep track of it, but I trust the code structure more than documentation.

For the rest of metrics, flat structure is fine.

**Comment by eakuefner** [comment]
+1 to eliminating metric subdirectories other than system_health, and to everything said above. I think originally we said that there were two possible plans:

1. Put system_health metrics in the root directory and other metrics in their own subdirectories, or
2. Put system_health metrics in system_health and other metrics in the root directory.

I agree with @benshayden that having the metric_runner stuff in the metrics dir was what put us into this weird intermediate state, and also with @nedn that the primary goal of the separation is to make it easy to answer the "which metrics are the most important" question.

**Comment by benshayden** [comment]
Archiving
