### ISSUE TITLE
a recent trace shows no slices (but it has events)

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2763]
I was trying to open the trace attached to crbug.com/644251 .
traceviewer doesn't show anything to me. It shows a list of processes but I don't see any slices.
I confirm that I see slices in the JSON. so something is there but gets lost in the process of being displayed.
This happens loading the trace on OSX both in M52 and in canary 54.0.2827.0.

Here's what I get: the void
<img width="1319" alt="screen shot 2016-09-06 at 2 28 47 pm" src="https://cloud.githubusercontent.com/assets/7137473/18275315/41e0728a-743e-11e6-8977-80bae697a79c.png">

**Comment by primiano** [comment]
@petrcermak @zeptonaut

**Comment by pasko** [comment]
FWIW, the trace opens fine for me in M53

**Comment by zeptonaut** [comment]
@Alex319, would you be willing to look into this?

**Comment by petrcermak** [comment]
Sounds like #2416. Is it a huge trace? Could you try collapsing some of the processes?

**Comment by primiano** [comment]
Uh if I collapse the browser process magically the slices appear.
Ok this is definitely a dupe of #2416
