### ISSUE TITLE
Show not-logged-in warning

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#2764]
If you access a report with data that requires a login it happens rather frequently that nothing is displayed due to not being logged in.
The V8 team had several performance regressions that were not properly addressed due to people accidentally not being logged in.

Could we show an ugly error message when trying to display a graph / report that requires a user to be logged in?

**Comment by anniesullie** [comment]
I think there are a couple places this warning should show and we missed one--can you post a link to the page you aren't seeing a warning on?

**Comment by camillobruni** [comment]
I was thinking mainly about something like https://chromeperf.appspot.com/report?https://chromeperf.appspot.com/report?sid=1be638d9f575cfb937fab7d6ea8c133704cf8b2b1a5929a722ac21baf7cec8ad

**Comment by simonhatch** [comment]
Got the big red warnings up again.
