### ISSUE TITLE
clock_sync_latency_metric no longer being reported

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2770]
It looks like [the clock sync latency metric](https://chromeperf.appspot.com/report?sid=e2c3f601cd3972d2b767a9ad7b27c87fb85973084ea1c59e7801f8d76fe61e05) is no longer being reported on any platform. I wonder if this might have to do with one of @benshayden's CLs submitted around the same period ([link](https://github.com/catapult-project/catapult/commits/6c34841e91eac95aa405ea8e05efd63c28492af1/tracing/tracing/metrics/system_health/clock_sync_latency_metric.html)).

@Alex319, would you mind investigating?

**Comment by benshayden** [comment]
Add "_avg" to the subtest: clock_sync_latency_battor_avg

**Comment by Alex319** [comment]
I just checked, and adding "_avg_"to the subtest does in fact make the metric show up in the dashboard. It looks like this is because @benshayden 's change changed the value in the metric from a single value to a histogram, so you need to take the "average" (of the one sample in the set)

**Comment by benshayden** [comment]
Please re-open if something needs to be done here.

**Comment by zeptonaut** [comment]
Got it. Thanks @benshayden.
