### ISSUE TITLE
Perf Dashboard: Cannot assign hundreds of alerts to a single existing crbug

### ISSUE THREAD

**Issue by miu-at-google** [catapult-project/catapult#2771]
Chrome version: 52.0.2743.82 (Linux)
URL: https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:
I am perf sheriff'ing. I am confident that HUNDREDS of alerts in the Perf Dashboard are being caused by the same single change. I wish to assign all of them to a single crbug, but the UI won't allow me to do this. It just chokes and becomes unresponsive, and seems to only gradually assign only a few with each of my attempts.

Please fix this scaling issue ASAP, as it's preventing me from clearing the alerts to find other alerts that need to be addressed!

**Comment by miu-at-google** [comment]
I also cannot simply "ignore" these alerts, either. This is now a P0 issue, since I cannot effectively do any more perf regression sheriffing.

**Comment by miu-at-google** [comment]
Using "ignore" seems marginally faster than "existing bug," so I'm trying to clear low-alert-count line items as best I can that way. Very slow-going though...

**Comment by miu-at-google** [comment]
Also, I'm occasionally getting "500" error messages.

**Comment by anniesullie** [comment]
I'm looking into this now. @dave-2 @Apeliotes @eakuefner

**Comment by anniesullie** [comment]
Trace of a slow /associate_alerts run: https://pantheon.corp.google.com/traces/details/fd1a6fd58430a73d8e6ed59f4e311451?project=chromeperf#TIMELINE

**Comment by dave-2** [comment]
@Apeliotes and I think that this particular query is taking a long time. It might not account for the entire slowness, but it showed in 4/4 stack traces for the DeadlineExceededError and is a good place to start.

`grouped_alerts = alert_class.query(alert_class.group == group.key).fetch()`
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/alert.py#L81

**Comment by dave-2** [comment]
@Apeliotes is going to look at moving the query logic out of _pre_put_hook and into the caller in associate_alerts. It has more knowledge about the alert groups, and can do the query once per group, rather than once per alert.

**Comment by anniesullie** [comment]
@Apeliotes has a WIP CL here: https://codereview.chromium.org/2355553002/

**Comment by simonhatch** [comment]
Picked this up yesterday, WIP: https://codereview.chromium.org/2650683007/

StackDriver seems to suggest this implementation takes 1300 ms vs 9950 ms (old) for 53 alerts.

**Comment by simonhatch** [comment]
Going to mark this as fixed since we landed some optimizations towards this. Reopen if still an issue.
