### ISSUE TITLE
py_vulcanize breaks paper and iron components

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2772]
It's not possible to use paper or iron components in tracing right now, seemingly due to py_vulcanize reordering stuff.

Two examples:

1. iron-iconset-svg (included by iron-icon) uses an `attached` method to set `display` to `none` imperatively: https://github.com/PolymerElements/iron-iconset-svg/blob/master/iron-iconset-svg.html#L74
2. paper-card uses a `style include` tag that doesn't seem to resolve properly: https://github.com/PolymerElements/paper-card/blob/master/paper-card.html#L64

@natduca @benshayden

**Comment by natduca** [comment]
Is this just https://github.com/catapult-project/catapult/issues/2698 ?

**Comment by eakuefner** [comment]
Yes, I'll dupe this one onto that one.
