### ISSUE TITLE
Dashboard sort "Delta%" alphabetically instead of numerically?

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2774]
Click sort on "Delta%" column in https://chromeperf.appspot.com/group_report?bug_id=644403 seems to sort the rows alphabetically.

**Comment by anniesullie** [comment]
This is a big problem for group_report?rev=, when there are positive and negative changes, they get intermixed.

**Comment by jessimb** [comment]
I want to note that I fixed the sorting issue, not the mixing results problem, so I have opened a new bug to address that.
