### ISSUE TITLE
iron-iconset is messing up about:tracing view

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#2775]
![image](https://cloud.githubusercontent.com/assets/412396/18317351/b16368c6-74d2-11e6-8da4-ec74c9a6e5b9.png)

**Comment by natduca** [comment]
Calling @eakuefner @benshayden

**Comment by eakuefner** [comment]
Fix landed yesterday: https://codereview.chromium.org/2310823004/ -- hopefully it makes it to Canary today.

**Comment by chromy** [comment]
I guess this is fixed now :)
