### ISSUE TITLE
Always use --pageset-repeat 1 for each bisect iteration?

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2787]
The current 24 hours limit is proving limiting to bisect some benchmarks, particularly for memory.top_10_mobile (e.g. [crbug.com/631496](https://bugs.chromium.org/p/chromium/issues/detail?id=631496#c37)).

This benchmark has a default pageset_repeat of 5 (with independent runs, i.e. ShouldTearDownStateAfterEachStorySetRun is True), since that allows to smooth out some of the noise in our continuous tracking and reporting for system health plan. However, I think there is no need to do the 5 repeats when trying to bisect; since the bisect logic itself will _also_ try to do several runs of the benchmark to gain confidence in the measurements.

My proposal would then be to either:

1. Always pass --pageset-repeat 1 on each bisect iteration, or
2. Pass --pageset-repeat 1 only when ShouldTearDownStateAfterEachStorySetRun is True (since runs are independent, and we know any pageset repeat > 1 in the benchmark was just intended to de-noise).

The problem is of course with the few long running benchmarks where ShouldTearDownStateAfterEachStorySetRun is set to false False. In such case (1) may not reproduce regressions, and (2) may not finish in time and be affected by the 24 hours limit (like it does today). Anyway, we essentially give up on bisectability when setting ShouldTearDownStateAfterEachStorySetRun to false, so I think either trade-off would be acceptable.

@anniesullie @ro-berto @nedn @primiano @picksi any thoughts?

**Comment by anniesullie** [comment]
@nedn if a benchmark is independent, there should be no problem with this, right?

**Comment by nedn** [comment]
Yes.  But I am surprise to hear that there is double repeat mechanism here. How does bisect do repeating run if without using --pageset-repeat?

**Comment by nedn** [comment]
I think the total repeat run to be used by bisect should be no less than the one used in regular run. Also we should know the timing breakdown of that 24 hours run. Is that because of the build time? Is that because we didn't bisect for single story?

**Comment by perezju** [comment]
Skimming through the build log most of the time seems to be spent actually testing (30 mins each "run"), and not that much waiting for builds.

![bisect_log](https://cloud.githubusercontent.com/assets/16922344/18388345/33ef9040-7699-11e6-977e-1fb9de2d053a.png)

Also this particular benchmark does *not* support story filter as currently implemented. Because, it needs to keep the browser open for the whole time so it doesn't get killed during the "background" measurements (that's something I could also try to fix, but that is an orthogonal issue).

**Comment by nedn** [comment]
If each run takes 30 min, 24 hour mean roughly there are 48 runs? Why does bisecting require so many runs?

**Comment by anniesullie** [comment]
Backing up, didn't we encode the memory pageset repeat in the benchmark because we got different results in later iterations? Is this solved by independence?

**Comment by perezju** [comment]
Re @nedn: Yes that particular bisect did 32 runs; It tested 7 different revisions and did 5 runs on each revision (sometimes just 3, don't know how it chooses how many). The rest of the time it was probably waiting for builds.

Re @anniesullie: Hmm, that's true. The page set repeat got encoded in the benchmark from the time when we didn't have independence between different iterations (but now we do), and to have it run the same number of times both downstream and upstream (where it always defaults to 1).

We could return to run with explicit --pageset-repeat 5 downstream, but I got the idea that was sort of frown upon?

**Comment by nedn** [comment]
I prefer that we keep a consistent number of pageset-repeat everywhere as the knowledge of how many repeat is enough to make this benchmark good enough should be encoded in the benchmark config itself. 
I think the bug here is bisect was using it own mechanism of repeating runs & not relying on pageset-repeat command.

**Comment by perezju** [comment]
@dave-2 I think this is a very simple change we could do to unblock many bisects that fail today due to the 24 hours limit.

**Comment by perezju** [comment]
This is fixed now. (Just got a bisect result where the flag was passed and worked as expected.)
