### ISSUE TITLE
Feature proposal: Delta sparkline

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2788]
**<tt>\<tr-v-ui-scalar-span\></tt>** has supported sparklines for quite a while now (<tt>tracing.ui.analysis.multi_sample_sub_view_test.instantiate_flat</tt> test below):

![screenshot from 2016-09-09 12 57 32](https://cloud.githubusercontent.com/assets/2546601/18386173/0df363fa-768d-11e6-96cc-656ae6c806e4.png)

I would like to extend this feature to __deltas and negative values__ in general (context: #2751). Here are several options that I came up with:

![untitled drawing 1](https://cloud.githubusercontent.com/assets/2546601/18386215/6495502e-768d-11e6-859e-d2d60849addc.png)

Note that the first two options _don't_ work well when negative and positive values are _not_ represented using _different_ colors:

![untitled drawing 2](https://cloud.githubusercontent.com/assets/2546601/18386259/a40ced2a-768d-11e6-857d-0e8e1992d783.png)

My personal favorite is _Option 4_ because it naturally looks like a bar chart with an axis in the middle.

@natduca, @zeptonaut, @benshayden, @eakuefner: Please let me know your thoughts.

**Comment by zeptonaut** [comment]
Great mock-ups Petr! Makes it super easy to tell exactly what you're talking about. My vote is also for Option 4.

**Comment by benshayden** [comment]
+1 for option 4 with red and green backgrounds.

Would it be possible to make the green slightly lighter than the red for color-blind users?

I noticed that the direction of the sparkline indicates the sign of the delta, not left=bad, right=good. I think that's correct, I just wanted to note it.

**Comment by eakuefner** [comment]
+1 to everything @benshayden said.

**Comment by petrcermak** [comment]
Thanks for all the comments. Here's the final design:

![delta sparkline 2 3](https://cloud.githubusercontent.com/assets/2546601/18435789/16fe1c8a-78ed-11e6-9081-2eb168bc5209.png)

Key things:

* Direction: left=negative, right=positive
* Color: red=bad, green=good, blue=not delta or no improvement direction
* By default, the vertical axis (going through 0.0 MiB) shifts left/right to make sure that the _min_ value, the _max_ value and _zero_ are in the visible range. In other words, the chart range is _[min(spans.min, 0), max(spans.max, 0)]_. No sparkline is displayed when _spans.min == spans.max == 0_.

@benshayden: I'll try to make the green a little lighter :wink:

**Comment by petrcermak** [comment]
Implementation pending (https://codereview.chromium.org/2336703002/):

![screenshot from 2016-09-12 19 09 32](https://cloud.githubusercontent.com/assets/2546601/18447188/712abd14-791d-11e6-934b-6e55e197bee1.png)

**Comment by benshayden** [comment]
If the zero could be anywhere in the span, and the span is very wide, then it might be difficult to find the sparkline. If the zero were always in the center of the span, then, yes, it might compress the range and make fine gradations less visible, but it would always be easy to find the sparkline. (Maybe a bit of clever math could find a best-of-both-worlds where the sparkline drifts towards the center as the width of the span grows?)

**Comment by petrcermak** [comment]
There will typically be several vertically aligned scalar spans, whose sparklines will (assuming the correct context range) together span the whole width. Therefore, I don't think that finding the sparkline would be a problem:

![screenshot from 2016-09-13 13 52 11](https://cloud.githubusercontent.com/assets/2546601/18474295/4c19852c-79b9-11e6-8aad-321968f02541.png)

However, if you think that it's a problem, then I think that the following logic would work:

```javascript
function calculateSparklineRange(contextRange) {
  if (contextRange.min >= 0) {
    // All values are non-negative.
    return tr.b.Range.fromExplicitRange(0, contextRange.max);
  } else if (contextRange.max < 0) {
    // All values are non-positive.
    return tr.b.Range.fromExplicitRange(contextRange.min, 0);
  } else {
    // There are both negative and positive values.
    var absoluteMax = Math.max(-contextRange.min, contextRange.max);
    return tr.b.Range.fromExplicitRange(-absoluteMax, absoluteMax);
  }
}
```

Let me know what you think.

**Comment by petrcermak** [comment]
__Done__ :white_check_mark:
