### ISSUE TITLE
Display weird values in breakdown-span

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2793]
Metrics may add negative, zero, infinity, or NaN values to Breakdowns. Breakdown-span should display those outside of its BarChart.

**Comment by nedn** [comment]
Can we fix this soon-ish to unblock landing https://codereview.chromium.org/2324973002

**Comment by benshayden** [comment]
I'll fix it tonight, but why does it need to block your cl?

**Comment by nedn** [comment]
Without the fix, the breakdown of TTI will be broken when TTI is +inf. But you may be right that it's not that big of an issue to be a blocker.

**Comment by benshayden** [comment]
JSON.stringify(NaN) === 'null' :-)
