### ISSUE TITLE
Can we shrink value-set-json?

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2794]
Some metrics can produce a staggering amount of data, which value-set-json dutifully preserves and replicates. This can get so big that results2.html can either take a long time to display it, or fail entirely.

Should we deduplicate IterationInfo?

Should we be smarter about capping sample diagnostics and sampleValues?

Should we manually serialize floats to truncate insignificant digits?

Let's pretty-print a large value-set-json and try to find features that take too much space.

**Comment by eakuefner** [comment]
Pretty printing would help, but I also think simply analyzing character counts would help us find culprits. I'm going to try to produce a tree that shows character counts by level of the histogram dict.

**Comment by benshayden** [comment]
[Chunking the ValueSet](https://codereview.chromium.org/2353723003) attacks the same problem but doesn't actually shrink the histograms, it's just related.

As a point of clarification, ValueSet only contains Histograms, but those can contain Diagnostics, so when I said that Histograms are fat, I didn't mean to say that Diagnostics are definitely not the problem, but I agree that the distinction between non-Diagnostic parts of Histograms and Diagnostics is a useful one here. So I'm not sure that Diagnostics are not the problem, it would be useful to investigate all of the json.

**Comment by benshayden** [comment]
Here's some kind of an idea. >:-}

value-set-table really only needs Histogram's names, description, IterationInfo, and average in order to display the default view. It only needs the full HistogramBins and statistics and Diagnostics when the user clicks on a cell, and then only for that Histogram.

Put just the names, IterationInfos, and averages in an "index" json div tag (or chunked to multiple tags if necessary). Load these stripped-down Histograms as HistogramRefs ala EventRef/ValueRef. Put each full Histogram in its own json div tag whose id contains the uuid, and only load it onclick. Define a HistogramLoader interface to allow value-set-table to say "um, i need to load the full Histogram for this HistogramRef", and results2_template.html to implement the interface to say "oh, here you go."

The wrinkle is setting a reference column. Computing the emoji requires the full Histograms. IIUC, grown-up webdevs would set visibility:hidden on the emoji, use requestIdleCallback to load full Histograms in 50ms chunks, and show the emoji when they're available.

This might take a few days to implement properly, so maybe low priority, though it sounds like fun. :-)

**Comment by anniesullie** [comment]
I'd really love to see some solid data about what takes up so much space! Ethan, will the tree of character counts get us there?

**Comment by benshayden** [comment]
I took a quick look at a pretty-printed dict of an empty histogram. These numbers aren't quite as hard-and-fast as if a script were to crunch through hundreds of real-world histograms with diagnostics, but they provide a good basic picture of the low-hanging fruit.

In an empty histogram with 30 bins that takes 2650 bytes of json, centralBins takes 960 bytes to contain zero information.
`"centralBins":[{"count":0,"diagnosticMaps":[]},{"count":0,"diagnosticMaps":[]},`...
That is pure bloat that can be cut entirely. For empty bins in non-empty histograms, centralBins can elide `"count": 0` and `"diagnosticMaps": []`. Same goes for the underflow and overflow bins. Sparse histograms can use a dictionary instead of an array and serialize only the non-empty bins keyed to their indices. The string keys could be single characters `"c"` or small numbers `0`-`99` (ala protocol buffers) instead of `"count"`, `"diagnosticMaps"`, `"summaryOptions"`, etc.
Default values of summaryOptions need not be serialized.
Essentially, if restoring a serialized field would have no effect on a pristine Histogram created during Histogram.fromDict(), then that field should not be serialized.

The binBoundaries array of 30 floats takes 572 bytes. Trimming floats could more than halve that. We could also make HistogramBinBoundaries remember how it was built. With an enum like EXPONENTIAL=0, LINEAR=1, that binBoundaries array could be shortened from a couple hundred bytes to `[[0,0.001,30000]]` since addExponentialBins and addLinearBins are deterministic. We could elide the serialized binBoundaries entirely if it was taken from the DEFAULT_BOUNDARIES_FOR_UNIT, but we probably shouldn't in case that map of constants is changed.

IterationInfo takes 384 bytes per Histogram. Using single-character keys could nearly halve that.

RunningStatistics takes 154 bytes. Floats can be trimmed, keys could be substituted for short number tags ala protocol buffer.

`"guid":"877f5c3a-33c4-4fd4-a94d-72f831e3e794",` is 47 bytes but `0:"ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ"` is only 20. UUID4s are 128 bits, each character could contain 8 of those bits, though I'm not entirely sure how happy the various parsers would be to find control characters in json strings. Base64 would use 6 bits per character so the entire guid entry in the histogram dict would be 26 or 27 bytes serialized.

That's the bottom of the barrel. Any questions?

**Comment by benshayden** [comment]
I think is done enough for now, but please re-open if you have any further questions.
