### ISSUE TITLE
Telemetry should suffix outputted traces with date

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2799]
I have been running benchmarks locally to collect traces, and something I noticed is that the current scheme does not accommodate running a benchmark multiple times, thus the traces from my first run got overwritten by the second run. We should suffix the outputted trace filenames with the date so that this doesn't happen.

Apropos of this, it's endlessly confusing to people that --output-format=json is responsible for outputting traces; instead we should add an option like --output-traces to mitigate the confusion here.

@nedn

**Comment by nedn** [comment]
I recall the plan is to have the --out-dir option that telemetry gonna dump all the artifacts into that directory.

**Comment by nedn** [comment]
Topic: https://github.com/catapult-project/catapult/issues/2483#issuecomment-233019161

**Comment by eakuefner** [comment]
Makes sense. As discussed in that bug, we can create the --data-dir flag and start by having traces dumped to that dir. I'll create a separate bug for the first phase of that plan, and leave this bug for suffixing the output html files.

**Comment by eakuefner** [comment]
This is done.
