### ISSUE TITLE
replace multi event details table with histogram

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#2800]
It will look like this

<img width="929" alt="screen shot 2016-09-14 at 12 53 42 pm" src="https://cloud.githubusercontent.com/assets/1453861/18527630/654d6952-7a7a-11e6-916f-c8573374dd2b.png">

**Comment by benshayden** [comment]
Can you add some padding around the radio buttons?

Would it be useful to have multiple histograms? Either five separate histograms, or 3 histograms, 2 of which have two radio buttons? That would reduce the number of clicks required, but it might overwhelm the user with data. You and Fadi know how this will be used better than I do, so it's up to you.

It looks like you're setting the maximum bin boundary to the maximum of the range of the samples, which can waste a lot of space for long-tailed distributions such as this. Instead of taking the maximum, do you want to take the 95th percentile, so that 5% of the samples end up in the overflow bin? See Statistics.percentile().

**Comment by lpy** [comment]
I use the minimum of the range of the samples as the left boundary, if I use Statistics.percentile() to decide the right boundary, then I will need to go through samples to find the minimum value. Any existing util function to help?

**Comment by benshayden** [comment]
You're trying to avoid iterating over all the samples twice just to compute the boundaries, then again to add them to the histogram, correct?

You can pass a callback |opt_func| to Statistics.percentile() that has a side-effect of computing the min:
var min = Number.MAX_VALUE;
var pctile95 = Statistics.percentile(events, 0.95, function(event) {
  var sample = event[fieldName];
  min = Math.min(min, sample);
  return sample;
});

**Comment by fmeawad** [comment]
@natduca

**Comment by fmeawad** [comment]
Can you also show us what happens when you brush/select the samples?

**Comment by lpy** [comment]
It looks like this.

<img width="609" alt="screen shot 2016-09-19 at 10 20 48 am" src="https://cloud.githubusercontent.com/assets/1453861/18641766/e7b03830-7e52-11e6-9ed7-abf96ef055ca.png">

**Comment by benshayden** [comment]
Oof, those floats look awful. We have an awesome Unit system that can format durations and timestamps nicely, and Generic diagnostics can't use it.
I can whip up a ScalarDiagnostic unless you want to do it.

I noticed you cropped out the statistics table on the right. If the statistics aren't useful for your use case, feel free to call customizeSummaryOptions({...}) on your histogram to turn them all off. See histogram.html for the argument.

**Comment by lpy** [comment]
@benshayden Thanks, I think having ScalarDiagnostic will be great, I agree those floats look awful. 
@fmeawad , do you think we need the long float?

**Comment by fmeawad** [comment]
I think 2 decimal points should be enough.

**Comment by benshayden** [comment]
The default TimeDisplayMode (ms) specifies minimumFractionDigits: 3. I imagine that's ok, but LMK if you really want a custom Unit or TimeDisplayMode :-)

**Comment by lpy** [comment]
3 looks good to me. Unless @fmeawad has a really strong will that we want 2.

**Comment by fmeawad** [comment]
3 sounds better, I thought we used 2 everywhere :)

**Comment by lpy** [comment]
Now looks like this:
<img width="719" alt="screen shot 2016-09-20 at 5 39 01 pm" src="https://cloud.githubusercontent.com/assets/1453861/18693758/2a8e6454-7f59-11e6-9e0b-e5f409252e94.png">

**Comment by fmeawad** [comment]
@natduca

**Comment by natduca** [comment]
Nice!

**Comment by lpy** [comment]
Done.

**Comment by lpy** [comment]
<img width="637" alt="screen shot 2016-09-28 at 12 45 22 pm" src="https://cloud.githubusercontent.com/assets/1453861/18929494/89f396be-8579-11e6-834b-1ae95930da3f.png">
