### ISSUE TITLE
Catapult CQ blocked on failure to clock sync on Mac

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2804]
This is currently block @lpy's CL here: https://codereview.chromium.org/2338913004

It looks like we're failing to clock sync between Telemetry and the Mac reference version of Chrome. It's very strange that this is only happening on Mac, which has the same reference build as Linux and Windows.

I'm going to start investigating.

/cc @nedn

**Comment by zeptonaut** [comment]
Syncing to the same revision that's listed as the diffbase for that tryjob (5148bd4b2be6fddb9fb33cae504afe76e113cfbd) and applying the patch, my test succeeds locally. I'm wondering if this is some sort of an infrastructure failure?

**Comment by nedn** [comment]
I suspect the Mac bot is stuck at the older version of catapult.

Halppp! @dave-2

**Comment by zeptonaut** [comment]
Just for completion, I ensured this worked with:

```
$ git checkout master
$ git pull
$ git checkout -b repro_branch
$ git reset --hard 5148bd
$ python telemetry/bin/run_tests --browser=reference --start-xvfb
```

**Comment by anniesullie** [comment]
@nedn, @zeptonaut: I think the best way to move forward here is to file a bug on crbug.com with all the details we can about why we think the Mac bot is stuck, and add label `Infra-Troopers` and Component `Infra>Client>Perf`. Can one of you do that and cc me and @dave-2?

**Comment by zeptonaut** [comment]
I'll take care of this, and link to the bug when it's done.

**Comment by zeptonaut** [comment]
(I'm going to try to run that CL through the CQ one more time before getting infra involved.)

**Comment by lpy** [comment]
Thanks Charlie!

**Comment by Apeliotes** [comment]
Update: I'm disabling testTBM2ForSmoke to help unblock the CQ for now. And infra is looking into things in crbug.com/647469

**Comment by zeptonaut** [comment]
So Ned has a fix for this that's currently up review: https://codereview.chromium.org/2342303002/

What's weird is how *simple* this fix is: version 2661, which we were using as the lower limit for "this version of Chrome has devtools clock sync available", turns out to not actually have it available (problem #1). Because of this, we were trying the devtools clock sync instead of the legacy clock sync and silently failing (problem #2). But why was this passing when @nedn and I tried it locally, but failing on the CQ? This part is a little unclear. Ned and I did notice a strange behavior, though: apparently there can't be two versions of Chrome (non-Canary) running at the same time, at least on Mac. I know I had Chrome 52.x running when I ran my Telemetry test yesterday, which means that Telemetry used that version rather than its own reference build (problem #3). It's strange: that shouldn't have had an effect though. My Chrome stable version on my Mac was actually the same as the reference build because I hadn't updated Chrome yet. We're not completely sure why it was passing locally, but we think it may have something to do with this.

What we haven't figured out yet: why was this okay on Linux and Windows? The only thing that we could think of was that maybe we have different builds for our reference version on Mac than we do for Linux and Windows. Ned added some logging that says the current Chrome version number when making the clock sync type decision, so hopefully we get an answer to this soon.

**Comment by nedn** [comment]
The revision number of Chrome ref on [Linux](https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Linux%20Tryserver/builds/4931/steps/Telemetry%20Tests%20with%20Stable%20Browser/logs/stdio) & [Win](https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/4778/steps/Telemetry%20Tests%20with%20Stable%20Browser/logs/stdio) are 2623, which is less than the current cut-off point, hence the backcompat clock sync code path is activated.

**Comment by nedn** [comment]
Should be fixed
