### ISSUE TITLE
Investigate impact of turning off memcache for TestMetadata and Row entities

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2807]
We use the NDB datastore, which has some caching properties on by default:
https://cloud.google.com/appengine/docs/python/ndb/cache

The in-context cache seems to me to be clearly a net win: everything will be in memory if it's accessed multiple times during the same request.

But the memcache doesn't seem to meet our usage pattern. Our most common endpoint is /add_points, which essentially updates each TestMetadata entity with new Row entities once every 30-360 minutes. Which means that at least this endpoint is essentially just thrashing memcache by just continually storing new entries. But I believe pretty much all of our endpoints have essentially random access patterns, where it's very difficult to predict which TestMetadata and Row entities will be accessed at a given point in time, and it's my understanding that if they are accessed by queries instead of ndb.get then the memcache isn't used.

Every time I look at a stackdriver trace of a long query, I see dozens or hundreds of memcache.Get and memcache.Delete lines, and although they are never the biggest bottleneck they consistently add up to seconds or more. I was poking at cleaning up some system health alerts in the interactive shell, and using context.set_memcache_policy to turn off memcache sped them up about 50% (the specific task was query for all TestMetadata which have the system health sheriff and call put on them).

I'm putting up a CL now to turn this off, and we'll use stackdriver to compare latency next week vs this week.

@eakuefner @Apeliotes @benshayden @dave-2

**Comment by anniesullie** [comment]
WIP in https://codereview.chromium.org/2349703002

**Comment by anniesullie** [comment]
I started investigating this, running a query to `fetch()` and `put_multi()` 10 `TestMetadata` entities on the [interactive shell](https://chromeperf.appspot.com/_ah/stats/shell). The results were pretty interesting:

* Without my CL: 131 memcache calls
* With my CL: 83 memcache calls
* With all NDB memcache turned off (`ndb.get_context().set_memcache_policy(lambda _: False)`): 56 memcache calls

There are only 10 entities being interacted with and a single query. Where are all those memcache calls coming from? Luckily, the timeline on the interactive shell has callstacks (unfortunately, I can't find the same callstacks in stackdriver traces). The callstacks show that:

* Our hooks in [`datastore_hooks.py`](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/datastore_hooks.py) create a lot of additional memcache calls
* Even though the code is written as one query, app engine breaks it up into multiple `RunQuery` calls which each go through `datastore_hooks.IsUnalteredQueryPermitted`. I believe we could cache the results in `request.registry` in that file to speed things up.

**All the investigations so far lead me to believe that we can still get a lot of performance out of app engine datastore.**

**Comment by anniesullie** [comment]
Ah, note the numbers in my comment above are doubled since the output is doubled on the interactive shell page. But https://codereview.chromium.org/2350113002/ seems to get the numbers down to a sensible point; need to fix its unit tests though.

**Comment by dave-2** [comment]
Maybe the rest are from `stored_object`.
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/stored_object.py

**Comment by anniesullie** [comment]
Yep, it's usage of `stored_object` and `layered_cache` that are at the root of all the memcache accesses I'm working around in `datastore_hooks` in https://codereview.chromium.org/2350113002/. However those usages are good, in my opinion: for example we cache the results of a query on a user to chrome-infra-auth. In that case, we're likely to check the same user over and over again, so putting it in memcache makes sense. My CL just caches the info per-request in a dict which should be in-memory, so we don't go through the long list of checks again and again.

`stored_object` and `layered_cache` should be the same API as well, but that's a separate bug.

**Comment by anniesullie** [comment]
I think @simonhatch has found a lot of lower-hanging fruit for optimizations
