### ISSUE TITLE
Enable eslint "Require Camelcase" rule

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2809]
http://eslint.org/docs/rules/camelcase

This will prevent camelcase/underscore-delimited confusion from ever taking up time in code review.

**Comment by eakuefner** [comment]
In favor of this. It might cause a little pain in those instances where we need to cross the Python/JS boundary, but probably not and we can address that if/when it comes up.

**Comment by zeptonaut** [comment]
It looks like the main thing preventing this from working is in the few cases where we use an underscore to add meaning to the variable name, like `g_myGlobal` or `opt_myOptionalParameter`.

I know part of the beauty of `eslint` is that it's really easy to write custom rules for it. I wonder how hard it would be to write a rule that basically does:

1. Run camelcase rule on the code
2. For each violation of the camelcase rule that starts with `opt_` or `g_`, strip off that prefix and rerun the result through the camelcase rule, reporting any errors that come out.

Totally do not know the limitations of writing these rules, but it seems like some sort of "rule inheritance" like that might be possible.

**Comment by zeptonaut** [comment]
(FWIW, here's the code for the original camelcase rule: https://github.com/eslint/eslint/blob/c67632259783c9630831bce5f272eb6160ee086c/lib/rules/camelcase.js)

**Comment by eakuefner** [comment]
I am sure that it would be possible to write a plugin that extends the built-in camelcase rule, and reasonably confident that it would not be very much work if you want to take it on.

**Comment by eakuefner** [comment]
Though re: globals, I'm curious where the g_ convention comes from and why we need it.

**Comment by zeptonaut** [comment]
Yea: I agree that the globals are likely less useful than the opt_, which is very prevalent.

**Comment by benshayden** [comment]
:+1:

**Comment by zeptonaut** [comment]
Based on [this discussion](https://groups.google.com/forum/#!topic/eslint/2dUMPWpmbEI), it sounds like our best bet is to create a folder for our own eslint rules and just copy and paste their camelcase rule w/ our modifications. It ain't pretty, but given our very limited modifications, we shouldn't create too much hardship for ourselves in the future.
