### ISSUE TITLE
telemetry pulling and wiping but not displaying tombstones

### ISSUE THREAD

**Issue by jbudorick** [catapult-project/catapult#2812]
e.g. https://chromium-swarm.appspot.com/user/task/314cb5d7698ba610

I'm planning on looking into why the DevToolsTargetCrashedException is unprintable.

cc @nedn

**Comment by nedn** [comment]
Thanks John!
cc @ehanley324 @kenrussell

**Comment by jbudorick** [comment]
Replaced by #2821
