### ISSUE TITLE
Perf Tryjob from dashboard still uses rietveld to trigger job.

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#2817]
Perf Tryjobs triggered via dashboard still uses rietveld to start try jobs. This need to be changed to use buildbucket APIs.
https://cs.chromium.org/chromium/src/third_party/catapult/dashboard/dashboard/start_try_job.py?q=start_try&sq=package:chromium&l=624

**Comment by benshayden** [comment]
Simon says this is done.
