### ISSUE TITLE
Data stoppage alerts use computed property for last_row_date

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2818]
Instead of saving the `last_row_date` when they are created, it's implemented as a computed property which does a get() on the `Row`, so if we show 500 data stoppage alerts then we are doing 500 get()s in serial.

The right solution to fix this is to make `last_row_date` a timestamp property that is set upon creation, not a computed property.

A quick workaround is to display fewer data stoppage alerts.

@dave-2 @eakuefner @benshayden @Apeliotes

**Comment by eakuefner** [comment]
I think this is fixed as of pretty recently, right?
