### ISSUE TITLE
scalar_span_test.html is failing at Catapult HEAD

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2823]
@benshayden, would you mind looking into this?

**Comment by benshayden** [comment]
Looking.

**Comment by eakuefner** [comment]
@zeptonaut can you link example failing build(s) here?

**Comment by zeptonaut** [comment]
Gahhhh, I thought I was synced to HEAD but I wasn't :-/ Sorry for the bad bug.
