### ISSUE TITLE
run_metric should share code

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2828]
It should probably share code with either timeline_based_measurement.py and/or results_renderer.py, and there should be unit tests.

**Comment by benshayden** [comment]
What should run_metric share code with? It looks like it calls metric_runner.RunMetricOnTraces and results_renderer.RenderHTMLView.

**Comment by benshayden** [comment]
I'm looking at [run_metric](https://github.com/catapult-project/catapult/blob/master/tracing/bin/run_metric) and [telemetry_based_measurement](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/web_perf/timeline_based_measurement.py), both of which call [metric_runner](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/metric_runner.py). Both also use [results_renderer](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/results_renderer.py), though of course telemetry_based_measurement delegates that to HtmlOutputFormatter.

run_metric and telemetry_based_measurement do different things with Failures, which we're going to merge into Histograms via FailureInfo #3077 
telemetry_based_measurement consumes the scalars, run_metric does not.

run_metric looks to me like pretty simple glue code between metric_runner and results_renderer.

Do you see any specific code that run_metric should share with telemetry_based_measurement? @eakuefner @nedn 
If not, I think this issue can be closed?

**Comment by nedn** [comment]
I am unclear why we think they need to share more code. Closing this sgtm.
