### ISSUE TITLE
Allow 'const' in JS

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2833]
We currently disallow const in our codebase based on some old folk knowledge that const is slow. According to V8 team, this has not been the case for some time especially as the semantics of const have solidified recently with ES6. We should get rid of the Catapult "don't use const" check and replace it with eslint's `prefer-const` rule.

@zeptonaut @benshayden

**Comment by benshayden** [comment]
:+1:

**Comment by zeptonaut** [comment]
My feeling is that this is going to be a *massive* change in the codebase if we turn it on. I tried to confirm that by adding:

```js
      "prefer-const": ["error", {
        "destructuring": "any",
        "ignoreReadBeforeAssign": true
      }],
```

to the .eslintrc file and rerunning the linter, but... no errors are reported for that rule, which I'm *extremely* skeptical of.

The command I used to run it was:

```sh
$ find tracing/tracing -name "*.html" | xargs common/node_runner/node_runner/bin/node/node_linux_x86_64_da9f3781488844a966106822ef3dbdbe2377ff13/node-v6.5.0-linux-x64/bin/node common/node_runner/node_runner/node_modules/eslint/bin/eslint.js -c common/eslint/.eslintrc --rulesdir common/eslint/rules > /tmp/violations.txt
```

Any ideas what I might be doing wrong?

**Comment by benshayden** [comment]
Looks like this rule only looks at "let" declarations, not "var"s.
http://eslint.org/docs/rules/prefer-const

Try turning on no-var and running eslint with --fix to change all vars to lets, not that that's something that we necessarily want to do, but that might let prefer-const have something to do.

**Comment by eakuefner** [comment]
I think this suggests a two step approach of moving from var to let and then turning on prefer-const. Using --fix seems like it might actually be a compelling option here.

If folks agree that turning on prefer-const is an eventual goal, does that suggest that we should start early by getting rid of the current no const check?

**Comment by zeptonaut** [comment]
Unfortunately, the `--fix` option doesn't work for our use case of eslint yet :-(

I actually spent some time investigating why this morning: I couldn't figure out why it wasn't fixing the existing `no-extra-semi` violations. It turns out, it says why on [this](http://eslint.org/docs/user-guide/command-line-interface#fix) page:

> Not all problems are fixable using this option, and the option does not work in these situations:
> 
> This option throws an error when code is piped to ESLint.
> This option has no effect on code that uses processors.

I talked to a guy in the eslint chat room, who said that he was interested in fixing this problem, but that last time it was proposed it kind of sputtered. [Here's the tracking bug for the last time](https://github.com/eslint/eslint/issues/5121).

**Comment by benshayden** [comment]
Another route would be to hack the prefer-const rule to check vars.

**Comment by zeptonaut** [comment]
I agree that `prefer-const` would be a good thing to have eventually, but I guess my feeling is that there might be more impactful rules that we could turn on for now that help enforce our existing style. A couple examples:

- [Enforce consistent spacing for object literals](http://eslint.org/docs/rules/object-curly-spacing)
- [Enforce consistent spacing between blocks](http://eslint.org/docs/rules/space-before-blocks)
- [Use eslint's method of enforcing strict mode](http://eslint.org/docs/rules/strict)
- [Require the use of === and !== over == and !=](http://eslint.org/docs/rules/eqeqeq)
- [Enforce the use of dot notation where possible](http://eslint.org/docs/rules/dot-notation)
- [Prefer use of arrow functions for callbacks](http://eslint.org/docs/rules/prefer-arrow-callback)

It's not that I don't think that the `const` migration would be useful: I think my preference is to focus first on preventing bad practices from ever making it to code review, and kick the can down the road a little bit for trying to change people's behavior with regards to ES6 features that will require major changes to the codebase.
