### ISSUE TITLE
Turn on comma-spacing eslint rule

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2836]
I just saw this in a code review:

![image](https://cloud.githubusercontent.com/assets/1407397/18727754/2e3b9b3e-8018-11e6-9c4c-ad61201c82ed.png)

We should definitely turn on an eslint rule to ensure that commas have no spaces before them and one space after them.

/cc @eakuefner @benshayden

**Comment by eakuefner** [comment]
+1

Charlie, I've assigned this to you so that this bug can have an owner. Are you willing to turn the rule on?

**Comment by zeptonaut** [comment]
It was done in this CL by @Alex319, but there was no corresponding BUG= so it didn't get mentioned in this bug. Going to go ahead and close this.
