### ISSUE TITLE
Memory-infra counts should be using count units

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2837]
Currently, the counts reported by the memory metric show decimal places, which is probably not what we want because these are presumably whole numbers. @benshayden added a 'count' unit which deals with this use case, which memory-infra should use for these histograms.

<img width="938" alt="screen shot 2016-09-21 at 14 48 10" src="https://cloud.githubusercontent.com/assets/75990/18730511/94ad93c0-800b-11e6-85ea-19e9fb8c8412.png">

**Comment by fmeawad** [comment]
@ssiddhartha

**Comment by petrcermak** [comment]
__Fixed__ ✅
