### ISSUE TITLE
Right-align scalar-span by default

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2856]
Every table of numbers should always align the decimal point to afford vertical scanning. This is one of the primary advantages of positional number systems such as Hindu-Arabic numerals over other types of numeral systems such as Roman or Egyptian numerals.

All of Tufte's tables' number columns that I checked are right-aligned since numbers typically have the same number of digits after the decimal point, though I can't find where he explicitly recommends it.
Here's a paper that does explicitly recommend it:
[Strategy Institute 2011](http://aaude.org/system/files/documents/public/strategy-institute-handout-final.pdf), and a [UX stackexchange thread](http://ux.stackexchange.com/questions/24066/what-is-the-best-practice-for-data-table-cell-content-alignment).

If an application would have the same number of digits before the decimal point but a variable number of digits after it, then left-alignment could possibly make sense, though I am unaware of such an application.

If scalar-span were used in paragraphs of flowing text, then its alignment wouldn't matter, so it might as well be right-aligned.

**Comment by petrcermak** [comment]
+1 👍
