### ISSUE TITLE
BIsect could generate results2.html

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2861]
Bisect involves running benchmarks, collecting results, and presenting information about the results to help diagnose the regression. results2.html is the new way to present benchmark results.

What would be required to actually generate results2.html from bisect? Where is the code?
What use cases are covered by the existing bisect results that are not covered by results2.html?
@ro-berto @nedn @eakuefner @dave-2

**Comment by anniesullie** [comment]
Long term, I think we'll want some way to assemble results2.html from different runs. Another example that's very similar to this (I think) is wanting to eventually be able to run perf tryjobs for, say, 3 benchmarks on 4 different bots and get some summary of the results. @dave-2 has been thinking about long-term plans for the control logic for bisect: any thoughts?

**Comment by nedn** [comment]
We  have [a script](https://codereview.chromium.org/2332153005/) that can turn chart-json to results2.html. I suppose we can extend that script so that it can take a list of chart json.

**Comment by eakuefner** [comment]
I think that this bug isn't really actionable, and should probably be closed as such. I have a feeling that many of the use cases that would have been covered by integration with results2 will instead turn out to be features of Pinpoint.
