### ISSUE TITLE
New power metrics not working on some test cases on Mac

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2867]
[https://build.chromium.org/p/tryserver.chromium.perf/builders/mac_retina_perf_cq/builds/518/steps/battor.power_cases_no_chrome_trace/logs/stdio]

The build above fails in the new power metric with "Cannot read property 'rendererHelpers' of undefined". This is likely due to my recent changes to the power metric.

**Comment by Alex319** [comment]
It looks like the problem here is that these failures occur when there isn't any Chrome trace available. In this case, the power metric will be unable to run. I plan to add code to the power metric that fails gracefully when this happens.

**Comment by nedn** [comment]
@erikchen
