### ISSUE TITLE
Migrate callstats.py based benchmarks to telemetry

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#2868]
There is a set of [benchmarks](https://chromeperf.appspot.com/report?https://chromeperf.appspot.com/report?sid=1be638d9f575cfb937fab7d6ea8c133704cf8b2b1a5929a722ac21baf7cec8ad&start_rev=36493&end_rev=10000000000000) based on V8 runtime call stats that are currently using callstats.py to /add_point(s) to the dashboard. Now that runtime call stats works in Tracing, we should migrate those benchmarks to use TBMv2.x instead.

**Comment by fmeawad** [comment]
@nedn @lpy

**Comment by nedn** [comment]
Since this involves patches work in chromium, can you make the crbug? We can keep this one for creating tbm2 metrics.

**Comment by fmeawad** [comment]
Agreed.
