### ISSUE TITLE
Uploaded results.html are not stored on selected --upload-bucket

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2872]
On [crbug.com/623015](https://crbug.com/623015) I've just added `--output-format html` to also get the `results.html` file uploaded at the end of a test run. While traces are correctly being uploaded to the `chrome-health-archives` bucket, the `results.html` file ends up in `chromium-telemetry`.

Example [log](https://uberchromegw.corp.google.com/i/internal.client.clank/builders/integration-android-low-end-phone/builds/2290/steps/memory.long_running_dual_browser_test/logs/stdio) (internal)

Is this WAI?

@Apeliotes

**Comment by chromy** [comment]
The relevant lines we would need to change are:
[HTML Output](https://github.com/catapult-project/catapult/blob/bea54e53a27aa0697b4bf7bbe31f89366906b0d6/telemetry/telemetry/internal/results/html_output_formatter.py#L188)
[HTML2 Output](https://github.com/catapult-project/catapult/blob/bea54e53a27aa0697b4bf7bbe31f89366906b0d6/telemetry/telemetry/internal/results/html2_output_formatter.py#L32)

They would have to be more like [this](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/story_runner.py#L350).

**Comment by perezju** [comment]
+ @nedn @anniesullie @eakuefner what are your thoughts on this?

**Comment by anniesullie** [comment]
I don't know the reason for this. @Apeliotes @eakuefner do you know?

**Comment by eakuefner** [comment]
This isn't WAI. The fix is exactly what @chromy suggests, and I support it.

**Comment by chromy** [comment]
Thanks all! (CL uploaded here https://codereview.chromium.org/2518943004/)

**Comment by benshayden** [comment]
This looks done.
