### ISSUE TITLE
Perf Dashboard: "Graph" button results in "malformed request"

### ISSUE THREAD

**Issue by jeisinger** [catapult-project/catapult#2876]
Chrome version: 55.0.2875.0 (Mac)
URL: https://chromeperf.appspot.com/alerts?sheriff=V8%20Memory%20Perf%20Sheriff&sortby=end_revision&sortdirection=down

Please copy and paste any errors from JavaScript console (Command+Option+J to open):

Please describe the problem:

when selecting a bunch regressions and clicking on "graph" a new tab with this URL is opened: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpYKUrAsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpe-CugkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpcyO6woM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5d2hvgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpc_WvwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICglfCqsAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpc3I-goM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5fngoAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5YHhsQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5eiprAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpf2P4ggM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgxZP-_goM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgxZP-_gkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5YH1qAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5bzMoAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5amkoAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5YawtAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5eKRuQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICglfDeqQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5brsswsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5c3bvQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgxZWF_AsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5euCsgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpbnNvAsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5fqEvwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5evmqwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5eattwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5ZiMqgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5d3fqAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5eattwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpc2clwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpdmF4QoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpY2U9AkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5aTOuAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpbuEtQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpcKG7ggM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpZebiAgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpcD0-gsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5ZLZqgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5fnFpAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5a2KqgsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5b2EuQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpZqh_AkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpe6K4wkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICglfC0oQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5ZbAvwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5a35pgsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpYr8-gkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpdqE-goM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5ZbAvwsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpee3-wgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICglfTlpwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpcb87QkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpbeI8goM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5eykpgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5ZizrgsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpav5rgsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpYTnmAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpYOxlggM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpZeR_wsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpcDT_gsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpcnBtAsM

which results in a 400 - bad request error

**Comment by jessimb** [comment]
Bug also reported in #1408, #1994, #2596, and #2434.
