### ISSUE TITLE
Perf Dashboard: internal server error

### ISSUE THREAD

**Issue by jeisinger** [catapult-project/catapult#2877]
Chrome version: 55.0.2875.0 (Mac)
URL: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5b6muAsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICglYyioAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICglfDe6QgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5cWAtwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpa_qjAgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICglciUtgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpa679AoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg5em64ggM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgpd6y9QoM

Please copy and paste any errors from JavaScript console (Command+Option+J to open):

https://chromeperf.appspot.com/group_report Failed to load resource: the server responded with a status of 500 ()

Please describe the problem:

trying to load above page gives me a 500 - internal server error

**Comment by anniesullie** [comment]
I pasted the code that gets called for this request into the interactive shell and the call to `_GetSubTestsForAlerts` which makes repeated calls to `list_tests.GetSubTests` is slowing things down dramatically. This is very similar to #2887, and the same work applies there, need to document what this is trying to accomplish exactly so we can find a faster way to do it.

**Comment by anniesullie** [comment]
I just pushed a version that removes this `list_tests.GetSubTests` code altogether. Let me know if
* You still see internal server errors
* You notice any regressions in the way the chart legend lists timeseries

**Comment by jeisinger** [comment]
all looks good now, thx
