### ISSUE TITLE
Perf Dashboard: ctrl+c is broken in test field

### ISSUE THREAD

**Issue by vapier** [catapult-project/catapult#2880]
Chrome version: 53.0.2785.36 (Chrome OS)
URL: https://chromeperf.appspot.com/report

Please describe the problem:
if you select a test in the Test Suite field, then highlight the text and hit CTRL+C, the field is cleared and the text isn't actually copied.

**Comment by anniesullie** [comment]
@Apeliotes can you look at this with the autocomplete refactor--does copy/paste work better now?

**Comment by vapier** [comment]
looks like any keyboard shortcut ... ctrl+a also makes it angry.  maybe the JS logic isn't checking for modifiers ?

**Comment by benshayden** [comment]
Archiving.

**Comment by vapier** [comment]
looks like it's been fixed at some point
