### ISSUE TITLE
Perf Dashboard: Bisect not choosing correct Bisect bot

### ISSUE THREAD

**Issue by rmcilroy** [catapult-project/catapult#2883]
Chrome version: 54.0.2816.0 (Linux)
URL: https://chromeperf.appspot.com/group_report?bug_id=650590

Please describe the problem:
The above report is for alerts on chromium-win-clang (and one on chromium-rel-mac11), however when I try and perform a bisect, the popup chooses "android_webview_aosp_perf_bisect" as the bisect bot. When I try to change it, this is the only option in the list.

**Comment by rmcilroy** [comment]
Also selected the wrong bot initially in https://chromeperf.appspot.com/group_report?bug_id=650686, but I was able to select the correct bot in that case.

**Comment by anniesullie** [comment]
The problem in the first one is that chromium-win-clang is an FYI bot and does not have a bisector. It looks like bisecting on chromium-rel-mac11 works as expected?

@ulan should memory.long_running_idle_gmail_tbmv2 be monitored on FYI bots?

For the second one, the default I get is android_webview_aosp_arm64_bisect, which isn't a great name but is the correct bisect AFAICT. Is that what you're seeing?

**Comment by rmcilroy** [comment]
Thanks for the quick reply. 

For the second one I also get android_webview_aosp_arm64_bisect, however the alert was for android-webview-nexus5X (which is running arm32, not arm64, so a different architecture). There doesn't seem to be an arm32 webview perf bisect bot in the list though -android_webview_aosp_perf_bisect doesn't appear - that might be the closest match?

For the first one, makes sense about chromium-win-clang being an FYI bot but:
 - should we even be triaging alerts from FYI bots which don't have bisectors?
 - it seems strange that we even offer android_webview_aosp_perf_bisect would be offered as an option, since it is completely unrelated to the alert. Could we just print a warning that no bisect bot is available instead?

**Comment by anniesullie** [comment]
@yoland68 can you take a look at @rmcilroy's comments on WebView perfbots and bisectors?

**Comment by case540** [comment]
@rmcilroy The android-webview-nexus5X bot is arm64. So for those builds you will want to bisect on the android_webview_aosp_arm64_bisect. So it sounds like it is doing the right thing.

Currently, there are two WebView bisect bots.

64 Bit

**Bot:** Android Nexus5X WebView Perf
https://build.chromium.org/p/chromium.perf/builders/Android%20Nexus5X%20WebView%20Perf%20(1)
**Bisect Bot:** android_webview_arm64_aosp_perf_bisect
https://build.chromium.org/p/tryserver.chromium.perf/builders/android_webview_arm64_aosp_perf_bisect

32 Bit

**Bot:** Android Nexus6 WebView Perf
https://build.chromium.org/p/chromium.perf/builders/Android%20Nexus6%20WebView%20Perf%20(1)
**Bisect Bot:** android_webview_nexus6_aosp_perf_bisect
https://build.chromium.org/p/tryserver.chromium.perf/builders/android_webview_nexus6_aosp_perf_bisect

**Comment by anniesullie** [comment]
Based on @case540's comment, closing as WAI.

**Comment by rmcilroy** [comment]
Ahh I see - sorry for the noise (although it would be great if we could rename the bots or have a list of what the corresponding bisect bot is for each bot is).

I still have the question that we are monitoring FYI bots with no corresponding bisect bot, and the interface chooses an inappropriate one in the case of the inital report (e.g., android_webview_aosp_perf_bisect for the FYI bot chromium-win-clang)

**Comment by rmcilroy** [comment]
The issue of the dashboard suggesting android_webview_aosp_perf_bisect as a bisector for chromium-win-clang caused some fruitless investigation on https://bugs.chromium.org/p/chromium/issues/detail?id=650590 since the bisects weren't representative of the actual regression on the FYI bot. Any chance we could get this fixed?

**Comment by anniesullie** [comment]
(sorry for the delay here)

I changed these tests not to alert on FYI bots.

**Comment by rmcilroy** [comment]
That's great, thanks Annie!
