### ISSUE TITLE
Refactor cpu usage track and cpuTimeMetric to share code

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2886]
https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/tracks/cpu_usage_track.html

https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/system_health/cpu_time_metric.html

@fmeawad @nedn

**Comment by nedn** [comment]
@zeptonaut @natduca 

I think this is a bit related to https://codereview.chromium.org/2323533003/#msg46 (having a general API for computing Chrome's EIL between time a & b).

**Comment by fmeawad** [comment]
@lpy

**Comment by benshayden** [comment]
I had been thinking that keeping metrics in metrics/ would simplify and clarify ownership. We would be able to say to metric authors "you own this file, we own the UI, we'll make the UI call a function from your file". However, Nat reminded me that tracing/ui should not have a hard dependency on any metric, all of which have hard dependencies on lots of other code including stuff in extras/chrome/, because systrace uses a lean systrace_config.html to only import the code that they need.

Relatedly, Lighthouse was recently looking at their code size and noticed that they were importing all of memory-infra, which is a lot of code that they don't need. @paulirish 

So, for the metrics that we might want to handle specially in the UI like cpuTimeMetric (as opposed to metrics_side_panel, which handles all registered metrics generally without a hard dependency on all_metrics.html), let's split the core functionality to extras/. Metric authors would own one meaty file in extras/ and a trivial file in metrics/ that calls to the file in extras/ and generates Histograms and Diagnostics. Configs can pick and choose which files in extras/ they want to include without accidentally bringing in all of tracing/value and extras/chrome.

I wonder if it would be worth it to build a presubmit test that fails if certain configs depend on certain files, e.g. if lighthouse_config.html depends on global_memory_dump.html then error. Or maybe clients like systrace and lighthouse should use a gypi file that explicitly lists all of the transitive dependencies? That would leverage the existing presubmit for trace_viewer.gypi.

WDYT?

**Comment by benshayden** [comment]
Archiving
