### ISSUE TITLE
Calls to list_tests.GetSubTests slowing down queries for chart data

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2887]
In `graph_json.py`, we call `list_tests.GetSubTests` in several places. This slows down the request substantially. The data seems to be used for grouping tests in the legend into core/non-core traces. We need to write up a doc about exactly what the UI requirements are and implement a faster solution.

**Comment by anniesullie** [comment]
Wrote up a [design doc](https://docs.google.com/document/d/1HCoC__FPYwnuZRmnA-cmi6kKoWGq8YlFU9y3KRFbFnU/edit#). I'm hoping to optimize the queries in graph_json tomorrow.

**Comment by eakuefner** [comment]
This is fixed.
