### ISSUE TITLE
Sweep the repo for catapult-camelcase violations

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2892]
https://codereview.chromium.org/2385153002/

When we enable eslint rules, should we sweep the repo to fix existing violations so that devs don't need to fix them in unrelated CLs?

@zeptonaut @eakuefner

**Comment by benshayden** [comment]
It looks like this rule is only disabled in statistics.html for normalized_samples.

**Comment by zeptonaut** [comment]
Yea, I think this bug is okay to close. I think that we've naturally adopted this process, anyhow.
