### ISSUE TITLE
Memory metrics should report slope

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2893]
Preserving an idea here from an old email thread: it seemed important a few months ago for memory infra to be able to look at the rate at which memory usage increases over time in test scenarios. Quoting Petr:

> I can see two options to do this:
> Memory-metric-specific:
> For each value (e.g. memory:chrome:all_processes:reported_by_chrome:v8:effective_size), the memory metric explicitly injects yet another value (memory:chrome:all_processes:reported_by_chrome:v8:effective_size_slope).
> TBMv2-wide:
> Add "slope" to the possible statistics reported by tr.v.Numeric. The challenge here is how to aggregate slope over multiple traces, i.e. given two traces with slopes s1 and s2, how do you aggregate the overall slope (this is not a problem in option 1 because slope would be a regular histogram).

So, two concrete questions:
1. Do memory metric consumers still want to do this?
2. If so, does this seem like something that should be a TBMv2 feature?

Given the technical challenge of approach 2 and the lack of motivation for slope in other contexts, my inclination is to say that this should be done at the memory metric level if at all.

Assigning to @chromy just so that this bug is triaged -- memory-infra folks please feel free to shuffle ownership.

@perezju @benshayden @nedn

**Comment by benshayden** [comment]
I assume by "time" you're referring to the passage of time measured in ms within a single trace, not the x-axis of the dashboard charts, measured in build numbers, or any other x-axis, but I thought I'd check.

Adding a time dimension to Histograms seems like it might over-complicate them.
There might be a few other metrics that might benefit from it, but it doesn't seem to be generally useful in the ways that Diagnostics and statistics are generally useful.
I might rather provide helper methods to compute slope metrics if memory isn't the only metric that wants it.
WDYT? :-)

**Comment by nedn** [comment]
I agree with making this a one off thing for memory and not generalize until we see a few more use cases.

**Comment by perezju** [comment]
We still want this, but I it's not high on our current list of priorities. I also agree that perhaps this is something that should be implemented as a one-off for memory (and we might think about generalizing only if really needed).

The use case we have in mind is for long running tests, where we want to use a large `--pageset-repeat` and keep the browser open for the whole duration of the test. For example:

Repeat 60 times:
- load google.com
- load facebook.com
- ... [for some 10 pages]

We then want to compute the slope of, say, overall pss across the 60 individual measurements for google.com; in this case a positive slope is a strong indicator of a memory leak.

In particular note that the slope is not computed for a single trace, but when summarizing across many different traces.

@primiano @picksi

**Comment by nedn** [comment]
Hmhh, seems like this should be a feature of summarization then. IIRC, result.html currently have some feature for detecting the correlation between metrics' change on the number of repeat, so this is probably not too controversial

**Comment by picksi** [comment]
There is value in knowing the underlying slope (e.g. rate of change of memory use), but I don't know how much engineering time it merits. Assuming, of course, that it will be possible to see slopes just by looking at the original graphs ... i.e. a leak will be clearly visible as an upward trend in the data.

**Comment by perezju** [comment]
I think I'm going to close this now as obsolete. The only place where this would make sense is in our internal long running (~5 hours) memory test. And if something breaks there, we can do manual investigations, compute slope's etc. as needed. No need at the moment to generalize.
