### ISSUE TITLE
Enable keyword-spacing eslint rule

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2894]
I noticed in a recent code review that

```js
for(var exp of model.userModel.expectations) {
```

made it past any presubmits and had to be fixed in code review, wasting reviewee and reviewer time.

eslint has a rule for this, [keyword-spacing](http://eslint.org/docs/rules/keyword-spacing), which we could turn on to catch this. Before turning it on, we probably want to fix all existing occurrences of this in the tracing codebase so that people don't get warnings on code they didn't write.

@Alex319, would you be willing to take this on? I could help you figure out how to do this (it isn't too bad), and it'd be great to get you acquainted with how to do this so that you could help us turn on awesome new eslint rules to make the tracing codebase even healthier.

/cc @eakuefner @benshayden

**Comment by Alex319** [comment]
That would be a good idea. It would be very helpful for me to get a better
understanding of how the linter/presubmit process works.

-Alexander Mont
