### ISSUE TITLE
ref graph doesn't display and selection is grayed out

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2899]
@anniesullie @Apeliotes 

When I go to a group_report eg https://chromeperf.appspot.com/report?sid=1bcc282005db82d372b30d61d7bf667a205cd63b57bccd4f0a231f008da00377&rev=352345 I see that page_load_time_ref and ref are checked and they seem grayed out, so that I cannot check them. I don't see a line for ref on the chart. Also, when I hover on the i for either of the grayed ones, the card is semi-transparent.

**Comment by anniesullie** [comment]
Can you post a screenshot? I see something different: the page_load_time chart is checked, and the ref build doesn't show up at all. Whether that's a bug depends on how you selected what goes in that chart, can you explain?

![screen shot 2016-10-05 at 11 05 55 am](https://cloud.githubusercontent.com/assets/4331931/19118841/bbbde2c2-8aeb-11e6-841e-88c3dc611800.png)

**Comment by benshayden** [comment]
Archiving.
