### ISSUE TITLE
Clean up dashboard dependency tree.

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#2900]
https://codereview.chromium.org/2384973002/ created the `common/` and `services/` folders.

We'll want to clean up the code to ensure that all the dependency requirements are met:
- `common/` has no dependencies on any other folders.
- `services/` can only depend on `common/`.
- `models/` can depend on `common/` and `services/`.
- `dashboard/` can depend on all of the above.

`common/` is going to expand as I think there are other files that could go into it, like `request_handler.py` and `xsrf.py`.

There's also an open question on what to do with the rest of the files in `dashboard/`. We should consider something like moving all the default module request handlers into a folder called `default/`.

**Comment by anniesullie** [comment]
@nedn @Apeliotes is there some existing lightweight way in telemetry to ensure via unittest which python modules can depend on each other?

I agree request handlers specific to perf dashboard should be in their own folder, but if you aren't familiar with the way modules are setup, `default` is a pretty confusing name for it. I think we should come up with a better name for the perf dashboard module (and eventually poke at whether it should be broken down into multiple modules)

**Comment by nedn** [comment]
No we don't. I believe best way to achieve this is through isolated testing, i.e: you declare all the files needed for your project & only use those files in the test.

@ehanley324

**Comment by benshayden** [comment]
Archiving.
