### ISSUE TITLE
CQ blocked on SDK download failure

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2903]
https://uberchromegw.corp.google.com/i/tryserver.client.catapult/waterfall
https://uberchromegw.corp.google.com/i/tryserver.client.catapult/builders/Catapult%20Mac%20Tryserver/builds/5257/steps/Run%20SDK%20downloader/logs/stdio

```
Traceback (most recent call last):
  File "/b/build/slave/catapult/build/get_appengine.py", line 15, in <module>
    from install_cipd_packages import get_platform
ImportError: No module named install_cipd_packages
step returned non-zero exit code: 1
@@@STEP_FAILURE@@@
```

Similar issue: http://crbug.com/648429. Not sure if it's related to how we share code with infra on that step. I think the next steps are:

* Look through commit history to see if this is clearly related to a specific CL
* File a crbug and cc relevant folks for help.

**Comment by anniesullie** [comment]
Looking at the history, the CL that added that import is https://chromium.googlesource.com/infra/infra/+/de4d0ca9f402ff42fddd504c616c5216ca2a9712

**Comment by jbudorick** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=653125

**Comment by jbudorick** [comment]
dnj@ fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=653116
