### ISSUE TITLE
Babylonian unit scale

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2904]
https://chromiumperfstats.appspot.com/
How long is 100000 seconds? Hours? Days?
Firefighter needs to be able to use longer units of time than seconds.
The minute and hour are based on a sexagesimal unit system invented by the Babylonians.
We currently have metric and binary unit scales.
Let's add a Babylonian unit scale for long time measurements.

@eakuefner @dave-2

**Comment by Alex319** [comment]
I worked with fixing the unit_scale before so I can work on this

**Comment by Alex319** [comment]
It looks like this was done but not tested correctly; it didn't work. Will send commit that fixes the bug and adds a test case.
