### ISSUE TITLE
Metrics side panel no longer show loading metric

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2907]
To reproduce:
Open dev server
View the trace

[http___bookish_com1.html.zip](https://github.com/catapult-project/catapult/files/514108/http___bookish_com1.html.zip)

Click on metric side panel & loadingMetric

**Comment by nedn** [comment]
Hmhh, actually this is a Chrome bug. The metric side panel works just fine in Chrome 53.0.2785.143 but doesn't show anything in TOT chrome build.

*sigh*

**Comment by nedn** [comment]
@benshayden

**Comment by benshayden** [comment]
I opened that trace in a dev server trace viewer in a debug chrome built at revision 2c87d6e203c564cb1224cae7501eccb10df2141d, and the metrics side panel looks fine.
