### ISSUE TITLE
node_runner fails to init on Windows for new users

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2908]
The eslint tests started failing on build79-b1 right around the same time as the SDK Downloader failure for reasons seemingly to do with the bot, rather than the platform.

I'm going to disable the tests on Windows for now and then investigate.

@zeptonaut @dave-2

**Comment by zeptonaut** [comment]
Note that, even when this test was passing (e.g. https://codereview.chromium.org/2397163002), we were still seeing an error during `npm install` on Windows:

```
module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\b\build\slave\catapult\build\catapult\common\node_runner\node_runner\bin\node\node_win_AMD64_0046368de2ffb3d474847238dfc82c3f7995810a\lib\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

@eakuefner suspects that we may be calling `npm install` slightly wrong on Windows, which caused this issue to manifest.

**Comment by eakuefner** [comment]
Removing P0 because I've disabled the tests on Windows temporarily. Also going to rename to reflect the fact that Node seems generally wonky on Windows after https://codereview.chromium.org/2361623007.

**Comment by eakuefner** [comment]
It turns out that the issue here is that node.exe is one level shallower in the hierarchy than the binary on other platforms (which is at `bin/node`). Hence, on Windows, npm can't be found. This explains why we see the error on all bots, even the ones that already have eslint setup. I'm guessing that the bot that this started failing on recently got a fresh checkout or something.

The best fix as suggested by @Apeliotes will be to just add a separate dependency in `node_binaries.json` that points to the correct path for `npm-cli.js` on each platform.

**Comment by eakuefner** [comment]
This is done.
