### ISSUE TITLE
Disable eslint for Jinja templates

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2913]
Some files, such as dashboard/templates/edit_anomaly_configs.html, will generate false positive parsing errors when processed with eslint. This is because these files are Ginger templates, which contain expressions like {{this}} that get replaced by Ginger with other code before being executed. However, as-is this is not valid Javascript and as such eslint throws a parsing error. Using eslint-disable in the file does not prevent the error from showing up, as eslint still needs to parse the file first. There should be a way in the script that runs eslint to tell it not to run eslint on particular files or to suppress warnings from particular files.

**Comment by benshayden** [comment]
/* eslint-disable */
http://eslint.org/docs/user-guide/configuring

**Comment by eakuefner** [comment]
s/Ginger/Jinja/ ?

There is an eslint-plugin-jinja, but it hasn't been updated to indicate compatibility with the latest release of eslint which we use. Others have been adding new custom rules to our eslint configuration, so this is probably a case where we could just fork the plugin and check it in. It doesn't seem to do much other than some simple regex replacements.

@zeptonaut

**Comment by anniesullie** [comment]
Yep, it's jinja, but we should be aiming to remove jinja templates in favor of polymer, instead of improving linting on them.

**Comment by eakuefner** [comment]
Okay, as there are only 19 of them, I think just prepending an eslint-disable comment is not a bad idea. @Alex319 want to take that on?

**Comment by Alex319** [comment]
As I mentioned, using eslint-disable on the file _does not_ remove the error. This is because the error is a _parsing_ error - i.e. it's not that eslint is reporting a warning; it's that eslint is trying to parse the file and is unable to because it doesn't recognize the Jinja template syntax {{ ... }}. Prepending eslint-disable does not stop eslint from trying to _parse_ the file (it needs to parse the file before it can see the eslint-disable)

**Comment by benshayden** [comment]
Oh sorry I missed that!

How much work would it take to port the jinja templates to polymer?

If too much, then could catapult_build/js_checks.py blacklist that directory?

**Comment by eakuefner** [comment]
I think presubmit's API allows for exclude lists to be passed around.

**Comment by eakuefner** [comment]
Can we step back, though? @Alex319 what is your use case? Are you modifying these templates? Are you just messing around with eslint locally? Something else?

If you're just using eslint locally, you can just make sure that you don't pass files in dashboard/templates/ into the command.

**Comment by zeptonaut** [comment]
@Alex319 - feel free to correct me if I'm wrong, but I think the rationale is to get down to zero errors/warnings when we run `common/eslint/bin/run_eslint`. My preferences (in order) are:

1. Turn on the eslint Jinja plugin for these files. That way, we get the same linting as we get on our normal HTML files.
2. Add these files to an exclude list that we pass from run_eslint to the eslint Python wrapper.

**Comment by zeptonaut** [comment]
I think we might be able to do this using a [.eslintignore file](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories). It's worth a shot?

**Comment by chromy** [comment]
I think @Alex319 added a  .eslintignore file in  https://chromiumcodereview.appspot.com/2422713002/
So it looks like this is done?
