### ISSUE TITLE
telemetry benchmark run throw exception when the browser doesn't exist

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2917]
To reproduce:
Go to chromium checkout
Run: `./tools/perf/run_benchmark -v --browser=release_x64 --output-format=html2 --also-run-disabled-tests page_cycler_v2_site_isolation.basic_oopif` (or pick other value of --browser= that you don't have).

Instead of outputting something like "cannot find browser of type release_x64", telemetry crashes with an exception:
Traceback (most recent call last):
  <module> at /usr/local/google/code/chromium/src/tools/perf/run_benchmark:22
    sys.exit(main())
  main at /usr/local/google/code/chromium/src/tools/perf/run_benchmark:19
    return benchmark_runner.main(config, [trybot_command.Trybot])
  main at /usr/local/google/code/chromium/src/third_party/catapult/telemetry/telemetry/benchmark_runner.py:468
    return command_instance.Run(options)
  Run at /usr/local/google/code/chromium/src/third_party/catapult/telemetry/telemetry/benchmark_runner.py:245
    return min(255, self._benchmark().Run(args))
  Run at /usr/local/google/code/chromium/src/third_party/catapult/telemetry/telemetry/benchmark.py:91
    return story_runner.RunBenchmark(self, finder_options)
  RunBenchmark at /usr/local/google/code/chromium/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py:325
    if (possible_browser.platform.GetOSName() == 'chromeos' and
AttributeError: 'NoneType' object has no attribute 'platform'

**Comment by csharrison** [comment]
I am getting this error when I try to run `run_benchmark try all` 

See:
https://build.chromium.org/p/tryserver.chromium.perf/builders/android_nexus7_perf_bisect/builds/3372

**Comment by nedn** [comment]
Should be fixed.
