### ISSUE TITLE
Perf Dashboard: 

### ISSUE THREAD

**Issue by dpuga1** [catapult-project/catapult#2918]
Chrome version: 42.0.2311.111 (Linux)
URL: https://chromeperf.appspot.com/report?sid=d43e01435d822ddc47de4440ca63af82426026a1f618e673c50254043b07b966&rev=234467

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:

**Comment by chromy** [comment]
It looks like that benchmark has moved to https://chromeperf.appspot.com/report?sid=a17c48033d83c0e25776306c7bf2a7dbd5c50c7ce2799fcf6b1f5d8d0a512851&rev=234467 (although that is a slightly newer version of macOS)
