### ISSUE TITLE
Histograms should be able to specify their default statistic

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2922]
We see situations where teams have been interested in setting goals based on summary statistics, e.g. movement in the 95th percentile. It should be possible for metric authors to indicate that a statistic other than the mean ought to be used for display in value-set-table cells, for alerting on the dashboard, and for bisection.

@benshayden @natduca

**Comment by benshayden** [comment]
Might metrics want to alert on multiple statistics? Say, both mean and stddev, or multiple percentiles? If so, then a default statistic doesn't seem useful there, or for bisect?

Do we have a specific metric that definitely wants to display something other than avg in value-set-table-cells?

**Comment by eakuefner** [comment]
Archiving; descriptors subsume this.
