### ISSUE TITLE
Enable eslint's 'quotes' rule

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2925]
This rule enforces use of single quotes (`'`) over double quotes (`"`), which is the convention that we already use almost everywhere in Catapult.

**Comment by chromy** [comment]
It's a little sad we can't easily enter strings with apostrophes in without escaping :(
But also I think this is done now right since nice I got an error about using the wrong kind of quotes and it looks like it is enabled in .eslintrc?

**Comment by zeptonaut** [comment]
Yep, @Alex319 went ahead and enabled it.
