### ISSUE TITLE
Create a convenient script for uploading files in binary_dependencies.json

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2926]
binary_dependencies.json contains all the information we need for uploading files to cloud storage. We should have a convenient script, s.t like upload_binaries that people can just point it to a .json file to upload files to cloud.

Command: `upload_binaries binary_dependencies.json`

**Comment by nedn** [comment]
cc: @chromy @jbudorick

**Comment by nedn** [comment]
John: currently how do you update the devil binaries?

**Comment by nedn** [comment]
Assign to John since he already has a script.

**Comment by jbudorick** [comment]
Sample usage:

```shell
./third_party/catapult/dependency_manager/bin/update \
  --config third_party/catapult/devil/devil/devil_dependencies.json \
  --dependency forwarder_host \
  --platform linux2_x86_64 \
  --path out-gn/Release/clang_x64/host_forwarder
```
