### ISSUE TITLE
v8_callstats_dump is broken, valueDicts should be removed

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2929]
https://github.com/catapult-project/catapult/blob/master/trace_processor/experimental/mappers/v8_callstats_dump.html#L31

ValueSet.valueDicts was not intended to be used like this, and this is broken in particular because of [this change](https://github.com/catapult-project/catapult/commit/03fbd54d8fdb0defa1a677b71d67a9f46544fa86).

ValueSet.valueDicts should probably be removed so that it isn't used like this. v8_callstats_dump is the only remaining caller besides value_set_test and metric_map_function. Those two callers should manually do what valueDicts does.

@fmeawad, can I ask you to fix v8_callstats_dump and then assign this back to me? Then I'll remove the getter. :-)

**Comment by fmeawad** [comment]
Instead of fixing it, I will make it use the runtime_stats_metric that I am working on now. I will make sure the later does not suffer the issues you spotted here.

**Comment by fmeawad** [comment]
I will leave this open until I migrate it to use the metric instead.

**Comment by benshayden** [comment]
This looks done
