### ISSUE TITLE
Result side panel doesn't show any results

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2937]
Chrome version:
53.0.2785.143 (Official Build) (64-bit)
OS	Linux 

Trace:

[http___www_muzoboss_ru_with_ts_proxy.html.zip](https://github.com/catapult-project/catapult/files/527397/http___www_muzoboss_ru_with_ts_proxy.html.zip)

To reproduce: 

+ Unzip & copy the trace to tracing/test_data.
+ Run the dev_server.
+ Open the side panel.
+ Expect to see metrics but it's empty.

It's worth noting that opening the html trace directly on the same browser does shows the metric in side panel. 

![screenshot](https://cloud.githubusercontent.com/assets/911877/19353603/e26e9302-9131-11e6-8962-f7fed641c977.png)

**Comment by nedn** [comment]
cc @benshayden

**Comment by deepanjanroy** [comment]
I had the exact same problem, but clearing all site data fixed it for me (devtools -> application tab -> Clear Storage -> Clear site data.) The metrics side panel work for me for your trace on Chrome 53 and ToT catapult.

**Comment by nedn** [comment]
Thanks Deep! That fixes my problem as well. Weird :-/

@caseq
