### ISSUE TITLE
Perf Dashboard:  Data stoppage alerts cannot show the graph

### ISSUE THREAD

**Issue by SummerLW** [catapult-project/catapult#2939]
Chrome version: 53.0.2785.116 (Linux)
URL: https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZy3AELEhNTdG9wcGFnZUFsZXJ0UGFyZW50Iq0BQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwX2VuX21fd2lraXBlZGlhX29yZ193aWtpX1NjaWVuY2UMCxINU3RvcHBhZ2VBbGVydBjR6BkM,agxzfmNocm9tZXBlcmZy4gELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IrMBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwX21faW50bF90YW9iYW9fY29tX2dyb3VwX3B1cmNoYXNlX2h0bWwMCxINU3RvcHBhZ2VBbGVydBjR6BkM,agxzfmNocm9tZXBlcmZy3AELEhNTdG9wcGFnZUFsZXJ0UGFyZW50Iq0BQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwX21feW91dHViZV9jb21fcmVzdWx0c19xX3NjaWVuY2UMCxINU3RvcHBhZ2VBbGVydBjR6BkM,agxzfmNocm9tZXBlcmZy4gELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IrMBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwX3NlYXJjaF95YWhvb19jb21fc2VhcmNoX195bHRfcF9nb29nbGUMCxINU3RvcHBhZ2VBbGVydBjR6BkM,agxzfmNocm9tZXBlcmZy2wELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IqwBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwX3d3d19hbWF6b25fY29tX2dwX2F3X3Nfa19uZXh1cwwLEg1TdG9wcGFnZUFsZXJ0GNHoGQw,agxzfmNocm9tZXBlcmZy2AELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IqkBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwX3d3d19iYWlkdV9jb21fc193b3JkX2dvb2dsZQwLEg1TdG9wcGFnZUFsZXJ0GNHoGQw,agxzfmNocm9tZXBlcmZy3wELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IrABQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwX3lhbmRleF9ydV90b3VjaHNlYXJjaF90ZXh0X3NjaWVuY2UMCxINU3RvcHBhZ2VBbGVydBjR6BkM,agxzfmNocm9tZXBlcmZy1AELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IqUBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwc19tX2ZhY2Vib29rX2NvbV9yaWhhbm5hDAsSDVN0b3BwYWdlQWxlcnQY0egZDA,agxzfmNocm9tZXBlcmZy9AELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IsUBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwc19tb2JpbGVfdHdpdHRlcl9jb21fanVzdGluYmllYmVyX3NraXBfaW50ZXJzdGl0aWFsX3RydWUMCxINU3RvcHBhZ2VBbGVydBjR6BkM,agxzfmNocm9tZXBlcmZy3gELEhNTdG9wcGFnZUFsZXJ0UGFyZW50Iq8BQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1WC9tZW1vcnkudG9wXzEwX21vYmlsZS9tZW1vcnk6Y2hyb21lOmFsbF9wcm9jZXNzZXM6cmVwb3J0ZWRfYnlfY2hyb21lOmdwdTplZmZlY3RpdmVfc2l6ZV9hdmcvYmFja2dyb3VuZC9hZnRlcl9odHRwc193d3dfZ29vZ2xlX2NvX3VrX2hsX2VuX3Ffc2NpZW5jZQwLEg1TdG9wcGFnZUFsZXJ0GNHoGQw

Please describe the problem:
When I tried to select one from Data stoppage alerts, and click GRAPH, it gives me an error "Error: Bad Request. Your client has issued a malformed or illegal request."

**Comment by jasontiller3** [comment]
Other data stoppage alerts are also throwing 400 errors:

https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZy0AELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IqEBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1L3BhZ2VfY3ljbGVyX3YyLnR5cGljYWxfMjUvdGltZVRvRmlyc3RDb250ZW50ZnVsUGFpbnRfYXZnL3BjdjEtY29sZC9odHRwX19fYWxscmVjaXBlcy5jb21fUmVjaXBlX1B1bGwtQXBhcnQtSG90LUNyb3NzLUJ1bnNfRGV0YWlsLmFzcHgMCxINU3RvcHBhZ2VBbGVydBid8RkM,agxzfmNocm9tZXBlcmZypAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InZDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX19hcnN0ZWNobmljYS5jb21fDAsSDVN0b3BwYWdlQWxlcnQYnfEZDA,agxzfmNocm9tZXBlcmZyoAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InJDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX19jb2xvcmFkby5lZHUMCxINU3RvcHBhZ2VBbGVydBid8RkM,agxzfmNocm9tZXBlcmZy5gELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IrcBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1L3BhZ2VfY3ljbGVyX3YyLnR5cGljYWxfMjUvdGltZVRvRmlyc3RDb250ZW50ZnVsUGFpbnRfYXZnL3BjdjEtY29sZC9odHRwX19fZ2F3a2VyLmNvbV81OTM5NjgzX2Jhc2VkLW9uLWEtdHJ1ZS1zdG9yeS1pcy1hLXJvdHRlbi1saWUtaS1ob3BlLXlvdS1uZXZlci1iZWxpZXZlDAsSDVN0b3BwYWdlQWxlcnQYnfEZDA,agxzfmNocm9tZXBlcmZyogELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InRDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX19tb25leS5jbm4uY29tXwwLEg1TdG9wcGFnZUFsZXJ0GJ3xGQw,agxzfmNocm9tZXBlcmZypQELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IndDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX19wcmVtaWVybGVhZ3VlLmNvbQwLEg1TdG9wcGFnZUFsZXJ0GJ3xGQw,agxzfmNocm9tZXBlcmZyoQELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InNDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193YWxncmVlbnMuY29tDAsSDVN0b3BwYWdlQWxlcnQYnfEZDA,agxzfmNocm9tZXBlcmZyowELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InVDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cuYWlyYm5iLmNvbV8MCxINU3RvcHBhZ2VBbGVydBid8RkM,agxzfmNocm9tZXBlcmZy0AELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IqEBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1L3BhZ2VfY3ljbGVyX3YyLnR5cGljYWxfMjUvdGltZVRvRmlyc3RDb250ZW50ZnVsUGFpbnRfYXZnL3BjdjEtY29sZC9odHRwX19fd3d3LmJhcm5lc2FuZG5vYmxlLmNvbV91X2Jvb2tzLWJlc3RzZWxsaW5nLWJvb2tzXzM3OTAwMzA1N18MCxINU3RvcHBhZ2VBbGVydBid8RkM,agxzfmNocm9tZXBlcmZykQILEhNTdG9wcGFnZUFsZXJ0UGFyZW50IuIBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1L3BhZ2VfY3ljbGVyX3YyLnR5cGljYWxfMjUvdGltZVRvRmlyc3RDb250ZW50ZnVsUGFpbnRfYXZnL3BjdjEtY29sZC9odHRwX19fd3d3LmVjb25vbWlzdC5jb21fbmV3c19zY2llbmNlLWFuZC10ZWNobm9sb2d5XzIxNTczNTI5LXNtYWxsLW1vZGVscy1jb3NtaWMtcGhlbm9tZW5hLWFyZS1zaGVkZGluZy1saWdodC1yZWFsLXRoaW5nLWhvdy1idWlsZAwLEg1TdG9wcGFnZUFsZXJ0GJ3xGQw,agxzfmNocm9tZXBlcmZynwELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InFDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cuZmRhLmdvdgwLEg1TdG9wcGFnZUFsZXJ0GJ3xGQw,agxzfmNocm9tZXBlcmZyoQELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InNDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cuZmlmYS5jb21fDAsSDVN0b3BwYWdlQWxlcnQYnfEZDA,agxzfmNocm9tZXBlcmZyugELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IosBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1L3BhZ2VfY3ljbGVyX3YyLnR5cGljYWxfMjUvdGltZVRvRmlyc3RDb250ZW50ZnVsUGFpbnRfYXZnL3BjdjEtY29sZC9odHRwX19fd3d3LmZsaWNrci5jb21fc2VhcmNoXz9xX21vbmtleXNfZl9ocAwLEg1TdG9wcGFnZUFsZXJ0GJ3xGQw,agxzfmNocm9tZXBlcmZyqAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InpDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cuZ2FtZXN0b3AuY29tX3BzMwwLEg1TdG9wcGFnZUFsZXJ0GJ3xGQw,agxzfmNocm9tZXBlcmZyqgELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InxDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cuaHRtbDVyb2Nrcy5jb21fZW5fDAsSDVN0b3BwYWdlQWxlcnQYnfEZDA,agxzfmNocm9tZXBlcmZyoAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InJDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cuaWduLmNvbV8MCxINU3RvcHBhZ2VBbGVydBid8RkM,agxzfmNocm9tZXBlcmZysgELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IoMBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1L3BhZ2VfY3ljbGVyX3YyLnR5cGljYWxfMjUvdGltZVRvRmlyc3RDb250ZW50ZnVsUGFpbnRfYXZnL3BjdjEtY29sZC9odHRwX19fd3d3LmltZGIuY29tX3RpdGxlX3R0MDkxMDk3MF8MCxINU3RvcHBhZ2VBbGVydBid8RkM,agxzfmNocm9tZXBlcmZyoAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InJDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cubWxiLmNvbV8MCxINU3RvcHBhZ2VBbGVydBid8RkM,agxzfmNocm9tZXBlcmZysAELEhNTdG9wcGFnZUFsZXJ0UGFyZW50IoEBQ2hyb21pdW1QZXJmL2FuZHJvaWQtbmV4dXM1L3BhZ2VfY3ljbGVyX3YyLnR5cGljYWxfMjUvdGltZVRvRmlyc3RDb250ZW50ZnVsUGFpbnRfYXZnL3BjdjEtY29sZC9odHRwX19fd3d3Lm5hdGlvbmFsZ2VvZ3JhcGhpYy5jb21fDAsSDVN0b3BwYWdlQWxlcnQYnfEZDA,agxzfmNocm9tZXBlcmZypgELEhNTdG9wcGFnZUFsZXJ0UGFyZW50InhDaHJvbWl1bVBlcmYvYW5kcm9pZC1uZXh1czUvcGFnZV9jeWNsZXJfdjIudHlwaWNhbF8yNS90aW1lVG9GaXJzdENvbnRlbnRmdWxQYWludF9hdmcvcGN2MS1jb2xkL2h0dHBfX193d3cubmljay5jb21fZ2FtZXMMCxINU3RvcHBhZ2VBbGVydBid8RkM

**Comment by benshayden** [comment]
Stoppage alerts are gone.
