### ISSUE TITLE
ninjatracing display is broken by MAX_CPU_TRACK_INTERVAL_COUNT limit

### ISSUE THREAD

**Issue by randomascii** [catapult-project/catapult#2942]
Change https://codereview.chromium.org/2099103003/ added a 100,000 limit to interval counts when loading traces. Unfortunately this is not sufficient when loading traces created by ninjatracing. A build of just base works fine, but a build of the 'chrome' target throws an exception and silently (if you don't have devtools) fails to load the trace. A build of the 'all' target would be even more over the limit.

Loading ninjatracing files is an important diagnostic tool for understanding build issues. All buildbot builds contain a link to allow visualizing of the build - this is presumed to be mostly broken now.

I worked around the issue temporarily by doing a 64-bit build of Chrome with MAX_CPU_TRACK_INTERVAL_COUNT set to 1,000,000 but a better solution is needed. Suggestions:

1) Have a higher limit for 64-bit browsers
2) Have a higher limit for the type of traces created by ninjatracing - with two traces loaded I'm only using 218 MB which shows that the current limit is extremely conservative for this type of trace.

**Comment by zeptonaut** [comment]
Do the ninjatracing builds actually have CPU samples? If not, maybe it makes sense to not throw an error if the limits are exceeded. If they do, I think that we should examine what's required to increase the limit.

**Comment by zeptonaut** [comment]
Also, could you email us a trace that exhibits the problem you're seeing?

**Comment by zeptonaut** [comment]
(Closing this as duplicate of #2935, but definitely still interested in fixing this)

**Comment by randomascii** [comment]
Here's an actual build trace generate by running ninjatracing on a recent full rebuild of the 'chrome' target. The output would be perhaps twice as large if I had built the 'all' target.

[build_trace.zip](https://github.com/catapult-project/catapult/files/537682/build_trace.zip)
