### ISSUE TITLE
Rename IterationInfo to TelemetryInfo

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2943]
It seems that telemetry already uses the term "story run" to refer to the concept that "iteration" is meant to convey. If that's correct, then should we rename "iteration" to "story run"? @eakuefner @nedn

**Comment by nedn** [comment]
sgtm. But can we shorten the name to just "RunInfo"?

**Comment by benshayden** [comment]
Isn't "run" ambiguous between story run and benchmark run?

**Comment by eakuefner** [comment]
I don't there is room for this type of confusion in practice, given that RunInfo would be attached at the histogram level and have fields pertaining both to benchmarks and to stories. Brevity in naming routinely proves to be beneficial to usability, and we've had at least a couple cases where we have had to retroactively shorten too-long names (UserStory -> Story, canonicalUrlThatCreatedThisTrace -> canonicalUrl).

+1 to RunInfo.

**Comment by benshayden** [comment]
:+1: :-)

**Comment by benshayden** [comment]
I think we settled on TelemetryInfo in the context of the Histogram Pipeline doc?
