### ISSUE TITLE
Create script to merge results2 instances

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2945]
For bot workflows that use Telemetry (CT, bisect), it would be really useful to be able to merge results2s together.

@benshayden @nedn

**Comment by benshayden** [comment]
The place to implement this functionality seems to be in [valueset2html](https://github.com/catapult-project/catapult/blob/master/tracing/bin/valueset2html). Maybe we could add repeatable flags like --html=an_input_results2.html --html=another_input_results2.html --json=an_input_valueset.json --json=another_input_valueset.json ?

**Comment by nedn** [comment]
argpase can support multiple positional args as a list, so I think ```valueset2html an_input_results2.html another_input_results2.html ... --output=<..>``` seems simpler. We can just auto detect whether each input source is json or .html file.

Just want to make sure, we currently merge the results into a same column based on their label?
