### ISSUE TITLE
Add support for run-as in DeviceUtils and/or AdbWrapper

### ISSUE THREAD

**Issue by jbudorick** [catapult-project/catapult#2948]
(not sure which of the two it belongs in yet)

We should add support for run-as <package name> to devil to support the more nuanced permissions and selinux controls present in recent android versions.

cc @case540 @randalnephew @perezju

**Comment by jbudorick** [comment]
More context: https://bugs.chromium.org/p/chromium/issues/detail?id=593720#c13

**Comment by jbudorick** [comment]
Leaning toward adding a run_as kwarg to DeviceUtils.RunShellCommand.

**Comment by jbudorick** [comment]
also, cc @agrieve

**Comment by perezju** [comment]
Still missing some context, what would this "run_as" option do?

**Comment by jbudorick** [comment]
It wrap the shell command w/ Android's [run-as](https://android.googlesource.com/platform/system/core/+/master/run-as/run-as.cpp#35) command. (I don't immediately see any non-code documentation for it, unfortunately.)

You'd do something like:

```python
device.RunShellCommand(['mkdir', 'files'], run_as='org.chromium.content_shell_apk', check_return=True)
```

and the resulting adb command would be (% RunShellCommand's modifications)

```shell
adb -s <serial> shell run-as org.chromium.content_shell_apk mkdir files
```

**Comment by perezju** [comment]
Neat, sounds good! I feel that it belongs to DeviceUtils.
