### ISSUE TITLE
Metric side panel showing "Zero values"

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2951]
To reproduce:
Download
[Before.html.zip](https://github.com/catapult-project/catapult/files/544574/Before.html.zip)
Open the file in dev server.
Choose "cpuTimeMetric".

Chrome version:  54.0.2840.71 (64-bit) on
OS: Mac

@benshayden @eakuefner

**Comment by benshayden** [comment]
https://codereview.chromium.org/2444513002
