### ISSUE TITLE
Dashboard: Add memory infra specific test picker UI

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#2954]
It is quite hard (even for domain experts) to select the right set of graphs to investigate memory regressions via the https://chromeperf.appspot.com/report UI. This is mostly because memory-infra has so many graphs which relate in complicated ways and we forced them to fit into the existing model.

We have some ideas about a UI that might work better for us and great if we could experiment on a special 'memory infra report page' rather than generalising ahead of time and trying to build the one test picker to rule them all.

**Comment by benshayden** [comment]
Archiving. V2SPA redesigns this.
