### ISSUE TITLE
Page does too much filesystem work

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2960]
While fixing #2429 I noticed that my patch makes telemetry_perf_unittests time out on Windows. @nedn suspects that it's due to #1955 which is possible because `Page.display_name`, which my patch causes us to execute much more frequently, does filesystem actions.

In any case, we should memoize `Page.display_name` since the fields of `Page` on which it relies are immutable.

**Comment by nedn** [comment]
How is  page.display_name  doing too much filesystem work?

**Comment by eakuefner** [comment]
Actually, I misread the code; it's using os.path but not actually touching the filesystem. I'll just close this bug and file a new one once we can figure out the root cause of this in more detail.
