### ISSUE TITLE
Allow ES6 short-hand property or method names?

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2963]
[Object_initializer#New_notations_in_ECMAScript_2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015)
[compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Browser_compatibility)

I'm thinking of the dictionaries returned from the callbacks passed to tr.exportTo(), which always look like {foo: foo}.
I have seen a bad copy-paste like {fii: foo} in codereview, which would be prevented if those dictionaries used short-hand properties like {foo}.
Also, variables longer than 38 chars wouldn't require 2 lines like [this](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/value/diagnostics/related_histogram_breakdown.html#L127).

Do we support IE or Safari? They don't support new object literal notations.

@zeptonaut @eakuefner

**Comment by zeptonaut** [comment]
Nope, we don't support IE or Safari, so lack of compatibility there is okay. Our general rule is "if it's in the standards and supported in Chrome, go for it". This is also encouraged in the [airbnb style guide here](https://github.com/airbnb/javascript#es6-object-shorthand), so my vote is to go for it.
