### ISSUE TITLE
Perf Dashboard: Nudge UI is hard to use

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2964]
Chrome version: 54.0.2840.71 (Mac)
URL: https://chromeperf.appspot.com/report?sid=acd845b38f455fc74479a3fc52eb74f6b8187b870ba1955cb717a256f3c5f32e&start_rev=1476807204&end_rev=1477710789

There are two things here:
1) When I change the nudge level the point doesn't always move and often gets stuck.
This seems to be an actual bug, I see the following in devtools

> Uncaught TypeError: Cannot set property 'start_revision' of null(…)
> chart-container.html:1899 Uncaught TypeError: Cannot set property 'start_revision' of null(…)
the failing code is:
`alertInfo['start_revision'] = event.detail.startRev;`

2) I cannot map the SHA1 of the nudge to any point in the dashboard. What is that supposed to be?

**Comment by anniesullie** [comment]
@eakuefner @jessimb - another one for Jessi's project to improve perf sheriffing.
