### ISSUE TITLE
memory.top_10_mobile_stress 

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2965]
Hey I am sheriffing today and I see quite some alerts coming from memory.top_10_mobile_stress
I couldn't find an owner for that in the spreadsheet. I think is one of the benchmarks that we ended up owning because of legacy.
Considering that we (memory-infra) are planning to migrate memory.top_10_mobile (what currently used for android system health) to just system_health, should we also start dropping this memory.top_10_mobile_stress ?

@perezju @anniesullie @nedn opinions?

**Comment by perezju** [comment]
We (I?) own `memory.top_10_mobile_stress`. The idea of that test is to run for some long-ish amount of time without restarting the browser, thus giving us coverage to catch memory leaks. Which we do not have elsewhere.

It has a similar purpose to `memory.long_running_dual_browser_test`, but that one uses both webview and chrome at the same time. It may be ok to drop some of these benchmarks, but we should definitely keep some form of testing for this scenario.

**Comment by primiano** [comment]
Ah ok sorry for my brainfart. I mistakenly thought this was one of the legacy benchmarks before we even started memory-infra.
Only one question: how will this long fit into the let's "move to system health" picture ?

**Comment by perezju** [comment]
Numbers from this benchmark are not used at all for Android System Health, so it's largely an ortogonal issue. After the switch to system health we can stop running and monitoring `memory.top_10_mobile`, but we would still need `memory.top_10_mobile_stress` (or something like it).

Not sure if a "stress" version of the system health benchmark would be appropriate? That probably needs a bit more thinking.

**Comment by nedn** [comment]
The "stress" is only about it being a long running story, isn't it? It's within our plan to add a long running system health story.

**Comment by perezju** [comment]
True. We do have a few already:

* long_running:tools:gmail-background
* long_running:tools:gmail-foreground

Each taking about 4-5 minutes. While we're looking for something more in the order of maybe 1 hour? Would we be happy with adding a 1-hour or longer story to system health?

**Comment by nedn** [comment]
IMO, 1-hour is a bit too much. Have we ever get good value from this long running story given that bisect doesn't work well with it?

**Comment by picksi** [comment]
The Android long-running test gave good information on stability and memory
leaks. Nothing directly actionable but it acted as a barometer when
something went wrong.

Simon

**Comment by nedn** [comment]
@picksi, those are fair points. Though I think for now let keep this 1 hour long running benchmark separately since it's currently architected to work around the problem that we can't have 1 hour long tracing.

**Comment by perezju** [comment]
Obsolete issue. This benchmark no longer exists.
