### ISSUE TITLE
Perf Dashboard: bisects are failing due to infrastructure issue

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2966]
So, I started my perf sheriff shift with 112 alerts.
The first triaged ones are coming back, unfortunately they don't look encouraging.
crbug.com/661509, crbug.com/661504, crbug.com/661493 all failed with

```
Bisect failed: http://build.chromium.org/p/tryserver.chromium.perf/builders/android_nexus5_perf_bisect/builds/4311
Failure reason: the build has failed due to infrastructure failure. 
```

:-/

**Comment by anniesullie** [comment]
All of these are failing in `provision_devices` step. I'm seeing this:

https://build.chromium.org/p/tryserver.chromium.perf/buildslaves/build102-b4 - last two builds and fails flakily in 2 of previous 7 builds
https://build.chromium.org/p/tryserver.chromium.perf/builders/android_webview_arm64_aosp_perf_bisect - last two builds failed and ~10 builds eariler there is a string of 5 failures
https://build.chromium.org/p/tryserver.chromium.perf/builders/android_nexus5_perf_bisect - failed this run then had two green runs

Log output from one of the failures is just:
```
I    0.012s TimeoutThread-1-for-MainThread  [host]> /b/c/b/android_nexus7_perf_bisect/src/third_party/catapult/devil/bin/deps/linux2/x86_64/bin/adb devices
step returned non-zero exit code: 87
@@@STEP_EXCEPTION@@@
```

Is this just the failure we get when there are no devices attached? (usually I see a device_status output on the main perf waterfall). Or is this a transient failure of some sort?  Output looks different than crbug.com/660852 which is also `adb devices` failure.

**Comment by jbudorick** [comment]
It looks like something unexpected is happening in `device_recovery` -- on both the N5 and the N7 bots, it's exiting immediately after the USB reset. This (or similar) is the last line of the log:

```shell
D    1.794s Main  fcntl.ioctl(/dev/bus/usb/002/005, 21780)
```

This comes from [here](https://codesearch.chromium.org/chromium/src/third_party/catapult/devil/devil/utils/reset_usb.py?q=reset_usb.py&sq=package:chromium&l=30) and should be followed by more recovery logic; it's not yet clear to me why that's not happening.

**Comment by jbudorick** [comment]
... actually, looking closer, I have a guess. I'll send out a speculative fix in a moment.

**Comment by jbudorick** [comment]
Kicked new bisects for [crbug.com/661509](crbug.com/661509), [crbug.com/661504](crbug.com/661504), and [crbug.com/661493](crbug.com/661493)

**Comment by anniesullie** [comment]
One hasn't finished yet, but the other two completed successfully. Closing this bug. Thanks, John!
