### ISSUE TITLE
Perf dashboard incorrectly populates bisect fields for complicated story names

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2967]
A brief story ([crbug.com/658840](https://bugs.chromium.org/p/chromium/issues/detail?id=658840)):

- I started a bisect from the dashboard on the `idle:power_avg` metric of our story, named [`https://www.youtube.com/watch?v=3KANI2dpXLw?autoplay=1`](https://chromeperf.appspot.com/report?sid=74674c766cf8eac5d768508b048ab06395e3277f1e8a1bfcc54610353ec0f260&rev=426756)
- When I click "bisect" on the graph, the story filter gets prepopulated as `https...www\.youtube\.com.watch\?v.3KANI2dpXLw\?autoplay.1`. This is incorrect - when I started a bisect with this story filter, it filtered out *all* stories, including YouTube.
- As a workaround, I modified the story filter to "youtube". This caused the correct story to pass through the story filter and actually be run.
- This [new bisect](https://chromeperf.appspot.com/buildbucket_job_status/8997159303725899680) failed with error codes `[B4T_MISSING_METRIC, B4T_REF_RANGE_FAIL]`. `B4T_MISSING_METRIC` indicates that the failure was due to the fact that, when Telemetry was run, the metric on which the bisect was based could not be found. `B4T_REF_RANGE_FAIL` indicates that this failure happened on either the "good" or the "bad" revisions (or, in our case, both).
- Digging into the [buildbot STDIO](https://build.chromium.org/p/tryserver.chromium.perf/builders/mac_retina_perf_bisect/builds/1782/steps/steps/logs/stdio) for the failed run, you can see that the `idle:power_avg` metric *does indeed* exist in this run (search for `idle:power_avg` and scroll down to the bottom). However, the story name is slightly different in the test output (`https://www.youtube.com/watch?v=3KANI2dpXLw?autoplay=1`) than in the bisect job (`https___www.youtube.com_watch?v_3KANI2dpXLw?autoplay_1`).

*Next steps*
- Fix the improper escaping of the story name
- Kick off another bisect where the metric name matches the metric name actually spit out by the benchmark rather than using the default metric name prepopulated by the perf dashboard.

FYI @nedn @ro-berto @dave-2

**Comment by zeptonaut** [comment]
Clearing myself from the assignment: @dave-2 or @ro-berto, would either of you be willing to look into making sure that the perf dashboard correctly populates bisect request fields?

**Comment by anniesullie** [comment]
@eakuefner @benshayden I think we need to think about the right way to get the story name to flow through dashboard and bisect better.

@perezju as FYI

**Comment by zeptonaut** [comment]
One thing that I don't understand: on that bug, the bisect for `cpu_time_percentage_avg/https___www.youtube.com_watch?v_3KANI2dpXLw?autoplay_1` succeeded, despite having all of the same problems as `idle:power_avg/https___www.youtube.com_watch?v_3KANI2dpXLw?autoplay_1`. Something about my understanding must not be right here...

**Comment by perezju** [comment]
Where is the bisect that filtered all stories with the pre-populated story filter?

I've just ran:

    $ tools/perf/run_benchmark -v --browser=system --pageset-repeat=1 --story-filter='https...www\.youtube\.com.watch\?v.3KANI2dpXLw\?autoplay.1' battor.power_cases --also-run-disabled-tests

and it does seem to work correctly.

**Comment by perezju** [comment]
I think that the problem is not on the story filter, but in the code responsible to find the metric from the output (which has nothing to do with story filtering).

**Comment by zeptonaut** [comment]
@perezju here's the original bisect which filtered out the YouTube story: https://chromeperf.appspot.com/buildbucket_job_status/8997163445546668768

**Comment by perezju** [comment]
Maybe there is something going wrong with the quoting on arguments, plus how does `runisolatedtest.py` actually runs the command?

On [this log](https://build.chromium.org/p/tryserver.chromium.perf/builders/mac_retina_perf_bisect/builds/1780/steps/Gathering%20reference%20values.Performance%20Test%201%20of%205/logs/Captured%20Output) from that bisect it can be seen that the story filter did arrive correctly quoted:

     /usr/bin/python2.7 /b/c/b/mac_retina_perf_bisect/src/tools/perf/run_benchmark -v --browser=release --output-format=chartjson --upload-results --pageset-repeat=1 --also-run-disabled-tests --story-filter='https...www\.youtube\.com.watch\?v.3KANI2dpXLw\?autoplay.1' battor.power_cases --output-dir=/tmp/perf-test-outputCAbasv

And running a similar command on my machine (with the same story filter) does work as intended.

**Comment by nedn** [comment]
Oh, for those bisect, I believe Charlie was setting the `"--story-filter"` command manually.

**Comment by perezju** [comment]
I think there are two issues at play:

1. Auto-populated story-filter for complicated stories may cause all stories to be filtered out. Example: [log](https://build.chromium.org/p/tryserver.chromium.perf/builders/mac_retina_perf_bisect/builds/1780/steps/Gathering%20reference%20values.Performance%20Test%201%20of%205/logs/Captured%20Output)

2. With manually selected story filter (just "youtube"), the filtering does work, but bisect is unable to find the metric in the output. (Unrelated to story filtering at all).


Re issue 1, I'm not sure exactly how runisolatedtest.py works, but the following also works on my machine (where `$SRC` points to a chromium checkout, and the current directory is on an infra checkout):

     ./runisolatedtest.py --test_name "" --checkout_dir $SRC $SRC/tools/perf/run_benchmark -- /usr/bin/python $SRC/tools/perf/run_benchmark --browser=system --pageset-repeat=1 --also-run-disabled-tests --story-filter='https...www\.youtube\.com.watch\?v.3KANI2dpXLw\?autoplay.1' battor.power_cases

**Comment by perezju** [comment]
Part 1 of this issue is now tracked at [crbug.com/662472](https://bugs.chromium.org/p/chromium/issues/detail?id=662472), which I'm working on now. Will post updates here as well.

If part 2 is also an issue, that would merit filing a separe bug.
