### ISSUE TITLE
--verbose flag does not work with adb_profile_chrome

### ISSUE THREAD

**Issue by sunnyps** [catapult-project/catapult#2975]
sunnyps@sunnyps-linux:~/src/chromium/src$ build/android/adb_profile_chrome --browser chromium --time 10 --perf --verbose
No handlers could be found for logger "devil.utils.cmd_helper"

I got verbose logging to work by adding logging.basicConfig() to systrace/profile_chrome/main.py:87 before logging.getLogger().setLevel(logging.DEBUG)

**Comment by jbudorick** [comment]
this'll be a two-part fix:
 - making devil silent if the client script doesn't set up logging
 - making adb_profile_chrome set up logging, basically by landing your workaround
