### ISSUE TITLE
[Results2] Allow increasing the width of the metric name column

### ISSUE THREAD

**Issue by ulan** [catapult-project/catapult#2979]
Currently metric names are cropped if they are too long. This makes the some results unreadable (see screeenshot).

![screenshot from 2016-11-07 16 19 18](https://cloud.githubusercontent.com/assets/294429/20063088/3f3594b8-a506-11e6-9850-17cd0d7e4c3c.png)

**Comment by anniesullie** [comment]
@benshayden is this a dupe of #2946 ?

**Comment by eakuefner** [comment]
@anniesullie Whoops, yes it is.
