### ISSUE TITLE
Tracing error: "ColorScheme is not defined"

### ISSUE THREAD

**Issue by progers** [catapult-project/catapult#2983]
In Chrome, I get the following error when using about:tracing:
Tracing error: "ColorScheme is not defined"

I think this may be related to the following recent commit:
https://github.com/catapult-project/catapult/commit/7c46a7e394ed53f69e5fef922db557f886e82a96

(Filed in Chrome under https://crbug.com/662301)

**Comment by vmpstr** [comment]
Currently this makes it not possible to view a trace on mac on canary for me, so I think this is important to fix.

**Comment by anniesullie** [comment]
@Apeliotes can you take a look?

**Comment by progers** [comment]
This was just fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=662301.

Should be in tomorrow's canary.

**Comment by progers** [comment]
I am still getting errors when using tracing in canary and tip-of-tree builds:
Cannot read property 'getColorIdForReservedName' of undefined TypeError: Cannot read property 'getColorIdForReservedName' of undefined

**Comment by progers** [comment]
For folks blocked by this: you can work around this by adding an early return in model_track.html as the first line of drawVSyncHighlight.
