### ISSUE TITLE
Perf Dashboard: /report?end_rev is being ignored.

### ISSUE THREAD

**Issue by agrieve** [catapult-project/catapult#2986]
E.g.:
https://chromeperf.appspot.com/report?sid=f8be4459943df7093c2c0cdfa83b9350c742c4da55093717a3f0633ac95b5e2a&num_points=150&end_rev=051a90313eb6f6851bb463e415d73d8556d3366d

According to the [docs](https://github.com/catapult-project/catapult/blob/master/dashboard/docs/pages-and-endpoints.md), end_rev= should do something.

I also tried using the chromium commit number, but no difference.

I'd really like this to work, so that I can point people to the apk size graph showing their commit.

**Comment by anniesullie** [comment]
A couple of things going wrong here:

  1. The `end_rev` needs to be combined with a `start_rev`, like so: https://chromeperf.appspot.com/report?sid=f8be4459943df7093c2c0cdfa83b9350c742c4da55093717a3f0633ac95b5e2a&num_points=150&end_rev=430517&start_rev=430510
  2. The `end_rev`, `start_rev` and `rev` params need to be the "Point id" from the tooltip

Note if you want it to be centered around the commit you can use the `rev` param like this: https://chromeperf.appspot.com/report?sid=f8be4459943df7093c2c0cdfa83b9350c742c4da55093717a3f0633ac95b5e2a&num_points=15&rev=430517

I'll send out a CL to update the documentation.
