### ISSUE TITLE
Use individual power samples for power metrics, one sample per UE for energy metrics

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2990]
Currently, we have only one sample per trace in the histogram for both power and energy metrics. This should be changed so that instead we have:

- For power metric, one sample in histogram for each power sample in the given region.
- For energy metrics, one sample in histogram for each UE with the given title.

**Comment by benshayden** [comment]
Why?

**Comment by zeptonaut** [comment]
To follow up about why: this allows `story:power_min` to tell people what the minimum instantaneous power draw was throughout the story, and `story:power_avg` to tell people what the average power draw was throughout the story, etc.

Alex had actually already made these changes to all metrics except for the story:power metric, which got missed.
