### ISSUE TITLE
Perf Dashboard: edit_sheriffs not listing all monitored tests?

### ISSUE THREAD

**Issue by phoglund** [catapult-project/catapult#2993]
Chrome version: 54.0.2840.90 (Linux)
URL: https://chromeperf.appspot.com/edit_sheriffs

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
No errors.

Please describe the problem:
1). I go to edit_sheriffs and edit the WebRTC rotation. I add
  ChromeOSVideo/*/video_WebRtcCamera/*
  ChromeOSVideo/*/video_WebRtcPeerConnectionWithCamera/*
2) I click submit. The page says it added a bunch of tests:
Added tests
ChromeOSVideo/cros-peach_pit/video_WebRtcCamera/total_num_frames_640x480
ChromeOSVideo/cros-veyron_jerry/video_WebRtcCamera/total_num_frames_1280x720
ChromeOSVideo/cros-cave/video_WebRtcPeerConnectionWithCamera/frozen_frames
ChromeOSVideo/cros-nyan_big/video_WebRtcCamera/frozen_frames_1280x720
ChromeOSVideo/cros-auron_paine/video_WebRtcPeerConnectionWithCamera/frozen_frames
ChromeOSVideo/cros-sentry/video_WebRtcCamera/black_frames_1280x720
ChromeOSVideo/cros-veyron_jaq/video_WebRtcPeerConnectionWithCamera/total_num_frames
ChromeOSVideo/cros-glimmer/video_WebRtcPeerConnectionWithCamera/black_frames
ChromeOSVideo/cros-cyan/video_WebRtcPeerConnectionWithCamera/frozen_frames
...

3). I reload edit_sheriffs and click List Monitored Tests. I would expect the recently added tests above to be in the list, but there are no ChromeOSVideo tests at all. are the tests monitored or not?

Here is an example test I'm trying to get under monitoring:
https://chromeperf.appspot.com/report?sid=170c4613c1176d884f35ee4ec42def6a2d6e39306a7ab88dc94f0cd07e1d85b0

**Comment by phoglund** [comment]
Ping

**Comment by phoglund** [comment]
Ping

**Comment by phoglund** [comment]
I think I know why this happens: another sheriff rotation was already picking up the alerts.

The above behavior is still buggy and confusing; edit_sheriffs should not say it added the tests when it actually didn't.

**Comment by anniesullie** [comment]
This is a pretty big edge case, trying to sheriff the same test under two rotations.

In the long term, we are moving in a direction where the test will configure its monitoring when it is uploaded, so that things like this will be clearer.

I think we can close this for now?

**Comment by phoglund** [comment]
Fair enough.
