### ISSUE TITLE
after_load:power and idle:power not being reported 

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2994]
([perf dashboard link](https://chromeperf.appspot.com/report?sid=f7b87aa77382a21b2b02a1f33c215dab467cfc5e2b91039dbf76196ee59cd3d2&start_rev=421483&end_rev=430930&rev=426756), [example trace link](https://console.developers.google.com/m/cloudstorage/b/chrome-telemetry-output/o/trace-file-id_0-2016-11-09_07-40-35-38380.html))

It looks like, since 10/27, idle:power_avg is no longer being reported for any story:

![gy3htbt0u3v](https://cloud.githubusercontent.com/assets/1407397/20149949/72d437a8-a681-11e6-87be-7e2039bd113e.png)

It looks like this is happening even though we're getting (at least some) RAIL stages, as evidenced by this screenshot of the example trace:

![jf4hr6x5hoj](https://cloud.githubusercontent.com/assets/1407397/20149904/4208b3ba-a681-11e6-9bc0-6dbf6ff4fc3b.png)

@Alex319, this is pretty scary. Can you take a look at this ASAP?

**Comment by Alex319** [comment]
Just going through old bugs to check their status. Just checked dashboard and it appears this bug was fixed a while ago.
