### ISSUE TITLE
Data stoppage alert leads to graph with no data

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2996]
I have about ten graphs (one example below) from data stoppage alerts that show no data whatsoever when I view them. I'm logged into my Chromium account.

https://chromeperf.appspot.com/report?sid=53e7459c3c0730e175a5d0c4c5a8ef30e97bee3c7ac5fa924958e3dc601db48f

**Comment by anniesullie** [comment]
It actually has a single data point, which is really hard to see in the graph UI. I'm not sure the best way to deal with this--we got 1 data point from a monitored timeseries on 10/22, then nothing else. I don't think it's really a special case?

**Comment by anniesullie** [comment]
WontFixing cause this is a weird edge case.
