### ISSUE TITLE
Upgrade to Polymer 1.0+

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#3]
Reason: Polymer 1.0+ is actively maintained (and has better performance than Polymer 0.5).

The Polymer team made a tool called polyup to automate some of the relatively straightforward parts of the process: http://polymerlabs.github.io/polyup/. Some other things will have to be done manually, as described in https://www.polymer-project.org/1.0/docs/migration.html.

**Comment by anniesullie** [comment]
@natduca @dj2 FYI about polyup

**Comment by qyearsley** [comment]
@atotic started working on this and has made two branches of catapult, `polymer10` (a full, good port of /tracing that passes all the tests) and `polymer10-dashboard`, a partway-done /dashboard port.

@chrisphn

**Comment by chrisphn** [comment]
Unfinished dashboard work is here: https://chromiumcodereview-hr.appspot.com/1791553002
