### ISSUE TITLE
GenericTable is dead code, and generic-table-view is unnecessary

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3001]
???

**Comment by benshayden** [comment]
Oh, actually, it is used in [timeline_view_metadata_overlay.html](https://github.com/catapult-project/catapult/blob/ff40d4569c8bcf2eed27ed49682e7b8198d24dc1/tracing/tracing/ui/timeline_view_metadata_overlay.html#L21), but that should use tr-ui-b-table.

GenericTable is unused, though.
