### ISSUE TITLE
500 Server Error when posting results

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#3009]
We've had an issue with our runtime stats benchmarks yesterday.
We saw a "500 Server Error. The server encountered an error and could not complete your request. Please try again in 30 seconds." during two uploads.

We run our runtime benchmarks in two configuration (default and with ignition switched on). Weirdly enough enough we've seen the error only while uploading the second set. We only upload new data every 1.5 hours.

I can provide you with a link to the failing JSON from one of our internal builders.
The following is the time data from our builder:

Start	Tue Nov 15 20:15:08 2016
End	Tue Nov 15 20:16:16 2016
Elapsed	1 mins, 7 secs

I'd be interested to see how we can prevent this infrequent errors from our side (I reparsed the JSON file locally without errors).

**Comment by anniesullie** [comment]
Based on the time elapsed, looks like we hit the 60s timeout for processing an app engine request. A link to the JSON would be very helpful. In the short term, if it's possible to break up into multiple requests it would probably work around the problem.

I'm looking through the logs for the past two days and I see a few problems that could be related to this, I believe my timestamps are US Eastern time:
2015-11-15:
17:02:15 - Request takes 72.4 seconds, deadline exceeded error from app engine
23:15:14 - Request takes 26.7 seconds, memory limit exceeded
2016-11-16:
02:15:49 - Request takes 20.9 seconds, memory limit exceeded

Scrolling back through the previous two days, I don't see any similar failures. Perhaps we're adding just a bit more data starting yesterday?

@eakuefner @benshayden I think taking a look at this JSON would give us some solid understanding of the performance of /add_point and areas for optimization as we plan to add more data. Perhaps it's possible to do something better with JSON processing that uses less memory and time. This could potentially save us app engine quota as well. I think the best way to investigate is to take the JSON from @camillobruni and pipe it through the relevant bits of /add_point code in the interactive shell to get timing data. Note that we overwrite data points if we add them with the same revision more than once, so it's okay if you actually add the data to the data store.

**Comment by camillobruni** [comment]
I think I've seen this maybe once before. Between yesterday and today we had issues with only two revisions.
We might have increased the posted data by a bit since I added some more probes yesterday (~30 sites * 4 probes = 120 more data points per config)

**Comment by eakuefner** [comment]
@camillobruni I'll reach out to you to try to get an example JSON for which this fails. It looks like Fadi has reported similar issues with the public (Telemetry-based) V8 perf tests, which makes me wonder if this is just a matter of us uploading dramatically more data than any other test to the dashboard. I'll attach the JSON output from the bug that he filed. I think that to debug this, we should use these two JSON files and upload manually to get some suitable log spew.

[v8_points.json.gz](https://github.com/catapult-project/catapult/files/617549/v8_points.json.gz)

**Comment by anniesullie** [comment]
@eakuefner he sent us the json via email on November 16. If you can't find it, let me know and I will forward.

**Comment by eakuefner** [comment]
Found it, thanks @anniesullie

**Comment by eakuefner** [comment]
Marking available to focus on histogram pipeline.

**Comment by benshayden** [comment]
I think add_histograms avoids this particular timeout by processing histogramsets in the taskqueue, which has a 10 minute timeout iirc. There's a separate crbug about a similar add_histograms timeout, in which I suggested splitting the results into multiple uploads (e.g. one POST per story, plus one for the summary).
