### ISSUE TITLE
"ref_ref" memory metric subtest on dashboard?

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3010]
@Apeliotes @nedn @perezju 

https://chromeperf.appspot.com/report?sid=110821072ed0a8a740c3e27c44b949d23844bfa6770ddbfb2f1293c9915eade8&rev=429305

The dashboard shows a disabled time-series name "ref_ref" on this chart.
Neither @Apeliotes nor I could figure out what it means.
Is the story named "ref"? Or did the dashboard get confused?

**Comment by anniesullie** [comment]
I can't figure out how that link was generated. I tried to add the ref build by hand in /report and it gave me the expected chart: https://chromeperf.appspot.com/report?sid=7f3366d2c23d489198d1157fb192e9dc5ffb84b63d5807eb43fa08e6822be935 (the sid is a hash, so it's clear I have a different set of charts than in the link in the report)

It does look like there is some confusion in code somewhere that tries to "show the ref build" when you're already looking at one chart with the ref build. But not sure where that comes from. My guess is maybe the "chart" icon on the alerts page?
