### ISSUE TITLE
Lots of "Error creating bug" when triaging alerts and cc-ing someone

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3011]
@anniesullie @Apeliotes 

I managed to create a couple of bugs, but the dashboard is fairly consistently failing to create bugs when triaging alerts, even for a single alert at a time.
Workaround: crbug.com/new

**Comment by anniesullie** [comment]
Wait, instead of working around, let's try and debug the problem. I'm going to add some additional logging, looks from the error like monorail service is failing.

**Comment by anniesullie** [comment]
Also note bisects won't automatically kick off if you don't file through the dashboard.

**Comment by anniesullie** [comment]
Okay, new version of dashboard with additional logging deployed. Please file bugs through perf dashboard and let me know if you still see problems.

**Comment by anniesullie** [comment]
Looks like this is specifically when cc-ing someone.

**Comment by benshayden** [comment]
@anniesullie mentioned offline that the html form inserts a space after the comma when trying to cc multiple people, so monorail says that " benjhayden@chromium.org" is invalid.
When building the create issue request, the dashboard should strip each element of the cc array.
Easy fix. :+1:
