### ISSUE TITLE
Alert triage bug form sets "Performance-Sheriff", which is a non-standard label

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3012]
crbug.com/new only offers "Performance-Sheriff-Regression" and "Performance-Sheriff-BotHealth", not "Performance-Sheriff".

Should monorail offer "Performance-Sheriff" as a standard label, or should the dashboard set "Performance-Sheriff-Regression" for new alert triage bugs?

@anniesullie @Apeliotes

**Comment by anniesullie** [comment]
@eakuefner I think you led the work to convert Performance-Sheriff -> Performance-Sheriff-Regression and Performance-Sheriff-BotHealth, but the bugs and dashboard were never updated to use Performance-Sheriff-Regression. Should we change the dashboard+existing bugs, or the autocomplete in crbug?

**Comment by anniesullie** [comment]
@Benhenry FYI on perf sheriff labels

**Comment by benhenry** [comment]
@anniesullie - I'm going to collect all of the labels we have on crbug.com.

This bug is specifically about updating the templates. We can do that. Which templates do we need? Performance-Sheriff seems to make the most sense, do we need $1-BotHealth as well?

**Comment by anniesullie** [comment]
We definitely need a separate label for BotHealth bugs! They are currently filed as Performance-Sheriff-BotHealth, and the labels at http://go/perfbot-sheriff are up to date. So I think the bot health sheriff is fine, it's just there's a discrepancy for regression sheriff.

**Comment by eakuefner** [comment]
@anniesullie to answer your question, yes, I think that covering regression sheriffing just slipped my mind when I was working on this.

I think that to fix the regression sheriffing rotation:

1. The dashboard will need to be updated
2. The Markdown doc will probably also need to be updated
3. All Performance-Sheriff bugs should be bulk edited to Performance-Sheriff-Regression.

Basically the same process that I took for bot health sheriffing, with the addition of the dashboard change to account for the fact that it automatically files bugs.

**Comment by anniesullie** [comment]
@eakuefner make sure you're on the same page as @benhenry for what the labels should be (or whether we should wait on having some kind of speed component hierarchy)

**Comment by eakuefner** [comment]
The consensus when we worked with laforge@ to get the labels revamped was that Performance-Sheriff-BotHealth would be for bothealth bugs and Performance-Sheriff-Regression would be for regression bugs, to address concern about the ambiguity of the Performance-Sheriff label. As a result, Performance-Sheriff isn't officially listed in Monorail.

**Comment by benhenry** [comment]
When did you last work with laforge? Let's figure out what's right for us
and do that.

If we need things officially listed in Monorail, I can help with that.

Ben

**Comment by eakuefner** [comment]
Context is in https://bugs.chromium.org/p/chromium/issues/detail?id=574545 -- looks like it was at the beginning of this year.
