### ISSUE TITLE
Perf Dashboard: Feature Request: Show intercept for a specific revision

### ISSUE THREAD

**Issue by rsesek** [catapult-project/catapult#3013]
Chrome version: 56.0.2920.0 (Mac)
URL: https://chromeperf.appspot.com/report?sid=0ad66a520656c12b27dee814adc6597fa1f7ae03c1de28ab04ddf1fd715313b8

Please copy and paste any errors from JavaScript console (Command+Option+J to open):

Please describe the problem:
This is a feature request.

When looking at perf graphs, I sometimes want to see if my CL has any effect. Currently this can only be done by scrubbing through the graph to find the build that contains the relevant revision, and this has to be done for every graph that's being inspected. It'd be nice if you could specify an intercept revision number, which could be shown as a vertical line in the graph. This would let you clearly see where your CL landed and if there are any changes in the graph as a result.

**Comment by anniesullie** [comment]
@eakuefner @Apeliotes @benshayden FYI

We are working on improving the graph UX and will definitely keep this in mind.

In the meantime, we do have another feature on the dashboard that's not what you requested, but might be useful: https://chromeperf.appspot.com/group_report?rev=XXXXX (replace XXXXX with chromium commit pos). It will show you all the performance changes the dashboard detected in timeseries the perf sheriff rotation monitors that include your CL. Of course the dashboard shows CL ranges, so your CL may not be the cause of some of the changes.

**Comment by benshayden** [comment]
Archiving.
