### ISSUE TITLE
Remove simple_mock

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3018]
This is a rehash of crbug.com/517499, which is a super old bug that has (rightly) been archived since these sorts of bugs now belong in Catapult.

TL;DR:
* `simple_mock` contains some functionality duplicated by the built-in `mock` library. It should be removed and subsumed by use of the `mock` library where appropriate
* There's a fake timer class that is misleadingly called a mock ([Fowler](http://martinfowler.com/articles/mocksArentStubs.html)) which should be renamed and moved into its own module.

**Comment by TshepoMokoena** [comment]
@eakuefner   Hi this is my first time trying to contribute to an open source project , could help me locate the code for this issue

**Comment by eakuefner** [comment]
Hi @TshepoMokoena -- you can search for files using `git grep` or GitHub's file finder: https://github.com/catapult-project/catapult/find/master which you can get to from the top-level Catapult project page. by pressing `t`. In this case, using the GitHub finder and typing the first few characters of `simple_mock` gets me to https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/testing/simple_mock.py, which is the file that this issue is talking about.

To fix this issue, you'll want to:

1. Search the rest of the code (using git grep, or the search box on GitHub) for usages of `simple_mock` and evaluate whether they can be replaced by usage of Python's `mock` library instead (use search to see examples of how we use it in Catapult, and look also at the [documentation](http://www.voidspace.org.uk/python/mock/).
2. Rename `MockTimer` to `FakeTimer` and move it alongside the other [fakes](https://github.com/catapult-project/catapult/tree/master/telemetry/telemetry/testing/fakes) that Telemetry defines.
3. Delete `simple_mock.py`.

**Comment by jacoblukose** [comment]
Can I please know the coding style guide ?

**Comment by eakuefner** [comment]
@jacoblukose https://github.com/catapult-project/catapult/blob/master/docs/style-guide.md

**Comment by alisye** [comment]
Should simple_mock_unittest.py also be deleted?

**Comment by eakuefner** [comment]
Yes. Once a module is deleted, generally its unit tests can be as well, because they're testing code that doesn't exist any more.

As well, please note that there's already partial progress on this bug in https://codereview.chromium.org/2601923002

**Comment by amalphonse** [comment]
Hello,

I am first time looking to contribute. Does this project still need help?

**Comment by eakuefner** [comment]
Thanks for your interest, but this bug is just about fixed pending a couple CLs from an external contributor that are still in flight. Assigning myself just to clarify that this bug is owned.

**Comment by eakuefner** [comment]
Archiving.
