### ISSUE TITLE
Trace Viewer: counter labels missing

### ISSUE THREAD

**Issue by skyostil** [catapult-project/catapult#3027]
Counter labels are now showing up as white rectangles in Trace Viewer:

![broken_counter_labels](https://cloud.githubusercontent.com/assets/118517/20561924/e9558254-b178-11e6-8f69-96db8b843c80.png)

**Comment by chromy** [comment]
Think I found the cause.

**Comment by chromy** [comment]
CL: https://codereview.chromium.org/2521893004/

**Comment by skyostil** [comment]
Thanks for the quick fix!
