### ISSUE TITLE
Bad interpolation of python values into JavaScript snippets

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3028]
For example:

    action_runner.ScrollPageToElement(selector='.r > a[href*="wikipedia"]')

Fails with:

    EvaluateException: UncaughtSyntaxError:
    SyntaxError: missing ) after argument list

**Comment by perezju** [comment]
Making this issue now about the more general problem:

Telemetry has various EvaluateJavascript (and related) methods that allow to run some javascript snippets in Chrome during tests. These methods are used in many places, and it’s not uncommon for clients wanting to inject some (Python) values into the code snippets that are going to be executed.

The problem is that in virtually all of the occurrences when values are injected into snippets, this is done using naive string interpolation, which fails to quote special characters in strings as noted in the example above.

After feedback on [design doc](https://docs.google.com/document/d/1lKe6qOt89WqF6W2FCBOXrHj-f3SrYXERPvZsvF_6ZzY/edit#heading=h.3pyc7rgr53b7) discussing possible solutions, I propose to proceed as follows:

1. Introduce a new module, e.g. `js_template`, with helper methods to properly interpolate Python values into JavaScript snippets.
2. Tag all areas in the (Telemetry) code that need fixing with TODO's pointing to this issue.
3. Fix outward facing methods, e.g. like `ScrollPageToElement` that take a CSS selector as a string, using the new module. But do not change any of the JavaScriptEvaluate (and related) API's yet.
4. Upgrade the relevant API's of [action_runner.py](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/actions/action_runner.py), and fix their clients. (Can be done in a mostly backwards compatible way.)
5. Upgrade the relevant API's of [web_contents.py](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/browser/web_contents.py), and fix their clients. Might need multiple CLs, introducing a new EvaluateJavaScript2, rename methods (e.g. old version to EvaluateJavaScriptDEPRECATED), switch clients, remove deprecated methods.
6. Upgrade the relevant API's of [inspector_backend.py](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/backends/chrome_inspector/inspector_backend.py) and their clients. Might also need a stepped change as above.

@nedn @natduca @chromy

**Comment by nedn** [comment]
Plan SGTM

**Comment by perezju** [comment]
Mainly remainder to self: also need to check that clients calling [page_action.EvaluateCallbackWithElement](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/actions/page_action.py#L42) are quoting correctly the argument passed as `callback_js`.

**Comment by perezju** [comment]
A CL for step 1 above is [in review](https://codereview.chromium.org/2547503002/). I've also just finished cataloging clients that need fixing within in Telemetry.

Most clients just want to interpolate values, which the proposed method in that CL already does very well.

A few others want to interpolate some piece of code *literally* within another piece of code, [for example](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/actions/scroll.py#L39):

```
self._distance_func = ('function() { return 0 + %s; }' % distance_expr)
```

where `distance_expr` is arbitrary JavaScript code. Arguably this is "not a bug" since naive string interpolation is *precisely* the correct way to paste some bit of code within another.

However, a few other clients want to interpolate both values and literals at the same time, [for example](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/backends/form_based_credentials_backend.py#L59):

```
condition = '(document.querySelector("#%s") !== null) || (%s)' % (
    self.login_form_id, self.logged_in_javascript)
```

One could do the interpolation of literals and values separately, e.g.:

```
template = '(document.querySelector({{ selector }}) !== null) || (%s)' % (
    self.logged_in_javascript)
condition = js_template.Render(template, selector='#' +  self.login_form_id)
```

but I worry that having this as two different kinds of interpolation can get awkward and confusing pretty quickly.

I've proposed as an alternative to write:

```
condition = js_template.Render(
    (document.querySelector({{ selector }}) !== null) || ({{ CODE }}),
    selector='#' + self.login_form_id,
    CODE=self.logged_in_javascript)
```

where `ALL_UPPER_CASE_FIELDS` are interpolated literally, while `regular_field_names` are interpolated as values.

Thoughts or opinions on this proposal?

**Comment by nedn** [comment]
I don't like using upper name vs lower name because it makes ABC_def unclear. Instead, can we make `{{ %code }}` interpolated literally?

**Comment by perezju** [comment]
Steps 1, 2, 3 from the plan above are all done. I'll start thinking about 4.

**Comment by perezju** [comment]
I started to work on [step 5 above](https://github.com/catapult-project/catapult/issues/3028#issuecomment-264153603), but it got really murky because of the API change needed, and how tricky it is  to be find the clients that need updating. It all gets extra confusing since, even before starting this cleanup, there were be several methods named, e.g., `EvaluateJavaScript` all with different interfaces.

So I'm planning a slight course adjustment in the plan, taking full on the suggestion made by Nat. Rather than trying to go by layers (action_runner -> web_contents -> inspector_backend), proceed as follows:

1. Create a single new consistent API available at all three levels (and add a deprecation notice to the old method names):

  - `EvaluateJavaScript2(expression, timeout=[...], context_id=[...], **kwargs)`
  - `ExecuteJavaScript2(statement, timeout=[...], context_id=[...], **kwargs)`
  - `WaitForJavaScriptCondition2(condition, timeout=[...], **kwargs)`

2. Send out email on telemetry-announce@ about plan.

3. Move all clients using the old names to this v2 API, fixing bad interpolations as we go along. This will be probably staggered in several CLs (both in catapult and chromium repo), but this time it will be easy to find all clients still using the old names.

4. When all clients have been moved, remove the old method names.

5. Send out update on telemetry-announce@.

6. Add new method names (dropping the "2"), as alias to the new API.

7. Again many CLs on both repo's to move clients back to the method names without the "2", but now with a sane and consistent API.

8. Send out final update on telemetry-announce@.

Does that sound reasonable?

**Comment by achuithb** [comment]
I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=682812 to handle this in chromeos. 

I'm planning on writing a wrapper method so we don't have to do this rename twice.

**Comment by perezju** [comment]
Ready to move on with the mass migration of clients to the v2 API (i.e. step 3 in plan above). Will probably do this in at least 5 batches as listed here: [use_deprecated_js_api.txt](https://github.com/catapult-project/catapult/files/739535/use_deprecated_js_api.txt).

**Comment by perezju** [comment]
And the migration to v2 is completed!

I'll leave things to settle for a few days, to make sure no issues were introduced, before killing the old implementations and mapping old method names to the new implementation.

Will also send a new announcement before proceeding.

**Comment by perezju** [comment]
This is now done!
