### ISSUE TITLE
Migrate from iterItems() to ES8's Object.entries and Object.values

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3031]
I'd like to approve [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) and [`Object.values()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values), which are both part of the ES8 spec. 

I know that we should generally be wary of adopting any features that are still experimental into our codebase, but:

- Both functions are already implemented in two browsers (Chrome 51 and Firefox 47). I'm fairly sure this means that they've already met the bar of "two implementations" required to *definitely* be included in ES8.
- They provide a clear benefit of allowing us to get rid of `iteration_helpers.[dictionaryLength,dictionaryValues]` and use ES6 `for... of` iteration for objects instead of `iterItems`, giving us more consistent iteration syntax regardless of the container being iterated over:

```js
// Old
tr.b.iterItems(myDict, (key, value) => {
  console.log(`${key}: ${value}`);
});

// New
for (var [key, value] of myDict.entries()) {
  console.log(`${key}: ${value}`);
}
```

@benshayden @eakuefner, are you both okay with this?

**Comment by zeptonaut** [comment]
Bah: I should have included this bug on https://codereview.chromium.org/2535353002/, which approved these.

**Comment by benshayden** [comment]
This can be closed, right?

**Comment by zeptonaut** [comment]
I'm going to keep it open and use this as the bug for any migrations that need to happen as well, if that works for you.

**Comment by benshayden** [comment]
Alex has left the team and Charlie is overloaded.
@lpy would you have time to migrate the 83 iterItems calls to Object.entries()? If not, then I can take it.

**Comment by zeptonaut** [comment]
@benshayden Alex did almost all of this before he left, and I have a CL almost ready to go that finishes his work in https://codereview.chromium.org/2714543004/, so I think I can drive this to the finish. Retrospectively, I should definitely have just asked @lpy to do this though.
