### ISSUE TITLE
Results too big to be uploaded to dashboard

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#3033]
I have recently added a test that produces a set of Histograms. Each histogram is transformed into a set of scalar values and gets uploaded to the dashboard.

It seems that we are reaching some limit when attempting to upload those results to the dashboard.
Ex link: https://build.chromium.org/p/chromium.perf/builders/Mac%2010.11%20Perf%20%281%29/builds/3660/steps/v8.runtime_stats.top_25/logs/json.output

Calling on @eakuefner @benshayden @anniesullie 

This issue might be related to issue #3009

**Comment by eakuefner** [comment]
Yup, I think this is a dupe. Let's broaden the scope of that issue and log the troubleshooting there.
