### ISSUE TITLE
Better documentation for running system health benchmark and diagnosing regressions

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3035]
(splitting off from [crbug.com/661711](https://crbug.com/661711))

For example how to run individual stories, and how to run tryjobs.

Also may be linked on bugs triaging alerts and from chrome perf graphs?

We have something about [Memory Health Plan](https://sites.google.com/a/google.com/chrome-speed-infra/home/memory-infra/memory-health-plan) here, but could be improved.

@nedn @anniesullie @primiano

**Comment by primiano** [comment]
Oh this would be great @perezju 
I just moved most of our docs into https://chromium.googlesource.com/chromium/src/+/master/docs/memory-infra
Would be great if we could have a memory-benchmark.md page that shows:
- Which benchmarks are currently running on the dashboard with links
- what do they do
- what the top-level metrics do
- how to tryjob
- how to repro locally

**Comment by nedn** [comment]
Recently @kenrussell also had the questions about how to use the perf dashboard & tracing link to diagnose a gpu regression.

**Comment by perezju** [comment]
Not sure why the CL wasn't linked. But documentation on [memory benchmarks](https://chromium.googlesource.com/chromium/src/+/master/docs/memory-infra/memory_benchmarks.md) is now available!
