### ISSUE TITLE
Plumb label through and reland convert_chart_json

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3036]
Today alexclarke@ spent ~hours reproing a benchmark and ended up with a non-functional result.html page

here's what he did:
28420  [2016-11-25 12:13:21 +0000] tools/perf/run_benchmark run --browser=release thread_times.simple_mobile_sites   --results-label=patch --also-run-disabled-tests --reset-results
28421  [2016-11-25 12:21:39 +0000] git difftool
28422  [2016-11-25 12:21:48 +0000] git commit -a --amend
28423  [2016-11-25 12:21:55 +0000] git checkout master
28424  [2016-11-25 12:22:01 +0000] cr build chrome
28425  [2016-11-25 12:26:07 +0000] tools/perf/run_benchmark run --browser=release thread_times.simple_mobile_sites   --results-label=tot --also-run-disabled-tests 

And this is what he ended up with 
[results.html.gz](https://github.com/catapult-project/catapult/files/613266/results.html.gz)

Something clearly went wrong. we were expecting two columns.
The major problem here is that other than html2 being broken, there is no way to go back to results1.
That seems to have been ripped out in https://codereview.chromium.org/2474573002 (imho with a quite aggressive timeline)

**Comment by primiano** [comment]
@eakuefner @benshayden

**Comment by benshayden** [comment]
Sorry bout that!
Chart-json doesn't contain --results-label so we forgot to plumb it through the converter.
It's a 2-line fix. :-)

**Comment by benshayden** [comment]
https://codereview.chromium.org/2531423002

**Comment by benshayden** [comment]
This should be fixed, please let us know if there are any other problems. :-)
