### ISSUE TITLE
Getting HTTP 500 sometimes when migrating test names

### ISSUE THREAD

**Issue by phoglund** [catapult-project/catapult#3038]
I ran a migration from

ChromeOSVideo/*/video_WebRtcPeerConnectionWithCamera/*

to ChromeOSWebRtcVideo/*/video_WebRtcPeerConnectionWithCamera/*

by clicking list tests and then run migration. I ran around 1:10 PM CET, 28 Nov 2016. I either get a blank page with this js error:

Failed to load resource: the server responded with a status of 500 ()

or an actual 500 page (with no further information).

I tried a few times and eventually it worked. The page gets stuck for processing so it's possible some RPC is timing out here. There was on the order of a couple hundred tests to migrate in the list.

**Comment by phoglund** [comment]
Aha, I got this now for some reason:

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c5e0a84b.397104067757099422/dashboard/migrate_test_names.py", line 115, in post
    _AddTasksForPattern(old_pattern, new_pattern)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c5e0a84b.397104067757099422/dashboard/migrate_test_names.py", line 143, in _AddTasksForPattern
    _AddTaskForTest(test, new_pattern)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c5e0a84b.397104067757099422/dashboard/migrate_test_names.py", line 167, in _AddTaskForTest
    queue_name=_TASK_QUEUE_NAME)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2506, in add
    queue_name=queue_name, transactional=transactional)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1204, in add
    return self.add_async(queue_name, transactional).get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 596, in get_result
    def get_result(self):
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.

**Comment by phoglund** [comment]
Breaking the jobs up into subtasks seems to work, a bit tedious though...

**Comment by anniesullie** [comment]
@eakuefner 

Yeah, unfortunately it depends on the amount of data being migrated; we have a hard 60s deadline for the http request and hard 60s deadlines for each datastore request. There are a couple workarounds:

1. Maybe move some endpoints to managed VMs, which have longer request deadlines (but still hard 60s datastore deadlines)
2. A larger refactor where a client page manages the requests (effectively breaking down the requests for you) and also gives you a nice UX explaining how the migration is going.

1 is a config change; we've been considering it for other reasons but probably not worth doing for just this bug. 2 is a pretty hefty refactor; on our end we'd say it shaves off an hour every few months, and it would take a solid week to implement, which doesn't work out according to this chart:
 
![is_it_worth_the_time](https://cloud.githubusercontent.com/assets/4331931/20673543/76eaad32-b553-11e6-860d-ac8c4c48acc4.png)

**Comment by phoglund** [comment]
Thanks for the explanatory xckd chart :) Could you return an error 400 instead and explain the request was too large, and that you should try breaking up the requests by hand? Or, alternatively, put that text on the migration page (e.g. NOTE: if your request fails with error 500, try migrating smaller amounts of tests).

If not, you can close this one.

**Comment by phoglund** [comment]
Related question: how long can I expect a migration job to take? I filed 6-7 jobs yesterday and have not received any emails yet, and the migrations does not appear to have executed.

**Comment by phoglund** [comment]
Wait, never mind, it did execute, but I didn't get any emails. I checked my spam folder too, nothing there. That sounds like a bug since the migration page states that  you should get emails. Sorry about being a pain in the ass here :)

Another question: my migration effectively moved tests from ChromeOSVideo to ChromeOSWebRtcVideo. How long can I expect the ChromeOSVideo master to be listed in the bot list here: https://chromeperf.appspot.com/report?sid=ec6aa222482fd0c9caca43ac70cc718ec52d050426f2366d5a9870f601f97830?

I think it will confuse our sheriffs since there's no test data in there anymore. Will it disappear by itself shortly or?...

**Comment by anniesullie** [comment]
Sorry for the belated answers here:

* We can't return a 400 if the queries will need to be broken up because we don't know how long they will take until we try to start executing them
* You should only receive emails about tests that are monitored.
* It looks like there is still quite a bit of data under ChromeOSVideo master, type `ChromeOSVideo/*/*/` into the "old pattern" textbox of the migration page to see.
* Migrations can unfortunately take a long time depending on the amount of data; you can see if they're finished running by checking the task queue in the app engine developer console.

**Comment by simonhatch** [comment]
Migrations have since been optimized and are sharded out heavily on the backend now. Going to close this out.
