### ISSUE TITLE
Arrow functions that return object literals have confusing syntax

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#3039]
```
> var foo = () => [];
> var bar = () => {};
```
Quiz time: `console.log(foo());` prints `[]` but what does `console.log(bar())` print?

> I'll
>  give
> you
> a
> second.

Like me you might have expected `{}` but actually the answer is `undefined` because the `{}` in `() => {}` is interpreted as an empty statement block from the statement form of the arrow syntax
(e.g. `() => { a(); return b(); }`). I found this a bit surprising.

Maybe we should forbid the idiom `() => {}` with a presubmit since it seems so unlikely that is actually what the author intended?

**Comment by anniesullie** [comment]
Yeah, we had problems with this during the polymer migration. @zeptonaut @eakuefner @Apeliotes (also is "Code Health" the right label for style guide/linter discussions?)

**Comment by zeptonaut** [comment]
I think this should be doable with the eslint [arrow-body-style rule](http://eslint.org/docs/rules/arrow-body-style#requirereturnforobjectliteral):

```
"arrow-body-style": ["error", "always", { "requireReturnForObjectLiteral": true }]
```

**Comment by anniesullie** [comment]
Neat! I think you could locally revert https://codereview.chromium.org/2531293002/ to test?
