### ISSUE TITLE
Ensure 'Show all' is checked when a value link to a non-source value is clicked

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3046]
This should work but doesn't: when a non-source value is clicked, we should click the show all box for the user if it's unchecked.

As an extension to this, we might consider switching to a whitelist system once this is fixed, whereby specific clicked histogram links could be added to a whitelist, and the algorithm for deciding which values to show could be extended to source values + whitelist. Then there are persistence questions; we could have this persist until refresh, or we could put it into settings with a reset button, and maybe histograms that are displayed because of being whitelisted could have an X next to them to have their rows deleted from the table one-by-one.

**Comment by benshayden** [comment]
This was fixed by 540c2319b770c51f285bf293290ff911e34adc76
