### ISSUE TITLE
Enable no-confusing-arrow rule

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3054]
In CLs like https://codereview.chromium.org/2533283003 we see folks getting confused by stuff like `x => 3 <= x`; it turns out that this is actually [prohibited by Airbnb](https://github.com/airbnb/javascript#arrows--confusing) and [has a corresponding eslint rule](http://eslint.org/docs/rules/no-confusing-arrow) which I think we should enable to mitigate this kind of confusion.

@zeptonaut @benshayden WDYT?

**Comment by eakuefner** [comment]
(And to be clear, my position on `allowParens` is `true`)

**Comment by benshayden** [comment]
👍

**Comment by zeptonaut** [comment]
SGTM!
