### ISSUE TITLE
examples/run_benchmark is broken

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3070]
Looks like benchmark_runner.ProjectConfig got deleted at some point:

```
Traceback (most recent call last):
  <module> at /Users/eakuefner/code/catapult/telemetry/examples/run_benchmark:19
    sys.exit(main())
  main at /Users/eakuefner/code/catapult/telemetry/examples/run_benchmark:13
    config = benchmark_runner.ProjectConfig(
AttributeError: 'module' object has no attribute 'ProjectConfig'
```

@Apeliotes @nedn

**Comment by benshayden** [comment]
Could this have done it?
https://github.com/catapult-project/catapult/commit/b1d2bdcb8df1fe5274df1dc6ec8627ab296263b6

Looks like it's still in project_config.py, not benchmark_runner.py?
https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/project_config.py

**Comment by eakuefner** [comment]
Yep, thanks for pointing that out! CL: https://codereview.chromium.org/2553683009

I should have put the fix in a separate CL originally :)

**Comment by eakuefner** [comment]
**Fixed**
