### ISSUE TITLE
Failure Diagnostics

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3077]
When a benchmark or story or story run fails for some reason, that information is currently only available in buildbot logs, not in results2 or the dashboard.

Results2 and the dashboard group Histograms by TelemetryInfo and the Histogram name.
Currently, only metrics know Histogram names, and only when everything succeeds.

When metrics register the list of Histogram names that they can produce #3076 , then telemetry can synthesize Failure Histograms to record the details of the failure through results2 and the dashboard.

Failure Histograms are just empty Histograms with a name and diagnostics. The details of the failure (whether it was the benchmark, story, or story run that failed, and as much of the "why" as is available) can be recorded in a new FailureInfo Diagnostic.

Failure Histograms can also contain TelemetryInfo, BuildbotInfo, and DeviceInfo diagnostics just like normal Histograms.

Merging/Collecting Failure Histograms will involve merging/collecting diagnostics: #2842 #2854

**Comment by eakuefner** [comment]
@natduca

**Comment by benshayden** [comment]
@anniesullie

**Comment by benshayden** [comment]
Failures are handled by sheriff-o-matic. #3692
