### ISSUE TITLE
Space x-axis linearly with commit positions

### ISSUE THREAD

**Issue by jessimb** [catapult-project/catapult#3086]
As discussed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=672971), a non-linear x-axis is very misleading. 

This illustrates how the revisions are spaced, with all points being equidistant regardless of how far apart the actual commits are.
![ocvaolq7c3t](https://cloud.githubusercontent.com/assets/6227957/21119819/1d44a31a-c079-11e6-81c9-90661a2ef4a2.png)

It would be more useful if we were to space the x-axis based on commit positions. This would allow us to see the anomalies on a scale that shows their true impact.

@anniesullie

**Comment by eakuefner** [comment]
Wait, is this actually what we want? In your doc that you wrote recently (currently internal), it seemed like @anniesullie suggested that this was something we were really not sure we wanted. Let's add this to the agenda for tomorrow's meeting.
