### ISSUE TITLE
system_health.memory_mobile is running on Desktop

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3089]
For example here on [Linux Perf bot](https://build.chromium.org/p/chromium.perf/builders/Linux%20Perf/builds/113/steps/%5Btrigger%5D%20system_health.memory_mobile%20on%20%28102b%29%20GPU%20on%20Linux%20on%20Ubuntu-14.04). Is this intended?

@nedn

**Comment by nedn** [comment]
It's triggered, but not run. The reason is we are getting away from the step of generating a list of tests before triggering the test.
@ehanley324

**Comment by nedn** [comment]
This is WAI.

**Comment by perezju** [comment]
Ah, yes, forgot about that. Thanks for the reminder.
