### ISSUE TITLE
Crash running benchmark without specifying output-format

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3091]
./tools/perf/run_benchmark --browser=release smoothness.top_25_smooth runs to completion but dumps this out:

Traceback (most recent call last):
  <module> at /usr/local/google/home/simonhatch/chromium/src/tools/perf/run_benchmark:22
    sys.exit(main())
  main at /usr/local/google/home/simonhatch/chromium/src/tools/perf/run_benchmark:19
    return benchmark_runner.main(config, [trybot_command.Trybot])
  main at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/telemetry/telemetry/benchmark_runner.py:432
    return command_instance.Run(options)
  Run at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/telemetry/telemetry/benchmark_runner.py:245
    return min(255, self._benchmark().Run(args))
  Run at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/telemetry/telemetry/benchmark.py:91
    return story_runner.RunBenchmark(self, finder_options)
  RunBenchmark at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py:357
    results.PrintSummary()
  PrintSummary at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/telemetry/telemetry/internal/results/page_test_results.py:370
    output_formatter.Format(self)
  Format at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/telemetry/telemetry/internal/results/html_output_formatter.py:53
    histograms = self._ConvertChartJson(page_test_results)
  _ConvertChartJson at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/telemetry/telemetry/internal/results/html_output_formatter.py:40
    vinn_result = convert_chart_json.ConvertChartJson(chart_json_path)
  ConvertChartJson at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/tracing/tracing/value/convert_chart_json.py:24
    js_args=[os.path.abspath(chart_json)])
  RunFile at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/third_party/vinn/vinn/_vinn.py:186
    return _RunFileWithD8(temp_boostrap_file, js_args, v8_args, stdout, stdin)
  _RunFileWithD8 at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/third_party/vinn/vinn/_vinn.py:265
    'Exception raised when executing %s:\n%s' % (js_file_path, out))
RuntimeError: Exception raised when executing /tmp/tmpQPh8KV/_tmp_boostrap.js:
/tracing/value/chart_json_converter.html:62: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
            for (var sample of value.values) {
                                    ^
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at Object.tr.b.iterItems (/tracing/value/chart_json_converter.html:62:37)
    at Object.iterItems (/tracing/base/iteration_helpers.html:173:10)
    at Object.tr.b.iterItems (/tracing/value/chart_json_converter.html:27:14)
    at Object.iterItems (/tracing/base/iteration_helpers.html:173:10)
    at Function.convertChartJson (/tracing/value/chart_json_converter.html:23:12)
    at eval (/usr/local/google/home/simonhatch/chromium/src/third_party/catapult/tracing/tracing/value/convert_chart_json_cmdline.html:17:27)
    at Object.loadHTMLFile (/usr/local/google/home/simonhatch/chromium/src/third_party/catapult/third_party/vinn/vinn/html_imports_loader.js:140:5)
    at /usr/local/google/home/simonhatch/chromium/src/third_party/catapult/third_party/vinn/vinn/d8_bootstrap.js:150:19

Running with --output-format=chartjson --output-dir=/tmp works fine.

**Comment by eakuefner** [comment]
@simonhatch to confirm, it looks like you're using chart JSON for the command that succeeds but HTML (default) for the one that fails, right? So this looks like an issue with `HTMLOutputFormatter` and not specifying an --output-dir.

**Comment by eakuefner** [comment]
@benshayden

**Comment by eakuefner** [comment]
Alright, so even with my fix I don't seem to be able to repo this locally. Simon, are you synced to HEAD? What Catapult/Chromium revision?

**Comment by simonhatch** [comment]
Sorry yes, corrected the title, running with --output-format=chartjson works fine but without crashed.

Chromium: 81892544ca67cc6ff463c7a5d58bcfadd499594d
Catapult: c78686903901261433d5abf72d94f0052524b5c7

Was ToT like 20 minutes before I logged bug.

Also got it on trybot: https://build.chromium.org/p/tryserver.chromium.perf/builders/linux_perf_bisect/builds/6935

**Comment by eakuefner** [comment]
@benshayden looked at this and figured out that it must be because the benchmark is producing an empty `ListOfScalarValues`. Should be a straightforward fix, and explains why I couldn't repro.

**Comment by eakuefner** [comment]
This is fixed.
