### ISSUE TITLE
Dashboard - Remove unused params from bisect-form.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3094]
Leaving dead parameters here is just confusing people.

Here's a config I pulled from one of the latest android_nexus5_perf_bisect runs:

{
  "bad_revision": "438202", 
  "bug_id": 674523, 
  "builder_host": null, 
  "builder_port": null, 
  "command": "src/tools/perf/run_benchmark -v --browser=android-chromium --output-format=chartjson --upload-results --pageset-repeat=1 --also-run-disabled-tests --story-filter=http.www.baidu.com.s.word.google memory.top_10_mobile", 
  "good_revision": "438197", 
  "gs_bucket": "chrome-perf", 
  "max_time_minutes": "20", 
  "metric": "memory:chrome:all_processes:reported_by_os:gpu_memory:proportional_resident_size_avg/foreground/http_www_baidu_com_s_word_google", 
  "recipe_tester_name": "android_nexus5_perf_bisect", 
  "repeat_count": "10", 
  "test_type": "perf", 
  "try_job_id": 5814849953595392
}

Bypass no-repro doesn't show up in the config.
Use archive also doesn't show up in the config.
Repeat count is sent, but pretty sure isn't used by the new MWU algorithm.
Max time(min) is also sent, but pretty sure it's ignored too. Poke around the recipe and couldn't find references to actually using it.

**Comment by simonhatch** [comment]
@dave-2 @ro-berto Can you guys confirm and I'll go remove these.

**Comment by anniesullie** [comment]
FWIW during the perfbot fixit we set repeat count for return_code bisects and it did appear to be used.

**Comment by simonhatch** [comment]
Ah yes looks like it is used if return_code bisect is specified, otherwise ignored. Maybe hide the field depending on the bisect mode.

Max time is a bit more complex, it looks like a single instance of revision_state.py:_do_test(), which calls down to perf_test.py:run_perf_test() respects the max time, but for a single batch of test runs. But if the confidence isn't high enough, it'll just end up re-running against LKGR or FKBR anyway, in effect bypassing the max_time request.

**Comment by pasko** [comment]
hey guys, if you remove repeat count, then how are we supposed to get more samples when the "Compare samples" step suggests: "significance": "NEED_MORE_DATA"

all caps, hard to resist, right?

**Comment by simonhatch** [comment]
The bisect should continue gathering samples on it's own until either it has the confidence to continue or some max threshold of tests has been reached (currently set at 20). If you see NEED_MORE_DATA in Compare Samples on the "Gathering Reference Values" step, it's usually followed by some re-testing steps until it has enough data to continue. If it's on a normal revision step comparing against LKGR/FKBR, there are 2 "Compare Samples" steps, and only one of them needs to come back with an answer to continue.

@dave-2 is the person to speak to for a much more thorough explanation
