### ISSUE TITLE
Dashboard - No android_webview_nexus6_aosp_perf_bisect option.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3096]
https://build.chromium.org/p/tryserver.chromium.perf/builders/android_webview_nexus6_aosp_perf_bisect

There seems to be a nexus6-webview bot, but no option to initiate from the dashboard. Should I add it?

**Comment by anniesullie** [comment]
@case540 FYI

Yes, please!

**Comment by simonhatch** [comment]
https://build.chromium.org/p/tryserver.chromium.perf/builders/android_webview_nexus6_aosp_perf_bisect/builds/97

Added the bot to the bot map and successfully launched a bisect against that bot via the dashboard, so closing this. If there are any problems with the bot itself, we can open new bugs.
