### ISSUE TITLE
assert.isTrue/isFalse in chai fail to display the back trace.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3097]
This makes it very difficult to determine which assertion failed in a test containing multiple isTrue/isFalse assertions. I don't know if updating chai #2164 would fix this.

Monkey patch in base/assert_utils.html in https://codereview.chromium.org/2585483002

**Comment by eakuefner** [comment]
Have you seen http://stackoverflow.com/questions/13375474/how-can-i-make-the-exception-of-chai-js-include-stack-trace-info ? I think the right thing to do is set that somewhere in base. Our Chai is new enough that it sounds like it should have this functionality.
