### ISSUE TITLE
Dashboard - Default metric for media.tough_video_cases_extra seems wrong on group_report.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3104]
Taken from https://bugs.chromium.org/p/chromium/issues/detail?id=660232

https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg3eG-yggM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg_cKavQkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgvdHqpgkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICgvY7L6woM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg_dSDugkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg_ZLmugsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICg_di6pAoM

Default metric for every graph is always the same, crowd1080_vp9.webm_seek_cold

<img width="1460" alt="screen shot 2016-12-21 at 4 45 07 pm" src="https://cloud.githubusercontent.com/assets/11619067/21407412/4728a9ca-c79e-11e6-899e-76edaa350329.png">

@perezju

**Comment by perezju** [comment]
Ah, I think I've noticed this in the past. The correct default metric actually *is* sent, as [computed in _PrefillInfo](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/start_try_job.py#L256), but the UI doesn't show it as selected on the dialog box.

@eakuefner @anniesullie who could have a look at this from the UI side of things?

**Comment by anniesullie** [comment]
@simonhatch do you have time to take a look?

**Comment by simonhatch** [comment]
Possibly later in the week, I'll keep this on my radar and if nobody picks it up I'll assign it to myself.
