### ISSUE TITLE
Dashboard - Invalid story filter default for webrtc.*

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3107]
From: https://bugs.chromium.org/p/chromium/issues/detail?id=670657

**Comment by perezju** [comment]
From [webrtc_cases.py](https://chromium.googlesource.com/chromium/src/+/master/tools/perf/page_sets/webrtc_cases.py) it looks like most webrtc page sets have a single story/page.

The only exceptions are `WebrtcAudioPageSet` which appears to be dead code (not referenced anywhere), and `WebrtcRenderingPageSet` (benchmark: `webrtc.webrtc_smoothness`, not monitored) with 2 stories.

Given this I'll just add webrtc.* benchmarks to the list of benchmarks for which `--story-filter` is never used.

@phoglund - FYI as benchmark owner.
