### ISSUE TITLE
add_point is inefficient

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3108]
I'm creating this to track progress and case studies for add_point being inefficient, which has been increasingly frequently forcing metric authors to artificially pare down data that they are uploading.

We know of three major cases to study right now:

* V8
* memory-infra (uploading a subset of summary statistics since the very beginning; resolving this is also important for @jessimb's work)
* power (see https://bugs.chromium.org/p/chromium/issues/detail?id=677869#c1)

@anniesullie

**Comment by eakuefner** [comment]
I think #3009 may be related here but we need to do more measurement and investigation to figure out what the distal cause might be, as far as uploading of V8 results is concerned.

**Comment by eakuefner** [comment]
Case study from memory where it turned out that add_point wasn't really a problem in that particular case. Nonetheless, adding this to the list to study. https://bugs.chromium.org/p/chromium/issues/detail?id=623015#c5

**Comment by eakuefner** [comment]
Got to a breakthrough here: _ValidateRowId performs a _lot_ of gets that probably should either be eliminated or moved to add_point_queue's handler.

**Comment by anniesullie** [comment]
I haven't looked at these, but ideally the validation would not be moved to add_point_queue because then we can't give an error message if validation fails. If they cannot be eliminated or moved, the gets could be batched in a get_multi().

**Comment by eakuefner** [comment]
For context, this is for last revision checks. One thing there is, I'm not sure we should be doing that for all tests? Especially if you get to a point where you're trying to process some hundreds of histograms per upload, I feel that maybe we should not be getting every touched test in the `add_point` request.

It's mostly to enforce this heuristic that, for every test, the uploaded point shouldn't be too far ahead or behind the last point. So I wonder if it would be better to check this for a limited number of tests (say, only one) instead. Given that the heuristic is pretty loose anyway, I'm not sure that we actually get much benefit by querying for so much data.

**Comment by anniesullie** [comment]
Ah, yeah, this test should only need to happen for one test at most.

**Comment by simonhatch** [comment]
Mind if I close this out? There's been a round of optimizations on add_point since this was filed.
