### ISSUE TITLE
Unify and fix chrome command line managers in catapult

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3112]
There are currently two modules to set/manage command line flags:

* [telemetry.internal.backends.android_command_line_backend](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/backends/android_command_line_backend.py)
* [devil.android.flag_changer](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/flag_changer.py)

I propose to deprecate the one contained in telemetry, and refactor its clients to use the one in devil.

We then need to update the flag changer to:
* Use `/data/local/tmp` instead of `/data/local` on eng and userdebug builds (was [crbug.com/593720](https://crbug.com/593720))
* Complain if trying to set flags to one location, but the file already exists on the other (was [crbug.com/640228](https://crbug.com/640228))

FYI - @nedn @jbudorick

**Comment by nedn** [comment]
+1 for unifying one place for managing Android commandline flags in devil.

**Comment by jbudorick** [comment]
SGTM

**Comment by sfiera** [comment]
I now get an exception at [flag_changer.py:292](https://github.com/catapult-project/catapult/blob/c76f6de23ebfaa9817b4802085e064d0f4f4ab58/devil/devil/android/flag_changer.py#L292) if I pass an empty flag (e.g. ``adb_chrome_public_command_line --google-base-url=``).

(I do this because I set my flags through a script with variables declared at the top . Usually I don't want a different base URL, so I don't set the variable, and ``--google-base-url=$(GOOGLE_BASE_URL)`` becomes an empty flag value)

**Comment by perezju** [comment]
Thanks for reporting. Just sent out for review a CL to fix this.

**Comment by perezju** [comment]
As far as I can see, there are no clients anymore:

* Sending [a full path to the command line file](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/flag_changer.py#L64) to the `FlagCanger` constructor.
* Passing [prematurely quoted flags](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/flag_changer.py#L291).

However it's hard to be sure, particularly the latter (flags often come from far far away!).

In particular, I couldn't find the bit of code that turns e.g. [`@CommandLineFlags.Add("enable-webvr")`](https://cs.chromium.org/chromium/src/chrome/android/javatests/src/org/chromium/chrome/browser/vr_shell/WebVrTest.java?l=47) (without leading dashes) eventually into a `--enable-webvr`. @jbudorick maybe you know?

Aside, and unless there is a better proposal, my plan is to turn each of those warnings into a hard failure (on two separate CLs) and hope that nothing breaks. :crossed_fingers:

**Comment by jbudorick** [comment]
@perezju that's done entirely in Java ([here](https://codesearch.chromium.org/chromium/src/base/test/android/javatests/src/org/chromium/base/test/util/CommandLineFlags.java?rcl=a6d53528275dd00edf03ddc1da5b3afdf3fa80a0&l=73)) and shouldn't interact with the file on device at all.
