### ISSUE TITLE
ChartJsonConverter is a class with a single (static) method

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3114]
Currently, we have a class called `ChartJsonConverter` which contains no state and has only one method, which is static, called `convertChartJson`. I feel like this function should just be bare, and this is reasonably common practice elsewhere in tracing.

Ned suggested in the original CL that we name files after nouns instead of verbs (hence the name `ChartJsonConverter`), but naming this particular file after a noun necessitates the dummy class. Empirically, we also have non-noun-named files, mostly for commands, like `trace2html.html`, `map_single_trace.html`, etc. So I'm wondering if we can encode a determination on this inconsistency in the style guide.

I think that we should not prescribe that names need to be nouns because that will cause functions like this, that ought to stand alone, to need to be wrapped in classes. In particular, I'd advocate for a style guide rule that talks about preferring bare functions to single-method classes. What do folks think about this?

@zeptonaut @Apeliotes @nedn @benshayden

**Comment by Apeliotes** [comment]
+1
I don't mind names being verbs as long as we have consensus, and think that single-method stateless classes should be avoided where possible.

**Comment by nedn** [comment]
IMO,
Script names should be verbs: "run_benchmark", "run_test", "trace2html", "map_single_trace"
File names should be nouns: "benchmark_runner.py", "test_runner.py", "trace_2_html_converter.html".

There is no reason why "naming [a] particular file after a noun necessitates the dummy class". In fact, why not just have a method named `Convert`, `chart_json_converted.Convert()` is clear enough. If you have many different format to convert back and forth from, you can rename the file to `results_converter.py` with methods like:
`results_converter.ConvertToChartJSONFromLegacyTelemetryResult`
`results_converter.ConvertToChartJSONFromBuildBotOutput`
...

**Comment by benshayden** [comment]
Your proposal works for python modules, but not tracing's export system. In tracing, we have a convention whereby a file named `foo.html` exports something named `foo`, so that, if somebody is wondering where `foo` is defined, they shouldn't need to run a full-text search, they can go straight to `foo.html`. Exporting `tr.v.convertChartJson()` from a file named `chart_json_converter.html` would violate this convention and make it slightly more difficult for future devs to find the definition of `convertChartJson()`.

Can you say more about why all non-script file names should be nouns? This restriction seems to make the difficult problem of naming things even more difficult.

**Comment by zeptonaut** [comment]
I lean towards Ned's point of view here. I still have minor PTSD from my past project where class/file names were apparently determined by rolling a D20, and having a hard rule to say "files that you can run look like verbs, files that are used by files that can run look like nouns". 

I don't think that there's a hard rule about 1 file === 1 export within tracing: for example, [iteration_helpers.html](https://cs.corp.google.com/github/catapult-project/catapult/tracing/tracing/base/iteration_helpers.html?q=p:github+f:%5Ecatapult-project/catapult/+iteration_helpers.html&dr&l=378). However, I do think that the places where we break this convention are often the functions that people have the hardest time finding, so I'm hesitant to start adding more places where we do break it.

I guess, to me, `tr.b.ChartJsonConverter.convert()`seems like the best option if the code needs to be shared, but I don't have an incredibly strong opinion on it as long as there's good reason behind the decision that we make.

**Comment by benshayden** [comment]
@eakuefner WDYT of Charlie's comment? If the stateless class is ok, then can you close this bug?

**Comment by eakuefner** [comment]
Archiving.
