### ISSUE TITLE
It's hard to test callers of uri.Controller

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#3118]
It's hard to test callers of [uri.Controller](https://github.com/catapult-project/catapult/blob/f51508d45a48ff3c372a2549959b5978fd261826/dashboard/dashboard/static/uri.html#L66) since it dispatches events straight to window (and its users add listeners to window) (e.g. [1](https://github.com/catapult-project/catapult/blob/1e916c1c87c895ab139ee27078dbb324b53a451f/dashboard/dashboard/elements/report-page.html#L122), [2](https://github.com/catapult-project/catapult/blob/1e916c1c87c895ab139ee27078dbb324b53a451f/dashboard/dashboard/elements/chart-container.html#L619)) two users of uri.Controller effect each-other. This is doesn't happen normally (since probably there's only ever one uri.Controller at once) but can happen in tests but only when we're running many test cases which use uri.Controller not just a single test.

This doesn't happen at the moment but I'm trying to [add a new caller of `uri.Controller`](https://codereview.chromium.org/2562443002) which also uses `chart-container` and has a test case. This test case passes but it breaks `dashboard.elements.report-page-test` when they are run together. The report-page-test runs second but events fired by its `uri.Controller` cause the first test case to try to update its `chart-container` which breaks because now it has zero height because the parent of the chart has been folded up in the results UI or something?

Anyway tests failing but only when run together seems sad but I can't think of a great solution.
Normally I would say we should should solve this removing the 'global' but then we couldn't use events, we could stop dispatching directly to window and force listeners to use `event.stopPropagation()` in the right places but that seems a bit error prone or we could remove all listeners from `window` after each test case but that seems ugly.

**Comment by anniesullie** [comment]
Would adding a thin shim class around events that we can mock help?

**Comment by chromy** [comment]
That's a good idea, something like: [https://codereview.chromium.org/2618783004]()?
