### ISSUE TITLE
Dumping logic into RequestHandler overrides makes them difficult to test

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3120]
In `AddPointHandler`, we dump a whole bunch of business logic into the `post` method, which makes it pretty difficult to test e.g. interactively in appstats.

As part of my investigation on #3009 I've been playing in appstats with `add_point`, but to get to a reasonable point where I can test, I needed to figure out how to instantiate a handler, and then how to construct a `Request` instance manually, and then finally call `Initialize` on the handler to populate the handler's request field properly.

It would have been a lot easier to do this testing if there were a simple method that I could have called with the JSON I have on hand.

Should we encourage people to put as little logic as possible in `get`/`post` methods to make testing easier when it eventually becomes necessary? In this case, I'm imagining factoring out most of the behavior of the `post` method of `AddPointHandler` to a helper that accepts a JSON string that I can call directly.

@anniesullie WDYT? I guess there are two questions here: whether the refactoring of AddPointHandler I propose sounds reasonable, and whether this is a guideline that we might like to encode in the style guide.

**Comment by anniesullie** [comment]
I think yes on both points.

**Comment by eakuefner** [comment]
Awesome! Then I think it'll be easier for me to just do this refactoring before continuing with my investigation.
