### ISSUE TITLE
Running benchmarks locally doesn't work for Android N

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#3127]
liberato@ and I (crouleau@) found Telemetry: Run Benchmarks Locally documentation (https://sites.google.com/a/chromium.org/dev/developers/telemetry/run_locally) and began to follow it.

For Android N (a Nexus 6 specifically) the run_benchmark command would only get us to the "Welcome to Chrome" page and just get stuck there. Here are the steps we took:

1. build chrome_public_apk
2. adb install -r out/my_build/apks/ChromePublic.apk
3. ./tools/perf/run_benchmark --browser=android-chromium smoothness.tough_scrolling_cases
4.We get error "WARNING:root:Cannot find path for chrome_stable on platform android_n_armeabi-v7a. Falling back to android_armeabi-v7a."
5. It sits on the "Welcome to Chrome" page and waits for the first run to complete. It sits there forever.

We downgraded the Nexus 6 to M and it started working again.

**Comment by CalebRouleau** [comment]
@eakuefner suggested writing this bug and adding @nedn and @ehanley324

**Comment by nedn** [comment]
@perezju would you work to fix the Android commandline flag fix this?

**Comment by perezju** [comment]
Yes, my planned fix in #3112 should make this work. For the moment the workaround is:

* `adb shell setenforce 0`
* `adb rm -f /data/local/tmp/chrome-command-line`
* `adb rm -f /data/local/chrome-command-line`

Then the `run_benchmark` command above should work without issues.

**Comment by perezju** [comment]
The command line issue should be fixed now, some code clean up is still needed and tracked in #3112.

Improving things around the need for setenforce are tracked in #3172.

Feel free to reopen if there are other outstanding issues.
