### ISSUE TITLE
How should WebURLLoaderImpl::Context::OnCompletedRequest be categorized?

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3133]
This event title is currently uncategorized ("other") by ChromeUserFriendlyCategoryDriver, but it can take a large amount of time, which makes breakdown bar charts difficult to use.

https://codesearch.chromium.org/chromium/src/content/child/web_url_loader_impl.cc?q=WebURLLoaderImpl::Context::OnCompletedRequest

What category can this trace event title be added to in order to make breakdown charts more useful?

(@nedn recorded a trace. Not sure if it's necessary and allowed to link to it here. Ask me or Ned if you need it?)

**Comment by benshayden** [comment]
Here's a histogram of all of these events in that trace:
http://i.imgur.com/FSCrVyh.png

**Comment by eakuefner** [comment]
By the way, you can attach images/arbitrary attachments directly to bugs.

**Comment by nedn** [comment]
@tdresser

**Comment by tdresser** [comment]
Naively, I'd say resource_loading, but I don't have much context here. @bryanmcquade?

**Comment by benshayden** [comment]
Archiving
