### ISSUE TITLE
Perf Dashboard: New Bug -> "No bisect automatically started. Invalid &#34;good&#34; revision: 1483535434."

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3143]
When sheriffing regression alerts, sometimes the New Bug button will file a bug, display that error message, but fail to start a bisect. This failure might be restricted to internal bots.

Clicking the Bisect button after filing the bug successfully starts the bisect, so this seems to be separate from the causes found in #2971 , but I'm not sure.

(As a separate but related issue, the html tag codes are displayed on screen, so maybe it's being double-escaped?)

@simonhatch , @anniesullie suggested asking you. :-)

**Comment by simonhatch** [comment]
haha nice :)

Probably the same issue, #2971 dealt with no auto-firing a bisect after New Bug, so it sounds the same but I'll grab this and look into it.

**Comment by anniesullie** [comment]
Wait, Ben, I thought the bisect **was** automatically kicked?

**Comment by benshayden** [comment]
The bisect was not being automatically kicked off when I filed the bug, but it did start when I clicked the Bisect button.

Also, I was only seeing this issue on the internal bots, which use git hashes instead of revision numbers, IIUC.
