### ISSUE TITLE
trace2html files always give "Could not find an importer for the provided eventData." on import

### ISSUE THREAD

**Issue by randomascii** [catapult-project/catapult#3147]
I've just tried running trace2html on three different .json.gz files saved by chrome://tracing, using both canary and stable to save and try loading the results. In all three cases when loading the .html file I got:

Import error
Could not find an importer for the provided eventData.

One of the json.gz files, saved from canary with virtually zero tabs open, is attached.

[trace_test.json.gz](https://github.com/catapult-project/catapult/files/713031/trace_test.json.gz)

**Comment by anniesullie** [comment]
@benshayden Can you take a look?

**Comment by benshayden** [comment]
Confirmed.

Workaround: it works if you gunzip the trace json before running trace2html.

The console says
```
Error: Could not find an importer for the provided eventData.
    at Import.createImports (3147.json.html:82266)
    at Task.run (3147.json.html:22086)
    at runAnother (3147.json.html:22179)
    at runTask (3147.json.html:21811)
    at processIdleWork (3147.json.html:21855)
    at window.requestIdleCallback.timeout (3147.json.html:21791)
```
which points to [this line](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/importer/import.html#L151)
```
        if (traces.length && !this.hasEventDataDecoder_(importers)) {
          throw new Error(
              'Could not find an importer for the provided eventData.');
        }
```

There aren't any suspicious recent changes in tracing/tracing/importer. There are a few recent changes in extras/importer that could possibly be related, but no smoking guns.

I added a printf to hasEventDataDecoder_ to figure out why the workaround works.
If you gunzip the trace before running trace2html, then the Importer finds the GzipImporter (whose isTraceDataContainer() returns true and whose gzipData_ is 254557 octets long) as well as the TraceEventImporter (whose isTraceDataContainer() returns false).
If you pass your gz directly to trace2html, then the importer only finds the GzipImporter, and its gzipData_ is 278296 octets long.

I started reading trace2html.py, and I'm not sure it actually can accept gzipped traces.
I think it might be double-gzipping when the input is already gzipped. I think it should be using [`try: GzipFile(filename, 'r')`](http://stackoverflow.com/questions/3703276/how-to-tell-if-a-file-is-gzip-compressed).
I'll try that in the morning.

**Comment by benshayden** [comment]
@randomascii If you git pull in catapult, this should be fixed now. Please re-open if not. Thanks!

**Comment by randomascii** [comment]
I tested and the problem is fixed, although it has not yet made it to canary.

I found that I had to save the trace with a fixed browser - loading it with a fixed browser was insufficient.

Are there any tests to prevent this or some similar bug from returning? trace2html support is an important scenario.
