### ISSUE TITLE
results.html broken for system_health.memory_desktop

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#3148]
For example the following command:

```
tools/perf/run_benchmark run system_health.memory_desktop \
  --story-filter load:search:google \
  --browser stable
```

Generates a results.html file which gets stuck on 'Loading Histogram 6000 of 9186'
with the following stack trace:

```
results.html:16471 Unrecognized unit Error: Unrecognized unit
    at Function.Unit.fromJSON (file:///usr/local/google/home/hjd/proj/chromium/src/tools/perf/results.html:12392:11)
    at Function.fromDict (file:///usr/local/google/home/hjd/proj/chromium/src/tools/perf/results.html:15071:53)
    at HistogramSet.importDicts (file:///usr/local/google/home/hjd/proj/chromium/src/tools/perf/results.html:16069:44)
    at HistogramImporter.loadSomeHistograms_ (file:///usr/local/google/home/hjd/proj/chromium/src/tools/perf/results.html:29170:26)
    at runTask (file:///usr/local/google/home/hjd/proj/chromium/src/tools/perf/results.html:16478:21)
    at processRequests (file:///usr/local/google/home/hjd/proj/chromium/src/tools/perf/results.html:16497:7)
```

This seems to be due to trying to build a histogram from a dict without a unit:

```json
{
    "storyDisplayName": "background:news:nytimes",
    "benchmarkName": "system_health.memory_mobile",
    "benchmarkStartMs": 1480078635691,
    "label": "",
    "product-version": "Chrome/57.0.2928.0",
    "storyUrl": "http://www.nytimes.com/2016/10/04/us/politics/vice-presidential-debate.html?_r=0",
    "os-version": "6.0.1",
    "storyRepeatCounter": 0,
    "storyGroupingKeys": {"case": "background", "group": "news"},
    "guid": "7e85c67e-5f4d-4a84-b100-475f5a9de42c",
    "type": "IterationInfo",
    "storysetRepeatCounter": 0
}
```

**Comment by chromy** [comment]
I'll look further today, we should probably add the unit to that histogram. @benshayden @gkraynov

**Comment by benshayden** [comment]
That's not a histogram, that's a shared diagnostic. It's confused because IterationInfo was recently renamed to TelemetryInfo. Do you need the data in that file, or can you re-run the benchmark? If you need the data, then I can alias IterationInfo for backcompat.

**Comment by chromy** [comment]
Ah I see, thanks! I was getting kind of confused looking at that json.
We can easily re-run the benchmark, but I think we're running ToT Chrome and catapult.
Should it be working currently given that configuration?

**Comment by benshayden** [comment]
ToT catapult [should not be producing](https://github.com/catapult-project/catapult/search?utf8=%E2%9C%93&q=IterationInfo) new IterationInfos.

Did you have a pre-existing results.html that contained IterationInfo before you ran the benchmark? Existing results are preserved unless you pass --reset-results to run_benchmark.

I thought of another fix instead of maintaining an alias in the code for back-compat:
`sed -e 's/IterationInfo/TelemetryInfo/g' results.html`

**Comment by chromy** [comment]
Yep that was the issue. Thanks Ben!
