### ISSUE TITLE
Allow alerts to specify bug template

### ISSUE THREAD

**Issue by agrieve** [catapult-project/catapult#3150]
This would be really useful for things like `resource_sizes` alerts, where basically none of the bugs should be Restrict-View-Google, where starting a bisect is often unnecessary, and where the most important thing is to point people a the [how to deal with these alerts](tools/perf/docs/apk_size_regressions.md) page.

**Comment by anniesullie** [comment]
@eakuefner @simonhatch

**Comment by eakuefner** [comment]
This seems like a great use case for the upcoming histogram pipeline; I'm going to make a hotlist to start collecting use cases like these.

**Comment by agrieve** [comment]
@eakuefner - Wondering where this stands in terms of roadmaps?

**Comment by eakuefner** [comment]
Thanks @agrieve, that's a good question. We're hoping to land the MVP for the histogram pipeline this quarter and start looking at further use cases in Q2. We have a collection of use cases like these that involve attaching more metadata to test results and we're hoping to service as many of them as possible using the technology that we're building right now.

**Comment by benhenry** [comment]
+1 to bug template AND GET query string per alert. Sometimes, we do not want to create a new bug template in the project, but will need to adjust some of the params using the GET query string.

**Comment by eakuefner** [comment]
@benhenry I'm a little ignorant of Monorail, so I forgot that query params are a different concept than templates, which I assume persist server-side? How are they keyed? Is there a different query param that I can pass, like ?template=XXX ?

**Comment by benhenry** [comment]
exactly, it does `?template={STRING_ESCD_TEMPLATE_NAME}`

**Comment by tdresser** [comment]
This is making perf sheriffing for sizes really painful currently. Any update here?

**Comment by anniesullie** [comment]
A related feature we've had a request for is better and more configurable bug titles. See #3414 and #2337.

@simonhatch @eakuefner should we merge the issues together?

**Comment by eakuefner** [comment]
It seems like #3414 and #2337 are asking for the same thing as each other, but not as this bug.

In particular, it doesn't seem to me like they're asking for more configuration in either case; rather just for some subtest components to be added to the bug title. I think we should coalesce those two bugs and come to a conclusion about what the right pieces to add are. @natorion has a good suggestion in #3414 whereas #2337 left off by comparing two alternatives, so maybe we can just do what @natorion suggests directly.

My point is talking about this is that I don't see either of the two mentioned bugs as blocking on the histogram pipeline, where this one definitely does.

**Comment by anniesullie** [comment]
When I look at #3414 and #2337, I see the need for user configuration. For the memory metrics, we would want to focus on the metric name and not mention the benchmark at all. For v8, we'd want to keep the benchmark name in there and extend it to a subtest.

This bug is about user configuration too, adding a template.

**Comment by eakuefner** [comment]
Sure, I buy that. So yeah, if we're willing to block #3414 and #2337 on the histogram pipeline, then we can easily incorporate those use cases into designing a solution for this problem.

**Comment by WhiteHalmos** [comment]
Is this still on the roadmap? It would be really helpful to binary size sheriffing and potentially other perf sheriffs too.

**Comment by nedn** [comment]
@dave-2 @simonhatch can you put this on service meeting next week? @anniesullie mentioned that it would help people who deal with perf bugs tremendously

**Comment by simonhatch** [comment]
Done.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917861
