### ISSUE TITLE
Add a separate option to run_benchmark to control whether to save traces.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3154]
Currently, `run_benchmark --output-format=json` has the side-effect of saving traces, and is the only way to accomplish this effect. This is undiscoverable and consistently confusing users, only most recently @shubhie .

I was about to write that it's impossible to generate html or csv results while saving traces (so you'd have to do this in two steps: `run_benchmark --output-format=json` then `run_metric`), but I just noticed that `--output-format` sets `action='append', dest='output_formats'`, so you can set `--output-format=json --output-format=html --output-format=csv`. That might be another issue, or just a TIL.

But it is impossible to save traces without generating results.json. It seems like those should be orthogonal.
Let's split the saving of traces out into an explicit option instead of implicitly bundling it in one of the output formats.

@eakuefner I think we had discussed plans along these lines, but I couldn't find a bug. Please mark this as a duplicate issue if necessary.

Should we also rename the flag to the plural `--output-formats` to indicate that it can take multiple values and so that it matches what the code calls it?

@nedn for telemetry ownership.

**Comment by nedn** [comment]
Please refer to https://github.com/catapult-project/catapult/issues/2483#issuecomment-233019161

**Comment by nedn** [comment]
Duplicate this to #2483
