### ISSUE TITLE
Instead of prefixing bugs filed from dashboard, apply a hotlist label

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3163]
Currently, when bugs are filed from the perf dashboard, we prefix them with "Perf dashboard:" which is a verbose and implicit way to tell that a bug was filed from the perf dashboard. Instead, we should probably just add them to "Hotlist:From Dashboard".

@anniesullie

**Comment by anniesullie** [comment]
The big problem is that many people filing bugs aren't project members, so the bug labels get dropped. The bugs often lack context without these labels.

**Comment by eakuefner** [comment]
Ah, not much to do here then.
