### ISSUE TITLE
Bisect can auto-assign bug to roller

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3169]
As a perf sheriff, I interpret a successful bisect as "You don't need to worry about this regression anymore until the assigned owner comments", and have sometimes missed that the assigned owner is a roller.

We should avoid auto-assigning bugs to rollers. e.g., https://bugs.chromium.org/p/chromium/issues/detail?id=685721#c5

I'm not certain all the autorollers contain "roller" in their email address, but we might be able to get away by filtering by that? Assuming no engineers have emails with "roller" in them...

Otherwise, maybe just a blacklist?

**Comment by tdresser** [comment]
@simonhatch

**Comment by simonhatch** [comment]
Definitely want to get to this, already tracking it here:
https://bugs.chromium.org/p/chromium/issues/detail?id=672130
