### ISSUE TITLE
Check SELinux mode before running Telemetry

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3172]
On Android N, some Telemetry features require SELinux mode set to 0. Bots do this automatically during device provisioning, but developers are often faced with confusing error messages when the mode is not set appropriately.

We could make Telemetry either (1) give more meaningful error messages or (2) have Telemetry itself change the mode before running.

@nedn @primiano thoughts?

**Comment by nedn** [comment]
(2) sgtm. Just need to make sure that we can revert the SELinux mode to original state if that's possible.

**Comment by jbudorick** [comment]
@perezju bots don't disable SELinux during provisioning.

**Comment by jbudorick** [comment]
(FTR, @perezju pointed out to me where we do disable SELinux during provisioning in some setups.)

**Comment by primiano** [comment]
SGTM. Just plumb a call to "adb shell getenforce".
It it says "Enforcing" (mind the capital E) we should spit out an error to the developer saying "do adb shell setenforce 0"
otherwise, it's all good if it says "Disabled" or "Permissive".

**Comment by perezju** [comment]
@primiano does the test/check need to be done always? Or only on Android N (and above)?

On an Android L device, freshly rebooted, `adb shell getenforce` returns `Enforcing`; but we don't really need to switch it to permissive there, or do we?

**Comment by perezju** [comment]
Chatted offline with primiano, we'll do the check for N and above only.

I'll also do an experiment to see if we can keep the "disable - launch Chrome - ensure it read command line - enable again" cycle tight, so other bits in Chrome do not depend on SELinux being permissive.

**Comment by jbudorick** [comment]
N+ for now SGTM.

**Comment by perezju** [comment]
This is done!
