### ISSUE TITLE
Dashboard - Update bot_whitelist?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3180]
Noticed a lot of bisects get flagged with Restrict-View that seemingly shouldn't.

Digging into this a bit, seems like bots are auto-flagged as internal_only by default, and have to be whitelisted.

Querying for bots:
SELECT * FROM Bot WHERE __key__ HAS ANCESTOR Key(Master, 'ChromiumPerf')

Yields a list of bots that probably shouldn't be internal only:

name=android-webview-nexus5X
name=android-webview-nexus6
name=chromium-rel-mac11-air
name=chromium-rel-mac11-pro
name=chromium-rel-mac12
name=chromium-rel-mac12-mini-8gb
name=win-high-dpi

Is it ok if I flip these? Looking around it sounds like I need to visit /change_internal_only afterwards to propogate this to tests.

**Comment by eakuefner** [comment]
This seems fine to me. And yes, you'll have to use /change_internal_only afterwards, which will schedule the updates to be done asynchronously.
