### ISSUE TITLE
Use a Renard Series for preferred numbers instead of the 1-2-5 series.

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#3194]
Preferred numbers are used to determine human-readable steps for labeling axes in trace viewer.

base/math.html uses the 1-2-5 series to get the closest preferred number larger than the specified minimum. This should be changed to use one of the more rounded Renard Series to pick the closest preferred number instead. R''10 would probably work well.

See https://en.wikipedia.org/wiki/Renard_series

**Comment by benshayden** [comment]
[preferredNumberLargerThanMin](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/base/math.html) is currently only used by [chart_series_y_axis](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/tracks/chart_series_y_axis.html) and [timeline_viewport](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/timeline_viewport.html).
If there might be any other clients that want to use a different preferred number series, then it might be good to parameterize the number series, possibly using a class.

**Comment by eakuefner** [comment]
Based on offline discussion, I think this bug can be closed.
