### ISSUE TITLE
Sort by delta does not distinct between regression and improvement

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3201]
Example: https://chromeperf.appspot.com/group_report?rev=375485

1.) Sort by Delta %
2.) It is sorted by the percentage. I would expect though that a 2 % regression is essentially a minus value when I sort.

E.g. sorting now:
Regression 1 %
Improvement 1.2 %
Regression 2 %

I would expect it goes from lowest (so worst from best or reverse):

Regression 2 %
Regression 1 %
Improvement 1.2 %

**Comment by anniesullie** [comment]
@simonhatch @jessimb

**Comment by simonhatch** [comment]
Makes sense, I can take a look.
