### ISSUE TITLE
Can't see more than 500 alerts

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3203]
When I open an alerts page with more than 500 alerts e.g. https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=V8%20Telemetry%20RuntimeStats, I can only see the first 500 alerts. This can be a problem if some benchmark is generating a lot of alerts (like Runtime callstats, memory benchmarks, ...)

There is a hidden expander button on the bottom. Clicking it makes another button appear. Clicking that button, nothing happens.

Would be great to display a maximum of xxx (e.g. 100) unexpanded lines instead. And when I click the button to expand, it should work :-).

**Comment by anniesullie** [comment]
@jessimb @simonhatch 

Yeah, paging of alerts definitely isn't implemented right now. In the short term, after all the recent performance fixes to alerts page, we could consider showing more than 500. @natorion do you know if there is a fixed number that might be better?

In the long term, we should implement proper paging. App engine data store supports [paged queries](https://cloud.google.com/appengine/docs/python/ndb/queries#cursors), but I think in this case we're actually already doing a query to get the length, and then dropping some. So we'd want to implement a simple paging, to be able to pull alerts 500-1000, 1000-1500, etc.

**Comment by jessimb** [comment]
+1 to paging! I like the idea of lazy loading (or clicking a button to load more) as well. From the user's perspective, being able to view more alerts at the same time is probably the better route. I can probably get to this next week.

**Comment by jessimb** [comment]
Try now :)

**Comment by natorion** [comment]
Works, thanks!
