### ISSUE TITLE
Dashboard - layered_cache.Set doesn't purge expired entities via stored_object

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3209]
Looks like layered_cache.Set() uses stored_object as a fallback when the value > 1Mb, but AFAIK doesn't store any expiry information with it. Normally values set get an expiry value and can be periodically purged via the DeleteExpiredEntitiesHandler.

**Comment by anniesullie** [comment]
Good catch! I think ideally we'd only have one system for these types of caches, it doesn't make sense to me why stored_object was written in the first case instead of just improving layered_cache.

**Comment by simonhatch** [comment]
Yeah exactly what I was gonna write another bug up proposing we consolidate these 2, there's different behaviours depending on which you use which is a bit weird (ie. memcache or no memcache, expiry or no expiry, etc.)

**Comment by benshayden** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=917853
