### ISSUE TITLE
Dashboard - Consolidate layered_cache and stored_object

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3210]
It's a bit weird to have 2 different caching systems, with different behaviours, one of which uses the other (sometimes).

Right now it looks like:

layered_cache.Set() with value < 1Mb
 - memcache -> No
 - ndb -> Yes
 - expiry -> Yes

layered_cache.Set() with value >= 1Mb
 - routes through stored_object.Set()
 - memcache -> Yes
 - ndb -> Yes
 - expiry -> No

stored_object.Set()
 - memcache -> Yes
 - ndb -> Yes
 - expiry -> No

On top of that, using layered_cache.Set() with large objects is inefficient, since every level pickles the data separately (slowly).

Seems like we should have a single api to route through that handles breaking the object up, writing to memcache, and setting expiry values.

Might even be cool to have a param on Set() that can tell the system how to refresh the cached value, so that end users potentially never even see the worst case.

**Comment by benshayden** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=917853
