### ISSUE TITLE
Improve autocomplete for memory infra metrics

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3212]
Splitting off from #2286, some examples of queries I would like to work, but they don't.

Suppose I want to find the metric:

```
memory:chrome:renderer_processes:reported_by_os:system_memory:java_heap:proportional_resident_size_avg
```

(that is: total **java_heap** used by **renderers** as seen **by the os**)

So I start typing:

![java_heap](https://cloud.githubusercontent.com/assets/16922344/22922569/3f5afdec-f296-11e6-8b69-416816aadba5.png)

Lot's of `java_heap` metrics, good, but not the one I'm looking for. So I type a bit more:

![java_heap-propor](https://cloud.githubusercontent.com/assets/16922344/22922669/a16fef7e-f296-11e6-9a42-142a04c4a5c4.png)

Only two of the metrics shown actually match my query. Still can't see the one I'm looking for.

Let's type a bit more:

![java_heap-proportional](https://cloud.githubusercontent.com/assets/16922344/22922864/35ce04b2-f297-11e6-8c65-010568cd7ea2.png)

Still only two results match my query, and most of them do not contain `java_heap` any more. My metric is nowhere to be seen.

Things I wished worked, but they don't.

![java_heap-renderer](https://cloud.githubusercontent.com/assets/16922344/22923077/f634a198-f297-11e6-8fe6-bcfcc5421efc.png)

![java_heap-by_os](https://cloud.githubusercontent.com/assets/16922344/22923126/1d41c234-f298-11e6-83a0-0d615a182d69.png)

![java_heap-renderer-by_os](https://cloud.githubusercontent.com/assets/16922344/22923187/4f4e75ec-f298-11e6-8af9-b60e15cae543.png)

My metric only becomes visible after typing all of:

```
memory:chrome:renderer_processes:reported_by_os:s
```

![java_heap-loooong](https://cloud.githubusercontent.com/assets/16922344/22923297/d9467ef2-f298-11e6-8ce0-88dd9429a7a7.png)

So today my best strategy is to type *nothing*, so at least the list of metrics is sorted in alphabetical order and I can browse through it until I find the metric I'm looking for. :disappointed: 

![type_nothing](https://cloud.githubusercontent.com/assets/16922344/22923489/97405a7c-f299-11e6-80ab-5d92736e2171.png)

@anniesullie @simonhatch @primiano @chromy

**Comment by anniesullie** [comment]
Thanks, @chromy!!

@simonhatch @benshayden Can you review the CL? At a high level I think the CL and demo look great, much more predictable behavior. The previous behavior wasn't documented and is not based on any specific requirements.

@natorion Can you take a look at the demo and let us know if it's an okay change for v8?

**Comment by natorion** [comment]
+1 to this change. Awesome! We were also wondering how the filtering works :-D

**Comment by chromy** [comment]
:flight_arrival:

**Comment by perezju** [comment]
:tada:
