### ISSUE TITLE
Monorail's 'Original alerts at time of bug-filing' link gives 400.

### ISSUE THREAD

**Issue by jessimb** [catapult-project/catapult#3214]
When bugs are filed, they automatically add the 'Original alerts at time of bug-filing' link to the Monorail bug. If there are many alerts (such as the case with [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=690358&can=1&q=status%3DFixed&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&start=100)) then clicking the link gives us the dreaded ```Error: Bad Request. Your client has issued a malformed or illegal request.``` error message. 

This was fixed in #2876 by allowing /group_report to use ?sid= (as is done in /report), which prevents the URL from being too long. However, [this code](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/file_bug.py#L177) wasn't updated to also use sid. 

To fix, we need to generate and put() a new page_state for the relevant keys and link to that instead.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917849
