### ISSUE TITLE
A telemetry tab is implemented using persistent websocket that is designed for short-lived connection

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3218]
This comes up when I am reading the code of Telemetry's tab_backend to investigate the issues related to Telemetry's startup is flaky on windows.

I think part of the reason why we can see flakes in the form of InspectorWebsocket errors is because Telemetry Tab is implemented using a persistent websocket  (connecting to devtool page's websocket) that is actually wasn't designed to be long lived.

In specific:
tab/web_content is a wrapper around [inspector_backend](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/backends/chrome_inspector/inspector_backend.py#L45) which in turn use [inspector_websocket](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/backends/chrome_inspector/inspector_backend.py#L45) to keep the connection with the devtool page.

The problem is the inspector_websocket instance inside InspectorBackend object is only connected once & reused many time, then closed when the tab is close, whereas inspector_websocket may not meant to be long lived connection as it uses the basic method websocket.create_connection() underneath ([code](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/backends/chrome_inspector/inspector_websocket.py#L64))
(see https://github.com/websocket-client/websocket-client/blob/f5fb0fcc16c4846e1f70e033d901cf93d3d6573f/README.rst#short-lived-one-off-send-receive which says `websocket.create_connection` is meant for "Short-lived one-off send-receive")

@kenrussell @zeptonaut @perezju @randalnephew

**Comment by kenrussell** [comment]
Thanks for tracking down this potential source of instability @nedn .

Should we talk with the DevTools team to see if this is likely to be a problem?

I'm concerned that if this class is changed to reconnect the DevTools socket every time, the connection costs may significantly impact the run time of tests.

**Comment by nedn** [comment]
I think we should talk with DevTools team to figure out whether we can rely on a long live socket connection between Telemetry & Devtool. Once that's answer, we can spend some time to profile the socket connection cost to see if it does affect the run time of tests.

@caseq thoughts?

**Comment by caseq** [comment]
There's no notion of short-lived vs. long long-live sockets on the protocol level, so DevTools are pretty unlikely no see any difference. What the referred fragment of the websocket-client doc appears to say is that they encourage usage of an event loop-based interface to the library instead of a synchronous one in larger apps. I generally share the sentiment that event loop provides more flexibility and opportunities for diagnostic, but it's ultimately the call of Telemetry team. What happens there looks to me like a genuine application-level timeout, though, so it's likely not related to the protocol or app model used.

**Comment by nedn** [comment]
Thanks Andrey for providing insights about socket protocol. So it seems like we can assume the socket protocol is bullet proof if the two end points are healthy?

If that's the case, I will close this bug.
