### ISSUE TITLE
group_report?rev=xxxx does not show you if bots have processed that revision already

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3220]
Currently /group_report?rev=xxxx does not show you if all bots have processed that revision already. It would be good to show which bots have not yet processed the given revision.

Challenges: Multiple projects reporting to Chromeperf have different revisions so rev=xxxx might not be sufficient. Maybe support a CL id for rev=xxxx instead?

**Comment by natorion** [comment]
That might also make more information available to the system e.g. reverts, associated projects, ...

**Comment by anniesullie** [comment]
@simonhatch @eakuefner @jessimb 

The big challenge here is that we don't actually know what repo rev=XXXX is from, so we don't know the full set of timeseries that *should* be in the report. But perhaps we could restrict to a sheriffing rotation (or a list of rotations) to understand what the list of timeseries that should be showing up are? If we did that, then we could:

* Compute how many builds have come in after XXXX
* Compare that to the min number in the alerting config
* List the ones that do not (yet) have regressions, with number of revisions and %change after XXXX?

**Comment by natorion** [comment]
Perf rotations might alert on commits from different projects e.g. the V8 perf sheriff rotation alerts on V8 bots (which have a V8 rev number) and ChromePerf ones like Speedometer (which have Chromium rev numbers). I suppose and extension of your first suggestion might be sufficient:

previous = Get all the results for rev-1
current = Get all the results for rev
If the entries in previous are <= current:
  Print OK
Else:
  Print "bots missing"
  Optional: List the ones that are missing

I have no clue though if the data would be reliable enough. In case of the addition of a benchmark the information might always show "bots missing" though. Obviously a look forward would also be possible to fix that problem.

**Comment by benshayden** [comment]
Archiving. Revision timestamps #4218 will dramatically simplify this bug.
