### ISSUE TITLE
ls /root insufficient for root testing in some circumstances

### ISSUE THREAD

**Issue by jbudorick** [catapult-project/catapult#3223]
On Pixel+N, the shell doesn't seem to be able to see anything in /root, whether it has root access or not. It exits with 0 in both cases, though. (I haven't had a chance to check other device/OS combinations.)

We need an alternate implementation of HasRoot and NeedsSU for this situation. Not immediately sure what it should be, but a few possible components include:

 - using `which which` and `which su` to determine the availability of su
 - checking `service.adb.root` for whether the device has root

@perezju thoughts?

**Comment by perezju** [comment]
:disappointed: yeah, don't have anything better to suggest, other than trying it out on several device and OS version combinaitons

**Comment by jbudorick** [comment]
@anniesullie can you add @weableandbob to catapult?

**Comment by jbudorick** [comment]
My initial thought for this would be to basically do what's recommended above:

 - check service.adb.root for whether the device has root
 - check for the existence of su w/ `which su` (and probably `which which` to make sure which exists)
 - check for the necessity of su w/ a combination of the two above: only if the device does not have root but su does exist

scoped to solely sailfish devices.

**Comment by anniesullie** [comment]
Added @weableandbob (will need to accept email invite)

**Comment by weableandbob** [comment]
The fix seems to work, as our Pixel is making it past the step where it was getting blacklisted due to permission problems.
