### ISSUE TITLE
Implement test_path_dict mode for /list_tests

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3225]
As part of solving the problem in #2887 we're implementing an endpoint that helps resolve test path dicts into lists of test paths

**Comment by eakuefner** [comment]
@anniesullie @simonhatch Just to give y'all an update on where I'm at with this today, I think it's finally time to parcel through that tricky logic in test-picker to handle the core case. I'll need to puzzle through the logic to make sure I understand it, but my goal is to generate tests from that, then do the port.

After core is implemented, I am confident that we should be able to burn down on basically all of the use cases for the endpoint, which should unblock us from completely removing the subtest dict from `test-picker`.

**Comment by simonhatch** [comment]
Awesome, thanks Ethan!

**Comment by eakuefner** [comment]
This is **done**.
