### ISSUE TITLE
Metrics in tracing_metric.html should be renamed for consistency with other metrics

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3233]
Right now, tracing_metric.html contains metrics with names like:

- `Average CPU overhead on all threads per memory-infra dump`
- `Average CPU overhead on non-memory-infra threads per memory-infra dump`
- `Max number of events per second`
- `Max event size in bytes per second`
- `Total trace size in bytes`

These are all great metric *descriptions*, but aren't consistent with other metric *names*, like `story:power`, or `css_animation:power`. We should rename the metrics in this file to have names that are more consistent with other metrics (e.g. memory, power), and use their existing names as descriptions.

@ssiddhartha @nedn @benshayden

**Comment by tdresser** [comment]
Having a central registry of metric names would be useful for a bunch of reasons, but I think it would also help with consistency here. If metric authors had to add their metric name to a list of other metric names, they'd be more likely to follow the conventions.

I agree that we should just go in and rename these though.

**Comment by nedn** [comment]
+1 for central registry of metrics. In general, I think there is a concept of "metric namespace" for test-agnostic metrics in general.

**Comment by zeptonaut** [comment]
Is anyone willing to take the lead on, for now, just renaming these metrics to something consistent with other metrics? @lpy @eakuefner @benshayden

**Comment by zeptonaut** [comment]
Thanks for doing this Ben!
