### ISSUE TITLE
Dashboard - update_test_suites.FetchCachedTestSuites

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3234]
This came out of https://codereview.chromium.org/2704663003/

We're in the middle of trying to remove a lot of usage of subtest-dict, and this is a very subtest-dict like thing, in that we're computing and storing a large expensive object and then using some subset of it. A quick poke through the datastore shows this object is split among 3 entities, making it 2-3 mb.

In that CL's case, it just wants a list of benchmarks for a given master.

There are 2 other callsites, in /report and /group_report, would be good to investigate how they're used in each case and see what we can simplify or do differently.

@eakuefner @anniesullie

**Comment by eakuefner** [comment]
Thank you for filing a bug about this, Simon. I think this would be great for one of us to pick up, and I'd be willing to look at it after I'm finished a little more finished with the subtest dict project.

**Comment by simonhatch** [comment]
So spent a bit of time today digging into this.

The suites menu is a bit complex, it wants the full list of all suites across masters/bots. For each suite, it wants to know whether there is at least one monitored test path. And it wants to know if all suites are deprecated or not.

suites = list_tests('*/*/*')
for s in suites:
  monitored = combination of top level suite.monitored for that suite
  deprecated = all suite.deprecated for that suite


Since it only wants to know if there is ANY monitored for a given suite (excluding master/bot), if you stored monitored separately from TestMetadata it'd boil down to a query.

TestMetadataMonitored:
  test = ndb.KeyProperty()
  suite = computed_property(test.split('/')[2])

Then this is as easy as TestMetadataMonitored.query(suite == 'foo').get()


Getting the deprecated status is a little more complex, since that wants to know if every suite is deprecated, so you need to query them all. Not particularly difficult, but slightly more time consuming.


If we had monitored stored separately from the TestMetadata, we could change update_test_suites to simply generate some entities like so:

SuiteData:
  suite = ndb.StringProperty()
  monitored = ndb.BooleanProperty()
  deprecated = ndb.BooleanProperty()



The bot menu doesn't use a whole lot from the test suite dict. Basically looks like this:

bots: {
  angle_perftests: {
    masters: {
      chromium_perf: {
        win: dep,
        linux: dep
      },
      chromium_perf_fyi: {
        wintest: dep
      }
    }
  },
  system_health: {
    masters: {
      chromium_perf: {
        win: dep,
        linux: dep
      },
      chromium_perf_fyi: {
        wintest: dep
      }
    }
  }
}

for bots you basically want:
  masters/bots = list_tests('*/*/suite')
  map this into dict => {
    masters: {
      bots: {
        deprecated or not
      }
    }
  }


Pasting this in the dev_console I think replicates what's being stored. Typically only have a few entities returned, so should be fairly cheap:

from dashboard import list_tests

tests = list_tests.GetTestsMatchingPattern('*/*/angle_perftests', list_entities=True)

for t in tests:
  print '%s - %s' % (t.key.id(), t.deprecated)


There's also a couple spots on the frontend, notable chart-container and chart-title which want the test suite dict in order to get whether a test is monitored, and the description.


Also looks like we might want to tackle #3930 first

**Comment by benshayden** [comment]
I think the new test suite descriptors in v2spa solves these use cases more efficiently.
