### ISSUE TITLE
Benchmark Health Report: Include data on bisects and bugs

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3237]
This is a follow up to #3224.

For the benchmark health report, we'll want to include data on bisects and bugs. If we go with @benhenry's idea of trying to understand which stages of the perf sheriffing process we are failing in (where is that image, @benhenry) I think this means that we would want to display data by bug:

* We got an alert
* It was marked invalid, or triaged into a bug
* The bug had bisects which reproed, or didn't repro, or failed
* The culprit CL was reverted or fixed, or not
* The bug was fixed or wontfixed or is still open

Getting all this data for a few hundred alerts probably can't be done fast enough in a single request, and likely the code would be less complex if we just tried to get data for a single bug per request. And then if we had an endpoint that could be used to get the data for a single request, it could also be used for other types of reporting, like "How well did bisect perform last week for the v8 memory sheriffing rotation?"

So I think we should have an endpoint that gets this data for a bug. @eakuefner @simonhatch WDYT?

I am also curious if we should have a polymer widget meant to interact with this endpoint. Things it could do:
* Provide a nice UI for the data
* Encapsulate requesting the data and parsing the response
A weird thing about having a UI is that for the benchmark_health_report use case, I'd probably want to be able to customize it to show just the bisects for a given benchmark. Not sure how to do something like that cleanly.

**Comment by anniesullie** [comment]
WIP: https://codereview.chromium.org/2706813003/

**Comment by benhenry** [comment]
https://docs.google.com/drawings/d/1BSsnrlSV7UnW3alZs4I84pbQfBPwlTW6-F7k8yBLEX0/edit

**Comment by anniesullie** [comment]
This is now **done**
