### ISSUE TITLE
How to get faster to the commit range of an alert?

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3241]
V8 performance bots run for every commit or for a small range of commits. Thus we normally don't need and support a bisect. This means the workflow for triaging V8 alerts is like this:

==========
If alert.wasRunOnV8Bots: //Thus we have run the V8 bots for every V8 revision
  alert.openReportPage
  ui.waitUntilGraphsAreLoaded
  ui.clickAlertOnFirstGraph
  ui.clickOnLink("V8 Git Hash Range")
![quicklinktothis](https://cloud.githubusercontent.com/assets/7190422/23157446/9396d8d8-f81b-11e6-950e-e200abc7439a.png)
  owner = revisionRangeWindow.getBlamedAuthor()
  alert.createIssue(owner)
  return

alert.openReportPage
alert.createIssue //triggers bisection

=========

It would be a time save and less frustrating if the link "V8 Git Hash Range" would already be displayed on the table showing the alerts like in the suggestion below (the position in the table does not matter that much, I simply needed space for the example):
![suggestion](https://cloud.githubusercontent.com/assets/7190422/23157596/2b966dce-f81c-11e6-92f3-007f6b7ce3e7.png)

I realize that the "V8 Git Hash Range" comes from our own bots and is not standardized. How about that a sheriff rotation can define those additional field which are then automatically shown on the report page if they are not null.

For the Chromium sheriffs I could image that the Chromium range might be interesting although I am not sure if they really mostly rely on bisection and never really look at the range. For V8 sheriffs displaying the V8 Git Range and the Chromium range would be interesting.

**Comment by anniesullie** [comment]
It should be doable to add a revision type for a sheriff rotation as you suggested. The only thing I noticed is that it might be confusing for users to have the "Revisions" column go to graphs when clicked, and then a second column with a revision range that links to the actual range. Any ideas on how to make that clearer?

@jessimb @simonhatch @eakuefner

**Comment by natorion** [comment]
The original is the revision range the other one is the changelog/blamelist?

**Comment by simonhatch** [comment]
Yeah having 2 revision ranges, one which goes to a graphs page and the other that goes to the actual range is pretty confusing. Kinda think it would make sense for the revision range to actually go to the range of commits, the little graph button to go to the /group_report, but then we'd need to ditch it going to /report.

Barring that, changelog sounds about right.

**Comment by benshayden** [comment]
(Trying to summarize this discussion into CL-sized pieces. Please correct me if I misunderstood, which is likely since I only had 4 hours of sleep.)

 * Change the Revisions column in the alert table to display different kinds of revisions depending on the sheriff rotation: v8 hash ranges for v8 sheriffs.
 * Change the links in the Revisions column to navigate to the revision log instead of opening /group_report
 * Change the graph icon links to navigate to /group_report instead of /report

**Comment by simonhatch** [comment]
I think the original suggestion was for there to be a changelog column for v8 sheriffs? I might have just been bikeshedding a bit in my comment, feel free to ignore it.

**Comment by anniesullie** [comment]
I think just having a changelog column which links to the changelog would be perfect. I like @benshayden's plan.

**Comment by benshayden** [comment]
@anniesullie Sorry, can you clarify? It seems like a new v8 changelog column would not be necessary if the existing Revisions column displayed v8 changes for v8 sheriffs. I don't know which would be better, but having both would be redundant, right?

**Comment by anniesullie** [comment]
I think ideally the revisions column would look like it does on the tooltip, showing the name of the revisions and the range, with a link to the viewer for the range:

v8:
![v8-tooltip](https://cloud.githubusercontent.com/assets/4331931/25919589/2762dca6-359d-11e7-9714-4aed98e5c8af.png)

chrome:
![chrome-tooltip](https://cloud.githubusercontent.com/assets/4331931/25919595/29b16072-359d-11e7-94a5-ebb1c8a1d55b.png)

**Comment by benshayden** [comment]
Showing all types of revisions would require multiple columns, then, right?

**Comment by anniesullie** [comment]
I was imagining multiple lines in a single column. But maybe we can start off simple and just use the first one?

**Comment by natorion** [comment]
The V8 changelog would already help tremendously. The others would be nice
too but lower priority.

anniesullie <notifications@github.com> schrieb am Mi., 10. Mai 2017, 22:34:

**Comment by benshayden** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=865515
