### ISSUE TITLE
Discourage clients to pass command as a string when shell features are not needed

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3242]
Borrowing from Python's own subprocess module, the safest and preferred method to specify a command and its arguments to run should be as a list.

Clients sometimes really need shell features (e.g. to expand variables or wildcards) which are only available by passing the command as a string. But the intent to use such features should be made explicit by setting a `shell=True` option.

We could start by emitting a warning if the command is passed as a string but `shell=True` is not set; and eventually turn this into an error when all clients comply.

Note, we already do this sort of signaling with soft comments [in some places](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/platform/android_platform_backend.py#L599); but would be best if it could be enforced at the code level.

@jbudorick what do you think about this proposal?

(This jumped at me again when looking into the work for [crbug.com/628617](https://crbug.com/628617))

**Comment by jbudorick** [comment]
sgtm!

**Comment by perezju** [comment]
Moved to https://crbug.com/1029769
