### ISSUE TITLE
Suggested improvements regarding chart UI

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3243]
# Behavior of a chart's legend
When comparing two metrics, the difference in the configuration is important, not the name of the actual metric being charted. It would be informative if the differentiator is used instead. See https://github.com/catapult-project/catapult/issues/3231#issuecomment-280736637 for a detailed suggestion on this.

# Snappiness of the chart
## Loading of a new chart
Depending on the data and benchmark being loaded, it can take several seconds until a chart appears. Some people complained that this takes too long. I couldn't repro it though but my subjective threshhold on this might be higher.

## Modifying an already displayed chart
What IMO really is an issue is the snappiness when a chart is already loaded: How fast does the chart react to changes: 1.) new data added 2.) revision range changed (that takes ages sometimes). The snappiness of arewefastyet is often brought up. Case 1.) probably is the same as "Loading of a new chart". For 2.) it should be possible to start prefetching revisions if chromeperf is idle?

# Browsing the commits on a chart/near an alert
If one wants to explore the commits near an alert, one is mostly out of luck. AFAIK it is simply not feasible to select a commit near an alert. It is possible to zoom in though, but that again is very cumbersome and fickly. Two different suggestions: 1.) Offer zooming the x also directly from the chart (see arewefastyet as an inspiration) 2.) Don't display the sticky alert marker directly on the graph but instead float it on the top of the chart: 
![marker](https://cloud.githubusercontent.com/assets/7190422/23168230/c7854a2c-f847-11e6-9543-fe0d15a714a7.png)

# Browsing the chart
Offer zooming the x and y axis directly via rectangle selection on the chart.

# Demystify the sticky/locked hovering information pane when a commit is selected or hovered
The behavior of the information pane is quite "surprising" or not even helping sometimes. FYI I am talking about the pane marked in the red rectangle.
![hoveringinfo](https://cloud.githubusercontent.com/assets/7190422/23168499/ad11bd8c-f848-11e6-811e-fc623a28b1d2.png)

A few suggestions:
## Plot an arrow to the commit being shown in the information pane
When investigating alerts or regressions I might display multiple charts and scroll up/down. Afterwards it is not clear anymore which commit is really shown in the information pane. Simply drawing an arrow/line from the pane to the actual commit on the graph would remove that problem.

## Keep displaying information while hovering over a commit despite another commit is pinned
Let's assume I want to investigate an alert. I am pinning that alert to the information pane. Now, I want to see the value or "Chromium Git Commit Range" of one commit before the alert. Even to get to the value I would need to click the commit before the alert thus changing the pinned commit to the other one. Theoretically I could also use the delta tool of the chart to show the difference for the value, but that does not work for the commit range. 
I think there are two issues at work here: 1.) I want to compare two commits, so I would need to pin two commits. Other solutions like simply adding the same chart twice is hard/cumbersome when one starts from the Alerts page. 2.) Always display some information while hovering over any commit (e.g. value + variance)

## Offer a way to close the pinned information pane
When I click on an alert, I see the options to triage, etc the alert. There is also a close button. Such a close button would be great on the pinned information pane too because the pane is often obstructing the chart.

**Comment by benshayden** [comment]
It looks like this was split into several bugs.
