### ISSUE TITLE
Highlight commit on the chart when group_report?rev=xxx is used

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3244]
Let's assume I want to investigate the impact of my CL. I know that I can do that with group_report?rev=12345 (and 12345 is the revision of my CL). Lots of alerts and improvements are displayed and I  start investigating them. Unfortunately, to identify my CL on a chart, I need to look for the commit by hovering over the chart. If the commit 12345 is highlighted automatically (e.g. a light yellow line on the y axis) it would be easy to spot my CL and start exploring neighboring commits.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917891
