### ISSUE TITLE
Warning about "non-overlapping commits" shown despite they are overlapping partially

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3245]
Example: https://chromeperf.appspot.com/group_report?bug_id=671172

It seems that the "non-overlapping commits" warning is show when both commits are only partially overlapping e.g.

alert A: 4-8
alert B: 6-20
alert C: 7-15

**Comment by simonhatch** [comment]
FYI: These are actually non-overlapping, but it's not obvious until you expand the groups.

**Comment by natorion** [comment]
IC, I created an FR out of this.
