### ISSUE TITLE
Alerts overlapping in "existing bug" list, but not upon submit

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#3246]
1) Go to triage alert: https://chromeperf.appspot.com/report?sid=2eedccb27b84725756dbe6153e7f7796f0207f15e7f46a02c14c7e429106849c&rev=1487342040
2) Click "existing bug"
3) Scroll down through existing bugs, bug 694563 is highlighted as overlapping
4) Click on that bug and then click "Submit"
5) Get a warning that there are non-overlapping alerts

Seems like these two systems should be calculating overlapping in the same way, so that you don't suggest associating an alert and then get a warning.

**Comment by benshayden** [comment]
Archiving. V2SPA fixes this.
