### ISSUE TITLE
Dashboard - Improve responsiveness modifying displayed chart

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3251]
Breaking up #3243 into individual issues.

Modifying an already displayed chart

What IMO really is an issue is the snappiness when a chart is already loaded: How fast does the chart react to changes: 1.) new data added 2.) revision range changed (that takes ages sometimes). The snappiness of arewefastyet is often brought up. Case 1.) probably is the same as "Loading of a new chart". For 2.) it should be possible to start prefetching revisions if chromeperf is idle?

@natorion

**Comment by benshayden** [comment]
I think that v2spa's service worker helps a lot, but I also plan to investigate chart performance more thoroughly before launch.
