### ISSUE TITLE
Dashboard - Improve browse commits near alert

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3252]
Breaking up #3243 into individual issues.

Browsing the commits on a chart/near an alert

If one wants to explore the commits near an alert, one is mostly out of luck. AFAIK it is simply not feasible to select a commit near an alert. It is possible to zoom in though, but that again is very cumbersome and fickly. Two different suggestions: 1.) Offer zooming the x also directly from the chart (see arewefastyet as an inspiration) 2.) Don't display the sticky alert marker directly on the graph but instead float it on the top of the chart:

<img src="https://cloud.githubusercontent.com/assets/7190422/23168230/c7854a2c-f847-11e6-9543-fe0d15a714a7.png"></img>

@natorion

**Comment by simonhatch** [comment]
Hacked up an attempt at this: https://dev-simonhatch-36b1fa4a-dot-chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgzIH0_goM

**Comment by simonhatch** [comment]
Multiple alerting graphs examples:

Here's dotted line extending to bottom, and floating the alerts a bit above the points:
https://dev-simonhatch-eb8c85d5-dot-chromeperf.appspot.com/report?sid=f4959a908625dbced0499ed0e9ff3e53a6e940546777a75d37afe6acf93a1343


Alert at top, line extending to bottom:
https://dev-simonhatch-d1a14d6e-dot-chromeperf.appspot.com/report?sid=d5360100abaabb01f4ae4ef3409bc7f3345bb32a78be8ec5dcc5886a1138cfe0


Floating alerts at the top or bottom becomes a bit of a mess if you happen to load multiple graphs with many alerts, dunno if we care about that use case, seems uncommon. Also extending a line across from top to bottom with the alerts fixed at the top or bottom makes it difficult to understand which alert is associated with which graph. Best compromise seems to be to float the alert a little above the point, with a line extending down?

**Comment by natorion** [comment]
Played around a little bit. Feedback following in chunks

1.) Floating alerts bit above the points:
- Looked nice at first
- Does not solve the problem if there is a steeper regression and at that point is still in the way
![6ls6uxf5ypl](https://cloud.githubusercontent.com/assets/7190422/24269699/98acc4a4-1012-11e7-8e00-87020ddc812b.png)

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917893
