### ISSUE TITLE
Dashboard - Render arrow from chart-tooltip popup to commit.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3254]
Breaking up #3243 into individual issues.

Plot an arrow to the commit being shown in the information pane

When investigating alerts or regressions I might display multiple charts and scroll up/down. Afterwards it is not clear anymore which commit is really shown in the information pane. Simply drawing an arrow/line from the pane to the actual commit on the graph would remove that problem.

@natorion

**Comment by benshayden** [comment]
Archiving. V2SPA will fix this.
