### ISSUE TITLE
Dashboard - Add close button to chart-tooltip.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3256]
Breaking up #3243 into individual issues.

Offer a way to close the pinned information pane

When I click on an alert, I see the options to triage, etc the alert. There is also a close button. Such a close button would be great on the pinned information pane too because the pane is often obstructing the chart.

@natorion

**Comment by simonhatch** [comment]
How's this:

https://dev-simonhatch-7686e033-dot-chromeperf.appspot.com/report?sid=a25effb414e5e78f8f791d1ff043f002dbbddd164138beeebe1c867482b11ebe

**Comment by natorion** [comment]
Thanks. That would accomplish the task.

I am wondering, if the known "Close" button (see screenshot) that is shown when an alert is selected might be the better UI. It is an already known UI pattern used on chromeperf. I also played around a little bit and when the content of the pinned pane is scrolled, the "X" disappears (see screenshot).

![closebuttonvanished](https://cloud.githubusercontent.com/assets/7190422/23226508/160a6d96-f936-11e6-8ccb-b1130c416a44.png)

**Comment by simonhatch** [comment]
Hmm that's kind of annoying, didn't realize it did that. Do you have a preference of close button vs X? We should probably make all these popups have a similar UI, although in this case the close button would probably be to the right of the bisect/trace buttons.

@anniesullie

**Comment by anniesullie** [comment]
I think it makes sense because of the scrolling issue, and because the buttons in the triage dialog work the same way.

The chart legend uses "x", but it is very small so I think it's an exception?

**Comment by natorion** [comment]
Given that the close button is already being used I would favor the close button. Might also be more touch friendly, which probably is not that important ;-).

**Comment by simonhatch** [comment]
Ok great I can change the X to a close button. So it'll be on the far right, because there's also an optional "debug" button that's displayed for the last data point in a series.

**Comment by simonhatch** [comment]
How's this: https://dev-simonhatch-62ad4b1b-dot-chromeperf.appspot.com/report?sid=2ccfb75e2e41e37ad9281fedb04c9bb50747f42914bcd055788ed7b80a1e47fa

**Comment by natorion** [comment]
Couldn't brake it 👍
