### ISSUE TITLE
Visualize the clustering and overlapping of grouped alerts

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3257]
Reference: #3245 

It would be interesting to see which alerts overlap and which don't. That would make it easy to identify if there are multiple issues in the alert range. Additionally it would be easy to identify cluster and thus also hinting to the location of multiple issues. See attached picture.

- Big bottom bar is the min and max range of all the grouped alerts
- Small lines are the individual alert ranges (multiple alerts for the same range are only shown as one line, maybe use line thickness to visualize the alert count)
- Red lines show non-overlaps or the average of a cluster thus identifying "wrong" alerts or multiple issues.

![overlapper](https://cloud.githubusercontent.com/assets/7190422/23203841/8da28ff2-f8e4-11e6-8e2b-5a4eeac338b0.png)

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917885
