### ISSUE TITLE
Add group_report?rev=xxx link to a pinned commit information pane

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3258]
See screenshot to identify the information pane I am talking about: 
![hoveringinfo](https://cloud.githubusercontent.com/assets/7190422/23168499/ad11bd8c-f848-11e6-811e-fc623a28b1d2.png)

It would help if this pane also have an entry to the associated group_report?rev=xxxx link. E.G. in the screenshot above that would be group_report?rev=450345.

That would improve the discoverability and reduce the error-proness of this feature and make it easy to investigate commits.

**Comment by anniesullie** [comment]
One thing that could get a little confusing here: In that screenshot, the rev that regressed could be anything from 450243-450345, which is over a hundred commit positions, and the range can vary from bot to bot. How do we know that we want to link to rev=450345.

**Comment by natorion** [comment]
If it is the wrong revision, a user can simply change the revision number. With this change he at least has the chance to discover the feature and already gets a good preset.

Perfect solution would be a range in group_report?rev=xxxx, but that seems like a second iteration of this feature with more work attached to it.

**Comment by anniesullie** [comment]
Makes sense. I'll take this and make a demo.

**Comment by anniesullie** [comment]
Demo: https://dev-sullivan-4c493604-dot-chromeperf.appspot.com/report?sid=c99c1147fedb76916f456dabc859c1e59ca16fd82dc3dac8d110b2366b898970

**Comment by natorion** [comment]
Simple but awesome :-) Thanks!

**Comment by perezju** [comment]
This is great!
