### ISSUE TITLE
results2.html: exception on clicking 'show overview' for the first time

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#3260]
The following line doesn't look right: [histogram_set_table_row.html#L260](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/value/ui/histogram_set_table_row.html#L260)
It seems like `displayLabel` will never be defined there?

I think this is the cause of a bug in results2.html where you have to click the 'show overview' button twice to get the overview to show up however I'm not sure what the fix should be.

**Comment by chromy** [comment]
@benshayden I think you're the expert here :)

**Comment by benshayden** [comment]
Nice catch! Patch incoming.
