### ISSUE TITLE
Core test selection should include siblings if a selection is leaf-level

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3264]
If I select a leaf test, then I want all of its siblings to be selected. Currently, we only check for children, which makes browsing charts needlessly inconvenient. In the same vein as #3263, we can do this in a straightforward, easily testable way once we're using /list_tests?type=test_path_dict everywhere.

@anniesullie

**Comment by benshayden** [comment]
Archiving. V2SPA uses descriptors instead of the test tree.
