### ISSUE TITLE
Need to update documentation to include gcloud appengine library install

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3265]
After https://codereview.chromium.org/2701113002/ I cannot run the unit tests locally, even though I have gcloud sdk installed and added to my path. I'm running on Mac, not sure if it matters. I get this error:

```
WARNING:root:Could not load Pipeline API. Will fix path for testing. ImportError: No module named appengine.api
Failed to import test module: add_point_queue_test
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/sullivan/github/catapult/dashboard/dashboard/add_point_queue_test.py", line 7, in <module>
    from dashboard import add_point_queue
  File "/Users/sullivan/github/catapult/dashboard/dashboard/add_point_queue.py", line 11, in <module>
    from google.appengine.api import datastore_errors
ImportError: No module named appengine.api
```

When I print out the appengine path that gets inserted here: https://codereview.chromium.org/2701113002/diff/40001/dashboard/dashboard/__init__.py

It's `/Users/sullivan/google-cloud-sdk/platform/google_appengine`. I do indeed have gcloud installed at `/Users/sullivan/google-cloud-sdk/`, but there is no `platform/google_appengine` directory. Is that the right path?

@eakuefner @simonhatch @jessimb FYI

**Comment by simonhatch** [comment]
Just checked my mac install and repro'd, looks like this fixes it:

gcloud components install app-engine-python

Should add that to the install steps and possibly error out with a helpful message if its not installed.

**Comment by anniesullie** [comment]
Thanks, that works for me too! Re-titling bug.

**Comment by anniesullie** [comment]
https://codereview.chromium.org/2711883002

**Comment by anniesullie** [comment]
Send a PSA to chrome-speed-services@

**Comment by anniesullie** [comment]
This is **done**.
