### ISSUE TITLE
Back/forward button doesn't work in traceviewer

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#3268]
When selection changes, the brushing state controller is supposed to do a pushState that saves the selection id. Then when you press back, the brushing state controller should receive a popstate message, with the selection id. It then should change the selection

This isn't working.

Steps to reproduce: open a trace in the trace_viewer.html, make a selection, make another, press back.
What should happne: pressing back restores the old selection
What does happen: nothing

**Comment by natduca** [comment]
@lpy I would start by seeing if brushing_state_controller's historyEnabled property is set to true. If it is not, then thats the bug. If its set to true, then start following the onUserInitiatedSelectionChange_ to see if window.pushState is being called.

**Comment by lpy** [comment]
This was fixed.
