### ISSUE TITLE
is_selected is a fake bool

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3269]
In the process of implementing a mode for `/graph_json` that can take a fully resolved list of test paths rather than a test path dict, I discovered that the `is_selected` request parameter that the endpoint accepts is a fake bool: it takes the value `'true'` and then is treated as though it were a boolean. This has not resulted in any bugs because we use `.get()` and only set the field in `chart-container` when we want to query for selected tests, but this seems dangerous because it could lead to subtle bugs. I think it would be better to use 0/1 (which is the convention we use elsewhere) and check for these explicitly.

This is also causing me to rethink my position on allowing boolean args not to appear in the request: I now believe that if boolean args are to be accepted, then it's safer to make them mandatory to prevent subtle bugs like this, so I'd also like to update the `return_selected` parameter that the `/list_tests` code I added accepts.

@anniesullie

**Comment by eakuefner** [comment]
Marked this as code health; to be clear it's non-urgent and I'll work around it until the endpoint work is closed out.

**Comment by anniesullie** [comment]
Agreed this is a problem; I think we should start with an audit of request params.

**Comment by benshayden** [comment]
Archiving.

**Comment by simonhatch** [comment]
This was never fixed AFAIK and still an issue.

**Comment by eakuefner** [comment]
I'm not going to work on this but am removing my assignment instead of archiving because @simonhatch reopened. @benshayden feel free to re-archive; I think descriptors probably subsume this functionality anyway.

**Comment by benshayden** [comment]
/graph_json will be deprecated by v2spa, and can be removed when the legacy /report and /group_report pages are removed.
