### ISSUE TITLE
Standardize dashboard error reporting

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3271]
I'm a huge fan of throwing in deep business logic and using the handler to catch the exception and call self.ReportError, but unfortunately we don't do this everywhere, and we're inconsistent about it in a number of different ways:

* graph_json uses returning `None` in some private functions to signify that there was a problem, and just calls `logging.error` to record the problem, which I think is especially bad because it means you need to go to the logs to see what the specific problem was.
* Many files specify their own `BadRequestError` so that they can use the pattern that I describe.

I'd propose using `ValueError` more (which is, I think, the built-in exception type that most of our uses of `BadRequestError` correspond to) and/or defining a shared `BadRequestError`.

**Comment by anniesullie** [comment]
+1 to these suggestions!

**Comment by eakuefner** [comment]
Archiving.
