### ISSUE TITLE
Make App Engine scripts consistent

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3274]
We will have 4 scripts that do similar App Enginey stuff:
- Deploy App Engine
- Deploy Cloud Endpoints
- Run dev server / JS tests
- Run Python unit tests

They all need to do things like find the Cloud SDK in `PATH`, add required libraries to `PYTHONPATH`, etc. Let's put them all in one place and reuse some common code.

@anniesullie

**Comment by anniesullie** [comment]
Awesome! As we come up with clear plans, can we keep the doc updated? https://docs.google.com/document/d/1GLaXuQsc0r6K6WfFk0LC7nGVO-1aExt4PUsBCRXQgm8/edit

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917871
