### ISSUE TITLE
Enable eslint's dot-notation rule

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3278]
The [airbnb style guide recommends using dot notation](https://github.com/airbnb/javascript#properties--dot)

```
myObject.myProperty = 1;
```

over bracket notation

```
myObject['myProperty'] = 1;
```

where possible. (There are some instances where it's not possible, such as if the property name has a minus in it that would be interpreted as a subtraction operator without the bracket notation.)

eslint has the [dot-notation rule](http://eslint.org/docs/rules/dot-notation.html) with the `--fix` capability, so we could turn it on and fix the existing codebase. 

@eakuefner, @benshayden do you think this sounds reasonable? @lpy, would you be willing to take on the task of rolling out this new rule after using eslint's `--fix` capability to fix any existing violations in the codebase?

**Comment by lpy** [comment]
Duplicate to #3461, close it as duplicate and fixed.
