### ISSUE TITLE
[histogram-set-table] Enable deep links and using the browser's back button via location.hash.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3289]
Currently, when the user clicks a related histogram link, it is difficult to get the UI back to where it was before. The user needs to clear the search box, re-expand rows and re-open histogram cells.

There's also no way to share deep links to specific UI configurations. Users can share links to files, but then they need to figure out how to instruct colleagues to navigate the UI.

location.hash should persist the UI state in order to enable deep links and allow users to use the browser's back button to restore UI state after clicking related histogram links.

 * search box
 * reference column
 * display statistic
 * show all
 * groupby picker
 * expanded rows
 * open histograms
 * overview line charts
 * sort column and descending
 * brushed bins
 * merged sample diagnostics
 * unconstrained Name column

One alternative idea for solving the back-navigation problem (but not deep links) would involve adding a row of links to the top controls. That would make it easier to undo several related histogram navigations, but that's an unlikely scenario. That design is also significantly more complex than using location.hash because it opens up several questions about how exactly the links would be created, what they would display, etc.

@fmeawad

**Comment by fmeawad** [comment]
I think the deep links for me is more important then the back button use case.
To help with the pointing out to issues can you append the list you have with:

- sorting

**Comment by benshayden** [comment]
@zeptonaut recommended [app-route](https://www.polymer-project.org/1.0/toolbox/routing).

**Comment by benshayden** [comment]
If these deep links replace the existing localStorage integration, then that would solve a whole class of bugs like #3281

**Comment by benshayden** [comment]
Currently, the histogram-set-table manages all of the configuration, but I think it's complex enough to warrant its own MVC pattern:

![](http://i.imgur.com/vpLOKm5.png)

Some of the configuration is set by the user in the top-controls (which should be moved to a separate dom-module), and some is set in the table itself (which should also be moved to its own dom-module). The histogram-set-table itself will coordinate the Configuration object and communication, and handle some styling and edge cases like `zero Histograms`. The table-core element will contain, style, and build the base-table using HistogramSetTableRow as histogram-set-table currently does. The histogram-set-table can compute possibleGroups, possibleStatistics, possibleReferenceLabels, and `histograms.length === sourceHistograms.length` (which controls whether Show All is enabled), and pass them to the top-controls in `set histograms`, but only the table-core needs to store the HistogramSet, and the possibilities don't need to be shared via the Configuration.

The Configuration object is the Model in this MVC.
When the Configuration changes, it will send `configuration-changed` events to the top-controls and table-core elements, as well as an app-route wrapper to translate the configuration to hash params.
The top-controls element is a View-Controller for the top half of the Configuration fields. The table-core is Controller for the bottom half of the Configuration fields, but consumes all of the fields.
The app-route wrapper will act as a third View-Controller that displays and can modify all Configuration fields.
All 3 View-Controllers will have a reference to the Configuration object so they don't need to store any state themselves.

Currently, the histogram-set-table supports several setters like `set groupingKeys`, `set referenceDisplayLabel`, `set displayStatistics`, etc. These are called from event callbacks for the various control elements both in top-controls and in the base-table. Most of those setters carefully call updateContents_, sometimes using getExpansionStates_ and setExpansionStates_ to avoid losing that information. The Configuration object will simplify all of those setters to a single `configuration-changed` event, whose handler can use Configuration.expansionStates instead of get/setExpansionStates_.

**Comment by zeptonaut** [comment]
Also worth noting as a possible implementation is https://github.com/Kalitte/app-states#0.6.9: I'm not sure which is more used, that or `<app-route>`.

**Comment by benshayden** [comment]
hash is lost through the google signin page. probably use query string and html5 history api instead.

**Comment by benshayden** [comment]
Done!
