### ISSUE TITLE
ChromeProcessNames FixedColorScheme needs to be imported by breakdown_span.html

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3295]
results.html for memory benchmarks are broken because breakdown-span tried to look up the ChromeProcessNames FixedColorScheme but can't find it because it isn't vulcanized because memory_metric.html isn't (and shouldn't be) imported by breakdown_span.html.

That FixedColorScheme should be moved to its own file so it can be imported to both memory_metric.html and breakdown_span.html without requiring all of memoryMetric to be vulcanized into results.html.

It might be good to make an all_fixed_color_schemes.html to import all FixedColorSchemes, so it can be imported by breakdown_span.html and whatever else might need to look up FixedColorSchemes.

@chromy  Can I ask you to take this?

**Comment by chromy** [comment]
Yep! I'll take a look. Is there a script I can run to produce a results2.html from a trace?

**Comment by benshayden** [comment]
Sorry, I totally should have linked to a repro!
http://www/~benjhayden/3295.html
Open devtools and click one of the cells to open a histogram that should have the processes diagnostic.

In order to test that your change fixes it, right click that link, Save Link As into your git working directory, and pass it through `./tracing/bin/valueset2html 3295.html`, open that local file, and click one of the cells to open a histogram. You should see beautiful merged RelatedHistogramBreakdowns :-)

**Comment by benshayden** [comment]
And to actually answer your question, `./tracing/bin/run_metric traceFileOrDir metricName [metricName [metricName...]]`

**Comment by chromy** [comment]
Thanks! Looks great :) I have updated the patch.

**Comment by perezju** [comment]
After that CL landed I'm now seeing when running benchmarks:

```
Warning: Unknown process id "gpu_process". Please add it to |CHROME_PROCESS_NAMES|.
Warning: Unknown process id "gpu_process". Please add it to |CHROME_PROCESS_NAMES|.
```

And Hector is OOO for a week. The issue seems benign, but I'm not sure. @benshayden could you have a look?

**Comment by chromy** [comment]
😥 I messed up the default case on line 173 of
tracing/tracing/metrics/system_health/memory_metric.html

Now it always logs an error when the process name isn't the renderer or the
browser whereas before it only logged an error if the name wasn't in the
list of all the known names. We probably should probably only log if
!Object.values(CHROME_PROCESS_NAMES).contains(baseCanonicalName)

This doesn't actually effect anything other than spamming the logs.

Sorry about this.

**Comment by perezju** [comment]
No worries! I did a quick check and at least the gpu values *are* there in the results, so if it's only a bit of extra log spam then there is no urgency.

**Comment by benshayden** [comment]
Fix: https://codereview.chromium.org/2742533002
Followup: #3351
