### ISSUE TITLE
Calling this.async in attached is bad news

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#3297]
As I discovered in [cr/2671813006](https://codereview.chromium.org/2671813006/) the following piece of code from [timeline_view.html](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/timeline_view.html#L144) makes it hard to test:

```javascript
attached: function() {
  this.async(function() {
    this.trackViewContainer_ = Polymer.dom(this).querySelector(
        '#track_view_container');
    if (!this.trackViewContainer_)
      console.error('missing trackviewContainer');
  });
},
```

There isn't an easy way to force the async callback to happen without `requestAnimationFrame()` hacks, even the usual trick of abusing `Polymer.dom.flush()` doesn't work here.

The:
```
attached: function() {
  this.async(function() {
    ...
  });
},
```
pattern was a partial replacement for the `domReady` event that was removed in Polymer 0.5 because it was flaky. See the [migration guide](https://www.polymer-project.org/1.0/docs/migration). The issue is that we need to wait for our Light Dom children to be present which happens at some arbitrary time (but normally after attached). I think the RightThing(™️) thing is to [observe our children](https://www.polymer-project.org/1.0/docs/devguide/local-dom#observe-nodes). Which hopefully should be easier to test?

cc: @zeptonaut

**Comment by chromy** [comment]
See also: https://github.com/Polymer/docs/issues/1456

**Comment by zeptonaut** [comment]
Sounds like a plan to me :-)

**Comment by benshayden** [comment]
@chromy Are you driving this? Did you mean to assign yourself?

**Comment by chromy** [comment]
Yep, I'm driving this but it's low priority. I'm off this week but maybe I
can look at it next week.

**Comment by benshayden** [comment]
sgtm, thanks!
