### ISSUE TITLE
Add logic for identifying Location::setHash.

### ISSUE THREAD

**Issue by sunjianchromium** [catapult-project/catapult#3300]
Currently, spa_navigation_helper only identifies History::pushState
as the event that updates the url fragment. Location::setHash actually
serves as the same purpose as History::pushState. This patch adds logic
to identifying Location::setHash.
Background: https://docs.google.com/document/d/1B44Aqym4rRNlghlMNzSR2clIZhdvVyhQ2LMmvRKEkW0/edit?usp=sharing

**Comment by benshayden** [comment]
This looks done, and is a metrics bug, not a tbm2 bug.
