### ISSUE TITLE
Add a metric for spa navigation.

### ISSUE THREAD

**Issue by sunjianchromium** [catapult-project/catapult#3302]
Currently, we have written the logic to identifying navigation start and first paint for each SPA navigation. We need to write a metric to measure the duration between navigation
start and first paint event for each spa navigation.
Doc: https://docs.google.com/document/d/1B44Aqym4rRNlghlMNzSR2clIZhdvVyhQ2LMmvRKEkW0/edit?usp=sharing

**Comment by benshayden** [comment]
This looks done
