### ISSUE TITLE
chart-container needs to be refactored

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3303]
In the process of addressing #3226, it's come up that `chart-container` has a lot of cruft that it doesn't seem to make sense to reuse. In particular, the goal is that we should be able to pass lists of tests directly to /graph_json, but there are a couple of major architectural issues that make this difficult to do in a sane, comprehensible way:

1. `addSeriesGroup` takes `testPathAndSelected`, which is an ad-hoc, list-based data structure that indicates the selected tests for a given main test and uses a lot of lines parsing through this. It would be better to take more arguments that are smaller, less ad-hoc, and more descriptive.
2. `seriesGroupList` is another ad-hoc data structure that `addSeriesGroup` mutates, and this is used throughout `chart-container`. As with 1, code that uses `seriesGroupList` is hard to understand and modify because `seriesGroupList` is insufficiently object-oriented, both in terms of its structure and in terms of its lack of modularity.

I have a plan to refactor chart-container that would replace these as follows:
1. Implement list mode for `sendGraphJsonRequest` (easy)
2. Rename `seriesGroupList` to `legacySeriesGroupList`
3. Introduce a `SeriesGroup` class that is easy to understand
4. Write `addSeriesGroup2` which accepts a `SeriesGroup`, or possibly separate args that it then collates into a `SeriesGroup` instance.
5. Convert callers of `addSeriesGroup` (`report-page.addChart`, etc.) to `addSeriesGroup2`
6. Delete `addSeriesGroup` and rename `addSeriesGroup2`.

Approach 1 would be to proceed with this refactor before continuing on #3226, approach 2 is to try to hack on top of the existing code and circle back to this refactor in the future, which could result in some ugly bits but would probably be a little better at avoiding scope creep as far as the main goal of fixing the V8 performance problem ASAP. I would be a little worried that approach 2 would be difficult to review, but we could start on that route and see what happens.

Step 1 of the above plan can be done independently of which approach we plan to take, so I think I may just upload that now.

I met with @simonhatch briefly today to talk about these problems; he's going to take a look at the code himself and we'll talk again tomorrow about what to do.

@anniesullie

**Comment by anniesullie** [comment]
Yeah, this definitely needs refactoring! A deeper issue to think about is that this logic all encapsulates a concept of results grouping that is totally different than how telemetry sees it.
