### ISSUE TITLE
Totals rows in multi-event-sub-view are broken/showing-NAN

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#3304]
Totals are broken in the multi event sub view:

![image](https://cloud.githubusercontent.com/assets/412396/23383667/7078d136-fcfc-11e6-9799-4c94a27ebb79.png)

**Comment by natduca** [comment]
@lpy @benshayden @eakuefner any ideas?

**Comment by eakuefner** [comment]
I think @benshayden has a CL in flight to fix this.

**Comment by eakuefner** [comment]
Actually, a quick manual bisect shows that https://codereview.chromium.org/1974123002 is the first bad CL. @benshayden it seems like the root cause you suspected may not actually be to blame, but can you take a look?

Let's also definitely add a unit test for this.

**Comment by benshayden** [comment]
Dupe #3349
