### ISSUE TITLE
Add CPU time version of generateTimeBreakdownTree

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3315]
Once we have a CPU time FMP metric (#3282), we'll want to break down the CPU time metric the same was as the wall clock metric.

**Comment by benshayden** [comment]
Does [RelatedHistogramBreakdown.buildFromEvents](https://github.com/catapult-project/catapult/blob/0975e3101889d59c7f7c5174cf2ef7e0c6529f9d/tracing/tracing/value/diagnostics/related_histogram_breakdown.html#L86) do what you're looking for?

**Comment by tdresser** [comment]
Sure does, thanks!
