### ISSUE TITLE
Frequency display broken

### ISSUE THREAD

**Issue by ChrisCraik** [catapult-project/catapult#3317]
Appears CPUs have been moved out of the kernel subsection.

This appears to have broken frequency display, where each CPU's frequency would show up directly beneath the CPU, and show/hide based on whether kernel was collapsed or not.

**Comment by ChrisCraik** [comment]
@zeptonaut @Alex319 Looks like this is from fe1f77a00fc87241d0b3c0127d3d61c2ac7e3166

**Comment by ChrisCraik** [comment]
Do we want all the arbitrary clocks to still reside in the kernel? Seems strange that we'd treat CPU freq different, but I'd say we definitely want CPU freq to remain beside the CPU scheduling tracks.

If we do want to move them out of the kernel, maybe to a collapsible 'other clocks' section?

**Comment by zeptonaut** [comment]
Unassigning @Alex319, as he's no longer on our team.

@ChrisCraik, could you supply a screenshot of the bug?

**Comment by ChrisCraik** [comment]
Sure, much easier to understand with visuals. Previously, the kernel when collapsed would show only CPU tracks:

![collapsed](https://cloud.githubusercontent.com/assets/384439/23483675/c94caa70-fe88-11e6-8b59-bcff3e0fc88c.png)

And when expanded, would show associated clocks alongside those CPU tracks:

![expanded](https://cloud.githubusercontent.com/assets/384439/23483677/c95ee6a4-fe88-11e6-93d0-f2d6a7b963e9.png)

Now there's a few individual problems:

- There's no way to expand the default/device section, so clocks are never displayed.

- All of the other, unassociated clocks are put in kernel, when they make about as much sense to live near the other clocks.

- The CPU tracks are above the CPU usage track, meaning you need to do more vertical scrolling to get between important parts of the trace.

![new](https://cloud.githubusercontent.com/assets/384439/23483676/c95e29da-fe88-11e6-9e9f-ba37832da1b6.png)

**Comment by zeptonaut** [comment]
It seems like, more generally, the problem here is the same as #1790: because there's no way to rearrange/pin tracks, their original vertical location matters a whole lot more than it probably should. CPUs lie right near the border of device and kernel: they belong to the device, but work is scheduled by the kernel. We originally introduced the distinction because we had power samples that clearly weren't really associated with the kernel: they were associated with the device.

I'm not completely sure what the right answer is here, other than it'd be great if things like this didn't matter so much in the first place.

**Comment by ChrisCraik** [comment]
I don't worry as much about the original vertical location - main problem is information that's supposed to display and react to track collapse state is now completely hidden and invisible.

I think the right way to approach fixing 'device' content showing in the 'kernel' track would have been to separate it into a 'device' track, or to simply rename 'kernel' -> 'device' or something similar. The downside to having an additional collapsible category is that it just adds more vertical clutter (at least speaking for the systrace usecase).

Though there's no immediate rush to update, this issue is preventing us from updating systrace in aosp.

**Comment by ChrisCraik** [comment]
If there's no clear plan how to improve this in the short term, can we consider reverting fe1f77a for the time being, as it breaks the Systrace displaying CPU frequency? Android devs are hitting bugs that need fixes that have already landed upstream, and I'd like to push an update when possible.

I'd be happy to review it re-landing, and discuss what the appropriate long term display for the data could be.

**Comment by zeptonaut** [comment]
Just to summarize: @ChrisCraik and I talked offline and decided to follow the plan he summarized in his last comment.
