### ISSUE TITLE
Histogram should support inter-percentile ranges

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3319]
Many of our metrics are either multimodal, or include outliers we'd like to exclude. If either of these is true, we should probably be using percentiles instead of the mean.

Using std with percentiles doesn't really make sense though. std makes the most sense when your data is normally distributed, with a single mode, and you're including outliers.

We should expose interquartile range in addition to std, and include people to use mean/std if the metric is normally distributed and we aren't worried about outliers and percentiles/iqr otherwise.

**Comment by tdresser** [comment]
@benshayden - any thoughts?

**Comment by benshayden** [comment]
SGTM. Would generalized inter-percentile ranges be useful?
I can hack this up next week if that's soon enough?

**Comment by tdresser** [comment]
I'm in no rush.

I don't have much experience with inter-percentile ranges in general, as none of our tools support them.
It would be nice to be able to compare the data we get from various ranges, if it isn't much more effort.

**Comment by benshayden** [comment]
I can't imagine any way of doing this that would take longer than a couple hours. :-)
(Self: remember delta statistics.)

Options:
1. customizeSummaryOptions({iqr: true})
1. customizeSummaryOptions({iprs: [[0.25, 0.75], [0.1, 0.9]]}) produces 2 statistics: ipr_025_075 and ipr_010_090.
1. No new options. Generate IPRs automatically for every pair of percentiles. E.g. to get IQR, set percentile=[0.25,0.75]. This scheme might give you more IPRs than you want: percentile=[0.1,0.25,0.75,0.9] would produce 12 IPRs, which might clutter UIs.

Thoughts?

**Comment by tdresser** [comment]
4. `cSO({iprs:[{lower:0.25, upper:0.75}, {lower:0.1, upper:0.9}])`

I'm voting 2.

**Comment by benshayden** [comment]
SGTM

**Comment by benshayden** [comment]
Now that I'm almost done implementing this, what do you think of [mean/median absolute deviation](https://www.edge.org/response-detail/25401)?

If you would be interested in evaluating them as alternatives to IPRs, then I can easily resurrect [this old CL](https://codereview.chromium.org/2000893002) and make Histogram support both IPRs and the MADs for direct comparison.

**Comment by tdresser** [comment]
The big question is how we want to handle outliers. IPR ignores them, STD emphasizes them, and MAD is in between.

Would it be reasonable to do a local benchmark run including IPR, STD and MAD on a benchmark or two, and upload the results, so we can see some practical examples? That way we can look at some concrete data before uploading these patches, reducing the risk that folks will come to depend on them.

**Comment by benshayden** [comment]
Can I ask you or @deepanjanroy  to patch in [AAD/MAD](https://codereview.chromium.org/2745333002) and [IPRs](https://codereview.chromium.org/2742163002) and enable them in whichever metrics interest you and run the benchmarks? I have about [50 bugs](https://github.com/catapult-project/catapult/issues?q=assignee%3Abenshayden+is%3Aopen) that I need to fix asap, and I think you're probably stronger on the statistical philosophy of evaluating aad vs map vs iprs.

**Comment by tdresser** [comment]
Yup, one of us can take a look.

**Comment by maxlgu** [comment]
When the input is iprs: [[lower:0.2555, upper:0.7555]], do we want to produces: ipr_025_55_075_55 or do we want to truncate it to ipr_025_075? As I notice that for percentile [0.5555] it will produce pct_055_55.

**Comment by maxlgu** [comment]
If we produce ipr_011_011_011, it is ambiguous because it could means either {0.11011, 011} or {0.11, 0.11011}

**Comment by benshayden** [comment]
The [draft CL](https://codereview.chromium.org/2746363003) truncates using opt_force3.

**Comment by maxlgu** [comment]
Is there any way to search for all the CL belonging this issue in https://codereview.chromium.org/ ? I missed [https://codereview.chromium.org/2746363003](url) until it was mentioned here actually. And it seems like Rietveld doesn't support searching CLs by subjects or descriptions.

**Comment by maxlgu** [comment]
This is my report of comparing MAD, AAD, IQR and STD https://docs.google.com/a/google.com/document/d/1cu0h94BiL9BoBMSvAjNCZk1g4kixJvBTyOrUkUY3TwM/edit?usp=sharing

**Comment by tdresser** [comment]
Filed issue 3644 to track using iqr where appropriate.

**Comment by maxlgu** [comment]
Thanks Tim.
