### ISSUE TITLE
Telemetry gtest_progress output should also shows the grouping keys of story

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3320]
The stories in a Telemetry benchmark are distinguished by both the name & the value of grouping keys. However, the gtest_progress output only display story by name. This lead to confusion for people who investigate Telemetry failure in the log. e.g: we can't distinguish 3G story vs non 3G for `loading.mobile` benchmark in https://chromium-swarm.appspot.com/task?id=34a228bd293dfb10&refresh=10&show_raw=1

@eakuefner: can you triage this?

**Comment by eakuefner** [comment]
@randalnephew Would you be willing to take a look at this?

I think the thing to do here is modify `GtestProgressReporter.WillRunStory` and `GtestProgressReporter.DidRunStory` to print the [same string that we inject into the tir_label](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/results/page_test_results.py#L319).

**Comment by randalnephew** [comment]
Will do.

**Comment by eakuefner** [comment]
Thanks Randy!

**Comment by randalnephew** [comment]
[ RUN      ] https://www.google.com/search?q=flower#q=flower+delivery
[ RUN      ] /tmp/tmpoEnuPr.html
[       OK ] /tmp/tmpoEnuPr.html (2357 ms)
[       OK ] https://www.google.com/search?q=flower#q=flower+delivery (34898 ms)
[ RUN      ] https://www.google.com/search?q=flower#q=flower+delivery-[traffic_setting - Regular-3G]-other_key - other_value]

Is that an exceptable output? I haven't changed the messaging for the DidRunStory yet, want to get the formatting agreed upon before doing that.

**Comment by nedn** [comment]
I think we should use `@` as the delimiter between the story name & the printed grouping keys of story since '-' can be interpret as part of the URL? Otherwise this seems ok to me.

**Comment by eakuefner** [comment]
I also find the brackets to be a little strange. What if you used dict formatting instead? Something like:
`...@{traffic_setting:Regular-3G,other_key:other_value}`?

**Comment by randalnephew** [comment]
Wait, isn't @ valid in URLs just not common?
