### ISSUE TITLE
Intent to turn on curly rule in eslint

### ISSUE THREAD

**Issue by lpy** [catapult-project/catapult#3322]
Intent to turn on the following rule in eslint

```
"curly": ["error", "multi-line", "consistent"]
```
which aims to prevent code like:
```
if (event)
  doThis();
```
but allow code like:
```
if (event) doThis();
```

**Comment by zeptonaut** [comment]
@lpy, could you add more detail in the bug description about what code we're trying to prevent/allow by turning on this rule? It seems like a little more detail is probably warranted.

**Comment by zeptonaut** [comment]
@lpy this came up in code review recently when someone noticed this still wasn't being caught. Any update on enabling this rule?

https://codereview.chromium.org/2769513002/diff/80001/tracing/tracing/model/helpers/chrome_renderer_helper.html#newcode140

**Comment by lpy** [comment]
ah sorry, it's on my list, I will send out a patch late today or maybe tomorrow.

One thing I noticed was that --fix would mess up with the codebase and changed code from
```
if (some_condition)
  this_is_a_very_long_function_name();
```
to
```
if (some_condition) {this_is_a_very_long_function_name();}
```

And those will need manual editing, any suggestion for eslint configuration? Or it's just something that can't be done by eslint?

**Comment by zeptonaut** [comment]
It looks like [that's what the `multi-line` option is for](http://eslint.org/docs/rules/curly#multi-line). Did you give that a try?

It seems like we probably also want the `consistent` option.

**Comment by lpy** [comment]
Yes, I tried it with `"curly": ["error", "multi-line", "consistent"]`

**Comment by zeptonaut** [comment]
Hmmm, maybe I was wrong then. Is [`multi`](http://eslint.org/docs/rules/curly#multi) more what we're going for? It seems to be a more restrictive version of `multi-line`.

**Comment by anniesullie** [comment]
I took a look at the [review](https://codereview.chromium.org/2776653002/), just wanted to verify that changes like this are what we want:

```
if (end < start)
  return null;
```

becomes

```
if (end < start) return null;
```

and **NOT**

```
if (end < start) {
  return null;
}
```

**Comment by zeptonaut** [comment]
Yep! That's exactly right.

**Comment by lpy** [comment]
I am a little confused here.

```
if (end < start) return null;
```
and
```
if (end < start) {
  return null;
}
```
both should be valid, right? The rule we are going to turn on accepts both cases.

**Comment by zeptonaut** [comment]
Ah, yes, sorry. They need to both be valid in case the whole thing doesn't fit on one line. Ideally, we'd have a rule that amounted to "If the whole thing fits on one line, require that it be put on one line. Otherwise, put it to the next line and add braces." eslint isn't that sophisticated, though, so we'll just have to keep an eye out for that part in code review and recommend that people squash it to one line if it fits.

**Comment by lpy** [comment]
Closed as fixed.

**Comment by zeptonaut** [comment]
Thanks @lpy!
