### ISSUE TITLE
Add breakdowns to FCP and onload in loadingMetric.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3326]
If metrics are monitored, then Breakdowns would be helpful.

https://bugs.chromium.org/p/chromium/issues/detail?id=697665

![](http://i.imgur.com/BVQtq27.png)

Also, the numbers in the FMP and TTI breakdowns should be rounded. The UI can't do it because it doesn't know the units.

Maybe units should be an optional field on the Breakdown diagnostic? Or can loadingMetric use RelatedHistogramBreakdowns instead? That would also let us monitor the sum of the 'other' category so we'd know when we needed to whitelist new events in ChromeUserFriendlyCategoryDriver.

Also, loadingMetric could use RelatedEventSets containing the largest few events in the 'other' category so we don't need to hack the loadingMetric to print them every time the other category creeps up.

@nedn @nyaxt @zeptonaut @eakuefner

**Comment by zeptonaut** [comment]
I don't think I understand breakdowns or diagnostics quite well enough to contribute to the discussion :-/

My intuition though is that we should try to do something simple, like round to a certain # of significant figures or places after the decimal point, unless there's a really compelling reason not to do so. I generally prefer the approach "wait until people are so frustrated that they're screaming for a feature before adding it".

**Comment by tdresser** [comment]
Monitoring the sum of the 'other' category sounds great to me, as does using RelatedEventSets.
I'm fine with dumb rounding.

**Comment by nedn** [comment]
+1 for dumb rounding. People can pick appropriate representation themselves for the breakdown, IMO.

Monitoring other is an interesting idea. That means you will need to export 'other' breakdown as a metric, doesn't it?

**Comment by eakuefner** [comment]
I think this is done.
