### ISSUE TITLE
Benchmark health report: Make the report a sortable table

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3327]
Data will need to be collected offline and stored in the datastore to create this type of report. We'll also want to include data from the go/chrome-benchmarks spreadsheet.

@simonhatch @eakuefner @nedn

**Comment by benshayden** [comment]
The benchmark health report was removed. There's a separate crbug about finding/writing a reusable sortable lit-html component.

**Comment by nedn** [comment]
@CalebRouleau fyi
