### ISSUE TITLE
Pinpoint - Need basic "new" page for initiating bisects.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3333]
Nothing fancy for now, just needs to be functional, mostly a copy of bisect-form.

**Comment by simonhatch** [comment]
@dave-2 landed https://codereview.chromium.org/2903343002/ which adds a /new endpoint with some basic inputs. Will need to flesh out with some more logic like:

On the UI side:

- Validate that all fields have inputs
- Add a radio button at the bottom to switch between performance/functional bisect
- Add a little text area to hold explainer text/errors
- Remove the "metric" field if functional selected
- Eventually, need to contact the dashboard somehow to get a dropdown of available bots

On the backend:
- Validation of various bot/test/metric params by contacting dashboard
- Validation of git hashes via gitiles_service

Also need to discuss how the dashboard will display the UI from pinpoint. Possibilities like:
- Just include the <pinpoint-bisect-form> element.
- Iframe the endpoint

**Comment by simonhatch** [comment]
@dave-2 landed https://codereview.chromium.org/2903343002/ which adds a /new endpoint with some basic inputs. Will need to flesh out with some more logic like:

On the UI side:

- Validate that all fields have inputs
- Add a radio button at the bottom to switch between performance/functional bisect
- Add a little text area to hold explainer text/errors
- Remove the "metric" field if functional selected
- Eventually, need to contact the dashboard somehow to get a dropdown of available bots

On the backend:

- Validation of various bot/test/metric params by contacting dashboard
- Validation of git hashes via gitiles_service

Also need to discuss how the dashboard will display the UI from pinpoint. Possibilities like:

- Just include the element.
- Iframe the endpoint

**Comment by simonhatch** [comment]
@dave-2 @anniesullie 

So I have a somewhat working new page here at: https://codereview.chromium.org/2960873002/

Right now basically I just include the polymer element directly in <bisect-button> and can optionally show it instead of the regular bisect form.

The pinpoint /new endpoint is wrapped with a oauth.Authorize decorator so that service accounts can access it

The dashboard has Pinpoint's <new-job-dialog> talk to it's own endpoint => /start_pinpoint_job, which uses it's service_account credentials to contact Pinpoint.

Random questions:
Should I be trying to use the user's credentials instead of the dashboard's service account? Tried initially to use an user authorized http instance but could never get it to contact Pinpoint correctly.

**Comment by anniesullie** [comment]
I think the current CL looks good.
  * Ideally I do think that it would use the user's credentials. You should be able to look at the monorail bug code for an example of the client side and the api auth code as an example of the service side. But if your code isn't different than that, and it's not working, I'm fine with punting for now. Would be great to tell pinpoint the user that requested the job though, so we can log it.
  * I think it's fine to loop the request through the dashboard. If the polymer element did the XHR directly to pinpoint, how would it do auth?
