### ISSUE TITLE
Removal of iterItems() broke html results of perf tests

### ISSUE THREAD

**Issue by wangxianzhu** [catapult-project/catapult#3339]
For example, now html result of blink_perf.paint show only one result. See HTML results link in
https://build.chromium.org/p/tryserver.chromium.perf/builders/linux_perf_bisect/builds/7060.

**Comment by benshayden** [comment]
[Revision link](https://github.com/catapult-project/catapult/commit/5f6a29f) since the title is not a clickable link.

Why do you think removing iterItems caused the results.html to display only 1 result?
When I open the results.html sent from googleusercontent.com, I see only 2 `<histogram-json>` tags in the file and no errors on the devtools console.

**Comment by zeptonaut** [comment]
Doing some manual reconstruction based on [the CL that the try job was launched from](https://codereview.chromium.org/2732573003/#ps60001), I think that I've figured out the problem that @wangxianzhu is talking about.

Before my change, the results2 UI looked like this:

![after_revert](https://cloud.githubusercontent.com/assets/1407397/23629879/1391dd74-0287-11e7-9af4-64144f8cf36b.png)

After the change, the results2 UI looked like this:

![before_revert](https://cloud.githubusercontent.com/assets/1407397/23629888/1bddd398-0287-11e7-8df8-6a1aae89ec8d.png)

Like @benshayden, I'm not seeing any errors in the Javascript console.

**Comment by zeptonaut** [comment]
I think I may have found the problem:

![problem](https://cloud.githubusercontent.com/assets/1407397/23630254/741dd264-0288-11e7-9d0f-2f8437bc7b7a.png)

It looks like I didn't change a `return` statement to a `continue` inside of an `iterItems` call. I'm going to see how hard it is to add a test for that, and then make sure that I didn't make the same mistake elsewhere.

**Comment by zeptonaut** [comment]
Hmmm, it actually looks like this is a pretty specific logic path that probably doesn't justify a test. I'm just going to try to find anywhere else that I may have screwed this up.
