### ISSUE TITLE
Uninstalling/reinstalling system apps

### ISSUE THREAD

**Issue by weableandbob** [catapult-project/catapult#3341]
I'm running into an issue running tests on the Chromium BuildBots when an additional APK needs to be installed, but the application is a system app. Currently, the test runner uses the default logic of removing the existing version of the application before installing the provided APK, which throws an error with a system app. There are two potential solutions to this:

1. Add support to the test runner to specify that an APK should be reinstalled instead of removed and installed.
2. Add support to Catapult for removing system apps. As @jbudorick pointed out, this is [already done with WebView during device provisioning](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/tools/provision_devices.py#L346), so we could generalize the process.

Anyone have any preference for one solution or the other?

**Comment by jbudorick** [comment]
@case540 @perezju @yoland68 ^^^

I vote for the second option.

**Comment by weableandbob** [comment]
An implementation of option #2 is available at https://codereview.chromium.org/2734023002/ if it's decided to go that route.
