### ISSUE TITLE
Usability problems of results2.html for system health benchmark

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3344]
On [crbug.com/697910#c9](https://bugs.chromium.org/p/chromium/issues/detail?id=697910#c9) a developer ran a trybot and obtained [these results](https://console.developers.google.com/m/cloudstorage/b/chromium-telemetry/o/html-results/results-2017-03-06_00-32-17).

* The page is not very responsive when typing a filter for histrogram names; e.g. when typing "v8:effective" the feedback (letters shown as I type) is slow.
* Clicking the arrows to swap between "story" and "name" to be shown first freezes the tab and takes about 15 seconds to complete.
* Trying to tick "story set repeat" to see values for individual runs of a particular story causes the tab to die ("Aw, Snap! Something went wrong ...").

Context (what I want to do): On `load:social:tumblr` the value for `...:v8:effective_size` is -9.3 MiB on the patch w.r.t. TOT; but the change does not show as "significant". I want to see individual values to figure out why.

@benshayden @eakuefner

**Comment by anniesullie** [comment]
Also @simonhatch  FYI

**Comment by benshayden** [comment]
Thanks for the bug report[s]!

The unresponsive search box appears to be due to the fact that histogram-set-table.updateContents_ unnecessarily calls updateGroups_, which should only be called in `set histograms`. https://codereview.chromium.org/2741453003

Looking into the other issues is taking longer since it's harder to debug tab crashes.

**Comment by benshayden** [comment]
I think I'd like to finish the MVC refactor #3289 , then add Google Analytics metrics to measure usage frequencies, latencies, and crashes #3416 . Hopefully, the MVC refactor should fix most of the responsiveness issues and crashes, and the analytics should help find the rest.
So I'll close this bug in favor of those, if that's ok. Please feel free to reopen this or open a new bug. Thanks!
