### ISSUE TITLE
Unable to remove internal_only flag from builders

### ISSUE THREAD

**Issue by hkjellander** [catapult-project/catapult#3346]
I've been trying to remove the "internal_only" flag from bots at https://chromeperf.appspot.com/change_internal_only for more than a day now, but every time I check back on the page, my changes are reset so it seems something must be failing somewhere.

Example:
```
WebRTCPerf
  webrtc-android-tests-nexus4-lollipop
  webrtc-android-tests-nexus5-kitkat 
  webrtc-android-tests-nexus6-lollipop
  webrtc-android-tests-nexus6-nougat 
```
None of those should be marked internal_only, but I'm unable to change them using that page.

I'm also curious about which is the URL for the "task queue" page where one's supposed to be able to see the progress?

Could it really be that the task queue is several days behind?

**Comment by simonhatch** [comment]
I think this takes a couple days to full work through. Quick check on the appengine dashboard shows the migrate queue has thousands of tasks in it, and growing.

**Comment by hkjellander** [comment]
It's been 3 more days now and these builders are still marked as internal_only. Is it really taking that long?
Is it possible to view this queue statuses if you don't have App engine dashboard access?

**Comment by anniesullie** [comment]
@simonhatch: I think the problem is that it takes a very long time to change all `Row` entities. I *think* I changed it so that we don't actually need to query internal_only state of `Row` anymore, maybe we can flip this to just changing `Bot` and `Test`? We ran out of quota yesterday, and I worry about the expense of migration tasks like this.

**Comment by hkjellander** [comment]
Thanks for looking into this. Does that mean I should redo my operation of removing 'internal_only' from the bots that shouldn't have it?

**Comment by simonhatch** [comment]
Sorry I haven't actually looked into the change Annie suggested yet.

One question for @anniesullie do we need to add those bots to the bot_whitelist first before the change_internal. Kinda poking around add_point_queue and it seems like the test would get reset to internal if its not in the whitelist?

**Comment by anniesullie** [comment]
Yeah, I think there may be a bug if they're not getting added to the whitelist by change_internal?

**Comment by simonhatch** [comment]
I don't see any mention of it in /change_internal_only so kinda sounds like that's the issue. I'll make the change and upload a fix today.

**Comment by simonhatch** [comment]
So this doesn't implement the fix Annie mentions ( #3360 ) but running /change_internal_only should work now at least.

**Comment by hkjellander** [comment]
Thanks simonhatch! I checked now and a few of the bots I previously changed were now updated. I updated the last few now (~5).

**Comment by simonhatch** [comment]
Think this was fixed a while ago.
