### ISSUE TITLE
Totals always be '0' in multi event summary table(analysis view)

### ISSUE THREAD

**Issue by veryzhang** [catapult-project/catapult#3349]
In file below:
catapult/tracing/tracing/ui/analysis/multi_event_summary_table.html
#line 295
`var allEvents = new tr.model.EventSet();
    var rows = [];
    for (var [title, eventsOfSingleTitle] of Object.entries(eventsByTitle)) {
      for (var event of allEvents) allEvents.push(event);
      var row = new tr.ui.analysis.MultiEventSummary(
          title, eventsOfSingleTitle);
      rows.push(row);
    }`

allEvents here is empty, so it can't push anything into itself here.
Then the 'totals' of all events' duration will be 0.

**Comment by benshayden** [comment]
Good eye!
https://codereview.chromium.org/2728373007
Looks like an honest mistake in a complex refactoring change.
