### ISSUE TITLE
Enable no-console eslint rule.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3351]
There are currently 63 calls to console methods in 36 files in tracing, including 8 `*_cmdline.html`.

We've historically advised against calling these methods in code review in the past with varying levels of strength in order to keep the console clean when running tests, but they sneak in. Reviewers are only human.

Recently, however, keeping the console clean has also become vital to ensuring that some vinn-run processes work at all: a stray console.log() deep in extras/ or third_party could mix a fun ascii cat picture in with your carefully computed results and you will have a bad day. map_single_trace_cmdline is careful to tag the MRE_RESULT line, but it's the only one of 8 cmdlines to do so, and it shouldn't need to do that.

I can only think of 2 necessary uses of console.log(), but please LMK if there are others:
 * returning results from the `*_cmdline.html` files
 * printf-debugging.

I propose introducing two new APIs to explicitly support only those two uses:
 * cmdlinePrint()
 * DEBUG()

Presubmit can ensure that cmdlinePrint() is only called from _cmdline.html files, and that DEBUG() is never called in committed code. If a contributor bypasses presubmit, "DEBUG" should be more visible in code review than a humble console.debug.

Simply deleting window.console in base/base.html would invite confused reverts, so I propose replacing console methods with `throw new Error('Please use DEBUG() or throw an Error instead')` with a link to this bug.

@zeptonaut @lpy @eakuefner @fmeawad @chromy @perezju @tdresser WDYT?

**Comment by tdresser** [comment]
Overall, SGTM. 

I'm not convinced that migrating to DEBUG over console.log is worth it though. How often do contributors bypass presubmit?

**Comment by anniesullie** [comment]
Agreed on sgtm except I don't think `DEBUG` is worth it.

**Comment by benshayden** [comment]
Just to clarify, instead of making console inaccessible, the presubmit should check that it isn't used outside of _cmdline.html. Is that right? SGTM if it SGTY.

**Comment by tdresser** [comment]
Yup, that's what I was thinking.

**Comment by eakuefner** [comment]
This all sounds fine to me. I think we should proceed with this fix, but I also wonder offhand how Node and company handle data interchange, and if it's by some mechanism other than standard streams. Not a question to answer right now, but just something I might think about as we move closer to a Node-centric world.

**Comment by zeptonaut** [comment]
Agree w/ others: +1 on enabling presubmit, but DEBUG isn't worth it. I think this can be achieved with eslint's [`no-console`](http://eslint.org/docs/rules/no-console) rule combined with a 

```js
/* eslint-disable no-console */
```

at the top of the _cmdline.html file.
