### ISSUE TITLE
Add more monorail integration with the Release Notes page

### ISSUE THREAD

**Issue by jessimb** [catapult-project/catapult#3353]
As part of #3141, we would like to add extra columns to the Release Notes alerts-table. 

One of the extra columns would include more monorail information about the bug, such as: title, link, owners, status, priority, and labels.
We should probably have a new element that organizes this information nicely, and then we can pull this element into the alert-table's extraColumns feature.

**Comment by anniesullie** [comment]
Might take a look at bug_details.py and bug-details.html. They're pretty ugly right now, but it's a start.

**Comment by jessimb** [comment]
This is done.
