### ISSUE TITLE
Add more bisect information with the Release Notes page

### ISSUE THREAD

**Issue by jessimb** [catapult-project/catapult#3354]
As part of #3141, we would like to add extra columns to the Release Notes alerts-table. 

One of the extra columns would include more bisect information about the alert: more clear status and ability to re-kick a bisect from the Speed Releasing page.

We can either update the existing bisect-status element (thus this would be functionality on /alerts as well), or we can create a new element for use on the /speed_releasing endpoint. 
If we went the new element way, we can pipe it into the table via extraColumns or we can add extra plumbing to allow alerts-table to pick which element to use.

**Comment by eakuefner** [comment]
Archiving; v2spa subsumes.
