### ISSUE TITLE
Dashboard - Change /change_internal_only to only flip bot/test data.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3360]
From @anniesullie in #3346:

I think the problem is that it takes a very long time to change all Row entities. I think I changed it so that we don't actually need to query internal_only state of Row anymore, maybe we can flip this to just changing Bot and Test? We ran out of quota yesterday, and I worry about the expense of migration tasks like this.

**Comment by eakuefner** [comment]
@anniesullie I'm in the process of building corresponding Rows for histograms, and I wondered if this statement means that I shouldn't set internal_only on the Rows that I'm creating. Can you confirm?

**Comment by anniesullie** [comment]
@simonhatch WDYT? It seems to me like there isn't harm in setting it correctly.

**Comment by eakuefner** [comment]
Okay, I'll just set it correctly for now; we can always blow away the rows created during testing if @simonhatch confirms that we really never need to query internal_only of Rows.
