### ISSUE TITLE
Enable eslint's object-shorthand rule

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3361]
I propose that we enable eslint's [`object-shorthand` rule](http://eslint.org/docs/rules/object-shorthand), which discourages things like:

```js
{
  foo: foo,
  bar: baz
}
```

in favor of

```js
{
  foo,
  bar: baz
}
```

This is allowed by Google's internal style guide and recommended by [airbnb's style guide](https://github.com/airbnb/javascript#es6-object-shorthand).

@eakuefner @benshayden @lpy WDYT?

**Comment by benshayden** [comment]
sgtm

**Comment by zeptonaut** [comment]
Anyone interested in helping to enable this rule? @deepanjanroy? @lpy?

**Comment by deepanjanroy** [comment]
I can take this.

**Comment by zeptonaut** [comment]
Thanks Deep!

The main way we've been doing this is to enable the rule in the .eslintrc file, then run `common/eslint/bin/run_eslint --all --extra-args="--fix"` to fix all violations of the rule across the codebase. You might have to follow up with some manual cleanups (if, for example, fixing the instance caused a violation of another rule), but that shouldn't be too bad. Once all of that's done, just upload the CL and send it out for review.

**Comment by lpy** [comment]
I will take this if that's OK to you Deep @deepanjanroy 

I will enable it with the following configuration:

```
{
    "object-shorthand": ["error", "always"]
}
```

**Comment by deepanjanroy** [comment]
Actually yes go ahead. This slipped my mind.

**Comment by lpy** [comment]
Done.

**Comment by zeptonaut** [comment]
This is awesome. Thank you for taking this on!
