### ISSUE TITLE
group_report?rev=xxx grouping broken (?) when CL is impactful

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3369]
V8 recently switched the compiler architecture. In order to easily identify the improvements and regressions we are using the group_report view (https://chromeperf.appspot.com/group_report?rev=455720). Issues found:

1.) The grouping seems to be broken. Improvement alerts with the same revision range and even from the same testsuites and bots are not grouped together.

2.) The default state of the button on the top right is "Show all improvements". That is already the case in the beginning. Clicking once on it changes the button to "Hide all improvements" and nothing happens. Clicking once more on the button changes it back to the initial state but the improvements are not shown anymore.

**Comment by anniesullie** [comment]
@simonhatch

**Comment by natorion** [comment]
Generally, what are the current triggers for the grouping feature? I get this question often and would like to add it to https://docs.google.com/presentation/d/1JBs1dYP_6IPZfAEYGZr2HcWPfvFZjV6bqe1A6NIUqt0/edit.

**Comment by simonhatch** [comment]
I think alert_group specifically filters out improvements for grouping: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/alert_group.py#L197


The requirements to be grouped should be that the ranges overlap, they're the same "kind" of alert (ie. StoppageAlert vs Alert), and they from the same test suite (https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/alert_group.py#L234)


Interesting note reading the code, the AlertGroup class holds a list of test_suites, yet we only ever add 1 suite to.

**Comment by simonhatch** [comment]
Re: The button, should this default to showing the improvements or not?

**Comment by natorion** [comment]
I would expect seeing improvements and regressions because when I am looking at this particular page I am interested in the general impact of it.

**Comment by anniesullie** [comment]
I think most users expect both improvements and regressions, understanding the general impact is the big reason for looking at /rev=XXX
