### ISSUE TITLE
It is hard to differentiate rows with a lot of alerts

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3370]
When I have an alert page with a lot of alerts, it is hard to identify the checkboxes that belog to individual alerts. It would have to either have a filter on the alert/issue page or to alternate the background color for each row in the table.

Example (I was isolating the JetStream alerts and put them into a separate bug):
![vyw72swevqy](https://cloud.githubusercontent.com/assets/7190422/23853311/500414a6-07ec-11e7-919c-254b7fad8193.png)

**Comment by geekodour** [comment]
How about switching the the checkbox column from first column to the last column? along with alternate background color for rows?

**Comment by geekodour** [comment]
Let me know, I'll send a PR to this issue

**Comment by eakuefner** [comment]
Most look-and-feel guidelines [suggest](http://ux.stackexchange.com/questions/5080/should-checkbox-labels-be-to-the-right-or-the-left) that checkbox labels should be positioned to the right of the control for left-to-right languages, so I don't think moving the checkboxes is a good idea.

Zebra-striping is a good idea, though, and I'd support a patch that adds that.

@geekodour please note that we don't use pull requests for code review. Instead, we use Rietveld, and you can read more about how to contribute in [CONTRIBUTING.md](https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md). Also read the section on becoming a committer to learn how to sign Google's CLA for individual contributors.

**Comment by sh4d0wst0rm** [comment]
May be we can try to highlight the complete  row where cursor is currently present  .

**Comment by benshayden** [comment]
Archiving. Both V1 and V2SPA highlight the row on hover.
