### ISSUE TITLE
run_py_devicetests hangs in flag_changer_devicetest.FlagChangerTest

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3374]
There is a missing call to `super(...).tearDown()` [here](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/flag_changer_devicetest.py#L41), so the device used for the test is never released.

This also caused me to wonder, do we run `run_py_devicetests` on any bots? Maybe it works because it has more that one device?

@jbudorick

**Comment by jbudorick** [comment]
They run on the [catapult android trybot](https://uberchromegw.corp.google.com/i/tryserver.client.catapult/builders/Catapult%20Android%20Tryserver).

**Comment by perezju** [comment]
Yeah, it has several devices. That's probably why it didn't get stuck.

Anyway, this should be fixed now.
