### ISSUE TITLE
Dashboard - Should we be using threadsafe: true?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3375]
We have threadsafe: false specified in app.yaml, but this disables concurrent requests and might be causing AppEngine to spin up more instances than we need to handle load or causing us to respond slower than we could.

Believe setting this to true sets default to 8 concurrent requests per instance for python27.

@eakuefner @anniesullie

**Comment by anniesullie** [comment]
For the record, I do not remember the exact reason this was turned off. I'm wondering if there's an easy way to test turning it on. Perhaps there is a way to divert X% of traffic to a threadsafe version and compare performance and error rates?

**Comment by eakuefner** [comment]
@anniesullie There should be, yes. In the versions page, you can set up percentages and all of that.

**Comment by eakuefner** [comment]
("Split Traffic" is the button)

**Comment by anniesullie** [comment]
Yep! But do we know how to:

  * Compare error rates
  * Get an analysis report comparing the two versions from Cloud Trace?
  * See the task queue delay dashboards we have set up on stackdriver for both versions?

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917876
