### ISSUE TITLE
Dashboard - Cleanup main directory.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3376]
Coming out of: https://codereview.chromium.org/2732193003/

Main directory starting to get a little crowded, maybe time to think about how to structure the code a bit more.

**Comment by benshayden** [comment]
Archiving. Launching V2SPA will involve cleaning out old endpoints, let's revisit then.

**Comment by simonhatch** [comment]
I'd still like to do this.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917882
