### ISSUE TITLE
Data stoppage from January alerted in March

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#3386]
My rotation "Chromium AV Perf Sheriff" just received data stoppage alerts because of graphs that haven't been updated since January. 

Here's the alert text: https://docs.google.com/document/d/1gJ_3tfm6dMcf7WiFYP51pJ-smvjR55KwETQ0hI7RkQQ/edit?usp=sharing 

It seems like this is a little be late to get the alert (Although we aren't worried about it since the machine was simply updated). Is this a known issue?

Thank you!

**Comment by simonhatch** [comment]
Yep! #3365

**Comment by CalebRouleau** [comment]
Thank you!
