### ISSUE TITLE
Dashboard should make it easier to explore related test path

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3405]
Context: any time a regression happen (e.g: https://chromeperf.appspot.com/group_report?bug_id=701829), people usually want to see whether other metrics or other pages on the regressed benchmarks also change. Or sometimes people want to see what happen on other bots.

After trying to click around on clickable part of the test path, it seems like this feature is sort of support, but not in a very intuitive way.  
Clicking on "pcv1-cold" in  "ChromiumPerf/linux-release/page_cycler_v2.intl_es_fr_pt-BR / timeToFirstContentfulPaint_avg / pcv1-cold / http___www.ebay.es_sch_i.html?_sacat_382__trkparms_clkid%3D6548971389060485883__qi_RTM1381637" shows me all the graphs that starts with "ChromiumPerf/linux-release/page_cycler_v2.intl_es_fr_pt-BR / timeToFirstContentfulPaint_avg / pcv1-cold /". This is great, but then I am not sure how to get from this to previous view of only a single graph. Also there is no way for me to change the bot platform here.

Proposal: each separate part in the test path in this report page should be a drop down for me to choose just like the "Browse graphs" view.

![graph](https://cloud.githubusercontent.com/assets/911877/24000833/bee148d8-0a32-11e7-953d-ea41770716b2.png)

@anniesullie

**Comment by simonhatch** [comment]
There's a similar request that might conflict a bit with this, #2641 the plan there is to have the title auto-populate the picker.

**Comment by benshayden** [comment]
If each test path component in chart-title becomes a drop-down, that seems awfully similar to test-picker, so this seems to agree with offline discussions about merging test-picker with chart-title.

At the speed services weekly before last, we discussed sparklines in tabs. Users can click to select a tab such as Bots or Stories, scroll through sparklines, and click on a sparkline to promote it to a full chart, rinse and repeat. I'll try to have a demo this week.

**Comment by benshayden** [comment]
[This demo](https://dev-benjhayden-5d4212e2-dot-chromeperf.appspot.com/report?sid=4a565ec69501908a575b892167ae573f3db5b077f34d3a2c2040e7cc364f8641)
- offers tabs of related timeseries sparklines for memory measurements
- draws a vertical line through all sparklines when you mouse over a point in the chart
- uses the same colors in sparklines as in the chart
- hides error bars from sparklines to keep them simple
- automatically updates the sparklines when you change the chart by zooming, panning, or enabling/disabling timeseries
- promotes a sparkline to a full chart when you click on it (with cursor:pointer to afford this)
- closes the open tab of sparklines when you click the emdash on the right edge of the tab strip

Followups can add tabs of sparklines for Bots and Subtests. When more benchmarks are uploading via the Histogram Pipeline, we can remove the hard-coded memory measurement relationship maps and generalize these tabs to support all metrics' relationships.

![](http://imgur.com/9hVRuYP.png)

Any thoughts before I mail it out for review? @simonhatch @eakuefner

**Comment by tdresser** [comment]
Nits: 
* There should be a way to expand the related graphs more, or perhaps they should only expand fully.
* When minimized, clicking on the header looks like it should do something, but doesn't.

**Comment by benshayden** [comment]
Closing this in favor of more specific followup bugs: #3913 #3854 #3852 #3836 #3835 
If sparklines turn out to be the wrong approach, we can file a new bug.
