### ISSUE TITLE
Formalize SeriesGroup

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3406]
I have the following report created: https://chromeperf.appspot.com/report?sid=586693eb71389e83b46647fa97f2346c35a9a7cc3e743a4b2bbd0dcc22366d71

![gb1xpk7hcgw](https://cloud.githubusercontent.com/assets/7190422/24002174/58f7a534-0a60-11e7-8f55-e76d6c9d276c.png)

When I open the URL in a new tab the graphs are all in a chart each and not working properly:
![foe1acamgio](https://cloud.githubusercontent.com/assets/7190422/24002228/7bb5bdae-0a60-11e7-9a38-6b0526d05a2c.png)

**Comment by natorion** [comment]
I am logged in btw.

**Comment by anniesullie** [comment]
@eakuefner can you check if this is related to https://codereview.chromium.org/2716683004/ ?

@natorion does this seem like a new bug today?

**Comment by natorion** [comment]
I think this is not older than a day. I noticed this today as our screen suddenly is showing a chart for each graph.

**Comment by anniesullie** [comment]
I locally reverted @eakuefner's CL, chart looks different: https://dev-sullivan-185a732f-dot-chromeperf.appspot.com/report?sid=586693eb71389e83b46647fa97f2346c35a9a7cc3e743a4b2bbd0dcc22366d71

I'm going to push this version live and revert the CL. @eakuefner can you take a look?

**Comment by natorion** [comment]
Thanks.

**Comment by eakuefner** [comment]
Thanks @anniesullie, and thanks @natorion for reporting. Looks like, with my patch, we're deserializing page states slightly wrong. I'll figure out the fix and upload it.

**Comment by eakuefner** [comment]
Two problems here:

1. addChart formerly was able to take multiple series groups, but I refactored addChart to take a single exploded series group. This was just a conceptual misunderstanding.
2. The functionality that converts legacy chart states into these exploded series groups was not tested, nor easy to test as factored.

To fix this, and make sure that this kind of thing is well-tested, I plan to do as follows:

1. Introduce a `SeriesGroup` class that contains the `mainPath`/`selectedPaths`/`unselectedPaths` that we were passing to addSeriesGroup2 in my CL. `SeriesGroup` will have a `fromLegacyChartState` method that will be broken out roughly as follows:
  1. Build a pair of request param dicts to /list_test for selected and unselected tests. This will be trivial to test.
  2. Actually execute the request using fetch, returning a promise. It should not be necessary to test this.
  3. Pass a list of promises to a method that actually calls the `SeriesGroup` constructor. This should be fairly easy to test as well, by using Promise.resolve in the tests.
2. In the reverted CL, make addChart take a list of SeriesGroups. With this, we formalize a "chart" as a collection of series groups, which was implicit before but will be explicit now.

@benshayden I would appreciate your review on step 1 as this uses the mockless approach to testing that we were talking about recently.

**Comment by eakuefner** [comment]
Okay, actually, I think this might be able not to be reviewed by Ben, as it's a little less innovative than I thought, having written it out. For now, I'm testing the request builder, but nothing about whether the correct requests are performed, and I think that would have been sufficient to catch the bug that @natorion is talking about.

**Comment by eakuefner** [comment]
Graphs look the same in https://dev-eakuefner-7b3ab91d-dot-chromeperf.appspot.com/report?sid=586693eb71389e83b46647fa97f2346c35a9a7cc3e743a4b2bbd0dcc22366d71

As a side effect, it looks like this actually fixes a zoom bug; if you look in production, the graphs displayed don't match the zoom region, but here, they do.
