### ISSUE TITLE
No changelog/commit ranges shown anymore

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3409]
No Chromium or V8 commit range is shown anymore:

![11bhctw8mrw](https://cloud.githubusercontent.com/assets/7190422/24041959/17149acc-0b10-11e7-8245-f9dc1b881620.png)

**Comment by natorion** [comment]
This still worked two hours ago.

**Comment by anniesullie** [comment]
@simonhatch can you take a look? I have not done any pushes this morning.

**Comment by nedn** [comment]
Dashboard uploading log shows that the v8 revision was uploaded: https://luci-logdog.appspot.com/v/?s=chrome%2Fbb%2Fchromium.perf%2FLinux_Perf%2F470%2F%2B%2Frecipes%2Fsteps%2Fspeedometer_Dashboard_Upload%2F0%2Fstdout

So this is a problem with dashboard server

**Comment by simonhatch** [comment]
Oh weird this only shows up if you're not logged in. Seems like the revision_info is empty that's getting passed back from /report.

**Comment by simonhatch** [comment]
This is working now, tracked it down to missing data in the revision_info stored_object. Annie pointed me to the group where changes to these are logged and I was able to restore it. Deeper mystery is how it got overwritten now, there were no changes logged last night to that object, last one was on March 15 in the morning.

**Comment by anniesullie** [comment]
Looks like it is the same issue resolved in https://codereview.chromium.org/2758273002/ ?

**Comment by simonhatch** [comment]
Yeah think it's all the same underlying issue, sorry about that!

**Comment by natorion** [comment]
I think this is fixed.
