### ISSUE TITLE
container-to-container drag is hosed

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3418]
With my recent CL, I broke the functionality whereby you can drag a series group from one chart container to another, which I didn't even realize was possible until I read the code in chart-legend that facilitates this. In discussion with @simonhatch it seemed like he too only recently became aware of this functionality, and in a similar way (stumbled across it while fixing something else).

My strong preference is to kill it, considering that:

1. It's not especially good UX
2. People don't seem to know it's a thing
3. It's suboptimal from a performance perspective and fixing that would be nontrivial and P4 (in particular, it does all the graph_json XHRs again, which is :-1:, and in order to do this in the new world would _also_ have to do list_tests requests to resolve the test_path_dicts all over again).

@anniesullie WDYT?
@benshayden FYI

**Comment by anniesullie** [comment]
I think it's fine to kill it. We'd still be able to drag from the menu at the top to a chart, right?

**Comment by eakuefner** [comment]
Yes.

**Comment by eakuefner** [comment]
CL: https://codereview.chromium.org/2758033002

**Comment by eakuefner** [comment]
We fixed the glitch.
