### ISSUE TITLE
The importer progress shows what just finished instead of what's running

### ISSUE THREAD

**Issue by jreck** [catapult-project/catapult#3420]
The importer progress box displays the message for the previous stage instead of the current one. If you import a huge trace it will for example get stuck on "importing clock sync markers" even though it's the importEvents() that's slow.

This is due to progressMeter.update() being called in the same task as the thing it's about to run, so the DOM update doesn't happen until after the task completes.

**Comment by fmeawad** [comment]
@lpy

**Comment by lpy** [comment]
Is it done?
