### ISSUE TITLE
Starting a bisect ends in an error 500

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3421]
Repro:
1.) Open https://chromeperf.appspot.com/report?sid=52526171df058db7556268f29628a5fb8433821fd889f035360b5abfdee7722a&rev=457752
2.) Click on the triaged alert shown
3.) Click Bisect
4.) Error 500 shown in the status pane on the bottom left.
![9shqjo7jxfy](https://cloud.githubusercontent.com/assets/7190422/24092336/fce6047a-0d4d-11e7-930d-12480320d537.png)

**Comment by simonhatch** [comment]
Think this was fixed with: https://codereview.chromium.org/2758273002/

Can you try again?

**Comment by natorion** [comment]
Closing according to #3422
