### ISSUE TITLE
Chromeperf is non-functional

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3422]
1.) Starting a Bisect results in a 500
2.) Test suite selection on https://chromeperf.appspot.com/report is not possible (the bot selection never appears
3.) Report in https://bugs.chromium.org/p/chromium/issues/detail?id=703047 cannot be opened

Tried it out on two different computer with different accounts. Same result.

**Comment by natorion** [comment]
This seems to work now.

**Comment by natorion** [comment]
Bisect still does not work.

**Comment by schuay** [comment]
Starting bisects works again for me, thanks!

**Comment by natorion** [comment]
Thanks folks.

**Comment by simonhatch** [comment]
Gonna close this out, working again, sorry!
