### ISSUE TITLE
Some bots are suddenly private

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3423]
It seems that since this weekend a lot of bots have gone private. We used to display https://chromeperf.appspot.com/report?sid=dacae5bee5602349868539c19c00afbaa35ef42024e13cec1b35fda91883e166 on a Screen (speedometer with some bots) and now this does not work anymore because "Failed to fetch graph data.
Note that some data is only available when logged in.". It seems the only available bots when one is not logged in are very, very few. Not even the linux-release one.

Was this intentional?

**Comment by simonhatch** [comment]
Not intentional no, I'll try to figure out why they're private now.

**Comment by eakuefner** [comment]
@simonhatch can this be closed?

**Comment by simonhatch** [comment]
Indeed!
