### ISSUE TITLE
Approve ES2017 Array.includes()

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3424]
ES 2017 introduces an `Array`/`String.includes()` method that allows you to write:

```js
if ('text1234'.includes('xt12')) {
  ...
}
```

instead of 

```js
if ('text1234'.indexOf('xt12') !== -1) {
  ...
}
```

[This new syntax has already slipped into the codebase without causing any problems.](https://cs.corp.google.com/search/?q=p:github+f:%5Ecatapult-project/catapult/+indexof.*!%3D%3D%5C+-1+f:.html&m=100&det=matsel&type=cs) Are there any objections to marking it as approved?

@eakuefner @benshayden

**Comment by zeptonaut** [comment]
Also relevant: the feature is widely implemented (Chrome 47, Firefox 43, Edge 14, Opera 34, Safari 9).

**Comment by benshayden** [comment]
sgtm, thanks!

(Looks like the link is for indexOf, not includes)

**Comment by lpy** [comment]
LGTM.
BTW, I guess we really shouldn't post any corp link publicly.

**Comment by zeptonaut** [comment]
@lpy This is definitely the policy. I'm going to start a conversation about this in an internal email thread to figure out how we should handle this wrt. code search, code review, etc.
