### ISSUE TITLE
Refactor math utilities in base

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3425]
Currently, there are several files in base that provide math utilities:

 * bbox2.html
 * math.html
 * quad.html
 * rect.html
 * running_statistics.html
 * statistics.html
 * piecewise_linear_function.html
 * range.html
 * sorted_array_utils.html

It would be easier to understand both these related files and the rest of base/ if these files were moved to a subdirectory.

**Comment by chromy** [comment]
Something like this: https://codereview.chromium.org/2764863002/?

**Comment by benshayden** [comment]
Wow, yes, thanks!
How many files are left in base after that CL?
Please send that to me and charliea, and self-assign this bug. I'll probably stamp it quickly, but I'd like to make sure that he doesn't have any concerns.
Thanks!

**Comment by chromy** [comment]
Cool! I added you and charliea to the review :)

Afterwards there would be 30 source files and 23 test files for 53 total. These are the ones that are left:
```
assert_utils.html
base.html
base64.html
category_util.html
color.html
color_scheme.html
event.html
event_target.html
extension_registry.html
extension_registry_base.html
extension_registry_basic.html
extension_registry_type_based.html
fixed_color_scheme.html
guid.html
in_memory_trace_stream.html
interval_tree.html
iteration_helpers.html
multi_dimensional_view.html
raf.html
scalar.html
settings.html
sinebow_color_generator.html
task.html
time_display_modes.html
timing.html
trace_stream.html
unit.html
unit_scale.html
utils.html
xhr.html
```

**Comment by chromy** [comment]
Done!
