### ISSUE TITLE
Dashboard - Optimize DeprecatedTests MR

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3428]
Getting stoppage alerts sometimes a month later, and @anniesullie mentioned the s5 bots still haven't been marked deprecated.

Quick look in here looks like the MR runs over every TestMetadata entity, does a list_tests.GetTestDescendants() call, and queues up tasks to delete Row data if there are no descendants.

Wonder if it'd be faster to somehow only run the MR at the suite level, query for list_tests.GetTestDescendants() once, and do the rest of the logic somewhat in parallel.

**Comment by anniesullie** [comment]
Another note: there is no good reason for this to be a mapreduce. Having it be a mapreduce makes it really easy to code up in a way that there is one function run per test, and if we are calling list_tests.GetTestDescendants() for every single test, that's not a good thing. Should consider a taskqueue-driven option here.

**Comment by simonhatch** [comment]
Also, was poking more at this last night and discovered we have at least 4 mapreduces running in parallel, with a hundred or so still in the running state. Not clear if they're just giving priority to the newer ones, or stalled out in some way, or what's going on with them, but they're still active. The oldest is nearly a year old and still going. Spoke to @anniesullie this morning to confirm, this whole thing is a mess.

**Comment by simonhatch** [comment]
I think I have some cycles to start on this.

**Comment by simonhatch** [comment]
This seems to be mostly working now, so next steps are:

- Get rid of the old MR code (I was having trouble getting gcloud to deploy mapreduce.yaml, so maybe need to switch back to the old AppEngineSDK temporarily?)
- Integrate some StackDriver metrics reporting and add alerting?

**Comment by benshayden** [comment]
Is this done?

**Comment by simonhatch** [comment]
MR code is gone, never got around to any stackdriver metrics. Perhaps we could add some log-driven metrics, any idea if you can alert on those?

**Comment by benshayden** [comment]
Let's pick the metrics up in https://bugs.chromium.org/p/chromium/issues/detail?id=867060
