### ISSUE TITLE
Analytics metrics for dashboard

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3430]
The dashboard currently contains a dom-module `load-analytics` to measure page loads, but no analytics to measure what users do after the page loads.
If we're going to be removing UI features, then it would be good to be able to know how often they are used.
What events could be tracked?

 * test-picker
    * "ADD" onclick 
    * Dragging the cardinal rose to add a timeseries to an existing chart
 * chart-legend
    * collapse/expand
    * toggle less/more
    * toggle a timeseries
    * clicking the information `i`
 * chart-container
    * hover a point
    * click a point
    * mousebuttonup in the minimap
    * close a chart
    * breakdown chart load by test path
 * <what else?>

IIRC, analytics also provides some way of seeing how often types of actions follows other types of actions.

@zeptonaut @anniesullie @eakuefner

**Comment by zeptonaut** [comment]
I support the general idea of knowing usage before removing features, but defer to @eakuefner @anniesullie and @simonhatch completely on dashboard UI in general.

**Comment by simonhatch** [comment]
@natorion

**Comment by benshayden** [comment]
Ethan is updating the account number in the code, Hannah is adding tr.b.Timing calls.

**Comment by benshayden** [comment]
@hannahtwiggsmith recently [landed some metrics](https://codereview.chromium.org/2917853003). I'll take over adding more.
