### ISSUE TITLE
The histogram produce too many statistics by default

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3435]
By default, it produces "avg, count, max, std, min, std, sum". 
And because we don't have a code review mechanism to know which specific data point a metric will produce, people usually ends up having more metrics than they need.

An example is the case of trace_import_duration, which should have only 1 data point per trace, and I am sure that @zeptonaut only cares about the "avg" value here.
Should we change the default to be only producing avg?

@tdresser @eakuefner @benshayden 

![download](https://cloud.githubusercontent.com/assets/911877/24208726/bfa58b4a-0efa-11e7-9aa4-c88db24d05ec.png)

**Comment by nedn** [comment]
![download](https://cloud.githubusercontent.com/assets/911877/24208698/a4b2a2d2-0efa-11e7-84d8-d7e83fcbab4a.png)

**Comment by simonhatch** [comment]
+1 if we're storing these on rows, probably best to start with the minimal set possible and let interested users expand.

**Comment by zeptonaut** [comment]
My vote is for only "_avg" by default and to let people expand as necessary. From what I've seen, "_avg" is by far the most common thing that people are after, although others are certainly useful at times.

**Comment by benshayden** [comment]
See also https://github.com/catapult-project/catapult/issues/3380 and https://github.com/catapult-project/catapult/issues/3440

**Comment by eakuefner** [comment]
Archiving.
