### ISSUE TITLE
Dashboard trace button needs a new name

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3438]
The dashboard has two features in the tooltip:
 * A link to the trace collected during the benchmark in cloud storage
 * A button to re-run the benchmark at that revision as a perf tryjob in order to get a trace.

These are both called "trace". The naming is confusing, the button name should be more clear.

@nedn @tdresser @simonhatch @eakuefner @benshayden

**Comment by nadia39** [comment]
I would like to contribute to this issue.
I need to contribute to an open source project.
Where is the file I need to change?

**Comment by anniesullie** [comment]
You'd need to change it here: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/trace-button.html#L40

Please read the contributor's guide first: https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md

**Comment by SapanaJadhav** [comment]
Hi anniesullie, i would like to tackle with this issue.

**Comment by Kwantem** [comment]
Hello I noticed that this issue is still open. I would like to tackle this issue and help to start clearing the board.

**Comment by anniesullie** [comment]
Whoops, sorry this was fixed in b3b786c1974dc5d99f9abf9b707616a1a6f27be8.

**Comment by SapanaJadhav** [comment]
Yes I saw, thanks
