### ISSUE TITLE
Generalize request memoization pattern

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3441]
As described to @simonhatch and implemented initially by @jessimb in https://codereview.chromium.org/2750223003, we have started to use an approach of using a map of promises to allow us to memoize the results of the small requests we're increasingly making throughout the dashboard in an efficient, asynchronous way.

One major side effect of using this pattern is that, by allowing the map to return promises, it becomes possible to define a hook that can populate the map with pre-resolved promises, so that TDD of elements that use this approach becomes easily possible: simply prepopulate this map, then simulate your actions, then make your assertions. No mocks or libraries required.

I'm using this pattern in https://codereview.chromium.org/2767433002, and in an effort to get that done as soon as possible, I'll create yet another singleton instance of this pattern in that file, but we want to generalize this. So after I wrap that up, I want to:

1. Write a doc to describe this pattern in general
2. Figure out how to deal with notions of cancellation
3. Implement the generalization and replace our two implementations with instances of this new class.

**Comment by benshayden** [comment]
Step 3 is done, so here is what still needs to be done:

 * Documentation
 * Figure out cancellation.

Would the jsdoc in AsyncMap suffice for documentation?

**Comment by eakuefner** [comment]
Yes, I think so, and I also think that cancellation can be a fresh bug.
