### ISSUE TITLE
Standardize test path handling on the client side

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3443]
As part of the work on rolling out use of the new and improved `test_path_dict` mode of `/list_tests`, we've been inserting code in a number of places to deal with the output of this endpoint, which is good for a great many different use cases. At the same time, we have a lot of code for mangling test paths (e.g. in chart-container, for computing legends, and similarly in https://codereview.chromium.org/2767433002 for computing picker items), and a desire to #3441 globally for dealing with "I need to resolve some test paths".

After #3228 is fixed, this should be one of the things we revisit: how much of the code that does this stuff can we simply standardize into a module?

Also, to anticipate the question of whether this logic should happen on the serverside instead, I say no, as that will keep the endpoint simple and the relationship between the client's needs for fully-qualified and/or partial test paths clear (I start with a single test path returned by the server and chop it up according to my needs, vs. I request different parts of the same data).

**Comment by benshayden** [comment]
V2SPA uses descriptors instead of test paths.
