### ISSUE TITLE
No way to access revision ranges from perf dashboard

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3448]
Steps to reproduce: 

1. Go to any graph on the perf dashboard (e.g. https://chromeperf.appspot.com/group_report?bug_id=704182)
2. Click on a data point on the graph
3. Click on the revision range associated with that data point

**Expected**: See the list of patches associated with that revision.
**Actual**: Get a sad robot page.

![sad_robot](https://cloud.githubusercontent.com/assets/1407397/24359687/11fc1e46-12d3-11e7-9089-e6285b934270.png)

It seems this is true for whichever revision range you click on: they all result in 404s.

Marking this as P0 because it has pretty severe implications for using the perf dashboard.

FYI @simonhatch

**Comment by anniesullie** [comment]
I can't repro; looks like you're having a login issue?

**Comment by simonhatch** [comment]
Works fine in incognito too, so not sure what the problem is.

**Comment by zeptonaut** [comment]
Closing as WontFix. I can open it fine w/ my personal account, but unable to open it with my google.com or chromium.org accounts. I'll continue debugging on my end.
