### ISSUE TITLE
Grouping in tracing gc_objects_stats_table broken

### ISSUE THREAD

**Issue by mlippautz** [catapult-project/catapult#3457]
The code there assumes that the instance types and their groupings are constant, mentioning to emulate a list from a custom viewer. In fact, the custom viewer treats any entries that are non-existent in the groups as a group itself. This is different from skipping the entries by relying on stable groups.

This breaks as soon as instance types change on the producer side of the tracer. We just figured this out while having a deep look into several trace files. What should actually happen is that we iterate the keys in the dump and only group those that have an entry in some groups map. 

https://cs.chromium.org/chromium/src/third_party/catapult/tracing/tracing/ui/extras/v8/gc_objects_stats_table.html?q=gc_objects_stats_table&sq=package:chromium&dr

**Comment by lpy** [comment]
This is fixed.
