### ISSUE TITLE
Move breakdown creation out of renderer helper

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3459]
We should move the breakdown stuff that's currently in chrome_renderer_helper into the loading metric, so that it computes its own breakdowns just like the v8 metric does.

@benshayden

**Comment by maxlgu** [comment]
Have been fixed in #3316
Code review:
https://codereview.chromium.org/2789573002/

Accoding to discussion in the code review. Breakdown generation has been moved to breakdown_tree_helpers instead of loading_metric
