### ISSUE TITLE
Use the same colors for graphs when the same report is opened

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3462]
e.g. I have the following report: https://chromeperf.appspot.com/report?sid=dacae5bee5602349868539c19c00afbaa35ef42024e13cec1b35fda91883e166

When I open the report the first time it looks like this:
![6xneqhxssmt](https://cloud.githubusercontent.com/assets/7190422/24491266/c84a66b2-1526-11e7-8c33-03b370c86413.png)

Now I hit refresh in the browser or open the report on another machine/window and suddenly the same report looks like this:
![sd0qatrv9f4](https://cloud.githubusercontent.com/assets/7190422/24491302/ed0825de-1526-11e7-9829-df6ca431ae79.png)

Please notice how the color of the graphs swapped. That is confusing when one wants to share a graph or display it on a screen. Or if you simply reopen the graph on another page and suddenly your mental image is wrong because the colors are different.

**Comment by benshayden** [comment]
I'll go ahead and land the fix without a test, which is blocked on making the XHRs asynchronous. (The test would test that specific test-paths got specific colors, but that would happen as long as the XHRs are synchronous.)
