### ISSUE TITLE
CPU Clock Domain does not collapse properly without Chrome Trace

### ISSUE THREAD

**Issue by randalnephew** [catapult-project/catapult#3463]
It cannot find a path from the CPU tracing agent clock domain to the telemetry clock domain.
To reproduce this problem, just enable the CPU trace agent on the power.idle_platform benchmark once it lands. 

This is a problem for the idle platform power benchmark I am writing. It is intended to run without launching chrome, so we can determine background system power and help find sources of noise.

**Comment by zeptonaut** [comment]
It looks like what's happening is that we're not specifying the clock domain for the CPU agent trace, so it's defaulting to UNKNOWN_CHROME_LEGACY. Based on the fact that it uses the Python trace_time.Now() and is always running on the same machine (heck, even in the same process) as Telemetry, we should just explicitly specify the TELEMETRY clock domain.
