### ISSUE TITLE
Perf Dashboard: Error creating bug!

### ISSUE THREAD

**Issue by SummerLW** [catapult-project/catapult#3466]
Chrome version: 56.0.2924.87 (Mac)
URL: https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down

Please copy and paste any errors from JavaScript console (Command+Option+J to open):
Error creating bug!

Please describe the problem:
When I tried to create a new bug on the Chrome Performance Dashboard, it always showed me that "Error creating bug!" and I could not create any bug.

**Comment by anniesullie** [comment]
@simonhatch @eakuefner

**Comment by simonhatch** [comment]
I see an error in the logs about <someone>@gmail.com, are you logged in with the wrong account?

**Comment by benshayden** [comment]
Archiving.
