### ISSUE TITLE
Broken "Buildbot stdio" links on perf dashboard

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3472]
For example hovering over points on [this graph](https://chromeperf.appspot.com/report?sid=da780d2ad605d0faedd6e10579e4dd4652d8395fd3b7f39de9ba83823a6c5173), some random "Buildbot stdio" link points to:

```
https://luci-logdog.appspot.com/v/?s=chrome%2Fbb%2Fchromium.perf%2FMac_Retina_Perf%2F506%2F%2B%2Frecipes%2Fsteps%2Fmemory.desktop%2F0%2Fstdout
```

But the correct link should be:

```
https://luci-logdog.appspot.com/v/?s=chrome%2Fbb%2Fchromium.perf%2FMac_Retina_Perf%2F506%2F%2B%2Frecipes%2Fsteps%2Fmemory.desktop_on_Intel_GPU_on_Mac_on_Mac-10.11%2F0%2Fstdout
```

I assume this affects all swarmed bots?

@anniesullie @simonhatch

**Comment by anniesullie** [comment]
This is tracked in crbug.com/663901

**Comment by zeptonaut** [comment]
Closing this given that it's tracked elsewhere.
