### ISSUE TITLE
No "revision navigator" on the bottom of a chart

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3474]
e.g. https://chromeperf.appspot.com/report?sid=1fa17bc31b0af720d548c3a58560396b2c642ccd0d099b0e59d7c3924c518ae6

I can't navigate to previous revisions etc. Reloading or constructing the report from scratch did not help.

![vc5uwmguhe7](https://cloud.githubusercontent.com/assets/7190422/24756267/69784368-1add-11e7-9c17-0c6f6b60273a.png)

**Comment by natorion** [comment]
This also happens with other reports like https://chromeperf.appspot.com/report?https://chromeperf.appspot.com/report?sid=1be638d9f575cfb937fab7d6ea8c133704cf8b2b1a5929a722ac21baf7cec8ad&start_rev=36493&end_rev=10000000000000.

cc @anniesullie @simonhatch @eakuefner

**Comment by simonhatch** [comment]
Console has an error:

Uncaught SyntaxError: Unexpected token N in JSON at position 368125
    at JSON.parse (<anonymous>)
    at HTMLElement.onLoadGraph (chart-slider.html:130)

I'll try to see why that's happening.

**Comment by simonhatch** [comment]
So there's a NaN in the json send by /graph_revisions. Quick check on StackOverflow suggests this isn't a valid thing, http://stackoverflow.com/questions/15228651/how-to-parse-json-string-containing-nan-in-node-js. Not sure what to send in this case, anybody have opinion on this?

**Comment by anniesullie** [comment]
Does `null` cause errors or visual glitches?

**Comment by simonhatch** [comment]
The chart-slider shows up but /graph_json fails in _GetFlotJson() now if you try to scrub to the range with the null value.

**Comment by anniesullie** [comment]
I think maybe zeroing it out is the best thing to do. It will probably look like gaps in the data, which is correct.

**Comment by simonhatch** [comment]
Sigh, linked wrong bug in description, https://codereview.chromium.org/2827993003/
