### ISSUE TITLE
Device dropping offline should raise DeviceUnreachableError

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3476]
When a device becomes unresponsive adb (version 1.0.32) returns

```
error: device 'abcd1234' not found
```

and an exit status of `1`.

On [adb_wrapper.py](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/sdk/adb_wrapper.py#L256) this is reported as an `AdbCommandFailedError`.

It would be preferable, however, to raise the more specific `DeviceUnreachableError`.

This will make it easier to gather stats and investigate the issue of devices dropping offline on bots.

@jbudorick

**Comment by jbudorick** [comment]
SGTM. My primary concern will be the places that handle both AdbCommandFailedError and AdbCommandTimeoutError but not DeviceUnreachableError.

After doing this, we could look at doing some more interesting things w/ DeviceUnreachableError, e.g. having some layer in devil (maybe a new one around DeviceUtils) automatically wait some length of time for a device to come back.

**Comment by perezju** [comment]
> SGTM. My primary concern will be the places that handle both AdbCommandFailedError and AdbCommandTimeoutError but not DeviceUnreachableError.

Good point. Will have that in mind and check for clients trying to catch these exceptions.

**Comment by pasko** [comment]
An interesting application for DeviceUnreachableError would be to catch it on higher levels, not in devil (recipes?), wrap the test and notify the infra that the device flakes. Currently in tools/cygprofile we don't distinguish between wrong adb commands (i.e. more likely a developer issue) and devices unreachable (i.e. troopers need to look at it).

WDYT?

**Comment by jbudorick** [comment]
In many cases (though perhaps not in tools/cygprofile?), we already do something like that via [the device blacklist](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/device_blacklist.py) & [device_monitor.py](https://github.com/catapult-project/catapult/blob/master/devil/devil/android/tools/device_monitor.py), eventually resulting in the device tickets visible in [g/cit-android](http://g/cit-android). Determining what belongs on the blacklist already is the responsibility of higher-level scripts (e.g. [the test runner](https://codesearch.chromium.org/chromium/src/build/android/pylib/local/device/local_device_environment.py?rcl=82dacd2fe4b344aef399c25f0f186f435bac888d&l=137)).

DeviceUnreachableError does give client scripts a bit more info, though I imagine that most of them will want to blacklist the device in question regardless.
