### ISSUE TITLE
Add ability to disable bisect on a per-graph basis

### ISSUE THREAD

**Issue by agrieve** [catapult-project/catapult#3478]
E.g. for Chromium resource_sizes alerts:

The normal case is that there is only one commit in the blame list, so I know who to blame. I click "file bug", assign the owner and remove RVG.

Later, once bisect is done, it adds a big comment that buries the more useful initial comment, and adds back the RVG label (which I never want since this is an upstream graph).

There's also been a couple times when I assign it to the most relevant person, and then the bisect bot comes and assigns it to the author of the commit (which is not always the right person).

**Comment by anniesullie** [comment]
@simonhatch Maybe we could just not bisect if we know there's only one revision in the range?

**Comment by simonhatch** [comment]
That seems pretty reasonable, shouldn't be kicking off bisects in that case anyway. @agrieve wdyt?

**Comment by agrieve** [comment]
Sounds good to me!

**Comment by agrieve** [comment]
Not sure this is working. E.g., just filed this one:
https://bugs.chromium.org/p/chromium/issues/detail?id=722423

And a bisect job was created.

**Comment by simonhatch** [comment]
Ah this is the automated kickoff, that'll need to be disabled.

**Comment by agrieve** [comment]
Wondering if this will be prioritized soon?

**Comment by simonhatch** [comment]
I'll try to take a look at this soon.

**Comment by simonhatch** [comment]
@anniesullie @eakuefner 

Revisiting this, thinking about it a bit, maybe an easy solution would be simply to pass a bool to /file_bug to disable the automated bisect if the range is too small (as we did with the bisect button above).

**Comment by anniesullie** [comment]
Yeah, that works for me.

**Comment by agrieve** [comment]
Looks good! Thanks!
