### ISSUE TITLE
Eslint checks on trybot don't match local checks

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3479]
I got a catapult CL [1] which failed presubmits on the CQ [2]. I see errors like
```

** Presubmit Messages **
If this change has associated Catapult and/or Rietveld bug(s), add a "BUG=<bug>(, <bug>)*" line to the patch description where <bug> can be one of the following: catapult:#NNNN, v8:NNNNNN, angleproject:NNNNNN, chromium:NNNNNN.

** Presubmit ERRORS **
Found JavaScript style violations:

eslint found lint errors:

/b/build/slave/presubmit_catapult/build/catapult/experimental/trace_on_tap/background.js
  117:5  error  Expected { after 'if' condition  curly

/b/build/slave/presubmit_catapult/build/catapult/experimental/trace_on_tap/popup.js
  66:9  error  Expected { after 'if' condition  curly
  79:5  error  Expected { after 'if' condition  curly
```

But I don't get the same locally (I develop on OSX).
If I run git cl presubmit --force, or just 
```
~/code/catapult (traceontap @ origin/master +1) primiano-macbook 20:41:52 10/04
$ common/eslint/bin/run_eslint --paths experimental/trace_on_tap/*.js
```
I don't get anything (and if I screw up something I get some lint errors).

So it looks like the CQ is using different lint rules?

@benshayden ideas why?

[1] https://codereview.chromium.org/2516893003
[2] https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Presubmit/builds/6811/steps/presubmit/logs/stdio

**Comment by anniesullie** [comment]
@eakuefner

**Comment by eakuefner** [comment]
Primiano, it looks like you just didn't rebase. Applying the patch set with the errors at ToT causes the curly errors to show up locally for me. New rules are constantly being enabled in .eslintrc, and it looks like curly was enabled in https://codereview.chromium.org/2778063003.

**Comment by primiano** [comment]
Ahh facepalm. I didn't think to that as I rebased just few days ago.
Your reply makes lot of sense. Sorry for the noise, wasn't used to such a live codebase :)
Thanks for keep improving eslint.
