### ISSUE TITLE
Limit what character Telemetry tags can have

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3480]
We should limit what character Telemetry tags can have for possible future improvement (maybe "a:b" map to a key value pair {'a': 'b'}).

Proposed current limitation: a tag is a string which can only contain alphanumeric characters, underscores, and dashes ('-'). The maximum length is 50.

@benshayden @eakuefner @perezju

**Comment by nedn** [comment]
Telemetry announcement: https://groups.google.com/a/chromium.org/forum/#!topic/telemetry-announce/wx4edwTv0sI

**Comment by perezju** [comment]
To keep a consistent style among tag names, I think we should allow either underscores or dashes, but not both.

/bikeshedding

**Comment by nedn** [comment]
Allowing only alphanumeric & underscores sgtm.
