### ISSUE TITLE
Histogram_set_view fails in trace-viewer

### ISSUE THREAD

**Issue by maxlgu** [catapult-project/catapult#3490]
Steps to reproduce the bug:
 1. Run Catapult
 2. Click Metrics on the right menu bar
 3. Select any metric that includes histograms
 4. The metric results don't show up. Console shows error message. 
![image](https://cloud.githubusercontent.com/assets/26091905/24964907/870dd6a8-1f70-11e7-946f-9ceadd79faa3.png)

Other info:
1. The issue happens after the CL "Refactor histogram-set-view to an MVC pattern."

**Comment by eakuefner** [comment]
Max, can you upload the trace and ping me the link? Also, if this is based on modifications to the loading metric, can you link a CL with your modifications? I can't repro this with ToT, sfgate, and the current loadingMetric.

@benshayden

**Comment by eakuefner** [comment]
Handing to @simonhatch since I think he might take a look at it.

**Comment by maxlgu** [comment]
I can reproduce the bug with ToT, using the trace 'Repaint On Scroll
Region', and testing on 'cpuTimeMetric'. I was not on my own CL when
producing the bug.

**Comment by simonhatch** [comment]
So this is working now, but with a big TODO in there to possibly fold the settings into the ViewState. For now at least, you'll get metric results.

**Comment by maxlgu** [comment]
Great thanks!

**Comment by benshayden** [comment]
Apologies for the breakage and thanks, Simon, for the fix.
I think the correct solution would be to make the groupby-picker allow its settingsKey to be optional, and [Synchronize HistogramSetViewState with location.search using HTML5 history API.](https://codereview.chromium.org/2802933002) I still need to do a bit more work on that CL as described in the Messages.

**Comment by maxlgu** [comment]
Thanks Simon and Ben!
