### ISSUE TITLE
Dashboard should support story tags

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3494]
Telemetry team is working on [better story organization through tagging](https://docs.google.com/document/d/1t8JG5988sB8ncznEjjQNfurRl6V8B2xML-kX07cQXaM/edit#heading=h.ktk80n4s9l13). On the dashboard side, we will need to:

1. Add tags to data model (probably as an indexed repeated `StringProperty` on `TestMetadata`)
2. Support setting tags through /add_histogram
3. Support filtering by tag on the `/report` page.

@simonhatch @eakuefner

**Comment by benshayden** [comment]
#3554 is tracking the frontend changes. Hannah will update that bug shortly.

Copying from the [design doc](https://docs.google.com/document/d/1lgVsfHCGueXDX4F660U5ynIbRTujzP7t847hXLdPIoo/edit#) (google-only), the next step is to implement GetDiagnosticsHandler to allow the test-picker to query the latest TagMap diagnostic for the selected test suite.

**Comment by hannahtwiggsmith** [comment]
Instead of StringProperty on TestMetadata we made a SparseDiagnostic entity that is plumbed through AddHistogram, and the story tag filter supports filtering stories by tag on the report page.

I think that everything is in place for this feature.
