### ISSUE TITLE
TraceViewer: memory-infra UI should hide PSS column if all zero

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3501]
Today on OSX we don't have PSS for technical reasons.
However, when grabbing a trace it shows negative numbers like the following:

![image](https://cloud.githubusercontent.com/assets/7137473/25172583/c9a5d0de-24f1-11e7-9914-6e36de0e9486.png)

This is because the dump provider emits all zeros, but then the tracing overhead gets discounted from native heap. We should not do that, or simply hide the PSS column if <= 0.

@chromy 
@pavolas FYI
(am I the only boring person with a consistent username here? :P)

**Comment by chromy** [comment]
So I have written both patches to do it both ways I'm just trying to decide which is cleaner.

**Comment by primiano** [comment]
> So I have written both patches to do it both ways
You rock!

>  I'm just trying to decide which is cleaner.
The one that has less diff lines and touches less files :)

**Comment by chromy** [comment]
Sgtm :)

Mac:
![image](https://cloud.githubusercontent.com/assets/351085/25177813/2420ee46-24fb-11e7-961b-bcf17d7c1e8d.png)

Linux:
![image](https://cloud.githubusercontent.com/assets/351085/25177797/100af8e8-24fb-11e7-9a26-d96496474aa1.png)

CL: https://codereview.chromium.org/2821313003/

**Comment by chromy** [comment]
Done.
