### ISSUE TITLE
Kill is_multi_tab_test flag in legacy_page_test .LegacyPageTest

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3514]
Enabling "is_multi_tab_test = True" breaks the abstraction of a story run | story set run is the atomic unit of benchmark run. This is because the state of subsequent runs is now vastly different from the previous run, not just in term of OS/browser machinery state but also at the abstraction level since the number of tabs on the browser aren't the same.

We should just kill this flag & the conditional statement in https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/page/shared_page_state.py#L222

**Comment by nedn** [comment]
@perezju

**Comment by perezju** [comment]
Seems like this is [currently only used in tests](https://cs.chromium.org/search/?q=def%5C+TabForPage&type=cs)? Agree we should kill and not let it be used in new benchmarks.

**Comment by ashley3** [comment]
Tentative change out for review here: https://codereview.chromium.org/2841663002/
Announcement made here: https://groups.google.com/a/chromium.org/forum/#!topic/telemetry-announce/1IX-tEKE7es

**Comment by ashley3** [comment]
Haven't seen any complaints on the announcement email so I'm gonna go ahead and submit the change now

**Comment by ashley3** [comment]
Code removed; gonna go ahead and close this issue
