### ISSUE TITLE
Results2 from the perf trybot is missing the groupby picker

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3515]
Somebody ran some perf trybot jobs on https://codereview.chromium.org/2835933002/ .
The results HTML (https://console.developers.google.com/m/cloudstorage/b/chromium-telemetry/o/html-results/results-2017-04-24_03-57-12) seem to miss the column picker.

Essentially I can see that a histogram for a metric has 100 samples, but I cannot split by individual page anymore.

![image](https://cloud.githubusercontent.com/assets/7137473/25336486/a1eade84-28ef-11e7-91f2-13f7e78cf189.png)

@benshayden  Ideas?

**Comment by anniesullie** [comment]
@simonhatch @eakuefner

**Comment by perezju** [comment]
Not that also the "triangles" to fold/unfold merged metrics into their parts are missing. Maybe something broke on the merging UI?

**Comment by benshayden** [comment]
This issue will be fixed by [Fix a bug in how histogram-set-controls handles its groupby-picker.](https://codereview.chromium.org/2802333002)
