### ISSUE TITLE
Error message is too vague when filing bug with invalid owner email

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#3520]
I was attempting to file a bug for this alert:
https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgoueQmgoM

I put the owner as acondor [at] chromium [dot] org, an email address I think may not exist. Instead of letting me know that, I got this rather unhelpful error message:

![screenshot 2017-04-24 at 5 11 57 pm](https://cloud.githubusercontent.com/assets/3644011/25363734/b03d2a74-2911-11e7-8a8c-c986ba96a1bc.png)

If an invalid Chromium account was actually what was wrong, it would be nice to tell the user that.

**Comment by anniesullie** [comment]
@simonhatch
