### ISSUE TITLE
All Telemetry based tests on my Linux workstation core dump

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#3525]
All Telemetry-based tests on my Linux workstation are core dumping somewhere inside Telemetry's Python code.

Attached is the output of:

strace -f -e trace=process ./content/test/gpu/run_unittests.py > output.txt 2>&1

with the following patch applied to rule out vtune as the cause of the core dumps:

--- a/telemetry/telemetry/internal/platform/profiler/vtune_profiler.py
+++ b/telemetry/telemetry/internal/platform/profiler/vtune_profiler.py
@@ -124,6 +124,8 @@ class VTuneProfiler(profiler.Profiler):
       return False
     if browser_type.startswith('cros'):
       return False
+    if True:
+      return False
     try:
       proc = subprocess.Popen(['amplxe-cl', '-version'],
                               stderr=subprocess.STDOUT,

I can't figure out what operation is causing the core dump.

Can you help? Thanks.
[output.txt](https://github.com/catapult-project/catapult/files/960215/output.txt)

**Comment by kenrussell** [comment]
Figured out how to get pdb attached to run_tests.py. So far it's crashing inside this operation:

> /Work/kbr/src/chrome/src/third_party/catapult/third_party/typ/typ/runner.py(174)run()
-> ret, test_set = self.find_tests(self.args)

Still looking.

**Comment by kenrussell** [comment]
CC'ing @dpranke and @nedn .

**Comment by dpranke** [comment]
python itself is core dumping?

**Comment by kenrussell** [comment]
Yes. With this log added:

kbr@ftfy:/Work/kbr/src/chrome/src$ diff /usr/lib/python2.7/unittest/loader.py /usr/lib/python2.7/unittest/loader.py.BACKUP 
232d231
<         print 'importing ' + name

It's crashing attempting to load the lint unittest:

importing gpu_tests.gpu_integration_test_unittest
importing gpu_tests.test_expectations_unittest
importing gpu_tests.gpu_test_expectations_unittest
importing gpu_tests.lint_unittest

I also had to hack Telemetry's run_tests.py to stop matching "*test.py":

--- a/telemetry/telemetry/testing/run_tests.py
+++ b/telemetry/telemetry/testing/run_tests.py
@@ -186,6 +186,8 @@ class RunTestsCommand(command_line.OptparseCommand):
     runner.args.timing = True
     runner.args.verbose = 3
 
+    runner.args.suffixes=['*_unittest.py']
+

Giving up for tonight.

**Comment by kenrussell** [comment]
P.S. I remember trying to look into pylint errors ynovikov@ was running into, but don't see any changes under third_party/logilab or third_party/pylint.

**Comment by kenrussell** [comment]
I'm still stuck on this and can't run any Telemetry tests on my workstation. Can anyone help me? How can I more easily try importing this particular file without trampolining through all of the Telemetry and typ harnesses?

**Comment by kenrussell** [comment]
Stepping through: it's crashing upon

import astroid

inside src/third_party/pylint/pylint/lint.py .

**Comment by kenrussell** [comment]
The crash is happening while pyximport is attempting to import mx/DateTime/mxDateTime out of /usr/lib/python2.7/dist-packages . A "return None" statement inside pyximport is causing a SIGSEGV. Here is the tail end of the pdb session:
[python-crash-backtrace.txt](https://github.com/catapult-project/catapult/files/962979/python-crash-backtrace.txt)

> /usr/lib/python2.7/dist-packages/pyximport/pyximport.py(302)find_module()
-> for path in paths:
(Pdb) 
> /usr/lib/python2.7/dist-packages/pyximport/pyximport.py(314)find_module()
-> _debug("%s not found" % fullname)
(Pdb) 
> /usr/lib/python2.7/dist-packages/pyximport/pyximport.py(315)find_module()
-> return None
(Pdb) s
--Return--
> /usr/lib/python2.7/dist-packages/pyximport/pyximport.py(315)find_module()->None
-> return None
(Pdb) s

I'm at a loss -- the files in that package haven't been touched in years.

**Comment by kenrussell** [comment]
This:

sudo apt remove python-egenix-mxdatetime

Fixed the seg fault.

**Comment by kenrussell** [comment]
Thanks @kainino0x for suggesting this as a viable solution!!!

**Comment by kenrussell** [comment]
Also for the record: how to find which package contained the file:

dpkg-query --search /usr/lib/python2.7/dist-packages/mx/...

**Comment by kenrussell** [comment]
Note: ynovikov@ is running into this same problem. I have a feeling a lot of Telemetry users inside Google may run into the same thing. It's worth a PSA.

**Comment by nedn** [comment]
I think the best thing here is improve the error message. Maybe add a try catch somewhere that would allow: "You maybe encounter the problem with python-egenix-mxdatetime module. You can try the workaround by ..."
