### ISSUE TITLE
Add CPU time EQT metric

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3529]
Some EQT variability is due to task descheduling.

We should add a CPU time EQT metric, similar to the way that we added a CPU time FMP metric.

We'd expect this metric to be less representative of user experience, but more stable.

**Comment by tdresser** [comment]
Ulan, do you want to take this on, or should we find someone else?

**Comment by ulan** [comment]
I will look into it.

**Comment by tdresser** [comment]
Any thoughts on when you'll have time for this?

**Comment by ulan** [comment]
Sorry for the delayed reply. This github account is connected to my private email that I don't check often. In future please feel free to ping me on the corp account if I don't reply within two days.

I started working on this issue. Before I implement it, let me confirm with you that I get the high level idea right. The algorithm would be to find the time window that maximizes the EQT using wall times and then re-compute the EQT in that window using the CPU times?

**Comment by tdresser** [comment]
Ideally, we'd consistently use CPU time for this metric, so we'd find the cpu time window which maximized the CPU time EQT.

**Comment by ulan** [comment]
This means for each task we modify its end time to be (task.start + task.cpuDuration) and then compute max EQT for the modified tasks? The start times of the tasks remain unchanged.

**Comment by tdresser** [comment]
Shouldn't we use the cpu start and cpu end times?
I was thinking we could do something similar to what @maxlgu did with the CPU time breakdowns here: https://cs.chromium.org/chromium/src/third_party/catapult/tracing/tracing/metrics/system_health/breakdown_tree_helpers.html?rcl=deb2d7670a64dd33163f3c6e7c95b7066188e2f5&l=34, where we pass in a method to get the start time and duration of tasks.

**Comment by ulan** [comment]
Oh, I didn't know we have cpu start time. In that case, we should use cpu start and end time.

Thank you for the link. I'll implement similar thing for EQT.
