### ISSUE TITLE
Dashboard - Reduce bisect retries?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3530]
Now that these are working again, we might be spamming some bugs with way too many retries:

https://bugs.chromium.org/p/chromium/issues/detail?id=703743 has reached 107 comments, a large portion of which are bisect attempts.

**Comment by anniesullie** [comment]
@dave-2 has expressed opinions against retries in the past, IIRC

**Comment by dave-2** [comment]
Yes, I never really liked automated retries. It's unintuitive that the system would be doing all this stuff when nobody asked it to. Reducing the number of retries or eliminating them sgtm

**Comment by simonhatch** [comment]
@picksi 

Was trying to get some basic numbers on how often these retries succeed or not. Scraped bugs from the last month and tried bucketing them into whether they were probably relaunches from the dashboard (I can share script if anybody interested):

https://docs.google.com/spreadsheets/d/1B9LuivttyKVJANLjxaobqgcxrILW6Ck3Zcq_3pJML9g

It's a little hand-wavy since I don't know if there's explicitly a way to tell whether a bisect is a relaunch of an existing one, so I mostly try to match up suite/bot/metric/revisions with the first one in the bug.

Relaunch success rate isn't spectacular, being somewhere in the 10-15% range.

**Comment by simonhatch** [comment]
So just re-ran that script this today and got similar results:

Bisects	1160
Bugs w/ Relaunch	303
Relaunch Bisects	369 (100.0%) 
Relaunch Successes	33 (8.9%) 
Relaunch No-Repro	278 (75.3%) 
Relaunch Failures	58 (15.7%) 

Doesn't seem worth it to me, if there are no objections I can post a cl to remove the retry logic tomorrow.
