### ISSUE TITLE
Perf Dashboard: problems with multiple login

### ISSUE THREAD

**Issue by mustaqahmed** [catapult-project/catapult#3536]
The [dashboard](https://chromeperf.appspot.com/) used to allow switching between multiple logins, but it no longer does. With multiple logins (in my case, google.com & chromium.org), the dashboard jumps to the "default" account. Clicking on the login id doesn't give us an option anymore, simply redirects to the same page.

**Comment by eakuefner** [comment]
@simonhatch

**Comment by CalebRouleau** [comment]
This is really broken right now. I can't seem to view results. I get this:
"No data available for crouleau@google.com. Note that some data is only visible when signed in with a chromium.org account, which is linked to a google user."

Then when I try to switch users it doesn't work.

**Comment by simonhatch** [comment]
What url are you trying to visit?

**Comment by CalebRouleau** [comment]
https://chromeperf.appspot.com/group_report?bug_id=718221

**Comment by simonhatch** [comment]
Doesn't seem to be any alerts on that report, so maybe the UI is misleading and shouldn't have that message.

The original link from the bug for all alerts was https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgsrSMtQoM, which shows the alert has since been marked ignore.

**Comment by CalebRouleau** [comment]
Thank you!

**Comment by simonhatch** [comment]
Just linking people from https://bugs.chromium.org/p/chromium/issues/detail?id=719375

@perezju

**Comment by simonhatch** [comment]
@gkraynov

**Comment by simonhatch** [comment]
I can repro this in incognito, will try to debug today.

**Comment by simonhatch** [comment]
So found someone who seems to have investigated this, https://p.ota.to/blog/multiple-google-account-sign-in-on-app-engine/

**Comment by eakuefner** [comment]
Here's a recent thread on chromium-dev about similar problems with other Chromium tools: https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/DQ8qMIEMv9Y/nMz9IWIrAwAJ -- seems like this might be what's happening here.

**Comment by simonhatch** [comment]
Quick followup, you can use the following URL (adapted from the thread @eakuefner linked):

https://www.google.com/accounts/ServiceLogin?service=ah&passive=false&continue=https://appengine.google.com/_ah/conflogin%3Fcontinue%3Dhttps://chromeperf.appspot.com/

Which (at least for now) will force the account selector to appear and you can login with a different account.

**Comment by schuay** [comment]
I'm also running into this. I'm signed in with both @google.com and @chromium.org accounts, with @google.com seen as the active account by chromeperf/. There's no way to switch the active account.

**Comment by simonhatch** [comment]
We should think about using https://www.webcomponents.org/element/GoogleWebComponents/google-signin, we tried that on Pinpoint and it's really simple to use and I think it handles signout/multiple login issues.

**Comment by benshayden** [comment]
Archiving. V2SPA uses google-signin. Changing V1 to use it would require changing all the endpoints to accept Authorization headers.
