### ISSUE TITLE
Dashboard - Test-Picker takes up a lot of space

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3537]
After selecting anything, often doubles in size. This was brought up by Ben from Dashboard story tagging support doc.

@eakuefner @benshayden

**Comment by benshayden** [comment]
Like this?

![](http://i.imgur.com/oc33GPq.png)

[Demo](https://dev-benjhayden-7787540c-dot-chromeperf.appspot.com/report?sid=ca6c52111f8337a0f6478573cd639ed39dbd8eb82d903d8c3932651f452b9fb9)

Currently, autocomplete-box adds some light-dom containing the selectedItem.name in a blue rounded span inside the paper-input. When there is a selectedItem, the input query is empty so it displays the placeholder, and takes up a lot of space. I removed that light-dom so that the paper-input can keep displaying the selectedItem.name, and move the placeholder above it, which is how paper-input was designed to be used.

**Comment by simonhatch** [comment]
Definitely takes up less space, although now the longer metric names get cut off. Maybe it should expand to the size of the name at least? What does everyone else think?

**Comment by benshayden** [comment]
![](http://i.imgur.com/ZLtHQBZh.png)

Yeah, it does look a little bad, but the full names are displayed in the chart-title after the user clicks Add. If users forget what they selected in a previous box while composing a test path, they can click that box to see the full value in the dropdown menu.

Also, it would not be trivial to allow the input element to expand to exactly the right size. IIUC, I'd need to measure the text (which forces layout) and set style.width on the paper-input, which can be a bit error prone. LMK if there's an easier way.

**Comment by eakuefner** [comment]
What if we just ellipsized the abbreviated name? That avoids the confusion that might be introduced by cutting off, and also obviates a need for forced layouts.

**Comment by anniesullie** [comment]
I like the ellipsis idea, especially since there's a text-overflow property for that. I think we'd also want to show the full name on hover (in a tooltip or similar).

**Comment by anniesullie** [comment]
Also we may need to increase the padding between the menus a tiny bit.

**Comment by benshayden** [comment]
Thanks!

![](http://i.imgur.com/CudibR9h.png)

[Demo](https://dev-benjhayden-7ef5172e-dot-chromeperf.appspot.com/report?sid=ca6c52111f8337a0f6478573cd639ed39dbd8eb82d903d8c3932651f452b9fb9)

I also thought that it would be easier to compose test paths if, once you select a test path component from a menu and the next menu loaded, it automatically focused the next menu, but I can remove that if it isn't right for some reason. Or I can make it stop doing that when the Add button is enabled?

**Comment by anniesullie** [comment]
One weird thing I noticed about the demo: if you click on the Test suite, you get a nice menu with "power.gpu_rasterization.whatever" showing in bold, so you know what the text is. Same with Bot, and all the subtests up to the last one. For the last one, after you select a page, clicking on it doesn't give you that little menu that shows what you selected. Any idea why?

**Comment by benshayden** [comment]
I'm not seeing that. Are you sure it wasn't just slow?

It's possible that onDropdownSelect hangs awaiting `this.updateSubtestMenus(boxIndex + 1)` when there is no such menu, but I can't debug that if I can't repro.

**Comment by anniesullie** [comment]
Weird, I see it on the data I entered, but not my best guess of the data you entered in your screenshot. What I put in the menus:

image_decoding.image_decoding_measurement
android-nexus5X
cpu_cstate_C0_residency_percent
image_decoding.html?gif

I'm only seeing this with image_decoding.html?gif. Perhaps it has something to do with the question mark in the name? I don't see it with ref in that same menu.

**Comment by benshayden** [comment]
Yes, it's interpreting the query as a regex, so `html?gif` matches `htmgif` and `htmlgif`, which aren't in the items, so the autocomplete-box goes to build a menu containing zero menu items, and correctly decides not to do that.

Can I remove regex support and interpret the query as a substring?
Alternatively, I could regex-escape item names when items are selected, so the input box would display `image_decoding\.html\?gif`, but I would be afraid that people would copy-paste those strings into places that don't interpret it as a regex, like run_benchmark.

**Comment by anniesullie** [comment]
@chromy I think you added the regex support, but not sure. Do you have any thoughts on the best thing to do here?

**Comment by chromy** [comment]
Yep it was me. So long as we keep the fuzzy matching support I'm happy as it is super useful for accessing the very long memory metrics. As far as I know people do not rely on the fact each subpart of the query acts as a regex.

I think the regex-escape the item names is not ideal for the reasons you mentioned Ben. Perhaps the best solution is something like replacing:
```javascript
    this.rs = query.split(' ').map(part => new RegExp(part, flags));
```

```javascript
    this.rs = query.split(' ').map(part => new RegExp(escapeRegex(part), flags));
```

in [autocomplete.html](https://cs.corp.google.com/github/catapult-project/catapult/dashboard/dashboard/static/autocomplete.html?q=this.rs+%3D+query.split+p:github+f:%5Ecatapult-project&dr=C&l=53). This allows us to support both easily support case insensitive matching and avoids the problems with regex chars in the query

**Comment by benshayden** [comment]
Keeping fuzzy matching sgtm.

It seems like it would be simpler to implement case-insensitivity by lowercasing everything and calling String.includes() rather than using an escaped regex, no?

**Comment by chromy** [comment]
I marginal prefer not modifying the list, feels like it would mean fewer
things to think about when reading the code. However it's your CL not mine,
so do what you think is best :), I would happily lgtm either.

**Comment by benshayden** [comment]
@chromy Sorry, by "lowercasing everything", I meant in FuzzySelect just before comparison, not the entries in the menu.
