### ISSUE TITLE
groupby picker only shows up after refreshing the page

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3541]
When I open https://console.developers.google.com/m/cloudstorage/b/chromium-telemetry/o/html-results/results-2017-04-07_17-42-56, I don't see the groupby picker. I can only see it after refreshing the page.

Chrome version: 
Mac Version 58.0.3029.96 (64-bit)

**Found:**
<img width="720" alt="screen shot 2017-05-05 at 3 47 37 pm" src="https://cloud.githubusercontent.com/assets/911877/25761889/6efc7b0e-31aa-11e7-990b-c6c37ed949a0.png">

**Expected:**
<img width="731" alt="screen shot 2017-05-05 at 3 48 27 pm" src="https://cloud.githubusercontent.com/assets/911877/25761865/52334d04-31aa-11e7-91be-8407d3cf7855.png">

**Comment by nedn** [comment]
@eakuefner @benshayden

**Comment by benshayden** [comment]
Fixed https://codereview.chromium.org/2802933002
