### ISSUE TITLE
Perf Dashboard: 500 Internal Server Error

### ISSUE THREAD

**Issue by ulan** [catapult-project/catapult#3542]
Creating a bug for an alert fails with:
"500 Internal Server Error
The server has either erred or is incapable of performing the requested operation."

I noticed the problem last week, when some request would fail with 500. Now it seems all requests are failing.

**Comment by simonhatch** [comment]
From the logs it looks like there were some problems communicating with monorail:

HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues?alt=json&sendEmail=true

I'll see if I can surface that better.

**Comment by simonhatch** [comment]
Gonna close this out as we've surfaced the error to make it clearer.
