### ISSUE TITLE
Dragging multiple series with different units onto a chart should lead to sensible results

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3543]
On the perf dashboard, when you drag multiple series onto a chart that each have the same unit, the Y axis automatically scales to accommodate all of the series. 

For example, this graph answers the question "what's the average power during video playback during the story video.html?src=tulip2.mp4?".

![power](https://cloud.githubusercontent.com/assets/1407397/25806884/d88b0246-33d2-11e7-843c-d8495f11bac9.png)

[A commenter on this bug thread](https://bugs.chromium.org/p/chromium/issues/detail?id=703098#c25) asked a very reasonable question that might be answered with the help of this data: how does this power use relate to Chrome's CPU use?

Thankfully, we also have a metric for CPU use during the story (cpu_time_percentage_avg). Unfortunately, even though we have a metric for CPU use and a metric for power, it's really hard to plot the two together to see how they correlate.

It'd be _awesome_ to be able to answer this question by dragging both time series to the same graph, having the right Y axis automatically show the cpu_time_percentage_avg unit (n% (lower is better)), and have it automatically scale just like the left Y axis does. In reality, what happens is this:

![power_and_cpu](https://cloud.githubusercontent.com/assets/1407397/25807173/e4acb384-33d3-11e7-9850-d0a28994fc69.png)

There are a couple of funny things about this:

- The graph looks like it's saying that the unit of cpu_time_percentage_avg is also Watts (lower is better), even though it's not.
- Surprisingly, even if you uncheck all of the power data series so that only the CPU consumption data is showing, the Y axis still reads Watts (lower is better).

@simonhatch @eakuefner do you have any idea how hard this would be?

This definitely isn't something that's sapping my productivity every day, but it does seem like an instance where the dashboard behaves unexpectedly.

**Comment by anniesullie** [comment]
@benshayden here's another UI bug to think about.

**Comment by benshayden** [comment]
V2SPA handles this.
