### ISSUE TITLE
Decouple HistogramSet creation from output

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3551]
After #3550 is done, we need to make it possible to create the corresponding HistogramSet for a legacy benchmark earlier than output time so that we can call AddSharedDiagnostic. The logic from here https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/results/page_test_results.py#L165 should be factored into a method called something like PopulateHistogramSet that does that logic if self._histograms is not already populated.

**Comment by simonhatch** [comment]
Done in: https://codereview.chromium.org/2928533002/
