### ISSUE TITLE
Dashboard - Test-Picker tags support

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3554]
As described in https://docs.google.com/document/d/1W3-aeJABBS_WkzetVsXdBM9caAggr1wiRr1GJapotrY/edit#

Following mock, will need some UI elements for tags box + any tags already selected. Some backend support to surface the tags data from the diagnostic as well.

**Comment by hannahtwiggsmith** [comment]
The tag-filter dom-module can land this week if there are no further comments. Integration with the test-picker will come later.

[Design Doc (google only)](https://docs.google.com/a/google.com/document/d/1lgVsfHCGueXDX4F660U5ynIbRTujzP7t847hXLdPIoo/edit?usp=sharing)

## Story Tag Filter:

![download](https://user-images.githubusercontent.com/10691724/27562905-9db12eca-5a83-11e7-8aa4-cad044c35bee.png)

When the user clicks on the filter button, the story tag dropdown appears. The user can select story tags in the tag dropdown. When a tag is selected, it will appear to the right of the filter button as a removable chip. The user can remove a tag by either unchecking the box in the dropdown or clicking the x in its chip. The dropdown closes when the user clicks outside of it.
