### ISSUE TITLE
importing telemetry.core.platform_module fails on Cygwin

### ISSUE THREAD

**Issue by kainino0x** [catapult-project/catapult#3558]
See https://bugs.chromium.org/p/chromium/issues/detail?id=711307#c23

The core issue seems to be that ctypes.windll probably doesn't exist under Python on Cygwin (which sort of makes sense since windll is a Windows-only module). Perhaps the platform detection is a little wrong under cygwin, and a different path needs to be taken here.

```
________ running '/usr/bin/python src/third_party/catapult/telemetry/bin/fetch_telemetry_binary_dependencies' in '/cygdrive/c/src/chrome'
ERROR:root:Error when determining if QPC is usable.
Traceback (most recent call last):
  File "/cygdrive/c/src/chrome/src/third_party/catapult/common/py_trace_event/py_trace_event/trace_time.py", line 130, in IsQPCUsable
    ctypes.windll.Kernel32.QueryPerformanceFrequency(
AttributeError: 'module' object has no attribute 'windll'
```

**Comment by nedn** [comment]
There is also:
Traceback (most recent call last):
  <module> at /cygdrive/c/src/chrome/src/third_party/catapult/telemetry/bin/fetch_telemetry_binary_dependencies:10
    from telemetry.core import platform as platform_module
  <module> at /cygdrive/c/src/chrome/src/third_party/catapult/telemetry/telemetry/core/platform.py:14
    from telemetry.internal.platform import (platform_backend as
  <module> at /cygdrive/c/src/chrome/src/third_party/catapult/telemetry/telemetry/internal/platform/platform_backend.py:10
    from telemetry.internal.platform import network_controller_backend
  <module> at /cygdrive/c/src/chrome/src/third_party/catapult/telemetry/telemetry/internal/platform/network_controller_backend.py:15
    import platformsettings
  <module> at /cygdrive/c/src/chrome/src/third_party/catapult/telemetry/third_party/web-page-replay/platformsettings.py:779
    _inst = _new_platform_settings(platform.system(), platform.release())
  _new_platform_settings at /cygdrive/c/src/chrome/src/third_party/catapult/telemetry/third_party/web-page-replay/platformsettings.py:774
    raise NotImplementedError('Sorry %s %s is not supported.' % (system, release))
NotImplementedError: Sorry CYGWIN_NT-10.0 2.7.0(0.306/5/3) is not supported.

**Comment by noell** [comment]
For the "NotImplementedError: Sorry CYGWIN_NT-10.0 2.7.0(0.306/5/3) is not supported" case nedn@ mentioned above, a simple fix for fetch_telemetry_binary_dependencies script is:

```
   import os
   import sys
+if sys.platform in ('cygwin'):
+  print '%s for platform [%s]: skipped' % (os.path.basename(__file__), sys.platform)
+  exit(0)
```

**Comment by noell** [comment]
For the "NotImplementedError: Sorry CYGWIN_NT-10.0 2.7.0(0.306/5/3) is not supported" case nedn@ mentioned above, a simple fix for fetch_telemetry_binary_dependencies script is:

```
 import os
 import sys
+if sys.platform in ('cygwin'):
+  print '%s for platform [%s]: skipped' % (os.path.basename(__file__), sys.platform)
+  exit(0)
```

**Comment by nedn** [comment]
I sent out a bunch of patch fix, can you execute "gclient run_hook" again?

**Comment by nedn** [comment]
Np, sorry for the hassles!
