### ISSUE TITLE
Got "No alerts specified to add bugs to." on first time create new bug for the regression.

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3561]
Everytime I see a regression that I want to create a bug for in https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgqs3CkwkM, I always get the "No alerts specified to add bugs to." notification on the first try.

Trying the same action again always succeed.

**Comment by simonhatch** [comment]
This happens when you actually try to file the bug? ie. on submit on the new bug window?

**Comment by nedn** [comment]
Correct. 
![rzetet5hahe](https://cloud.githubusercontent.com/assets/911877/26064355/b01becb2-395e-11e7-9725-8bd9e9155557.png)

**Comment by anniesullie** [comment]
I'm pretty sure this is a longstanding issue with the oauth login clearing out the postdata.

**Comment by benshayden** [comment]
V2SPA proactively refreshes the oauth token before posting requests.
