### ISSUE TITLE
Perf Dashboard: 

### ISSUE THREAD

**Issue by SummerLW** [catapult-project/catapult#3562]
Chrome version: 57.0.2987.133 (Mac)
URL: https://chromeperf.appspot.com/group_report?sid=3258abe45ad15b71bde2213b2fd29b0439e744ac861284deadaac7f2a078ede9

Please copy and paste any errors from JavaScript console (Command+Option+J to open):
The user does not exist: ['weilanweilan2008@gmail.com']

Please describe the problem:
I already logged in as lanwei@chromium.org, but it still gives me this error, saying that I am using another account. I cleared all the  cookies, but still does not work. Could you please tell me how to reset the account? Thank you.

**Comment by anniesullie** [comment]
@simonhatch

**Comment by simonhatch** [comment]
Wonder if this is related to #3536

**Comment by benshayden** [comment]
Archiving.
