### ISSUE TITLE
Make row pipeline not depend on rows having values.

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3564]
Historically, we've simply avoided adding rows with empty values (due to failures of benchmarks, etc.) because the alerting pipeline among other things cannot handle them.

However, with histograms, it will be legitimate for rows not to have associated values, since empty histograms may have attached diagnostics that will nonetheless need to be stored and surfaced. We should make sure that pieces that process rows can handle them being empty.

@simonhatch

**Comment by benshayden** [comment]
Archiving due to #4328
