### ISSUE TITLE
autocomplete-box should be case insensitive

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#3566]
All the autocomplete-boxes for selecting benchmarks and bots are case sensitive.
This is rather inconvenient as we sometimes have some names in camelcase and sometimes not.
I think the old implementation of the search box was case insensitive, if it's not too much work, I'd like to see the same behavior again.

**Comment by simonhatch** [comment]
@benshayden

**Comment by benshayden** [comment]
![](http://i.imgur.com/63ilT8sh.png)

[Demo](https://dev-benjhayden-2297ebad-dot-chromeperf.appspot.com/report)

[CL](https://codereview.chromium.org/2889243002)

**Comment by anniesullie** [comment]
Looks great! Thanks for the demo and quick fix!

**Comment by camillobruni** [comment]
thanks for the fix!
