### ISSUE TITLE
Perf Dashboard: Sorting by Track

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3568]
Right now, when looking for alerts to group together, I need to skim much of the list. For example, a regression in memory.top_10_mobile should probably be grouped with a regression in system_health.memory_mobile, but they don't sort adjacent to each other.

Could these have some sort of category (maybe by track?), so that we could easily group all the page all the memory regressions together, and all the page load regressions together, etc?

Alternatively, maybe this will happen naturally as we rename things.

**Comment by simonhatch** [comment]
@nedn 

I think this will be possible when we introduce story tags?

**Comment by nedn** [comment]
On the benchmarking side, I think this is not related to story tags (characteristic of test), but about grouping regressions based on the characteristics of the metrics.

On the dashboard side, I am not sure these two can have a same abstraction though. Maybe something like test path's tag?

**Comment by anniesullie** [comment]
Note that often we don't want to group all the memory regressions together--they're broken down into components and likely a skia regression is totally unrelated to a v8 one. But you would still want to be able to look at them all together as a sheriff to make that decision.

I do think renaming things down into a minimal set will help a lot, but you'll still have issues where both loading.desktop and system_health.common_desktop regressed loading metrics, but system_health.common desktop also has unrelated power regressions.

@benshayden is working on a doc about how we might be able to use [RelatedHistogramBreakdown](https://github.com/catapult-project/catapult/blob/master/docs/histogram-set-json-format.md#relatedhistogrambreakdown) for both problems--identify metrics that are likely related across benchmarks, and also identify things that look related but probably aren't (a v8 and skia memory regression in the same range).

**Comment by benshayden** [comment]
V2SPA allows sorting by measurement so you can see all memory regressions together. It will also use RelatedNameMap diagnostics to improve the grouping.
