### ISSUE TITLE
Dashboard - GuessBrowserName gives incorrect browser for webview metrics.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3571]
From crbug.com/724032

The logic in https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/start_try_job.py#L511 that guesses the browser based on the bot name.

@perezju @tdresser

**Comment by perezju** [comment]
How can I view the `_BOT_BROWSER_MAP_KEY`?

Also the monochrome bot is a bit special, because it runs on a target browser not known by Telemetry (with `--browser=exact --browser-executable [...]`), but I guess now there should be no problem on adding it to the list of known browsers.

**Comment by simonhatch** [comment]
You can go to chromeperf -> admin -> edit_site_config and you'll see bot_browser_map

**Comment by simonhatch** [comment]
So there's some discussion in crbug.com/724519 "Tidying up monochrome bots". For specifying --browser more specifically for certain tests/bot combos seems like the correct way to do this would be to pass it up through diagnostics? @eakuefner 

As Juan mentioned, this has probably never worked properly. We could either wait on the Histogram Pipeline, or do something shorter term like supplementing the _BOT_BROWSER_MAP with test patterns and apk paths?

**Comment by eakuefner** [comment]
Yes, I think this, together with the botmap itself, should definitely eventually be surfaced through diagnostics.

**Comment by simonhatch** [comment]
I'm going to close this out as we have no plans of fixing it, and Pinpoint will take over doing clank soon enough.
