### ISSUE TITLE
Make it possible for multiple sheriff rotations to receive alerts for a single test path

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3576]
Steps to reproduce: 

1. Go to the "Edit sheriffs" page for "Power perf sheriff"
2. Observe that there are no monitored patterns
3. Click "List monitored tests"
4. Observe that there are tons of monitored tests

It seems like when changing monitored patterns, tests are only ever *added* to the list, never removed.

/cc @simonhatch @eakuefner

**Comment by zeptonaut** [comment]
I'm going to broaden this bug because it's worse than I originally thought. I have a set of test paths that are monitored by the Chromium Perf Sheriff rotation, but I want to make sure that those test paths aren't generating too many spurious alerts, so I also have those test paths monitored by the Power Perf Sheriff rotation (basically just sending emails to the group chromium-power-perf-alerts@) to see what the noise on them looks like.

Right now, I have the following test paths monitored:

![ndm3zdjqthd](https://user-images.githubusercontent.com/1407397/27640710-023f02f8-5be8-11e7-896a-eea94e8b6ab1.png)

However, when I submit those and click "List monitored tests", the list comes back empty, even though these are the same paths that are being successfully monitored by the Chromium Perf Sheriff rotation. Any idea what the deal is? Is there some logic that prevents a test path from being monitored by multiple sheriff rotations?

**Comment by anniesullie** [comment]
Yes, a test can only have one sheriff associated with it.

**Comment by zeptonaut** [comment]
Booo. How hard would it be to change this? Otherwise, it seems pretty hard to understand what sort of power alerts the perf sheriffs are seeing, because they might have triaged the alert before I even see it.

**Comment by anniesullie** [comment]
@simonhatch I think it would be a lot of work. Maybe something like the benchmark health report could provide a better view into the quality of the alerts?

**Comment by simonhatch** [comment]
Agreed, my feeling would it'd be a lot of work, but that's not based on a thorough check of the code. Pretty sure there's a bunch of things written with the assumption of 1 sheriff though.

**Comment by zeptonaut** [comment]
Hmmm, okay. Sounds like this one's doomed to be closed as WontFix then. I'll try using the benchmark health report for this instead.
