### ISSUE TITLE
Progressbar message has spaces stripped out

### ISSUE THREAD

**Issue by danelphick** [catapult-project/catapult#3577]
When importing a trace, the progress bar contains text like "Importing1of 2".

This is because the version of rjsmin is old and doesn't know about template literals (e.g. `strings`), which were added in ES6 I think. The template literal is here: https://github.com/catapult-project/catapult/blob/master/tracing/tracing/importer/import.html#L141 and it was introduced in https://github.com/catapult-project/catapult/commit/f3e59acf67b0c545d72b2cd70651806f8b6903ac 2 months ago.

**Comment by fmeawad** [comment]
@lpy Can you take a look?

**Comment by chromy** [comment]
I think Dan sent a CL to Ned: https://codereview.chromium.org/2898763002/

**Comment by danelphick** [comment]
This should now be fixed. (When building chromium, you have to delete out/gen/content/browser/tracing/about_tracing.js to force it to be rebuilt due to the simplicity of its build rules).
