### ISSUE TITLE
Add TimeToFirstPaint metric to loading_metrics.html

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3587]
This metrics is deemed to be important, so we should also enable it.

@tdresser @nyaxt  @irori

**Comment by lpy** [comment]
Is this duplicate to #3572?

**Comment by nedn** [comment]
right

**Comment by nedn** [comment]
Reopen since we closed the other bug.

**Comment by benshayden** [comment]
Looks like this is done: https://github.com/catapult-project/catapult/commit/b6cdfc5c8c4e60cedc450ba52d618b90996b9e54
