### ISSUE TITLE
Add HistogramSet.createHistogram() as syntactic sugar.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3591]
Several metrics define a helper function to create a histogram and add it to a HistogramSet. TBMv2 should support a single general helper method `HistogramSet.createHistogram()` so that metrics don't need to define boilerplate. @eakuefner @deepanjanroy @zeptonaut

**Comment by zeptonaut** [comment]
FWIW, the most common pattern I've seen is "create a histogram, add a single value to it, and add it to the histogram set", so it's probably worth making sure that we provide some nice syntax for that, too.

**Comment by benshayden** [comment]
[This CL](https://codereview.chromium.org/2907683003) provides `histograms.createHistogram(name, unit, sample[s], opt_options)` which creates the histogram, adds it to the set, and returns it. WDYT?

**Comment by zeptonaut** [comment]
Love it :-)
