### ISSUE TITLE
Dashboard - 500 errors on /start_try_job

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3593]
From @vinterstum 

Looks like it's timing out fetching from chrome-infra-auth, similar to the monorail timeouts that were happening a week or so ago.

**Comment by vinterstum** [comment]
Working again now, intermittent issue?

**Comment by simonhatch** [comment]
Yeah these kind of issues come and go. We could probably do better surfacing the error rather than a generic 500 error, and also up the timeout a bit.

**Comment by simonhatch** [comment]
Going to close this out since it's so old.
