### ISSUE TITLE
Perf Dashboard: feature request to select checkbox with keyboard cursor and space

### ISSUE THREAD

**Issue by toyoshim** [catapult-project/catapult#3600]
Today, when we want to select multiple alerts together to report single bug for them, we need to click all relevant check-boxes, or need to tap the 'Tab' key four times to move to the next alert.

This is very tough to select tens of items together.
If we can use cursor key, i.e., up and down to move between check-boxes, it will simplify the step to merge multiple alerts.

**Comment by simonhatch** [comment]
In #3569 there was a request to select a range of alerts (along with a working demo), would that suffice?
