### ISSUE TITLE
"Import Warning: UserModelBuilder: Please file a bug with this trace: double-handled event: MouseLeave"

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3622]
cc @benshayden 

https://console.developers.google.com/m/cloudstorage/b/chrome-telemetry-output/o/trace-file-id_1-2017-06-01_17-58-38-83818.html

**Comment by benshayden** [comment]
Thanks!

Is this breaking or blocking anything?
If not, then I'll keep it on my backlog.

**Comment by zeptonaut** [comment]
Nope :-) Just saw it and figured you'd want to know.

**Comment by tdresser** [comment]
This is probably an issue with the mouse input latency logic in Chrome, as opposed to a problem in tracing.
It's similar to the errors we were seeing when mouse up and down were totally broken.

Feel free to file a Chrome bug, and cc me.
