### ISSUE TITLE
Display Histograms and Diagnostics on the dashboard

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3628]
As Histograms and Diagnostics become available in the dashboard backend #3328 , many opportunities arise to satisfy more use cases and improve existing features in the frontend.
At a basic level, when users select a point on a chart, the Histogram for that point can be displayed using the existing [tr-v-ui-histogram-span](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/value/ui/histogram_span.html) module that is currently used in results.html and the trace viewer's Metrics side panel:

![histogram-span](https://raw.githubusercontent.com/catapult-project/catapult/master/docs/images/metrics-results-ui-show-histogram.png)

This would provide more numeric information such as statistics and distribution, basic diagnostic information such as DeviceInfo, and facilitate drill-down exploration via Breakdowns and relationship diagnostics.
There are many possible places for the Histogram to appear, but the simplest incremental change would be to display it in the chart-tooltip below the existing contents of that module.
Once that is working, it would be relatively easy to change the placement because the most difficult part of adding dom-modules from tracing/ui to the dashboard is reconciling Polymer.Settings.useNativeShadow, which tracing/ui currently requires to be true, but the dashboard assumes to be false.
So we can incrementally add histogram-span to the chart-tooltip and evaluate improvements to the UX in parallel with finishing the pipeline on the backend.

**Comment by simonhatch** [comment]
I think figuring out the technical hurdles to including dom-modules from tracing/ui is definitely something we need to do.

AFAIK we have no consensus yet on where/how these things will get integrated, or what they should look like, on the dashboard so let's hold off on that part for now and just make this about figuring out the first part.

@eakuefner @anniesullie

**Comment by benshayden** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=865515
