### ISSUE TITLE
Redesign /list_tests API.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3632]
Currently, GetReportPageLink() in email_template.py speculatively guesses test paths by appending '_ref' and 'ref'. This requires /list_tests to silently ignore requests for test paths that do not exist.
Generally, the interface to /list_tests seems too complex.

@simonhatch @eakuefner I'm not sure if I have enough context to describe this bug adequately. Can you help clarify?

**Comment by simonhatch** [comment]
I believe that's what caused #3619 yes, maybe we should rename this to having a single way to get at ref tests? ( @eakuefner did you run into this while working on list_tests and is there something already on this?).

**Comment by eakuefner** [comment]
I'm not really clear on the context @benshayden is talking about, but I think https://github.com/catapult-project/catapult/issues/3263 is probably related.
