### ISSUE TITLE
Story Runner Unittest creates a results.html file that is not cleaned up

### ISSUE THREAD

**Issue by phrmsilva** [catapult-project/catapult#3634]
When Telemetry's story runner untitests are run, it creates an empty file at `telemetry/testing/results.html`. That is not being cleaned up. This seems like it is coming from tests' calls to the `CreateResults` method in Telemetry's `results_options.py`.

We have the options to either add a removal to the tests' tearDown process, or add a testing flag to the CreateResults methods.

It is unclear whether other unittests do the same.

cc @benshayden

**Comment by benshayden** [comment]
@eakuefner two questions:
 * Do you have a preference for whether tearDown() should os.remove() the empty file, or the tests should pass an option to CreateResults() to prevent that function from creating the file in the first place?
 * Also, it looks like CreateResults is also called in PageTestTestCase, but that doesn't appear to be used anywhere. Should that class be deleted?

**Comment by eakuefner** [comment]
* `tearDown` is the right place to do it, and there are several examples where we clean up file spew within tests, e.g. here https://github.com/catapult-project/catapult/blob/32bdd960945af3580a61f9640bbfe72677e458ac/telemetry/telemetry/page/page_test_unittest.py#L150. Let's avoid cluttering the already complicated CreateResults API.
* https://github.com/catapult-project/catapult/blob/32bdd960945af3580a61f9640bbfe72677e458ac/telemetry/telemetry/page/page_test_unittest.py#L71
