### ISSUE TITLE
Dashboard: Add warning on alerts over very large ranges

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3636]
We recently got data back on a benchmark that had been disabled for many months. This caused hundreds of alerts to come in at once, and confused the sheriff rotation, since it wasn't clear what happened. It would be good to mark alerts (in the alerts table and in the graphs) somehow to note that there is a long time period (> 2 weeks maybe?) between the point that alerted and the previous data point.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917908
