### ISSUE TITLE
Audit TBMv2 aggregations approaches

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3644]
We currently use mean / std most places.
There are some places we should switch to using percentiles / iqr.

Assigning to myself for now.

**Comment by tdresser** [comment]
@maxlgu @deepanjanroy

**Comment by benshayden** [comment]
@tdresser Can you either archive this or move it to crbug?

**Comment by tdresser** [comment]
Moved to our internal backlog.
