### ISSUE TITLE
Perf Dashboard: Clicking link from Alerts page opens graph page with no graph

### ISSUE THREAD

**Issue by majido** [catapult-project/catapult#3648]
Chrome version: 59.0.3071.86 (Linux)
URL: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgtqntuwoM

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:
When I click the alert's link from alert homepage it opens a graph page without any alert's displaying or checked. 

I suspect I may have marked the alert "ignored" before but somehow alerts homepage is still showing the old alert even after I refreshed multiple times.

**Comment by anniesullie** [comment]
@simonhatch @benshayden

**Comment by simonhatch** [comment]
I'll take a look.

**Comment by simonhatch** [comment]
Think this is the same max 500 alerts from #3625. In this case, there are well over 500 alerts overlapping that range, and the code in group_reports takes the keys, finds the anomalies associated with those keys, finds all anomalies overlapping the ranges of those keys, then returns at most 500 of them. The requested ones are also added to the list but at the end, and we only send the first 500.

We probably need to figure out what to do with this 500 alert cap, short term to avoid this type of situation could probably just rewrite that function a bit to make the requested anomalies part of the first 500.

**Comment by benshayden** [comment]
Looks fixed?
