### ISSUE TITLE
NetworkController can reference undefined trace_event.TracedMetaClass object

### ISSUE THREAD

**Issue by YngveNPettersen** [catapult-project/catapult#3649]
The telemetry/telemetry/core/network_controller.py class NetworkController include a statement

  __metaclass__ = trace_event.TracedMetaClass

This statement will fail, and raise an exception, if the trace_event module for some reason did not load the trace_event_impl module, because trace_event.TracedMetaClass is only defined if that trace_event_impl has been loaded.  (One reason why it can fail, is a missing pywin32 win32file module on Windows)

**Comment by nedn** [comment]
CL: https://codereview.chromium.org/2942213002/

**Comment by nedn** [comment]
Should be fixed now.
