### ISSUE TITLE
Group Alerts on the dashboard frontend

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3651]
Currently, the chromeperf dashboard runs an algorithm on the backend to group Alerts. Whenever an Anomaly or StoppageAlert (the two subclasses of Alert) entity is created, a complex algorithm (over 200 lines) updates the AlertGroup table and KeyProperties pointing from Alert to AlertGroup. There are known bugs in this algorithm that are difficult to fix due to the asynchronous nature of the database: #1677 #3246 #3219 #3567 . This algorithm is also difficult to modify because its state is persisted. Re-grouping existing alerts would require writing a tricky map-reduce. The edit-debug cycle is theoretically on the order of days, but nobody has tried to modify the algorithm so we aren't sure. This is effectively blocking improvements to the grouping algorithm explored in [Grouping Alerts for Related Histograms](https://docs.google.com/document/d/1ndFZoRqj_G-LFI202MCH4-DdAhXqkbRlyhp3Bieioeg/edit) (google-only).

These groupings are only used to simplify the alerts-table on the frontend (see notes in [Portrait of AlertGroup](https://docs.google.com/document/d/1PnfTF_kKbBfO6PXncEAZv1A72HDgcq6bQ7ooskJsI3k/edit) (google-only)), so it is possible to allow the frontend to perform the grouping after it queries the Anomalies and StoppageAlerts. This would make it impossible for the alerts-table to contain Alerts that should have been grouped but weren't. It would make it significantly easier to modify the algorithm because all of its state would be ephemeral. The edit-debug cycle would be shortened to seconds or minutes.
The frontend grouping algorithm would require less code than the backend algorithm because the backend algorithm needs to support updating existing AlertGroup and Alert entities, whereas the frontend algorithm would only need to handle the alerts that it receives.

Rewriting the algorithm but keeping it in the backend might not be able to fix the inconsistency issues due to the asynchronous nature of the database, and might not be able to reduce the edit-debug cycle time.

Next steps:
- #3652 Add a URI option to alerts-table to allow users to run the grouping algorithm in the frontend so that we can  compare the backend algorithm against the frontend algorithm.
- #3653 Refactor EditAnomaliesHandler, AssociateAlertsHandler, and FileBugHandler to modify the Alert entities directly instead of going through alert_group.ModifyAlertsAndAssociatedGroups.
- Remove references to AlertGroup from alerts-table.
- Remove AlertGroup from backend.
- Close all old bugs referencing alert grouping.

(I'll file bugs for the remaining steps as we approach them.)

**Comment by anniesullie** [comment]
Thanks for the clear explanation! As we discussed in the meeting this week, this approach wasn't the first that occurred to most of us, but you've made a clear and compelling argument for it. Excited to see this work happening!

**Comment by benshayden** [comment]
As we work to improve alert grouping, sheriffs need some way to compare grouping before and after changes. There might be many possible metrics, but the simplest is the number of groups. The grouping algorithm shouldn't necessarily try to drive the number of groups toward 0 to the detriment of alerts that should have been separated, but having this number can help sheriffs start to evaluate changes to the grouping algorithm.

@simonhatch WDYT?

![](http://i.imgur.com/rJC6qCW.png)

**Comment by simonhatch** [comment]
As a potential signal to help the sheriffs evaluate the changes, this sgtm. Got anything written up about your overall approach and how this fits in?

**Comment by benshayden** [comment]
[Grouping Alerts for Related Histograms](https://docs.google.com/document/d/1ndFZoRqj_G-LFI202MCH4-DdAhXqkbRlyhp3Bieioeg/edit#) is ready for review, especially sections
- [Plan for Evaluation](https://docs.google.com/document/d/1ndFZoRqj_G-LFI202MCH4-DdAhXqkbRlyhp3Bieioeg/edit#heading=h.t0myvjqn29m0)
- [Draft of Request for Sheriffs](https://docs.google.com/document/d/1ndFZoRqj_G-LFI202MCH4-DdAhXqkbRlyhp3Bieioeg/edit#heading=h.hwma00exef2s)
- [Related Histogram Names StringSet SparseDiagnostic](https://docs.google.com/document/d/1ndFZoRqj_G-LFI202MCH4-DdAhXqkbRlyhp3Bieioeg/edit#heading=h.hat73ac2y036) outlines the nuts and bolts of one way that grouping related alerts (or ungrouping unrelated alerts) could work.

**Comment by benshayden** [comment]
I haven't updated the design doc yet, but here's a demo of the hack that we discussed to ungroup memory regressions from other types of alerts.

This appears to have a negligible effect on the number of alert groups in Blink Memory Mobile Sheriff ([before](https://chromeperf.appspot.com/alerts?3651=y&sortby=end_revision&sortdirection=down&sheriff=Blink%20Memory%20Mobile%20Sheriff) vs [after](https://dev-benjhayden-87dc1066-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Blink%20Memory%20Mobile%20Sheriff)) and Desktop Memory Sheriff ([before](https://chromeperf.appspot.com/alerts?3651=y&sortby=end_revision&sortdirection=down&sheriff=Desktop%20Memory%20Sheriff) vs [after](https://dev-benjhayden-87dc1066-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Desktop%20Memory%20Sheriff)), except that alerts for changes in process_counts and dump_counts are ungrouped from memory regressions.

I'm not very familiar with the sheriff rotation configuration system. Does it offer most of the benefit that this change could have had?

**Comment by anniesullie** [comment]
Can you clarify what the hack does? My understanding was that we wanted memory regressions to be grouped by the metric, and not the benchmark. I see unrelated metrics being grouped together still in the after links, for example in memory.blink_memory_mobile I see memory:chrome:renderer_processes:reported_by_chrome:v8:effective_size_avg grouped with memory:chrome:renderer_processes:reported_by_chrome:font_caches:effective_size_avg and memory:chrome:renderer_processes:reported_by_chrome:skia:effective_size_avg in the first group of 17.

**Comment by benshayden** [comment]
[Code](https://codereview.chromium.org/2966353002)
All memory measurements are listed in a Set. Alerts are grouped together if either both of them are in the set, or neither of them.

I also tried using a prototype of [related names](https://codereview.chromium.org/2965853003) to generate a map from histogram name to sets of related names, and group alerts according to the [algorithm described in the doc](https://docs.google.com/document/d/1ndFZoRqj_G-LFI202MCH4-DdAhXqkbRlyhp3Bieioeg/edit#heading=h.hat73ac2y036) ([code](https://codereview.chromium.org/2971203002)), but that also had a negligible effect.

**Comment by anniesullie** [comment]
Ah. Almost all the memory benchmarks are separate from performance benchmarks, so I wouldn't expect this CL to make much difference. The grouping problem we have with memory is that unrelated memory metrics get grouped together.

**Comment by benshayden** [comment]
Thanks, that clarifies things.

I generated that related names map from a single desktop benchmark run, so it was probably missing a lot of potential relationships. I'll try to generate that map from memoryMetric's source directly so that it contains all potential relationships and see if it has a bigger impact on the grouping.

**Comment by benshayden** [comment]
112 groups [Before](https://chromeperf.appspot.com/alerts?3651=y&sortby=end_revision&sortdirection=down&sheriff=Blink%20Memory%20Mobile%20Sheriff) vs 261 groups [After](https://dev-benjhayden-6539cc70-dot-chromeperf.appspot.com/alerts?sheriff=Blink%20Memory%20Mobile%20Sheriff&sortby=end_revision&sortdirection=down).
[This version](https://codereview.chromium.org/2973883002) is based on my possibly mistaken reading of memoryMetric. (It is... complex.)
I'm going to try to figure out how to compare this new version to the [old version](https://codereview.chromium.org/2971203002) that was based on addRelatedNames of a single benchmark run. Feel free to let me know how I misunderstood memoryMetric's relationships or wait for me to take a closer look and report back.

**Comment by anniesullie** [comment]
Cool! I'm not sure what the right reading is exactly, but I do expect the number of groups to go up significantly.

**Comment by benshayden** [comment]
Here are updated demos after I fixed some bugs: [Desktop Memory Sheriff](https://dev-benjhayden-d5329c1a-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Desktop%20Memory%20Sheriff), [Blink Memory Mobile Sheriff](https://dev-benjhayden-d5329c1a-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Blink%20Memory%20Mobile%20Sheriff)
I'm still not sure that the list of memory metric names is complete, or that the generated relationships are accurate.

**Comment by benshayden** [comment]
I went ahead and made a demo of merging related alerts across benchmarks (Step 2 in the design doc): [triaged Chromium Perf Sheriff](https://dev-benjhayden-dac15b00-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Chromium%20Perf%20Sheriff&triaged=true), [Desktop Memory Sheriff](https://dev-benjhayden-dac15b00-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Desktop%20Memory%20Sheriff), [Blink Memory Mobile Sheriff](https://dev-benjhayden-dac15b00-dot-chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Blink%20Memory%20Mobile%20Sheriff), [CL](https://codereview.chromium.org/2983393002).

![](http://i.imgur.com/R2zEnhO.png)

Of course, let's focus on validating and landing Step 1 first, but feel free to poke at those demos for Step 2 as you wish.

**Comment by benshayden** [comment]
The next steps here are #3653  and #3014 .
