### ISSUE TITLE
Group Alerts on the dashboard frontend behind a flag.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3652]
This is the first step in #3651 .
This flag will allow us to compare the backend grouping algorithm to the frontend grouping algorithm. Both algorithms should have the same results.

**Comment by benshayden** [comment]
Links to compare:
- [current chromeperf.appspot.com](https://chromeperf.appspot.com/alerts)
- [demo without 3651=y](https://dev-benjhayden-28c79b4f-dot-chromeperf.appspot.com/alerts) uses the existing backend AlertGroup, just refactored to support a uri parameter to allow switching to the frontend grouping algorithm.
- [demo with 3651=y](https://dev-benjhayden-28c79b4f-dot-chromeperf.appspot.com/alerts?3651=y) groups on the frontend using the exact same criteria. **Actually produces fewer groups** presumably due to known inconsistency bugs in AlertGroup.

@simonhatch @eakuefner WDYT?

**Comment by anniesullie** [comment]
This looks great to me! Is there any way to do a quick JS timing to see how fast alert grouping is? Like just:

```
var start = new Date();
// group alerts
var end = new Date();
console.log('Milliseconds to compute: ', end - start);

**Comment by benshayden** [comment]
Grouping 500 alerts takes 22 ms on my desktop. [demo with 3651=y with tr.b.Timing](https://dev-benjhayden-40e9962b-dot-chromeperf.appspot.com/alerts?3651=y&sortby=end_revision&sortdirection=down)

**Comment by anniesullie** [comment]
That's great! I think we can definitely wait till code review to go over finer-grained details (like currently the console says it groups 3 times at load).

**Comment by benshayden** [comment]
That is a pre-existing bug: #3659
