### ISSUE TITLE
Improve usability of button to populate test picker in dashboard chart-title.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3663]
The button in the chart-title that populates the test picker uses the NW arrow to long bar unicode glyph, which is uncommon. It doesn't perfectly convey its purpose, it's just the closest icon we could think of.
It's also difficult to think of a 1 or 2 word phrase that would fit in the button without taking up too much room. "Populate test picker" would probably be too long to always display there, but displaying it onhover in the button title is certainly feasible and might help discoverability.

Also, there's a CSS bug where it can be split to a separate line when the chart title is too long, which takes up too much vertical space.

**Comment by anniesullie** [comment]
I really loved the ideas you and Hannah had at our discussion yesterday about making an expandable chart title/testpicker element for each chart. Is the plan to do some simple fixes in this bug and file an issue for the new menu?

**Comment by benshayden** [comment]
Yes, this bug is about small quick fixes to tide us over until we've finished designing and socializing the change to move the test-picker into chart-title.

**Comment by benshayden** [comment]
[Tooltip added](https://github.com/catapult-project/catapult/commit/c8c5d6b714f8929979b8ae457cbe05459d59b816).

Still need to fix the CSS bug by adding white-space: nowrap
