### ISSUE TITLE
Isolate Keys differ between str and unicode Changes

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3668]
I've run into an issue with the way we look up `Isolates`. We look up `Isolates` by (`builder_name`, `change`, `target`). We take that tuple and generate a hash, and use those hashes as the NDB Keys to make lookups fast.
```
def _Key(builder_name, change, target):
  string = '\n'.join((builder_name, repr(change), target))
  return hashlib.sha256(string).hexdigest()
```

Unfortunately, `repr()` has differing results when a `Change` has type `str`:
```
Change(base_commit=Dep(repository='chromium', git_hash='9e3eeee7b6604d0862a15de01b706e8507114f77'), deps=frozenset([]), patch=None)
```
And when it has type `unicode`:
```
Change(base_commit=Dep(repository=u'chromium', git_hash=u'9e3eeee7b6604d0862a15de01b706e8507114f77'), deps=frozenset([]), patch=None)
```

The Python built-in `hash()` has the same hash for `str` and `unicode`, but we can't use it. As @perezju rightfully said, `hash()` isn't guaranteed to be consistent across Python invocations. And in Python 3.3, it's initialized with a random seed to prevent hash collision vulnerabilities.

Using `str()` instead of `repr()` would work, but would fail if we ever decide to modify the output formatting of `Change`.

@perezju @simonhatch @anniesullie 
Do y'all have any ideas off the top of your heads that might work?

**Comment by perezju** [comment]
This might be playing it a bit too safe, but I would:
- In the constructors for Dep/Change/Patch cast all input args to be `unicode` (or all `str`, but for future proofing I would suggest unicode already).
- Add some `key()` method to these classes, which builds a string uniquely identifying the object (again I would use `unicode` as return type), e.g. `u'repository@full_hash'` for a Dep.
- Pass the utf-8 encoded keys to `hashlib.sha256` (which expects str or bytes).

**Comment by dave-2** [comment]
Not too keen on the first one, because it feels like we're trying to work around a design flaw in Python 2, and there's no reason why we should do this for Dep/Change/Patch and don't do it for any other class.

The second one sounds reasonable. That also helps with my other concern, which is that some other implementation detail besides the string type may derail the hash. With `key()`, we have full control over the hash value from within the class.

For the third one, it appears that `hashlib.sha256()` is also agnostic to string type, and we only have a problem with `repr()`. So replacing `repr()` with `change.key()` should be sufficient.

**Comment by dave-2** [comment]
Hmm, do I really even need to hash the string? The NDB docs don't state any limit or performance implications with the key length or contents.

**Comment by dave-2** [comment]
Found the answer. "Every index entry contains the key name it's referring to, so longer key names mean higher indexing overhead." And "key names are limited to 500 characters".

https://stackoverflow.com/questions/2557632/how-long-max-characters-can-a-datastore-entity-key-name-be-is-it-bad-to-haver

**Comment by perezju** [comment]
> For the third one, it appears that `hashlib.sha256()` is also agnostic to string type

As long as there are no unicode chars on your string; otherwise it fails, e.g.:

```
>>> hashlib.sha256(u'hello').hexdigest()
'2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824'
>>> hashlib.sha256(u'\u1f601').hexdigest()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u1f60' in position 0: ordinal not in range(128)
```

If the string is unicode I think it tries to do `str(s)` which leads to `s.encode('ascii')`. But I agree it's probably a safe assumption that the relevant strings will only contain ascii chars and we don't have to be as defensive as I proposed on my original suggestion.
