### ISSUE TITLE
Additional alert and "all graphs" links missing

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#3673]
Issues created today did not include the usual links:
 - Original alerts at time of bug-filing:
 - All graphs for this bug:

Example: 
 - https://bugs.chromium.org/p/chromium/issues/detail?id=736694
 - https://bugs.chromium.org/p/chromium/issues/detail?id=736687

**Comment by camillobruni** [comment]
If this gets fixed, would there be a way to re-attach the comments to all the performance issues that were created today?

**Comment by simonhatch** [comment]
I think this is due to #3666

**Comment by anniesullie** [comment]
In #3666, the links still show up in the bug, they are just very very long. In this one, we get no links. 

When I search go/chromeperf-logs for `path:/file_bug` and log level error, I get lots of 403 errors from monorail.  I filed a bug on the monorail project: https://bugs.chromium.org/p/monorail/issues/detail?id=2837

**Comment by anniesullie** [comment]
Closing as a dupe of #3699
