### ISSUE TITLE
[wpr-go] Replay with HTTP/2 only if it was used during record mode

### ISSUE THREAD

**Issue by xunjieli** [catapult-project/catapult#3674]
wpr-go uses HTTP/2 in replay mode for all archived responses. Ideally, we would like to match the network protocol used by the real server -- If the real server only speaks HTTP/1.1, the replay server should use HTTP/1.1 instead of HTTP/2.

\cc @nedn @tombergan

**Comment by nedn** [comment]
+1

**Comment by nedn** [comment]
Though I think we should do this after the wpr-go migration? Migration & fixing should probably be done sequentially to control the changes.

**Comment by xunjieli** [comment]
> Though I think we should do this after the wpr-go migration? 
I am not sure. I think we should figure out a way forward. 

One solution is to use a socks proxy to resolve dns requests and direct them either to an HTTP/1.1 server or an HTTP/2 server.
But tsproxy(catapult/telemetry/third_party/tsproxy) already uses a socks proxy. If we go down this route, it means that wpr-go won't work with tsproxy.

**Comment by xunjieli** [comment]
@pmeenan  Patrick, do you see another way (other than using a dns socks proxy) to make wpr-go match protocol usage?

**Comment by xunjieli** [comment]
It turns out that Tls.Config can be changed on the fly using GetConfigForClient
https://golang.org/pkg/crypto/tls/#Config

This is trivial then. I will upload a patch.

**Comment by xunjieli** [comment]
I will do a follow-up to add some tests. Marking this as fixed now.
