### ISSUE TITLE
Possibility to load data from prod in dashboard by uploading a json file

### ISSUE THREAD

**Issue by jonex** [catapult-project/catapult#3675]
It makes it easier to import data as the export URL can be accessed within a browser using already present authentication and saved to disk, and then imported using this page.

**Comment by simonhatch** [comment]
I'm not sure I understand this request, we'd have an endpoint on the dashboard that could accept manually submitted chartjson perf data?

**Comment by jonex** [comment]
I added this to the load_from_prod page, had to create an issue so I could submit the CL.

**Comment by simonhatch** [comment]
Think this was done a long time ago.
