### ISSUE TITLE
Get rid of TelemetryInfo.legacyTirLabel

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3677]
We want to get rid of the `legacyTirLabel` field of `TelemetryInfo`. There are two different use cases of TIR labels that we want to accommodate in doing so:

  1. TIR labels being produced from story grouping keys, as in https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/results/page_test_results.py#L322. In this case, we can safely ignore the TIR label, since story grouping keys will be preserved in TagMap/StoryInfo.
  2. TIR labels that are produced by any other method. A safe but potentially not very useful thing to do here would be to add a `tir_label:foo` tag for the tir_label.

We can accommodate both of these as follows: if story grouping keys are present, then that implies that the tir_label must have been produced according to them. In this case, we can ignore the tir_label and only add tags for the grouping key pairs. Otherwise, we will emit the `tir_label:foo` tag as described in 2. above.

**Comment by benshayden** [comment]
This is currently in [2959983002](https://codereview.chromium.org/2959983002).
