### ISSUE TITLE
[wpr-go] Upload binary to cloud storage and specify deps in binary_dependencies.json

### ISSUE THREAD

**Issue by xunjieli** [catapult-project/catapult#3678]
We need to compile wpr-go and upload the binary to cloud storage and specify the deps in catapult/telemetry/telemetry/internal/binary_dependencies.json.

/cc @nedn @tombergan

**Comment by nedn** [comment]
This should be fixed now. Later we can try to expand the binary on more platforms once we have integration test coverage.
