### ISSUE TITLE
Dashboard - when populateTestPicker clicked in /group_report, open /report in new tab.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3685]
There's no test picker

@benshayden @tdresser

**Comment by tdresser** [comment]
Or perhaps make the button pop open a new tab with a populated test picker?

**Comment by benshayden** [comment]
@eakuefner @simonhatch Can either of you point me towards a way to pass a test path to /report? Do I need to use PageState or is there an easier way?

**Comment by eakuefner** [comment]
You can use "old-style" query parameters, which are processed here: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/report.py#L43
