### ISSUE TITLE
Remove data stoppage alerts

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3692]
I just triaged 3,000 data stoppage alerts on the perf dashboard. I painstakingly went through each, looking for hints of what the root cause might have been. Almost every one was a bot turn down, a test turn down, a disable, a rename, or some other expected cause. We already have red steps on the perf waterfall when a test fails or the dashboard upload fails, so these alerts are a lot of work to triage, and providing little value. We'd like to remove them.

I did some datastore queries to see which rotations have data stoppage alerts. Only a few rotations are getting stoppage alerts, and even fewer are triaging them:

* The media team gets the alerts. @crouleau are they critical?
* The webrtc team has recently triaged some alerts, @ehlemur are they critical?

@simonhatch @benshayden @nedn

**Comment by CalebRouleau** [comment]
The alerts are too noisy to be of any use to us, honestly. It would be nice for us to have some quick and easy way to know that our tests haven't been turned off, but other than that we get little value from them. I wouldn't mind if they were deprecated.

The performance alerts we rely on heavily.

**Comment by anniesullie** [comment]
Thanks for the feedback! Perhaps a CL watch on the files where user stories are disabled would be a more effective way to catch this?

**Comment by hkjellander** [comment]
I think we've had use for them at some single time, but offline/malfunctioning bots should be detected with other kinds of monitoring, so I wouldn't mind having them turned down. As already mentioned, the usual causes of them are almost always turned down bots, disabled/renamed tests etc

**Comment by CalebRouleau** [comment]
@dalecurtis, any thoughts?

**Comment by dalecurtis** [comment]
So long as there's some mechanism for surfacing data stoppage I don't really care about the specifics of that mechanism. The historical problem we've always faced is a metric suddenly breaking and we don't know for months that it's stopped updating. I'd be against disabling them wholesale but supportive of making them more functional.

**Comment by anniesullie** [comment]
Do you have some example bugs? Are these from build breakages/disables, or green builds where the metric just somehow stopped reporting?

**Comment by CalebRouleau** [comment]
I think Dale is referring to breakages/disables. What happened for a while was that my team was not listed as the owner for the media.* tests so other teams would make changes to them without informing us. I think this problem is already solved now that we are listed as owners.

**Comment by anniesullie** [comment]
This is now **done**.
