### ISSUE TITLE
Chart X-axis should always be timestamp

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3694]
Currently the chart x-axis is set to `revision` (or `a_default_rev` if specified), and the x-axis is fixed because there isn't a sensible way to show distance between commits. But we also have a timestamp for each data point, and those do have a sensible distance that can be shown on the x-axis. I think always showing the points on the x-axis distanced by time would be easier for the user to understand, and also remove a lot of complex code in `chart-container.html`.

**Comment by anniesullie** [comment]
@perezju @simonhatch @benshayden @eakuefner FYI

**Comment by perezju** [comment]
I remember some perf bots were running revisions out of order. Is this still the case? That might cause a lot of confusion :confused:

**Comment by anniesullie** [comment]
To my knowledge, there was one bot that ran revisions out of order for 1-2 days during the swarming conversion (I think it was picking up builds from both 32 and 64 bit builders). Despite the fact that the dashboard ordered the revisions correctly, it was still super confusing!

I will do a one-off job to ensure that this is not a normal pattern for dashboard data uploads.

The alerting algorithm would still order the points by revision, so alerts in this case would have worked (except they wouldn't actually have alerted properly from two different builds)

**Comment by anniesullie** [comment]
Code review and demos: https://codereview.chromium.org/2970813004/

Looks like the CrOS data is all over the map, completely out of order :(

Will think more on what to do about this.

**Comment by benshayden** [comment]
I think revision timestamps #4218 should solve this.
