### ISSUE TITLE
Smoke test diagnostic equality

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3695]
It's crucial that Python diagnostic implementations specify an __eq__ because this is used by the histogram pipeline. Probably we want `Diagnostic` to specify an abstract `Equals` method that `__eq__` calls and then smoke test this.

**Comment by eakuefner** [comment]
Also, while doing this, we should add typechecks to the __eq__ method that we implement on `Diagnostic`; see https://codereview.chromium.org/2964713002/.

**Comment by eakuefner** [comment]
We should also smoke test this in JavaScript.

**Comment by simonhatch** [comment]
Latest failures in /add_histograms are diagnostics without __eq__ not getting deduped properly.

"tagmap diagnostics must be the same for all histograms"
