### ISSUE TITLE
Perf Dashboard: New bug should include links to graphs automatically

### ISSUE THREAD

**Issue by xhwang-chromium** [catapult-project/catapult#3699]
When filing a new bug using the "NEW BUG" button, the link to the graph is not automatically included. If I don't put anything in the "descriptions" section, the bug ends up with a one-sentence description "see the link to graphs below" without the actual link. See this bug for an example:

https://bugs.chromium.org/p/chromium/issues/detail?id=738712#c4

Maybe it's expected that people who file the bug should provide the link in the descriptions, but that's not intuitive nor obvious. If that's true, we probably should provide a template for people to follow. Even better, the system should be able to automatically include links to graphs when filing new bugs.

**Comment by CalebRouleau** [comment]
This definitely used to work: there would automatically be a comment on the bug added with useful links. Not sure what happened with xhwang@'s bug, but it would be great if someone could look into it.

**Comment by anniesullie** [comment]
We were investigating this in https://bugs.chromium.org/p/monorail/issues/detail?id=2837

The bug occurs if:
 * You're logged into the dashboard with an account that doesn't have Restrict-View-Google privileges and you file a bug
 * The bug automatically gets Restrict-View-Google label applied.

I'm working on a CL right now to work around by using the dashboard service account.

**Comment by anniesullie** [comment]
CL in progress: https://codereview.chromium.org/2967233002

**Comment by anniesullie** [comment]
This should be **fixed** now.
