### ISSUE TITLE
Catapult vulcanizer does not preserve order of scripts when inline and external scripts are interleaved

### ISSUE THREAD

**Issue by deepanjanroy** [catapult-project/catapult#3701]
To reproduce: 
1. Run `tracing/bin/vulcanize_trace_viewer --no-min`
2. Inspect contents of `trace_viewer_full.html`, and compare it with `tracing/extras/importer/jszip.html`. The jszip file currently has the format 
```
<script>
// some header code
</script>

<script src="path/to/jszip.js"></script>
<script>
// some footer code
</script>
```
The correct vulcanization should be 

```
// some header code
// jszip source
// some footer code
```

Instead we get (text search for "Vinn workaround for JSzip requiring window" to find this in `trace_viewer_full.html`):

```
// jszip source 
// some header code
// some footer code
``` 

I was trying to use a vulcanized trace viewer with Chrome Trace Processor and ran into this issue.

**Comment by benshayden** [comment]
Started, unless you already have a fix?

**Comment by deepanjanroy** [comment]
Previous discussion of bug in #2698. Still looking into this before accepting the hacky patch.
