### ISSUE TITLE
TryJob entities for failed bisects don't show in queries

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3702]
I'm working on https://codereview.chromium.org/2976503002/ which I want to use to get data about how successful bisects are (in addition to alert triaging and bug resolution). It looks like the TryJob.results_data has all the information I need to compute the result of a bisect, so that we wouldn't need to worry about changing the bisect comment confusing scripts.

But I'm running into a problem: for most bugs, I don't see no-repro bisects showing in TryJob queries. Examples:

```
from dashboard.models import try_job

jobs = try_job.TryJob.query(try_job.TryJob.bug_id==bug_id).fetch()
print len(jobs)
```

bug_id = 740128 (very recent job) prints 1.
bug_id = 737977 (week-old bug with 4 no-repro bisects) prints 0
bug_id = 737561 (week-old bug with 3 no-repro and 1 unable to narrow) prints 1
bug_id = 737510 (week-old bug with 2 no-repro and 1 repro) prints 1
bug_id = 737500 (week-old bug with 2 no-repro and 2 unable to complete) prints 0

I don't see these getting deleted anywhere or their bug_id getting reset, but I'm probably missing it?

@simonhatch, any ideas where the TryJob entities are going?

**Comment by simonhatch** [comment]
We just removed the retry logic, which used to delete the TryJob entities when it hadn't had a successful run after N tries.

The only way prior to that change to get data on how successful bisects were was to scrape crbug. Checking the TryJob entities should work now (after I think Tues/Wed of last week) but anything older will have deleted any failures.

**Comment by anniesullie** [comment]
Great! I added some custom logic for now, will be great to remove it in the future.
