### ISSUE TITLE
Async event time computation wrong for non-nested events.

### ISSUE THREAD

**Issue by dmurph** [catapult-project/catapult#3707]
See trace and corresponding results. IndexedDBTransaction::lifetime computation is wrong.
[traceAndResults.zip](https://github.com/catapult-project/catapult/files/1143411/traceAndResults.zip)

**Comment by dmurph** [comment]
@nedn

**Comment by nedn** [comment]
Replace this with https://bugs.chromium.org/p/chromium/issues/detail?id=741920
