### ISSUE TITLE
[wpr-go] Write a converter to convert old archive format (.wpr) to new archive format (.wprgo)

### ISSUE THREAD

**Issue by xunjieli** [catapult-project/catapult#3713]
Re-recording benchmarks turned out to be much more tedious than I expected. Some sites have changed and expectations need to be rewritten (e.g. https://bugs.chromium.org/p/chromium/issues/detail?id=742361). 

Instead of re-recording all benchmarks, we should try write a converter to convert the old format to the new format. Some fields are missing (e.g. negotiated protocol, certs used). We can write a script to fill in those fields after conversion. 

/cc @nedn @tombergan

master bug #3629

**Comment by tombergan** [comment]
> Instead of re-recording all benchmarks, we should try write a converter to convert the old format to the new format. Some fields are missing (e.g. negotiated protocol, certs used). We can write a script to fill in those fields after conversion

Could you cheat by loading the pages through wpr-go using wpr-python as a proxy?

chrome -> wpr-go -> wpr-python

**Comment by xunjieli** [comment]
That's a neat setup. Thanks for the suggestion! I've started on the converter path. If that doesn't work, I will investigate this option.

**Comment by xunjieli** [comment]
Fixed in https://chromium-review.googlesource.com/c/581747/.

Usage:
tools/perf/convert_legacy_wpr_archive convert /path/to/page_set.json

This will dump requests in .wpr files to .json files, use legacyformatconvertor.go to issue the same requests against the WPR python server, and save responses to .wprgo archive.
