### ISSUE TITLE
GetHistogramHandler leaks internal_only

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3714]
Currently, GetHistogramHandler returns `'Histogram "%s" not found for user'` for internal_only entities, but `'Histogram "%s" not found'` for missing entities. This allows external users to deduce which entities exist but are internal. These two error strings should be the same in order to prevent leaking that information.
@hannahtwiggsmith @simonhatch @eakuefner

**Comment by simonhatch** [comment]
Nice catch!

Although since they're accessed by guid, we're not leaking any names or anything other than it's existence. Still should fix it though, I can put up a cl.
