### ISSUE TITLE
Plumb SparseDiagnostics by name

### ISSUE THREAD

**Issue by phrmsilva** [catapult-project/catapult#3719]
Once the changes of converting some of our diagnostics into GenericSet diagnostics land, we will need to plumb these new diagnostics into Sparse Diagnostics by name (along with by type, which is the current way).

Once #3715 is done, until Sparse Diagnostics also use names for creation of instances, Ownership diagnostics will not be available.

CC @benshayden @eakuefner

**Comment by simonhatch** [comment]
@hannahtwiggsmith In case there's some overlap here

**Comment by benshayden** [comment]
Is this the same as #3718 ?

Also, Diagnostics in general won't be available until we turn on the histogram pipeline.

**Comment by phrmsilva** [comment]
@benshayden Yup, looks like a duplicate. I'll close this one.
