### ISSUE TITLE
Add a copy trace link on the perf dashboard

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3721]
Since google cloud storage generate ephemeral URLs for their URL, users usually mistakenly use those from the address bar for sharing trace links (see https://bugs.chromium.org/p/chromium/issues/detail?id=741695#c13). 

I think we can reduce the number of incidents like these by adding a "copy trace link to clipboard" button next to the Trace Link.

**Comment by nedn** [comment]
@simonhatch @anniesullie

**Comment by simonhatch** [comment]
Maybe something like this: https://material.io/icons/#ic_content_copy ?

**Comment by nedn** [comment]
SGTM. Though can we add tooltip which shows "Copy trace link to clipboard"?

**Comment by simonhatch** [comment]
Yeah, just figured an icon would be cleaner rather than more text.

**Comment by nedn** [comment]
Should we also inconify the trace link for consistency as well? :-)

**Comment by anniesullie** [comment]
This is **fixed**
