### ISSUE TITLE
Redesign diagnostic tables in histogram-span

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3724]
Related to #3507 , there will soon be many more histogram-level diagnostics, so the current diagnostics table will grow too large.
The histogram-span dom-module currently makes a distinction between histogram-level diagnostics and sample diagnostics.
TBMv2 now also makes a distinction between histogram diagnostics produced by metrics and histogram diagnostics with reserved names that are produced by other agents such as telemetry. For brevity, let's term this latter class of histogram diagnostics "metadata". Indeed, some of these metadata diagnostics are derived from trace metadata.
The UI should reflect this new distinction.
It would be very convenient if we could assume that users only ever want to see one of the 3 categories of diagnostics:

- metrics' histogram-level diagnostics
- metadata histogram-level diagnostics
- sample diagnostics

Let's make that assumption for now and see how well it works out. If there are too many complaints, we can go back to the drawing board.

We discussed two ways to structure the histogram-span to allow users to select which of the 3 categories of diagnostics are displayed:

1. Add a single metadata toggle button.
   - When active,
      - and bins are not brushed, then only metadata diagnostics are displayed.
      - and bins are brushed, then sample diagnostics are displayed.
   - When inactive,
      - and bins are not brushed, then only metrics' histogram-level diagnostics are displayed.
      - and bins are brushed, then sample diagnostics are displayed.

2. Add a tab-view containing 3 tabs for the 3 categories of diagnostics. If the histogram contains no sample diagnostics, then the sample diagnostics tab can be elided. If the histogram contains no metrics' histogram-level diagnostics, then its tab can be elided. If the user selects the sample diagnostics tab without manually brushing any bins, then it can automatically select all bins. The existing "Merge Sample Diagnostics" checkbox naturally belongs in the sample diagnostics tab. If the number of metadata diagnostics proves burdensome, then it can be split into more tabs such as "telemetry", "device", "other", etc. We assume that users compare contents of histogram-set-table-cells between columns within rows, so when the user selects a tab, the other cells in that row should update to display the tab for the same diagnostics category. This behavior suggests adding a string enum field to HistogramSetTableRowState. Alternatively, we could make the entire table display the same diagnostic category and put the string enum field on HistogramSetViewState.

Option 2 seems to offer better discoverability and extensibility, so let's try it first.

@simonhatch @eakuefner @hannahtwiggsmith @phrmsilva Thoughts?

**Comment by anniesullie** [comment]
Some pictures would really, really help here. Like a picture of what the current diagnostics would look like if we just dumped in all the new ones, and some mocks of suggestions 1 and 2.

When you're saying you think we can assume people only want to look at one of the 3 types of diagnostics at once, I think you're proposing that we reduce clutter by using this grouping? It would be good to understand the set of metrics we're looking at and what other proposed groupings would look like, too.

**Comment by benshayden** [comment]
http://www/~benjhayden/2982383002.html?q=TimeToFirstM%7Cpropo&s=avg&g=name&n=0&t=memory%3Achrome%3Aall_processes%3Areported_by_os%3Aproportional_resident_size-(c-(ToT-(o-1))).cpuTimeToFirstMeaningfulPaint-(c-(ToT-(o-1.b-0_62)))

![](http://i.imgur.com/VSOf6UKl.png)

**Comment by anniesullie** [comment]
I actually get a 403 for the full results.html link, any ideas?

**Comment by benshayden** [comment]
Sorry, I forgot to Share since I uploaded it via web form; I usually chmod a+r and cp it via CLI.
Try again?

**Comment by anniesullie** [comment]
The tabs look good to me.
