### ISSUE TITLE
Perf dashboard should show absolute change in bug title instead of percent

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3725]
I think this is difficult right now because often things are written in bytes, and the code to convert them to KiB, MiB etc is on the client side. But it would be really great if the bug title focused on the absolute change and not the percent change. This was just pointed out to me focusing on a regression in binary size, but the memory team has mentioned it as well ( @perezju @primiano WDYT?). I'm curious whether v8 team would prefer this as well? @camillobruni @natorion

**Comment by anniesullie** [comment]
@simonhatch @eakuefner @benshayden FYI

**Comment by perezju** [comment]
+1! Yes. For a while I was re-titling some memory bugs from relative to absolute changes. But of course me manually doing that work did not scale.

**Comment by natorion** [comment]
I think this highly depends on the benchmark/metric. We have benchmarks reporting microseconds, scores, milliseconds, bytes, megabytes, kilobytes, simple counters.

So, why not have both via #3150 ? :-)

**Comment by benshayden** [comment]
v2spa generates bug summaries in the frontend. 
https://bugs.chromium.org/p/chromium/issues/detail?id=917861
