### ISSUE TITLE
Document new GenericSet diagnostics in how-to-write-metrics.md and histogram-set-json-format.md

### ISSUE THREAD

**Issue by phrmsilva** [catapult-project/catapult#3730]
Once Ownership Diagnostics become instances of Generic Set, we should properly document that GenericSet Sparse Diagnostics named by OWNERS' and BUG_COMPONENTS' will be automatically added to every HistogramSet by Telemetry's story runner.

The same will be true for when DeviceInfo diagnostics are split into GenericSet

**Comment by benshayden** [comment]
Done.
