### ISSUE TITLE
"file a bug" link from a gasper alert will create a "Cr-Blink-JavaScript" label instead of a component

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3731]
"file a bug" link from a gasper alert will create a "Cr-Blink-JavaScript" label instead of a component.

Example: https://bugs.chromium.org/p/chromium/issues/detail?id=747799

**Comment by natorion** [comment]
Additionally:

-a bisect is not started automatically
-The alert is not associated to the bug

This is a completely different workflow than filing alerts via chromeperf. I would have expected it works the same way.

**Comment by anniesullie** [comment]
Sorry about that! This workflow was written way before the current dashboard and just never updated. I think it would be better if the links took you directly to the triage page for the alert (picking a random alert, it looks like this: https://chromeperf.appspot.com/group_report?sid=e4ba2ca2436b0b34e4d269eb667e25d010e7985076375a42b5eacf2395c026a4)

Would that be okay? I think trying to make all the triage actions work directly from the bug without looping into that page would add a lot of complexity to the code (leading to bugs) and also make it hard to prevent cross-site request forgery.

**Comment by natorion** [comment]
That would work too. Better to remove the feature instead of let it create "orphan" bugs.

**Comment by natorion** [comment]
I wonder if we have Analytics data for Monorail we could find out how often people would want to create an issue via the gasper mail. That would make it easy to decide if 1.) the feature is removed 2.) Fixed.

**Comment by anniesullie** [comment]
I have a WIP CL for this at: https://chromium-review.googlesource.com/#/c/catapult/+/752185

But it's blocked by #4021 (turns out some of the emails don't link to the right triage page)

@CalebRouleau FYI

**Comment by anniesullie** [comment]
I modified this so that it links to the right page to triage from the dashboard instead of the email. Example mail with the correct page: https://groups.google.com/a/google.com/d/msg/v8-perf-alerts/u55cewvx0Ys/6eHYl1deBQAJ
