### ISSUE TITLE
Pinpoint - Dashboard Integration

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3736]
This didn't have a tracking bug. Need to both put up a new job dialog from Pinpoint (done) and change the dashboard to use Pinpoint for whitelisted configs.

**Comment by simonhatch** [comment]
Here's the rough plan to get the dashboard integration fixed up for non-telemetry tests:

- Move bot_dimensions.json to the Dashboard (probably in a stored_object).
- Clone the Pinpoint dialog into Dashboard and remove references Pinpoint's elements.
- Modify the new Dashboard dialog to only contain a few modifiable fields (bug, story filter, start/end commit)
- Have the Dashboard backend do the conversion (bot -> dimensions) or guesswork (suite -> isolate target) before sending to Pinpoint's /new

@anniesullie @dave-2

**Comment by anniesullie** [comment]
This works for me

**Comment by simonhatch** [comment]
Done, any problems/etc will be done in follow ups.
