### ISSUE TITLE
Dashboard demo indicator

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3739]
Currently, the only way to tell whether you are looking at the production chromeperf.appspot.com or a demo version is the URL, which is easy to overlook and not captured in screenshots.

Miscommunications about dashboard demos can be avoided if they were visually distinguished from production somehow. One possibility is a thin colorful border all around the page. This border would be captured in screenshots regardless of scroll position. The color should avoid suggesting an error, but could suggest newness. Additionally, the word "Demo" can be displayed in the nav-bar with the same background color as the border in order to verbally explain the purpose of the border.

![](http://i.imgur.com/yNmEbsB.png)

@simonhatch @anniesullie WDYT?

**Comment by anniesullie** [comment]
lgtm!
