### ISSUE TITLE
Drawing different kinds of edges (flow events)

### ISSUE THREAD

**Issue by alanamarzoev** [catapult-project/catapult#3746]
Hi,

I was wondering if it is possible to modify the color/thickness of edges associated with flow events as a way of visually indicating different kinds of dependencies.

**Comment by benshayden** [comment]
[drawFlowEvent_](https://github.com/catapult-project/catapult/blob/7a394f2ae91916756d332f677321f1402b6ca8cf/tracing/tracing/ui/tracks/model_track.html#L350) already draws a few different styles of bezier curves depending on selection state, but could possibly be modified to vary color or thickness.

What exactly are you trying to do?

**Comment by alanamarzoev** [comment]
Is there a way to modify this just through changing something in the JSON? Specifically, I'm generating a task/object trace by converting task data into JSON (flow and complete events) and would like different colors/thicknesses for the flow event arrows with the goal of being able to differentiate between object dependencies and task dependencies.

E.g. - is there something along the lines of "cname" that can be used to specify color on edges (rather than on nodes)?

**Comment by benshayden** [comment]
It looks like FlowEvents already plumb cname in trace_event_importer.html, but drawFlowEvent_ just doesn't use it!
[Here's a patch to use FlowEvent.colorId in drawFlowEvent_](https://codereview.chromium.org/2989873002). I'll do a bit more testing and then mail it out. Feel free to comment there.

**Comment by benshayden** [comment]
You should be able to specify cname on flow events now.
This patch should be picked up by chrome://tracing via the usual chrome release process, but you can use it now if you check out catapult and use one of the scripts in tracing/bin/ like trace2html.
Thanks!
