### ISSUE TITLE
Measure dashboard alert grouping quality

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3750]
The dashboard groups alerts to save sheriffs time. The grouping algorithm is improving via #3651 , #3014  etc. There are currently no statistics anywhere to quantify how well alerts are being grouped. Good groups save sheriffs' time without hiding regressions. Bad groups either hide regressions or waste sheriffs' time by making them triage more groups than necessary.

Each alert can be assigned to one bug. Each alert group can contain alerts that are assigned to one or more bugs. Each bug can be assigned to one or more alerts in one or more groups.

- Bugs-per-group counts the average number of bugs in each group.
- Groups-per-bug counts the average number of alert groups that contain alerts assigned to each bug.

Ideally, both of these statistics would be 1: sheriffs can file 1 bug per group, and don't need to dup multiple groups to the same bug.

- When bugsPerGroup is greater than 1, then sheriffs are manually splitting groups into multiple bugs.
- When groupsPerBug is greater than 1, then sheriffs are manually duping groups to the same bug.

These statistics are retrospective, after sheriffs have already triaged them, so they are also affected whenever the grouping algorithm changes.

These statistics are heavily influenced by trivial single-bug single-group alerts, which are common.
If we want to ignore trivial alert groups, these statistics could be formulated instead as
- "plural groups" would count the number of groups in the table that have more than 1 bug.
- "plural bugs" would count the number of bugs in the table that are assigned to alerts that were grouped into more than 1 group.

There may be other possible statistics, but I'd like to start with adding bugsPerGroup and groupsPerBug to the triaged alerts-table and see what they say.

These statistics could be reported to Google Analytics, but that would rely on somebody opening triaged alerts regularly. I could use a chrome extension for that, but it feels like a hack.

@simonhatch WDYT?

**Comment by simonhatch** [comment]
I'm ok with adding them, and since they're only shown when triaged are shown, it's unlikely a lot of sheriffs will see/ask questions about them.

Would still like to know what the plan is a bit more concretely, will you be tracking these somewhere and presenting them in the related-histograms meetings? etc.

**Comment by benshayden** [comment]
I don't have a great plan for tracking them, but I could figure something out if that's important.
I was mostly imagining looking at them in a few weeks after the current changes settle down when we revisit the grouping algorithm. If either number rises significantly, then I'd look at how my changes caused a problem. If groups-per-bug is still significantly higher than bugs-per-group, then I'd look at how to merge more groups together.
How does that sound?

**Comment by simonhatch** [comment]
Sure, sounds reasonable!
