### ISSUE TITLE
Changing reference column/sort order creates history entries

### ISSUE THREAD

**Issue by pcc** [catapult-project/catapult#3755]
To reproduce:
1. Click on a link to a results.html page
2. Choose a reference column
3. Choose a sort order
3. Press back button

Expected behaviour:
Should go back to the page with the link to results.html

Actual behaviour:
The sort order changes back to its previous value. If I press back again, nothing happens.

**Comment by anniesullie** [comment]
@benshayden

**Comment by benshayden** [comment]
Yeah, the idea is that you can open a top-level histogram A, click a link to a related histogram B, then click the browser back button to go back to A.
But it isn't working very well, so I'll back out the pushState until I can debug it.
