### ISSUE TITLE
Add suggested owners to bug report

### ISSUE THREAD

**Issue by phrmsilva** [catapult-project/catapult#3760]
As we move away from pre-filling the owners field in the bug report, we want to find a better solution that will get rid of the owners sheet (at least for sheriffing bugs). With the current implementation, we expect to have owners diagnostics filled out for the Benchmarks where owners are defined so we could make use of that information to surface in a non-invasive way to the sheriff at the bug report process

**Comment by phrmsilva** [comment]
+ eakuefner

**Comment by eakuefner** [comment]
I think this is being covered by @benshayden's work on v2spa, so I'm going to go ahead and close it.
