### ISSUE TITLE
Dashboard - Improve testing coverage of UI

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3764]
Backend is often tested pretty rigorously but the frontend often doesn't get more than an instantiation test, feels like a bit of a blind spot on the Dashboard. Just logging this so we can loop back in the future. I know results.html has some fairly good coverage, maybe we can look at that for inspiration?

@eakuefner @anniesullie @benshayden

**Comment by benshayden** [comment]
V2spa frontend is tested pretty well.
