### ISSUE TITLE
Dashboard Python Tests failing, blocking catapult CQ

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3767]
@anniesullie @simonhatch @eakuefner @benshayden 

Example: https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Mac%20Tryserver/builds/8572
Can any of you address this as soon as possible?

**Comment by phrmsilva** [comment]
That's from a test I added, I'll look into it. Odd that it didn't fail in the CQ when I committed

**Comment by nedn** [comment]
Thanks!

**Comment by nedn** [comment]
For P0, I suggest revert your CL, reland & fix the tests to unblock other folks while you're debugging the failure.

**Comment by phrmsilva** [comment]
I have a CL to fix I'll send it now

**Comment by nedn** [comment]
The original CL is reverted in https://codereview.chromium.org/2997643002/

**Comment by phrmsilva** [comment]
Faulty tests have been reverted, let me know if this persists

**Comment by xunjieli** [comment]
CQ is still broken. I have CQ-ed my CL twice. https://codereview.chromium.org/2990423002/

**Comment by phrmsilva** [comment]
@xunjieli thanks for let me know.

A second CL has been reverted now. All dashboard tests that had been added in add_histograms are now reverted.

**Comment by phrmsilva** [comment]
Link to second revert: https://codereview.chromium.org/2999663002

**Comment by phrmsilva** [comment]
@xunjieli Could you please try running the CQ again, now that we have reverted a second CL, and let me know the outcome?

**Comment by phrmsilva** [comment]
From https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Linux%20Tryserver/builds/8701 looks like it's not working yet.

However the error message points to tests in `dashboard.add_histograms_test`

```[9/942] add_histograms_test.AddHistogramsEndToEndTest.testPostHistogramEndToEnd failed unexpectedly:
  Traceback (most recent call last):
    File "/b/build/slave/Catapult_Linux_Tryserver/build/catapult/dashboard/dashboard/add_histograms_test.py", line 79, in testPostHistogramEndToEnd
      '25f0a111-9bb4-4cea-b0c1-af2609623160',
  NameError: global name 'reserved_infos' is not defined
```

All other failures are similar.

However, from https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/add_histograms_test.py doesn't look like the code from master is using 'reserved_infos' anymore.

**Comment by phrmsilva** [comment]
I'm guessing the branch needs to be manually rebased to the HEAD of the remote master since I guess the CQ is not picking up the new reverted code

**Comment by phrmsilva** [comment]
I was able to do a dry run with the CQ ([see this CL](https://codereview.chromium.org/3000593002)) and everything passed. If the tests in `dashboard.add_histogram` are still failing, I recommend rebasing onto master to make sure the changes added by the reverts are accounted for in the CL.

My apologies for the inconvenience this may have caused, I'll follow up tomorrow with CLs covering the changes that were reverted today.

Please reopen this bug if the problem persists.
