### ISSUE TITLE
Clicking submit in /file_bug post shows "No alerts specified to add bugs to." 

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3771]
My steps:
Navigate to a /group_report page.
I can verify that I am already logged in the perf dashboard ("nednguyen@google.com" is shown in the upper right corner). 
Select a few graphs.
Click "Triage" button, then "New Bug".
Enter some texts in the bug form.
Hit "Submit".

What I expect:
Perf dashboard created a crbug for the regressions I triaged.

What actually happened:
The bug window shows "No alerts specified to add bugs to."

**Comment by anniesullie** [comment]
Any errors in JS console? What Chrome version/OS?

**Comment by nedn** [comment]
I already that windows, so JS console errors are lost.

Chrome version: Version 60.0.3112.90 (Official Build) (64-bit)
OS: Mac 10.12.16

**Comment by benshayden** [comment]
Archiving
