### ISSUE TITLE
Devil timeout_retry should state total timeout when it expires

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3776]
While investigating https://bugs.chromium.org/p/chromium/issues/detail?id=753793, I got hung up by the following error:

```
CommandTimeoutError: Timed out waiting for 'verify_charging', wait of 1.0 secs required but only 0.6 secs left
```

Why were we only waiting for 1s to verify charging, and why were we giving up when a full 0.6s of that 1s was remaining?

After talking to @jbudorick quite a bit, I realized that I was misunderstanding how the `timeout_retry` code worked: in reality, we were waiting for 29.4s and giving up because there wasn't enough time remaining for the last 1s polling period.

We should modify the `CommandTimeoutError` message to include not only the polling period and time remaining, but also the overall timeout.

**Comment by jbudorick** [comment]
iirc @perezju has done some work on this in the past & may have opinions here, too.

**Comment by perezju** [comment]
Yeah, I guess the current error message is just leaking some implementation detail which may not be that useful or relevant to the user reading the logs. Maybe just replace it with something like:

```
CommandTimeoutError: Timed out waiting 30 seconds for 'verify_charging'
```

??
