### ISSUE TITLE
Dashboard - Overlapping range queries

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3777]
This comes up often, most recently in https://bugs.chromium.org/p/chromium/issues/detail?id=755661

I'll just repost my comment from the bug:

I think this is largely due to how we query for ranges. Since AppEngine doesn't support  multiple inequality filters on a single query, we have trouble doing true range overlap queries. The workaround right now is to query for all alerts with end_revision >= revision, ordered by end_revision, and then manually test to see if their start_revision <= rev. The query is capped at 500 (for display).

Since there's nearly 9k commits between 480144 and 488973, there's going to be a tonne of alerts to sort through (most of which won't overlap the specified revision.

I think make this better, we need to revisit this query and either move to something that does support the query, or investigate something like geohashing.

@anniesullie @eakuefner

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917898
