### ISSUE TITLE
[wpr-go] Support archives recorded using localhost servers

### ISSUE THREAD

**Issue by xunjieli** [catapult-project/catapult#3787]
For more context, see:
https://bugs.chromium.org/p/chromium/issues/detail?id=757014#c6

Some archives might be recorded using a localhost server. To support this use case, we need to add an ability to remap localhost to a named host so WprGo can serve those requests. Telemetry starts Chrome using a host resolver mapping that excludes localhost.

**Comment by kenrussell** [comment]
Note: adding this functionality is now urgent. It's preventing the maps benchmark from being re-recorded per http://crbug.com/788060 and http://crbug.com/784418 .

**Comment by kenrussell** [comment]
We're instead proceeding with serving up the Maps team's data as static files and not recording them into WPR archives at all, so this can be closed per http://crbug.com/788060 .
