### ISSUE TITLE
[API][Feature Request] Implement Access-Control-Allow-Origin header for Chromiumdash

### ISSUE THREAD

**Issue by eleve11** [catapult-project/catapult#3792]
Context: I am working on extending Chromiumdash with some perf data from Chromeperf API. The authentication strategy is: sending a user authenticated request from the client side JS.

When sending a the request from the client side of Chromiumdash, Chromeperf returns a 405 because the Access-Control-Allow-Origin header is not set to allow cross domain requests from Chromiumdash.

The URLs would be: https://chromiumdash.appspot.com and https://6575-e7e1ae5-tainted-adolimpio-dot-chromiumdash-staging.googleplex.com/
for the second one I think the regexp should be:
`https:\/\/(?:\d+-(?:[a-z][a-z]*[0-9]+[a-z0-9]*)-(tainted-\w-dot-)?)?chromiumdash-staging\.googleplex\.com`
but please double check this.

Is it possible to add such support?

Note: the sent requests are POST but they get translated to OPTIONS with a access-control-request-method:"POST" header, for the same reason.

CC: @anniesullie @natorion @nedn

**Comment by eleve11** [comment]
updated regexp

**Comment by anniesullie** [comment]
CL out for review: https://codereview.chromium.org/3005493002/

**Comment by anniesullie** [comment]
This is now **fixed**.
