### ISSUE TITLE
Parts of a report not loading

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3820]
When I open https://chromeperf.appspot.com/report?sid=7623b4e9ccbd4479da04d77bde69837ed642ce323001bdd92ebb4ce37b656a48 Speedometer (1) keeps on loading but never finishes. What is happening?

**Comment by simonhatch** [comment]
I believe this was migrated recently from:

Total/http___browserbench.org_Speedometer_ -> Total/Speedometer

@ashley3

**Comment by ashley3** [comment]
Yep, looks like some of the bots kept reporting the old name past when I did the migration so I'll try to run the migrations again today

**Comment by simonhatch** [comment]
@natorion How did you get this link? It might just be an old link, the shorturi contains the page_state, which may just refer to an old name.

**Comment by natorion** [comment]
It is a link I use for a dashboard. I am surprised that there is no error
in case the benchmark is not there though.

**Comment by simonhatch** [comment]
Maybe we should just go and migrate page_states when we do migrations, there are < 200k of them.

**Comment by natorion** [comment]
I just noticed that there is indeed an error message: "Some charts failed to load. Either they don't exist, or they are empty, or they are accessible only for signed-in google.com accounts." Is this new? I can't recall that I have seen this particular phrasing before.

**Comment by simonhatch** [comment]
The message is somewhat new, last 2 months or so. Before that there was a similar message:

"No data available.
Note that some data is only available when logged in."

that was displayed on the graphs that failed to load.
