### ISSUE TITLE
Evaluate using HTTP push or vulcanization

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3824]
Once we have good analytics #3430 , then let's see if we want to try to speed up loading.
[http2push-gae plugin](https://github.com/GoogleChrome/http2push-gae)?
Py-vulcanize?
Polymer vulcanize?

**Comment by anniesullie** [comment]
I'm guessing #2652 will be the biggest performance win.

**Comment by benshayden** [comment]
v2spa is vulcanized, and plans some prefetching.
