### ISSUE TITLE
Roll Polymer 1.8 to start down the path towards Polymer 2.0

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3832]
The [Polymer 2.0 upgrade guide](https://www.polymer-project.org/2.0/docs/upgrade) recommends updating to Polymer 1.8, upgrading elements one at a time instead of one huge branch, and then updating to Polymer 2.0.
There are some cleanups that can be done after migrating to Polymer 2.0 tracked in #3058 .
This bug tracks updating to 1.8.
Is it as simple as bower update?
@eakuefner @zeptonaut

**Comment by zeptonaut** [comment]
My guess would be that it is as simple as a bower update, although doing this might require updating some other dependencies that it pulls in.

**Comment by anniesullie** [comment]
@dave-2 was mentioning it may be possible to do the pinpoint elements in polymer 2.0 relatively easily.

**Comment by dave-2** [comment]
We're already running Polymer 1.9.3! Surprise!
