### ISSUE TITLE
Dialog with point details no longer appears on chart

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3842]
When hovering over a line on [a chart](https://chromeperf.appspot.com/report?sid=690e7122b0fc9c0ea8f768b1bbafd988fd1c4166cc7cdd154a68e349d964881f&rev=1503046073), or trying to click on an alert, the dialog with details about the point no longer seems to appear.

This is bad, as I'm unable to e.g. kick-off bisects ... or do really anything with the data on the charts.

**Comment by perezju** [comment]
Weirdly the issue seems to be affecting [this chart](https://chromeperf.appspot.com/report?sid=ae4791152fdbe2b91b952621899ce2e7e16778ffee5378ab40e9b81fccc6be92&rev=1503046073), but not [this other chart](https://chromeperf.appspot.com/report?sid=ba97263b067fc751f7a9bdc08764b47b8afe2ba9818758e9604b5751c4830440&start_rev=492256&end_rev=500184).

**Comment by anniesullie** [comment]
Duping into #3842
