### ISSUE TITLE
RequestDebugTrace (--extra-chrome-categories) not working

### ISSUE THREAD

**Issue by altimin** [catapult-project/catapult#3844]
I requested a debug trace from perf waterfall with renderer.scheduler categories enabled.

Here is the generated try job: https://codereview.chromium.org/3009173002

But the resulting trace (https://console.developers.google.com/m/cloudstorage/b/chromium-telemetry/o/trace-file-id_4-2017-09-06_04-51-14-47168.html) does not contain requested categories.

**Comment by anniesullie** [comment]
Thanks for the detailed report! It made it really easy to spot the problem. Currently the `--extra-chrome-categories` flag is not supported for the thread_times benchmark. @nedn @zeptonaut does it make sense to add this in a one-off like I did for smoothness benchmark? Or will the benchmark be changed soon?

**Comment by nedn** [comment]
It will be changed in crbug.com/760553

**Comment by anniesullie** [comment]
I put up a CL for supporting this in thread_times in https://chromium-review.googlesource.com/c/chromium/src/+/658039

If we decide not to land it due to the upcoming change, @altimin you may be able to patch this into your tryjob at least.

**Comment by anniesullie** [comment]
Marking **fixed** since the change to telemetry is in.
