### ISSUE TITLE
Dashboard thinks commit positions after 500000 are not valid

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3855]
Start from e.g. [this chart](https://chromeperf.appspot.com/report?sid=d6957e69c2f909489ad115051b3d7fe15ab533e338c56163fcb76ef0238664ac) then try to kick off a bisect from one of the points close to the right (most recent).

"Start Bisect" button is disabled and error shows: "Revisions should be git positions or hashes".

![not_commit_pos](https://user-images.githubusercontent.com/16922344/30272948-cdc88a70-96ee-11e7-8c61-6606ec9436f5.png)

P1 as this greatly hampers the ability to easily kick off bisects.

A workaround is to figure out the corresponding git hash for each commit position and use those.

@anniesullie @simonhatch

**Comment by anniesullie** [comment]
CL up for review: https://codereview.chromium.org/3007373002

**Comment by anniesullie** [comment]
Verified on https://dev-sullivan-3e7cdead-dot-chromeperf.appspot.com/report?sid=d6957e69c2f909489ad115051b3d7fe15ab533e338c56163fcb76ef0238664ac, setting to default.

**Comment by anniesullie** [comment]
Removing P1 label as this should be fixed in production; will close when CL lands.

**Comment by anniesullie** [comment]
CL landed, this is now **fixed**.
