### ISSUE TITLE
Pinpoint - Error adding webrtc repository

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3861]
From https://pinpoint-dot-chromeperf.appspot.com/job/16c6a0ddb80000

@dave-2

**Comment by dave-2** [comment]
Looks like there are duplicate webrtc repos.

Primary one is at:
https://webrtc.googlesource.com/src
There's a name conflict when trying to add a mirror at:
https://chromium.googlesource.com/external/webrtc/trunk/webrtc

I also see that there's something else at:
https://chromium.googlesource.com/external/webrtc/ ?

I can manually add the mirror at a different name. Man, what should I call all these webrtcs?
`external/trunk/webrtc` and `external/webrtc`?

**Comment by dave-2** [comment]
Looks like webrtc just moved locations last night/this morning.

I've uploaded a patch to handle repos moving locations.
https://codereview.chromium.org/3013683002/
