### ISSUE TITLE
Slice titles in chrome_user_friendly_category_driver needs updating

### ISSUE THREAD

**Issue by deepanjanroy** [catapult-project/catapult#3864]
We are analyzing what chrome does during a page load across 10k-ish sites, and we are using the breakdowns from chrome_user_friendly_category_driver. Unfortunately, we often end up with a very large "other" category in the breakdown. I looked into what slices actually contributed to this other category, and here is a list of slice titles
[here is a list of slice titles](https://gist.github.com/deepanjanroy/84788dee9be12b01502a1708daf135da), sorted by total cumulative ms spent in those slices. 

Some of these slices clearly belong to some of the existing categories. For example,  'LocalFrameView::performLayout' should clearly be part of layout - I suspect the 'FrameView::performLayout' slice got renamed to this. 

Other slice like v8.callFunction might have gone away if we enabled v8 runtime call stats - more investigation is required.

**Comment by deepanjanroy** [comment]
cc @tdresser

**Comment by benshayden** [comment]
I noticed this will working on #3761 and started [trying to categorize some of them](https://codereview.chromium.org/3009553002/diff/360001/tracing/tracing/extras/chrome/chrome_user_friendly_category_driver.html). I can split and upload those changes or you can take them, up to you.

**Comment by deepanjanroy** [comment]
Thanks for already starting the work on this @benshayden! You can split and upload changes from that CL since you already have them - I'm not particularly rushed. 

I [started a spreadsheet](https://docs.google.com/a/chromium.org/spreadsheets/d/1L_z4hH-f31FQGTJEajMaQIDbrZ5vd9SwG493ePt6SqI/edit?usp=sharing) to collect the categories for the slices. I'm not familiar with most of these slices, so the appropriate categories are not obvious to me. For example, I'm not sure where to put `V8.NewContext` (does this go into v8_runtime?) or `ThreadProxy::BeginMainFrame` (is this composite?). If you know off the top of your head the category of any of those slices, especially in the top 50, feel free to add them to / comment on the spreadsheet directly.

**Comment by benshayden** [comment]
Archiving.
