### ISSUE TITLE
Perf Dashboard: 403 when using pinpoint for bisect

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3865]
Chrome version: 61.0.3163.79 (Linux)
URL: https://chromeperf.appspot.com/report?sid=d520c90500207dfdfd4df0c1125ae9ea75669e3357d7100fa93a2cc206074bc2

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Failed to load resource: the server responded with a status of 400 ()
/pinpoint/new/prefill Failed to load resource: the server responded with a status of 403 ()
2/pinpoint/new Failed to load resource: the server responded with a status of 403 ()
/pinpoint/new/prefill Failed to load resource: the server responded with a status of 403 ()
jquery.flot.min.js:7 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
    at Canvas.resize (jquery.flot.min.js:7)
    at Plot.plot.resize (jquery.flot.min.js:7)
    at HTMLElement.resizeGraph (chart-slider.html:402)
Canvas.resize @ jquery.flot.min.js:7
Plot.plot.resize @ jquery.flot.min.js:7
resizeGraph @ chart-slider.html:402

Please describe the problem:
I can't start a bisect with Pinpoint because of authentication errors . See screenshot.
![6tsthxs1cqz](https://user-images.githubusercontent.com/7190422/30481798-b59c749a-9a20-11e7-9744-9957ed87ed0b.png)

**Comment by anniesullie** [comment]
@simonhatch @dave-2

**Comment by anniesullie** [comment]
Quick initial analysis: I made a test bug (crbug.com/765641) and tried to bisect:
1. Not logged in: failed with a clear error message telling me to log in, not a 403
2. Logged in from google.com, appeared to succeed and posted a bug comment.
3. Logged in from chromium.org, appeared to succeed and posted a bug comment.

So I'm not sure how to reproduce. Then I checked go/chromeperf-logs, and searched for `status:403 path:/pinpoint`. I see 2 requests to each of `/pinpoint/new` and `/pinpoint/new/prefill` which each result in 403 response with no logs. @simonhatch @dave-2 any ideas why?

@natorion in the meantime you can follow along on crbug.com/765641 to see the bisects.

**Comment by simonhatch** [comment]
Yeah that's really strange, I can't reproduce this either. Went through the same steps as @anniesullie (except I didn't kick the bisects), and got the same results. The js error is a little strange, since it seems to imply that something else also went wrong on the page, since there's a flot error there with invalid dimensions.

**Comment by anniesullie** [comment]
Is there any logging we could add to get more details on why it returned 403?

**Comment by dave-2** [comment]
I see a bunch of similar log entries from last night, just before midnight PDT. Looks like someone tried and wasn't able to kick off 5 bisect jobs.

**Comment by dave-2** [comment]
I found it.

Dashboard's `app.yaml`:
```yaml
- url: /pinpoint/.*
  script: dashboard.dispatcher.APP
  login: admin
  secure: always
```
It's only available to people logged in as a perf dashboard admininstrator.

**Comment by simonhatch** [comment]
Ooh nice catch!

**Comment by anniesullie** [comment]
+1, good catch, @dave-2!
