### ISSUE TITLE
Bisect dialog should prefill bug_id on /group_report?bug_id=XXXX

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3876]
The use case I have is that I'm on the /group_report page looking at a perf regression. The graph steps up strangely, so that maybe the regression is actually one before or one after the point with the alert, I can't tell. I know there are longer-term ways to address this use case (allowing people to specify multi-point alerts), but in the short term, I think that defaulting the bug_id to the argument in /group_report?bug_id=XXXX would save a lot of time.

@benhenry in case he disagrees.

@dave-2 @simonhatch

**Comment by simonhatch** [comment]
How's this: https://dev-simonhatch-86c099bf-dot-chromeperf.appspot.com/group_report?bug_id=763873

**Comment by anniesullie** [comment]
LGTM!

**Comment by benhenry** [comment]
Yeah, I don't disagree, this is cool.
