### ISSUE TITLE
Pinpoint chart data visualization

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3877]
Currently, the Pinpoint chart looks like this.
![image](https://user-images.githubusercontent.com/211662/30608682-fb033dba-9d2d-11e7-91af-9d5911bb05eb.png)

We have #3869 filed to show the points at their proper distances, but there's also a question of how best to show the distribution of each point.

## Areas
I have a prototype that shows the quartiles using areas. This makes it clearer that there are outliers skewing the range.
![image](https://user-images.githubusercontent.com/211662/30609828-42a8f206-9d31-11e7-9cfc-625020117318.png)
Please excuse the weird point icons. The final product would have splits in the lines and areas as in the current version.

## Stacks
I also have a version that shows the quartiles using stepped areas. This makes it very easy to compare adjacent data points. It's much clearer to see why bisect decided there was a break on the right side here -- the interquartile ranges don't overlap at all.
![image](https://user-images.githubusercontent.com/211662/30610121-1c9593a2-9d32-11e7-85de-def574c98747.png)
The final product would also have the highlighted pulsing points (well, pulsing lines in this case) as in the current version.

## Dots
Juan (@perezju) also suggested using dots to represent the exact data points. This makes it very obvious if the data is bimodal, whereas the stacks do not. We can scale to thousands of data points by bucketing the data and showing the median of each bucket. It's unclear what we would do for points that are off the graph.
![image](https://user-images.githubusercontent.com/211662/30609029-109253f4-9d2f-11e7-9030-38a59792eb83.png)
The final product would also have the medians plotted as bigger points and connected as in the current version.

## Heatmap
One way to think about this is a cross between stacks and dots. Individual data points show up as horizontal lines, and we use opacity to show density if there are multiple lines in the same spot.
![image](https://user-images.githubusercontent.com/211662/30609454-4c4bc92e-9d30-11e7-864d-c15dbbe34532.png)
![image](https://user-images.githubusercontent.com/211662/30609477-54245e2c-9d30-11e7-8c18-379410af0b29.png)
These particular ones have many series plotted in different colors, which is very data-dense, but starts being hard to read past 2-3 series.

## Other
???

@perezju @simonhatch @anniesullie @benshayden

**Comment by anniesullie** [comment]
This is super exciting! I really love the stacks, but I can see the value in seeing all the dots (and don't know what to do about ones that go out of range either).

I've always loved the idea of heatmaps, but it does feel a bit like information overload.

Do any of these look significantly less readable if we show the distances between commits?

**Comment by dave-2** [comment]
I think it's possible to have heatmaps that don't feel like information overload. This comparison is a big misleading, because the amount of data on those heatmaps is several orders of magnitude higher than the rest of the charts.

**Comment by benshayden** [comment]
I like the stacks, too!

[UMA Timeline](https://uma.googleplex.com/p/chrome/timeline_v2/) draws multiple lines when you select multiple percentiles. WDYT?

When would pinpoint plot multiple timeseries?

**Comment by perezju** [comment]
I like the heatmap idea too. It's basically like the dots, but bucketed and using opacity to show density. I don't think it would look too information dense; if anything it would look cleaner than the dots themselves and there is no issue to scale with thousands or more data points.

**Comment by anniesullie** [comment]
Maybe we should try implementing a heatmap? A well-done one might just end up looking like a better stack.

As to @benshayden's question about when we'd plot multiple timeseries, the biggest thing I can think of is that we know some histograms are related, and maybe we could show breakdown timeseries to help understand whether a specific breakdown metric would be better to bisect on next.

**Comment by benshayden** [comment]
Would it make sense to use sparklines for breakdown timeseries on pinpoint to be consistent with the dashboard's charts?

**Comment by dave-2** [comment]
I've whipped up a demo with a heatmap. Here it is with a variety of data types:

## Single peaked
https://pinpoint-dot-chromeperf.appspot.com/job/14df783e780000
![image](https://user-images.githubusercontent.com/211662/31357928-831e516a-acf8-11e7-8c57-48ad1d89219e.png)
https://dev-dtu-568fb944-dot-pinpoint-dot-chromeperf.appspot.com/job/14df783e780000
![image](https://user-images.githubusercontent.com/211662/31357932-8754e55a-acf8-11e7-940f-58d31794c564.png)

## Bimodal
https://pinpoint-dot-chromeperf.appspot.com/job/14fde9d4780000
![image](https://user-images.githubusercontent.com/211662/31357969-a74101d2-acf8-11e7-97af-a399ecb28957.png)
https://dev-dtu-568fb944-dot-pinpoint-dot-chromeperf.appspot.com/job/14fde9d4780000
![image](https://user-images.githubusercontent.com/211662/31357976-aaeeb842-acf8-11e7-83ab-b04fc7692b29.png)

## Low noise and high noise
https://pinpoint-dot-chromeperf.appspot.com/job/128f1e09780000
![image](https://user-images.githubusercontent.com/211662/31358352-1e7087e0-acfa-11e7-96fc-6235d8d4dc70.png)
https://dev-dtu-568fb944-dot-pinpoint-dot-chromeperf.appspot.com/job/128f1e09780000
![image](https://user-images.githubusercontent.com/211662/31358357-21bb1578-acfa-11e7-94b9-7820b98f4656.png)

# Some considerations
## Bucket size
I've chosen ~10 buckets, so that the buckets match the y-axis ticks exactly. And [research seems to indicate](https://en.wikipedia.org/wiki/Histogram#Number_of_bins_and_width) that we don't need that many. But I think it works well with many more buckets, too, though it does start looking a bit cluttered:
![image](https://user-images.githubusercontent.com/211662/31358068-006d673c-acf9-11e7-887c-18a8decadc9d.png)

## Median/mean lines and flashing dot
Since it's more information dense, I've found it difficult to overlay median lines in a way that looks good. And without median points or lines, there's no flashing dot, either.

Some possibilities might be to reduce the opacity of the histogram or to use the secondary color (pink). But the secondary color is already used for selecting on the graph. It also is easier with fewer buckets than more buckets.

I do find that it is still easy to see at a glance what's going on even without the medians, so maybe it's better without them. As an alternative, I've split the heatmap in places where Pinpoint detected a difference, and automatically selected the biggest difference.

## Zooming
I've added a zoom button. Since we now want to see the entire distribution and not just the medians, it's become more important to be able to zoom out. I've added a zoom-in animation on-load to indicate to the user that it's zoomed in. The buckets automatically split and merge when zooming in and out -- you'll see a subtle jitter in the zoom animation when this happens.

## Side histogram
Since the main chart is a histogram with zoom now, we can move the Values histogram to the right of the chart, to align its y-axis, buckets, and zoom with the main chart.

**Comment by perezju** [comment]
I think this is moving in the right direction, the heatmaps do convey more information and I think they are intuitive to read (not sure what others think?)

Some random thoughts/observations:

* Zooming: I think the zoomed out version might work better as the default (and maybe only) version
* On bucket size: It does seem to me that more buckets actually make the trend easier to view, and the whole graph looks less "blocky". Taken to the extreme, this lands back into just plotting the actual points, which would eliminate the "clutteredness" and may make it possible to add back the median lines?

  Can we estimate how many points such a graph will typically have? Maybe they are not that many after all?

As this is highly subjective will be very glad to hear the opinions from others.

**Comment by simonhatch** [comment]
Spoke a bit offline with Dave earlier in the week, will record thoughts here.

Really like the heatmaps, they do convey a lot of information that I think is otherwise not available. At the same time I find them something unintuitive about them that I can't put my finger on, maybe that's just a side effect of them being such a new visualization approach (to me). Might be after more extensive use they'll feel a bit more natural. Maybe I'm used to seeing a mean being plotted (would plotting a line chart over the heatmap be weird?).

I know Dave's got some more ideas up his sleeve, moving the histogram in line with the chart and overlying before/after which could be really interesting.
