### ISSUE TITLE
Pinpoint - Some sort of way to get stats out of Pinpoint

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3879]
Similar to bisect stats, ie. repro, no repro, failure, etc.

@dave-2

**Comment by perezju** [comment]
I'll also be very interested in reviewing the sort of stats we can get out of pinpoint to track issues with our benchmarks/metrics etc.

**Comment by simonhatch** [comment]
Not sure if we want to combine these, but it came up recently that something similar would be useful for perf sheriffs as well if dashboard could query for for a list of bugs to follow up on, for example.

@anniesullie
