### ISSUE TITLE
Pinpoint: Values on a datapoint should be alligned on the y, not the x axis

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3882]
The main graph shows aligns the value of the benchmark result on the y axis. When I click on one datapoint there appears a values box. This box aligns the values on the x axis. Please also align the values in the box on the y axis so it is consistent. See screenshot for more context.

![image](https://user-images.githubusercontent.com/7190422/30632925-0dc8c2d2-9dea-11e7-87b8-a6beafd06b7d.png)

**Comment by dave-2** [comment]
Hi Michael, curious what information you want from the graph, so I can understand how to best meet your needs.

Right now, the graph just shows the shape of the distribution, e.g. is it normal or bimodal or does it have a long tail? Neither axis is aligned.

**Comment by natorion** [comment]
I think the information on the graph is already useful. I simply think that flipping the axes is beneficial because it repeats the model used in the actual bisect/regression graph on top of Pinpoint (and Chromeperf). There the time axis is always the x axis, and the value axis is the y axis. Here it is the opposite when one assumes that multiple runs = time.

**Comment by dave-2** [comment]
Oh! Got it. You're talking about flipping the x and y axes. That makes sense, can do.

I thought you wanted all the data points to use the same y scaling. Sorry for the confusion.
