### ISSUE TITLE
Pinpoint should assign bugs and cc relevant people

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3890]
Based on discussion in today's speed services meeting, and follow up discussions from [crbug.com/739133](http://crbug.com/739133), pinpoint should do the following when it finds culprit CLs:

* Assign the bug to the author of the culprit with the largest regression
* Cc the reviewers and review-cc of the culprit (this is especially helpful in cases where regressions are submitted by people who don't have editbugs, don't contribute regularly, or don't read bugmail)
* Also cc author/reviewers/cc list of any smaller regressions.

@simonhatch @benhenry @dave-2

**Comment by simonhatch** [comment]
@natorion

**Comment by dave-2** [comment]
Current status: completed points 2 and 3, but not 1 (it assigns the last regression in the range, not the largest regression)

**Comment by dave-2** [comment]
The most important part of the work is done, so I created a new bug for point #1 with a lower priority (#4123)
