### ISSUE TITLE
validate_all_diagnostics produces import error during presubmit

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3894]
I'm having trouble uploading my changelist, which is a simple change that removes one power metric but doesn't touch any diagnostics.

When I run `git cl upload`, I get:

```
** Presubmit ERRORS **
Failed validate_all_diagnostics: 

***************
Traceback (most recent call last):
  File "/usr/local/google/home/charliea/github/catapult/tracing/bin/validate_all_diagnostics", line 21, in <module>
    from tracing.value.diagnostics import diagnostic
ImportError: No module named value.diagnostics
***************
```

Any idea what might be going on? Strangely, it looks like this code hasn't been touched in a while, so I'm wondering if it's just something that I've done wrong. (I eventually got around this by running `git cl upload --bypass-hooks`.)

**Comment by benshayden** [comment]
Unable to repro. Maybe your $PYTHONPATH is pointing to another `tracing` directory?
```
import tracing
print tracing.__file__
```

**Comment by zeptonaut** [comment]
I don't have my laptop with me today to try this again, but I'll update this bug again when I do.

**Comment by zeptonaut** [comment]
I don't think so :-/ 

```sh
[~/github/catapult (rm_after_load_power)] echo $PYTHONPATH

/usr/local/buildtools/current/sitecustomize:/usr/local/google/home/charliea/google_appengine:/usr/local/google/home/charliea/google_appengine
```

To repro this, I just deleted part of a comment in `power_metric.html` and tried to run `git cl upload`. I'm pretty sure that, last time, I ran into this problem on my laptop, and this time I did on my desktop, so it seems to repro across devices.

**Comment by zeptonaut** [comment]
Hm, this also seems to happen when I run `validate_all_diagnostics` directly, regardless of the directory that I'm in.

**Comment by benshayden** [comment]
Still unable to repro on linux desktop and mac laptop.
Is there a `__init__.py` file in tracing/tracing/value/diagnostics/? Try removing `__init__.pyc`?
`git config remote.origin.url` should say `https://chromium.googlesource.com/catapult`.
`git pull --rebase`?
`git status`?
`git diff origin`?
What does `print tracing.__file__` say?

**Comment by zeptonaut** [comment]
Removing the __init__.pyc files did the trick! Thanks Ben!
