### ISSUE TITLE
Investigate different hypothesis tests

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3898]
MWU is very simple to implement and pretty good at functional bisects, where all the data points are 0 or 1. But it's not very good at comparisons where the mean and median don't move much but the amount of noise changes. There are other hypothesis tests that have the reverse characteristics. We should consider doing multiple hypothesis tests at the same time and using the lower p-value or something like that.

Here's a job where the mean didn't change that much compared to the noise. The left point is very bimodal, with several values above the entire distribution of the right point, so I would consider this to be a change of noise from high to low.
https://pinpoint-dot-chromeperf.appspot.com/job/16b7e3ffb80000

**Comment by anniesullie** [comment]
Another example I think would be good to investigate in this bug:

These two bisects are for very similar regressions (warm vs cold page load time on the same page/device):

https://pinpoint-dot-chromeperf.appspot.com/job/100a0b2fb80000
https://pinpoint-dot-chromeperf.appspot.com/job/16b7e3ffb80000

First one looks great. In the second one, I think most chrome devs would look at the chart and say there is a regression.

**Comment by dave-2** [comment]
Whoops, that's the same example!

**Comment by dave-2** [comment]
https://pinpoint-dot-chromeperf.appspot.com/job/16b133ea840000

The p-values I got:
With MWU: 0.121703560217
With KS: 3.6276162006545173e-06
With A-D: 7.084135146700235e-05

**Comment by dave-2** [comment]
https://pinpoint-dot-chromeperf.appspot.com/job/148d2146840000

**Comment by dave-2** [comment]
Since we now have K-S, I'm closing this bug. We may want to investigate more in the future by asking statistics-discuss, but all of the above jobs should work now.
