### ISSUE TITLE
Dashboard - Alert icons are displayed in front of the chart tooltip

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3908]
<img width="742" alt="screen shot 2017-09-25 at 10 08 35 am" src="https://user-images.githubusercontent.com/11619067/30812722-8d9bb76a-a1d9-11e7-8dd7-911130b8d298.png">

@benshayden

**Comment by benshayden** [comment]
Oh, z-index.

**Comment by simonhatch** [comment]
Ben fixed this a while back.
