### ISSUE TITLE
Automatically set TOT as reference column

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3909]
Chrome perf bots produce results.html files containing 2 columns: "Patch", "TOT". Most users usually want to compare Patch to TOT.
Results.html cannot rely on there always being these 2 columns, but when these are the 2 columns, it can automatically select "TOT" as the reference in order to save users 2 clicks.

Thanks, @agrieve !

**Comment by benshayden** [comment]
I started to make a [change](https://chromium-review.googlesource.com/c/catapult/+/693397) to results.html to do this, but @nedn objected. We agreed to instead add `?r=TOT&s=%25Δavg` to the buildbot output's link, so I'll investigate that route instead.

**Comment by benshayden** [comment]
I had assumed that query parameters would survive when cloudstorage redirects to apidata.googleusercontent.com, but that does not appear to be the case ([location.search doesn't work](https://console.developers.google.com/m/cloudstorage/b/chromium-telemetry/o/html-results/results-2017-10-10_19-21-40?r=TOT&s=%25Δavg)), so this approach won't quite work.

The fragment does survive, so I can make results.html optionally use that instead, and update this CL to use '#' instead of '?'. ([location.hash would work](https://console.developers.google.com/m/cloudstorage/b/chromium-telemetry/o/html-results/results-2017-10-10_19-21-40#r=TOT&s=%25Δavg))

Steps:

1. Make results.html use either location.search or location.hash.
1. [Add `#r=TOT&s=%25Δavg` to the buildbot output's link](https://chromium-review.googlesource.com/c/chromium/tools/build/+/695806)

**Comment by anniesullie** [comment]
This plan sgtm, but can you clarify what happens if both hash and query are set?
1. If both hash and query are set at the start
2. If we generally prefer one, do we migrate to it? Like we prefer query, we see something in the hash, do we update to use query next time we change the query?

**Comment by benshayden** [comment]
If hash is set, then results.html will use hash regardless of whether query is set.
If hash is not set, then results.html will use query regardless of whether the query contains unrecognized parameters like cloudstorage's `qk` parameter.
This isn't a principled strategy, it's a pragmatic workaround for the cloudstorage URLs specifically that should probably also work for other similar situations if any crop up.
I could make it just always use hash, that would be simpler, but I'm not sure if there might be contexts where it would be better to use query instead, and it isn't too hard to support both.

Maybe what we really need is a histograms viewer on chromeperf.appspot.com that takes a json url, like [the devtools timeline viewer](https://chromedevtools.github.io/timeline-viewer/)? That would simplify telemetry a bit. That would also allow gzipping the histograms json, which is difficult to do with vulcanized results.html files. It would require network access to view telemetry results unless the user had previously accessed the viewer to cache it.

**Comment by anniesullie** [comment]
If we had a histogram viewer like the devtools timeline one, would the histograms still be stored in cloud storage?

**Comment by benshayden** [comment]
If they're successfully uploaded and if there's an endpoint like /results2 to query and display all of the histograms from a given benchmark run, is there any reason to still store them in cloudstorage?

**Comment by anniesullie** [comment]
That's my question: uploaded to where? For data that's already perf dashboard timeseries, I think you mean it's in the data store, which is fine. But when you run locally, or with a perf tryjob, where is it uploaded?

**Comment by benshayden** [comment]
If the histograms are uploaded to the dashboard, then the link can be something like 
`https://chromeperf.appspot.com/histograms?uploadTimestamp=1234567890&r=TOT&s=%Δavg`

If the json is uploaded to cloud storage (or Drive or another filesystem accessible over http) instead of the dashboard, then the link can be something like
`https://chromeperf.appspot.com/histograms?r=TOT&s=%Δavg&
jsonUrl=https%3A%2F%2Fconsole.developers.google.com%2Fm%2Fcloudstorage%2Fchromium-telemetry%2Fo%2Fhistograms-2018-01-01_00-00-00.json`

Perf try jobs currently vulcanize a results.html and upload it to cloudstorage and display the cloudstorage link, but if we had a /histograms endpoint, then perf try jobs could skip vulcanizing, just upload the json to cloudstorage, and display a `/histograms?jsonUrl` link.

If the histograms are not uploaded anywhere that is accessible over http, then telemetry could either
- ask users to manually open the local json file in `https://chromeperf.appspot.com/histograms`, or
- vulcanize a results.html.

We could do a short survey or something to see if manually opening the local json file in the viewer would be too cumbersome for users. If it would, then telemetry can keep vulcanizing results.html, and the /histograms viewer would be a bit less necessary, though still necessary enough I think for the use-case of comparing the effects of a change across a broad range of metrics.

Does that sound right?

**Comment by anniesullie** [comment]
A couple things:

* My hunch is that people do still want to be able to view the file locally, but I also think we're seeing some clear use cases for having a viewer (perf dashboard, pinpoint).
* I'd prefer it to work the way you described for cloud storage (`...jsonUrl=...console.developers.google.com...`) but I'm really unclear about whether cross-domain access is possible. Not sure what we should do in this case.

@dave-2 @simonhatch WDYT about how the pinpoint use case should work? Would there be histogramset separate from JSON? If so, where would it be stored? If not, I'm assuming there's a reason to prefer everything vulcanized together?

**Comment by simonhatch** [comment]
What do you mean histogramset separate from JSON?

I'm not totally sure how Pinpoint would work. It has to pull the data from swarming via the api, not sure if there's a link available so it probably will have to upload it somewhere. Also Pinpoint does multiple runs, so someone needs to do the merging step. Could either have Pinpoint do it, or let this viewer endpoint take multiple urls and do the merging for you.

**Comment by anniesullie** [comment]
Mistyped. I edited my comment for clarity. I meant in pinpoint, would it store histogramset JSON somewhere, separate from the results.html viewer?

**Comment by simonhatch** [comment]
I would think separate, otherwise we'd need to solve vulcanizing them together in AppEngine?

**Comment by benshayden** [comment]
Sorry, I'm not sure I followed all that.

@dave-2 and I discussed serving HistogramSet json from pinpoint to the histograms viewer in #3925 . Do our comments there help?

> I'm really unclear about whether cross-domain access is possible.

The [devtools timeline viewer](https://chromedevtools.github.io/timeline-viewer/) can load any json file over [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Does that help?

**Comment by nedn** [comment]
Passing by, given so much back n forth in text communication here, I suggest making a VC with people who have concerns to get everyone on the same page.

**Comment by anniesullie** [comment]
I think the big remaining question is the one @benshayden just asked: can we use CORS to load the histogramset from the places it will be uploaded to? In #3925 @dave-2 suggests storing "the URLs or isolate hashes", which I think means he's considering just using the histogramset that's already been produced as a build artifact. Getting a sample url for such a histogramset and checking if it's possible to load via CORS with infra team would be the next step.

**Comment by simonhatch** [comment]
Sure, this overlaps heavily with Pinpoint so let's just make sure we're on the same page since I'll be trying to get something working with Dave out. Sending an invite out.

**Comment by benshayden** [comment]
The original bug in this issue [has been fixed](https://chromium-review.googlesource.com/c/chromium/tools/build/+/695806) (not sure why the bots didn't update this bug), so closing. I'll open a new bug to track the histograms viewer soon. Thanks, all!
