### ISSUE TITLE
Pinpoint - Support tracing args for request debug trace

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3918]
To support this feature, Pinpoint need to support these extra params for telemetry tests when creating a job.

command.append('--extra-chrome-categories=%s' % chrome_trace_filter_string)
command.append('--extra-atrace-categories=%s' % atrace_filter_string)

@dave-2

**Comment by anniesullie** [comment]
Long term, would also be good to allow people to specify their own telemetry arguments.

**Comment by simonhatch** [comment]
Should we just go ahead now and make this general, add some extra-telemetry-args to new.py?

**Comment by anniesullie** [comment]
I think the backend should be general, and the dialog should give users some good default choices. (At first, options for extra trace filter strings with links to docs on what those are, then more options as we see users wanting to do things and not knowing how)
