### ISSUE TITLE
Dashboard - Add default_expiration: 30s on dev versions

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3920]
Something that comes up relatively often, iterating on UI it's useful to shove default_expiration: "30s" into the app.yaml, wonder if there's a nice way to just always do this for dev versions

@dave-2

**Comment by benshayden** [comment]
cp app.yaml dev.yaml
echo 'default_expiration: "30s"' >> dev.yaml
See v2spa_dev.yaml
