### ISSUE TITLE
Perf Dashboard: Wrong count of alerts shown

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3929]
Chrome version: 62.0.3202.29 (Linux)
URL: https://chromeperf.appspot.com/group_report?sid=fce2dd5293e9c5d99778c313a08b1641eec14d60bf3fac1f697923c58a95a243

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
None
Please describe the problem:
According to the UI there are 212 alerts. According to the triage alert page there are 36. There are also 36 shown (see screenshot).

![image](https://user-images.githubusercontent.com/7190422/30966822-83d96744-a45a-11e7-8dbb-3b62aa84a957.png)

**Comment by anniesullie** [comment]
@benshayden can you take a look? I was able to reproduce by clicking on the link in the bug summary. I checked the response from the XHR to /group_report, and it's including both improvements and regressions. I believe before the grouping change we would only get regressions.

It looks like although the alerts have been triaged now (marked invalid), in the screenshot they were not triaged. So this is likely something that happens before the alerts have been triaged.

I tried to do some initial digging by copying the relevant code from [group_report.py](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/group_report.py) into the [interactive shell](https://chromeperf.appspot.com/_ah/stats/shell) (beware this uses the prod datastore, do not delete or modify with it!)

```
import json
from google.appengine.ext import ndb
from dashboard.models import page_state

hash_code = 'fce2dd5293e9c5d99778c313a08b1641eec14d60bf3fac1f697923c58a95a243'
state = ndb.Key(page_state.PageState, hash_code).get()
keys = [ndb.Key(urlsafe=k) for k in urlsafe_keys]
print len(keys)
```

This prints the correct 36! I have no idea what is happening here. This seems really similar to crbug.com/754707, where I also saw improvements in the alert JSON, and then later on @benshayden was not able to reproduce. @simonhatch any thoughts where to poke?

**Comment by natorion** [comment]
Seems like the number of alerts includes improvements although the improvements are not shown per default. See this link: https://chromeperf.appspot.com/group_report?sid=29bfeaa92c30c627bb8d2a59a4fbb5a34ad4cb8a6f59049925c9d3d385acbff3 and notice the state of the marked button on the top right. 

Looks like the default, initial state of the page is bogus?

![image](https://user-images.githubusercontent.com/7190422/30969246-1ad4f06c-a462-11e7-97c3-26b5cf27af71.png)

**Comment by simonhatch** [comment]
Yeah think the initial state isn't accurate reflected in the button in the top, improvements aren't shown by default but the button seems to imply they are. I think the alerts-table isn't aware of whether improvements should be shown or not, it does all the grouping in alerts-table.html:ShowAlertsGrouped(). The "Show All Improvements" button actually calls group-report-page.html:onToggleImprovements() which directly modifies the contents of the alerts table, which doesn't seem right.

Kinda think that onToggleImprovements should just call into alerts-table to show or hide the improvements, and let alerts-table handle the rest.

**Comment by benshayden** [comment]
Archiving
