### ISSUE TITLE
Perf Dashboard: Sorting breaks selection of alerts on group_report

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3933]
Chrome version: 62.0.3202.29 (Linux)
URL: https://chromeperf.appspot.com/group_report?sid=bd95b960d11403ebdb2787317048c729afbe6916e0b32620ef660ac93353cb18

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

jquery.flot.min.js:7 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
    at Canvas.resize (jquery.flot.min.js:7)
    at Plot.plot.resize (jquery.flot.min.js:7)
    at HTMLElement.resizeGraph (chart-slider.html:402)

Please describe the problem:
1.) Deselect all the alerts
2.) Sort by "Test"
3.) Wait
4.) Sorted but most alerts are suddenly selected again

**Comment by anniesullie** [comment]
@benshayden can you take a look?
@simonhatch FYI

**Comment by benshayden** [comment]
Looks done?
