### ISSUE TITLE
Dashboard - /add_histograms doesn't support tir_label

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3944]
Looking at /add_histograms code, realized that this doesn't support tir_label and thus won't work as-is for some benchmarks. Diving into this w/ @benshayden to try to and figure out how to support this, looks like this is generated in telemetry via https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/results/page_test_results.py#L409

We should be able to do the same thing in /add_histograms by duplicating the way the tir_label is generated off of the STORY_TAGS diagnostic.

**Comment by benshayden** [comment]
Yes, [ComputeTestPath](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/add_histograms.py#L206) needs to

- get the STORY_TAGS diagnostic,
- ignore non-key-value tags (those that do not contain a colon `:`),
- sort them,
- ignore keys with multiple values (e.g. if a Histogram has both `case:foo` and `case:bar`, then ignore both)
- `'_'.join(tag.split(':')[1] for tag in tags)`
- if that is truthy, add it to the test path between `hist.name` and `escaped_story_name`
