### ISSUE TITLE
[📍] Data migration plan

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3945]
We're starting to have some changes that will modify the NDB schema. We need to have some things in place to ensure these go smoothly:
* Migration process documentation.
* Data migration helper script or endpoint.
* Ability to update Jobs without setting the `updated` field.
* A test migration (looking like it's going to be the [trace links CL.](https://codereview.chromium.org/3014663002/))

Current thoughts on the process:
* Deploy a version that updates migrates the schema when the Job is read. This can be done by overriding `__setstate__` or `__new__` in the modified classes.
* Wait > 1 minute for running jobs to self-migrate.
  * Right now, running jobs are pinned to the version that they started on. We can pin them to the default version instead.
* Run the data migration once, on all jobs that are stopped.
* Deploy a version with the migration logic removed. Done!

**Comment by simonhatch** [comment]
I like it, much simpler than the version we had spoken about offline. This is more similar to how I'd expect the dashboard to do a migration.

Any thoughts on how to test the migration? Dashboard's migration endpoints are unit tested which gives some degree of confidence.

**Comment by dave-2** [comment]
Ran a test migration last night for #3887. Here's the data migration UI.

When there's no migration running:
![image](https://user-images.githubusercontent.com/211662/31284026-33ed1614-aa6c-11e7-8973-c6df8e753c01.png)

After clicking the button, or when there's a migration already in progress:
![image](https://user-images.githubusercontent.com/211662/31284034-39473a54-aa6c-11e7-86ac-46d711ddaa6f.png)

**Comment by dave-2** [comment]
Everything is done except the docs, so filed a followup for that (#4124)
