### ISSUE TITLE
document effect of upper case phase in trace event format

### ISSUE THREAD

**Issue by AndreasMadsen** [catapult-project/catapult#3946]
As far as I can tell, when the `ph` value is uppercase the events are grouped by the name when they are lowercase the events are grouped by the thread id.

This doesn't appear to be documented anywhere, at least not in https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview

Is this by choice? If so could you add it to the documentation?

**Comment by benshayden** [comment]
The specific grouping algorithm used by catapult's trace viewer is a View-level implementation detail that could be changed, or be different in a different trace viewer, so I'm not sure it makes sense to specify it in the Trace Event Format doc. IIUC, that doc is more about the low-level syntax and semantics of the trace format, not a complete specification of how the Model data should be visualized.

**Comment by AndreasMadsen** [comment]
Well, the issue took me a long time to solve. So I just wanted to suggest it.

At the very least, the documentation suggests that there is some correct choice of lowercase/uppercase, which I don't think are. Except that it affects the viewer.
