### ISSUE TITLE
Perf Dashboard: No v8 changelog showing anymore for v8.browsing_stories

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3947]
Chrome version: 62.0.3202.29 (Linux)
URL: https://chromeperf.appspot.com/report?sid=4b563c77f46345a2eca2856d92fbe574314836a2d25fe0cbf63db8f02688942a

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
Failed to load resource: the server responded with a status of 400 () in /getdiagnostics ... probably unrelated?
Please describe the problem:

Starting with point 503070 the data about the V8 changelog does not show up anymore. For the datapoints before this it did.

![image](https://user-images.githubusercontent.com/7190422/31177756-431c79fa-a917-11e7-994f-ede75ba8a4ec.png)

**Comment by anniesullie** [comment]
@simonhatch can you help triage? @martiniss did you help with this originally?

**Comment by simonhatch** [comment]
Looking at these points in the datastore, everything prior to Sept 20'ish has those extra revision annotations while later don't. Traced that back to the upload step from the waterfall, which is missing those params, which points at this cl: https://chromium-review.googlesource.com/c/chromium/tools/build/+/653206

It looks like the flags are created and then never passed, I'll put up a CL to fix.

**Comment by natorion** [comment]
Thanks! Is the data going to be backfilled after the fix lands?

**Comment by simonhatch** [comment]
No, the CL (https://chromium-review.googlesource.com/c/chromium/tools/build/+/700737) passes the correct revision args in during the upload step, so after it lands all subsequent uploads will get the right data.

To backfill I think there aren't a lot of great options. Short of either re-uploading all the previous runs or writing a custom script to run over those Rows, pull in DEPS/etc., figure out v8's revision, and resave. Optionally that could be done when you load the graph on a dev instance or something.

**Comment by natorion** [comment]
It is probably not worth it at that point. Thanks.

**Comment by natorion** [comment]
This is happening again, see https://chromeperf.appspot.com/report?sid=a90caad5fd61975ddbe8f89e1930493f0ee2f63e008bf57bb450cd5125b28b86

**Comment by simonhatch** [comment]
CL up: https://chromium-review.googlesource.com/c/chromium/tools/build/+/738435

**Comment by benshayden** [comment]
This looks fixed. If it happens again, please file a new monorail bug.
