### ISSUE TITLE
Add # histograms as part of benchmark smoke test

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3951]
Had a recent waterfall wide set of failures on dashboard upload due to an explosion in the # of metrics in loading.desktop. Ned has suggested adding a something in the benchmark smoke tests so that the CQ can catch this class of problems.

https://cs.chromium.org/chromium/src/tools/perf/benchmarks/benchmark_smoke_unittest.py?q=benchmark_smoke&sq=package:chromium&l=1

@nedn

**Comment by nedn** [comment]
@benshayden 

The idea here is we compute s.t like size (or the number of histogram) of the results & blow up if it's too big.
Note that the smoke test only run one story from the selected benchmark, but we can estimate the total size by multiply that by the number of stories & number of repeat from the benchmark.

**Comment by benshayden** [comment]
SGTM.
How should we modify SmokeTestGenerator to count the values? I don't see anything in the Benchmark class where it has access to the PageTestResults.

**Comment by nedn** [comment]
Modifying SmokeTestGenerator SGTM

**Comment by benshayden** [comment]
Started https://chromium-review.googlesource.com/c/chromium/src/+/704054

**Comment by chiniforooshan** [comment]
Hi, I'm getting errors like the following on CQ from a CL that should not affect telemetry in theory:

>   Traceback (most recent call last):
    File "/b/s/w/ir/third_party/catapult/telemetry/telemetry/value/failure.py", line 41, in _GetExcInfoFromMessage
      raise Exception(message)
  Exception: Too many values: 589 > 588

([failure](https://chromium-swarm.appspot.com/task?id=392ff34483822b10&refresh=10&show_raw=1))
([cl](https://chromium-review.googlesource.com/c/chromium/src/+/717034))

I'm not sure if this is a valid failure on my part and what does it mean?

**Comment by benshayden** [comment]
Thanks! I'll bump up the limit.
We could try to estimate what the limit should really be at some point.

**Comment by perezju** [comment]
Moved to: https://crbug.com/1001038
