### ISSUE TITLE
Perf Dashboard: Can't triage a lot of alerts at once on group_report page

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3961]
Chrome version: 62.0.3202.29 (Linux)
URL: https://chromeperf.appspot.com/group_report?rev=505211

Please describe the problem:

Repro:
1.) Open an impactful revision in group_report
2.) Select one of the buckets with a few hundred entries
3.) Tab hangs, kill dialog appears

I think this is due to the default behavior to automatically display all selected alerts. displaying 400 graphs is crippling the machine. When I mass-select alerts, I am not interested in the graphs but only in the alerts. How about adding a button similar to hide/show improvements that automatically displays graphs?

**Comment by anniesullie** [comment]
@simonhatch @benshayden

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917906
