### ISSUE TITLE
Perf dashboard charts should use d3

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3962]
The rest of tracing/results/etc uses d3, and its API is much more usable for the way we want to interact with the DOM. It can also be much more flexible in the way databinding works, which should mean that we can remove several hundred lines of code from chart-container.html for databinding and fixed-point x-axis, as well as make the format from graph_json.py much cleaner.

I'm taking this for now, but planning on hacking on it slowly; if anyone else gets to it faster feel free to steal.

@simonhatch @dave-2 @benshayden

**Comment by benshayden** [comment]
V2SPA uses a completely custom chart so we can build exactly the features we need in the same style and framework as the rest of the app without rolling a third party library with its own quirks.
