### ISSUE TITLE
Perf Dashboard: Cannot move from more specific to aggregate graph

### ISSUE THREAD

**Issue by mariakhomenko** [catapult-project/catapult#3963]
Chrome version: 62.0.3202.29 (Linux)
URL: https://chromeperf.appspot.com/report?sid=18011240ae6697979b36a8b2e93d401816c7be1217e34917687f7c11362f36de&start_rev=1504953559&end_rev=1507653641 (note you need to be signed in to see this)

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

chart-slider.html:402 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
    at Canvas.resize (jquery.flot.min.js:7)
    at Plot.plot.resize (jquery.flot.min.js:7)
    at HTMLElement.resizeGraph (chart-slider.html:402)
Canvas.resize @ jquery.flot.min.js:7
Plot.plot.resize @ jquery.flot.min.js:7
resizeGraph @ chart-slider.html:402
3chart-slider.html:402 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
    at Canvas.resize (jquery.flot.min.js:7)
    at Plot.plot.resize (jquery.flot.min.js:7)
    at HTMLElement.resizeGraph (chart-slider.html:402)

Please describe the problem:

Open graph for a specific test, e.g. ClankInternal/perf-clankium-l-phone/start_with_url.warm.startup_pages / foreground_tab_load_complete / about_blank

Go to the top and click X button next to the specific page selection, then click Add

Expected:
Adds a new graph that has the aggregate graph for all foreground_tab_load_complete pages

Actual:
Adds exactly the same graph again even though the last item is not populated

**Comment by anniesullie** [comment]
@benshayden @simonhatch

**Comment by benshayden** [comment]
This is done.
