### ISSUE TITLE
Perf Dashboard: Breadcrump updates are slow/not triggering

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3965]
Chrome version: 62.0.3202.45 (Linux)
URL: https://chromeperf.appspot.com/report?sid=c8e96db73e27d28cda8d41031225650b543995b6a7a660e4161613dc02a22c34&start_rev=445726&end_rev=499284

Please describe the problem:

When I want to swap out certain parameters in a benchmark in order to compare results (see the above example) e.g. switching the metrics but leave everything else the same I often have the problem that the update is not triggered. This manifests that when I use the arrow button to drag & drop a new graph onto another graph, the old graph appears twice.

I also watched other users struggle tremendously (no exaggeration) getting to the results they actually want by manipulating the breadcrump.

**Comment by anniesullie** [comment]
@benshayden @simonhatch 

I pushed a new dashboard version yesterday; @natorion any idea if it might be related to those changes (was it working fine yesterday?)

**Comment by natorion** [comment]
Sorry, no clue. I didn't look at Chromeperf intensively this week up until today.

**Comment by benshayden** [comment]
This sounds like #3963 . Can you see if [this demo](https://dev-benjhayden-fe5546b4-dot-chromeperf.appspot.com/report) works better? Here's [the CL in that demo](https://chromium-review.googlesource.com/c/catapult/+/710074).

**Comment by natorion** [comment]
I checked out the demo. Now all descendant Subtests are vanishing when I want to swap out and ascendant Subtest. It is very hard now to compare multiple metrics on the same workload because one always needs to reselect the same path.

**Comment by benshayden** [comment]
I think I've received somewhat positive feedback about v2spa's Measurement/Bot/Test case menus, but let's try to schedule a series of meetings to see what further refinements are warranted and file bugs in monorail instead of github.
