### ISSUE TITLE
Perf Dashboard: Graphs don't show despite there is data for them

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3966]
Chrome version: 62.0.3202.45 (Linux)
URL: https://chromeperf.appspot.com/report?sid=cf94a1287c526767108e905afccfb02e75c914e9d142ca817240909d8c83e20a&start_rev=422881&end_rev=499284

Please describe the problem:
Repro:
1.) Open https://chromeperf.appspot.com/report?sid=cf94a1287c526767108e905afccfb02e75c914e9d142ca817240909d8c83e20a&start_rev=422881&end_rev=499284
2.) Make revision slider smaller

3.) Suddenly one graphs stops to plot correctly
![image](https://user-images.githubusercontent.com/7190422/31435141-f5ad7a6c-ae7e-11e7-81c0-98aab1791808.png)

**Comment by anniesullie** [comment]
@simonhatch

**Comment by simonhatch** [comment]
Should be fixed now.
