### ISSUE TITLE
[📍] Show commit position in UI

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3970]
PinPoint is awesome. I like the ui, nice and polished.
Would be nice if It did show the commit position somewhere, so when I click on two points I can tell how far apart are from each other (in terms of CLs)

**Comment by dave-2** [comment]
Is it enough to show the relative positions on the chart? (#3869)
Or would you still like to see the actual commit positions?

**Comment by anniesullie** [comment]
As somebody that does a LOT of perf sheriff triaging, I would really like to see the actual commit positions. I need to copy/paste sometimes.

**Comment by dave-2** [comment]
👍
