### ISSUE TITLE
Improve network idle heuristic

### ISSUE THREAD

**Issue by maxlgu** [catapult-project/catapult#3974]
The latest impl is in catapult-csm: 
https://github.com/catapult-project/catapult-csm/blob/breakdownMapper/tracing/tracing/metrics/system_health/time_to_interactive.html#L131

Detecting network quietness design doc:
https://docs.google.com/document/d/1y6NYcI2NyLMh88KVr2NaevdX2e-e03vL99Wn-gy_hVk/edit

Edge case example:
https://github.com/GoogleChrome/lighthouse/issues/2447

Goals:
1. Publish doc on evaluation procedure.
2. Evaluate 3 candidates.
3. Land successful candidate in catapult

**Comment by maxlgu** [comment]
@tdresser @deepanjanroy

**Comment by deepanjanroy** [comment]
We're considering it done with the [TTI v1.0 doc](https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit).
