### ISSUE TITLE
Getting "No data available. Note that some data is only available when logged in." on dashboard

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3977]
I'm trying to pull up some graphs on the dashboard, but every graph that I try to pull up (at least for system_health.common_mobile on N5X) seems to be giving me this error, including benchmark_duration. However, I checked the last run of the Nexus 5X perf bots and several of the metrics that I checked reported data in the last run.

Any idea what's up?

/cc @simonhatch

**Comment by anniesullie** [comment]
Original URL: https://chromeperf.appspot.com/report?sid=347d58b6d51aa40ae0f6b0b674df919b6a09fcb3096aa46407e99d4aa3dc43d2&start_rev=1507884746&end_rev=1508168670

start_rev and end_rev are timestamps

**Comment by anniesullie** [comment]
Works without those params:  https://chromeperf.appspot.com/report?sid=347d58b6d51aa40ae0f6b0b674df919b6a09fcb3096aa46407e99d4aa3dc43d2

**Comment by simonhatch** [comment]
hehe

We could probably say something about the revision range being invalid?

**Comment by zeptonaut** [comment]
Agreed that an error about not being a valid revision range would be helpful. I got those start_rev and end_rev parameters from @benhenry, who in turn got them from @perezju's Android System Health Plan dashboard. So it looks like we should let @perezju know that the dashboard is setting invalid start_rev and end_rev parameters.

**Comment by zeptonaut** [comment]
Closing this issue, as the dashboard sky isn't actually falling.

**Comment by perezju** [comment]
Can you point to where the broken links are being provided on the health dashboard?

**Comment by anniesullie** [comment]
It's not clear what dashboard link was clicked, but what happened is that Charlie took a health dashboard link and tried to show some chromium.perf bots at the same revision. Since clank bots use time ranges and chromium.perf bots use commit positions, all the graphs showed "no data" which was alarming because we know the data is being uploaded.

**Comment by perezju** [comment]
Ok, got it. Yeah. Hopefully in histograms world these kinds of issues would be solved? Or will upstream bots still use commit positions for point ids?

**Comment by anniesullie** [comment]
Unfortunately histograms don't change the way the data is keyed, so they can't help much with this problem :(
