### ISSUE TITLE
Histogram Pipeline - Support ref builds

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3978]
Quick look through the code prior to uploading dummy benchmarks suggest they're not.

@benshayden

**Comment by simonhatch** [comment]
So this is calculated right now in : https://cs.chromium.org/chromium/build/scripts/slave/upload_perf_dashboard_results.py?q=upload_perf&sq=package:chromium&l=39

Basically checks if the name has 'reference' in it. We have a couple choices, do the exact same thing in upload_perf_dashboard_results.py and append a diagnostic, or do the same name check /add_histograms

I'm not really clear if there's much advantage one way or the other, thoughts?

**Comment by benshayden** [comment]
Eventually, we should be able to serve sane Histograms from the dashboard database to the report page or a histograms viewer or the API to e.g. colab. These Histograms' `benchmarks` should look like benchmark names in telemetry and the test-picker and everywhere else, so they can't contain `.reference`. So, _GetDashboardHistogramData should do the same thing as _GetDashboardJson, so we need to reserve a new diagnostic name. `isReferenceBuild`?

**Comment by simonhatch** [comment]
Think that means we need add_shared_diagnostic to actually replace the benchmark names then?

**Comment by benshayden** [comment]
[It already does](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/value/histogram_set.py#L35) a setitem operation.
But also, _GetDashboardHistogramData should remove the `.reference` so that the benchmark name matches telemetry's benchmark name so that it doesn't matter whether add_shared_diagnostic sets the diagnostic or adds to it.

**Comment by simonhatch** [comment]
Believe this is all fixed, closing.
