### ISSUE TITLE
Redesign Dashboard main page

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3979]
The chromeperf dashboard main page currently contains two tables of recent large anomalies: one for improvements and one for regressions.
It sounds like not many people use this page for its intended purpose, certainly not enough for it to be the main page, so let's remove these anomaly tables.

Should the report page move onto the main page?
Should the main page just contain a few links to /report, /alerts, etc with some explainer text?

@simonhatch @anniesullie

**Comment by benshayden** [comment]
@dave-2

**Comment by tdresser** [comment]
An option for the main page:

What if we used the main page to highlight a few key metrics on some sample benchmarks?
A super rough "How are we doing on key lab tests" dashboard?

**Comment by anniesullie** [comment]
I like @tdresser's idea. We could likely re-use Jessi's work on the system health dashboard for this.

**Comment by benshayden** [comment]
[/speed_releasing](https://chromeperf.appspot.com/speed_releasing) links to a few different speed-releasing-page reports. Each speed-releasing-page contains a speed-releasing-table (containing 1 to a few tables of numbers) plus an alerts-table. The speed-releasing-tables contain links to charts.

So, the main page could contain either a speed-releasing page or a speed-releasing-table: should there be an alerts-table on the main page?

Do those tables contain too much detail for the main page? Maybe 1 row for overall chrome memory usage, power, TTFMP, anything else?

**Comment by tdresser** [comment]
I don't think we need an alerts table.

Perhaps something like TTFCP, power and memory would be reasonable for now?
We should add TTI & EQT fairly soon.

@ulan - we never requested monitoring on the EQT metrics, did we? Do you want to, or shall I?

**Comment by ulan** [comment]
@tdresser filed crbug.com/776090 for EQT.
