### ISSUE TITLE
Merge test-picker + chart-title = chart-picker

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3980]
Currently, report-page contains a test-picker and zero or more chart-containers. There are a number of problems with this structure:

- Takes a long time to scroll to the top on pages with many charts in order to add a new chart
- Soft-blocks enclosing charts in paper-cards (TODO link bug)
- Requires a weird button to "populate test picker from a chart" in order to add a new chart that is similar to an existing chart
- Requires otherwise-unnecessary duplicate UI between test-picker, chart-title, and chart-legend to display test path components.
- I'm still not sure exactly what clicking on components in chart-title does or is supposed to do, or how to undo it.

All of these problems and more would be solved by merging test-picker into chart-title.

Instead of an Add button, charts would automatically update when the user changes test-path components.

This is a complex change, so let's land it in pieces behind a flag.

@simonhatch @anniesullie @dave-2

**Comment by anniesullie** [comment]
This sounds awesome, but can we think of a better name than chart-title-2? Maybe chart-header? chart-picker?

> Instead of an Add button, charts would automatically update when the user changes test-path components.

I think we need to think through this a little more: there are multiple levels of summary metrics in most tests, so with this logic you would go through and add "total_memory", "total_memory/browse_news", "total_memory/browse_news/cnn" when all you really wanted was cnn.

**Comment by benshayden** [comment]
> there are multiple levels of summary metrics in most tests, so with this logic you would go through and add "total_memory", "total_memory/browse_news", "total_memory/browse_news/cnn" when all you really wanted was cnn.

Good question! I'm sure there are other issues that we'll find as we play with demos.

I had been thinking that it would only show the cnn timeseries, not total_memory and browse_news and cnn. When the user selects total_memory, it would load and display the total_memory summary timeseries and focus the TIR label picker (unless we can remove it in favor of story-tag-filter); when the user selects browse_news, it would stop displaying the total_memory summary and instead display the browse_news summary timeseries and focus the story picker; when the user selects cnn, it would stop displaying the browse_news summary and instead display the cnn timeseries.
Do you think it would be ok to require users to open 3 different charts if they want to see total_memory and browse_news and cnn?
The related sparklines facilitate that workflow: users can stop at total_memory for a chart, open the Subtests sparklines, click browse_news to open a new chart for that subtest, open the Subtests sparklines for the browse_news chart, and click cnn to open a third chart. The user would end up with the total_memory chart on top of the browse_news chart on top of the cnn chart: a ladder of abstraction!
I was also thinking of a "duplicate chart" button to assist that workflow separately from sparklines.

**Comment by anniesullie** [comment]
To me, the "add" button sounds a lot less complex than switching what's displayed as the user selects from submenus. @dave-2 @simonhatch WDYT?
