### ISSUE TITLE
Perf Dashboard: browse completely broken

### ISSUE THREAD

**Issue by phoglund** [catapult-project/catapult#3988]
Chrome version: 61.0.3163.100 (Linux)
URL: https://chromeperf.appspot.com/report

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
components/iron-selector/iron-multi-selectable.html Failed to load resource: the server responded with a status of 500 ()
polymer-micro.html:343 [paper-tabs::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
_logger @ polymer-micro.html:343
polymer-micro.html:343 [iron-selector::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
_logger @ polymer-micro.html:343
polymer-micro.html:343 [paper-radio-group::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
_logger @ polymer-micro.html:343
polymer-micro.html:343 [paper-menu::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
_logger @ polymer-micro.html:343
iron-menu-behavior.html:110 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at HTMLElement._resetTabindices (iron-menu-behavior.html:110)
    at HTMLElement.attached (iron-menu-behavior.html:79)
    at Array.<anonymous> (polymer-micro.html:276)
    at Object._makeReady (polymer-micro.html:119)
    at polymer-micro.html:125

Please describe the problem:
When I put the cursor in "test suite", I can see a list of targets. I can't click on any of them though, and there's no way I can see to actually select a target.

**Comment by simonhatch** [comment]
Are you still having this issue? I'm unable to reproduce, on the same version of chrome (both mac and linux).
