### ISSUE TITLE
Pinpoint - Builder doesn't build if no compile required

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4006]
if you do a non c++ code change that doesn't require a recompile of chrome, the builder doesn't build anything. Probably want to force it to always build, since other changes (eg. benchmarks, data) will fail to run as perf try jobs right now.

@dave-2

**Comment by dave-2** [comment]
https://build.chromium.org/p/tryserver.chromium.perf/builders/Linux%20Builder/builds/14

**Comment by dave-2** [comment]
Fixed in https://chromium-review.googlesource.com/c/chromium/tools/build/+/881529
