### ISSUE TITLE
Histogram Pipeline - Rollout to chromium.perf bots

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4008]
Tracking bug for this, have a spreadsheet here: https://docs.google.com/spreadsheets/d/1slGyK5VA8-K2W07CXglO1k_0SOQfhjVsw-SFQkpDu-8/

@benshayden @eakuefner

**Comment by eakuefner** [comment]
Actually, I've been using https://bugs.chromium.org/p/chromium/issues/detail?id=744736 for tracking. Will close this bug in favor of that one.
