### ISSUE TITLE
Grouping of alerts doesn't work very well

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#4012]
My team's sheriff rotation "Chromium Perf AV Sheriff" triages lots of alerts. We have noticed that the grouping of alerts doesn't work very well. Here is an example:

![grouping](https://user-images.githubusercontent.com/1326100/32292086-311ef1ec-befc-11e7-981b-0265efe88519.png)

For the top three alerts, the revision range is identical. For the first and third alert, the revision range is identical and the metrics are both memory-related, and the device is the same.

All four alerts are for the same benchmark.

I was wondering if we could do a better job grouping these alerts. I know the dashboard currently doesn't know a lot about the metrics, but for cases of identical revision ranges and identical benchmarks maybe it would be better to be more aggressive.

Also, we could consider encouraging bots to pick revisions to run at that other bots are already running at, rather than just picking the most recent revision every time. This would make it easier to group alerts later.

**Comment by anniesullie** [comment]
I know it looks silly, but I think the groups are actually WAI in this case. For the second group, the alert is on CPU. That's really different from memory, and although the cause might be the same CL, we should really wait for a bisect.

We used to group the memory alerts together, but memory is a DAG @benshayden made a change to use the breakdown it the metric provides about the DAG structure to only group ones that are likely to be related. Again, it's possible that multiple areas of memory regressed with the same CL, but we'd like a bisect to confirm that.

**Comment by CalebRouleau** [comment]
When was Ben's change? It is likely the root cause of the pain that my rotation is feeling.

I know that it's possible that we will miss regressions if we group more aggressively, but in practice the way this works now sends out so many alerts that my team gets overwhelmed. For a revision range of ~60 CLs, we're maybe just fine with one memory alert that groups everything.

**Comment by anniesullie** [comment]
I think August? I wonder if maybe the problem could be monitoring too many metrics? It seems like grouping together unrelated metrics isn't a good solution to having too many alerts.

**Comment by CalebRouleau** [comment]
Okay, I will reduce the list of patterns that we alert on. Thanks for the help!
