### ISSUE TITLE
Alert emails do not group alerts in any way

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#4013]
My team gets alert emails frequently that tell us about regressions. These emails frequently say something like "99 anomalies found..." and then list all of the alerts. It would be nice if the email would do a better job grouping the alerts and telling us a number of distinct-ish alerts. For example, the first two alerts in the email were:

A 68.0% regression.
Master:	ChromiumPerf
Bot:	chromium-rel-win8-dual
Test:	media.desktop/cpu_time_percentage_avg/video.html?src_crowd720_vp9.webm
Revision Range:	512462 - 512494
View the graph and file a bug.
+++++++++++++++++++++++++++++++
A 71.9% regression.
Master:	ChromiumPerf
Bot:	chromium-rel-win8-dual
Test:	media.desktop/cpu_time_percentage_avg/video.html?src_garden2_10s.webm
Revision Range:	512462 - 512494

These two alerts had the same metric, the same benchmark, and the same revision range. The only thing that is different is the page. It would be nice if they could be grouped together.

I have attached an email we got showing a ton of alerts.
[alerts.pdf](https://github.com/catapult-project/catapult/files/1435367/alerts.pdf)

**Comment by anniesullie** [comment]
We ended up going the opposite direction with this, just saying how many new anomalies were found, and linking to the alerts page. An increasing amount of work is being done client-side, so it's hard to keep the email and the UI in sync.

**Comment by CalebRouleau** [comment]
Thanks Annie!
