### ISSUE TITLE
Histogram Pipeline - Missing supplemental stdio_uri column

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4018]
This is generated recipe side via: https://cs.chromium.org/chromium/build/scripts/slave/results_dashboard.py?q=results_dash&sq=package:chromium&l=255

We need to do something similar for histograms.

@benshayden @eakuefner

**Comment by benshayden** [comment]
There's already a diagnostic name reserved for them: `logUrls`.
I'll send out a CL to plumb `add_reserved_diagnostics --log_urls` through results_dashboard.py, and another CL to plumb the annotation in add_histograms_queue.py.
