### ISSUE TITLE
Alert emails are sent before alerts are saved to the datastore.

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#4021]
Here's the code:
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/find_anomalies.py#L102

And the point at which things are actually saved is in add_points_queue/add_histograms_queue, after futures.wait_all().

The reason this is a problem is that we should be linking the group_report page for the alert, but because it has not been put() yet, it has no key, so we fall back to linking /report:
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/email_template.py#L255

And then people who get the emails don't go through the triage flow, and they complain about the alternate triage flow not working right.

@simonhatch: any thoughts on the right fix? Some ideas:
* Just call email_sheriff.EmailSheriff() after futures.wait_all() in add_point_queue and add_histograms_queue. This is ugly because it will make them take longer (currently being run in parallel with the put() calls) and repeat the code in two places.
* Create a taskqueue task that takes the testpath and revision the alert was on and sends the email a few minutes later, assuming the put() will happen. Not sure how we feel about adding extra task queues like this? I can imagine it increasing frontend costs but I don't know.
* Send the email on a _post_put_hook for alert: we've been trying to avoid the datastore hooks.

**Comment by simonhatch** [comment]
Aren't the alerts put()'d here:

https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/find_anomalies.py#L108

Immediately following the email loop? Can't we just swap the order?

**Comment by anniesullie** [comment]
Woo-hoo! That does work!

Random sample mail sent after new deploy confirms: https://groups.google.com/a/google.com/forum/#!topic/v8-perf-alerts/6WcJPZiqaYw links to https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgl_f6sgsM
