### ISSUE TITLE
Alerts appearing for old data no longer matched by Sheriff rotation patterns

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#4026]
I turned off alerting for "reported_by_os" memory metrics for "Chromium AV Perf Sheriff" last week, but then this week we got an alert on it that was really old: https://bugs.chromium.org/p/chromium/issues/detail?id=782006#c18

We are also getting alerts for newer data that don't match our patterns as well: https://chromeperf.appspot.com/report?sid=c1dc0bea702816a9712d4d089e3786a41936ce4c03d65cf936337e9f5abd30da&rev=513820

**Comment by anniesullie** [comment]
@simonhatch can you take a look?

**Comment by simonhatch** [comment]
So none of the alerts associated with that bug are new, they seemed to have been created a long time ago (June/July) according to timestamps. I still have no theories on why they're showing up.

As for alerts on newer data that don't match your patterns. A few months back in an effort to track that down, I added a bunch of extra logging around sheriff switches, think I spotted this happening:

`2017-11-04 16:04:24.722 EDT
Sheriff Modified (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:301)
2017-11-04 16:04:24.722 EDT
 Test: ChromiumPerf/android-nexus5/media.mobile/memory:chrome:all_processes:reported_by_os:system_memory:java_heap:proportional_resident_size_avg/video.html?src_tulip2.vp9.webm_ref (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:302)
2017-11-04 16:04:24.723 EDT
 Old Sheriff: Key('Sheriff', 'Chromium Perf AV Sheriff') (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:303)
2017-11-04 16:04:24.723 EDT
 New Sheriff: None (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:304)
2017-11-04 16:04:25.165 EDT
Sheriff Modified (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:301)
2017-11-04 16:04:25.165 EDT
 Test: ChromiumPerf/android-nexus5/media.mobile/memory:chrome:all_processes:reported_by_os:system_memory:java_heap:proportional_resident_size_avg/video.html?src_crowd1080_vp9.webm_seek_ref (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:302)
2017-11-04 16:04:25.166 EDT
 Old Sheriff: Key('Sheriff', 'Chromium Perf AV Sheriff') (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:303)
2017-11-04 16:04:25.166 EDT
 New Sheriff: None (/base/data/home/apps/s~chromeperf/clean-sullivan-3a6a54cf.405268194291399074/dashboard/models/graph_data.py:304)`

So it looks like the test still thought it had a sheriff assigned at the time find_anomalies() was called. Near the end of that call, find_anomalies() put()'s the TestMetadata entity back into datastore, the _pre_put_hook runs and updates the sheriff for the test. Here it sees there's actually no sheriff, and updates the TestMetadata accordingly (so no new alerts should be expected).

I can't actually find a record in chrome-performance-monitoring-alerts of you removing the reported_by_os metrics, so I'd guess that the call failed, possibly timing out (ran into this issue recently #4027). The sheriff patterns get updated, but the actual TestMetadata entities never end up getting resaved until an alert fires.

**Comment by simonhatch** [comment]
@CalebRouleau any idea when you removed reported_by_os metrics?

**Comment by CalebRouleau** [comment]
November 3, between 10:20am and 5:38pm (I looked at some emails I wrote around that time)

**Comment by CalebRouleau** [comment]
If you go to https://chromeperf.appspot.com/edit_sheriffs, select "Chromium Perf AV Sheriff" and "List monitored tests" you get reported_by_os metrics in the list even though the patterns don't match them.

How can I fix this in the short term? Could I re-add them and then remove them again?

**Comment by CalebRouleau** [comment]
Any update on this? This continues to be a problem for our rotation. We are also anxious that some of the metrics I added might not be alerted on so we could be missing regressions.

**Comment by CalebRouleau** [comment]
Any update on this? Is there a workaround?

**Comment by CalebRouleau** [comment]
Simon is OOO. Assigning back to Annie.

**Comment by CalebRouleau** [comment]
I re-added 
ChromiumPerf/android-nexus5/media.mobile/memory:chrome:all_processes:reported_by_os:system_memory:java_heap:proportional_resident_size_avg/video.html?src_crowd.ogg_type_audio

and then I removed it again, and now it's gone. I'm going to do this for all of them.

**Comment by anniesullie** [comment]
Wait, I'm actually taking a look at this now, have a better way to do it, please hold off for a few hours

**Comment by CalebRouleau** [comment]
Ah whoops. I already did it for all the reported_by_os memory metrics... But I think there are still many inconsistencies still, so all help is appreciated.

**Comment by anniesullie** [comment]
@simonhatch: I tried to patch this up manually with code in the appstats shell that looks like this:

```
from dashboard import list_tests
from google.appengine.ext import ndb


tests = list_tests.GetTestsMatchingPattern(PATTERN, list_entities=True)

ndb.put_multi(tests)
```

This worked for all the patterns except `ChromiumPerf/*/media.*/time_to_*_play_avg/*`. The pattern times out trying to list all the tests, so I can't re-put them.

Was hoping to get to a second part, query all the TestMetadata entities with sheriff=='Chromium Perf AV Sheriff' and put() them as well, to make sure that we don't have stray alerts, but didn't have time today.

**Comment by CalebRouleau** [comment]
You could try doing 

ChromiumPerf/*/media.desktop/time_to_*_play_avg/*
ChromiumPerf/*/media.mobile/time_to_*_play_avg/*

separately to avoid the timeout.

**Comment by simonhatch** [comment]
Sorry, was OOO, I'll pick this back up. As I mentioned last week, managed to finally track this down to what I think is the root cause, failing edit_sheriff calls. The solution is like Annie attempted to do, to re-put() everything. We'll need to fix the edit_sheriffs endpoint as well, but I can kick off a task that re-puts() everything.

**Comment by CalebRouleau** [comment]
Any update on this? Was it fixed? How can I tell if it is working properly?

**Comment by simonhatch** [comment]
Not yet no, trying to get to this week.

**Comment by CalebRouleau** [comment]
We continue getting alerts for reported_by_os memory metrics, all of which have been turned off.

Also concerned that we could be missing alerts for other metrics. No way to tell if this is the case.

This bug was filed 20 days ago, and our sheriff rotation is still negatively affected by it. This is a piece of basic functionality without which our test cases are not useful.

**Comment by simonhatch** [comment]
CL is up here: https://chromium-review.googlesource.com/c/catapult/+/788451

Last week a lot of people were out for Thanksgiving. Once this CL lands, we just need to bolt on a put() to each TestMetadata (I can add that to /deprecate_tests) and do one pass on all tests to correct them.

**Comment by simonhatch** [comment]
Ok all tests were resaved over the weekend using this CL: https://chromium-review.googlesource.com/c/catapult/+/797437

Checked logs and there were a *lot* of tests resaved where the sheriff was set incorrectly, so let's see if this fixes the issue.

**Comment by CalebRouleau** [comment]
Thanks for working on this issue!

My sheriff rotation this week has been strangely quiet. I'm wondering if all our alerts are actually turned on. I haven't gotten any media.desktop or media.android alerts. Only media_perftests alerts are happening.

**Comment by simonhatch** [comment]
Np. Hopefully it's just a quiet week. I just checked the Chrome Perf AV Sheriff alerts list, seems to be pretty sparse, but here's one from Tues:
https://chromeperf.appspot.com/group_report?bug_id=792544

And there were improvements recently as well:
https://chromeperf.appspot.com/report?sid=bffef43948cac7a0e42d5783c88ef6b67f14a46a7141583d3b85764142b5fa08&rev=521605

**Comment by simonhatch** [comment]
We figured this out a while back, the TestMetadata entities got out of sync with the sheriff configs, swept through and fixed them all.
