### ISSUE TITLE
Dashboard - Adding sheriff test paths frequently times out

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4027]
Trying to add the test paths for crbug.com/781752

This endpoint was optimized recently and we still get timeouts, most often trying to add a complex test path to a benchmark with a lot of metrics.

Example: ChromiumPerf/*/v8.browsing_desktop/memory:chrome:renderer_processes:reported_by_chrome:v8:*/*/*

Always hits the 60s max. In the short term we can punt this to the taskqueue, but might want to look at #3581 soon.

@anniesullie

**Comment by simonhatch** [comment]
So I ended up trying to defer the task, and OOM'd instead, so to add those test paths I had to break this up and defer each query as well. Not sure if this is the right answer, although I'm not sure how to simplify that test path either.

@anniesullie  @eakuefner for thoughts here.

**Comment by eakuefner** [comment]
My first thought is, what if we allowed sheriff configs to be specified using histogram relationships instead? You could get the related name map easily and use that to find the children without any wildcarding.

**Comment by eakuefner** [comment]
Actually, the idea described in @nedn's pasted comment on #3581 is in a similar vein. There, we want to sheriff according to story tags, and so you'd get the TagMap and then use that to insert story parts of test paths. So it's clear that there's room for more than one diagnostic to be useful in making alert generation more efficient.

**Comment by simonhatch** [comment]
Closing this out since the original issue is fixed
