### ISSUE TITLE
Perf Dashboard: Nudging long distances takes forever

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4034]
My current workflow for nudging long distances is:

1. Nudge +-5.
2. Refresh the page.
3. Goto #1.

Sometimes I need to do this >5 times to get the alert into the right place.

**Comment by anniesullie** [comment]
@simonhatch @benshayden

**Comment by benshayden** [comment]
I think we've talked in the past about allowing users to create new Alerts. Would it be easier to Ignore the Alert and create a new one in the right place instead of nudging it a long distance?

**Comment by tdresser** [comment]
If implementation overhead was 0, I'd say my preferred thing would be a "drag" option, somewhere around the nudge UI.

Letting users create new alerts sounds worth doing either way though, and would also address this reasonably.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=892929
