### ISSUE TITLE
AttributeError: 'DiagnosticRef' object has no attribute 'Inline'

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4042]
This was triggered by turning on loading.* and we're currently investigating. @anniesullie has some log lines to paste. @simonhatch

**Comment by eakuefner** [comment]
Here's a trace from one of the uploads https://00e9e64bac41c0d46c2b3b2513736ea2e63174187a1673063f-apidata.googleusercontent.com/download/storage/v1/b/chrome-telemetry-output/o/Vietnamnet_2017-11-16_00-57-46_92357.html?qk=AD5uMEtH13C17g62U7-dQTeIo4t3NYNLQ7oW9edcmkZpytx0nCZjIMmPMPBfq_Pfrnzy1K7mDyJwnIFDVgs018SdrCpbHq2ZoXkZwmQJJa5pl62gNftgp6b8Fzo_bkf1ChqIdqI1fQBiv7IW2YVuu5O2l7KTHiOvcpCGRciNmkxVODQ_Ln1eqskQ3T4SzO0uibvqaid26n2F4wDaUU4ro4UUBY7YbcU12ypfE1UZmANM0WUXK-b-uIyoifZlYIyEHs04grtEKaKjARnwJxTg0LYr-Cx9_ueIMBVLl1CUiJIrRZD_yGRaS51AmqoJl4mNsQxprNS0D9zoMce9j33OdBL-9DoPCBWpQ7WFAzyuwIsi5siYpLVefbjvd-rl8W5cKcPEAWtIn8XssTODuQSFPWqy8jrHRfkSZhxP2-muEgR_uw2hklb8yRP9Qx5VUXbyhRBuW7KresvuvJIbNjCCBR_NRUK1nktHGDtEjhyNq0VJhX0Ui92kNG_dt7oWy1YC7QgHjvLoMkI04JAxkdz3Vvg6ukLLp7uji3Use2ev88OCknyyRvUifs8smTQTvJIiKnJgD16b_-WFbGSbe6wgifRFRjskYq-TCRIzhvjUhQ-BZZLafLJsxBGjl5GHmgWpQdpR8Tva9ST5H0VQ3Wp_UkK0OI8Aqbn02-eughJFmUiMjQpQKtQrObQ997ob6NPR5eKMS4604g7IFRCP8NXbgj8C_A9obBRkPxvyCEQt8lGLHKmNPxgl2bgUfMHVTN7ELtwxiLi_yImi9bpL00vmAcXDP5rT1Q6Sew

Metadata shows that it came from one of the Mac bots. May just try to grab a logged json from a failed run and run it through a unit test.

**Comment by eakuefner** [comment]
From a bit more digging, turns out this is Mac Retina. Here's the first failing build: https://build.chromium.org/p/chromium.perf/builders/Mac%20Retina%20Perf/builds/1407

though this particular trace is from the second failing build.

**Comment by anniesullie** [comment]
Might not need it, but here's some info about how to use the metadata to track this down:

```
cpu-brand: " Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz"
os-name: "Mac OS X",
os-version: "10.11.6",
physical-memory: 16384,
product-version: "Chrome/64.0.3271.0",
revision: "d4191bbf4caa1a3134f65c292909be9b3a1fa35a-refs/heads/master@{#517006}",
trace-capture-datetime: "2017-11-16 9:2:19",
benchmarks: ["loading.desktop"],
```

So:
* The benchmark is loading.desktop
* It ran on a Mac 10.11 bot with 16GB RAM and an Intel Graphics card
* It ran at revision 517006.
* If Chrome version is 64, that's way ahead of the ref build, so despite the error being about 'DiagnosticRef' it's likely not a ref build.

**Comment by anniesullie** [comment]
Here's the HistogramSet from the second failing build on Mac Retina: https://logs.chromium.org/v/?s=chrome%2Fbb%2Fchromium.perf%2FMac_Retina_Perf%2F1408%2F%2B%2Frecipes%2Fsteps%2Floading.desktop_Dashboard_Upload%2F0%2Flogs%2Fjson.output%2F0

**Comment by eakuefner** [comment]
```
AttributeError: 'DiagnosticRef' object has no attribute 'Inline'
at InlineDenseSharedDiagnostics (/base/data/home/apps/s~chromeperf/clean-simonhatch-b33d83ad.405353340626386852/dashboard/add_histograms.py:301)
at ProcessHistogramSet (/base/data/home/apps/s~chromeperf/clean-simonhatch-b33d83ad.405353340626386852/dashboard/add_histograms.py:93)
at AuthorizedPost (/base/data/home/apps/s~chromeperf/clean-simonhatch-b33d83ad.405353340626386852/dashboard/add_histograms.py:76)
at _TryAuthorizePost (/base/data/home/apps/s~chromeperf/clean-simonhatch-b33d83ad.405353340626386852/dashboard/api/api_request_handler.py:49)
```

**Comment by eakuefner** [comment]
We thought the above CL would have fixed this, but we're still seeing some instances of it e.g. https://logs.chromium.org/v/?s=chrome%2Fbb%2Fchromium.perf.fyi%2FHistogram_Pipeline_Linux_Perf%2F8051%2F%2B%2Frecipes%2Fsteps%2Floading.desktop_Dashboard_Upload%2F0%2Flogs%2Fjson.output%2F0

@simonhatch is investigating.

**Comment by eakuefner** [comment]
I think we've fixed this, thanks to deduplication.
