### ISSUE TITLE
Perf Dashboard: Reliance on HTML imports breaks display in some browsers

### ISSUE THREAD

**Issue by RByers** [catapult-project/catapult#4056]
Chrome version: 64.0.3269.3 (Linux)
URL: https://chromeperf.appspot.com/

The use of HTML imports means the header shows up only on Chrome.  HTML Imports is basically a failed web platform feature and so will someday likely be removed from Chrome too.  Please either use a HTML imports polyfill or another technique.

From https://github.com/webcompat/web-bugs/issues/7572

**Comment by simonhatch** [comment]
@eakuefner 

Not super familiar with the options available here, I see the polyfill linked in the bug, what other techniques do you recommend?

**Comment by RByers** [comment]
Sorry, I'm not really an expert and don't know how what tools the site already relies on.  The simplest thing to do of course is probably to just drop in the [HTML Imports polyfill](https://github.com/webcomponents/html-imports). As long as you're not relying on non-interoperable browser features, anything is good with me ;-)

But I think the most typical approach for re-using components across pages is to rely on server or client-side templating tools.  Eg. If chromeperf aims to be entirely client-side UI then there are tools like [html-lit](https://github.com/PolymerLabs/lit-html) which can make it easier to stamp out HTML across different pages just based on sharing some JS files.

**Comment by simonhatch** [comment]
Thanks! Will take a look at these options.

**Comment by RByers** [comment]
Thank you!  Yeah I understand they're at least highly likely to be chromium-based browser users (eg. also Opera).

**Comment by simonhatch** [comment]
Doh! So webcomponents-lite.js defines the polyfill, and we import that on other pages but just missed it on the main page.

**Comment by simonhatch** [comment]
Closing this out, turned out to be a simple fix, confirmed the nav bar is showing up in Firefox and Safari. I don't have Edge to test on though.
