### ISSUE TITLE
[📍] Pinpoint - Fails to read out values from blink_perf.* and others

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#4060]
Context: I was triaging V8 perf alerts and created https://chromeperf.appspot.com/group_report?bug_id=788630/https://bugs.chromium.org/p/chromium/issues/detail?id=788630. That automatically triggered https://pinpoint-dot-chromeperf.appspot.com/job/148b392ff80000.

I don't know what the poinpoint job tried to test though, the result shows https://chromium.googlesource.com/chromium/src/+/8728d6e6928d6f53c1a3a0f58f06b55c28b97d9e with no actual values. When I click on a value I see the following error message:

Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-fd88dfbf.405549530597239895/dashboard/pinpoint/models/quest/execution.py", line 99, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-fd88dfbf.405549530597239895/dashboard/pinpoint/models/quest/read_value.py", line 198, in _Poll
    raise ReadValueError('Result values missing.')
ReadValueError: Result values missing.

![image](https://user-images.githubusercontent.com/7190422/33377711-bd3a7170-d512-11e7-8339-f768d0f8377a.png)

This looks like there is an infra problem. I suppose we can detect that already (e.g. all the values are marked as red?) and than tell the user "Infra problem, please contact blablabla" instead of "No differences found".

**Comment by simonhatch** [comment]
So looking a bit at this, pulled up the data in dev_console and tried to read out the values. It looks like Pinpoint expects the chart='AngularJS-TodoMVC', with no tir_label or story.

The histogram data shows a story diagnostic associated with the histogram, which is probably what's throwing this off: [u'http://browserbench.org/Speedometer/']

'AngularJS-TodoMVC' is a summary metric (should we even be reporting on this or the story instead?), and it looks like the value reading code in Pinpoint isn't supporting this properly. Kinda seems like if [no story is supplied](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/pinpoint/models/quest/read_value.py#L187), we should just match on histogram name? @benshayden is that right?

**Comment by simonhatch** [comment]
Should add I kicked off a pinpoint job on a non-summary metric, and it's chugging along fine: https://pinpoint-dot-chromeperf.appspot.com/job/14dbfffff80000
