### ISSUE TITLE
HistogramSet - "Total" missing speedometer2

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4069]
https://chromeperf.appspot.com/report?sid=7b4db014565130d71b24de7ed24f5437ee8d76abe7fc36028057b58fcc9e00e4

The existing linux-release bot has both Total and Speedometer, while the histogram version only has Speedometer

@eakuefner @benshayden

**Comment by eakuefner** [comment]
As discussed offline, this isn't strictly a bug as such, just a (probably desirable) difference in behavior. We'll send a PSA about the behavior change when the time is right.
