### ISSUE TITLE
Network simulation using WPR-Go

### ISSUE THREAD

**Issue by karan173** [catapult-project/catapult#4076]
Original WPR provided flags to simulate network behavior, e.g.:

> $ sudo ./replay.py --up 128KByte/s --down 4Mbit/s --delay_ms=100 archive.wpr

Is this possible using WPR-Go, how?

**Comment by anniesullie** [comment]
@xunjieli

**Comment by xunjieli** [comment]
Yes, this is still possible with WRP-Go. Network simulation is handled by tsproxy (catapult/telemetry/third_party/tsproxy/tsproxy.py). The replay.py script should invoke tsproxy. Let me know if that doesn't work.
