### ISSUE TITLE
buffer usage broken via chrome://inspect?tracing

### ISSUE THREAD

**Issue by mspang** [catapult-project/catapult#4088]
It always shows 0% and following error show in console:

inspector_tracing_controller_client.html:144 Uncaught (in promise) TypeError: this.bufferUsage_ is not a function
    at tr.b.timeout.then (inspector_tracing_controller_client.html:144)
tr.b.timeout.then @ inspector_tracing_controller_client.html:144

**Comment by simonhatch** [comment]
@benshayden

**Comment by mspang** [comment]
https://chromium-review.googlesource.com/c/catapult/+/812149
