### ISSUE TITLE
Dashboard - /add_histograms_queue populate benchmark description

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4096]
A TODO found in the code with no accompanying bug.

@eakuefner

**Comment by eakuefner** [comment]
I didn't end up working on this, but @simonhatch might. Here's the plan:

1. Add a BENCHMARK_DESCRIPTIONS reservation to reserved_names/infos
2. Add benchmark_description field to TelemetryInfo, and especially, make sure to serialize it in AsDict (using the reserved name).

At this point, metric_map_function will take care of the rest and we'll begin seeing benchmark descriptions in HistogramSets. Then, on the dashboard side, just add some code to add_histograms to pick up the description.
