### ISSUE TITLE
Perf Dashboard: Internal Server Error

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#4106]
Chrome version: 63.0.3239.84 (Linux)
URL: https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
None

Please describe the problem:
Select a set of alerts --> Triage --> New Bug --> Submit
Expected: Bug filed, bisect started, ....
Actual: "Internal Server Error" message, and by checking the bugs list, no bug is filed.

**Comment by simonhatch** [comment]
Dying in request to monorail:

```
<HttpError 503 when requesting https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues?alt=json&sendEmail=true returned "Internal Server Error"> (/base/data/home/apps/s~chromeperf/dev-simonhatch-4a18b812.406151311025836935/dashboard/services/issue_tracker_service.py:248)
```

Will file a bug there.

**Comment by fmeawad** [comment]
I was able to file bugs through the system, closing as fixed.
