### ISSUE TITLE
Pages on the perf dashboard with no data have a confusing error message

### ISSUE THREAD

**Issue by csharrison** [catapult-project/catapult#4108]
For example, navigate to
https://chromeperf.appspot.com/group_report?rev=523414 (replace the rev # with a recent rev with no alerts).

The error message is:
No data available for csharrison@chromium.org. Note that some data is only visible when signed in with a chromium.org account, which is linked to a google user.

Even though I am signed into a chromium.org account linked to a google user. The real issue is that the view has no data. This confused me and made me think there was some auth problem.

**Comment by simonhatch** [comment]
@benshayden something to think about for new UI

**Comment by benshayden** [comment]
Thanks, @csharrison ! I agree, the message could be clearer. It's tricky balancing security with friendliness. Maybe it should show a different error message depending on the user account?
For example, if you're signed in with chromium.org account:

> No data available.
> If csharrison@chromium.org is linked to a google.com account, then there is no data for this time series.
> Otherwise, some data is only available when signed in with a google.com account or a chromium.org account that is linked to a google.com account.

Or if you aren't signed in:
> No data available.
> Either there is no data, or it is only available when signed in with a google.com account or a chromium.org account that is linked to a google.com account. If you have such an account, __sign in__ to see if the data exists.

Suggestions welcome :-)

**Comment by csharrison** [comment]
Those sound fine to me, but it would be nice to have a 3rd option, if the user **is** signed in to an account linked to a google.com account. Perhaps that kind of state is not readily accessible in this UI though.

**Comment by benshayden** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=918197
