### ISSUE TITLE
[run_metric/process_traces] Diagnostics of metric results shows guids instead of values

### ISSUE THREAD

**Issue by maxlgu** [catapult-project/catapult#4113]
Trace file: https://drive.google.com/file/d/1H--z7KDumsQE6sIsmhrdqfMHMjOuO6Vt/view?usp=sharing
JSon results: https://drive.google.com/file/d/14-02l6ryDURuZtFVYWdR0Wa9ByldT4bi/view?usp=sharing

Reproduce:
1. cd catapult
2. ./tracing/bin/run_metric --filename run_metric_result --also-output-json test_trace.html loadingMetric
3. open run_metric_result.json

Notice that in the json file, the values within diagnostics are incorrect. The values should not be GUIDs.

>     "description": "time to first paint",
>     "diagnostics": {
>       "benchmarkStart": "1cc59b49-97a4-45fa-9d41-aef3299d0c9e",
>       "benchmarks": "20450a0d-49e0-4253-a843-e8103389863e",
>       "stories": "f14e5a47-5ad3-4b9f-a07d-99615250fd12",
>       "storyTags": "dff719e0-8aa4-4d8f-b13a-2602cba4ee87",
>       "storysetRepeats": "ebf72146-b626-44e5-a237-9332379fbb49",
>       "traceStart": "7275d8b7-1c23-40f8-80e1-23ac27e02f6e",
>       "traceUrls": "e0cb51ed-6eef-4ebe-a683-04e5036ae318"
>     },

**Comment by benshayden** [comment]
Why do you think the values should not be guids? That's how HistogramSet JSON works. https://github.com/catapult-project/catapult/blob/master/docs/histogram-set-json-format.md

**Comment by maxlgu** [comment]
Since it's expected, I will close the issue. Thanks!
