### ISSUE TITLE
Clicking "Existing Bug" to triage leads to 500 server error

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#4115]
Chrome version: 63.0.3239.84 (Linux)
URL: https://chromeperf.appspot.com/report?sid=2f778f049db72b3db4c85fabba6f72f5555f1952ff804c37fc9bbf4b4f4cf4bf&rev=521954

Please describe the problem:
Clicking on an alert, then on "Existing Bug"

![existing_bug](https://user-images.githubusercontent.com/16922344/33942941-722499f6-e00f-11e7-99e5-b98ce20fd2d6.png)

sometimes leads to a "500 Internal Server Error"

It reproduced for me some 3 out of 5 times I tried.

Filing on behalf of @gkraynov

**Comment by simonhatch** [comment]
Hmm, working right now for me. Logs say the problems were timeouts calling out to monorail. Wonder if we can bump up the timeout here, and also surface that error better.

**Comment by perezju** [comment]
Ohh, monorail has also been feeling somewhat slowish to me recently. Maybe something we could also file with them?

**Comment by simonhatch** [comment]
Good idea, filed: https://bugs.chromium.org/p/monorail/issues/detail?id=3297

**Comment by simonhatch** [comment]
So just to followup, suggestion from the bug is actually to bump up our default timeout value to 15s, 5s is too low and is just around the average response time.

**Comment by simonhatch** [comment]
So the timeout increase has landed, and I've deployed a new dashboard. Will leave this open for surfacing the error better in the UI.

**Comment by benshayden** [comment]
Archiving
