### ISSUE TITLE
[📍] Unable to find histogram for octane

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4116]
https://pinpoint-dot-chromeperf.appspot.com/job/14eef132040000

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-simonhatch-4865f2a6.406010213126766109/dashboard/pinpoint/models/quest/execution.py", line 99, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-simonhatch-4865f2a6.406010213126766109/dashboard/pinpoint/models/quest/read_value.py", line 209, in _Poll
    raise ReadValueError('Could not find values matching: %s' % name)
ReadValueError: Could not find values matching: histogram: Total story: Score
```

**Comment by simonhatch** [comment]
@benshayden 


```
  {
    "sampleValues": [
      31582
    ], 
    "name": "Total.Score", 
    "running": [
      1, 
      31582, 
      10.360342617026589, 
      31582, 
      31582, 
      31582, 
      0
    ], 
    "diagnostics": {
      "owners": "e3a737d8-f555-4149-9576-7321d36799c7", 
      "benchmarkStart": "e7cd8a21-38a7-4b77-b84d-bbeff1e18fe5", 
      "labels": "288658b7-9e0a-4e6f-9a3d-6f5fda135e83", 
      "osVersions": "228e6ffb-c472-416e-b508-434ab04c3b72", 
      "osNames": "81b2f390-734c-439d-968a-8e2546519020", 
      "benchmarks": "0568706d-49e6-423b-95cc-4862675a464f", 
      "memoryAmounts": "3b54b9d7-dcb3-4a37-9d13-01b5800876a5", 
      "architectures": "6aac145f-ca6e-4139-be7c-e9110e696504"
    }, 
    "allBins": [
      [
        1
      ]
    ], 
    "guid": "fad90e89-5fe1-4789-9dde-010bc133fee4", 
    "unit": "unitless_biggerIsBetter", 
    "description": "Geometric mean of the scores of each individual benchmark in the Octane benchmark collection."
  }, 
```


```
      "Total": {
        "Score": {
          "description": "Geometric mean of the scores of each individual benchmark in the Octane benchmark collection.",
          "important": true,
          "name": "Total.Score",
          "type": "scalar",
          "units": "score",
          "value": 31777
        }
      },
```

The name of the histogram seems to contain both the chart and the trace, which is unusual. The test path is Master/bot/Octane/Total/Score and the dashboard expects to be able to address it via histogram_name=Total, story=Score, which works fine for chartjson. Ideas?

**Comment by benshayden** [comment]
[chart json converter](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/value/chart_json_converter.html#L67) sets the HIstogram name from the Value.name: `"name": "Total.Score",`
Why is the value's name "Total.Score"?

**Comment by anniesullie** [comment]
Any update on this bug?

**Comment by simonhatch** [comment]
I'll look at this today.

**Comment by simonhatch** [comment]
So the 2nd bisect I posted isn't the same issue, I'll split that off and track my findings in a separate bug. This feels like a histogramset issue though, I don't Pinpoint is doing anything wrong here.

@eakuefner Any idea what to do in this case?

**Comment by eakuefner** [comment]
I'll have a fix uploaded for this shortly. This turns out to be the result of a bad interaction between some pretty ancient parts of Telemetry that we basically just have to work around at this point.

**Comment by anniesullie** [comment]
@eakuefner any update on this bug?

**Comment by simonhatch** [comment]
There was some discussion on the CL with pushback on fixing it properly by removing the hack in Telemetry. We ended up filing crbug.com/805010 for the proper telemetry-side fix, and figured we'd keep our eyes open if this was happening we'd have to implement a short-term hack in Pinpoint to find the values properly.

**Comment by eakuefner** [comment]
Yes. Some discussion between @nedn, @simonhatch, and me occurred on https://chromium-review.googlesource.com/c/chromium/src/+/879469. To summarize, @nedn prefers a more comprehensive fix that will take more time than the one-off originally proposed in my CL, and @simonhatch is okay with blocking bisection on tests like this (of which we believe there are relatively few remaining in tools/perf) on this better fix. That work is tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=805010. Here are the steps I suggested on the bug:

1. Grep for all the existing "AddValue" and "AddSummaryValue" callsites in tools/perf that have a dot in the value name.
2. Notify perf sheriffs/benchmark owners that the tests will be moving one level up on the dashboard, or migrate test paths for the old, two-level hierarchy (Simon, is this feasible)?
3. Remove that hack once and for all in Telemetry.

**Comment by eakuefner** [comment]
(Oops, just saw that Simon basically said the same thing.)

**Comment by anniesullie** [comment]
Any update here?

**Comment by simonhatch** [comment]
This is blocked on crbug.com/805010

If we're seeing jobs fail we should bump the priority on that, and temporarily put in a hack in Pinpoint to account for the naming problems.

**Comment by anniesullie** [comment]
Yeah, that would be great!

**Comment by anniesullie** [comment]
Any progress on that?

**Comment by simonhatch** [comment]
No progress on this, hasn't been prioritized.

@dave-2 , any idea if we're seeing a lot of failures because of this?

@eakuefner , when we turn on histograms, some test paths will change due to that naming hack not existing for histograms. Any idea if this will "just work" once we switch to histograms?

**Comment by dave-2** [comment]
This failure is very rare. It only affects one metric afaik.

**Comment by eakuefner** [comment]
Yes, this will work properly as a matter of course for histogram uploads. And, of course, at that time, we will also remove the logic that arranges test paths in this way when chart JSON is removed.
