### ISSUE TITLE
apk_helper.py fails to parse manifest if namespaces are stripped

### ISSUE THREAD

**Issue by m0hamed** [catapult-project/catapult#4133]
XML namespaces are not used at runtime and thus are not required in the final
apk. Currently the manifest parser bugs out if there is no namespace on the
first line in the manfiest file aapt dump output.

**Comment by simonhatch** [comment]
Not sure how to triage this, @nedn are you familiar with this

**Comment by nedn** [comment]
@jbudorick

**Comment by jbudorick** [comment]
Review in progress is https://chromium-review.googlesource.com/c/catapult/+/837940
