### ISSUE TITLE
Dashboard - /add_histograms doesn't create test paths with _avg

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4139]
Here's an example:

https://chromeperf.appspot.com/report?sid=5adc88409df3438e51f4e2aec2c7cab1219121b033132ebed00935eedbf9f531

dump_count vs dump_count_avg

Found while looking w/ @benshayden 

@eakuefner

**Comment by eakuefner** [comment]
This is expected, so probably just something to make a note of in the #4140 doc.

**Comment by simonhatch** [comment]
This is a pretty major change, can just call it out in the doc but I'd expect we need to actually handle it, either by migrating test paths, etc.

**Comment by eakuefner** [comment]
Reopened, there are actually several things to address here as discussed offline with @benshayden:

1. This will break existing reports -- what do we do about that?
2. We want to build a statistic picker to support augmented rows -- how do we fit this in with legacy data?
3. Building on the point above, should we migrate legacy data to fit the new format (un-suffixed test path with d_ annotations on the Row)? If not, where do we provide support for this on the backend and/or frontend?

**Comment by simonhatch** [comment]
Wrote some quick thoughts here: https://docs.google.com/document/d/1PAMvFc0JOOQqiUqfQy2J1U9MaNUtSLMZtWxLm-_f6QU/edit#
