### ISSUE TITLE
[📍] List available configurations in try job dialog.

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4144]
The [perf try bot doc](https://chromium.googlesource.com/chromium/src/+/master/docs/speed/perf_trybots.md) says to use `run_benchmark try --help` to list the available configurations. Since that will be deprecated, Pinpoint will need to have a dropdown with the configurations in the try job dialog.

We can have a `/api/config` endpoint to look up these kinds of things, and the dialog will do an AJAX call to fetch them.

We will also want the backend to automatically look up what `--browser` flag to use, rather than making the user enter it.

@simonhatch @anniesullie

**Comment by simonhatch** [comment]
Dashboard uses https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/start_try_job.py#L533 if you want to reuse/copy that.

**Comment by perezju** [comment]
adding @nedn and also see [chromium:788442](https://bugs.chromium.org/p/chromium/issues/detail?id=788442) where we're having some discussions on how to eventually revamp the browser selection mechanism for telemetry.

Also, in general, we wanted to move away from having to "guess" the correct browser type for each given bot, and instead have this be explicit somewhere (a bot to browser map stored somewhere, sgtm, but maybe this could be stores somewhere so both pinpoint and perf bots can reuse it?)
