### ISSUE TITLE
[📍] Can't seem to easily get a copy of the traceback on error

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#4155]
The following job seemed to end in an error: https://pinpoint-dot-chromeperf.appspot.com/job/12e373fb040000

I'm not sure if this is a pinpoint error or a Chrome one.

I can hover over the `error` icon to see a traceback but I can't figure out how to copy that trace back to debug further.

**Comment by dave-2** [comment]
It's now right up top!
