### ISSUE TITLE
Pinpoint - Old bisect docs should be updated or deleted

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4159]
There are docs like:

https://cs.chromium.org/chromium/src/docs/speed/perf_trybots.md?sq=package:chromium
https://cs.chromium.org/chromium/src/docs/speed/bisects.md?sq=package:chromium

@dave-2

**Comment by simonhatch** [comment]
@anniesullie also mentioned we should get this up to date:

https://chromium.googlesource.com/chromium/src/+/master/docs/speed/addressing_performance_regressions.md#Understanding-the-bisect-results

**Comment by anniesullie** [comment]
Thanks!

Here's an example of docs I'm putting on bugs for users: https://bugs.chromium.org/p/chromium/issues/detail?id=792938#c4, would be great to have a link instead.
