### ISSUE TITLE
[📍] Pinpoint bug updates point to outdated documentation

### ISSUE THREAD

**Issue by ajklein** [catapult-project/catapult#4162]
I'm trying to help debug https://crbug.com/801556. In that bug, there are posts from Pinpoint blaming a particular change. These updates also include the text "Understanding performance regressions: http://g.co/ChromePerformanceRegressions". But that page does not mention "pinpoint" anywhere; instead, it has an old bisect bot update as an example, and the rest of the documentation on that page references the example. For example, it's not at all clear to me, from the bug, what steps I need to reproduce the test locally, and the documentation doesn't help (since I don't have a bisect result with the "steps to produce this locally" info at the bottom.

Clicking on the individual [Pinpoint pages](https://pinpoint-dot-chromeperf.appspot.com/job/14e557ef040000) doesn't seem to show any repro steps either. And "Analyze benchmark results" gives me a 403.

**Comment by simonhatch** [comment]
Thanks, yeah these refer to the old system, we'll get these updated shortly. If you're having any issues in the meantime, feel free to reach out to me or Dave.

@dave-2

**Comment by anniesullie** [comment]
Just got another request to get instructions to run locally. @dave-2 @simonhatch can we get the documentation updated?

**Comment by dave-2** [comment]
Docs are updated to include Pinpoint. Thanks for the report!
