### ISSUE TITLE
Pinpoint reopens closed bugs

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#4171]
Sometimes a bisect comes back after a bug has already been closed, and this is really annoying for users working on the performance bugs (see crbug.com/797035). Pinpoint should only change the status to `Assigned` for bugs with state `open`.

@dave-2 @simonhatch

**Comment by camillobruni** [comment]
I just experienced a similar issue on an [issue](https://crbug.com/830500) which was marked as Duplicate and PinPoint moved it to Assigned again.

**Comment by anniesullie** [comment]
Thanks for the ping! Taking this while @dave-2 is OOO.

**Comment by anniesullie** [comment]
CL landed! Reassigning to @simonhatch to push a new version of pinpoint.

**Comment by simonhatch** [comment]
Done, thanks for doing this so quickly!
