### ISSUE TITLE
Pinpoint - Fails reading hist.running.mean

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4182]
See: https://pinpoint-dot-chromeperf.appspot.com/job/14ac7050840000
From crbug.com/802398

@dave-2

**Comment by simonhatch** [comment]
Also crbug.com/802405

**Comment by dave-2** [comment]
Looks like they are all on loading.desktop.

https://pinpoint-dot-chromeperf.appspot.com/job/14d09d42840000

https://pinpoint-dot-chromeperf.appspot.com/job/12ce8b92840000
https://pinpoint-dot-chromeperf.appspot.com/job/1052047c840000
https://pinpoint-dot-chromeperf.appspot.com/job/14bf89dc840000

**Comment by dave-2** [comment]
https://pinpoint-dot-chromeperf.appspot.com/job/11adf212840000

**Comment by simonhatch** [comment]
So looking at one of them, it looks like there were no sample values on the histogram:

https://chromium-swarm.appspot.com/task?id=3b4af11820390d10&refresh=10&show_raw=1
https://isolateserver.appspot.com/browse?digest=932553a6414236463ea1a002f2d7683629c9aca0

```
{'_exception': None, '_tir_label': u'warm', '_trace_urls': [], '_result_arguments': {}, '_statistic': u'avg', '_isolate_hash': u'932553a6414236463ea1a002f2d7683629c9aca0', '_completed': False, '_hist_name': u'timeToFirstContentfulPaint', '_story': u'PremierLeague', '_result_values': ()}


matching: [<tracing.value.histogram.Histogram object at 0xf08cecb0>]
{
  "name": "timeToFirstContentfulPaint", 
  "binBoundaries": [
    0, 
    [
      0, 
      1000, 
      20
    ], 
    [
      0, 
      3000, 
      20
    ], 
    [
      1, 
      20000, 
      20
    ]
  ], 
  "diagnostics": {
    "traceUrls": "9a764261-b3c0-4d5c-9278-4cf20c3852fa", 
    "owners": "2704fdfa-ea09-4014-8dcb-2155650c5c34", 
    "traceStart": "a79c10d1-e4fe-4927-bd13-d656370f704c", 
    "storyTags": "cc8742db-62a6-4321-b167-4db270591894", 
    "benchmarkStart": "6f0281db-b8c5-44c9-b9ea-36ff59a14063", 
    "labels": "7b79dc0d-8942-496b-9e34-7fb39fbffa17", 
    "osVersions": "d7f49f46-e1eb-4ad3-a840-ff156062aee8", 
    "tagmap": "0dae6ea1-435c-448a-92ba-09f5c1dabcbe", 
    "architectures": "29d308f2-beb6-407a-869e-488f0fd23086", 
    "benchmarks": "d0ad18f0-3996-4289-a385-d69fc3f8c887", 
    "memoryAmounts": "55bf3691-bce7-4dec-8531-fa47563db905", 
    "storysetRepeats": "6283861d-b915-4e59-a616-f3661f7d0f27", 
    "stories": "c8c11ead-42ee-4e13-8e9e-123aa8303645", 
    "osNames": "7cae64d7-0e8f-4223-abe0-99e695e16ad9"
  }, 
  "guid": "7812965b-cd36-46d4-bd21-741e375ddc86", 
  "summaryOptions": {
    "count": false, 
    "sum": false
  }, 
  "unit": "ms_smallerIsBetter", 
  "description": "time to first contentful paint"
}
```

So "running" isn't instantiated.

@eakuefner @benshayden any reason you can think of why the histogram would be there, seemingly with all the right info except no values?

**Comment by simonhatch** [comment]
If that's the case, then sounds like there was a problem with the run. Although there are no errors in the log.

From Pinpoint's perspective, kinda seems then like we should check if there are samples, and if not return and throw an error?

**Comment by benshayden** [comment]
Whether an empty histogram is a problem is up to the metric. If the metric author wants the benchmark run to fail, then they can make the metric throw an error. It might be worth checking with tdresser's team for help on how to interpret empty histograms and whether they want the benchmark run to fail instead of produce an empty histogram, or maybe add a GenericSet diagnostic containing a warning message.

**Comment by dave-2** [comment]
So as far as Pinpoint is concerned, we should detect empty histograms and return no values, I guess

**Comment by dave-2** [comment]
https://pinpoint-dot-chromeperf.appspot.com/job/15fcd72a840000

**Comment by simonhatch** [comment]
Fix is a few commits after that deployment
