### ISSUE TITLE
Pinpoint - many duplicate traces

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4185]
I didn't see a way to request traces from the pinpoint UI.
This would be pretty useful, either on a per point basis, or perhaps even for a set of points?

**Comment by simonhatch** [comment]
Aren't they surfaced on every point on the graph?

**Comment by tdresser** [comment]
I don't see anything linking to a trace in the pinpoint UI.

Also, I would like to be able to request with more categories (ideally it would be easy to get a trace with all the disabled by default categories).

**Comment by simonhatch** [comment]
<img width="1443" alt="screen shot 2018-01-22 at 5 51 20 pm" src="https://user-images.githubusercontent.com/11619067/35248655-f3d2abf8-ff9c-11e7-940d-c042b34820e4.png">

In the bottom right, when you click on a point and then an item in the "values" area, you'll get all the traces collected as part of that run.

**Comment by tdresser** [comment]
Thanks, I didn't realize the green boxes were anything but decorative...
What do they represent?

The trace links are kinda confusing. It isn't clear why we show (number of runs * number of metrics) links to traces.

**Comment by simonhatch** [comment]
Pinpoint runs the test at each point a number of times, those green boxes represent are the results of each of the build/test/results steps from one complete test run.

**Comment by tdresser** [comment]
We are there multiple traces per green box?

**Comment by simonhatch** [comment]
Originally I thought they were per-story but looking closer I think they're actually per-metric. So we could probably display that better, often they point to the same trace url.

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
Ah, this is probably why some of the recent jobs have gone over the size limit. Lots of redundant data. @simonhatch, do you want to look into it?

**Comment by dave-2** [comment]
I'll use this bug for the "duplicate traces" issue, and will track the trace visibility issue in #3886
