### ISSUE TITLE
[📍] Pinpoint sometimes comments on bugs when it couldn't reproduce if it doesn't get values

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#4187]
Example:
https://bugs.chromium.org/p/chromium/issues/detail?id=797118#c9 says "📍 Couldn't reproduce a difference", but https://pinpoint-dot-chromeperf.appspot.com/job/16f90944840000 shows no values.

@dave-2 @simonhatch

**Comment by dave-2** [comment]
I would call this fixed in #4231. Improved UI for tryjobs is tracked in #4298.
