### ISSUE TITLE
[📍] Extra test arguments field doesn't seem to work

### ISSUE THREAD

**Issue by a4sriniv** [catapult-project/catapult#4191]
I tried starting a try job to run the speedometer2 benchmark with the "Extra Test Arguments" field set to `--pageset-repeat 300 --suite "Vanilla|jQuery"`, but this seemed to have caused an error and redirects me to the undefined job page. If I run the benchmark without any arguments, it seems to work fine.

Am I entering these arguments in the right format?

**Comment by simonhatch** [comment]
Looks like a duplicate of #4130
