### ISSUE TITLE
Dashboard - Failing to update bug

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4193]
Getting a tonne of errors in the logs failing to update bug 787194, haven't dug into why yet.

@anniesullie @eakuefner

**Comment by simonhatch** [comment]
Going to close this and reopen on crbug

**Comment by simonhatch** [comment]
Ok turns out this is our issue, trying to assign an issue to someone who may not be part of the project.

Easiest thing to do would be to fallback to not setting the owner if that first call fails. We could try to guess a chromium account as well, as suggested in the crbug, but that's error prone and won't work 100% either. Thoughts?

@anniesullie @eakuefner

**Comment by anniesullie** [comment]
Yeah, I think generally people land CLs with google.com accounts because they don't have chromium accounts. I think the old bisect code tried to assign, and if it got an error it would try to add a comment and just cc the owner. I think that's the best we can do?

**Comment by simonhatch** [comment]
SGTM
