### ISSUE TITLE
[📍] Could not find histogram for webview test

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4195]
Job:
https://pinpoint-dot-chromeperf.appspot.com/job/14802e4c840000

Sample Swarming tasks:
https://chromium-swarm.appspot.com/task?id=3b3d95d4245a8b10
https://chromium-swarm.appspot.com/task?id=3b3d95d6b09da810

Sample histogram JSON:
https://isolateserver.appspot.com/browse?digest=9290d064090d0e7c0dd03e6b3877cfa626dba97b
https://isolateserver.appspot.com/browse?digest=35603d2dcd1921a7e76a9fa9afecf787caa2d8ad

Exception:
```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-e3d1f7a3.407146968428388466/dashboard/pinpoint/models/quest/execution.py", line 99, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-e3d1f7a3.407146968428388466/dashboard/pinpoint/models/quest/read_value.py", line 255, in _Poll
    raise ReadValueError('Could not find values matching: %s' % name)
ReadValueError: Could not find values matching: histogram: memory:webview:all_processes:reported_by_chrome:malloc:effective_size tir_label: browse_media story: browse:media:facebook_photos
```

**Comment by dave-2** [comment]
I don't see any webview results in the histogram json at all. Maybe the bot is misconfigured or something? @perezju

**Comment by perezju** [comment]
Yup, from the swarming task:

> Command: /usr/bin/python ../../third_party/catapult/devil/devil/android/tools/system_app.py remove --package com.android.webview com.google.android.webview -v -- ../../testing/scripts/run_telemetry_benchmark_as_googletest.py ../../tools/perf/run_benchmark system_health.memory_mobile --story-filter browse.media.facebook.photos --pageset-repeat 1 **--browser android-chromium** -v --upload-results --output-format=histograms --results-label chromium@f5e7621 --isolated-script-test-output /b/s/w/iog_IipH/output.json --isolated-script-test-chartjson-output /b/s/w/iog_IipH/chartjson-output.json

It's using the wrong kind of browser. How is that configured?

**Comment by simonhatch** [comment]
Dashboard supplies that, so I'll take this.

**Comment by simonhatch** [comment]
Dashboard config is updated, job here has the right browser: https://pinpoint-dot-chromeperf.appspot.com/job/129fd75c840000

Will wait til that finishes to close.

**Comment by simonhatch** [comment]
So another difference I just noticed was that the waterfall webview bots have this additional commandline param: --webview-embedder-apk=../../out/Release/apks/SystemWebViewShell.apk

**Comment by perezju** [comment]
I'm not sure how webview bots work on swarming, but it sounds like we also need that flag. How is that currently done for bots on the waterfall? Ideally we would like the same mechanism deciding on both bisects/waterfall what the required arguments are.

+ @nedn FYI for Telemetry args

**Comment by nedn** [comment]
@perezju they're set in here:
https://cs.chromium.org/chromium/src/tools/perf/core/perf_data_generator.py?rcl=ba12dcb89c18e461ec3963543c349260e620969c&l=643

It's a good point that it's desirable to have common place for the same args. However, with @ehanley324's work to refactor the perf json (Chromium Test Unification project), how this works will change drastically. So probably visit this again after that project is done :-)

**Comment by simonhatch** [comment]
Ok sounds like we should just lift that code into pinpoint for now. All the webview bots are down at the moment, when that get's resolved I'll rekick the test I ran yesterday with the apk param.

**Comment by ehanley324** [comment]
Is this flag needed for bots on the perf waterfall?  The way we generate json will be changing, but this is still the score set of flags that will be passed through the json to the script running telemetry on the swarming bot.  If we need a flag for some android bots we should add it here even before we refactor this so it doesn't get lost.

**Comment by perezju** [comment]
The flag is now there both for [bots on the waterfall](https://cs.chromium.org/chromium/src/tools/perf/core/perf_data_generator.py?rcl=master&l=617) and [for pinpoint](https://chromium.googlesource.com/catapult/+/a1303e46889b22580cbf6129a01fd1c1c094b4f3/dashboard/dashboard/pinpoint/models/quest/run_test.py#165).

**Comment by ehanley324** [comment]
Thanks for clarifying, I missed that.  lgtm
