### ISSUE TITLE
loading benchmark: a lot of bogus timeToOnload samples

### ISSUE THREAD

**Issue by irori** [catapult-project/catapult#4197]
Example: https://console.developers.google.com/m/cloudstorage/b/chrome-telemetry-output/o/AllRecipes_2018-01-24_08-08-55_56684.html

timeToOnload has 22 samples, 21 of them have no associated url and 20 are <1ms.
Perhaps they're from initial empty document for iframes? (Aren't we excluding events from subframes?)

cc: @nyaxt @nedn

**Comment by nedn** [comment]
@tdresser

**Comment by tdresser** [comment]
@deepanjanroy  @anniesullie 

Is process isolation causing us to report way more values for all our loading metrics?
I've been noticing that we're getting way too many values for paint metrics too.

Deep, can you take a look?

**Comment by deepanjanroy** [comment]
I debugged that trace and all those bogus onload values have empty url (""). Maybe we should add the empty url to [url blacklist](https://github.com/catapult-project/catapult/blob/8d63750dfb6f6734aaa66a95f553faa0bc93b703/tracing/tracing/metrics/system_health/loading_metric.html#L133)?

**Comment by tdresser** [comment]
Sounds good to me - can you own that work?

**Comment by deepanjanroy** [comment]
yes.

**Comment by karan173** [comment]
Hi can this be looked at with some priority since this essentially means that the onLoad timings given by telemetry are incorrect.  Also, not sure whether it is a part of this issue but I found that the onLoad timings for the "cold" cache temperature were lesser than those with the "warm" cache setting, which is probably incorrect.

Thanks.

**Comment by deepanjanroy** [comment]
CL uploaded: https://chromium-review.googlesource.com/c/catapult/+/894842
Should be fixed soon.

**Comment by deepanjanroy** [comment]
Should be fixed now.
