### ISSUE TITLE
Perf Dashboard: Units on Y-Axis of graphs says "percent" but should be "ms"

### ISSUE THREAD

**Issue by miu-at-google** [catapult-project/catapult#4198]
Chrome version: 58.0.3029.110 (Linux)
URL: https://chromeperf.appspot.com/report?sid=52d57df0c9ce96510c9a761cacc9143f3656f2b4e3b3e97e93f0de0ba66011fc&start_rev=524971&end_rev=531738

Repro steps:
1. Navigate to: https://chromeperf.appspot.com/report
2. Add the following graphs:
    test suite: performance_browser_tests
    bot: chromium-rel-win7-gpu-ati
    subtest: TabCapturePerformance_comp_gpu/Capture, .../CaptureLatency, and .../CaptureFailRate

Expected:
Y-Axis for Capture and CaptureLatency graphs should be "ms" (milliseconds).

Observed:
Y-Axis for Capture and CaptureLatency graphs is "percent."

Note that I *did* check that the test output is providing the correct units (in RESULT lines):

[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TabCapturePerformanceTest
[ RUN      ] TabCapturePerformanceTest.Performance/1
[711:6403:0124/202545.809687:WARNING:notification_platform_bridge_mac.mm(510)] AlertNotificationService: XPC connection invalidated.
[711:775:0124/202546.565081:INFO:CONSOLE(47)] "URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.", source: chrome-extension://ddchlicdkolnonkihahngkmmmjnjlkkf/performance.js (47)
Still waiting for the following processes to finish:
	./performance_browser_tests --enable-gpu --gtest_also_run_disabled_tests --gtest_filter=TabCapturePerformanceTest.Performance/1 --single_process --test-launcher-jobs=1 --test-launcher-output=/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/.com.google.Chrome.8UVqJJ/resultsYGHmvm/test_results.xml --test-launcher-print-test-stdio=always --test-launcher-timeout=120000 --user-data-dir=/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/.com.google.Chrome.8UVqJJ/dPOsInm --verbose
[711:775:0124/202601.573685:INFO:CONSOLE(0)] "[SUCCESS] tabCapturePerformanceTest", source: chrome-extension://ddchlicdkolnonkihahngkmmmjnjlkkf/performance.html?WebRTC=0&fps=60 (0)
*RESULT TabCapturePerformance_comp_gpu: RenderWidget::DidCommitAndDrawCompositorFrame= {16.711070,2.142408} ms
*RESULT TabCapturePerformance_comp_gpu: Capture= {16.709989,2.352931} ms
*RESULT TabCapturePerformance_comp_gpu: CaptureLatency= {18.438067,4.721133} ms
*RESULT TabCapturePerformance_comp_gpu: CaptureFailRate= 0.000000 percent
[711:775:0124/202603.295315:INFO:chrome_cryptauth_service.cc(231)] Profile is not authenticated yet; waiting before starting CryptAuth managers.
[       OK ] TabCapturePerformanceTest.Performance/1 (17566 ms)
[----------] 1 test from TabCapturePerformanceTest (17566 ms total)

**Comment by eakuefner** [comment]
Investigation reveals that this is not actually a dashboard bug, but rather a problem with the bot-side code that translates these results into the JSON that's uploaded.

Here's the JSON from a recent build that was uploaded to the dashboard: https://logs.chromium.org/v/?s=chrome%2Fbb%2Fchromium.perf%2FWin_7_ATI_GPU_Perf%2F1759%2F%2B%2Frecipes%2Fsteps%2Fperformance_browser_tests_Dashboard_Upload%2F0%2Flogs%2Fjson.output%2F0

You can see the "percent" units throughout.

@miu-at-google Please file a Chromium bug with the component Speed>Benchmarks.

@ehanley324
