### ISSUE TITLE
[📍] Pinpoint UI does not label graph axis

### ISSUE THREAD

**Issue by reillyeon** [catapult-project/catapult#4205]
I was given a link to a Pinpoint report however none of the axis are labeled so I am unable to interpret what the report is trying to tell me.

_Edited to add_: The job in question: https://pinpoint-dot-chromeperf.appspot.com/job/149bddac840000

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
Lol how embarrassing... flot, our charting library, doesn't support axis titles.

**Comment by simonhatch** [comment]
Yeah, dashboard has to do this: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-container.html#L207
