### ISSUE TITLE
[📍] Link in Monorail comment points to pinpoint.chromeperf instead of pinpoint-dot-chromeperf

### ISSUE THREAD

**Issue by reillyeon** [catapult-project/catapult#4206]
It appears that the correct hostname for Pinpoint is pinpoint-dot-chromeperf.appspot.com however in [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=805032#c7) the link is instead pinpoint.chromeperf.appspot.com which results in an SSL certificate error.

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
Sorry, this is an artifact of some jobs I edited manually yesterday. It won't happen normally.
