### ISSUE TITLE
benchmark_duration needs to be recorded for histogram tests

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4207]
Currently, Telemetry uses AddValue to add benchmark_duration, which means that it is not present for TBMv2 tests' histogram output. We should add it as a histogram for TBMv2 tests. This will take a tiny bit of finessing, since we also use chart_json_converter to convert legacy tests' chart JSON to histograms. We'll just have to make sure that this value/histogram is added exactly once based on the type of test.

**Comment by simonhatch** [comment]
We should also update any sheriffing/anomaly configs. I'll do that.

**Comment by eakuefner** [comment]
Of course, make sure that for now we monitor on both `benchmark_duration` and `benchmark_total_duration`; `benchmark_total_duration` will _not_ be present in chart JSON output.

**Comment by simonhatch** [comment]
Yep, also added a new anomaly config to look for jumps of 300,000 (5 minutes like old value)
