### ISSUE TITLE
Pinpoint - Let's add a "Re-run" button

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4210]
Will make going over and re-kicking failed bisects a lot easier.

@anniesullie @dave-2

**Comment by simonhatch** [comment]
I'll take this.

I'm thinking of copying Ben's expanding + menu in the bottom right, and moving the perf try in there along with a re-run option. wdyt?

**Comment by dave-2** [comment]
Sure, but it's a little different from the spec, so maybe we can adjust it. The expand should happen on click rather than hover, and the FAB should turn into a cancel button.

https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions

**Comment by simonhatch** [comment]
Sounds good!

**Comment by benshayden** [comment]
The MD spec seems aimed primarily at mobile touchscreens, which don't support hover, so I have to wonder what it would say if it were aimed at desktop. On touchscreens, V2SPA's FAB menu opens on tap and closes on the next tap (wherever that is), which is similar to how the FAB in Inbox for Android behaves, and seems close enough to spec. V2SPA's FAB's desktop behavior was modeled after inbox.google.com. But I'm happy to change V2SPA if the UX can be improved.

**Comment by simonhatch** [comment]
Ok give this a try, took Ben's floating button, tweaked to happen on click. Eventually I imagine we could let them tweak the parameters of the job before sending, but for now this is just uses the exact same params.

https://dev-simonhatch-df24d519-dot-pinpoint-dot-chromeperf.appspot.com/job/148aa1c5840000

**Comment by benshayden** [comment]
I sent you both a link to docs about usability issues with FABs. I might explore alternatives.

**Comment by simonhatch** [comment]
Sounds good, I'm not super attached to the fab, would just like to see an easy way to get at this.

**Comment by dave-2** [comment]
Looks like auto_explore is always set to `False` for the re-runs. I filed #4251 for one possibility for fixing it.

**Comment by perezju** [comment]
Just found this. Adding a re-run button was probably a quick way to move forward; but isn't it going in the opposite direction of what pin-point was aiming at?

That is, rather than "retrying" the whole job; be able to add extra attempts to some of the changes explored, or even add new changes to explore?

**Comment by simonhatch** [comment]
Yeah think you're right, ideally we'd be able to manipulate the job more as you mentioned. Don't think this is meant to replace that, just to make perf sheriffing a little easier in the short term.
