### ISSUE TITLE
Dashboard never marks alerts recovered

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#4211]
I've been doing a lot of triaging, and dashboard never seems to update bugs after alerts recover. Am I reading this code right that it only marks *untriaged* alerts as recovered? https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/alerts.py

If so, should I fix that code, or should we consider a larger refactor?
@simonhatch

**Comment by simonhatch** [comment]
Yeah seems that way! The code in auto_triage.py is actually what sets recovered, and it only queries for untriaged anomalies. Since we have our 1:1 later, we can talk about whether a larger effort is needed.

**Comment by anniesullie** [comment]
This depends on #4370

**Comment by anniesullie** [comment]
Which is *fixed*, so is this.
