### ISSUE TITLE
Fix the negative value of blocked_on_network of breakdown in loading metric

### ISSUE THREAD

**Issue by maxlgu** [catapult-project/catapult#4214]
The current way of calculating blocked_on_network based on approximating events' wall clock duration in a range is not accurate, causing the values to be negative sometimes, which doesn't make sense.

**Comment by sarathsi** [comment]
Hi , Is there any quick fix / workaround for this? I almost always see -VE "blocked_on_network" in the results. Thank you.

**Comment by sarathsi** [comment]
Something to fix in  here??
function addIdleAndBlockByNetworkBreakdown_() 
    let totalBlockedDuration = rangeOfInterest.duration;
    for (const component of Object.values(breakdownTree)) {
      totalBlockedDuration -= component.total;
    }

**Comment by maxlgu** [comment]
Hi,
The issue is caused by an approximating approach in calculating the self-time.
Here's the quick fix you can use:
https://chromium-review.googlesource.com/c/catapult/+/901770

The patch will be landed later soon.
Thanks!

**Comment by sarathsi** [comment]
Thank you very much. This fixed the problem.

**Comment by maxlgu** [comment]
Thanks Deep. The issue is fixed as the fix is in.
