### ISSUE TITLE
ValueCanBeAddedPredicate not respected for histogram output

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4215]
In offline discussion with @simonhatch we realized that we're uploading spurious histograms using the histogram pipeline because we currently pass the histogram set directly through Telemetry, rather than filtering based on ValueCanBeAddedPredicate. We need to add a pass that filters the HistogramSet based on the conditions of ValueCanBeAddedPredicate.

**Comment by eakuefner** [comment]
@nedn 

This actually turns out to be pretty complicated, because `ValueCanBeAddedPredicate` can accept an arbitrary value. In practice, all existing usages of `ValueCanBeAddedPredicate` filter on the name only.

Ned, what I would like to do here is restrict `ValueCanBeAddedPredicate` to accept only the name of the value, rather than the whole value. Does that sound okay with you? If so, then I can own the two-sided patch to do this (there are not very many implementations of ValueCanBeAddedPredicate in tools/perf) and send an announcement to telemetry-announce.

**Comment by nedn** [comment]
That sounds ok to me!

**Comment by eakuefner** [comment]
Thanks. I'll get started on this work.

**Comment by eakuefner** [comment]
Status update: almost done here. Waiting for cleanups on the src/ side to be approved, then we'll get rid of VCBAP (already have a CL up for that).

The parallel effort to use `ShouldAddValue` to filter histograms is ongoing. There's a bit of metric work to do to make sure that we can sanely delete histograms (see above), and then I'll write one last Telemetry CL to filter histograms in `timeline_based_measurement`.
