### ISSUE TITLE
REVISION_TIMESTAMPS diagnostic

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4218]
For non-chromium.perf clients, we'll need the ability to key histogram uploads by something other that Chromium commit positions. In particular, it would be best to introduce a `revisionTimestamps` shared `DateRange` that contains the source control timestamp from the revision under test.

There are other issues described in #3014 that this helps solve, but the goal for now is to just reserve this name and use it when keying  rows and histograms in `add_histograms_queue` to allow data to be uploaded sanely from non-Chromium waterfalls.

**Comment by eakuefner** [comment]
Just wanted to record a caveat that I came across when looking into this: git actually deals with two different timestamps, per commit. There's an "author" timestamp and a "commit" timestamp. In Gerrit, for some repos (Catapult, but not Chromium for example), the author timestamp is when the CL was created (might be patch set, not sure), and the commit timestamp is when CQ actually landed it. So commit timestamps can reasonably well be thought to be monotonic, where author timestamps cannot. For this, then, we want to make sure to use commit timestamps, just in case we're dealing with a repository wherein author and commit timestamps differ.

**Comment by eakuefner** [comment]
We learned today that commit timestamps coming from Gerrit are not necessarily monotonic. If the merge strategy is "Rebase always", though, we're fine as per the documentation cf https://gerrit-review.googlesource.com/Documentation/project-configuration.html#rebase_always.

We should see if it's possible for all projects that we test to use rebase always.

**Comment by kharland** [comment]
I think nearly all Fuchsia projects use Rebase only so we should be ok.   I can check for place where we're not and see if we can change that.

**Comment by eakuefner** [comment]
Revision timestamps have been implemented on the dashboard side, so I think this is done.
