### ISSUE TITLE
Migrate FailureValue and SkipValue out of the value system

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4229]
Currently, `FailureValue` and `SkipValue` are Value subtypes, which is problematic for a number of reasons:

* Benchmarks could add either type of value if they wanted to. Currently, no benchmarks add FailureValues in tools/perf, but one benchmark adds a SkipValue and probably shouldn't.
* That these types are value subtypes creates an expectation that these will be surfaced like values. Currently, we do not surface them: FailureValues and SkipValues are thrown away when converting to chart JSON.
* Toward a long term view of replacing the Telemetry value system with the Catapult histogram system entirely, there is no correspondence between FailureValue/SkipValue and the histogram system.

FailureValues and SkipValues are used for a few things in Telemetry that it may not be worth it to try to subsume. For example, FailureValues can alter control flow and SkipValues are used to report which pages where skipped.

I would propose:

1. Simplifying FailureValue and SkipValue and making them not be value subtypes (maybe move to telemetry/internal/results)
2. Refactoring PageTestResults to consist of a backend, to which Telemetry can have access but benchmarks should not, and a frontend, to which benchmarks can have access. The backend would let you do everything that PTR can do right now, and have hooks for adding skips or failures, and the frontend would only let you add values/histograms and look them up.

The second step would also have the benefit of disallowing benchmarks from calling any one of the methods of PageTestResults which are public so that they can be called elsewhere in Telemetry, but probably should never be called by benchmarks.

@nedn WDYT?
@benshayden FYI

**Comment by nedn** [comment]
> 1. Simplifying FailureValue and SkipValue and making them not be value subtypes (maybe move to telemetry/internal/results)


I think making FailureValue & SkipValue not value subtypes is probably the right direction. Overall, these signals has more to do with the json test results format that track fail/pass, than the histogram/chartjson which track perf metrics.

The only relevant bit, I think is histogram/chartjson should still know about missing value because that may affect the fidelity of the statistics that they output. 

> Refactoring PageTestResults to consist of a backend, to which Telemetry can have access but benchmarks should not, and a frontend, to which benchmarks can have access. The backend would let you do everything that PTR can do right now, and have hooks for adding skips or failures, and the frontend would only let you add values/histograms and look them up.

I still think it's ok for benchmark to add failure & skip signal. For an analogy, in python unittest, you can invoke self.fail("this is failed") or self.skip("this is skipped") to stop the test. What we can consider is expose similar Fail() & Skip() methods instead of allowing benchmarks/stories to construct these Failure/Skip values directly.

@perezju

**Comment by eakuefner** [comment]
Right, failures and skips are currently taken into account in Telemetry's summarization path. One fortunate thing with histograms, though, is that you don't necessarily need explicit skip or failure information to explain why merged histograms may be off. If a story is skipped or fails in Telemetry, then the merged histogram will exclude that story from the STORIES diagnostic. We plan to eventually surface information like this on perf dashboard graphs.

I realized that the issue of whether benchmarks can add skips or failures is orthogonal to the idea of splitting skip and failure logic out of the value system. I like the idea of just adding Fail() and Skip() hooks to PageTestResults, which is much simpler than my original proposal of splitting PTR into a backend and frontend.

So here's my revised implementation plan:

1. Add Fail and Skip hooks to PageTestResults, and implement initially in terms of FailureValue and SkipValue
2. Port all FailureValues and SkipValues in Telemetry to use Fail and Skip hooks instead.
3. Port the one usage of SkipValue in tools perf to Skip
4. Move FailureValue and SkipValue out of the value system and update the logic that uses them.

**Comment by nedn** [comment]
SGTM

**Comment by eakuefner** [comment]
Update: CLs up for parts 1-3. Part 4 coming up.

**Comment by eakuefner** [comment]
It's now time for us to make Failure and Skip non-values. One of the first questions I tried to answer was which parameters to delete from the constructor. I struggled with the story/page field but then figured out that we can delete it.

Currently, values are organized into story runs, but there is no need for this in the histogram system, since individual histograms are annotated with their story run information as they are imported by Telemetry.

The story run concept is still useful for allowing the JSON test results output formatter to figure out when story runs were failed/skipped, and it's also useful for the filtration logic (ShouldAddValue). It is only otherwise used by merge_values and summary.py, which we can delete when we delete the value system. But I think this points to us wanting to initially keep track of lists of Failures and Skips within StoryRun, which in turn implies that, unlike values, they need not know their story (since the StoryRun already knows it).

So, to continue this plan:

1. Make `Failure` a very simple object that just tracks the exception or message and a `handleable` boolean. The description field of `FailureValue` is currently only ever used to figure out whether the failure was able to be handled by Telemetry or not.
2. At the same time, add a `failures` field to `StoryRun`
3. Massage the logic in `Summary` to deal with that `StoryRun` change
4. Migrate all users of FailureValue in Telemetry to use this new, slightly different object
5. Implement PageTestResults.Fail in terms of StoryRun.Fail, which is already implemented to be responsible for creating Failure objects but not currently called outside of tests. This mirrors how AddValue is implemented today.

We will be able to do a similar thing for Skip (will just track a reason). There can be a debate about whether we want to replace these lists with a single property that just takes the run status (pending/succeeded/failed/skipped), but the above design gives feature parity for now (technically, it is possible to add multiple failures/skips per story run). The simplicity of these objects lends support to the idea of just simplifying this whole thing into a vastly easier 'status' concept at some point after we do this.

**Comment by eakuefner** [comment]
And to be clear, steps 1-5 will have to be done atomically.

**Comment by perezju** [comment]
plan sgtm!

**Comment by eakuefner** [comment]
Update: in the CL for this I uploaded, @nedn asked a really good question: why does StoryRun even need to track a list of failures at all? The answer is, it doesn't, because we never use them for anything. Failure does not need to be a class, and the CL basically does everything I described above _except_ making Failure an object and storing them. Instead, it really is enough for StoryRun just to know whether it failed or not.

**Comment by eakuefner** [comment]
The CL I landed ended up needing to be reverted because there are a bunch of unit tests in tools/perf that refer to results.failures. Luckily, a quick scan seems to indicate that callers always just check the `len`, so my plan to reland is:

1. Land with the `failures` getter still present, implemented simply in terms of `num_failures`, which we plan to keep.
2. Switch the callsites on the Chromium side to use `had_failures` instead.
3. Delete the `failures` getter.

**Comment by eakuefner** [comment]
As of https://chromium-review.googlesource.com/c/catapult/+/940268 the work to remove FailureValue will be complete. The work for SkipValue will be similar, but hopefully simpler.

**Comment by benshayden** [comment]
@CalebRouleau

**Comment by perezju** [comment]
FYI - I also removed the SkipValue as part of work on [crbug.com/921616](https://crbug.com/921616).
