### ISSUE TITLE
Dashboard - Check if revision is an integer value

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4239]
/add_histograms should check that revision is an integer value. We'll die later anyway, should probably surface a nicer error message.

@eakuefner

**Comment by eakuefner** [comment]
I think the Fuchsia case actually illustrates that this bug is catastrophic, too. It seems that we can get one upload in with a string revision and then not subsequent ones, so we should definitely make sure to short this out as soon as possible in the code.
