### ISSUE TITLE
Add the ability to fetch raw performance data

### ISSUE THREAD

**Issue by kharland** [catapult-project/catapult#4246]
The Fuchsia team will often want to locally analyze performance test data.   As an example, one use case is that we'd like download the raw performance numbers for some zircon benchmark and plot metrics such as the median or average of these runs to compare one test with another. 

It would also be useful to have information about the build that produced a set of test results such as the hardware and git revision that were involved.

**Comment by simonhatch** [comment]
FYI @benshayden is working on a revamp of the dashboard UI, which will actually expose a lot of statistical information.

But if you're interested in getting the performance test data, we do have an (early) api here: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/api/README.md

Let me know if that meets your needs.

**Comment by anniesullie** [comment]
@simonhatch from offline discussion I think they'd like to be able to fetch raw histogram data from the API, which seems like a good feature. @eakuefner

**Comment by simonhatch** [comment]
Ah, well there's actually /get_histogram and /get_diagnostic endpoints, they're not using the same auth as the api but we can change that.

**Comment by eakuefner** [comment]
We also haven't implemented the ability to fetch timeseries of histograms yet, not sure if that's something that would be required here, but it would be good for our roadmapping to clarify.

We don't actually store the raw data as uploaded, and that would be better to rely on LogDog for. If that's a feature that folks are interested in, then we can reserve a diagnostic name (maybe DATA_URLS?) for storing links to raw data.

**Comment by kharland** [comment]
anniesullie@ is correct.  Ah but there is one thing I forgot about:  Our perf tests spit out 10,000 - 20,000 sample points, which means we have to truncate these values before uploading to Catapult or else the dashboard rejects the upload because it's too large.   It sounds a bit absurd but having all of those datapoints but they reveal some odd things about the test run such as spikes in the first and last few runs and steps at different intervals.

LogDog isn't a bad idea, but the process for fetching data from LogDog using a git revision or builder API seems a bit complicated. We've considered using Google Storage for this since much of our infra already works with gsutil; That still seems like a viable option if we can't use Catapult.

**Comment by simonhatch** [comment]
Ah right, we talked about this last week on chat, believe the solution we discussed was what Ethan mentioned, stuffing it in cloud storage of some kind and leaving a diagnostic in with the link so that you can refer to it from the dashboard. Yeah I think we can get something going here, wonder if it makes sense for us to upload it to cloud storage for you and then strip/lighten the histogram that's stored with the row.

**Comment by kharland** [comment]
I hadn't thought about that: having Catapult do the stripping/uploading for the User. That wouldn't be a bad idea from the client's perspective.  I'm not sure what kind of load that puts on the Catapult team.  This is important but not urgent for us, so if it's feasible but can't be done in very short-term that's perfectly OK.

**Comment by benshayden** [comment]
[/api/timeseries2?columns=histogram](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/api/README.md#timeseries) returns timeseries of full uploaded histograms. If you run into problems, please open a new bug in crbug instead of github.
