### ISSUE TITLE
Pinpoint job runs forever because request deadline exceeded

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#4248]
This was started 5 days ago and is still running: https://pinpoint-dot-chromeperf.appspot.com/job/16f70c89840000. Is it normal?

@simonhatch

**Comment by simonhatch** [comment]
@dave-2 

Haven't dug too deep but maybe Dave has seen this before, found this in the logs:
"Process terminated because the request deadline was exceeded."

**Comment by dave-2** [comment]
I've seen a couple of these, but not sure yet what causes them. Maybe a request to an external service took too long, bringing the total processing time over 100s.

In the case where the deadline is exceeded, the Job will stop running, but it won't be updated in the datastore, so the UI will say it's still "running". Maybe we need cron job or something on the backend to monitor and re-kick these tasks.

**Comment by dave-2** [comment]
I wrote the cron job as described in the previous comment. But then I ran a query for what jobs it would affect, and we haven't seen this since March 6. I do know we made some improvements to error handling around that time (8a42ad3cb185e340c32b20f657980fd057e3769f and 47c60197d6b64fbfa560a766eeb31b27a18db078). So maybe this is fixed, and we don't need a cron job after all. I just need to run a one-time migration to close out the old jobs.

I prefer not having a cron job if we can, because it may hide other errors related to job scheduling and error handling.

**Comment by dave-2** [comment]
Just in case we need it in the future (before I go in and fail the old jobs), here's the data from the time period around Mar 6.
```
  i job_id         job creation time          time since last updated
 44 129f75ca440000 2018-03-08 20:03:19.650810 0:00:12.812890
 45 16049cac440000 2018-03-08 16:17:04.149700 0:11:02.523440
 46 12d75bca440000 2018-03-08 15:43:07.900380 0:00:25.482450
 47 12e69552440000 2018-03-08 10:57:25.498650 0:00:42.311140
 48 15f09462440000 2018-03-07 21:05:05.399180 0:00:14.142090
 49 148b0a12440000 2018-03-06 19:52:32.769190 0:00:19.454910
 50 16cc175c440000 2018-03-06 00:58:52.309400 0:10:54.802260
 51 12c4e692440000 2018-03-06 00:26:19.943940 0:00:13.395210
 52 11dec422440000 2018-03-06 00:22:11.563150 8 days, 22:07:34.009990
 53 14ba1422440000 2018-03-06 00:20:32.641020 0:09:16.455140
 54 1595815c440000 2018-03-05 22:48:59.922630 0:11:10.569500
 55 14943902440000 2018-03-05 16:15:47.572460 0:00:38.922940
 56 1488b712440000 2018-03-05 15:03:48.977530 8 days, 22:07:31.056980
 57 148fe1ec440000 2018-03-05 12:01:32.995070 0:01:03.395750
 58 16fcd2fc440000 2018-03-04 23:46:46.476270 0:01:15.591400
 59 14a483cc440000 2018-03-04 19:52:02.416350 0:00:24.067390
 60 14e91e3c440000 2018-03-04 19:20:20.762010 8 days, 22:07:32.255850
 61 14adce3c440000 2018-03-04 19:17:06.217270 10 days, 17:26:46.362260
 62 14931d94440000 2018-03-02 16:09:08.020720 12 days, 18:53:17.150600
 63 12f60d18440000 2018-02-28 07:11:46.283270 12 days, 19:28:28.833690
 64 14a2c368440000 2018-02-27 21:16:56.173270 15 days, 22:04:33.814520
 65 11f511f0440000 2018-02-27 21:01:57.349690 15 days, 22:05:43.740200
 66 14b6ba18440000 2018-02-27 16:19:43.251550 15 days, 22:05:27.230630
 67 12e10b48440000 2018-02-27 14:28:11.576510 15 days, 22:05:21.719950
 68 16d8a648440000 2018-02-27 10:08:39.272380 15 days, 22:05:17.715790
 69 14872858440000 2018-02-27 07:34:16.800940 15 days, 22:04:35.140800
 70 14a87268440000 2018-02-27 07:34:01.400610 15 days, 22:05:17.308000
 71 14fff058440000 2018-02-27 07:33:56.231220 15 days, 22:05:28.794040
 72 14e872f0440000 2018-02-27 07:32:27.265250 15 days, 22:05:48.809340
```
