### ISSUE TITLE
[📍] Include all arguments in Job arguments dict.

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4251]
Originally I thought that we should restrict the arguments stored in the dict, so we don't clutter the display with irrelevant ones. But right now it seems more useful to include them all, so we can easily see what Changes the Job ran with, easily see whether it was a tryjob or perf bisect or functional bisect, and accurately re-run a job (#4210).

**Comment by dave-2** [comment]
Also considering taking out the `auto_explore` parameter. Since there's no "midpoint" of `HEAD` and `HEAD + patch`, the behavior is essentially the same for perf tryjobs and bisect jobs.

I think we would keep it only if we think it's useful to compare an old and a new revision without running a bisect.

@perezju

**Comment by perezju** [comment]
> I think we would keep it only if we think it's useful to compare an old and a new revision without running a bisect.

That's certainly something we would like to like to be able to do. For example when comparing between two distant Chrome milestones; we might want to be able to manually chose some specific points in between to also run and definitely *not* let autoexplore go and try to pin-point every single regression that happened between the last 5 releases or so.
