### ISSUE TITLE
Request to be added to LEGACY_BENCHMARKS in add_histograms_queue.py

### ISSUE THREAD

**Issue by xunjieli** [catapult-project/catapult#4260]
Test suite name: cronet_perf_tests
We want to remove the reporting of _min, _avg, _sum, _max suffixed statistics.

Ethan, could you help?

**Comment by eakuefner** [comment]
Sure. Is cronet_perf_tests the only suite for which we need to prevent creating these?

**Comment by xunjieli** [comment]
Yes, that's the only test suite that we need blacklisted.
All 24 benchmarks (listed on https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Cronet%20Perf%20Sheriff)  are under this test suite.

**Comment by eakuefner** [comment]
I have landed and deployed the fix, so this is **done**.
