### ISSUE TITLE
"Range" is named to clash with a Python builtin

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4261]
In the process of fixing #4218, I briefly investigated moving `DateRange` out of `histogram.py`. It turns out that `DateRange` depends on `Range`, so I would want to move that out as well. However, `range` is a Python builtin that returns a list of numbers. In practice, we mostly use `xrange`, although there are a few histogram tests that use `range`. And even in JS, we also have `Statistics.range`, which has nothing to do with `tr.b.Range`.

I can think of two ways to proceed:

1. Just move the Python range into tracing/value/range.py. Import range as range_module if we want to use the builtin range, but otherwise don't worry about the clobbering.
2. Rename Range to Interval.

@simonhatch @benshayden thoughts?

**Comment by benshayden** [comment]
I think it would make sense to rename Range to Interval at some point, but I don't think it needs to happen right now.

**Comment by eakuefner** [comment]
Thanks! It will be a little bit of a cleanup because there are certainly a lot of users of Range, so I'll just keep the Python Range in `histogram.py` for now, since nothing in the file actually uses `DateRange` (so date_range.py will be able to import histogram without circularity).

**Comment by eakuefner** [comment]
Another thing we discussed briefly offline was the idea of implementing `IntervalTree` in terms of the renamed `Range` for clarity.

**Comment by benshayden** [comment]
DateRange was moved out of histogram.py by importing histogram in the constructor instead of the module.
I don't think it's worth it to rename Range everywhere in catapult at this point. Maybe in TBMv3?
