### ISSUE TITLE
[📍] BattOr 'StartTracing' error

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4270]
https://pinpoint-dot-chromeperf.appspot.com/job/13d3f97d840000
https://chromium-swarm.appspot.com/task?id=3bb27b6e5330d410
```
BattOrError: BattOr did not complete command 'StartTracing' correctly.
Outputted: [0215/053306.180051:ERROR:serial_io_handler.cc(149)] Failed to open serial port: FILE_ERROR_ACCESS_DENIED
```
@zeptonaut

**Comment by zeptonaut** [comment]
Thanks for reporting this @dave-2. I filed this bug as https://bugs.chromium.org/p/chromium/issues/detail?id=813788 because I usually track these bugs in Monorail and put it on my backlog of BattOr issues to investigate.
