### ISSUE TITLE
[📍] benchmark_total_duration appears as a separate column in results2

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4271]
@eakuefner @benshayden @simonhatch 

Example: https://pinpoint-dot-chromeperf.appspot.com/results2/13d2e6bd840000

![image](https://user-images.githubusercontent.com/211662/36288493-bf152d10-126f-11e8-8017-7912fa667dab.png)

**Comment by benshayden** [comment]
[AddDurationHistogram](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/results/page_test_results.py#L394) needs to do this:
```
hist.diagnostics[reserved_infos.LABELS.name] = generic_set.GenericSet([self.telemetry_info.label])
```
It should probably also add diagnostics for benchmark_name and benchmark_start_epoch.
