### ISSUE TITLE
[🔊] Soundwave should cache responses in local sqlite db

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#4281]
We want this to:

* Avoid having to download the same data multiple times in case of failures.
* Help dealing with concurrency issues when later trying to get data from multiple requests in parallel.
* Serve as a stepping stone to sort out the tables/schemas we'll need before going for a more full-blown pipeline to materialize our data.

@zeptonaut

**Comment by zeptonaut** [comment]
:+1: this will hopefully make it a lot easier to join the data in meaningful ways for analysis

**Comment by perezju** [comment]
With #4382 closed (so we now let pandas to de df <-> SQLite translation), next steps here are to implement the `--continue` flag to retry and reuse partially downloaded data after a script failure.
