### ISSUE TITLE
add clk_set_rate support

### ISSUE THREAD

**Issue by weivincewang** [catapult-project/catapult#4284]
Upstream has clk_* in `/trace/events/clk.h' and clock_* in
`/trace/events/power.h' for reporting clock events.
Individual driver may pick either so we should support both.

**Comment by weivincewang** [comment]
https://chromium-review.googlesource.com/?polygerrit=0#/c/catapult/+/933284/

**Comment by eakuefner** [comment]
Looks like this is done.
