### ISSUE TITLE
"Re-run this job" button on pinpoint doesn't seem to work

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#4285]
https://pinpoint-dot-chromeperf.appspot.com/job/14c82720440000 failed, and I wanted to re-run it. To do so, I went down to the lower right hand corner of the job page, clicked the "+" FAB, then clicked "re-run this job".

The next page showed:

![image](https://user-images.githubusercontent.com/1407397/36611935-164fda38-18a3-11e8-9dba-8876b132fbfb.png)

Something looks broken here.

@simonhatch @dave-2

**Comment by simonhatch** [comment]
That link works fine to me. First thought is consistency issue, trying to load the job too soon after writing it initially?

**Comment by simonhatch** [comment]
Hmm is this your new job? https://pinpoint-dot-chromeperf.appspot.com/job/129943ff840000

**Comment by zeptonaut** [comment]
Nope - I started the one you linked to manually.

**Comment by simonhatch** [comment]
I mean is that the re-run?

**Comment by dave-2** [comment]
#4165

**Comment by zeptonaut** [comment]
@simonhatch nope. I started that one via a completely new try job (going to the main page, clicking the "+", and reentering all details for the job). @dave-2 as far as I can tell, I'm logged in (when I went back to the main page and started a new job, it worked. I haven't logged back in all day, and it still says "Sign out" in the upper right.)

**Comment by dave-2** [comment]
I think this is fixed! Let me know if it still doesn't work,
