### ISSUE TITLE
Pinpoint posts invalid links to monorail bugs when launching perf try jobs

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#4286]
I kicked off three perf try jobs attached to https://bugs.chromium.org/p/chromium/issues/detail?id=780907.

Pinpoint, as expected, posted three bug comments to the monorail bug:

- https://bugs.chromium.org/p/chromium/issues/detail?id=780907#c17, linking to https://chromeperf.appspot.com/job/11fada6f840000
- https://bugs.chromium.org/p/chromium/issues/detail?id=780907#c18 linking to https://chromeperf.appspot.com/job/14c82720440000
- https://bugs.chromium.org/p/chromium/issues/detail?id=780907#c19 linking to https://chromeperf.appspot.com/job/159b942f840000

At least on my machine, all three of those links are broken though.

I think that the prefix for the links should have been https://pinpoint-dot-chromeperf.appspot.com instead of http://chromeperf.appspot.com, which would have made the links: 

- https://pinpoint-dot-chromeperf.appspot.com/job/11fada6f840000
- https://pinpoint-dot-chromeperf.appspot.com/job/14c82720440000
- https://pinpoint-dot-chromeperf.appspot.com/job/159b942f840000

All of which work for me.

@dave-2 @simonhatch

**Comment by simonhatch** [comment]
Yeah sorry this was rolled back last night but I didn't deploy a new version until ~30 mins ago.
