### ISSUE TITLE
Exploring memory metrics in v2spa dashboard

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#4302]
On a discussion [about metrics](https://docs.google.com/document/d/10uY_Fp-n74yKzARNMyIZfqxUVrEDGHbcIu6Rety0KBE/edit?usp=sharing) I just wrote this:

> I'm not sure if just the notion of a parent metric is enough to concisely describe memory-infra metrics. Although it's true that the hierarchies in memory metrics can be represented by a tree, this approach (I believe) would still force us to explicitly list all the nodes of the tree, which is huge. Instead memory metrics can be more concisely thought of as having several "fields" or "parameters", and these parameters can range over some small-ish sets of values. The tree gets large when you multiply all of the possible value combinations (also with the added complexity that some combinations of values make sense while others don't).

Picture for some context:
![](https://storage.googleapis.com/chromium-docs.appspot.com/a73239c6367ed0f844500e51ce1e04556cb99b4f.png)

(Also see more details about [memory metrics](https://chromium.googlesource.com/chromium/src/+/master/docs/memory-infra/memory_benchmarks.md#understanding-memory-metrics))

Which got me thinking of this:
![memory_metrics_tree](https://user-images.githubusercontent.com/16922344/36892527-eb871b68-1dfc-11e8-85ae-a211fa33a83c.png)

The tree is *huge* and hard to explore for this very reason. If I've selected, say:

> memory → chrome → renderer_processes → reported_by_chrome → malloc → effective_size

and then I say to myself, "hmm.. I wonder how that same metric looks on the *browser_process*", then I have to go and navigate again on a completely different part of the tree.

I'm not exactly sure what a better representation would look like (one that also works for other metrics), just wanted to throw these comments here in case they are helpful spark some ideas.

@anniesullie @benshayden

**Comment by anniesullie** [comment]
@tdresser and @sadrulhc as well--in an ideal world we could come up with some way to represent hierarchy of metrics that "just works":
* The hierarchy works for telemetry, and the perf dashboard understands it
* The hierarchy works for UMA metrics and the finch/timeline dashboards understand it.
* You can also just read about in documentation, like a page linked off of go/speed-launch-metrics, which in my dream world only needs to be written in one place.

I have no idea if this is feasible at all, but I'm really happy that @sadrulhc started the discussion!

**Comment by tdresser** [comment]
I think parent/child relationships are adequate, we just might need more than just a simple parent field.

What if metric names in the file describing metrics could be regular expressions?
Then you could refer to a parent metric which wasn't explicitly defined, but matched a regexp.

**Comment by sadrulhc** [comment]
Something like tagging would also be helpful for this I think. Switching from browser to renderer would mean replacing the single tag.

Where does the screenshot of the tool in the OP come from? It looks interesting!

**Comment by benshayden** [comment]
@sadrulhc [V2SPA](https://v2spa-dot-chromeperf.appspot.com/#testSuite=system_health.memory_mobile&measurement=memory%253Achrome%253Aall_processes%253Areported_by_chrome%253Aeffective_size&bot=ChromiumPerf%253Aandroid-one) is a prototype of the next version of the chromeperf dashboard as a Single Page App. It's still very much under development, but please feel free to chat feedback at me!

Related sparklines allow navigation down through RelatedNameMap diagnostics (component and process type in the case of the memoryMetric), but, you're right, we haven't talked about breadcrumbs to navigate back up relationship trees. Thank you for starting this discussion!

If I were to try to address this in V2SPA right now, one thing I might try is a link below the Measurement box, above the chart that says "all_processes", which opens the all_processes version of the measurement in a new chart. That chart would contain related sparklines including the browser_process version of the measurement, so you could drill down that branch. There might be room for both the all_processes link and an "all components" link, and, for the cpu time metric, links to "all interactions" and "all threads". Would something along those lines help or do you have something else in mind? That would only work for RelatedNameMaps, not the reported_by_os/reported_by_chrome or effective_size/proportional_size dimensions, so maybe something more general is needed. I'm just thinking, I want to hear what you think! I'll prototype related sparklines in V2SPA soon so we can see what this stuff will look like. In go/chromeperf-v2, click the Launch Status link to see what I'm planning on prototyping next, and feel free to comment there to bump priority.

**Comment by perezju** [comment]
Honestly, I don't have a clear picture of how a good implementation would look like. But I can tell you about the sorts of things I would like to be able to accomplish (sorted in order of importance):

1. **If I know which metric I want, I should be able to find it quickly.** Although not fantastic, this works reasonably well in the current chromeperf picker, as I can type e.g. "java all_proc" to get a very short list from where I can pick my metric, say: `memory:chrome:all_processes:reported_by_os` `:system_memory:java_heap:proportional_resident_size_avg`.

   This use case doesn't work very well on the current V2SPA implementation. Even with filtering after typing, it forces me to do a bit of tree navigation until I can select my metric.

2. **After having selected a metric, I want to navigate to some other related metric.** Switching between renderer/gpu/browser/all processes is perhaps the most common. Going from a metric (e.g. `system_memory`) to a submetric (e.g. `system_memory:native_heap`), or the other way around would be very useful too. Switching between the various "size" labels (e.g. `effective_size` and `allocated_objects_size`) may also be somewhat common. Less common (but still makes sense on dual-browser benchmarks) is to jump from `memory:chrome` to `memory:webview`.

   I agree, perhaps using the notion of related metrics is the way to go for this. It sounds like this should cover the most common use cases, not sure about jumping between "sizes" though.

3. **Maybe I have no idea at which metric to look at.** Here it should be really easy to pick a top-level metric, say `memory:chrome:all_processes:reported_by_chrome:effective_size_avg`, then from there I can navigate to other related metrics.

**Comment by perezju** [comment]
Also forgot to reply to some previous comments:

> (from @anniesullie)
>
> The hierarchy works for telemetry, and the perf dashboard understands it

I intended to start this discussion more on how to visualize and navigate through memory metrics in the dashboard (orthogonal, although certainly related, to the question of how we organize them in code and documentation).

My focus was also in memory metrics because they are a particularly hard case, and because I have to deal with them a lot. Also note that for telemetry and the perf dashboard these are today an opaque blob-strings, they do not really understand the structure or hierarchy in them.

> (from @tdresser)
>
> What if metric names in the file describing metrics could be regular expressions?
> Then you could refer to a parent metric which wasn't explicitly defined, but matched a regexp.

That's certainly an interesting thought! I think that idea could work well for documenting memory metrics.

**Comment by benshayden** [comment]
I think this is done for now. Please feel free to open a new bug on crbug.
![](https://i.imgur.com/ExDYIxD.png)
