### ISSUE TITLE
Dashboard display incorrect delta percents

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#4304]

**Comment by simonhatch** [comment]
Do you have an example link?

**Comment by camillobruni** [comment]
I created a simple CL with the potential fix (obviously purely guessing): https://chromium-review.googlesource.com/c/catapult/+/946371

Example Graphs: https://chromeperf.appspot.com/report?sid=c783cddd83b7118ee1bd79d400e25061fd3af2f179ab8a19bb095a0cb0c28c9b&start_rev=36637&end_rev=10000000


Steps to reproduce (not fully reliable):
1. Select a range to get the delta on the above graph 
2. Note the delta (~100ms) and percentage (I've gotten up to 120%)
3. Redo roughly the same selection
4. Note a much lower (correct) value for the percentage (~80%)

**Comment by benshayden** [comment]
This is being rewritten in v2spa.
