### ISSUE TITLE
Write an apps script to inform benchmark owners of recent perf regression bug changes.

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#4311]
One big worry I have is that it's hard to know if a bug may have been WontFix-ed incorrectly (every once in a while I see a bug WontFix-ed because the CL author thinks the cause is not their CL, and sometimes they disagree with the benchmark owner on severity). It would be really easy to write an apps script to send a weekly report to each benchmark owner that lists all bugs WontFix-ed that week.

I thought that we may as well also have lists of Fixed and open bugs as well, since they are also easy and the benchmark owner may want to see them.

This collides a bit with benchmark health report, but is at a narrower scope (just making sure owners are able to follow up on bugs if they wish). @nedn @zeptonaut are you okay with me trying this out?

**Comment by nedn** [comment]
I don't see any problem with this. But I think we should try this out with a small audience first?

@zeptonaut maybe should work closely with you on this so he gain expertise in this area as well

**Comment by anniesullie** [comment]
Sure. Do you have any recommendation for small audience, or maybe just ping benchmark owners and see who writes back?

**Comment by nedn** [comment]
I think we can first start with memory benchmark & system_health common benchmark. They generate most volume of alerts anyway.

**Comment by anniesullie** [comment]
It might be good to also have a smaller benchmark owner on the list. It's possible we'll want a different format for benchmarks that get > 20 bugs per week vs benchmarks that get 0-2.

**Comment by nedn** [comment]
SGTM

**Comment by zeptonaut** [comment]
Sorry: somehow I missed this in the perf season. This sounds like a good plan to me, but I agree that rolling it out to a small audience would be a good start.

**Comment by anniesullie** [comment]
Script was sent to benchmark owners with good feedback; scheduled to update weekly.
