### ISSUE TITLE
[📍] Test Patch and Re-run This Job Fail

### ISSUE THREAD

**Issue by jonrossca** [catapult-project/catapult#4313]
I'm on https://pinpoint-dot-chromeperf.appspot.com/job/128650dc440000

Both Test a Patch and Re-run This Job

Lead to an error page of: 
Job undefined
Invalid job id.

I've tried both via my chromium and google accounts.

**Comment by simonhatch** [comment]
@dave2

**Comment by dave2** [comment]
Did you mean to ping me? No idea why if so :)

**Comment by simonhatch** [comment]
Nope sorry, meant @dave-2

**Comment by dave-2** [comment]
Fixed in [952093](https://chromium-review.googlesource.com/c/catapult/+/952093) and [955556](https://chromium-review.googlesource.com/c/catapult/+/955556). Let me know if you still see it.
