### ISSUE TITLE
[📍] Automatic bug de-duping from bisect results

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4319]
Sheriffs kick off lots of bisects on related similar alerts, so some CLs can have dozens of bugs/alerts associated with them. We want to automatically mark bugs as Duplicate if there's a single culprit that has been seen before in another bug.

I think this is on the dashboard side? @simonhatch

**Comment by anniesullie** [comment]
SImon, can you take a look? There's already code in the old bisect to do this, so hopefully a quick fix?

**Comment by simonhatch** [comment]
On the surface this looks pretty straightforward, think most of it is done via update_bug_results.py. I can take a look.

**Comment by simonhatch** [comment]
Tracked in crbug.com/840872
