### ISSUE TITLE
[📍] Analyze benchmark results fails with exception

### ISSUE THREAD

**Issue by sanekspot** [catapult-project/catapult#4322]
The "Analyze benchmark results" link for two different pinpoint jobs leads to an empty page. It keeps loading within a few seconds and then fails and displays a blank page.

Here's the html of the resulting page:
```
<html><head><title>s~chromeperf : uncaught application failure</title><body><pre>
  
<br></pre></body></html>
```

Links to the pinpoint jobs:
https://pinpoint-dot-chromeperf.appspot.com/job/11c37ab2440000
https://pinpoint-dot-chromeperf.appspot.com/job/12a9b5f2440000

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
Is this the kind of thing that will be fixed in https://chromium-review.googlesource.com/c/catapult/+/935146 ? (#4168)

It's a little strange because I see the 500 errors in the logs, but no exception is thrown.

**Comment by simonhatch** [comment]
Yep

**Comment by sanekspot** [comment]
It works now! Thanks for the quick fix.
