### ISSUE TITLE
[📍] Forbidden Error 403 when clicking "Analyze benchmark results"

### ISSUE THREAD

**Issue by wangxianzhu** [catapult-project/catapult#4330]
Clicking "Analyze benchmark results" in any finished pinpoint job page (e.g. https://pinpoint-dot-chromeperf.appspot.com/job/14e5632e440000), I got "Forbidden Error 403".

**Comment by dave-2** [comment]
I believe @simonhatch fixed this in c6434b02c577499932bf7ec31a9d6872c481dca2

**Comment by dave-2** [comment]
Please try again!
