### ISSUE TITLE
Perf Dashboard: Alerts not detected/issued even though large size change.

### ISSUE THREAD

**Issue by m0hamed** [catapult-project/catapult#4331]
Chrome version: 64.0.3282.186 (Linux)
URL: https://chromeperf.appspot.com/report?sid=3c0b30940c3a1df50ef9652385ac9a2ee7b7c52a98be9ed417123245455d379c&num_points=500

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
n/a

Please describe the problem:
Two alerts should have existed but were not, one at chromium commit 542396 and the other at 542061.

**Comment by simonhatch** [comment]
There are a lot of graphs on that page, do you mind specifying which one or giving a link that only has the graph in question?

**Comment by m0hamed** [comment]
It is the first graph on the page. It is named "ChromiumPerf/Android Builder/resource_sizes (MonochromePublic.apk)/MonochromePublic.apk_Specifics/normalized apk size"

**Comment by simonhatch** [comment]
Hmm that's strange, according to https://chromeperf.appspot.com/debug_alert?test_path=ChromiumPerf%2FAndroid+Builder%2Fresource_sizes+%28MonochromePublic.apk%29%2FMonochromePublic.apk_Specifics%2Fnormalized+apk+size&rev=542250&num_before=700&num_after=250&config=%7B%0D%0A++%22max_window_size%22%3A+2%2C+%0D%0A++%22min_absolute_change%22%3A+16000%2C+%0D%0A++%22min_relative_change%22%3A+0%2C+%0D%0A++%22min_segment_size%22%3A+0%0D%0A%7D we *should* be getting an alert there.

This kinda looks like a repeat of crbug.com/818035 but I won't dupe for now.

**Comment by benshayden** [comment]
818035 is fixed. Archiving.
