### ISSUE TITLE
Perf Dashboard: Error 500 when creating an issue

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#4337]
Chrome version: 65.0.3325.146 (Linux)
URL: https://chromeperf.appspot.com/group_report?sid=6438952bf43a5121d106ddb8a7166e9b42ad4544ef8aab6c8f1c846f9ca68ffb

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:
I wanted to create a bug for the given link via the Triage button. The form to create a bug appears. When I hit OK, the popup window ends into a error 500. The issue(s) are created though.

**Comment by simonhatch** [comment]
Looks like  in the case of a single cl range, we try to resolve the commit position assuming it's chromium/src. Will put up a fix.
