### ISSUE TITLE
HistogramSet - Some histograms don't have proper diagnostics

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4351]
Got exposed by uploading the dummy benchmarks which only have foo in them. Not clear if it's just the benchmark_duration or ones generated via is_summary. I *think* it's the benchmark_duration ones.

At the very least they're missing the benchmarks diagnostics, probably more.

@eakuefner

**Comment by eakuefner** [comment]
I think this is a dupe of #4244.
