### ISSUE TITLE
Pinpoint: Link to failing build

### ISSUE THREAD

**Issue by mlippautz** [catapult-project/catapult#4355]
E.g. https://pinpoint-dot-chromeperf.appspot.com/job/16e1c66d440000

It seems like pinpoint knows exactly which build on which builder is failing. It would be really helpful to have a direct link to the builder to investigate why the build was failing.

(That particular issue was trivially reproducible locally.)

**Comment by simonhatch** [comment]
@dave-2 

Possibly a dupe of #3899 ?

**Comment by dave-2** [comment]
Looks like it.

Duplicate of #3899
