### ISSUE TITLE
[📍] Make swarming "expired" a job-level error

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4367]
Since "expired" is an execution-level error, Pinpoint treats it like a test failure, meaning it will try to bisect on it. If the swarming task expired because the bots are overloaded, that will just add insult to injury. It's also unclear to the user what's going on. Instead, the job should bail out completely, which will make the error clear and reduce the bot load.

@anniesullie @simonhatch

**Comment by anniesullie** [comment]
+1 this would be great!
