### ISSUE TITLE
Tracing's color scheme is too dark for readability.

### ISSUE THREAD

**Issue by hashseed** [catapult-project/catapult#4373]
See https://bugs.chromium.org/p/chromium/issues/detail?id=828389

**Comment by hashseed** [comment]
fwiw this is the old palette vs the new suggested one:

![palettes](https://00e9e64bac88d98e901835a417dac8d55e5ff980fc60f7a1b3-apidata.googleusercontent.com/download/storage/v1/b/monorail-prod.appspot.com/o/16%2Fattachments%2F899b2c24-4e33-43ea-976b-4deb5b9f7bf0?qk=AD5uMEtiKr23q2x-IyG4SGYojsof-tNXsMm2j3YkNC7H2Mj5lFk5eOumqGqzKW4kmG2LyWr2wh47qFoGw2V2oZllxPxZJP61v58JCx2b--diD8yzQaQmnUEI7IAiYJ9i48PPetU_yUsk4ffnR57Rw1uOykpVap2m6KjAnjfgrfgwtf54GcaZJK1ZCIAoWb1WAdia_ITxJ_dtTGsRIsxre8uNLt9v4a5E4HVD9S3G_zScp2bR5tHPTsY4Q3bHgWKt-nLcDZ9YgB5Lk1bzi9iFShBymGXtvYiWuhEpXqekN-k-rfghvEzXM_qUxNHsMMDHZLhx947Jd95WkVSb5ARbZlYcRTy61Y3OxaY-_jglRXi7iu-rHmnkhZ5rnW3O-MZUEJpIMeRCepR4CLVSSjGc42aesGCplCY5B-gc7o9b-jAuAhauez23zNCuDaHKqnnKs5n4cd0uE3RddtEapLXvITVuExA3pW5b8QHpMUCncCyhJTfP_8GxLxJnLOEpFPwkACpR7bUbNqlFek800Xl7bdIGd6vS2kyC_7A5EMUZ9j5V2jLcOP3V6fpGnD6T_08faqsLnEoP8vi1kShO9QKD53xSF45k4aEEvUWrR6Hp0ktRD6nNZFW1j_p54s1gXh7JhLKDNrOOiAou4_FJQX_zMPUfbjZfCL_mmHKc8hCwtAw-lia6ws_7NUXJSnJq_XQrPz1m_mvcZRo6-bD4is_PFDPxIDW1FEIBuTJ5GYjIF025DEmjSvsBt-lG-WlVec46beWyPpDsIE1MIPINpKlO9VhMpSTbVYFu6g)

**Comment by hashseed** [comment]
This has been fixed.

**Comment by vnoe** [comment]
Readability of the entries is highly improved by the new color scheme, however, if an entry is highlighted you can barely make out which one.
