### ISSUE TITLE
Histograms should be elided if there were failures

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4376]
For chartjson, I think we don't generate the summary statistic if there are pages missing (is that right), but histograms will always create the summary from whatever pages happen to be there. What should we do here?

@eakuefner

**Comment by eakuefner** [comment]
We want to emulate the existing behavior, which is that if there are stories missing, we don't emit the histogram.

**Comment by eakuefner** [comment]
The plan here is to plumb had_failures through Telemetry info and just filter these out for now in add_reserved_diagnostics.
