### ISSUE TITLE
Histogram pipeline coalesces histograms instead of averaging averages

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4379]
HistogramSet computes summary statistics by merging histogram sample_values
ChartJSON computes them (I think) by averaging the averages from each page.

Should at least highlight this behaviour in differences doc. Error is also quite a bit different because of this.

@eakuefner

**Comment by eakuefner** [comment]
We decided that this difference is expected, let's talk through it with benchmarking team in ARB next week.

**Comment by eakuefner** [comment]
We spoke to @nedn and @ehanley324 and discussed the idea that we should just get rid of summary values eventually, but until then these numerical differences don't matter much.
