### ISSUE TITLE
Dashboard - Handling tir_labels incorrectly on /add_histograms

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4380]
https://chromeperf.appspot.com/report?sid=41e8377ec2fcf5a655e4611925dda666f186b087d44426ddeaee4ac1e7b8db2b

Chartjson has both [cold, warm] under timeToFirstContentfulPaint_avg

ChromiumPerfFyi/histogram-diff-chartjson-20/loading.desktop / timeToFirstContentfulPaint_avg / cold

Whereas histograms seems to mash them together for some reason:

ChromiumPerfFyi/histogram-diff-histograms-20/loading.desktop / timeToFirstContentfulPaint / cold_warm

@eakuefner

**Comment by eakuefner** [comment]
We need to set IS_SUMMARY for all the merged histograms to fix this bug.

**Comment by eakuefner** [comment]
This has been fixed by the same fix for #4387
