### ISSUE TITLE
Histograms - Some benchmark_total_duration have a bunch of stats

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4381]
Ie. https://chromeperf.appspot.com/report?sid=a38a4fd96d6be0707a990abbde2a10bafb2155c9ca3438114b6a8b8b885f548a

tab_switching.typical_25 has _avg, _count, _std, _sum, _count, _min, _max

@eakuefner

**Comment by eakuefner** [comment]
We'll fix this on the dashboard side by blacklisting benchmark_total_duration explicitly.

**Comment by eakuefner** [comment]
This is done.
