### ISSUE TITLE
Histograms - No summary statistics for tir_labels

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4387]
Moving this to it's own issue. Summary statistics are created for top level metrics, ie.

M/B/S/foo

but not for nested

M/B/S/foo/bar

@eakuefner

**Comment by eakuefner** [comment]
This has been broken out from #4378

**Comment by eakuefner** [comment]
This is actually not a bug, because we would expect summaries of the first form for benchmarks that do not use tags, and the second form for those that do.

**Comment by eakuefner** [comment]
This actually isn't fixed; the problem is that we don't emit summaries of the form M/B/S/foo/bar for benchmarks that use tags, because we currently don't consider tags when merging.

**Comment by eakuefner** [comment]
This is fixed.
