### ISSUE TITLE
Add support for URL tuples to generic-set-span

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4397]
Basically, we should add BUILDS to the add_reserved_diagnostics call in the recipe, and then plumb  BUILDS in /add_histograms.

**Comment by eakuefner** [comment]
Okay, so this is actually appearing in the data set, just some corner case in graph_json.py is preventing this from working completely properly. We should just modify graph_json to make this work in the sane case.

**Comment by eakuefner** [comment]
This turned out to be a little more complicated than originally anticipated. As it happens, the `a_` columns are always Markdown-formatted links. The easiest way of making this work is to allow tuples of [name, url] on the GenericSet side that we then squash to Markdown in /add_histograms. So to make this work, we need to:

1. Modify the recipe and the src-side OBBS script to add these tuples instead of plain URLs
2. Modify /add_histograms to munge these tuples into Markdown links for storage as annotations (this will fix this bug)
3. Add support to generic_set_span for rendering link tuples.

**Comment by eakuefner** [comment]
Having completed quite a lot of traveling and meetings, I expect to finally crack this today. I'm going to do step 2 (Catapult-side) first so that the Dashboard knows what to do with these tuple URLs once we start producing them, then do step 1 (which necessarily has to be done as two separate patches to the recipe and to the merge script, which lives in src/), then do step 3 as a followup.

**Comment by eakuefner** [comment]
After the src- and recipe-side changes cycle through to the bots, we should also add an assert that makes sure that LOG_URLS diagnostics only contain URL tuples. It might also be a good idea to add such functionality when addressing #3770.

**Comment by eakuefner** [comment]
This is **fixed**.

**Comment by eakuefner** [comment]
Reopening, forgot to add support to generic-set-span for this. Will queue that up.

**Comment by eakuefner** [comment]
@benshayden Assigning this over to you; all that's left to do is add support for parsing URL tuples to generic-set-span.

**Comment by benshayden** [comment]
https://chromium-review.googlesource.com/c/catapult/+/1392448
