### ISSUE TITLE
[📍] Pinpoint assigned blame to a change in that improved the metric

### ISSUE THREAD

**Issue by chcunningham** [catapult-project/catapult#4404]
On this pinpoint run, many cls were considered as possible culprits. The tool called that out in the chromium bug, but assigned the bug to the least likely culprit - one that actually improved the metric.

![image](https://user-images.githubusercontent.com/12039355/38710897-66e42d9c-3e77-11e8-98c0-6e4dab0101c1.png)

Pinpoint run: https://pinpoint-dot-chromeperf.appspot.com/job/14babd5cc40000
chromium bug: http://crbug.com/828286

**Comment by simonhatch** [comment]
This is a known issue that we're hoping to address soon: #4123
