### ISSUE TITLE
Dashboard - Remove code/command_line from TestMetadata?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4405]
I don't see any references in the code to these.

@anniesullie @eakuefner

**Comment by anniesullie** [comment]
Places it *could be* used:
  * Telling pinpoint which command to run
  * Telling CL authors how to reproduce locally

I'm skeptical that the current implementation is the best way to achieve either of these goals.

**Comment by simonhatch** [comment]
Yeah those could definitely be useful, but don't want to keep them around in case we might use them. If they're not being used right now, I'd vote to delete them and add/re-add whatever we need once we've figured out what Pinpoint needs.

**Comment by anniesullie** [comment]
sgtm
