### ISSUE TITLE
Dashboard - Need more warnings on migration page.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4407]
For crbug.com/831328 I was asked to migrate the data from the old builder to the new builder, pretty straightforward but I still managed to botch it up.

Looks like the data is sitting 1 level higher than I expected, https://chromeperf.appspot.com/report?sid=ca54cf9c3996d931ad0f0b45f622adcca9bcd880d178abd40b81fbd634e5e3db&num_points=1500

So moving:

ChromiumPerf/Android Builder/resource_sizes (MonochromePublic.apk)/MonochromePublic.apk_Specifics/normalized apk size

to

ChromiumPerf/Android Builder Perf/resource_sizes (MonochromePublic.apk)/MonochromePublic.apk_Specifics/normalized apk size

But it's actually all sitting on:

ChromiumPerf/Android Builder Perf/resource_sizes (MonochromePublic.apk)/normalized apk size

Don't know how I managed to do that, but would be great to have some more warnings or output showing where things will be migrated to.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=918181
