### ISSUE TITLE
Dashboard - Still need set_warning_message?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4418]
I just found this, never saw it before and don't recall ever seeing a warning on the dashboard. Should we keep this?

@eakuefner @anniesullie

**Comment by anniesullie** [comment]
The original idea was that it could be used to inform users of outages (bisect is down for these bots, perf dashboard isn't showing this data, perf waterfall is having an outage). It hasn't been used for that purpose in at least 2 years.

I think we should remove it, and re-implement in the UI if we see a need for it later.
