### ISSUE TITLE
Dashboard - oauth2_decorator and api_auth

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4419]
Have 2 ways for oauth right now, wonder if we can merge these.

@eakuefner @anniesullie

**Comment by benshayden** [comment]
V2SPA currently copies pinpoint's use of the google-signin component, which works with api_auth but not oauth2_decorator, iiuc.

oauth2_decorator is currently only used by associate_alerts, bug_detail, file_bug. V2SPA currently merges that functionality into /api/alerts, so oauth2_decorator and its callers can simply be deleted when the V1 UI is removed.

**Comment by simonhatch** [comment]
Oh neat, so I'll leave this alone then :)

**Comment by benshayden** [comment]
Closing: I don't think we'll forget to remove legacy code when v2spa is stable.
