### ISSUE TITLE
v2spa doesn't display cats when all alerts are triaged

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4420]
Without cats, why would I triage alerts?

**Comment by simonhatch** [comment]
This is a p0.

**Comment by tdresser** [comment]
Last time cats broke on the v1 alerts page, I seem to remember that @anniesullie had a fix up in an hour or two. 

This is important stuff.

**Comment by benshayden** [comment]
:100:

**Comment by tdresser** [comment]
Y'all are the best.
