### ISSUE TITLE
Range Selector in chart view - what's it for?

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4424]
If I click on a point in a chart, the range selection widget shows up for the main chart. I'm not sure what this does, but it doesn't appear to work currently.

**Comment by benshayden** [comment]
Yep, it isn't implemented yet, but it should fetch the full histograms for the brushed points and display them in a results.html-like pivot table below the chart. All histograms in a brushed range will be merged together into a single column, and you'll be able to select multiple ranges to construct multiple columns for comparison by holding down the control key. I'll write more about this in go/chromeperf-v2 and share it with you.

**Comment by tdresser** [comment]
Awesome!
