### ISSUE TITLE
Dashboard - /new_points?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4425]
From #3360 ran into this removing Row from the internal only kind list in datastore_hooks. Can't say I've ever used this page, or even recall ever seeing it, any idea what it's used for? If it's still useful, I can see about making it work with just the internal_only info from TestMetadata.

@anniesullie @eakuefner

**Comment by anniesullie** [comment]
It was added to help new dashboard clients check that their uploads are working correctly. If @simonhatch and @eakuefner aren't directing new clients there, I think it's fine to remove. If it's not removed, it should be updated for HistogramSet.
