### ISSUE TITLE
Alert not showing

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4433]
Internal bot
power.​typical​_10​_mobile

(index):26077 undefined TypeError: Cannot read property 'xPct' of undefined
    at ChartPair.reducers.dotClick ((index):39282)
    at Polymer.Path.setImmutable.state ((index):26071)
    at setImmutableInternal_ ((index):25892)
    at setImmutableInternal_ ((index):25898)
    at setImmutableInternal_ ((index):25898)
    at setImmutableInternal_ ((index):25898)
    at Object.Polymer.Path.setImmutable ((index):25926)
    at ElementBase.statePathReducer.wrapper ((index):26069)
    at rootReducer ((index):25957)
    at a ((index):11525) {type: "ChartPair.reducers.dotClick", statePath: "chromeperfApp.alertsSection.preview", ctrlKey: false, lineIndex: 1, datumIndex: undefined} {chromeperfApp: {…}, userEmail: "tdresser@chromium.org", testSuites: Array(204), testSuiteDescriptors: {…}, testSuiteDescriptorsInternal: {…}, …}
ElementBase.statePathReducer.wrapper @ (index):26077
rootReducer @ (index):25957
a @ (index):11525
action @ (index):25967
dispatch @ (index):11727
(anonymous) @ (index):11717
ChartPair.actions.dotClick @ (index):39093
ElementBase.action.wrapper @ (index):26145
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
onDotClick_ @ (index):38841
eventListenerWrapper @ (index):26116
handler @ (index):1701
onDotClick_ @ (index):29796
eventListenerWrapper @ (index):26116
handler @ (index):1701
_methodHost._addEventListenerToNode @ (index):9164
_fire @ (index):6081
forward @ (index):6429
click @ (index):6398
_handleNative @ (index):5878
(index):11806 Uncaught (in promise) TypeError: Cannot read property '3' of undefined
    at Object.dummyHistograms ((index):11806)
    at ChartPair.actions.dotClick ((index):39106)
    at ElementBase.action.wrapper ((index):26145)
    at action ((index):11719)
    at Object.action [as dispatch] ((index):25964)
    at HTMLElement.dispatch ((index):11727)
    at HTMLElement.onDotClick_ ((index):38841)
    at HTMLElement.eventListenerWrapper ((index):26116)
    at HTMLElement.handler ((index):1701)
    at HTMLElement.onDotClick_ ((index):29796)
dummyHistograms @ (index):11806
ChartPair.actions.dotClick @ (index):39106
ElementBase.action.wrapper @ (index):26145
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
onDotClick_ @ (index):38841
eventListenerWrapper @ (index):26116
handler @ (index):1701
onDotClick_ @ (index):29796
eventListenerWrapper @ (index):26116
handler @ (index):1701
_methodHost._addEventListenerToNode @ (index):9164
_fire @ (index):6081
forward @ (index):6429
click @ (index):6398
_handleNative @ (index):5878
async function (async)
ElementBase.action.wrapper @ (index):26143
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
onDotClick_ @ (index):38841
eventListenerWrapper @ (index):26116
handler @ (index):1701
onDotClick_ @ (index):29796
eventListenerWrapper @ (index):26116
handler @ (index):1701
_methodHost._addEventListenerToNode @ (index):9164
_fire @ (index):6081
forward @ (index):6429
click @ (index):6398
_handleNative @ (index):5878
(index):11848 TODO handle non-numeric revisions
(index):30367 GET https://v2spa-dot-chromeperf.appspot.com/api/timeseries2?testSuite=power.typical_10_mobile&measurement=application_energy_consumption_mwh&bot=redacted&statistic=avg&buildType=reference&columns=revision%2Cr_commit_pos%2Ctimestamp%2Cvalue 404 ()
fetch_ @ (index):30367
async function (async)
fetch_ @ (index):30358
get response @ (index):30349
completion @ (index):37136
fetch_ @ (index):37139
read @ (index):30454
ReadTimeseries @ (index):37283
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
(anonymous) @ (index):11717
Promise.all.fetchDescriptors.map @ (index):38100
ChartTimeseries.actions.fetchLineDescriptor @ (index):38098
ElementBase.action.wrapper @ (index):26145
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
(anonymous) @ (index):11717
ChartTimeseries.actions.loadLineDescriptor_ @ (index):38111
ElementBase.action.wrapper @ (index):26145
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
(anonymous) @ (index):11717
Promise.all.state.lineDescriptors.map.lineDescriptor @ (index):38085
ChartTimeseries.actions.load @ (index):38084
ElementBase.action.wrapper @ (index):26145
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
debounce @ (index):37976
_timer._asyncModule.run @ (index):5465
microtaskFlush @ (index):908
characterData (async)
run @ (index):1047
setConfig @ (index):5463
debounce @ (index):5530
__debounceRender @ (index):10511
runObserverEffect @ (index):2258
runEffectsForProperty @ (index):2206
runEffects @ (index):2173
_propertiesChanged @ (index):3630
_flushProperties @ (index):1567
__enableOrFlushClients @ (index):3535
_flushClients @ (index):3511
_propertiesChanged @ (index):3626
_flushProperties @ (index):1567
_invalidateProperties @ (index):3479
update @ (index):11604
(anonymous) @ (index):11610
a @ (index):11525
action @ (index):25967
dispatch @ (index):11727
(anonymous) @ (index):11717
AlertsTable.actions.selectAlert @ (index):26777
ElementBase.action.wrapper @ (index):26145
action @ (index):11719
action @ (index):25964
dispatch @ (index):11727
onSelect_ @ (index):26729
eventListenerWrapper @ (index):26116
handler @ (index):1701
_methodHost._addEventListenerToNode @ (index):9164
_fire @ (index):6081
forward @ (index):6429
click @ (index):6398
_handleNative @ (index):5878

**Comment by benshayden** [comment]
Clicking a dot brushes around it, which will fetch the full Histograms and display them in a table, when implemented. I'll clean up the dotClick methods and add null checks for now.
Thanks for reporting!
