### ISSUE TITLE
[📍] Pinpoint can't find the isolate hash

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#4438]
I've recently run into quite a few issues with bisects not running properly and failing without a possibility for me to investigate.

Error Message: Buildbucket says the build completed successfully, but Pinpoint can't find the isolate hash.
Affected issues: https://bugs.chromium.org/p/chromium/issues/list?can=2&q=%22Pinpoint+can%27t+find+the+isolate+hash%22

**Comment by camillobruni** [comment]
This is probably related to the linux-perf bot.

**Comment by simonhatch** [comment]
@dave-2 There were a bunch of name changes that happened in the last 2 weeks, we're working our way through the issues.

**Comment by dave-2** [comment]
This is tracked in Chromium at https://bugs.chromium.org/p/chromium/issues/detail?id=836037#c26 and is now fixed, but we are still unable to bisect on `linux-perf` before [r554597](https://crrev.com/554597).
