### ISSUE TITLE
Pinpoint - Surface build link

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4444]
Buildbucket provides the url of the builder, we should surface this in the UI.

status = buildbucket_service.GetJobStatus('foo')
print status['build']['url']

http://build.chromium.org/p/tryserver.chromium.perf/builders/Mac%20Builder%20Perf/builds/178

@dave-2 @wangxianzhu

**Comment by dave-2** [comment]
Duplicate of #3899
