### ISSUE TITLE
Perf Dashboard request: Remove particular outliers from the view

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#4452]
Chrome version: 66.0.3359.170 (Mac)
URL: https://chromeperf.appspot.com/report?sid=4b408af1644b74e7ff8c58244b985f7d4855474d8a85f040a8f08fcfb51eb3da&start_rev=547687&end_rev=554730

Please describe the problem:

Can we please somehow remove the attached outlier from the view somehow? It makes our dashboards worthless, because we don't see any movement on the graphs.
<img width="690" alt="screen shot 2018-05-16 at 15 04 59" src="https://user-images.githubusercontent.com/7190422/40119555-495da08a-591d-11e8-962b-2bf3dd8f9d5e.png">

**Comment by benshayden** [comment]
@simonhatch Can you delete() these Rows?

**Comment by simonhatch** [comment]
Yep, I actually did a pass for a separate bug, but some slipped through.

**Comment by benshayden** [comment]
Looks like these were fixed
