### ISSUE TITLE
Perf Dashboard: Some data seems to be lost

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#4453]
Chrome version: 66.0.3359.170 (Mac)
URL: https://chromeperf.appspot.com/report?sid=a20da9037c75ec4d1a27eb99861d7fd1ba5a9c67055fab6697d3f1e77fa0a77b

When I open the mentioned report above, the first data point comes from the 15th May. The benchmark is much older though and should have older data too. 

The new dashboard shows the data just fine, so I assume this is some UI issue with the old dashboard?

There are no errors on the JS console btw.

Please describe the problem:

**Comment by benshayden** [comment]
[Make sure the measurement ends with "_avg"](https://chromeperf.appspot.com/report?sid=3f8d7a9a2594e1e7b11bda51b582f6d85f323af990b469fd3e2e1a4d1987758a). The [new UI](https://v2spa-dot-chromeperf.appspot.com/#session=1db6fc7cedffe68103e05feaa4e521c50028baa55aacdb8151d6857ec196dd7c) hides the distinction.
