### ISSUE TITLE
[📍] Use looser thresholds for flaky functional tests.

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4459]
Perf regressions that perf dashboard can detect tend to be at least 2 standard deviations.
Flaky test failures can be quite small in comparison. 0% failing -> 10% failing ~= 0.3 standard deviations (http://crbug.com/842163#c4)

Using higher significance thresholds give the algorithm more leeway to run more repeats and find smaller regressions. The con is that we may expend extra bot resources on chasing after noise.

So maybe we want separate functional test thresholds that are tuned for running many more repeats to find these much smaller regressions.

@zeptonaut @simonhatch @perezju @anniesullie

**Comment by zeptonaut** [comment]
:+1: As a bot health sheriff, it can be really frustrating to see an obvious uptick in flakiness but be unable to bisect it.

**Comment by dave-2** [comment]
Following the research in #4508, we can use a similar technique to calculate the thresholds for functional bisects. But I also realized that for functional results, we don't have to run many simulations to determine the right thresholds.

Each pass/fail result is a Bernoulli trial, and the Binomial distribution is the probability of achieving n successes out of N Bernoulli trials. If we know our desired p-value in advance (0.01 in this case), we can look up from the Binomial distribution exactly what set of passes/failures has that probability of occurring.

```python
from scipy import stats

def Threshold(p_value, repeat_count):
  count = max(0, int(stats.binom(repeat_count, P).ppf(p_value)))
  return _Mwu((repeat_count, 0), (repeat_count - count, count))

def _Mwu(a, b):
  try:
    return stats.mannwhitneyu([0] * a[0] + [1] * a[1], [0] * b[0] + [1] * b[1]).pvalue * 2
  except ValueError:
    return 1.0
```

**Comment by perezju** [comment]
Ahh! That's true, well spotted!

**Comment by dave-2** [comment]
Done!
https://chromium-review.googlesource.com/c/catapult/+/1105057
