### ISSUE TITLE
Starting a new pinpoint task broken

### ISSUE THREAD

**Issue by sadrulhc** [catapult-project/catapult#4464]
When trying to add a new task from https://pinpoint-dot-chromeperf.appspot.com/, after filling out the gerrit URL, selecting a bot, and entering the benchmark name, clicking 'Start' fails with the following error: '__init__() got an unexpected keyword argument 'scope''

**Comment by simonhatch** [comment]
Thanks, will take a look after this dashbaord issue.

**Comment by simonhatch** [comment]
Looks like same root cause as the dashboard issue, #4465 , CL out for review.

**Comment by simonhatch** [comment]
Deployed version of dashboard works and pinpoint jobs start, closing.

**Comment by sadrulhc** [comment]
Thank you for the quick fix!
