### ISSUE TITLE
Build and test succeeds, but fails to find values

### ISSUE THREAD

**Issue by schuay** [catapult-project/catapult#4484]
See https://pinpoint-dot-chromeperf.appspot.com/job/12d94d42240000.

The error message is

```
  raise ReadValueError('Could not find values matching: %s' % conditions)
ReadValueError: Could not find values matching: {'story': u'browse:media:flickr_infinite_scroll', 'tir_label': u'browse_media', 'histogram': u'v8-gc-full-mark-compactor'}
```

**Comment by dave-2** [comment]
I looked at the output histograms, and though the test always passes, it only sometimes produces the `v8-gc-full-mark-compactor` metric. I filed a bug on the benchmark owners in Chromium: [issue 847994](https://bugs.chromium.org/p/chromium/issues/detail?id=847994)
