### ISSUE TITLE
"Tracing Dev Server Tests Canary" is using very old chrome

### ISSUE THREAD

**Issue by wangxianzhu** [catapult-project/catapult#4487]
My CL failed the CQ bot because the chrome used for testing doesn't support a new feature (ResizeObserver): https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/10822.

It's still using 62.0.3194.0 as the "canary".

**Comment by wangxianzhu** [comment]
I found the script to update reference builds, and I would like to update the reference builds by myself, but I need to make clear about the following questions:

- What's the policy of reference build updating?
- Is it intended that the canary references are older than the stable references?

**Comment by nedn** [comment]
@benshayden @eakuefner do we absolutely need the canary for tracing dev server? If not, I suggest we just use the reference build for testing.


@wangxianzhu for reference build updating, you can do them now if you want. We don't have a strict policy on it.

**Comment by eakuefner** [comment]
It'd be nice to run the viewer tests on something close to ToT, but as long as Canary isn't being rolled anywhere close to every day, I think it's not useful. +1 to getting rid of Canary.

**Comment by wangxianzhu** [comment]
I have updated the reference builds of all channels in https://chromium-review.googlesource.com/c/catapult/+/1071122. It also enables dev and canary channel updates in common/bin/update_chrome_reference_binaries. As long as the canary/dev references are updated periodically along with the stable channel, I think it's fine to keep the canary try jobs.
