### ISSUE TITLE
Pinpoint - New job dialog bot dropdown is empty

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4496]
Reported by rsesek

@dave-2

**Comment by dave-2** [comment]
I had moved the configs from public to internal for the upcoming move to chrome-swarming. I can put it back but we'll need to figure out some way to do external/internal. It's probably fine if the configuration list is external, but we need to ensure only internal users can kick off jobs. Filed #4497.

**Comment by simonhatch** [comment]
Can you not do a check on the user and return the appropriate bot list, and/or grey out the new job button when they don't have permission?

**Comment by dave-2** [comment]
Yes, but for external users, the list is empty. So would it be WAI?

**Comment by simonhatch** [comment]
Maybe we can grey out the button or do something to indicate they're not logged in/don't have permission.

**Comment by dave-2** [comment]
We can do that. --> #4497
