### ISSUE TITLE
[📍] Job terminated and reported a difference earlier than needed

### ISSUE THREAD

**Issue by sanekspot** [catapult-project/catapult#4501]
This job tested only two commits: 532803 and 533628 and reported that the last one is a culptrit without testing anything between these commits.

https://pinpoint-dot-chromeperf.appspot.com/job/12d77e01240000

**Comment by simonhatch** [comment]
@dave-2 Any idea what's going on here? From a glance, the commit positions are 800 apart.

**Comment by dave-2** [comment]
Not sure what happened here. I put this into the dev console and it continued running as expected, adding an additional commit to the list. I don't think there were any changes in this area recently, so that would imply some kind of transient error.

```
from dashboard.pinpoint.models import job
j = job.JobFromId('12d77e01240000')
j.Run()
```

**Comment by simonhatch** [comment]
That's really strange, since it commented on the bug, it presumably thought it was done.

**Comment by dave-2** [comment]
Yes, that means it did detect a difference, but unable to take the midpoint between the two commits. Maybe Gitiles produced an empty commit range or some other unexpected output?

**Comment by dave-2** [comment]
https://chromium-review.googlesource.com/c/catapult/+/1093724
