### ISSUE TITLE
Chrome perf /bugs/%d API call returns 500 Server error

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#4502]
From soundwave, requests e.g. to https://chromeperf.appspot.com/api/bugs/844643 are returning with:

```
  File "./soundwave/dashboard_api.py", line 172, in GetBugData
    yield self._MakeApiRequest('bugs/%d' % bug_id)
  File "../../common/py_utils/py_utils/retry_util.py", line 55, in Wrapper
    return f(*args, **kwargs)
  File "./soundwave/dashboard_api.py", line 128, in _MakeApiRequest
    raise BuildRequestError(request, resp, content)
ServerError: https://chromeperf.appspot.com/api/bugs/844643 returned HTTP Error 500:
500 Internal Server Error

The server has either erred or is incapable of performing the requested operation.
```

@simonhatch Any idea what is going on from the dashboard side?

**Comment by simonhatch** [comment]
Lemme look

**Comment by simonhatch** [comment]
Somehow some of these bisects never ran, and have a None last_ran_timestamp.

**Comment by simonhatch** [comment]
Weird, the cl never showed up here but the fix landed a few hours ago: https://chromium-review.googlesource.com/c/catapult/+/1091073

Redeploying dashboard now.

**Comment by perezju** [comment]
Thanks! Confirmed this now works for me.

**Comment by perezju** [comment]
Happening again, this time hitting: https://chromeperf.appspot.com/api/bugs/830736

**Comment by simonhatch** [comment]
Looking

**Comment by simonhatch** [comment]
Looks like we're hitting a rate limit from monorail

<HttpError 400 when requesting https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues/841231?alt=json returned "RateLimitExceeded:....

**Comment by perezju** [comment]
Hmm.. any idea what the rate limits are? As to possible solutions:

- We already have some caching in soundwave, we could be using it a bit more aggressively for bugs on which we have not-so-old data.
- Query for bugs at a slightly lower rate to avoid hitting those limits.
- Query for multiple bugs at a time, would that help?

**Comment by simonhatch** [comment]
No unfortunately not, going to file a crbug to see if we can find out and maybe get them bumped up a bit or something

**Comment by simonhatch** [comment]
That is https://bugs.chromium.org/p/monorail/issues/detail?id=3919, other link leads to some ancient chromium bug.

Yes, making comments optional sgtm.

**Comment by perezju** [comment]
Ups! Updated my comment too to point to the correct issue.

**Comment by benshayden** [comment]
This looks done?
