### ISSUE TITLE
Dashboard - Row indexes value?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4504]
Should we be indexing this?

@anniesullie @benshayden @eakuefner

**Comment by benshayden** [comment]
I think Row.value can be de-indexed.

**Comment by eakuefner** [comment]
@benshayden and I saw this yesterday as well; let's stop indexing it.

**Comment by simonhatch** [comment]
Sweet, the built-in index for Row is 13.5 TB

**Comment by simonhatch** [comment]
Update, these are used in projection queries over rows and must be indexed. Likely can't remove the index here unless we want to remove the projection query as well.
