### ISSUE TITLE
[📍] Run bisect with pinned commit instead of patch

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4517]
Right now we only support pinned patches. We want to support pinned commits too.

**Comment by tdresser** [comment]
Just making sure there's some movement on this. I'm currently blocking crbug.com/854605 on it.

**Comment by dave-2** [comment]
I got a little bit stuck with this, but was able to deploy an experimental version to move forward on [chromium:854605](https://bugs.chromium.org/p/chromium/issues/detail?id=854605). Unfortunately, we ran into other issues ([comment 30](https://bugs.chromium.org/p/chromium/issues/detail?id=854605#c30)).

And then ultimately realized we didn't need this after all ([comment 31](https://bugs.chromium.org/p/chromium/issues/detail?id=854605#c31)).
