### ISSUE TITLE
[📍] Error status code 500 accessing completed job

### ISSUE THREAD

**Issue by mrego** [catapult-project/catapult#4524]
Trying to access this job https://pinpoint-dot-chromeperf.appspot.com/job/12ec6803240000 I got:
```
Job 12ec6803240000
Error: The request failed with status code: 500
```

**Comment by mrego** [comment]
Same problem in a new job https://pinpoint-dot-chromeperf.appspot.com/job/100a7db3240000

**Comment by simonhatch** [comment]
@dave-2

**Comment by mrego** [comment]
And the same thing today https://pinpoint-dot-chromeperf.appspot.com/job/12b6c467240000

**Comment by fsamuel** [comment]
I'm experiencing the same issue over and over again!

**Comment by dave-2** [comment]
Fixed!
