### ISSUE TITLE
Use dashboard.api.utils to uniformly parse api params

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#4530]
For example the new `ParseBool` allows to robustly parse things like `'true'` and `'False'` into their corresponding bool values.

This is already used by `/bugs` API and should be also used by `/alerts`.

@simonhatch @benshayden @eakuefner

**Comment by benshayden** [comment]
[Done](https://chromium-review.googlesource.com/c/catapult/+/1128244/)
