### ISSUE TITLE
[📍] 'Pinpoint can't find the isolate hash'

### ISSUE THREAD

**Issue by sadrulhc** [catapult-project/catapult#4535]
Job link: https://pinpoint-dot-chromeperf.appspot.com/job/14faefe2a40000

The job failed, with error saying something like: 'buildbucket says build was successful, but pinpoint can't find the isolate hash' (I would copy-paste the error and stack-trace, but I can't find a way to actually make a copy since it only shows up on hover on 'Error').

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
This is because of the isolate migration from `telemetry_perf_tests` to `performance_test_suite`. The fixes are committed, let me just deploy a new perf dashboard.

**Comment by sadrulhc** [comment]
Hi! This seems to be still happening: https://pinpoint-dot-chromeperf.appspot.com/job/1430cdd4a40000

**Comment by dave-2** [comment]
Now being tracked in Chromium [issue 862654](https://bugs.chromium.org/p/chromium/issues/detail?id=862654)
