### ISSUE TITLE
Enable sorting by alert group size

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4540]
When I see "5 bazillion alerts", I find it demotivating.

Especially when the number of alerts is really big, it's heartening to see that number decrease rapidly, which is most easily achieved by triaging large groups first.

I'm not sure if this actually makes me more productive, but for inexplicable psychological reasons, it makes me a happier person.

**Comment by benshayden** [comment]
I'd considered adding this and now I definitely will. Thanks!

**Comment by tdresser** [comment]
A somewhat more rational justification for this, at least with the old workflow.

My workflow is actually fairly different for groups with > 1 entry.

Anything with > 1 entry, I'll view a single group at a time. For groups with a single entry, I'll view a set of ~10 of them at once (at least with the old UI).

Being able to process all single entry groups consecutively would make this process a bit smoother.

**Comment by benshayden** [comment]
[Done!](https://v2spa-dot-chromeperf.appspot.com/#sheriff=Chromium_Perf_Sheriff&sort=count)
