### ISSUE TITLE
Perf Dashboard V2 - working while creating new bug

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4541]
My current workflow:
1. Check boxes.
2. Observe graphs.
3. File bug.
4. While bug is being filed (indicated by the loading indicator, check more boxes.
5. Begin observing graphs.
6. The bug finishes being filed, clearing the set of checked boxes.
7. Return to step 1 (rechecking the boxes I checked in step 4).

**Comment by benshayden** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=918198
