### ISSUE TITLE
Perf Dashboard: view all alerts for a revision

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4543]
Sometimes there's a specific revision that is causing a ton of alerts. It would be nice to view all alerts with a specific regression in range, and then triage them.

Right now, engineers who land patches which trigger large numbers of alerts go through a pretty painful process...

**Comment by simonhatch** [comment]
There is https://chromeperf.appspot.com/group_report?rev=569223, does that do what you want?

**Comment by tdresser** [comment]
Hmmm, I want to exclude improvements, but otherwise that's pretty close.

**Comment by benshayden** [comment]
[Moved to crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=914090) to track this feature in v2spa.
