### ISSUE TITLE
Dashboard V2 - sometimes alerts fail to appear

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4544]
Example here:
https://v2spa-dot-chromeperf.appspot.com/#testSuite=system_health.memory_mobile&measurement=memory%253Awebview%253Aall_processes%253Areported_by_chrome%253Amalloc%253Aeffective_size&bot=ClankInternal%253Ahealth-plan-webview-phone&testCase=load%253Anews%253Anytimes&maxRev=573712

Example console dump:
GET https://v2spa-dot-chromeperf.appspot.com/api/timeseries2?testSuite=system_health.memory_mobile&measurement=memory%3Awebview%3Aall_processes%3Areported_by_chrome%3Amalloc%3Aeffective_size&bot=ClankInternal%3Ahealth-plan-webview-phone&testCase=load%3Anews%3Anytimes&statistic=avg&buildType=reference&columns=revision%2Cr_commit_pos%2Ctimestamp%2Cvalue 404 ()
fetch_ @ (index):16679
async function (async)
fetch_ @ (index):16672
get response @ (index):16663
completion @ (index):21770
fetch_ @ (index):21773
read @ (index):16752
ReadTimeseries @ (index):21913
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
(anonymous) @ (index):5990
Promise.all.fetchDescriptors.map @ (index):22546
ChartTimeseries.actions.fetchLineDescriptor @ (index):22544
ElementBase.action.wrapper @ (index):12836
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
(anonymous) @ (index):5990
ChartTimeseries.actions.loadLineDescriptor_ @ (index):22557
ElementBase.action.wrapper @ (index):12836
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
(anonymous) @ (index):5990
Promise.all.state.lineDescriptors.map.lineDescriptor @ (index):22533
ChartTimeseries.actions.load @ (index):22532
ElementBase.action.wrapper @ (index):12836
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
debounce @ (index):22425
_timer._asyncModule.run @ (index):2509
microtaskFlush @ (index):471
characterData (async)
run @ (index):519
setConfig @ (index):2507
debounce @ (index):2533
debounce @ (index):12731
observeLineDescriptors_ @ (index):22424
runObserverEffect @ (index):1115
runEffectsForProperty @ (index):1094
runEffects @ (index):1075
_propertiesChanged @ (index):1756
_flushProperties @ (index):660
_flushProperties @ (index):1701
_invalidateProperties @ (index):1690
update @ (index):5915
(anonymous) @ (index):5921
a @ (index):5864
action @ (index):12683
dispatch @ (index):6000
(anonymous) @ (index):5990
(anonymous) @ (index):12881
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
(anonymous) @ (index):5990
ChartPair.actions.load @ (index):23448
async function (async)
ChartPair.actions.load @ (index):23382
ElementBase.action.wrapper @ (index):12836
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
observeLineDescriptors_ @ (index):23240
runObserverEffect @ (index):1115
runEffectsForProperty @ (index):1094
runEffects @ (index):1075
_propertiesChanged @ (index):1756
_flushProperties @ (index):660
_flushProperties @ (index):1701
_invalidateProperties @ (index):1690
update @ (index):5915
(anonymous) @ (index):5921
a @ (index):5864
action @ (index):12683
dispatch @ (index):6000
(anonymous) @ (index):5990
(anonymous) @ (index):12881
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
(anonymous) @ (index):5990
AlertsSection.actions.layoutPreview @ (index):25565
ElementBase.action.wrapper @ (index):12836
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
(anonymous) @ (index):5990
AlertsSection.actions.maybeLayoutPreview @ (index):25582
ElementBase.action.wrapper @ (index):12836
action @ (index):5992
action @ (index):12680
dispatch @ (index):6000
onSelected_ @ (index):25165
eventListenerWrapper @ (index):12807
handler @ (index):896
onSelect_ @ (index):13371
eventListenerWrapper @ (index):12807
handler @ (index):896
_methodHost._addEventListenerToNode @ (index):4552
_fire @ (index):2945
forward @ (index):3196
click @ (index):3178
_handleNative @ (index):2819

**Comment by benshayden** [comment]
The console dump indicates that a ref-build timeseries was 404 not found, which is normal.
The health-plan-webview-phone bot appears to be deprecated.
I'll close this and keep working on debugging charts as I land them in master.
