### ISSUE TITLE
Dashboard V2: Sometimes graphs fail to show

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4545]
No error is shown in the console.

e.g., https://v2spa-dot-chromeperf.appspot.com/#testSuite=system_health.common_desktop&measurement=cpu_time_percentage&testCase=load%253Aaccessibility%253Ashopping%253Aamazon&maxRev=573712

571202-571239 | system​_health.​common​_desktop | cpu​_time​_percentage | ChromiumPerf | mac-10_13_laptop_high_end-perf | load:​accessibility:​shopping:​amazon | +0.019 | +5.7%
-- | -- | -- | -- | -- | -- | -- | --

**Comment by benshayden** [comment]
I'll do another round of debugging as I merge chart-timeseries to master branch.
