### ISSUE TITLE
Perf Dashboard V2: Iterating through groups of alerts via hotkeys

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4547]
As the sheriff, I'm generally going through groups consecutively.

The current workflow tries to be very order agnostic, but if it was a bit more opinionated, it could potentially much more efficient.

Suppose we have a "show the next group" button. Maybe also a keyboard shortcut.
Perhaps we speculatively prefetch the graphs for the next n groups as well.

Maybe add some keyboard shortcuts for "Invalid" and "New Bug". Maybe those keyboard shortcuts even auto-advance to the next group?

I can imagine getting to the point where much of the sheriffing process is just hitting a button, once per group, which either marks the current group as invalid and then advances to the next group, or files a new bug and advances the next group.

____

These thoughts brought to you by the 1500 alert shift I just had.

**Comment by benshayden** [comment]
Keyboard shortcuts are on go/chromeperf-v2-status. I'll bump them up!

**Comment by tdresser** [comment]
I think the speculative prefetch thing could be pretty important here.
A lot of my workflow right now revolves around getting the right graphs loading, especially for groups with large numbers of alerts.

Hard to say though.

**Comment by benshayden** [comment]
[Moved to crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=892948)
