### ISSUE TITLE
Pinpoint: Red X makes it look like failure

### ISSUE THREAD

**Issue by npm1** [catapult-project/catapult#4558]
What's the meaning of the red X in the histograms? Is it just that we're not measuring a specific metric, so there are no applicable histograms to show? In the example below the job passed all runs but I was unsure because the X made it look like a failure:

https://pinpoint-dot-chromeperf.appspot.com/job/14cda53ea40000

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
Sorry about that! The red X doesn't have a meaning in this case, and is just a bug. It will be fixed as part of a larger chart rewrite this quarter.

**Comment by dave-2** [comment]
Fixed!
