### ISSUE TITLE
[📍] Cannot signin to pinpoint despite having an @chromium.org & @google.com account

### ISSUE THREAD

**Issue by pkotwicz** [catapult-project/catapult#4559]
When I try signing in via the "Sign in" button at the top of https://pinpoint-dot-chromeperf.appspot.com/ I see a popup to sign in. After signing in, the "Sign in" button does not disappear. Refreshing the page does not help. Signing in from an incognito tab does not help.

When I try starting a job via the large "+" button I get the error message "User not authenticated"

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
I've had success doing an "Empty Cache and Hard Reload". Would you try and see if that helps?
Open DevTools and hold down the refresh button in Chrome to see the option.

**Comment by pkotwicz** [comment]
Ok, I am able to sign in now.

I had blocked "third party cookies". Enabling "third party cookies" allows to login
