### ISSUE TITLE
[📍] Executions comparison UI

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4560]
## Problem
For perf try jobs with no `comparison_mode`, the chart on the page doesn't show any useful information, because there's no defined metric to look at.
<img width="1067" alt="screen shot 2018-07-19 at 11 06 27 am" src="https://user-images.githubusercontent.com/211662/42961541-e446d3de-8b43-11e8-9d37-9a7fcc14ce3d.png">

Even pass/fail information is better served by the more detailed execution view below it. The only reason we have the chart is so users can click on the points to navigate between the execution details of the two changes.

## Proposed solution
Change the execution details view into a side-by-side comparison view of two adjacent executions. For a bisect job, it will show the currently selected change on the right, and the previous change on the left.

We'll want to re-layout the execution details to make it fit horizontally and make it easier to understand. I'll come up with a prototype for this as well.

@perezju @simonhatch

**Comment by perezju** [comment]
Yes! This would be great.

**Comment by dave-2** [comment]
Done!
