### ISSUE TITLE
[📍] Run a try job dialog includes deprecated bots

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#4561]
For example it includes both `Android Nexus5 Perf` and `android-nexus5`.

@dave-2 @simonhatch

**Comment by dave-2** [comment]
Users may still want to run jobs on the old names for a few weeks after the name is deprecated, so we still support the old names. I would feel comfortable with removing the old names after the perf dashboard data migration ([chromium:865998](https://bugs.chromium.org/p/chromium/issues/detail?id=865998))

**Comment by perezju** [comment]
So I'm confused. What happens today if I run a job under an old name? Does something different happen if I run the same job under the new name?

**Comment by dave-2** [comment]
It's the exact same thing. They're just additional aliases.

The perf dashboard treats them as separate bots, so when sheriffs triage alerts, they may still kick off bisects on the old names. So we need to support that.

**Comment by dave-2** [comment]
Done!

**Comment by dave-2** [comment]
No, I deployed right after landing, so the changes should already have taken effect. Note that the current names on the perf waterfall are inconsistent, with some having capitals/spaces, and others having lowercase/dashes.

Notifications: not yet. We're going to work with ChOps FE in Q4 to more standardize our deployment practices. Ideally, we will even have "deploy on green", automatic deployments when the tests pass.

**Comment by perezju** [comment]
Ah, you are right, I think I got confused between the `Android Nexus5 Perf` and `android-nexus5x-perf` (missed the extra `x`!).

Sorry for the noise.
