### ISSUE TITLE
Have cloud_storage.py use swarming credentials?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4563]
https://cs.chromium.org/chromium/src/third_party/catapult/common/py_utils/py_utils/cloud_storage.py?q=cloud_storage.py&sq=package:chromium&g=0&l=131

So trying to get the luci try server running, think we're down to a gsutil auth issue from the dependancy manager. Specifically, we seem to overwrite the env vars here in cloud_storage.py before calling gsutil. On the swarming bot, we have boto credentials in an env var, is there any way we can just use those? ie. check for SWARMING_HEADLESS: 1 and copy the env like the cros path?

@nedn

**Comment by simonhatch** [comment]
@zeptonaut Also touched the file at some point

**Comment by simonhatch** [comment]
Anybody opposed to be putting up a CL that checks for SWARMING_HEADLESS (an env var that swarming sets), and if that's set just use the current env vars?

**Comment by nedn** [comment]
Nope.

**Comment by simonhatch** [comment]
Long done.
