### ISSUE TITLE
Dashboard: Add support for bytes-per-second units

### ISSUE THREAD

**Issue by mseaborn** [catapult-project/catapult#4570]
The Catapult dashboard currently supports a limited set of units, documented here: https://github.com/catapult-project/catapult/blob/master/docs/histogram-set-json-format.md.  This includes "ms", "sizeInBytes", "J".

I would like to be able to graph values in units of bytes per second -- i.e. data throughput rates.  (More specifically, I would like to display units of megabytes per second or mebibytes per second.)

It looks like Catapult whitelists acceptable units.  If I try to upload a JSON HistogramSet file containing units of "bytesPerSecond_biggerIsBetter", I get a 500 HTTP error.

What is the reason that the Catapult dashboard whitelists the allowable units?  Would it be OK to change it to accept any unit strings?

**Comment by simonhatch** [comment]
@eakuefner

**Comment by eakuefner** [comment]
This is something we've been thinking about for a while, and I spoke to @benshayden about an approach we think is reasonable.

The TBMv2 unit system is actually tied to a bunch of frontend display/conversion logic, and units are also used to determine default bin boundaries for histograms. For example, you can see that sizeInBytes specifies a sane unitScale for memory units here https://github.com/catapult-project/catapult/blob/master/tracing/tracing/base/unit.html#L373. This logic is used in trace-viewer, results.html, and the dashboard.

By the way, we're trying to use Monorail these days for dealing with perf dashboard bugs -- you can use
Report Issue > Report a Perf Dashboard Bug on the perf dashboard to report bugs conveniently in the future. I'll file a Monorail bug about implementing this and refer to it here once filed.

**Comment by benshayden** [comment]
[This is happening here](https://chromium-review.googlesource.com/c/catapult/+/1280722).

**Comment by benshayden** [comment]
This should be done. Feel free to try to upload data with the new units and let me know if they don't look right on v2spa.
