### ISSUE TITLE
Perf Dashboard: No blink_perf.layout_ng data since 2018-08-24

### ISSUE THREAD

**Issue by cbiesinger** [catapult-project/catapult#4578]
Chrome version: 58.0.3029.110 (Linux)
URL: https://chromeperf.appspot.com/

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
none

Please describe the problem:
https://chromeperf.appspot.com/report?sid=b863b7236a5021ab4394e738586a9072959659de2622a2115eae52e7b4cf2b12

That link shows no new data for the blink_perf.layout_ng testsuite since 2018-08-24, even though https://ci.chromium.org/buildbot/chromium.perf.fyi/Mojo%20Linux%20Perf/ had successful runs since then

**Comment by simonhatch** [comment]
So dug into this, a new dashboard was deployed but without the requisite indexes. Those have been updated, and the next upload should work fine. I'll keep this open until I confirm.

**Comment by simonhatch** [comment]
That was quick, new points showing up.

**Comment by cbiesinger** [comment]
Thanks for fixing! Is the data that got uploaded in the meantime lost forever or is there a way to get that back into the chart?

**Comment by simonhatch** [comment]
Unfortunately there's no easy way to reupload these, and we don't preserve them currently on the dashboard. That could be a nice feature to have in the future.
