### ISSUE TITLE
Trace Viewer display thread names as numbers

### ISSUE THREAD

**Issue by maxlgu** [catapult-project/catapult#4584]
Here's a sample trace file. 
https://drive.google.com/file/d/1fTawQUc28jWVI5agfjdunyVBg6WX3jhy/view?usp=sharing

Some of the thread names are displayed as numbers, and metrics cannot be computed because failing to get render processes.

**Comment by maxlgu** [comment]
![screen shot 2018-09-19 at 17 27 27](https://user-images.githubusercontent.com/26091905/45782619-752b6e00-bc31-11e8-81e8-fa48f00b3122.png)

**Comment by maxlgu** [comment]
![screen shot 2018-09-19 at 17 29 16](https://user-images.githubusercontent.com/26091905/45782653-92603c80-bc31-11e8-99f6-c2aa866afbe7.png)

**Comment by benshayden** [comment]
Duplicate: https://bugs.chromium.org/p/chromium/issues/detail?id=886621
