### ISSUE TITLE
pinpoint: continue loading result when in the background

### ISSUE THREAD

**Issue by sadrulhc** [catapult-project/catapult#4588]
pinpoint seems to stop loading the results page when the tab goes in the background. This is a tad frustrating, as often when I will open multiple pinpoint results pages, and go back and forth between these tabs (and other tabs, like crbug etc.). So for each tab, I need to bring it to foreground, wait and stare at the page loading, because it didn't seem to do anything while in the background. It would be useful if the page kept loading the results while it's backgrounded.

@benshayden @piman

**Comment by dave-2** [comment]
This is for results2 for perf tryjobs, right?

**Comment by benshayden** [comment]
I think this is done. Sadrul, please reopen if there's more to do here.
